### ISSUE TITLE
rename apps

### ISSUE THREAD

**Issue by CaqCat** [GrapheneOS/os-issue-tracker#1000]
- rename **GrapheneOS Keyboard** to **Keyboard**

- rename **GrapheneOS Launcher** to **Launcher**

these are the only system apps that contain **GrapheneOS** in the app name

for example, the camera app is named **Camera**
it would be redundant if it was named **GrapheneOS Camera**

- rename **Wireless emergency alerts** to **Wireless Emergency Alerts**

to fix capitalization (only if this doesn't break anything)

**Comment by r3g-5z** [comment]
Not really something we're going to do downstream. These aren't user-facing apps.
