### ISSUE TITLE
improve app icons

### ISSUE THREAD

**Issue by CaqCat** [GrapheneOS/os-issue-tracker#1001]
- GrapheneOS Keyboard
- GrapheneOS Launcher
- SIM Toolkit
- Vanadium
- Wireless emergency alerts

**Comment by einekratzekatze** [comment]
Isnt the keyboard just AOSP? Changing it may cause confusing, because the apps that have an icon are modified or made by graphene

**Comment by thestinger** [comment]
We did make custom icons for all the AOSP apps which are normally visible on the home screen. When we have a decent gallery app replacing the AOSP one, we'll just move over our icon to it. Same can be done for the keyboard.

**Comment by r3g-5z** [comment]
Thes aren't user facing apps, and we already have our own icon for Vanadium in use while still following the upstream modern design of Chromium. We only want to change icons with ours that are user-facing such as what we did with AOSP Gallery and AOSP Calculator.
