### ISSUE TITLE
High battery usage of GmsCompat

### ISSUE THREAD

**Issue by aut0** [GrapheneOS/os-issue-tracker#1003]
Hi,

Recently I have had issues with high battery usage. The system battery app identifies "GmsCompat" as the culprit. I use sandboxed play services. I have tried to remove the three Google apps from the phone and reinstall the version provided on the website to make sure I didn't break it through an update. However, that did not solve the issue. All three Google Apps have network permission. Is there a way to debug this further?

Thank you :)

**Comment by thestinger** [comment]
There isn't an indication that this is a bug. You could simply be using apps which you've given background location and keep the GPS active, etc.

**Comment by aut0** [comment]
I raised it in the Matrix chat, but the only suggested solution was to remove all apps one-by-one and see if this solves an issue. Is there any way to generate debug information without going through this tedious procedure. I might add that this is a new issue on my phone. I have been using sandboxed play services for a while and this just started a couple of days ago.

Thanks

**Comment by aut0** [comment]
Fwiw, uninstalling play services "resolved" the issue

**Comment by lippling** [comment]
I have exactly the same problem.
After updating GrapheneOS a few days ago, GmsCompat drains the battery. Before updating everything was ok.

**Comment by C42EFF4Lbb54dwg** [comment]
> I have exactly the same problem. After updating GrapheneOS a few days ago, GmsCompat drains the battery. Before updating everything was ok.

Same problem here. Happy to provide logs.

**Comment by thestinger** [comment]
We need to know if you're using apps which use geolocation via the Google Play API. Those apps are now redirected to the GmsCompat implementation of the API by default. You can disable redirection to see if that helps.

**Comment by C42EFF4Lbb54dwg** [comment]
> We need to know if you're using apps which use geolocation via the Google Play API. Those apps are now redirected to the GmsCompat implementation of the API by default. You can disable redirection to see if that helps.

Yes, I am using apps which are using geolocation via the Google Play API. The only app which requires Google Play Services AND which I allowed background location service to is Tasker. Other apps which request location as and when I need them are Uber, Uber Eats, my banking app, and Waze (from my work profile). Switching off work profile had no impact on my battery life.

> Also worth noting is that battery usage from Play services is likely attributed to GmsCompat now. Do you actually have decreased battery life, or are you just seeing battery usage attributed to GmsCompat?

I actually see significant decreased battery life. Previously, my battery would last 15+ hours. With the latest update, it is less than 10 hours (if I am lucky) . I have removed Play Services and it is back to the former. 

I will reinstall play services and disable redirection to see if it helps.

**Comment by C42EFF4Lbb54dwg** [comment]
> > We need to know if you're using apps which use geolocation via the Google Play API. Those apps are now redirected to the GmsCompat implementation of the API by default. You can disable redirection to see if that helps.
> 
> Yes, I am using apps which are using geolocation via the Google Play API. The only app which requires Google Play Services AND which I allowed background location service to is Tasker. Other apps which request location as and when I need them are Uber, Uber Eats, my banking app, and Waze (from my work profile). Switching off work profile had no impact on my battery life.
> 
> > Also worth noting is that battery usage from Play services is likely attributed to GmsCompat now. Do you actually have decreased battery life, or are you just seeing battery usage attributed to GmsCompat?
> 
> I actually see significant decreased battery life. Previously, my battery would last 15+ hours. With the latest update, it is less than 10 hours (if I am lucky) . I have removed Play Services and it is back to the former.
> 
> I will reinstall play services and disable redirection to see if it helps.

Just an update - disabling redirection solved the draining issue. 10 hours in, only 16% down since last full charge.

**Comment by thestinger** [comment]
It's likely you're using apps which use network-based location via Play services, which is low power use. Our redirection feature implements it via GNSS which is much higher power use. Eventually we'll have a "network" location service based on a local database. This is probably working as intended for now.

**Comment by thestinger** [comment]
https://github.com/GrapheneOS/os-issue-tracker/issues/1039 has been opened about improving the UX.
