### ISSUE TITLE
Allow contactless payments from work profile

### ISSUE THREAD

**Issue by gordonel** [GrapheneOS/os-issue-tracker#1004]
Some banking apps provide a Google-free contactless payment service, but when the app is installed in a work profile and contactless payment is enabled in the app and in settings, the payments don't work at all, as if nothing is set up. Settings > Connected Devices > Connection preferences > Contactless Payments is greyed out

**Comment by thestinger** [comment]
I think this works the same as the stock OS / AOSP and we don't plan to change it. Work profiles are not really meant to be used how people are using them and are not going to be the focus of our profile improvements.
