### ISSUE TITLE
Allow customizable extra functions for nav buttons

### ISSUE THREAD

**Issue by LukeAbellSmith** [GrapheneOS/os-issue-tracker#1006]
Previously I ran Lineage OS. It had the option to set double-tap and long-press actions for the nav buttons, allowing quick access to extra functions.
Two examples:
-A double tap or long press (user selectable, they don't have to be the same) could be set to go to the most recent previous app, just like the slide gesture. 
-Holding Home would lock the screen - especially nice for devices where the fingerprint reader is the home button. This way we can use a soft key instead of wearing out the lock button.

If it's any help, here are the LOS github, a related LOS PR, and a thread mentioning the feature.
https://github.com/LineageOS
https://review.lineageos.org/c/LineageOS/android_packages_apps_CMParts/+/113451
https://forum.xda-developers.com/t/long-press-menu-button-square-for-last-app-lineage-os-14-1.3560356/

**Comment by thestinger** [comment]
GrapheneOS uses gesture navigation by default and we consider button navigation to be a legacy feature. It's not going to have features added to it.

> -A double tap or long press (user selectable, they don't have to be the same) could be set to go to the most recent previous app, just like the slide gesture.

Slide gesture works much better since you can cycle through the history of recently used apps.

> -Holding Home would lock the screen - especially nice for devices where the fingerprint reader is the home button. This way we can use a soft key instead of wearing out the lock button.

Don't really see the point of this. Power buttons don't normally get at all worn out in the normal life of a Pixel phone.

**Comment by thestinger** [comment]
If we add enhancements, it will be to gesture navigation. There are far higher priorities.

**Comment by Zanthed** [comment]
This isn't as trivial to implement as it looks.

CMParts (now known as LineageParts) is apart of LineageOS's massive SDK (lineage-sdk). We're obviously not going to implement that into our OS and the amount of time it would take to pick apart their SDK and LineageParts and create a standalone patch is way beyond the scope of this OS.

**Comment by LukeAbellSmith** [comment]
Fair enough

**Comment by s00se** [comment]
FWIW, you can tie the "assistant app" to a separate application to handle turning off the screen, so you can swiping in from corners and trigger an action using Tasker, for example. There is also a quick swipe down to bring down the notification shade when using gestures. 

These 2 features have allowed me to move from buttons to gestures fairly seamlessly.

**Comment by LukeAbellSmith** [comment]
Thanks for the tip, I'll consider it.
