### ISSUE TITLE
PlugShare App - EVs Searching and tracking

### ISSUE THREAD

**Issue by epimazzo** [GrapheneOS/os-issue-tracker#1008]
[This is a well-known worldwide EV application](https://play.google.com/store/apps/details?id=com.xatori.Plugshare&hl=en&gl=US) that helps you find, route, and discover nearby electric poles and charges worldwide. The app keeps requesting service locations even outside GOS rerouting OS API feature. It just works when you enable Google Play Services to "allow all the time" option and disable Sandbox rerouting OS API, which is a huge privacy flaw. 

The application didn't work or have any functionality without its primary purpose working. 

Thanks
Eddie

**Comment by epimazzo** [comment]
> > The app keeps requesting service locations even outside GOS rerouting OS API feature
> 
> Not clear what you mean.

Hi there,
I don't think it's a GOS issue or even a security flaw. That resides more on the app side itself. Sorry if I didn't describe it properly. This app only works when you disable OS API rerouting feature on Sandbox Google Play together with enabling the Google Play service set to "allow all the time" function. Otherwise, you can forget it. 
By knowing that, is there any workaround to fix it? 
Thanks

**Comment by jann-0** [comment]
Could you please join the official chat rooms as given [here](https://grapheneos.org/contacts#community)
and discuss the issue there? The issue tracker is  for discussing actual issues with any OS components.

**Comment by muhomorr** [comment]
> This app only works when you disable OS API rerouting feature on Sandbox Google Play together with enabling the Google Play service set to "allow all the time" function. Otherwise, you can forget it.
By knowing that, is there any workaround to fix it?

I have tested the PlugShare app, it works fine when "Reroute location requests to the OS APIs" option is enabled.
Have you tried testing outdoors? It looks like your device was unable to obtain a GPS lock.

**Comment by epimazzo** [comment]
> 

The outdoor thing is definitely a real point of discussion. I'm indoor. I'll again test outside following your success rate.  Thanks for sharing your experience and for testing out the app.
