### ISSUE TITLE
Prevent Apps with disabled network from DNS requests

### ISSUE THREAD

**Issue by OpenSourceGhost** [GrapheneOS/os-issue-tracker#1010]
Not sure if this is a bug, but Apps with disabled network permissions can't use network, but they can and do invoke Android DNS system to make connections to domains those apps need for network functions. The apps themselves are prevented from using networkg, but DNS requests go through.  For exaple, if I block network access to WhatsApp, I still Android sending DNS upstream to WhatsApp domains when I launch WhatsApp.

A bit off-topic, but are there plans to create 5G-only option (similar to LTE-only option)?

**Comment by flawedworld** [comment]
>Not sure if this is a bug, but Apps with disabled network permissions can't use network, but they can and do invoke Android DNS system to make connections to domains those apps need for network functions. The apps themselves are prevented from using networkg, but DNS requests go through. For exaple, if I block network access to WhatsApp, I still Android sending DNS upstream to WhatsApp domains when I launch WhatsApp.

That's not a bug. That's the intent filter verification process. https://grapheneos.org/usage#app-link-verification

>A bit off-topic, but are there plans to create 5G-only option (similar to LTE-only option)?

We will likely do this once 5G modem implementations are more mature and once 5G SA networks are more commonly deployed as most networks are in NSA mode currently and rely on LTE for as a backhaul for traditional telecoms which consequently would break traditional telecoms for almost all our users if they enabled a 5G only mode. 5G SA is only currently in parts of Singapore and some cities in China as far as I am aware. We could potentially enable it only for those regions in future until 5G SA is in common deployment.
