### ISSUE TITLE
No meta data on car stereo with Google Pixel 3a

### ISSUE THREAD

**Issue by jsarkari** [GrapheneOS/os-issue-tracker#1011]
There is no meta data showing on my Ford Mondeo car stereo since installing Graphene OS on my Pixel 3a.  It has the latest build currently: SQ1A.220205.002.2022021721

I have tried various music apps and the same issue.

I have a Oneplus 9 Pro and there are no issues with that albeit with stable Android 12 build.

Music plays but cannot see what is playing (meta data) but can skip, pause etc.

**Comment by thestinger** [comment]
It's unlikely that anything will happen with this since it's almost certainly an upstream issue. It would help to know if it also occurs with the stock OS on the Pixel 3a. 3a may simply not support what's required by that hardware.

**Comment by jsarkari01** [comment]
Thanks for getting back to me on this issue. Yes I have taken it back to Android 12 with the latest production version of security updates and interestingly music is not shown either.

So tested my Oneplus 9 Pro and no issues whatsoever.

I am replacing the 3a with the 6 Pro as it is higher spec and so be a lot better on Graphene OS also.
