### ISSUE TITLE
SMS/MMS app: Feature request for marking messages as unread

### ISSUE THREAD

**Issue by Kembolowski** [GrapheneOS/os-issue-tracker#1012]
I am missing the ability to mark an already received message as unread again.

A basic feature would be to select a conversation and mark it as unread like provided by other messaging clients. As a result the conversation is highlighted with a bold font.

An even better enhancement would be to select and mark single messages as unread similar to what is possible with email clients.

**Comment by thestinger** [comment]
We don't actively develop the SMS/MMS app. It's the AOSP Messaging app. We don't plan to add assorted features, especially frills like this. SMS/MMS are insecure and should be avoided. It's not a bad thing if users are pushed to use proper secure messaging.

**Comment by thestinger** [comment]
SMS/MMS is for legacy use only and you should be doing everything you can to phase it out.
