### ISSUE TITLE
'Failed to check for updates' in airplane mode

### ISSUE THREAD

**Issue by Kembolowski** [GrapheneOS/os-issue-tracker#1013]
When my device is in airplane mode I'm getting the following error notification after a while:

**Failed to check for updates**
An error occured checking for the latest update. The update system will try again soon.
`Unable to resolve host "releases.grapheneos.org": No address associated with hostname`

I'm using NetGuard which keeps a permanent VPN connection open, even in airplane mode.
It looks to me that the update service does not check whether any network interface is enabled. Instead it interprets the VPN connection as being connected with the internet.

**Comment by thestinger** [comment]
NetGuard should be marking the network as down.
