### ISSUE TITLE
GOS PHONE app issue

### ISSUE THREAD

**Issue by hjangadi** [GrapheneOS/os-issue-tracker#1014]
I am using GOS  on Pixel 6, I have issue of not seeing any mobile phone missed calls on GOS phone app. However I can see landline missed calls and other apps all notifications like WhatsApp miss calls are fine.

However I tried replacing with Google phone app but it's same issue. 
Hope this issue will be fixed in next release?

Thanks,
Harsha

**Comment by thestinger** [comment]
This sounds like a carrier-specific issue and may be an issue on there end. There are no known issues with this kind of thing in GrapheneOS.

**Comment by hjangadi** [comment]
> This sounds like a carrier-specific issue and may be an issue on there end. There are no known issues with this kind of thing in GrapheneOS.

**Comment by hjangadi** [comment]
Let me try changing my carrier and try tomorrow morning. I will let you know. 
If it is carrier then I wouldn't have seen only landline missed call.

**Comment by thestinger** [comment]
I don't quite understand what you mean by that. Do you mean that people calling you from a landline leaves you a missed call notification, but people using a cell phone doesn't? Which carrier is the side calling you using? Are you sure that you actually receive the call? Does it ring?

**Comment by hjangadi** [comment]
> I don't quite understand what you mean by that. Do you mean that people calling you from a landline leaves you a missed call notification, but people using a cell phone doesn't? Which carrier is the side calling you using? Are you sure that you actually receive the call? Does it ring?

**Comment by hjangadi** [comment]
I mean no issue with getting ring or receiving calls when I get ring. Issue is when I don't pickup my phone when I am away, I don't see missed call notification on the screen or of dot on the phone app. Where as other apps are fine e.g of someone calls me on what's app as miss call that I see when I see my phone later. Hope you got what I mean now?

**Comment by thestinger** [comment]
This cannot be reproduced and is likely a carrier issue.
