### ISSUE TITLE
[Feature Request] Add support for grayscale display and tile in swipe-down menu to toggle

### ISSUE THREAD

**Issue by frostelk** [GrapheneOS/os-issue-tracker#1016]
I used the grayscale display option a lot on my old phone before switching to GrapheneOS and would really like to have the option to quickly turn it on and off like the Night Light or Extra Dim tiles. A few studies (e.g., [1](https://doi.org/10.1080/03623319.2020.1737461), [2](https://doi.org/10.1007/s12144-021-02020-y)) have shown that grayscale display can reduce phone use and may help people who have unhealthy phone habits. In addition, I think grayscale display is well-aligned with the GrapheneOS ethos as a tool to resist the attention economy (though obviously a minor bandaid solution to a much larger problem). Personally, I find grayscale to be more effective for reducing eye strain than Night Light as well. My intuition is that it would not be overly difficult to implement but I could be wrong.

**Comment by flawedworld** [comment]
Grayscale is supported.  Settings -> Accessibility -> Text and Display -> Colour correction

**Comment by thestinger** [comment]
They seem to be asking for the tile rather than the option as a whole.

**Comment by thestinger** [comment]
They seem to be asking for a quick tile rather than the option as a whole.

**Comment by flawedworld** [comment]
Ah. AOSP currently offers holding the 2 volume buttons at the same time or using the accessibility button as an option to toggle this.

**Comment by frostelk** [comment]
> Grayscale is supported. Settings -> Accessibility -> Text and Display -> Colour correction

Ah great, thank you for this! I had expected to find it in Settings -> Display -> Colors, my mistake. As a side note, I see that in the Colors menu there are three settings, one of which is missing a description ("Natural", blank option, "Adaptive"). I wasn't going to open an issue since it is not consequential for me but figured I would mention it in case it has not been noticed yet.



> Ah. AOSP currently offers holding the 2 volume buttons at the same time or using the accessibility button as an option to toggle this.

Fantastic, I was not aware of the option to toggle with the volume controls. A quick tile is what I was envisioning, but this will work just as well for me.

Thank you for the quick response!

**Comment by flawedworld** [comment]
@frostelk Which device did you observe the blank option on?

**Comment by Flash1232** [comment]
Blank middle option present on my P6 as well

**Comment by thestinger** [comment]
If there's an issue with that on Pixel 6, a new issue should be filed.

**Comment by frostelk** [comment]
It was on Pixel 6 Pro, it looks like a new issue has been opened #1024 I will add a screenshot there
