### ISSUE TITLE
[Feature request] GrapheneOS Launcher grid size

### ISSUE THREAD

**Issue by BluePixel4k** [GrapheneOS/os-issue-tracker#1019]
In the Android 12 GrapheneOS launcher, you can customize the grid, but unfortunately there are only quite a few options.
2x2, 3x3, 4x4 and 5x5.

It would be great if there were more options like 5x6 and 5x7.

At the same time it would be nice to reduce the gaps in the app drawer. This would have the advantage that you can see more apps at once.

It has some similarity to this closed issue: #523

**Comment by Zanthed** [comment]
We'll see if Android 12L expands them as 12L is going to get more themeing and customisation options that stock OS has, otherwise we can re-open it as a feature request.

**Comment by BluePixel4k** [comment]
In the meantime, GrapheneOS is at Android 12L, but the launcher looks like you cannot make any further settings in this regard.
Or has the GrapheneOS launcher not been fully updated yet?

**Comment by thestinger** [comment]
It's updated.

**Comment by BluePixel4k** [comment]
Okay, can this issue then be reopened as a feature request?

**Comment by BluePixel4k** [comment]
> We'll see if Android 12L expands them as 12L is going to get more themeing and customisation options that stock OS has, otherwise we can re-open it as a feature request.

Can the issue be reopened again please?

**Comment by MaxHillebrand** [comment]
Would be really nice to have this.

**Comment by AD-Wright** [comment]
Now that we're on Android 14, any possibility of reopening this feature request?

**Comment by CocolinoFan** [comment]
Now that we're on Android 17, any possibility we could have more options for grid sizes? 🙂

**Comment by rusty-snake** [comment]
#8542
