### ISSUE TITLE
[Feature request] Audio equalizer

### ISSUE THREAD

**Issue by BluePixel4k** [GrapheneOS/os-issue-tracker#1020]
The Pixel 5 does not have the best speaker sound, but they can be improved with an equalizer. 
Currently, I use AudioFX, which is also available by default in LineageOS as a system app. Unfortunately, this has the disadvantage that the equalizer cannot improve everything. For example, not the YouTube app.

It would be great if GrapheneOS also comes with an equalizer as a default, thanks.

**Comment by Zanthed** [comment]
GrapheneOS already has an equaliser provided by AOSP. It just isn't available as a normal user-facing app. An app has to call it in someway. For example, in Spotify's settings and Apple Music's settings there is an Equaliser settings button which takes you to the system default equaliser.

**Comment by BluePixel4k** [comment]
Thank you, I had already discovered the equalizer via Spotify a while ago, but it didn't work then. 
Somehow it is sometimes a bit buggy. Sometimes I can not adjust the frequencies and then suddenly it works.

Can it be that you have to activate and adjust the equalizer but for each app individually and there is no setting for all apps at the same time?
That means you can not adjust the sound of apps that do not have the function?

Would be great if you could also find the equalizer via the launcher as a normal app :)

![Equaliser_bug](https://user-images.githubusercontent.com/77979781/155971478-86de24ac-c62a-4539-8c34-0f752a531b5d.png)
![Equaliser](https://user-images.githubusercontent.com/77979781/155971495-fd518ad0-6e96-4a9a-9916-2f6a34bb65ff.png)

**Comment by flawedworld** [comment]
The OEM (Google) did not give it many user facing options. Same behaviour is seen on stock.

**Comment by BluePixel4k** [comment]
Hmm that's a shame. Would it be possible if to replace the stock equaliser?
