### ISSUE TITLE
Investigate solution to restricting VVM SMS messages to system apps only

### ISSUE THREAD

**Issue by flawedworld** [GrapheneOS/os-issue-tracker#1022]

**Comment by thestinger** [comment]
I'm not sure this really makes sense. There are a bunch of other uses for SMS too. It's just what the SMS permission provides. SMS itself is also highly insecure, as is VVM in practice.

**Comment by Zanthed** [comment]
We could just expand the SMS security documentation to include things like VVM security, Wi-Fi calling security, etc
