### ISSUE TITLE
Brightness slider using white icon difficult to see against the 'GrapheneOS blue' color accent

### ISSUE THREAD

**Issue by s00se** [GrapheneOS/os-issue-tracker#1023]
The white icon against the 'GrapheneOS blue' color accent in quick settings is difficult to see due to reduced contrast, it sorta looks weird among the rest of the "black on light blue" elements in quick settings too.

![quicksettings](https://user-images.githubusercontent.com/95649696/156063526-52f4e616-90a5-451d-9133-16a92fdcd45c.png)

The icon is set to black once the user starts adjusting the brightness and it's must easier to see.

![adjustingquicksettings](https://user-images.githubusercontent.com/95649696/156063607-c0431993-3e2f-485b-9643-eecebf2c45d2.png)

Can it be updated to make it easier to see and less visually distracting?

**Comment by jorgeluiscarrillo** [comment]
This is an upstream bug. Sometimes a reboot will fix it. Hopefully will be fixed in 12L.

**Comment by flawedworld** [comment]
As above.

**Comment by s00se** [comment]
Interestingly, this doesn't appear to be an issue in the latest build just released or whatever is required to trigger the bug hasn't happened yet.

![Screenshot_20220301-212315_1](https://user-images.githubusercontent.com/95649696/156294781-afadc919-59cb-4f23-a08d-6f6066ef905c.png)
