### ISSUE TITLE
Investigate missing/incorrect display overlay on Pixel 6

### ISSUE THREAD

**Issue by flawedworld** [GrapheneOS/os-issue-tracker#1024]

**Comment by flawedworld** [comment]
May affect other devices, solely cosmetic.

**Comment by Zanthed** [comment]
The missing colour option happens on my Pixel 6 Pro as well.

**Comment by frostelk** [comment]
Screenshot on Pixel 6 Pro:

![missing_overlay](https://user-images.githubusercontent.com/84259278/156477078-311c2709-034a-4da5-b1c0-ef0874643891.jpeg)
