### ISSUE TITLE
Feature request: Option to always boot with flightmode enabled

### ISSUE THREAD

**Issue by gsture** [GrapheneOS/os-issue-tracker#1027]
It would be nice to have an option to always boot with flightmode enabled. This way you will have a choice after a reboot to go online, stay offline or only enable WiFi for example. 

Also the phone can not go online untill you succesfully unlock the phone with password after boot (phone now connects instantly even when phone is never unlocked). 

I think this would be nice to have and could have some security benefits as well. It would combine well with automatic reboot enabled.

**Comment by thestinger** [comment]
Unclear what you mean. It's already persistent.

**Comment by thestinger** [comment]
I don't understand the purpose of making airplane mode get re-enabled each boot, if that's what you're requesting. I don't see a good reason to implement it.

**Comment by patienttruth** [comment]
Here's a scenario.

Network is on, battery dies. Physical location changes to one that would only be visited with device in airplane mode, and battery is then charged.

Its not practical to change location before turning on phone which would initiate network connectivity upon boot.

Giving an option to boot without network seems like a good solution.

Is this scenario not a valid concern?

**Comment by GH2204** [comment]
Yeah,
this could be a nice additional or temp. solution on my request #1289 too.
