### ISSUE TITLE
Inconsistent displaying of system apps in Sensors permission manager

### ISSUE THREAD

**Issue by mariobrostech** [GrapheneOS/os-issue-tracker#1028]
Hi,

This is quite an inconsequential bug, but I wanted to bring it up in case you were unaware.

When going to Settings and searching for Sensors, tapping on the first result displays a permission manager. However, even when system apps are supposed to be hidden (as they are by default), they will still show in the list of allowed apps. When disabled, however, they don't show up in the list of disabled apps.

As a simple test to demonstrate this, go to Settings, search for Sensors, and tap on the Sensors option from the list. Then, observe that system apps are being displayed by default, even when they shouldn't be. For example, tapping on GrapheneOS Launcher and denying its sensor permission will make it completely disappear from the list (including from the "Not allowed" list). The only way to make it appear again is to tap the "Show system" option in the hamburger menu. This reveals it in the "Not allowed" list, and the user can then select it to re-enable its permissions.

Since the Sensors permission manager is exclusive GrapheneOS, I am unable to verify if this is a GrapheneOS-specific or AOSP issue. However, given the fact that other permission managers, such as Microphone and Camera, seem to be working fine, that would indicate an issue somewhere in the GrapheneOS code.

I would appreciate if anyone could validate these findings or could point me in the right direction to determine a fix.

Thanks in advance!

**Comment by thestinger** [comment]
It works the same way as other permissions and works the same way as AOSP. It's not a bug but rather it doesn't mean what you think. There is a generic permissions manager, not a sensors permission manager, and it's not specific to GrapheneOS.

**Comment by thestinger** [comment]
We know that the Android permission manager isn't designed as well as it could be for system apps. It's not something that was made by GrapheneOS and is in no way specific to Sensors. In order to make a feature request in this area, you'll need to be aware of the current situation and what's already planned.

**Comment by mariobrostech** [comment]
Ok, thanks for the clarification!
