### ISSUE TITLE
Network location provider (Google) not working with location rerouting disabled

### ISSUE THREAD

**Issue by UnmovableCheddar** [GrapheneOS/os-issue-tracker#1029]
On Pixel 6 pro, I've got:

- Reroute location requests to OS - unchecked
- Wifi enabled
- Bluetooth enabled
- Wifi scanning allowed
- Bluetooth scanning allowed
- Google Location Accuracy - checked
- Google Play Services permissions - Precise Location, Nearby devices, Network, Sensors, SMS
- 
My Location (com.mirfatif.mylocation) app shows Network location as "Not Supported", Google Maps fails to get location indoors, while it acquires location using network scanning on stock.

logcat didn't show anything useful. The only potentially relevant messages I've got are:
```
GCoreUlr: Received location statuses too frequently: [NetworkLocationStatus: Wifi status: 2 Cell status: 0...
```
and multiple instances of:
```
WifiService: Failed to start scan
```

What's also interesting is that I see "potential issues" with geolocation entry whenever rerouting is disabled, and when I click on it, it shows 2 entries - "Always-on Wi-Fi scanning is allowed" and "Always-on Bluetooth scanning is allowed"

**Comment by thestinger** [comment]
> What's also interesting is that I see "potential issues" with geolocation entry whenever rerouting is disabled, and when I click on it, it shows 2 entries - "Always-on Wi-Fi scanning is allowed" and "Always-on Bluetooth scanning is allowed"

That's expected. It gives suggestions.

**Comment by thestinger** [comment]
> Precise Location

You aren't clarifying if you allowed background access.

**Comment by UnmovableCheddar** [comment]
> You aren't clarifying if you allowed background access.

Yes. Play services is allowed to access precise location all the time

**Comment by thestinger** [comment]
Did you install Google Maps *after* you had installed Play services? It needs to be installed afterwards.

GrapheneOS itself doesn't have network location. If an app is using the OS location API, it won't get network location. GrapheneOS doesn't use Play services itself like the stock OS.

**Comment by UnmovableCheddar** [comment]
> Did you install Google Maps after you had installed Play services? 

Yes, every item in app repository client was installed on device before everything else, play store was initialized properly by signing in (still signed in) and Google Maps was installed directly from play store. No permission (e.g. network) was removed from any app.

Also important to note: only single profile is used on device.

[2022021721](https://grapheneos.org/releases#2022021721) build was used to setup GOS. Currently on [2022022818](https://grapheneos.org/releases#2022022818) and both of these builds produced same results.

As rerouting was enabled when Google Maps was first installed and was disabled after installation, I have tried reinstalling Google Maps just now with rerouting disabled before installation, to rule out the possibility of this playing a role and got same results.

**Comment by thestinger** [comment]
com.mirfatif.mylocation uses the OS location, not Play services. GrapheneOS itself doesn't have network location.

**Comment by thestinger** [comment]
Play services location (non-redirected) not working as well is a new issue.

**Comment by thestinger** [comment]
Play services location (non-redirected) not working as well as it did originally is a new issue.

**Comment by thestinger** [comment]
This has been substantially improved for the next release.
