### ISSUE TITLE
Do Not Disturb prevents notifications entirely

### ISSUE THREAD

**Issue by char-cole** [GrapheneOS/os-issue-tracker#1032]
I'm not sure if this is an intended feature or not, but when DND is active, all notifications in the pulldown tray are hidden. Even existing ones. On Android I recall that not being the case, if would silence all alerts & hide banners but I could still check notifs when I wanted to.

**Comment by kazigk** [comment]
AOSP behaves the same. This is how DnD mode works.

You can change this behaviour in Settings -> Notifications -> Do Not Disturb -> Display options for hidden notifications.
