### ISSUE TITLE
Re-entering password "for additional security" not possible as keyboard does not open -> locked out

### ISSUE THREAD

**Issue by codethief** [GrapheneOS/os-issue-tracker#1033]
This morning right after waking up I ran into a weird issue: When attempting to unlock my phone (Pixel 5, running the latest GrapheneOS version) via fingerprint, I was asked to re-enter my password "for additional security". But the keyboard did not open up – the whole screen stayed blank with just the password input field at the top but without any way to actually enter it. (Interestingly, the blue emergency button was gone as well and I could only see the label "Emergency call" "floating" on the screen and it didn't seem to respond to my taps.) Basically I was locked out of my own phone.

I was relieved to see that after rebooting the keyboard did show up again and I could access my phone.

I apologize that I can't provide any debug logs or anything. I still thought I would report this bug as it seemed quite important and, in fact, dangerous. (What do you do if you urgently need your phone or, even worse, need to do an emergency call?)

Please let me know if I can provide any more info that might be of help.

**Comment by thestinger** [comment]
There's already an issue filed about a similar problem and this has to be assumed to be the same one. It would have been possible for you to work around it if it wasn't frozen. No way for us to debug this or get more information now.

https://github.com/GrapheneOS/os-issue-tracker/issues/467
