### ISSUE TITLE
Contacts disappear from Phone

### ISSUE THREAD

**Issue by jaxkeiser** [GrapheneOS/os-issue-tracker#1034]
I have the latest version of GrapheneOS stable on a Pixel 4a and contacts in the default GrapheneOS Contacts App will sporadically disappear.

**Comment by thestinger** [comment]
You must have a device manager or something else. This isn't an issue with the OS in the default configuration.

**Comment by thestinger** [comment]
More details required if you think this is an issue with the OS. First you need to make sure you don't have a non-default launcher, any device manager, accessibility service, etc.

**Comment by jaxkeiser** [comment]
Can you explain how I can check for these things?

**Comment by thestinger** [comment]
Please ask for support in our Matrix chat room.

https://grapheneos.org/contact#community

**Comment by thestinger** [comment]
Link to the issue there so people have context.
