### ISSUE TITLE
Implement battery usage blaming for GmsCompat via AppOps

### ISSUE THREAD

**Issue by flawedworld** [GrapheneOS/os-issue-tracker#1039]

**Comment by caveman1973** [comment]
In issue #1003 they say about disabling redirection to fix the issue. How do I do that?

**Comment by thestinger** [comment]
This issue is about changing GmsCompat so that the power usage is blamed on the apps using the location API rather than GmsCompat. It's not about power usage itself but rather the UI showing what's using it.

**Comment by thestinger** [comment]
I suggest reading https://grapheneos.org/usage#sandboxed-google-play-configuration.

**Comment by thestinger** [comment]
Not required anymore.
