### ISSUE TITLE
Pixel 6 Pro -- Battery usage graph is clipped

### ISSUE THREAD

**Issue by lbdroid** [GrapheneOS/os-issue-tracker#1040]
System Settings --> Battery --> Battery usage

At the top, there is a graph that is supposed to show the battery level since the last full charge, but it only shows for the previous few minutes.

Screenshot attached shows the battery usage graph starts "13 min. ago". The phone has been unplugged for over 3 hours at that point, so the chart should show 3+ hours worth of battery level logging. Also note that the listed items "Mobile network standby" and "Screen" are showing 19 and 43 minutes.

![Screenshot_20220308-082847](https://user-images.githubusercontent.com/3372230/157248744-04431550-c380-4387-a511-0ca8fc00b1c1.png)

**Comment by thestinger** [comment]
This is the same as https://github.com/GrapheneOS/os-issue-tracker/issues/892.

**Comment by thestinger** [comment]
May be resolved by 12L, but that's likely going to be somewhat delayed for the Pixel 6 and 6 Pro.
