### ISSUE TITLE
Inverse Icons for Dark Mode

### ISSUE THREAD

**Issue by SenorFusion** [GrapheneOS/os-issue-tracker#1041]
The new icon sets from #999 and #1001 look fantastic.

However, in dark theme they are very bright and pretty jarring, especially when there are a bunch in the app drawer.

Would it be possible to invert them for Dark Theme?  Simply flip the icon design white for black and black for white.

This could be happen automatically when Dark Theme is selected.

This seems more in line with the design of Dark Theme: Dark Background, Light Text.

I understand themes is a larger issue for Android 13, but this would be nice in between now and then.

Thanks!

**Comment by empratyush** [comment]
#1408  should fix the issue.
