### ISSUE TITLE
Dark theme/ Light theme profile switching issue.

### ISSUE THREAD

**Issue by Pauler221** [GrapheneOS/os-issue-tracker#1042]
Having the dark theme enabled in the owner profile then switching to another profile which has a light theme enabled and switching back to the owner profiles makes folders, multitasking and search in the app drawer appear white (maybe also other elements are affected). 

Also the app drawer has a dark font under all of the apps names so it makes it hard to read. A reboot solves the issue. 

Basically all the colors get messed up when switching from owner (dark theme enabled) to another profile (white theme enabled) and switching back to owner.

**Comment by Pauler221** [comment]
Device model: Pixel 4a
OS version: 12 (beta channel, latest update)

**Comment by Zanthed** [comment]
This is a known upstream bug that we can't really do anything about. It has been an issue since Android 12 that should have been fixed in 12L by AOSP.
