### ISSUE TITLE
Lockscreen issue

### ISSUE THREAD

**Issue by Pauler221** [GrapheneOS/os-issue-tracker#1044]
After locking the screen and pressing the power button again the homescreen wallpaper appears and nothing else. Pressing the power button again two times fixes this. I don't know how to reproduce this. It happens from time to time.

**Comment by thestinger** [comment]
Need to know the OS version and device model.

**Comment by Pauler221** [comment]
Device model: Pixel 4a
OS version: 12 (beta channel, latest update)

**Comment by thestinger** [comment]
Unable to reproduce this. Which version are you on specifically? (build number)

Have you reproduced it on the latest version?

**Comment by flawedworld** [comment]
May security update fixed some issues on the lockscreen, please try and reproduce it there.

**Comment by flawedworld** [comment]
Closed, tell us if this is still an issue.
