### ISSUE TITLE
Homescreen apps flickering through foreground app while multitasking

### ISSUE THREAD

**Issue by Pauler221** [GrapheneOS/os-issue-tracker#1045]
Using the gesture navigation to switch from one app to another (multitasking by swiping left or right on the very bottom of the screen where the while "home button line" is) makes apps that are on the homescreen occasionally flicker through the multitasking apps.

This only happens from time to time but pretty often. I don't know how to trigger it.

Device model: Pixel 4a
OS version: 12 (beta channel, latest update)

**Comment by Pauler221** [comment]
This might be related to #1042 meaning that it only happens when having switched from the owner profile to a secondary profile with a different theme enabled and switching back to owner again without rebooting. 

I will try to see if this issue still occurs without having switched to a different profile during the up time of the device.

**Comment by Pauler221** [comment]
Homescreen apps also clipping through without having switched to other profile and back during device up time.

**Comment by robovoice1** [comment]
Also with Pixel 6 pro and 3 point navigation on latest beta channel release.

**Comment by flawedworld** [comment]
Please tell us if this is still an issue.

**Comment by mainrs** [comment]
> Please tell us if this is still an issue.

Is there a fix already available that I can test? I’m on stable rn.
