### ISSUE TITLE
Unlocking via fingerprint makes sound but black screen still persists for a second

### ISSUE THREAD

**Issue by Pauler221** [GrapheneOS/os-issue-tracker#1046]
Unlocking the device with a fingerprint without turning on the screen first (by pressing the power button) makes unlocking sound but the screen still stays black for around 1.5 seconds. This didn't happen before the update.

Device model: Pixel 4a
OS version: 12 (beta channel, latest update)

**Comment by w1bsb** [comment]
I am having the same issue with mine. I also noticed the unlock sound seems to stutter for a quick second, whereas pushing the power button to bring up the lock screen and then unlocking via fingerprint, the audio file plays normally.  It is almost as if the audio for the unlock sound tries to play more than once but fails until it finally plays. I'm guessing my issue and this issue are directly related.  I'm sorry I can't describe this better. 

Device: Google Pixel 4a
OS Version: Android 12, Stable Channel, Security update 3/5/22, build# SP2A.220305.012.2022030801

**Comment by croftman** [comment]
Same Here ! And I just update the rom

Device: Google Pixel 4a
OS Version: Android 12, Stable Channel, Security update 3/5/22, build# SP2A.220305.012.2022033013

**Comment by w1bsb** [comment]
@croftman  Does your unlock sound stutter as well?

**Comment by croftman** [comment]
> @croftman Does your unlock sound stutter as well?

Yes me too !

**Comment by w1bsb** [comment]
Thanks, just wanted to make sure I wasn't the only one.

**Comment by flawedworld** [comment]
Will be fixed in next release
