### ISSUE TITLE
Call audio over bluetooth

### ISSUE THREAD

**Issue by ph00lt0** [GrapheneOS/os-issue-tracker#1047]
When Bluetooth devices are connected I am expecting the audio of calls to be routed over those devices, however this does not seem to work. I first had this issue with Signal and thought that this was a bug with them, however it also happens with my VOIP client.

**Comment by ph00lt0** [comment]
I see my issue is a duplicate of:  https://github.com/GrapheneOS/os-issue-tracker/issues/762

**Comment by JanOstrowka** [comment]
#762 
I believe these issues are related

**Comment by thestinger** [comment]
Is this on secondary users or everywhere?

**Comment by mv10201** [comment]
I have this issue too. Media plays on BT no problem. Phone calls do not work on BT. Started a few weeks ago.
Pixel 4_ Android 12_ build SP2A.220305.012.2022032715
System set for automatic update

**Comment by ph00lt0** [comment]
@thestinger yeah that is https://github.com/GrapheneOS/os-issue-tracker/issues/762, but that one was only speaking about secondary user profiles, so unsure if it is the exact same problem. 

I logged another issue with Bluetooth audio. https://github.com/GrapheneOS/os-issue-tracker/issues/1095, but I wouldn't be able to tell you if it's connected at all.

**Comment by mv10201** [comment]
#762 - Mine is just phone problem, media ok. I am primary user, no secondary user configured.


Thanks

Mark

From: ***@***.***
Sent: March 30, 2022 9:22 AM
To: ***@***.***
Reply-to: ***@***.***
Cc: ***@***.***; ***@***.***
Subject: Re: [GrapheneOS/os-issue-tracker] Call audio over bluetooth (Issue #1047)


@thestinger<https://github.com/thestinger> yeah that is #762<https://github.com/GrapheneOS/os-issue-tracker/issues/762>, but that one was only speaking about secondary user profiles, so unsure if it is the exact same problem.

I logged another issue with Bluetooth audio. #1095<https://github.com/GrapheneOS/os-issue-tracker/issues/1095>, but I wouldn't be able to tell you if it's connected at all.

**Comment by thestinger** [comment]
Should be solved by the next OS release. You can let us know if it's still an issue after we make the release.

**Comment by Zanthed** [comment]
Seems to be fixed in the main profile. https://github.com/GrapheneOS/os-issue-tracker/issues/762 is only relevant for secondary profiles.
