### ISSUE TITLE
Problem connecting (wifi) with PEAP method and "Phase 2 authentication = none"

### ISSUE THREAD

**Issue by Saroumane** [GrapheneOS/os-issue-tracker#1048]
System info:

Google Pixel 3a
Build number SP2A.220305.012.2022030801

Sorry if  don't use the words correctly, I'm not familiar with all the intricacies of wireless networks.
I have a problem connecting to a wifi network. My friend is on Android 11 (stock OS) and he has to select the following setup for authentication :
- EAP method : `PEAP`
- Phase 2 authentication : `none`
- Identity : xxxx
- Password : xxxx

and he's connected.

On my GrapheneOS powered Pixel 3a, I can select `PEAP` as EAP method, but there is no `none` option for Phase 2 authentication.
So I cannot connect at all. (I also tried `PWD` as EAP method, no success)
Is it something removed upstream since Android 12 ? Or by GrapheneOS ? Or I completely missed something ?

**Comment by Zanthed** [comment]
Not a bug. It was removed upstream.

https://www.xda-developers.com/android-11-break-enterprise-wifi-connection/

**Comment by thestinger** [comment]
Android 11 QPR1 removed it for security reasons. It's over a year since that was released and networks should have adapted to this by using a secure setup by now.

**Comment by Zanthed** [comment]
Please contact your IT help desk. They should not be using that anymore.

**Comment by Saroumane** [comment]
I will try, but as it is the network for public/guest devices, I'm afraid they won't care. (And regarding my situation, I was planning to use a VPN). 
I might look after news reporting a leak involving this security issue (to support the change)
Anyway, thanks for the quick replies
