### ISSUE TITLE
System - System Update - Automatic reboot idle detection doesn't check Wifi tethering

### ISSUE THREAD

**Issue by RueleuR** [GrapheneOS/os-issue-tracker#1053]
What happens:
The System reboots after a system update with activated Wi-Fi tethering  and a connected and active client. 

What should happen:
The System waits for the reboot after a system update until the wifi tethering is off or no client is connected to the network.

Background:
Is not nice to lose the connection during a tethered online meeting. The update process needs some time.

Suggested solutions/enhancements:
- I switch off automatic reboot option. 😐
- improve idle detection and detect if the data connection or wifi/USB tethering is in use 😁
- the system allows to define a time window for automatic updates like in Windows 10  🙂

**Comment by flawedworld** [comment]
Intentional

**Comment by flawedworld** [comment]
We can't add detection to this as then it could be used to bypass the auto-reboot timer.

**Comment by thestinger** [comment]
This applies to idle detection in general rather than specifically to the update client. The phone can't really know whether the device that's connected is in use.

**Comment by thestinger** [comment]
@flawedworld It's a different form of idle detection than auto-reboot. It's not based on the device being locked but rather how JobScheduler decides if the device is idle. If you wake up the phone it won't consider it idle. It may consider it idle fairly quickly if it's not being used though. It also depends on certain variables.

**Comment by thestinger** [comment]
I don't know if there's anything we can or should do about it. If you have a device tethered indefinitely, it would never reboot to update if idle reboot was disabled while tethered. I think it may be best for people to turn it off in this situation if they don't want it to happen.

**Comment by thestinger** [comment]
Not planning to change how this works.

**Comment by thestinger** [comment]
It's the upstream design for the idle feature.

**Comment by RueleuR** [comment]
If the idle detection for updates is risky or complicated than a possibility to set an update time window (night) would be fine too.
