### ISSUE TITLE
Proximity sensor on while no app is running in multitasking

### ISSUE THREAD

**Issue by Pauler221** [GrapheneOS/os-issue-tracker#1056]
The proximity sensor is on from time to time. Doesn't matter if you're on the homescreen or using another app. Hovering your hand over the sensor makes your display go dark. Reboot solves the issue.

Device model: Pixel 4a
OS version: 12 (beta channel)
Build number: SP2A.220305.012.2022030801

**Comment by thestinger** [comment]
Not able to replicate and others don't seem to be able to replicate it either. This will be closed soon without a way to reproduce the problem.
