### ISSUE TITLE
On Pixel 6 build S2B3.220205.007.A1.2022031103 latest F-Droid apk fails to install; some apps (like Conversations XMPP client) crash

### ISSUE THREAD

**Issue by poke808** [GrapheneOS/os-issue-tracker#1057]
After migrating from a Pixel 3a with latest GrapheneOS (SP2A.220305.012.2022030801) where the two apps F-Droid and Conversations (XMPP client) are working flawlessly to a Pixel 6 with latest GrapheneOS (S2B3.220205.007.A1.2022031103) I am encountering issues with both apps.

Installing F-Droid from scratch on the Pixel 6 fails outright with
- F-Droid, version 1.14 - "App not installed as package appears to be invalid."

Migrating the two apps via Seedvault from the Pixel 3a to the Pixel 6 appears to work, but the following issues pop up
- F-Droid reports that it was build for a previous version of Android and may not work on this Pixel 6 (both the Pixel 3a and the Pixel 6 are on latest GrapheneOS releases, i.e. Android 12)
- Conversations, version 2.10.2+fcr - XMPP client crashes when establishing Audio/Video calls

On both phones these apps have been installed as User and not Owner.

**Comment by thestinger** [comment]
You need to report app bugs to the app developers.

> F-Droid, version 1.14 - "App not installed as package appears to be invalid."

You've likely done something like installing a different variant in another profile.

> F-Droid reports that it was build for a previous version of Android and may not work on this Pixel 6 (both the Pixel 3a and the Pixel 6 are on latest GrapheneOS releases, i.e. Android 12)

F-Droid targets the legacy API 25 (Android 7.1). This is a problem with their app and is expected.

> Conversations, version 2.10.2+fcr - XMPP client crashes when establishing Audio/Video calls

Needs to be reported to them. Likely not caused by GrapheneOS. Unless you have tested on the stock OS with Android 12.1 and it works there, no reason to think it's a GrapheneOS issue.

**Comment by poke808** [comment]
Thanks for getting back quick, thestinger, appreciated!

> You need to report app bugs to the app developers.
> 
> > F-Droid, version 1.14 - "App not installed as package appears to be invalid."
> 
> You've likely done something like installing a different variant in another profile.

I've done pretty much the same I've done on the Pixel 3a where it works - download the latest F-Droid apk from the F-Droid page and install it (as user). On the Pixel 3a with latest GrapheneOS it works, on the Pixel 6 with latest GrapheneOS it doesn't.

> > F-Droid reports that it was build for a previous version of Android and may not work on this Pixel 6 (both the Pixel 3a and the Pixel 6 are on latest GrapheneOS releases, i.e. Android 12)
> 
> F-Droid targets the legacy API 25 (Android 7.1). This is a problem with their app and is expected.

Ok. But why do I not see the same issue on the Pixel 3a with latest GrapheneOS then?

> > Conversations, version 2.10.2+fcr - XMPP client crashes when establishing Audio/Video calls
> 
> Needs to be reported to them. Likely not caused by GrapheneOS. Unless you have tested on the stock OS with Android 12.1 and it works there, no reason to think it's a GrapheneOS issue.

I have not tested with latest stock OS. I have only looked / compared latest GrapheneOS on both the Pixel 3a and the Pixel 6.

**Comment by thestinger** [comment]
> I've done pretty much the same I've done on the Pixel 3a where it works - download the latest F-Droid apk from the F-Droid page and install it (as user). On the Pixel 3a with latest GrapheneOS it works, on the Pixel 6 with latest GrapheneOS it doesn't.

I explained what the issue likely is in my response. It's not an issue with the OS.

> Ok. But why do I not see the same issue on the Pixel 3a with latest GrapheneOS then?

The warning is only shown on first launch and it's not an issue. It's an intended feature of the OS to warn when you first launch an app below API 28 instead of API 23 like AOSP / stock Pixel OS.

**Comment by poke808** [comment]
> > I've done pretty much the same I've done on the Pixel 3a where it works - download the latest F-Droid apk from the F-Droid page and install it (as user). On the Pixel 3a with latest GrapheneOS it works, on the Pixel 6 with latest GrapheneOS it doesn't.
> 
> I explained what the issue likely is in my response. It's not an issue with the OS.
> 
> > Ok. But why do I not see the same issue on the Pixel 3a with latest GrapheneOS then?
> 
> The warning is only shown on first launch and it's not an issue. It's an intended feature of the OS to warn when you first launch an app below API 28 instead of API 23 like AOSP / stock Pixel OS.

Gotcha, thanks. I'll raise this with the F-Droid team then.

**Comment by thestinger** [comment]
You likely have a different variant of the app installed in another profile as I said above. It will block you from installing another variant of the app. I suggest doing a factory reset and starting over without the configuration changes and apps you've installed if you're having problems. These aren't OS issues and may be caused by your configuration if you've done stuff like enabling developer options.

**Comment by poke808** [comment]
Really appreciate your time, Daniel. I was not aware that apps installed in other profiles have the potential to block each other, I was under the assumption profiles are completely separated. So, following your advice I have unsinstalled F-Droid on ALL profiles (a factory reset was not necessary) and then installed it again (from Vanadium download) and it worked. I probably need to spend more time studying (shared) permissions across profiles. Thanks again for your time and advice!

**Comment by thestinger** [comment]
Apks are installed globally so that they get reused across every profile with the app installed. There's key pinning and downgrade protection which is what makes this safe. Worth noting any user/work profile can update apps globally.

**Comment by thestinger** [comment]
Conversations issue may be an issue it has with Android 12.1. That's what I suggest reporting upstream. Someone with stock OS on Pixel 6 could check if the same thing happens. Also, there might be something wrong with the F-Droid Conversations build or it might be out of date. Try using the developer's official release.

**Comment by poke808** [comment]
After re-installing F-Droid (as per above) I have also re-installed Conversations - and - ey presto - issues went away (Audio/Video chat working). So, what didn't quite work (and may have contributed to this chaos) is transferring/backing up apps as users via Seedvault from the Pixel 3a to the Pixel 6. A complete, vanilla installation of both F-Droid and Conversations sould've worked (but, hey, I was keen on that Backup functionality ;)
