### ISSUE TITLE
Tor Browser and other apps not working

### ISSUE THREAD

**Issue by HersirX** [GrapheneOS/os-issue-tracker#1058]
Hello
Tor Browser and Wickrme are not functioning any more.
Those were perfectly working before. Since the "Apps" was published, i deactivated it, turned off GSF GPS and the Google Store. The apps functioned well. Now Tor Browser doesnt, where wickrme only does when google services framework is installed. Tor browser will launch but then crash immediatelly. I really have no wish to have anything of google in my mobile. I fo not think that the issues are with the apps, eben thou they state to be GSF dependent.
Is there a workaround? I think this issues started 2 weeks ago.

**Comment by Zanthed** [comment]
Not related to our OS. There's a bug in their app. Take it to the app developers why it doesn't work on Android 12.1.
