### ISSUE TITLE
cannot login into owner profile

### ISSUE THREAD

**Issue by h2dden** [GrapheneOS/os-issue-tracker#1060]
Android 12.1
Pixel 6
sometimes when switching from a secondary profile to owner, the keyboard refuses to pop up to enter the password and open the owner.
the only medicine is to bring up a secondary profile or to go back to the initial secondary profile and to end it so that it lands back to the login screen where the keyboard finally pops up
this is a video of the issue. riseup stores files for 12h only... if required to re upload, let me know
https://share.riseup.net/#efToowLOPfWmqAhwcOyKpw

**Comment by thestinger** [comment]
Sounds like this is the same issue as https://github.com/GrapheneOS/os-issue-tracker/issues/467.
