### ISSUE TITLE
Denied bind for untrusted_app

### ISSUE THREAD

**Issue by kyak** [GrapheneOS/os-issue-tracker#1067]
Hi,

I've noticed it just recently. But starting from the 7th February 2022 two of my GOS devices have stopped syncing using `syncthing`. The remote device (server) shows up is "Disconnected". This particular time of "last seen" (around 2022-02-07 10 PM GMT+3 on both devices) is not related to any upgrades on server side or syncthing side. But it is very close to https://grapheneos.org/releases#2022020800, which introduced some changes to Network. Anyway, I'm trying to rule out any possibility that it is not related to GrapheneOS.

In syncthing logs (particular, in "Android logs" section), I see this:

> 03-20 09:57:40.894 W/libsyncthing.so(  904): type=1400 audit(0.0:2262092): avc: denied { bind } for scontext=u:r:untrusted_app:s0:c185,c256,c512,c768 tcontext=u:r:untrusted_app:s0:c185,c256,c512,c768 tclass=netlink_route_socket permissive=0 bug=b/155595000 app=com.nutomic.syncthingandroid
03-20 09:57:40.897 W/libsyncthing.so(  904): type=1400 audit(0.0:2262093): avc: denied { bind } for scontext=u:r:untrusted_app:s0:c185,c256,c512,c768 tcontext=u:r:untrusted_app:s0:c185,c256,c512,c768 tclass=netlink_route_socket permissive=0 bug=b/155595000 app=com.nutomic.syncthingandroid
03-20 09:57:40.897 W/libsyncthing.so(  904): type=1400 audit(0.0:2262094): avc: denied { bind } for scontext=u:r:untrusted_app:s0:c185,c256,c512,c768 tcontext=u:r:untrusted_app:s0:c185,c256,c512,c768 tclass=netlink_route_socket permissive=0 bug=b/155595000 app=com.nutomic.syncthingandroid

On the server side (which is on the local network with both GOS devices), I see that the server sends discovery requests, but doesn't get any response from devices. I presume this might be related to the `avc: denied { bind }` message I'm seeing in the logs.

**Comment by thestinger** [comment]
https://forum.syncthing.net/t/after-updating-on-android-to-1-19-0-i-cannot-sync-anymore/17977

Upstream bug with the app.

**Comment by thestinger** [comment]
It's quite important for developers to test on newer releases of Android especially when updating API level. Shouldn't ever be blindly updating API level without heavily testing it. Many developers of open source apps in particular appear not to test on the developer previews or on new major releases.

The log issue you're showing is tied to restrictions introduced for API 30, i.e. Android 11. It's possible that app only recently moved to targeting API 30+. It's likely they did it to comply with Play Store policy without actually getting everything working on modern Android.

You're going to have to take it up with them. It appears they don't support modern Android, even Android 11.

**Comment by kyak** [comment]
Thanks Daniel!

This actually tells a lot about syncthing developers' attitude. I guess I'm off to searching alternatives..

**Comment by thestinger** [comment]
It's likely that there are just no core developers working on the app with access to modern Android phones and they may not realize that's crucial and that they can't get away with updating the API level without testing and migrating to new APIs.
