### ISSUE TITLE
Messaging and Phone app should not have Network permission by default

### ISSUE THREAD

**Issue by ThePowerOfDreams** [GrapheneOS/os-issue-tracker#1069]
It would appear as though Messaging and Phone are both granted Network permission by default; at least this seems to have been the case on my device).

If this is the case, it probably shouldn't be.

https://www.scss.tcd.ie/doug.leith/privacyofdialerandsmsapps.pdf

https://news.ycombinator.com/item?id=30751751

**Comment by flawedworld** [comment]
It's needed for them to work.

**Comment by Zanthed** [comment]
If you don't use that stuff, you're free to revoke the permission yourself. It's necessary for most people though so we cannot change it.
