### ISSUE TITLE
Airplane Mode Off Permissions

### ISSUE THREAD

**Issue by GrapheneSlut** [GrapheneOS/os-issue-tracker#1070]
Hello Graphene team. Thank you..

I'd like to request a feature that would require user pin/finger print to turn off Airplane Mode. 

This would help users to not mistakenly activate their cellular network in a secure area.

**Comment by GrapheneSlut** [comment]
Yes, great suggestion.. Thank you..  Preferably this would be a feature that allows users to turn permission required off and on for Airplane Mode. 

If this feature makes it I'll be stoked!

**Comment by thestinger** [comment]
Not currently planned.

**Comment by lemanschik** [comment]
@thestinger call emergency services by pressing the power button 5 times. This feature is on by default and you have to manually turn it off in every profile. Could that simple default to off?

Then at last the hidde quick tile would be save as the only other way to do a emergency call would be complet unlock and manual dial emergency numbers as also hit call button
