### ISSUE TITLE
Design and create reimplementation of Thales secure element firmware loader app for Pixels

### ISSUE THREAD

**Issue by flawedworld** [GrapheneOS/os-issue-tracker#1072]

**Comment by no-usernames-left** [comment]
Now this is interesting. What are the plans for this bad boy?

**Comment by flawedworld** [comment]
@no-usernames-left  https://github.com/GrapheneOS/grapheneos.org/commit/897da938847bb4af90ac981ab64bebe6565a6cf5

**Comment by no-usernames-left** [comment]
@flawedworld Wonderful news! Keep up the great work!
