### ISSUE TITLE
Seedvault Phone to Phone transfer and com.android.deskclock settings backup

### ISSUE THREAD

**Issue by RueleuR** [GrapheneOS/os-issue-tracker#1073]
I transfered the seedvault backup from a pixel 6 to a pixel 6 pro through a USB Stick. That worked very well. I have only two little issues to report:

a) Please make it possible to load the seedvault backup directly from the "old" phone. I think MTP USB has to be initalized before seedvault starts its tasks. . The backup didn't work with a direct conncetion between two phones with the include USB-C cable. But after finishing the setup routine a direct MTP USB connection through the cable is possible

b) There seems to be no seedvault backup of the clock app "com.android.deskclock". --> Please include the settings of this standard app in the backup list.

**Comment by flawedworld** [comment]
We want to completely replace Seedvault with our own backup app. That will likely be taken care of there.

**Comment by flawedworld** [comment]
>b) There seems to be no seedvault backup of the clock app "com.android.deskclock". --> Please include the settings of this standard app in the backup list.

We could look into this at some point though.

**Comment by lbdroid** [comment]
> We want to completely replace Seedvault with our own backup app. That will likely be taken care of there.

My apologies if this is not the place to talk about this, but I've seen no mention of "our own backup app" anywhere else. A few important (to me) points I'd like to suggest for this new backup application;

1) Don't lose seedvault's ability to backup to a Nextcloud instance. It would also be nice to be able to *restore from* Nextcloud during initial setup, so maybe through an integrated webdav library? This would also make it compatible with other webdav servers.
2) Ability to make NON-encrypted backups. Encryption is a nice thing to have when backing up to a not-entirely-trusted location, but just makes things difficult if the backup location is independently secure.
3) Ability to backup *everything* and not just that subset of software that has been flagged for backup in its manifest. At the moment, the only solution for a complete backup is to use external software that required root access (for example, oandbackupx), which is contradictory to the objectives of Graphene.
