### ISSUE TITLE
Can't see 5G as `Preferred network type` option after provisioning an eSIM

### ISSUE THREAD

**Issue by gordonel** [GrapheneOS/os-issue-tracker#1074]
Pixel 6, 2022032110. After provisioning an eSIM, `5G (recommended)` disappeared as a `Preferred network type` option in both SIM and eSIM settings. `*#*#4636#*#*` still has selectable options with NR, but they get reset within a couple of seconds to LTE*

**Comment by thestinger** [comment]
The debug menu options aren't persistent and aren't supposed to work beyond debugging.

**Comment by thestinger** [comment]
It's likely your eSIM network doesn't support 5G. Without further information we can't consider this a bug.

**Comment by gordonel** [comment]
@thestinger before I installed the eSIM, the physical SIM had 5G as an option. eSIM is from Czech T-Mobile, and supports 5G

**Comment by flawedworld** [comment]
Check on the stock OS. I highly doubt it's a GrapheneOS issue.

**Comment by gordonel** [comment]
@flawedworld not an option for me, unfortunately. I think we need to keep this issue open and wait if somebody can reproduce

**Comment by thestinger** [comment]
It's only a valid issue if it happens with GrapheneOS and not the stock OS. It's not our intention to support broader support for VoLTE, 5G, etc. than the stock OS by manually maintaining patches for the carrier configuration changing it from what the carrier has worked out with Google for Pixels. The carrier needs to get their carrier configuration updated for Pixels if there are features that are available and should be enabled but aren't yet enabled.

**Comment by gordonel** [comment]
> we have no plans to maintain custom carrier configuration because it would be completely unrealistic to maintain or test.
This is not really needed. As long as the OS and firmware have the latest GSMA spec implementation, everything should provision without issues

**Comment by gordonel** [comment]
> we have no plans to maintain custom carrier configuration because it would be completely unrealistic to maintain or test.

@thestinger This is not really needed. As long as the OS and firmware have the latest GSMA spec implementation, everything should provision without issues

**Comment by thestinger** [comment]
That's not how things actually work because as I said feature detection doesn't work in the real world for cellular and therefore these features have to be manually whitelisted across carriers in the massive carrier configuration and APN databases. Provisioning does not work and isn't how most of it works.

**Comment by thestinger** [comment]
Give me the mcc and mnc and I will show you the carrier configuration they have in the database.

**Comment by gordonel** [comment]
@thestinger MCC 260, MNC 02
