### ISSUE TITLE
Add "Freeze Google Play Apps" functionality to GmsCompat

### ISSUE THREAD

**Issue by gordonel** [GrapheneOS/os-issue-tracker#1075]
Given that some people aren't comfortable running Google stuff on their main profiles, but may need to from time to time in order to provision eSIMs, GmsCompat app should be able to freeze/disable Google Play apps. Simply installing and uninstalling them every time one needs to do something with eSIMs may cause issues down the road if the Google Play apps are primarily used in the work profile.

I had to completely reinstall Google Play apps twice already today

**Comment by thestinger** [comment]
This isn't going to be implemented as a feature specific to Google Play. We plan to support disabling user installed apps as you can do for system apps.
