### ISSUE TITLE
Battery Charge Level Controls

### ISSUE THREAD

**Issue by GrapheneSlut** [GrapheneOS/os-issue-tracker#1080]
Requesting enhancement - 

Monitor of battery health, power output and  - ability to set charging permissions i.e. (do not charge passed 90%/ do not charge until battery reaches 40%) etc.

**Comment by Zanthed** [comment]
The battery firmware and battery controller handle all of this for you. We're not adding things like this including adaptive charging or whatnot. Any modern phone has this and handles all of this for you.

**Comment by ashkitten** [comment]
> The battery firmware and battery controller handle all of this for you. We're not adding things like this including adaptive charging or whatnot. Any modern phone has this and handles all of this for you.

this is not true as far as i'm aware. the charging controller's job is to keep the battery from exploding, not to keep it at optimal health. there's a reason adaptive charging is implemented in the stock os and not in the charging controller firmware.

**Comment by hkup859** [comment]
I agree, battery charge control is (as far as I've seen) implemented at an os level. An example being samsung allowing you to stop the battery charge at 85%. While this may not be the most important next feature (though I'd love to see it) it is something that should be on the list of future work.

**Comment by thestinger** [comment]
Ask for the feature in AOSP. This isn't what we do.

**Comment by thestinger** [comment]
@ashkitten What you're stating about the battery controller is not accurate. It adjusts the charge rate to keep the battery healthy. What it doesn't do is implementing an arbitrary limit below the rated capacity. It just massively slows down the charge rate as it approaches capacity. It works well already.

**Comment by thestinger** [comment]
@hkup859 Simply wrong as already stated.
