### ISSUE TITLE
Web Installer fails on Arch Linux

### ISSUE THREAD

**Issue by atollk** [GrapheneOS/os-issue-tracker#1083]
Running on Arch Linux 5.16.6 with android-udev-20220102-1 (fastboot 31.0.33p1-android-tools), installing Graphene on a Pixel 3a via the web installer fails.
During "Flashing factory images", the step "Writing system" fails without any visible progress on the website with "Error: Timeout of 10000 ms exceeded". This happens consistently with multiple tries, i.e. all previous steps complete properly but "Writing system" fails at the start.
On a Windows 10 system with the exact same hardware, the installation completed without any issues.
Besides the OS, the difference was in the browser used which was Chromium on Arch Linux and Chrome on Windows. Both had  version 99.0.4844.82.

**Comment by flawedworld** [comment]
It is likely a cable/port issue.

**Comment by flawedworld** [comment]
Please use Matrix for support queries https://grapheneos.org/contact#community

**Comment by atollk** [comment]
How can it be a hardware issue if it works with the exact same hardware (including the cable) when I change my OS? 

I don't need support or a question answered; I managed to work around the issue on my own. This is meant as a bug report to GrapheneOS to give you the chance to improve the software. This project is in a sad state, if bug reports are brushed off as "it's the user's fault" with seemingly no interest in actually fixing issues.

**Comment by thestinger** [comment]
> How can it be a hardware issue if it works with the exact same hardware (including the cable) when I change my OS?

Your USB connection being unreliable doesn't mean that it will fail to work every time. A different operating system also means different USB and other drivers.

> I don't need support or a question answered; I managed to work around the issue on my own. This is meant as a bug report to GrapheneOS to give you the chance to improve the software. This project is in a sad state, if bug reports are brushed off as "it's the user's fault" with seemingly no interest in actually fixing issues.

This isn't a bug. The web installer works perfectly on Arch Linux. This issue was closed because it's not a bug but rather an issue with your setup. We have a lot of experience with this and know that for a fact. If you're going to start attacking the project here because the bug you filed was closed as invalid, you'll be banned from the issue tracker.

**Comment by atollk** [comment]
> Your USB connection being unreliable doesn't mean that it will fail to work every time. A different operating system also means different USB and other drivers.

Please explain to me in detail how an unreliable connection causes an exactly reproducible failure in one software setup and a perfectly functional behavior in another. I ran the installer three times on Arch and it behaved the exact same way every time. And while I'm not familiar with Android development, my few years of embedded development background tell me that this isn't what an error caused by "unreliable hardware" looks like.

Is it a driver issue? Yeah, it might be. Maybe it is a combination of my browser, browser version, linux version and fastboot version? Who knows, it's possible. But for sure it is not a "cable/port issue" as it was claimed to be. 

> We have a lot of experience with this and know that for a fact. If you're going to start attacking the project here because the bug you filed was closed as invalid, you'll be banned from the issue tracker.

Just to be clear, I didn't criticize the project, i.e. GrapheneOS as a whole, but rather the behavior you maintainers in this thread so far. And the fact that you deleted my comment (I don't even know why when you proceed to include most of it in your own as quotes) just confirms my opinion.

But sure, go ahead and ban me if you want to. The fact that I did the best issue description I could and was willing to wipe my phone and run the installer again in case you need to collect additional information from me to trace the issue down, and then my report doesn't even get read properly (which is the only explanation I have as to how one would conclude that it's a hardware issue), made me lose any interest in contributing to this project anyway.
