### ISSUE TITLE
Screen Recorder no longer able to capture screen taps

### ISSUE THREAD

**Issue by TheMCNerd2017** [GrapheneOS/os-issue-tracker#1086]
The screen recorder used to have an option that would allow screen taps to be captured. This option seems to have vanished at some point and screen taps do not show up in recordings, even if showing screen taps is enabled in developer settings.

![Screenshot_20220326-210347](https://user-images.githubusercontent.com/25375242/160262246-03f72bb7-9925-4937-b2bd-173f32dd0f16.png)

OS: GrapheneOS 12 (SP2A.220305.012.2022032110)
Device: Pixel 4 XL

**Comment by jorgeluiscarrillo** [comment]
This was removed upstream in 12L and will probably be added back in 13.

**Comment by thestinger** [comment]
We'll just go with upstream on this. It was removed due to being seriously broken.

**Comment by thestinger** [comment]
i.e. it needs to be reimplemented because it didn't work right and they decided to remove it rather than leaving a broken option, which may not be what users prefer but it's what they did and we don't want to override that.

**Comment by TheMCNerd2017** [comment]
> i.e. it needs to be reimplemented because it didn't work right and they decided to remove it rather than leaving a broken option, which may not be what users prefer but it's what they did and we don't want to override that.

Oh dear, I didn't realize it was removed due to not working right. Thanks for telling me. I'm curious though as to what bugs it had that made it broken.
