### ISSUE TITLE
Printing aborts when the device gets locked

### ISSUE THREAD

**Issue by k9janer** [GrapheneOS/os-issue-tracker#1087]
I have noticed that printing using the default print service aborts as soon as you lock the device.

My configuration:

- Pixel 6 using GrapheneOS SP2A.220305.013.A3.2022032110
- EPSON WF-2860 Series using latest firmware
- Pixel 6 is connected using WIFI, the printer is connected to the same network using rj45
- Using the default print service

Example:

1. Print a document in Collabora Office
2. The printer will start printing
3. Lock your device
4. The print job will fail almost immediately

As long as you don't lock the device, printing will work fine.

I tried allowing unrestricted battery usage for "default print service" and then "print spooler" but this didn't solve the issue for me.

**Comment by flawedworld** [comment]
@k9janer please check if this is still an issue.

**Comment by flawedworld** [comment]
It's likely that this is a bug with the printer app rather than a bug with AOSP.
