### ISSUE TITLE
Add missing Settings videos/demonstrations

### ISSUE THREAD

**Issue by ghost** [GrapheneOS/os-issue-tracker#1090]
Settings -> System -> Gestures:
- Quickly open camera
- One handed mode
- Tap to check phone
- Lift to check phone
- Prevent ringing

Settings -> Notifications:
- Bubbles

Settings -> Display -> Lock screen:
- Tap to check phone
- Lift to check phone

Settings -> Display:
- Adaptive brightness

**Comment by Zanthed** [comment]
https://github.com/GrapheneOS/platform_packages_apps_Settings/pull/85

**Comment by r3g-5z** [comment]
This may be desirable in the future, but for now the missing demonstrations will simply not render themselves rather than showing a blank screen.
