### ISSUE TITLE
(Req) automatic disabling microphone when not used

### ISSUE THREAD

**Issue by robovoice1** [GrapheneOS/os-issue-tracker#1093]
After the microphone is not used any more, the permission  is disabled after a selected period of time.

**Comment by ph00lt0** [comment]
Regardless whether this was the original request I think that would be a nice feature! @flawedworld

**Comment by robovoice1** [comment]
Right now: user gets asked to take action, if the mic was blocked- granting permission (avaiable) for mic. After the finished recordings i usually forget about changing the option back to blocked.

**Comment by flawedworld** [comment]
> Right now: user gets asked to take action, if the mic was blocked- granting permission (avaiable) for mic. After the finished recordings i usually forget about changing the option back to blocked. An option like microphone timeout.

There is already an option to give microphone access just once.
