### ISSUE TITLE
Music/audio doesn't always play over bluetooth when connected.

### ISSUE THREAD

**Issue by ph00lt0** [GrapheneOS/os-issue-tracker#1095]
I often find myself in the situation where my bluetooth headset is connected but GrapheneOS doesn't use this as audio output and it just plays on the speakers instead. It can always be resolved by reconnecting but I believe there is a bug here. It should always default to Bluetooth when connected imo. 

This bug is not related (at least not in experience) to the phone audio problem as that is not fixable by reconnecting.

**Comment by flawedworld** [comment]
I don't think this is a bug but rather it's to do with how apps treat bluetooth devices. If you are having problems with media audio with bluetooth devices, ensure the app has the "Nearby Devices" permission.

**Comment by ph00lt0** [comment]
@flawedworld sorry but this happened in various apps and was not depended on one specific app so I doubt that is lies with all those apps. I switched to wired headphones as i couldn't call with Bluetooth headset,but will try to test a bit and see if it got resolved by the latest update later.
