### ISSUE TITLE
Pixel 6 Quick Tap/Back Tap Gesture

### ISSUE THREAD

**Issue by klinegareth** [GrapheneOS/os-issue-tracker#1096]
Is there any way on the Pixel 6 to reenable double tapping the back of the phone to open the notification tray?

**Comment by flawedworld** [comment]
Someone would need to make a reimplementation of the ContextHub nanoapp that manages this.

**Comment by flawedworld** [comment]
It is unlikely that GrapheneOS will do this but we would accept a contribution from someone that did this.
