### ISSUE TITLE
Improve folder colours

### ISSUE THREAD

**Issue by julianfairfax** [GrapheneOS/os-issue-tracker#1098]
Since the update to Android 12L, the folder icons in the launcher now have a greyish colour when Monet is turned off, or no colour is detected for the folders. This greyish colour is, at least in my opinion, pretty visually unappealing. If possible, it should be replaced with a more whitish colour that looks more in line with the rest of the interface.

**Comment by thestinger** [comment]
I think this is working as intended.

**Comment by thestinger** [comment]
We could change the color palette choices of the launcher app but we have no plans to start fiddling with that and the changes would vary based on color scheme. Not planned. Best to stick with the defaults other than using our own GrapheneOS color scheme.

**Comment by julianfairfax** [comment]
> We could change the color palette choices of the launcher app but we have no plans to start fiddling with that and the changes would vary based on color scheme. Not planned. Best to stick with the defaults other than using our own GrapheneOS color scheme.

I agree, but it seems that with my (wallpaper's) color scheme, it doesn't actually pick up on the color and so I'm left with this ugly one, which I find odd. But I don't know how it's supposed to work so maybe it is working as intended?

**Comment by thestinger** [comment]
I think that's just the color it chose for that part of the color scheme.

**Comment by julianfairfax** [comment]
> I think that's just the color it chose for that part of the color scheme.

No it isn't because the color is the exact same when I turn Monet off. I know it works though because if I change my wallpaper to some other color, then it picks up that one.

**Comment by thestinger** [comment]
There's no guarantee it will pick a different color.

**Comment by julianfairfax** [comment]
> There's no guarantee it will pick a different color.

Well I was under the impression it would always pick some color, since the rest of the UI has. But in that case, the default color should be more appealing. Currently it's a shade of greyish, but it would be much nicer as a shade of whitish. The default color for dark mode for example, looks a lot better.

**Comment by thestinger** [comment]
We're not going to change how it picks colors and we're also not particularly interested in changing the launcher's choice of color palette colors.

**Comment by julianfairfax** [comment]
> We're not going to change how it picks colors and we're also not particularly interested in changing the launcher's choice of color palette colors.

Well I don't have any problem with how it picks colors or what the default one is, simply that isn't picking one at all. I don't see why that'd happen since everywhere else it does pick one. I guess the only solution to this is to change my wallpaper then?

**Comment by thestinger** [comment]
It is picking one. The grey you see is a color from the palette.

**Comment by julianfairfax** [comment]
> It is picking one. The grey you see is a color from the palette.

From my wallpaper's palette or from the system one? I don't see how it could be picking one if it's the same with and without Monet. I've attached some screenshots to show you.

Without Monet:
![Screenshot_20220403-101349.png](https://user-images.githubusercontent.com/43753131/161418611-2568c357-4542-4ce2-9041-f5973395d9cb.png)

With Monet:
![Screenshot_20220403-101404.png](https://user-images.githubusercontent.com/43753131/161418619-4e1f8392-29e8-45ef-99ac-53742f30ba6a.png)

**Comment by thestinger** [comment]
Not the same color. The 2nd one is more blue tinted.

**Comment by julianfairfax** [comment]
> Not the same color. The 2nd one is more blue tinted.

I haven't actually compared the hex colors but I quite honestly cannot perceive that difference.

**Comment by julianfairfax** [comment]
> Not the same color. The 2nd one is more blue tinted.

I have compared the hex colours, and yes, there is a difference, but that difference is almost imperceivable. To my eyes, this is the same colour, and this colour should be whiter. While it isn't as bad, even in the dark mode the colour is too grey. The light theme colour should be whiter and the dark theme colour should be darker, at least in my opinion.

> Best to stick with the defaults other than using our own GrapheneOS color scheme.

The defaults are unsatisfactory, so they should be changed.
