### ISSUE TITLE
Visual voicemail not working

### ISSUE THREAD

**Issue by reitenth** [GrapheneOS/os-issue-tracker#1100]
Every time it says visual voicemail is not activated yet, please try again later with a big notice saying activating visual voicemail. I just installed Grapheneos coming from Calyx and it was working completely fine with their default dialer. Thanks for the help

**Comment by thestinger** [comment]
Please get support in the Matrix room first. It's highly unlikely that this is a bug. Please don't bring up the project you're mentioning either here or in the Matrix room. It's against the rules.
