### ISSUE TITLE
Add toggle for updating GSF, Play Services and Play Store via Apps or by themselves

### ISSUE THREAD

**Issue by Glukonian** [GrapheneOS/os-issue-tracker#1102]
I think there should be a toggle, either in settings or the Apps app, that gives you the choice of:
• Updating the Google Apps via the Apps app, or
• Letting the Google Apps update themselves, with the user's knowledge that this may make installing them on multiple profiles more difficult.

I say this because the Apps repository has been falling very behind on Google App updates recently (as of this issue being opened, the latest version of Play Store is 29.7, while GOS is still on 29.5). It would be nice to have the option of the apps being independent from the Apps repository, so as to allow for faster updates.

**Comment by thestinger** [comment]
It's not viable because the compatibility layer needs to be kept updated with the changes.
