### ISSUE TITLE
Signal Notification and message receiving Issues when Bitwarden accessibility services are enabled. 

### ISSUE THREAD

**Issue by Solid-Vaccum** [GrapheneOS/os-issue-tracker#1109]
It took me awhile to track down the issue, but when Signal is installed along with Bitwarden, and the Bitwarden accessibility services are enabled, Signal does not receive push notifications or update messages until you open the app. This is for both the Play Store version of Signal, as well as the official website apk. It seems to happen especially when battery saver is on, regardless of the optimization settings. 

To test this, simply enable all of the Bitwarden accessibility services and get someone to send you a Signal message from another device. No notifications on lock screen, home screen, or elsewhere. Open the app and the message will pop up after a second when it updates. Turn the Bitwarden services off and your messages will work just fine. 

I also tried to turn off battery optimizations for the sandboxed play services, as well as to adjust a few other settings. These had zero affect and the issue(s) appear to be limited to the Bitwarden services, when enabled. 

This happened both on 1 of 2 Pixel 6 Pros, and 1 of 2 Pixel 6 regulars. I haven't figured out the connection as to why it only affected one phone of each and not the other. 

Play Services and Store were all installed before both Bitwarden and Signal. Molly seems to receive updates just fine still.

Currently running Pixel 6 | SP2A.220305.013.A3. Everything else is fully updated. Just reinstalled from the online tool to verify issue as well.

**Comment by Solid-Vaccum** [comment]
Why was this closed and labeled as invalid? This is a current and ongoing issue that is easily reproducible.

**Comment by thestinger** [comment]
Turning on battery saver is supposed to break this stuff.

Issues with apps having delayed FCM push are addressed by https://grapheneos.org/releases#2022052500 and only happened with Signal with sandboxed Google Play installed.

**Comment by thestinger** [comment]
Turning on battery saver is supposed to break this stuff. Don't use battery saver if you want working push and polling. Battery saver is for when you want to make sacrifices for extreme battery saving.

All known cases of apps having delayed FCM push are addressed by https://grapheneos.org/releases#2022052500. This only happened for Signal with sandboxed Google Play installed (not with their own push) and probably only when it didn't have a battery optimization exception itself.
