### ISSUE TITLE
Double-tap-to-wake triggered in pocket.

### ISSUE THREAD

**Issue by mowanotm** [GrapheneOS/os-issue-tracker#1110]
The "Double-tap to check phone" feature triggered in pocket, unintentionally reacting to notifications and toggling settings.
May I suggest a check to the proximity sensor?

**Comment by thestinger** [comment]
This does check the proximity sensor. Put your hand over the proximity sensor and try tapping the screen.

**Comment by thestinger** [comment]
Note: I mean hover your hand over it, so you're not screwing it up by touching the screen in an extra place.

**Comment by mowanotm** [comment]
My bad. Sorry for the misinformation. Was trying to make sense into my butt dial situation.
