### ISSUE TITLE
Use zygote but only spawn a single app from it

### ISSUE THREAD

**Issue by bill-myers** [GrapheneOS/os-issue-tracker#1111]
Currently GrapheneOS disables the zygote mechanism to provide distinct secret for each app, at the cost of increased app startup latency.

However, there is a solution that allows to have both the same distinct secrets and decreased latency: use a zygote-based spawning system, but recreate the zygote from scratch after every single app is spawned (which also means there is no need to fork the zygote).

It seems like this would be relatively easy to implement and give the best of both worlds at no cost.

**Comment by thestinger** [comment]
This would take too much time and would often increase latency. A spawning pool is the proper approach but would not be as easy to implement correctly as you think with support for all of the different app compatibility and debugging spawning options working properly. This kind of change is quite invasive and would be difficult to maintain. Our current approach piggybacks on the invokeWith spawning model already existing.

**Comment by thestinger** [comment]
Replacing with https://github.com/GrapheneOS/os-issue-tracker/issues/1113 which has been planned for a long time but seemingly never filed as an issue.
