### ISSUE TITLE
Optionally ignore android:allowBackup="false" and backup whole data directory

### ISSUE THREAD

**Issue by bill-myers** [GrapheneOS/os-issue-tracker#1112]
GrapheneOS seems to currently respect applications setting android:allowBackup="false" in the manifest and disallows backing them up, in addition to not backing up no-backup and cache directory.

However there is no reason why an application author should be allowed to decide whether data on the user's device is backed up or not, and it's useful to back up even caches so that a restore can put the device in exactly the same state as when the backup was made, so I'd suggest to add two new options, where the first would ignore the android:allowBackup setting and the second would backup the whole data directory of the app.

I think this behavior needs to be optional since it's not OK to have backups suddenly include more data without user content; however, both of these options should be set by default on new installations, and ideally there should be a notice on upgrade informing the user that they probably want to turn them on.

As a further enhancement, two per-app options could be provided as well that can override the system-wide options.

**Comment by flawedworld** [comment]
It's unlikely we are going to change how this works. Android 12 resolves this being an issue for most apps, and towards the end of 2022 as apps are forced to target Android 12, I expect it to be pretty much a non-issue.

**Comment by bill-myers** [comment]
Would be it possible to elaborate on how Android 12 changes this?

I have found the following in the Android documentation (https://developer.android.com/about/versions/12/behavior-changes-12):
```
For apps running on and targeting Android 12 and higher:

    Specifying android:allowBackup="false" does disable backups to Google Drive, but doesn’t disable D2D transfers for the app.

    Specifying include and exclude rules with the XML configuration mechanism no longer affects D2D transfers, though it still affects Google Drive backups. To specify rules for D2D transfers, you must use the new configuration covered in the next section.
```

My naive implementation is that unless either GrapheneOS deviates from AOSP as I'm suggesting, or by considering SeedVault/API backups as D2D backups rather than Google Drive Backups, then android:allowBackup="false" would still disable backups; hence Android 12 wouldn't resolve this issue.

**Comment by bill-myers** [comment]
That still allows the app to exclude arbitrary data from the backup by specifying `<data-extraction-rules><device-transfer><exclude>` rules and exclude the cache and no-backup subdirectories by not specifying `<data-extraction-rules><device-transfer>` (and also of course exclude everything by targeting Android 11 and using android:allowBackup="false").

This means that a restore of the device is much less likely to bring to the device to the exact same state as when the back up was made (for instance cache directories might contain downloaded data that is no longer available on the server, resulting in loss of data if they aren't backed up).

Also, it means that the user is not guaranteed to be able to arbitrarily examine and modify the app data by making backups and altering them, which is a problem since there is no other mechanism to do so (other than patching the apk before installing the app) since GrapheneOS doesn't provide root access.

**Comment by thestinger** [comment]
You need to wait for apps to update to API 31 or higher. It will resolve the issue for nearly every app. It will be required for apps to be API 31+ by the end of the year for the Play Store. It's important for apps to be able to exclude files for portability and security reasons. Signal encrypts the database with the hardware keystore without actually using that in a way which keeps the database at rest which they very likely did to block backing up with other mechanisms. If an app wants to break backups your proposal doesn't really stop them doing it. The allowBackup attribute was very flawed since it didn't differentiate between different kinds of backups and the SDK had lint errors which were easiest to fix by disabling it rather than making an explicit exclusion list.

**Comment by thestinger** [comment]
We also can't implement this proposal without severely breaking the security model in the CDD and that's not an option for GrapheneOS.
