### ISSUE TITLE
Timeout Error During installation

### ISSUE THREAD

**Issue by W8APP** [GrapheneOS/os-issue-tracker#1115]
I have a Pixel 3A that I can't get Graphene installed on. The error message is  Error: Timeout of 10000 ms exceeded   I have seen the threads stating that my USB cable is not adequate however I use the exact same cable when I had to re-flash stock andriod using the web interface.  I have attempted the Graphene os install process 3 times using the web browser solution w

I have tried the install process once using the command line (linux mint user) and the error message I get with that method is "Illegal number: 1:81  fastboot too old"

 I sure would love to get Graphene OS installed if possible.

**Comment by ph00lt0** [comment]
For support go to the matrix community. You should update the fastboot your using (android sdk) on your computer btw

**Comment by Zanthed** [comment]
Please ask for support in our Matrix community: https://grapheneos.org/contact#community
