### ISSUE TITLE
SMS app does not ring when receiving a message

### ISSUE THREAD

**Issue by n0sign4l-official** [GrapheneOS/os-issue-tracker#1117]
Hi,
I'm using multiple accounts and I'm able to receive all messages in my 2nd account and the phone vibrates when i do receive a message but it does not sound. Looking in the app everything is enable and also from the phone settings everything seems to be OK.

**Comment by akc3n** [comment]
https://github.com/GrapheneOS/os-issue-tracker/issues/483
https://github.com/GrapheneOS/os-issue-tracker/issues/459
