### ISSUE TITLE
Migrate carriersettings-extractor to using AOSP carriersettings proto instead of handcrafted proto

### ISSUE THREAD

**Issue by flawedworld** [GrapheneOS/os-issue-tracker#1120]
This should further improve carrier support and ensure correctness in the long-term

**Comment by daradib** [comment]
Sounds great - this was the intended plan, e.g., AOSPAlliance/android-prepare-vendor#28

> With Android 11, Google has included a new repo which seems to do what carriersettings-extractor does in reverse, converting AOSP xml format to the CarrierSettings protobuf format: [platform/tools/carrier_settings](https://android.googlesource.com/platform/tools/carrier_settings/). So we can presumably use the Google-supplied protobuf definitions instead of those that I wrote.
