### ISSUE TITLE
WhatsApp cannot see Google account for cloud recovery

### ISSUE THREAD

**Issue by Evernow** [GrapheneOS/os-issue-tracker#1122]
I've been attempting to recover a WhatsApp backup from Google Drive. Unfortunately I do need it for work, when I try to select a Google Account in WhatsApp to restore from, it does not recognize my Google Account which is logged in elsewhere, and when I try to login it says it is already added.

If I log out from Android settings, then login the WhatsApp app, the same process occurs except it logs in but then doesn't recognize it once done.

**Comment by Evernow** [comment]
> Make sure to install WhatsApp after Google Play.

I did, and just incase I uninstalled WhatsApp and then installed it again from Google Play

**Comment by colbyt** [comment]
This can be fixed by giving additional permissions.  Though I'm not sure the precise workflow, I force stopped whatsapp and play services.. gave whatsapp all the permissions it could have.  My play services has contacts, files, nearby, network, phone, sensors, sms and ask location.  Then it worked.

**Comment by khalykbek** [comment]
To restore your chat history from a Google Drive backup, WhatsApp needs Contacts and Media permissions

**Comment by ThePowerOfDreams** [comment]
> gave whatsapp all the permissions it could have. My play services has contacts, files, nearby, network, phone, sensors, sms and ask location.

I must admit that I am surprised and confused to see someone doing this while running GrapheneOS.

**Comment by Evernow** [comment]
Thank you for informing me of this! Finally was able to fully switch.

**Comment by colbyt** [comment]
I don't think it should be surprising, but here's why:    An org I work with is evaluating grapheneOS for use by many non technical human rights activists and are testing every app they commonly use to understand the workflow and limitations. The alternative is them using the same apps on stock android/ios.  Not all have the same security preferences and tradeoffs.  Many use GMail with Google Advanced Protection on chromebooks and this is the #1 most common use case along with MacOS/IOS.  Many live not only on Signal but where the public is -- Twitter, Telegram and Whatsapp based on regional differences (whatsapp is used for many things in latin america unlike in the US).  For years we recommended alternatives to these apps only to see people using them anyway. So a weaker graphene workflow is better than nothing for them.

> > gave whatsapp all the permissions it could have.
> 
> > My play services has contacts, files, nearby, network, phone, sensors, sms and ask location.
> 
> I must admit that I am surprised and confused to find someone doing either one of these things, let alone both, while running GrapheneOS.

**Comment by thestinger** [comment]
A lot of people want to use GrapheneOS as essentially the stock OS with much better privacy/security. They don't necessarily care much about privacy from Google in particular. Sandboxed Google Play is largely as functional as the privileged Google Play so it works well for that use case now. Some people would be happier with both privileged Google Play for functionality that doesn't work with them as regular apps yet along with the exclusive Pixel OS features but that's not happening since we aren't making alternate builds of the OS with it. Sandboxed Google Play aims to gradually reduce the few things which don't work yet and aren't inherently privileged functionality.

**Comment by thestinger** [comment]
Play services likely needs Media permission and perhaps others granted for this to work. There's no indication of any issue right now.

**Comment by thestinger** [comment]
None of the standard runtime permissions is granted by default. It's up to you to grant the required permissions to Play services for niche functionality depending on it.

**Comment by samuelion** [comment]
For me on a clean install, just need to add Contact permissions on Google Play Service to make it works.

**Comment by Marocco2** [comment]
To recap this issue, you'll need:
- contacts permissions from Google play services
- contacts permissions from WhatsApp
- media permissions from WhatsApp

Ungranting one of these won't restore your Google drive backup

**Comment by thestinger** [comment]
You can use Storage Scopes and Contact Scopes instead of the permissions.

**Comment by thestinger** [comment]
You can use Storage Scopes instead of the permissions. Contact Scopes may also work for this Google Play services functionality already. It likely won't work to provide this functionality for WhatsApp right now since it seems to use it to make use of the Google account.

**Comment by treequell** [comment]
> You can use Storage Scopes instead of the permissions. Contact Scopes may also work for this Google Play services functionality already. It likely won't work to provide this functionality for WhatsApp right now since it seems to use it to make use of the Google account.

I can confirm that Contact Scopes don't provide this functionality right now. Might that change in the future?

**Comment by treequell** [comment]
Has anybody got WhatsApp backups working when using Google's advanced protection program?

I can't seem to get the WebAuthn window to show, so that I can sign in with my security keys to my Google Account through WhatsApp.

**Comment by SohanShet** [comment]
Whatapp connects to google drive through google play services, giving permissions like file access contact access worked for me. 
Setting 》apps 》google play services 》 give permission

**Comment by ahnaf-9** [comment]
> Whatapp connects to google drive through google play services, giving permissions like file access contact access worked for me. Setting 》apps 》google play services 》 give permission
thanks so much. solved my issue

**Comment by richqck** [comment]
This is an old thread, but this worked for me. It's rather simple really :-) https://faq.whatsapp.com/209942271778103/?helpref=hc_fnav&cms_platform=android

**Comment by gollex** [comment]
> This is an old thread, but this worked for me. It's rather simple really :-) https://faq.whatsapp.com/209942271778103/?helpref=hc_fnav&cms_platform=android

did you get that step?!
"3. Tap Start on Transfer chat history from old phone."
for me its not giving that option.

**Comment by roasted-watermelon** [comment]
> For me on a clean install, just need to add Contact permissions on Google Play Service to make it works.

Three years later, this is the comment that helped me out. Thank you so much.

**Comment by jdrozdz** [comment]
Google Services didn't need all permissions, just those that WhatsApp need, so:
- Phone call
- Phone history
- SMS
- Media (Pictures & Movies)
- Sensors
- Localisation (probably not ?)
- Network

After all, usually I remove all permissions and leave only Network xD

**Comment by thestinger** [comment]
@jdrozdz You can use Storage Scopes instead of any media permissions. It likely doesn't need all of what you granted beyond that either.

**Comment by whatsadebugger** [comment]
Whatsapp is a piece of literal garbage. I can't even restore after logging in. You can't logout without uninstalling the app.

I was unable to see my google account even after handing it permissions. Which specific ones does it need? No app has given me as much trouble as whatsapp. 

Edit: I got it working Play services did not have contacts
