### ISSUE TITLE
Inconsistency in volume sliders

### ISSUE THREAD

**Issue by ojoeth** [GrapheneOS/os-issue-tracker#1123]
When adjusting the volume by pressing the volume buttons and expanding the three dots menu, the other volume sliders for ringtone and alarms sometimes do not show up. I have confirmed this issue with a friend also running graphene on the same release and same device.

Device: Pixel 6
Build Number: SP2A.220405.004.2022041100

**Comment by tonya1545b** [comment]
I just try if it happen to me as well and yes it did

**Comment by tonya1545b** [comment]
Only when i restart phone then it happen once

**Comment by r3g-5z** [comment]
Can't reproduce this anymore on stock OS and GrapheneOS. Likely fixed upstream now.
