### ISSUE TITLE
Battery Health Conservation

### ISSUE THREAD

**Issue by Phantom-Wolf** [GrapheneOS/os-issue-tracker#1124]
Can a battery conservation mode be implemented that allows a user to select a percentage that, when plugged in to charge, will charge to that percentage limit and shut off charging until unplugged. This would go a long way in preserving the battery. My laptop does this and it is an amazing feature because you can leave it plugged in without worrying of overcharging. There are apps that do this but they all require root access.

**Comment by Zanthed** [comment]
The battery controller and firmware already deal with this. Manual tweaking and configuration is not necessary and can be counter-productive.
