### ISSUE TITLE
System Updates resets an Accessibility toggle

### ISSUE THREAD

**Issue by Rufusdotrufus** [GrapheneOS/os-issue-tracker#1127]
System updates resets Extra Dim toggle in Settings>Accessibility.  Has been happening for many months.

Pixel 4
Build #: SP2A 220405.003.2022041100

**Comment by flawedworld** [comment]
Unable to reproduce, please ensure you are using the "Keep on after device restarts" toggle which is accessed by viewing the dedicated menu for "Extra Dim".
