### ISSUE TITLE
Mobile network battery drain

### ISSUE THREAD

**Issue by Phantom-Wolf** [GrapheneOS/os-issue-tracker#1128]
Is it normal for mobile network to drain battery this fast? My phone is a pixel 6 pro with grapheneos

T-Mobile sim

![Screenshot_20220414-193110](https://user-images.githubusercontent.com/51539880/163499339-46e7ee5f-03fb-41cb-b6cf-209271a9d1d8.png)

**Comment by Zanthed** [comment]
It's a firmware issue. Only Google can fix that. Plenty of other people are reporting this issue on stock OS.
