### ISSUE TITLE
Emergency function doenst let me add contacts

### ISSUE THREAD

**Issue by opensourcefan2** [GrapheneOS/os-issue-tracker#1129]
This emergency function where you can see some information when you hold the power button and click on "emergency" doesnt allow me to add contacts. I can scroll to contacts and pick one, but it just doesnt get added to the list.

Edit: Pixel 6, everything up-to-date

**Comment by khmann** [comment]
Conversely, the "emergency function" doesn't allow me to disable it.  A bad actor with the device in hand could force it to attach to a rogue base station.

Pixel 5, everything up-to-date.

**Comment by flawedworld** [comment]
fixed
