### ISSUE TITLE
[GmsCompat] Support installing/uninstalling apps relying on static libraries apks (such as trichrome builds)

### ISSUE THREAD

**Issue by Wonderfall** [GrapheneOS/os-issue-tracker#1130]
Some users might want to use Chrome as their primary/secondary browser for its synchronization features. It's also a decent choice for a Chromium-based browser that can work with FIDO2, that is until Vanadium is whitelisted by Play services.

Currently, installing Chrome from Play Store requires to clear storage of Play Store first, for some reason. Otherwise [it refuses to install](https://matrix.to/#/!SayHlEYXdrpSerhLMC:matrix.org/$A5ARf69hmf6rYoUIFkDn7rueXgewd8wDUFS3BRUzaRM?via=grapheneos.org&via=matrix.org&via=tchncs.de), because it seems it cannot proceed to install the Chrome trichrome library. Once the trichrome library is installed, Chrome can successfully be installed, and both can be updated (unsure if seamless auto-updates are working at the moment but I got a prompt for the trichrome library).

Another problem is when a user tries to uninstall Chrome, the Chrome trichrome library (`com.google.android.trichromelibrary`) will remain installed. That's probably because it wasn't intended to be uninstalled in the first place, since it also provides code for the webview on stock Android. Users shouldn't have to use `adb` to remove code that won't be updated.

**Comment by quh4gko8** [comment]
Addendum: This is not only specific to Chrome, but also to apps using static-library apk, including all Chromium forks that uses trichrome builds.

**Comment by andrew-ld** [comment]
```
I Finsky  : [102] pje.run(98): GROUP_INSTALL: Creating a parent session. id=com.google.android.trichromelibrary:506012934, staged=false, rollback=false, children=[com.google.android.trichromelibrary, com.android.chrome]

W Finsky  : [102] piu.f(3): DL: Can't find/invoke getDataLoaderParams for Session: android.content.pm.PackageInstaller$Session@ab4517e. ex=java.lang.SecurityException: Neither user 10153 nor current process has com.android.permission.USE_INSTALLER_V2.
07-28 09:01:32.127  1431  1616 I DisplayDeviceReposit

E Finsky  : [2] pjl.onReceive(18): Error -501 while installing com.google.android.trichromelibrary:506012934: INSTALL_FAILED_INTERNAL_ERROR: No child sessions found!
```
I can reproduce the issue, these are the relevant logs from the play store

**Comment by Wonderfall** [comment]
A few things came to my attention (thanks to muhomorr) regarding the removal part.

First, unused static libraries can't do anything on their own. They're pretty much harmless.

Second, static libraries can be marked as "unused" by the OS and there are some internal triggers that can decide whether those libraries can be pruned. In other words: no need for adb (unless you want to remove the library immediately), the OS will eventually take care of that.

Android 13 will make pruning of unused libraries consistent at each system boot and package install/removal.
