### ISSUE TITLE
Disable airplane mode from internet quick tile pop up or remove button

### ISSUE THREAD

**Issue by ph00lt0** [GrapheneOS/os-issue-tracker#1131]
I removed the quick tile of airplane mode to stop me from hitting this accidentally, like suggested in https://github.com/GrapheneOS/os-issue-tracker/issues/1070. However In the internet pop up for Wi-Fi settings, needed to enable the WiFi after it automatically shuts off there is a really big button to disable airplane mode. Personally I would prefer if it would not be part of this pop up at all, otherwise could at least a button be added to the same page to enable it again after clicking this? 

![image](https://user-images.githubusercontent.com/15004290/163679883-540812af-ab78-47aa-8a9d-e0e098a19d7e.jpeg)

Currently one can only disable airplane mode but cannot enable it again from the same place.

**Comment by flawedworld** [comment]
We aren't going to change the UI.

**Comment by ph00lt0** [comment]
Although I understand that it's pretty annoying, that there is only a button to turn it off and not on. If one wanted airplane mode the quick tile for that should do. This button only adds option to accidentally enable airplane mode. I would even like to have an option to never allow enabling of mobile network.
