### ISSUE TITLE
App special accesses get revoked frequently (upstream?)

### ISSUE THREAD

**Issue by Wonderfall** [GrapheneOS/os-issue-tracker#1132]
This is very likely an upstream bug, but I haven't found public reports about it.

I also haven't found a way to reliably reproduce this bug, but from time to time app special accesses get revoked after a reboot (not consistently, so there must be another factor?). I noticed this happened the first time on both my 3a and my 6. This happened recently and continues to happen regularly since then, but I've found reports of someone else having this issue in the testing channel approximately a few weeks before I first experienced the issue.

This is really annoying since it revokes the "Install unknown apps" access for Play Store and I have to check after every reboot to make it sure it hasn't been revoked. Fortunately I don't have many special access to grant, but I can imagine it could be frustrating as hell for some users who may have not realized this yet.

Note: "unused apps" toggles ("Remove permissions and free up space") are also being revoked as well when this happens.

**Comment by flawedworld** [comment]
It's occurring on the stock OS and on GrapheneOS, which would imply that it is an AOSP issue.

**Comment by abdulocracy** [comment]
This is being reset on reboot.

Also, I can't recall this happening on another Android 12 ROM, so might need a second look.

**Comment by thestinger** [comment]
@flawedworld Is there a thread or issue report we can refer to for this happening with the stock OS?

**Comment by muhomorr** [comment]
Capture a logcat or a bugreport the next time this issue occurs. Recent OS versions include additional logging that may help to resolve this issue.
https://github.com/GrapheneOS/platform_frameworks_base/commit/902845a29e7149c56b6b3100eb77072eb2aabcb6
