### ISSUE TITLE
Set 'Adaptive brightness' and 'Auto-rotate screen' to on by default

### ISSUE THREAD

**Issue by GlitchBuddy** [GrapheneOS/os-issue-tracker#1133]
As far as I know they are off by default in AOSP, however I think it would be a good idea to turn them on by default in GrapheneOS. These are features most people would expect to be turned on by default in most phones these days, and it would make the OS more user-friendly out of the box.

**Comment by GlitchBuddy** [comment]
Changes were merged into 12.1 some time ago, closing this issue

**Comment by glukonian** [comment]
Have recently installed a fresh copy of GrapheneOS and these settings are still not on by default. Re-opening this issue.
