### ISSUE TITLE
Inadequate activation of quick settings tiles

### ISSUE THREAD

**Issue by Pauler221** [GrapheneOS/os-issue-tracker#1134]
![Imagepipe_0](https://user-images.githubusercontent.com/33235963/163849040-316fec87-4f6f-4575-a0c3-0f38203a7ed5.jpg)
![stock](https://user-images.githubusercontent.com/33235963/163849048-a8e1efa1-8959-4b95-ae37-4cda16c97c7f.jpg)

Concerning the picture of a pixel 4a:
Marked in red: speaker
Marked in purple: "outlined area"

Pressing the touchscreen within the outlined area activates my flashlight. Doesn't matter what app you're using and this also works on the home screen but not on the lockscreen. 

The flashlight gets activated due to the quick setting being the top right option meaning depending on what setting is in the top right corner it gets activated by touching the screen in the outlined area. This also applies to the top left corner.

Device model: Pixel 4a
Build number: SP2A.220405.003.2022041300

**Comment by thestinger** [comment]
Unable to replicate. Turn off developer options if you have it enabled.

**Comment by thestinger** [comment]
Can't replicate this on a Pixel 4a and we're unlikely to change anything to do with this. If it is an issue, it's an AOSP issue not one caused by GrapheneOS and needs to be reported as an Android bug.
