### ISSUE TITLE
Mobile radio keeps turning off after system updates

### ISSUE THREAD

**Issue by pprodano** [GrapheneOS/os-issue-tracker#1139]
During last several updates of GOS on a Pixel 4XL, following the reboot cycle, the system consistently kept turning off Mobile Radio Power (which thus off all data/voice feature with and no mobile network access). Manually turning on the Mobile Radio did the trick, but this behaviour should be investigated. Is it possible for the team to check what is going on with the update cycle, and find out why Mobile Radio keeps turning off after updates?

**Comment by flawedworld** [comment]
You need to provide more information. Which update? Since how long ago? It's unlikely that it's something to do with GrapheneOS.

**Comment by pprodano** [comment]
Thanks for the quick response. The latest issue was with the update that occurred an hour ago (2022-04-21), but the same has happened the last few updates (I don't remember the exact dates). All I am able to tell is that before the update the mobile radio power was turned on, and then after the update it was off. What is different this time is that I can't seem to turn it back on. I toggle the slider to on position, and for a moment Voice Service goes to Emergency Calls only, and then a second later turns off again. Nothing I do seem to do will turn it on again. 

Is it something in the update script that is turning mobile radio off, or could it be the issue with my physical device (i.e., damaged hardware)? What gets me is that it was working a few hours ago (before the update), and now it does not. Comments?

**Comment by flawedworld** [comment]
I don't think it's anything to do with GrapheneOS. The [2022042000](https://grapheneos.org/releases#2022042000) release has fully functional carrier support so make sure you are on that.

**Comment by pprodano** [comment]
That is the update. Any ideas on how to troubleshoot this?

**Comment by flawedworld** [comment]
You can rule out it being a GrapheneOS issue by trying the stock OS, but I don't really think it's anything to do with GrapheneOS but rather a device issue.
