### ISSUE TITLE
File Manager shows "Can't load content at the moment" in Downloads Tab

### ISSUE THREAD

**Issue by rbn-code** [GrapheneOS/os-issue-tracker#1140]
When you launch the Files App it can't show the content of the "Downloads" Folder and shows "Can't load content at the moment"

<img width="50%" src="https://user-images.githubusercontent.com/99886395/164888783-ddc4f7d0-9351-494d-95d3-db1c1dafdc0b.png"></img>

even thought it has access to it:

<img width="50%" src="https://user-images.githubusercontent.com/99886395/164889156-4a1276ef-1222-42f1-9a83-0cebcb2d5f04.png"></img>

**Comment by Zanthed** [comment]
Can't reproduce this. Need more details.

**Comment by borkedtech** [comment]
@Zanthed what detail do  you need exactly? I'm happy to provide anything necessary to resolve this issue.

**Comment by caveman1973** [comment]
I'm not sure if what you're asking is something like this:

I use Protonmail in the Work profile (with sandboxed Play Services to get notifications). When I received an email with an attachment, it's a hassle to access it. I usually open Files from Work profile and use the export function to send it to Signal. Then I can download to my Main profile. 

What OP is asking is a way for Files in Main profile to access the files in Work profile.

**Comment by thestinger** [comment]
I don't see that being mentioned or requested anywhere.

**Comment by Zanthed** [comment]
There is very little information mentioned here. Nothing indicates this being a work profile thing. I cannot reproduce this, no one else has reported this, and there's no information other than two screenshots that don't indicate anything useful.

Unless there's more information like how to reproduce this, what were you doing when this happened, is this consistent, is this an issue on stock OS or AOSP or both, etc this is going to be closed.

**Comment by r0b1n-dev** [comment]
When you just launch the 'Files' App, the default Tab is 'Downloads' and the App is not able to display anything there (as you can see in the first screenshot). I thought this might be because it has no access rights to the folder, which is not the case (as you can see in the second screenshot).
I started noticing the issue after the update to [SP2A.220405.003.2022041300](https://github.com/GrapheneOS/platform_manifest/releases/tag/SP2A.220405.003.2022041300).

**Comment by flawedworld** [comment]
We need a bug report zip from a user who is experiencing this issue. We know roughly why the issue is happening but we need to see what the logs say. Please send me a bug report zip to @flawedworld:matrix.org or email it to contact@grapheneos.org

**Comment by rbn-code** [comment]
The recent update to SQ3A.220605.009.A1.2022063000 fixed the issue.
