### ISSUE TITLE
ePDG domain resolution ignores Private DNS-over-TLS server

### ISSUE THREAD

**Issue by OpenSourceGhost** [GrapheneOS/os-issue-tracker#1143]
Regardless of whether WiFi calling is enabled or not, ePDG domain resolution ignores selected Private DNS-over-TLS DNS and uses plaintext DNS resolver specified in WiFi settings (1.1.1.1/1.0.0.1 by default), even though Private DNS server is supposed override WiFi-set plaintext DNS settings.

I don't know whether it is a bug, but if not, then it would be nice to implement enforcement of ePDG domain resolution over DoT server. 

It would also be great if ePDG domain resolution could be completely disabled when WiFi calling is disabled, at least when Airplane mode is used.

**Comment by flawedworld** [comment]
ePDG is not considered to be user facing traffic. This is by design.

**Comment by flawedworld** [comment]
https://github.com/GrapheneOS/os-issue-tracker/issues/873
