### ISSUE TITLE
add a way to have third party access to more low-level things

### ISSUE THREAD

**Issue by alexmo1997** [GrapheneOS/os-issue-tracker#1145]
Seedvault appears to be great and all, and I know that you are in progress of developing your replacement for it that will hopefully fix some of its issues but there still is a problem with the whole paradigm of having all such things depend on the OS vendor.
I have made a seedvault restore a few weeks ago to my new device and it didn't work at all. It restored some app installs so I didn't need to install them anymore, but not a single app where it would have been of use had my old user data. Nether games nor messaging apps or anything else. Meanwhile a friend of mine uses some other insecure OS as he has a Oneplus, installed magisk on that and could go this his new phone with oandbackupx very easily.
And I really see your point that you don't want to give "root" access to arbitary applications and that it breaks the android security model. But then there needs to be a way to do things like that within the android security model.
Yes, you will develop a backup system and it will hopefully fix seedvaults issues (though I doubt that you will allow users to backup apps that are not declared as backupable, which breaks a lot of them since it is now opt-in for apps to be backupable). But even so, there will always the some kind of problem that will take some time and can't be on your priority list right now and is aside from switching to another os impossible to fix for users themselves. 
I am not sure how it should be implemented but I genuinely think that it's needed.

That's my two cents on this issue, I have read a lot of comments from people of the grapheneos community that said that things like magisk are bad because they break the security model, but I have no alternative, so I just needed to get this out there and would really appreciate it if you could give me your opinion on it.

**Comment by Zanthed** [comment]
There are app APIs for apps to implement themselves as storage providers. I don't know how we can automagically make that happen for every app you install. Those root backup providers ignore the apps request on backups (allowBackup) and can break things. It also is completely incompatible with apps that use the HSM (Signal, hence why they set allowBackup to false). We're not going to implement things like root, Magisk, or anything related. We're not a power OS or developer OS. Your concerns need to be taken to the app developers. Ask them why they are opting out of allowBackup. Ask them to start targeting API 31 and setting up actual backup rules.

Any OS you use is going to depend on the OS vendor. You can't maintain an OS yourself using some weird things like Magisk. It's not how any operating system works so your initial statement doesn't make any sense.

**Comment by Zanthed** [comment]
If an app isn't going to use the already supplied APIs, there's nothing we can do about that. Majority of people's complaints are not something we can fix or solve because the app simply doesn't use the built-in APIs.

**Comment by alexmo1997** [comment]
> Those root backup providers ignore the apps request on backups (allowBackup).

For something like that I think the user should be a higher authority, if the user knows what he's doing he should be able to backup apps that specify allowBackup=false

> If an app isn't going to use the already supplied APIs
the problem is that there aren't any apis (afaik) that would enable you to do what oandbackupx does or something like e.g. luckypatcher (i wouldn't use this particular app but it's a popular example). I think a user should be able to do those things on his device if he wishes to do so.

**Comment by thestinger** [comment]
allowBackup="false" no longer disables non-cloud backups for apps targeting API 31+ (Android 12) which will be mandatory on the Play Store near the end of this year for new apps and app updates.

**Comment by alexmo1997** [comment]
> allowBackup="false" no longer disables non-cloud backups for apps targeting API 31+
what is that supposed to mean? how would the app know if the backup system uploads the backups to a cloud?

**Comment by Zanthed** [comment]
> For something like that I think the user should be a higher authority, if the user knows what he's doing he should be able to backup apps that specify allowBackup=false

Then we're not the OS for that person. It's not something that should be ignored. It's a bug if it can be ignored. There are legitimate reasons for disallowing backups. Apps may not be able to handle backups properly, especially if they use the secure element in some way. We're not going to introduce severely API breaking changes when the app developer should be using the proper APIs.

**Comment by alexmo1997** [comment]
> Apps may not be able to handle backups properly, especially if they use the secure element in some way.
well it can still fail then, but I don't understand what would be the problem with allowing the user to do things like this. you could just do it as an "developer option" so users don't do it if they don't understand the consequences...

**Comment by alexmo1997** [comment]
I don't get why you can't be both? You could just tell people that using developer options is not officially supported if people asking questions bother you that much. It wouldn't do any harm otherwise and just let people have a secure operating system while still being able to do power-user tasks.

**Comment by Zanthed** [comment]
There are many developer options in there that substantially break security and privacy features implemented by us.

**Comment by alexmo1997** [comment]
That doesn't answer my question... You already have those developer options so that's not what we are talking about.

**Comment by thestinger** [comment]
> what is that supposed to mean? how would the app know if the backup system uploads the backups to a cloud?

It's not relevant. Backup service infrastructure is implemented by the OS. allowBackup="false" no longer disables non-cloud backups for API 31+ so you simply need to wait for apps to move to API 31+ and they'll stop being excluded as a whole from backups. They can provide an API 31+ backup file exclusion list with different exclusion lists for local backups, E2EE cloud backups and cloud backups. Seedvault always acts as if it's a local backup regardless of whether it stores the data, which is fine. The separate E2EE vs. non-E2EE exclusion lists are more meant for weaker approaches to E2EE.

We plan to replace Seedvault because it's unreliable / buggy and doesn't really follow the plans we had for it including security relevant things.
