### ISSUE TITLE
Add support for Material You in Launcher

### ISSUE THREAD

**Issue by dhishkyaon** [GrapheneOS/os-issue-tracker#1147]
This was fine when there was no support for Material You in grapheneos but now it supports Material You.
I have the red wallpaper on my Pixel 4a but the launcher still has blue-ish colors that don't go well together.

**Comment by thestinger** [comment]
We're going to wait for this to get implemented upstream for the AOSP launcher. We don't plan on implementing our own UI enhancements for it.
