### ISSUE TITLE
Headphones Audio Levels

### ISSUE THREAD

**Issue by GrapheneSlut** [GrapheneOS/os-issue-tracker#1150]
USB C to 3.5mm Aux -> Vehicle 
Pixel 6 - Graphene up to date
Using Spotify downloaded music

Audio levels are very low. I checked the audio output levels in the settings and it was all the way up. Played with audio settings in Spotify and it did not enhance audio. Checked vehicle stereo no enhancement

Tests of other audio apps suggested but wanted to submit this just incase.

**Comment by flawedworld** [comment]
We don't change how it works compared to the stock OS.


Are you using an Apple USB-C adapter by any chance? It's known to be a bit quiet.
