### ISSUE TITLE
App asking location fails with 'java.lang.IllegalArgumentException: provider "network" does not exist'

### ISSUE THREAD

**Issue by chriswoope** [GrapheneOS/os-issue-tracker#1151]
In an app, redirecting location to the OS services fails with the error noted below; the app works correctly when not redirecting Play Services location to OS services and giving Play Services location permissions.

It looks like that the app is explicitly asking for the "network" provider which would work with Play Services but the OS refuses the request.

The solution should probably be to strip the argument asking for a specific provider when redirecting the request to the OS if the requested provider is not available.

It's also possible that this request is not being redirected by GmsCompat and this code is the app OS fallback code that just assumes that the OS has a "network" provider, in which case the solution is probably to have the OS ignore the request of a specific provider if it doesn't have it instead of triggering an exception (if this is case, then this probably happens because the app still assumes that the OS is using Play Services for location, so it makes sense to ignore this request, or at least give the user the option to do so)

... AndroidRuntime: java.lang.IllegalArgumentException: provider "network" does not exist
... AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2430)
... AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2410)
... AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2393)
... AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2335)
... AndroidRuntime: 	at android.location.ILocationManager$Stub$Proxy.registerLocationListener(ILocationManager.java:1445)
... AndroidRuntime: 	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:1514)
... AndroidRuntime: 	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:1194)
... AndroidRuntime: 	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:1159)
... AndroidRuntime: 	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:1130)
... AndroidRuntime: 	at com.moov.location.LocationManager.initNetworkLocationClient(LocationManager.java:125)
... AndroidRuntime: 	at com.moov.location.LocationManager.lambda$initLocationClient$0$LocationManager(LocationManager.java:59)
... AndroidRuntime: 	at com.moov.location.-$$Lambda$LocationManager$x-u0a_XR6wQqKda0S2F9YoHmBH8.onSuccess(Unknown Source:6)
... AndroidRuntime: 	at com.google.android.gms.tasks.zzm.run(com.google.android.gms:play-services-tasks@@17.2.1:1)
... AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
... AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
... AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
... AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
... AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7870)
... AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
... AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
... AndroidRuntime: 	at com.android.internal.os.ExecInit.main(ExecInit.java:48)
... AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
... AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
... AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
... AndroidRuntime: 	at com.android.internal.util.Preconditions.checkArgument(Preconditions.java:59)
... AndroidRuntime: 	at com.android.server.location.LocationManagerService.registerLocationListener(LocationManagerService.java:718)
... AndroidRuntime: 	at android.location.ILocationManager$Stub.onTransact(ILocationManager.java:585)
... AndroidRuntime: 	at android.os.Binder.execTransactInternal(Binder.java:1206)
... AndroidRuntime: 	at android.os.Binder.execTransact(Binder.java:1164)
... AndroidRuntime:

**Comment by Zanthed** [comment]
cc @muhomorr

**Comment by muhomorr** [comment]
> It looks like that the app is explicitly asking for the "network" provider which would work with Play Services but the OS refuses the request.

"network" location provider isn't present on GrapheneOS, regardless of presence of Play services.

> In an app, redirecting location to the OS services fails with the error noted below; the app works correctly when not redirecting Play Services location to OS services and giving Play Services location permissions.

On stock OS, "network" provider is Play services, but no such integration is made on GrapheneOS, regardless of the state of the "Reroute location requests to the OS" toggle.

Which app is this?

**Comment by chriswoope** [comment]
The app is com.ridemovi.app

> On stock OS, "network" provider is Play services, but no such integration is made on GrapheneOS, regardless of the state of the "Reroute location requests to the OS" toggle.

Yeah, it looks like the application assumes that either Play Services is available or that a network provider is available.

It seems the best solution is for GrapheneOS to have requests that ask for the "network" provider (and I suppose the "fused" provider as well) not fail with IllegalArgumentException, but instead use the default location provider.

**Comment by muhomorr** [comment]
> The app is com.ridemovi.app

This app doesn't let me sign in.

Missing "network" location provider is a known issue. A new issue would be if there's a crash when "Reroute location requests to the OS" toggle is on, but no crash when it's off. Can you verify that this is the case?

> It seems the best solution is for GrapheneOS to have requests that ask for the "network" provider (and I suppose the "fused" provider as well) not fail with IllegalArgumentException, but instead use the default location provider.

"fused" location provider is present, it works despite there being no "network" provider.

**Comment by chriswoope** [comment]
It always crashes unless "Reroute location requests to the OS" is off and Play Services has location permissions (all other 3 combinations crash), with the error message in the title and logcat.

My guess without trying to decompile the code is that it first tries to use Play Services and if it fails it uses a code path that asks for the "network" provider without first checking whether it's present and crashes if it doesn't exist.

It seems the best short-term solution to handle such apps is to use the default provider when the "network" provider is requested but absent, but probably still don't advertise that a network provider is present.

Another possibility would be to support third-party network providers and then ask the user to install MicroG's UnifiedNLP.

**Comment by muhomorr** [comment]
Check one more thing: grant the Location permission to Play services, toggle off "Reroute location requests to the OS" and revoke the Network permission from Play services. Check if the app crashes in this case too.

**Comment by chriswoope** [comment]
@muhomorr The app works with that setup (I also force stopped both Play Services and the app after making the changes to be sure)

**Comment by muhomorr** [comment]
Closed with https://github.com/GrapheneOS/platform_frameworks_base/commit/d00ebff61401499a193b4d7a8a6b7a190bdc96eb

**Comment by chriswoope** [comment]
The issue is indeed solved in the latest GrapheneOS release. Thanks!
