### ISSUE TITLE
Change keyboard sound to a softer click

### ISSUE THREAD

**Issue by glukonian** [GrapheneOS/os-issue-tracker#1154]
The current keyboard sound (I'm assuming the AOSP default) is a very harsh clicking sound. It is not very pleasant to listen to, and I have had family members complain numerous times that it annoys them. I think it would be better if we switched to a softer, more muted keyboard sound, like the one in iOS or LineageOS for example.

**Comment by lbdroid** [comment]
I agree that the keyboard sounds are annoying. Personally, I turn them off. The haptics (P6 Pro) are so nice that ANY sound is, in my opinion, completely unnecessary.

**Comment by GlitchBuddy** [comment]
> I agree that the keyboard sounds are annoying. Personally, I turn them off. The haptics (P6 Pro) are so nice that ANY sound is, in my opinion, completely unnecessary.

I personally find that sounds help with my typing accuracy, and the case I have applied to my phone (P5) softens the haptics so they're not as noticeable, especially when typing quickly.

**Comment by Zanthed** [comment]
I think we're going to just turn it off by default. The sound is way too subjective and differs from person to person at the end of the day where turning it off by default will make everyone happy. The former isn't hard to do.

**Comment by GlitchBuddy** [comment]
The sound is already turned off by default. This issue was aimed at people who like to have it on.

**Comment by thestinger** [comment]
Not planned. You can use an actively developed keyboard instead.

**Comment by glukonian** [comment]
> Not planned. You can use an actively developed keyboard instead.

I believe the keyboard sounds are part of the operating system. For example, Gboard uses different keyboard sounds on both GrapheneOS and LineageOS.

**Comment by thestinger** [comment]
That's entirely up to the keyboard.

**Comment by thestinger** [comment]
i.e. they can choose if they want to use sounds provided by the OS or not. We could consider replacing the AOSP sounds with the Pixel ones or something else but it's a very low priority and we're not going to keep an issue open about it. If someone wants to work on that, they can work on it.
