### ISSUE TITLE
GPS Not working with |  Pixel 6  | and the latest Build: oriole-factory-2022042600.zip 

### ISSUE THREAD

**Issue by BronxHD** [GrapheneOS/os-issue-tracker#1155]
Even after reinstalling GraphenOS GPS is not working. I opened the app, allowed GPS the green GPS Symbol aooears in the Status Bar, but the app could not locate me. I tried it many times on different locations. My other devices were all functional. In the Build from 19.04.  / 20.04 (IDK)  Gps worked for me.
Hopefully this Issue is useful to fix and not only on my Pixel 6.
best regards!

**Comment by thestinger** [comment]
You aren't stating which app you're using or what kind of configuration you're using. You should try using GPSTest.

You'll need to get support in our Matrix room and then follow it up with an issue here with more details if it can't be resolved after troubleshooting. It could simply be a hardware issue. GPS is definitely not broken on these devices.
