### ISSUE TITLE
Alternative method at unlocking device upon reboot

### ISSUE THREAD

**Issue by kenktk** [GrapheneOS/os-issue-tracker#1156]
Implementing ubikey to unlock device (optionally) in conjunction with password. Perhaps adding toggles in settings if the user desires to be required to have the HW authentication upon every unlock on certain profiles. 

Not entirely sure how hard it is to make this happen or maybe it is out of the scope of GrapheneOS, but it would be a handy security feature to have in jurisdictions that force the user to give up the password for legal reasons. 

One way it could be implemented is by taking the hash of the ubikey value and xoring it with the hash of the user's password to then unlock the user partition.

**Comment by flawedworld** [comment]
https://github.com/GrapheneOS/os-issue-tracker/issues/940
