### ISSUE TITLE
Wi-Fi button control does not represent auto disconnect status

### ISSUE THREAD

**Issue by kenktk** [GrapheneOS/os-issue-tracker#1157]
The Wi-Fi widget/button in the control center does not represent the status of the Wi-Fi service when the network was automatically disconnected by the system. 

I.e., the button shows that Wi-Fi is toggled on but when in reality it is not when you enter settings. All other widgets/buttons follow the custom that their background is darkened when not enabled. Wi-Fi does not follow this precedent.

**Comment by flawedworld** [comment]
We aren't going to change how the 12.1 UI works.
