### ISSUE TITLE
Optional build/toggle to completely disable all cellular access via driver implementation

### ISSUE THREAD

**Issue by kenktk** [GrapheneOS/os-issue-tracker#1158]
The ability to completely disable emergency calling and any cellular activity via a toggle or perhaps an alternative build of the OS by removing/disabling the drivers. 

I find myself constantly wondering about the background cellular activity of my graphene device when it shows "emergency calls only" with no sim. I run GrapheneOS on two devices, one with cellular connectivity and one without. I would prefer if GrapheneOS had a better way at completely disabling the OS's access to the cellular and any wireless modems. This is sort of a big ask but I could see it being very valuable against adversarial SIGINT. Primarily my main focus would be disabling cellular but other radios should have the functionality to do this. 
I am not very experienced in building android, and I am not sure how many things will break by disabling radios. 
Certainly a lower priority feature request.

**Comment by flawedworld** [comment]
You can disable the modem radios with aeroplane mode

**Comment by thestinger** [comment]
(for people who aren't bri'ish that means airplane mode)

**Comment by kenktk** [comment]
Does this actually disable emergency calling though? When I sign into a user it still shows the emergency calling button. Im not sure if it is disabled. Or maybe this button is there to enable cellular. Im not sure.

**Comment by flawedworld** [comment]
The button will show irrespective of what state the radios are in. If you make an emergency call, aeroplane mode will turn off.
