### ISSUE TITLE
Support user-configurable network location provider

### ISSUE THREAD

**Issue by chriswoope** [GrapheneOS/os-issue-tracker#1161]
It seems that AOSP already supports using apps as network location providers, but they need to be whitelisted by the OS.

I think it would be nice if GrapheneOS would allow the user to choose the app to use as a network location provider instead of having a whitelist, and also include an option to use the default GPS-based location provider as a network provider.

This would allow the user to either keep the current state of failing when a network provider is requested, or fall back to the GPS provider, or use Play Services as the network provider, or use MicroG's UnifiedNlp as the network provider, or use some other app of their choice.

**Comment by thestinger** [comment]
It won't be implemented. Has been explained before on the tracker.

**Comment by chriswoope** [comment]
Why? Any reference to it?

**Comment by thestinger** [comment]
You're asking to violate the Android security model. Not going to happen. You can find the issue yourself rather than having me search for it.

**Comment by Zanthed** [comment]
See https://github.com/GrapheneOS/os-issue-tracker/issues/24#issuecomment-779557444

This is not going to be implemented.
