### ISSUE TITLE
Full plaintext DNS bypass - Feature Request

### ISSUE THREAD

**Issue by OpenSourceGhost** [GrapheneOS/os-issue-tracker#1163]
If I block outbound UDP port 53 on my router (to prevent any and all plaintext DNS queries), GrapheneOS (or any other Android phone/tablet) is unable to make the initial connection to WAN and all internet is blocked, even if private DNS-over-TLS sever address is specified in Android settings. 

Once that initial plaintext DNS connection is made, DoT settings kick-in, and blocking outbound UDP port 53 doesn't prevent Android phones/tablets from resolving queries exclusively via specified DNS-over-TLS servers until disconnected.

That should not be the case. Most DNS-over-TLS servers do not require initial plaintext DNS (bootstrap) connections, allowing even the very first query to be TLS-encrypted.  The issue isn't with GrapheneOS, but with Android WiFi and/or DoT implementation. Disabling plaintext DNS completely would be a great feature to have.

**Comment by thestinger** [comment]
DNS-over-TLS servers are configured via a hostname in order to perform authentication. It's designed to be secure, not for you to be able to block port 53 connections.

**Comment by thestinger** [comment]
Also, DoT is routed via the VPN, etc.

**Comment by OpenSourceGhost** [comment]
I see what you mean. Android DoT forces use of hostnames, such as dns.adguard.com, and plaintext DNS is required to resolve DoT DNS server hostnames before DoT can be used.

The way to connect to encrypted DNS servers directly (without resolving their hostnames) is either by using SDNS stamps or by specifying encryption protocol in DNS IP address:
tls://94.140.14.14
quic://94.140.14.14
https://94.140.14.14/dns-query

Android doesn't use such methods natively and requires local VPN interface to tunnel encrypted DNS queries without resolving DNS server hostnames via plaintext DNS queries.

Anyway, the issue was indeed closed and your support was much appreciated!
