### ISSUE TITLE
GrapheneOS Launcher - rename apps, hide apps, dark theme for Contacts, add Calendar

### ISSUE THREAD

**Issue by OpenSourceGhost** [GrapheneOS/os-issue-tracker#1164]
From cosmetic point of view, the only issues I noticed in GrapheneOS are:
- Contacts part of Phone supports dark theme, but Contacts app itself does not. It isn't graphically homogenous.
- There's no way to rename apps on GrapheneOS launcher home screen and app drawer. Long app names are cut off and that looks ugly.
- There is no way to hide app names on GrapheneOS launcher home screen. Being able to hide app names (at least on home screen) improves privacy.
- Calendar app is missing and/or has no usable interface. Can't something like Etar from LineageOS become a default Calendar app for GrapheneOS?

LineageOS launcher meets the requirements above, but I can't get any versions of it to install on GrapheneOS.

**Comment by thestinger** [comment]
Each issue report or feature request needs to be filed separately, and you need to check for duplicates and existing discussions first.

**Comment by thestinger** [comment]
> Contacts part of Phone supports dark theme, but Contacts app itself does not. It isn't graphically homogenous.

Already issues about adding dark mode where it's missing.

> There's no way to rename apps on GrapheneOS launcher home screen and app drawer. Long app names are cut off and that looks ugly.
>
> There is no way to hide app names on GrapheneOS launcher home screen. Being able to hide app names (at least on home screen) improves privacy.

That really doesn't improve privacy and is a very poor argument for the feature. These kinds of things aren't being added. Trying to awkwardly to fit things into a privacy niche to convince us to add them isn't going to work.

> Calendar app is missing and/or has no usable interface. Can't something like Etar from LineageOS become a default Calendar app for GrapheneOS?

Etar has restrictive licensing, is not taking security seriously and won't be included. There isn't a good enough calendar app to include meeting our requirements, so we won't include one. There's no particular reason we have to include more than the minimal AOSP Calendar interface for viewing events in other apps. It meets the CTS/CDD requirements. If users want an app they can use to create events and directly use, they can install one. GrapheneOS doesn't need to provide one of every major type of app bundled with the OS. There's no particular reason for it and it just forces people to have storage space and bandwidth used for apps they may not want to use anyway.
