### ISSUE TITLE
Randomize IMEI number

### ISSUE THREAD

**Issue by eliottlv** [GrapheneOS/os-issue-tracker#1165]
Is it possible to create a setting to randomize IMEI number like the setting used to randomize MAC addresses ?
It would be useful to reduce user tracking by mobile network operators when changing SIM card.

**Comment by thestinger** [comment]
No, it's not possible. It's not supported by modern cellular radios and isn't the only identifier.

**Comment by thestinger** [comment]
The issue tracker is not used for support and discussion.
