### ISSUE TITLE
Location in-use by Phone Services notification - non-stop after update

### ISSUE THREAD

**Issue by OpenSourceGhost** [GrapheneOS/os-issue-tracker#1166]
As soon as I updated my Pixel 4a 5G to the latest (May 2022) version, the little green location-in-use notification in upper right corner began showing up very frequently. Sometimes every 5 seconds.  It rarely showed (if ever) before the update.

Notification says "Being used by Phone Services". Disabling/enabling general location in settings has no effect on that. Cleaning cache for Phone Services and Phone-related apps also has no effect. 

Is this a bug in the latest AOSP? I can't find any settings that can disable that notification. Some apps use location services all the time. There is no reason to notify the user of that every 5 seconds.

**Comment by flawedworld** [comment]
Fixed

**Comment by flawedworld** [comment]
see: https://twitter.com/GrapheneOS/status/1521491857578078212
