### ISSUE TITLE
flash-all.sh sh incompatible 

### ISSUE THREAD

**Issue by nestire** [GrapheneOS/os-issue-tracker#1169]
Hi 
not sure if this i the right place to report this under Ubuntu 20.04  flash-all.sh report this error 
`./flash-all.sh: 51: [: oriole: unexpected operator`

the Problem is the check  
`if ! [ $product == oriole ]`
This just works under bash but not under sh(dash) changing the shepang from /bin/sh to /bin/bash resolves the issue or changing the check to
`if ! [ $product = oriole ]`

Fix under Ubuntu 20.04 without editing the script is changing the default shell from dash to bash with 
`sudo dpkg-reconfigure dash`

**Comment by thestinger** [comment]
Resolved and the current release will be updated. Thanks.
