### ISSUE TITLE
do-not-disturb is the only function in the swipe-down menu to not require authentication

### ISSUE THREAD

**Issue by khmann** [GrapheneOS/os-issue-tracker#1170]
Pixel 5, current.  

There are so many detailed toggles like camera/mic/nfc/location status that "leak" configuration information.  Perhaps if the unauthenticated menu displayed was limited to the first page?

As the main issue, someone could access the do-not-disturb feature unauthenticated to maliciously disable notifications.  They could also just turn down the ring volume, but the difference is DND mode might limit the displayed information.

thanks!

ps I definitely want the open flashlight

**Comment by flawedworld** [comment]
>There are so many detailed toggles like camera/mic/nfc/location status that "leak" configuration information. Perhaps if the unauthenticated menu displayed was limited to the first page?

https://github.com/GrapheneOS/os-issue-tracker/issues/205

>As the main issue, someone could access the do-not-disturb feature unauthenticated to maliciously disable notifications. They could also just turn down the ring volume, but the difference is DND mode might limit the displayed information.

https://github.com/GrapheneOS/os-issue-tracker/issues/205 + someone can just turn off the phone. I don't think we will change how this works.

>ps I definitely want the open flashlight

Upstream bug, we don't change how it works.

**Comment by khmann** [comment]
I'll try and complain to AOSP about DND authentication issue then... sorry, I'm new here, and this is my first android as a primary device.

low-priority feature request then:
A more limited lock-screen?  disable swipe-down?  or, +1 disable the swipe-down "expansion" in some way, ie: strictly limit displayed widgets to 4/6/8?  If I get around to contacting AOSP I'll pitch this concept to them as well.
