### ISSUE TITLE
Firmware Question

### ISSUE THREAD

**Issue by Phantom-Wolf** [GrapheneOS/os-issue-tracker#1173]
Please forgive my ignorance, I am still learning.

A few weeks ago, I asked about a battery drain issue from network standby. You answered with stating it is a know issue related to its firmware which is up to google to fix. 

My question is if they come up with a firmware update to fix the battery drain issue, is that something you pass through with your frequent updates? If not, where do I go to get those updates from google?

Thank you for your time

**Comment by Zanthed** [comment]
GrapheneOS ships all firmware updates in each release.

**Comment by Zanthed** [comment]
The user doesn't need to do anything special.
