### ISSUE TITLE
Reported crashes when using Google Maps

### ISSUE THREAD

**Issue by Wonderfall** [GrapheneOS/os-issue-tracker#1177]
A few users have been reporting crashes when using Google Maps recently. This seems to be reproducible under these circumstances:
- Google Maps (com.google.android.apps.maps) version 11.28.2
- Sandboxed Google Play installed w/ reroute location requests enabled
- Location has to be enabled and its permission granted to Maps (no crash otherwise)

The crash should happen immediately after the app launches, seemingly when the location requests are made. It is unclear from which side the regression came from.

At first sight this seems to be an issue with the reroute location requests feature. This can be confirmed by someone using the Play location API instead. Can't invest time in debugging this at the moment but hopefully this can be reproduced by a project member or someone can send some logs.

**Comment by thestinger** [comment]
Does it crash when not rerouting location requests?

cc @muhomorr

This is probably just a limitation of the rerouting feature.

**Comment by flawedworld** [comment]
Confirmed to be a bug with location rerouting, crash does not occur with it disabled.
