### ISSUE TITLE
auto-rotation not working -- pixel 6 pro

### ISSUE THREAD

**Issue by lbdroid** [GrapheneOS/os-issue-tracker#1178]
I have autorotation enabled (settings/display or quick access tile).

When rotating screen in any rotatable application, nothing happens.

It used to show an icon on the navigation bar when physocally rotated that could be tapped to cause the screen to rotate. It no longer appears.

**Comment by thestinger** [comment]
You likely messed with OS component permissions and disabled Sensors for a critical OS component. You'll need to reset app settings.

**Comment by lbdroid** [comment]
I did nothing of the sort. Have not touched permission on anything.

**Comment by lbdroid** [comment]
![Screenshot_20220507-164844](https://user-images.githubusercontent.com/3372230/167271246-19decfee-44bc-466b-b5c2-7ba788d62a3b.png)

**Comment by lbdroid** [comment]
As you can see, sensors are available to everything except for 3 things that definitely dont matter. This list includes system.

**Comment by thestinger** [comment]
And developer options are disabled?

**Comment by flawedworld** [comment]
Cannot reproduce on my Pixel 6.

**Comment by lbdroid** [comment]
Shoot, is there something in developer options that would cause this or something I can do to figure out what's going wrong? I hope it isn't a wipe-to-fix situation or hardware failure.

**Comment by thestinger** [comment]
Try turning it off since that resets many of the options.

**Comment by lbdroid** [comment]
I've tried that, no effect.

**Comment by lbdroid** [comment]
This is from "sky map" (f-droid). 

![Screenshot_20220507-172959](https://user-images.githubusercontent.com/3372230/167272299-f29da3ea-8ba6-4317-8def-a67369208337.png)

**Comment by thestinger** [comment]
This sounds like a hardware issue (accelerometer, etc. not working). Don't think we can do anything about it.

**Comment by lbdroid** [comment]
A hardware issue shouldn't manifest as reporting that the sensors are unavailable.

**Comment by thestinger** [comment]
Why wouldn't it do that if the sensor module is broken?

**Comment by lbdroid** [comment]
Because it makes no sense. Its a defined feature of the device, why would it ever claim that its not even present?

In addition, dumpsys sensorservice looks pretty normal, makes no suggestion that anything is missing/disabled/broken.

**Comment by lbdroid** [comment]
Every application that should be able to read sensors (but doesn't) has this error (logcat);

```05-07 18:43:17.103  1411  3806 W ServiceManager: Permission failure: android.permission.HIGH_SAMPLING_RATE_SENSORS from uid=10159 pid=8283```

**Comment by lbdroid** [comment]
Seems to be a hardware problem. I gave in and tried factory reset. No help. Rolled back to a build of graphene that I know I previously had working rotation. No help. Tried factory image. Still didn't work.
