### ISSUE TITLE
Google Pixel 6 Battery Share (wireless charging) Feature missing/not working

### ISSUE THREAD

**Issue by EthOverFlow** [GrapheneOS/os-issue-tracker#1180]
Google Pixel 6
GrapheneOS 12

Hello,

I just figured out, that the Battery Share Feature is missing in GrapheneOS or not correctly showing up in the settings.

Does the Google API block this feature or is it just a bug?
In the more shitty Android from Google its working with Battery Share.

Regards and thanks!

**Comment by thestinger** [comment]
https://github.com/GrapheneOS/os-issue-tracker/issues/455
