### ISSUE TITLE
Implementation of Stock OS Battery Saving Features

### ISSUE THREAD

**Issue by heuwerk** [GrapheneOS/os-issue-tracker#1182]
Hello,
is it possible to implement the stock OS power saving modes in GrapheneOS?
Namely the extreme power saving mode and the adaptive charging to 100% until the alarm clock rings.

**Comment by ThatOneCalculator** [comment]
Sorry for necroing, but does extreme battery saver really require Play Services? ProtonAOSP had it, even on the 100% degoogled version.

**Comment by ThatOneCalculator** [comment]
Again, why is this not planned? I find myself sometimes running out of battery sooner than I should be on GrapheneOS.

**Comment by thestinger** [comment]
Extreme Battery Saver isn't part of AOSP.
