### ISSUE TITLE
Wired Headphones Timeout - Cut off after 30 minutes

### ISSUE THREAD

**Issue by SenorFusion** [GrapheneOS/os-issue-tracker#1183]
Do USB accessories have a timeout period? I think the system is removing my wired headphones after a certain amount of time. This has happened consistently the same way many times, not just on recent releases.

Steps to repeat:

- USB accessories set on "Allow new USB peripherals when unlocked"
- Unlock phone
- Plug in wired headphones
- Put phone in pocket and go for a walk while listening to podcast
- In almost exactly 30 minutes the headphones will cutout and not work

Current steps to fix:

- Unplug headphones
- Unlock phone
- Replug headphones
- Restart audio

Device:

- Pixel 6
- Latest Graphene
- The headphones are a headphone / mic combo like the old wired apple headphones

**Comment by thestinger** [comment]
No, there's no timeout. A consequence of not allowing new USB peripherals when locked is that if they disconnect for any reason like the USB device resetting itself or going into a deep standby mode which makes it go away and reappear as a new USB device, it won't be picked up again. If you can't reproduce it with new USB peripherals always allowed, that's the reason.
