### ISSUE TITLE
Home button extremely slow when using multiple users

### ISSUE THREAD

**Issue by bcarter24** [GrapheneOS/os-issue-tracker#1184]
Using a pixel 6 pro. Very snappy and responsive, however after adding second user profile, and setting up that profile, when on any screen except the launcher home screen the center "home button" using three button navigation, it takes around 4 seconds for the phone to respond and exit to the home screen. Before adding a second profile, it was instantaneous. Switching back to owner profile the issue carried over and now happens on both profiles.

**Comment by Nesslyquik** [comment]
To add more detail (same phone, same issues): 

The issue doesn't happen after a restart until I log into the second user. The issue only happens on the main owner profile, though. App switching and going home on the second profile works as intended.

My second user has GSF running, not sure if that matters.

When the issue occurs, I swipe up from the bottom to go "Home" and the screen flashes black like it's going to work, then the app I was in appears again as a static image for 3 or 4 seconds (I cannot interact with the app, it is just like a screenshot of the screen the moment I triggered the Home function appears). Then, the phone shows me my home screen. 

Restarting the phone clears the issue. 

The issue does not always occur after logging into the second profile. I seem to notice it many hours after the last restart I did to fix the issue the last time it happened, so it may have to do with the OS and/or apps being used over time. I cannot verify that, though, but maybe others can confirm.

Hope this helps! I'm not an OS designer, I'm barely learning Python right now, so I don't know what else to say. I just know that the more information, the better, for troubleshooting issues!

**Comment by Maelstr0mX** [comment]
I confirm, I have the exact same issue on a Pixel 5.
The only way to "fix" the issue is either to restart, or "end session" of the other user. 

It only happens once I go back to my main profile and not while I'm using a secondary profile though.

**Comment by ToddCrimson** [comment]
I can confirm same issue.

**Comment by 1C4K3** [comment]
Confirmed this issue on a Pixel 6. 

The problem occurs when switching back from a second profile session to the main profile. Navigating from any app to the home screen takes a good 5 seconds. Ending the second profile session did not resolve the issue for me. Only a full restart stops it from happening.

**Comment by SimplyBacon** [comment]
I also have this issue on pixel 6 pro.  I have tried ending the other user session but my owner profile is still exhibiting issues.  A restart seems to clear it.

**Comment by thestinger** [comment]
Let us know if this is still an issue on Android 13.

**Comment by rand64** [comment]
> Let us know if this is still an issue on Android 13.

I am running a Pixel 6 Pro, for the last couple of updates it has been a lot worse. I still have to reboot after switching from the second profile to the first profile.

**Comment by SimplyBacon** [comment]
> Let us know if this is still an issue on Android 13.

Mine has been working correctly now.

**Comment by ryanameier** [comment]
I'm still noticing this issue, its just less frequent, typically happens if you switch between users multiple times. It also seems to effect the primary user and not the secondary user for just about everything (opening apps, closing apps, multiple page view etc). Sometimes app menu will not display, but when you click on the screen it opens an app from the tray that would of been there
Restart still fixes the problem as always

**Comment by rknb** [comment]
This happens on a brand new Pixel 7a on Android 13.

**Comment by frenchmustard** [comment]
Pixel 7 Pro here (latest ver OS), happens to me to after setting up a second profile and switching a couple of times. So not directly after setting up a profile and switching, but definitely after switching like 3/4 times minimum.

The home button will not respond for approximately 4 seconds and then respond. The app drawer also sometimes lags and does not show all the active apps. Seems like the profiles have something going on between them.

**Comment by rknb** [comment]
> Pixel 7 Pro here (latest ver OS), happens to me too after setting up a second profile and switching a couple of times. So not directly after setting up a profile and switching, but definitely after switching like 3/4 times minimum.
> 
> The home button will not respond for approximately 4 seconds and then respond. The app drawer also sometimes lags and does not show all the active apps. Seems like the profiles have something going on between them.

I had success in the stock OS to have one, and only one, Google-account linked to each profile. They're different Google accounts too. This helped me when I had this kind of lag.

**Comment by frenchmustard** [comment]
> > Pixel 7 Pro here (latest ver OS), happens to me too after setting up a second profile and switching a couple of times. So not directly after setting up a profile and switching, but definitely after switching like 3/4 times minimum.
> > The home button will not respond for approximately 4 seconds and then respond. The app drawer also sometimes lags and does not show all the active apps. Seems like the profiles have something going on between them.
> 
> I had success in the stock OS to have one, and only one, Google-account linked to each profile. They're different Google accounts too. This helped me when I had this kind of lag.

I have only 1 Google account linked and it's to the main profile.

**Comment by ProgrammerWhoPrograms** [comment]
Issue has returned for me in UP1A.231005.007.2023103100. Also occurs with the button for the app switcher.
