### ISSUE TITLE
Feature Request / Question: Peferred Network 4G + 5G

### ISSUE THREAD

**Issue by heuwerk** [GrapheneOS/os-issue-tracker#1190]
Hello GrapheneOS developers,
thank you very much for your hard work! I have a question regarding the preferred network type.
From a privacy perspective, would it make sense to expand the "4G only" option to "4G + 5G only" to increase speed? 
Apart from the higher bandwidth, are there any advantages of 5G over 4G at all?
Thanks in advance for an answer

**Comment by thestinger** [comment]
We don't currently plan to add a 4G + 5G mode. We'll eventually add a 5G only mode in all likelihood but at the moment it uses a lot more power and not broadly available enough for 5G only to be practical for most people.
