### ISSUE TITLE
Phone randomly called emergency services by itself

### ISSUE THREAD

**Issue by TheMCNerd2017** [GrapheneOS/os-issue-tracker#1192]
I was just using my phone normally when it out of nowhere it randomly called emergency services. I have no idea how or why it did this, it just suddenly opened the calling interface showing that it was calling 911. I was never in the dialer app, nor was I on the shutdown screen where there is an emergency button. I also never pressed the power button either when this happened.

Nothing has access to the Phone permissions except for the stock OS apps like Phone and Contacts.

Device: Pixel 4 XL
OS: GrapheneOS 12 (SP2A.220505.002.2022051100)

**Comment by flawedworld** [comment]
I don't see how this is possible without you either hitting the UI // buttons for it accidentally or an app dialling it. Nobody has ever reported this so it's likely one of the former.

**Comment by TheMCNerd2017** [comment]
> I don't see how this is possible without you either hitting the UI // buttons for it accidentally or an app dialling it. Nobody has ever reported this so it's likely one of the former.

I never pressed any buttons on my phone when this happened, and no apps on my phone have the Phone permission except for the usual apps included with GrapheneOS. I didn't even open the power menu. 
I'm guessing it was just an unlucky bitflip in RAM that caused this to happen.

**Comment by blackravensail** [comment]
This also happened to me, twice in the span of two minutes with the phone screen off in my pocket. Stopped on reboot. No record in dial app of calling emergency services. No indication of dialing emergency services. I just twice received a call back from them.
