### ISSUE TITLE
Option to sign into any user profile from the lock screen immediately after reboot

### ISSUE THREAD

**Issue by danielkauffman** [GrapheneOS/os-issue-tracker#1193]
I'm very experienced with Debian, but I'm new to using multiple profiles on Android, and I'm not understanding the UX.

First, after rebooting, I'm forced to sign into the owner profile before having the option to sign into any other profile.

Second, after successfully signing into the owner profile, and returning to the lock screen, I'm able to swipe down, click the user icon, and choose which profile to sign into.

If I describe signing into a Linux box in terms of the above experience instead of the typical experience: I would first to sign in as root, then lock the session to return to the greeter. From the greeter, I would use a hotkey that would allow me to choose a restricted user. Finally I would sign in.

Instead of this owner-then-lock-then-user dance: On the lock screen, why not simply show multiple profiles, click the one you want, and then sign into that profile? Is this feasible? Perhaps I'm not understanding something about the security model that would make this infeasible?

If the goal of the dance is to require special unlock after each boot, a possible solution would be an option for a boot unlock PIN / password which would be followed by a greeter showing all of the profiles.

Is the UX simply a historical artifact due to a lack of user profiles in some ancient version of Android?

Thanks for any clarification!

**Comment by Zanthed** [comment]
Not possible. The owner profile stores sensitive system-wide configuration that all users need to access and requires the owner profile to be decrypted.

**Comment by thestinger** [comment]
Encryption is per-user-profile and many OS services keep their data in the Owner profile. Signing into the Owner profile is also integrated with the secure element on Pixels beyond just integrating it into disk encryption and the hardware keystore. In addition to firmware signature verification and downgrade protection, the secure element requires that the Owner user authenticates successfully before it will allow updating the firmware. This provides the insider attack resistance feature.

> Is the UX simply a historical artifact due to a lack of user profiles in some ancient version of Android?

Not really. Encryption didn't used to be per-user and there wasn't an insider attack resistance secure element feature. It may have actually be possible to do what you're requesting in the past, but it isn't with the current approach. It was introduced as the current approach to these things.

> If I describe signing into a Linux box

Android is Linux.

> I would first to sign in as root, then lock the session to return to the greeter

Apps running within the owner user have no special access. They each run in their own app sandbox indistinguishable across users. The Owner user does not have the ability to access data of other users or mess with them beyond configuring the UserManager settings such as whether they can install apps or adding / remove them. It's not at all comparable to using root. The user-facing difference for the Owner user is that the privileged Settings app allows the Owner user to access more functionality. That's the extent of the additional access you receive there. It isn't a non-restricted user and can barely do more than a secondary user. Apps cannot do anything more.

**Comment by danielkauffman** [comment]
Thank you both for the clarifications, very helpful.
