### ISSUE TITLE
eSim activation not working

### ISSUE THREAD

**Issue by soinu** [GrapheneOS/os-issue-tracker#1196]
After https://github.com/GrapheneOS/os-issue-tracker/issues/159 has been implemented I tried to activate an eSim. I installed all 3 google apps but after scanning the eSim QR code the process is stuck at "Checking network info..."

Also tried the test profiles from https://source.android.com/devices/tech/connect/esim-test-profiles but phone stucks at the same step.

Please let me know how we can debug this any further and if you can reproduce it

**Comment by flawedworld** [comment]
If you are on a carrier specific device, there is a known issue which we inherit from the stock OS where you may not be able to activate an eSIM.

You can try toggle DSDS on/off by dialling ```*#*#4636#*#*``` then -> Phone information -> and play with the DSDS toggle and try to activate.

**Comment by soinu** [comment]
I don't think I am on a carrier specific device, how can I check?

> You can try toggle DSDS on/off by dialling *#*#4636#*#*

I can't dial this number, it shows "Vodafone Message: Connection problem or invalid MMI code"

**Comment by soinu** [comment]
Just to let you, and maybe further people finding this issue, know: After enabling DSDS the eSIM activation worked!

**Comment by bruttel** [comment]
Hi 
I experienced the same behavior when I wanted to add an eSIM on my updated Phone. 
I then took a phone I Installed everything back in March and did no updates since. Adding eSIM worked like a charm. 
So I decided to make a backup and restore it on the Phone that was working. Unfortunately the eSIM is disapeared after the restore... 
I then did factory reset, also i erased all downloaded SIM's and tried again. (On the phone where it initially worked...). No Success. 

Now it's getting interesting, I reinstalled GoogleOS -> eSIM found! 

So my questions are -> Why is the deleted eSIM still there? What happend in the releases between March and Now, that adding eSIM is not working any more...

**Comment by thestinger** [comment]
We have information on eSIM in the usage guide. Nothing about this has changed.

**Comment by bruttel** [comment]
According to your comment I guess I was not describing it well...
- Phone 1, Pixel 4, Release SQ3A -> eSIM Registration does not work. 
- Phone 2, Pixel 4, Release SP2A -> (same) eSIM Registration worked like a charm. 

Taking Backup from Phone 1, Restoring on Phone2 (Automatically it got Release SQ3A) -> eSIM disapeared... 
Also Installing (new QR Code) eSIM on Phone2 does not work any more. 

Also tried on Phone 2 (Now with SQ3A): 
1. Settings -> System -> Options to reset -> delete downloaded SIM -> Adding new eSIM still not possible
2. Settings -> System -> Options to reset  -> Factory Reset -> Adding new eSIM not possible
3. Reinstalled Google OS -> eSIM is magically back in place 

So at least we can say Point 1 does not work...
And I would say something between SQ3A and SP2A also changed... 

I am happy if I can assist with other details or Logs, if you think this is an issue. 

I think my next steps will be reinstalling GrapheneOS and doing this D2DS using *#*#INFO#*#* or *#*#4636#*#* ...

**Comment by bruttel** [comment]
I can confirm with using *#*#4636#*#* and doing D2DS I was able, on 
Phone 1, Pixel 4, Release SQ3A 
-> Register the eSIM without any issue. 
@thestinger, may I propose to add this hint for the eSIM in the usage guide?

**Comment by Poryhack** [comment]
I had the same problem and it was resolved by enabling DSDS as detailed above. Should definitely be added to the usage guide until the bug in question is fixed.

Can anyone provide insight into what exactly DSDS is and if it should be left on or even enabled by default?

**Comment by Zanthed** [comment]
@Poryhack https://support.google.com/pixelphone/answer/9449293?hl=en

**Comment by supersophie** [comment]
Tried ##4636## and got "_mobile network not available_"

This is on a Pixel5 running Android 14 latest Grapheneos release . Now EOL.

Any ideas?

**Comment by supersophie** [comment]
Hi.

I clicked on the 
  network & management
    eSIM support = enable
