### ISSUE TITLE
Protect against evil maid device replacement attacks

### ISSUE THREAD

**Issue by chriswoope** [GrapheneOS/os-issue-tracker#1197]
Currently an attacker can steal a GrapheneOS smartphone and replace it with an identical device running a version of GrapheneOS modified to send the unlock password to the attacker after it's typed in.

The user will then type in the password (being unable to notice the replacement), the modified phone will send it to the attacker and the attacker can then use it to unlock the original stolen phone and have full access to it.

A similar attack could perhaps be done against fingerprint unlock, with a device that has been modified in hardware to send pictures of the fingerprint to the attacker (either by hijacking the wires from the existing fingerprint sensor, or adding an additional under-display camera), or possibly by just lifting a fingerprint from the stolen device itself.

Unfortunately protecting against this attack is quite hard, because it will always succeed if all inputs and outputs of a phone can be recorded and replayed remotely good enough for the user to not notice the difference, and for any authentication method to succeed anyway, which is unfortunately the case at least potentially with the screen, audio and flashlight outputs and for the touchscreen, microphone, camera, fingerprint sensor and misc sensor inputs.

The only good solution I can think of is to require an USB-C device to be inserted in the device to unlock it with a signed challenge/response protocol for authentication, and prevent relaying it remotely by requiring that roundtrip times are fast enough to make such relaying impossible.

Once the USB-C key is authenticated with low roundtrip times, the device can show a custom message or picture, and the user can proceed with the normal unlock method. This defeats the attack because the attacker cannot obtain the custom message or picture and will be unable to show it on the smartphone screen (because they can't relay the USB-C communications fast enough for the stolen smartphone to not notice the relaying due to latency) and the user will thus notice that the device has been replaced and won't type the password or fingerprint unlock it.

Another option is to ask the user to unlock the phone in some sort of Faraday cage bag, so the password or fingerprint cannot be relayed, although it's not clear if that's feasible.

**Comment by thestinger** [comment]
This isn't a valid issue because there's no actionable proposal for a solution. Please don't file issues about generic topics rather than specific bug reports or feature requests.

It's not valid to prevent people from unlocking their device and accessing their data because it responds slightly slower than expected. Latency to a nearby device is far too low for that to be a viable approach to this.
