### ISSUE TITLE
Block upgrade reboots before alarms

### ISSUE THREAD

**Issue by jpds** [GrapheneOS/os-issue-tracker#1198]
I've had my phone reboot during the night with every single upgrade for the past two months.

The "Automatic reboot" toggle has been off the entire time, so I do not know why this is happening. At the same time - I think that there should be some integration between the upgrader and the alarms so that if there's an alarm in ~9 hours whilst one is sleeping - they don't then go onto miss the alarm.

**Comment by thestinger** [comment]
Clock app supports Direct Boot for alarms so that shouldn't be an issue unless something is wrong with it.

I don't see a reason that the device would reboot other than the idle reboot feature or auto-reboot feature. It's not reproducible without it.
