### ISSUE TITLE
Proposed Feature: Restricted networking

### ISSUE THREAD

**Issue by ddevz** [GrapheneOS/os-issue-tracker#1199]
**Concept:**
Basically, the idea is to separate the permissions of "app is allowed to connect to servers that I own" from "app is allowed to connect to any server on the internet"  (I.E. the app is allowed "dial home")

**One way to do it:**
Similar to the "connect to 802.11" button in the pull down menu, there could be a "connect to restricted 802.11", which would basically connect to the 802.11, but then add something like a iptables rule of "if destination is not 192.168.0.0/16 and destination is not 10.0.0.0/8 then DROP"
The idea is that anytime this is active, then *no* apps can connect to a system that you do not own

Then in addition to having a "networking" permission for apps, a "restricted networking" permission for apps could be added.  When granted, the restricted networking permission would allow apps to access the network if (and only if) the "restricted networking" is connected to (and 5G is not connected).  Those apps that have the general "networking" permissions would be allowed to access the network when any network (802.11, restricted 802.11 or "the G's" (I.E. 4G, 5G, etc)).

**Comment by ddevz** [comment]
Oh Hey, I just realized who I'm talking to!  

First, I would like to thank you for all your work developing GrapheneOS.  From what I've heard you've put a ton of effort into making it happen, and features like ability to deny "indirect access via OS components and apps enforcing the INTERNET permission" sound really awesome.  (I ran into that issue on LineageOS )


> It would have be added everywhere exposing an API requiring INTERNET and we can't do that for apps outside GrapheneOS.

Good point.  I hadn't thought about all the apps having to be changed.
I'll try to come up with a better approach.  (If I do come up with a better approach, should I post it here as a addition to this post, or as a new issue?) (I'm not sure if after a github issue is closed if people still get notified of new comments on it)

**Comment by thestinger** [comment]
The only way I can see to implement it would be revoking the INTERNET permission and then having a less powerful form of the INTERNET permission which we could add as an alternative to each API using it. It would be a lot of work to add all those checks everywhere the permission is used because they need to check the destination against requirements not just check a permission.

**Comment by thestinger** [comment]
I think it's just too much work for something too niche. In general, anything that's trusting everything on the local network is broken / insecure. There's also always the option to use a VPN app with all traffic forced through it and a feature for allowing certain traffic through to the local network which could be on an app-by-app basis.

**Comment by ddevz** [comment]
> There's also always the option to use a VPN app

I assume we are talking things like netguard?  Traditionally the problem with things like netguard is that in my experience, android will automatically resume network connections after a reboot, which is *before* the VPN/firewall gets loaded and allows communications.  (I'm guessing that GrapheneOS keeps networking disabled until after it loads its own firewall, but then resumes the connections automatically).

However I have no idea how the "boot sequence" in profiles work.  If a VPN is registered in a particular profile, and "always on" is selected, does GrapheneOS guarantee bring up the VPN before any traffic is allowed out of the user profile applications?

**Comment by thestinger** [comment]
You need to have the block connections without VPN toggle enabled and then it works properly. That works the same as in AOSP. Our own Network toggle has no issues like that either.

**Comment by ddevz** [comment]
> You need to have the block connections without VPN toggle enabled and then it works properly. That works the same as in AOSP. Our own Network toggle has no issues like that either.

Thanks.  I'll investigate how that works in AOSP and see if I can figure things out from here.  Thanks so much!
