### ISSUE TITLE
Adaptive Brightness defaults to 50% in dead of night

### ISSUE THREAD

**Issue by alternativesurfer** [GrapheneOS/os-issue-tracker#1200]
Hi, 

It seems that no matter the external light level at night....my phone's adaptive brightness starts at 50% when unlocking it late at night, even when Extra Dim is enabled.
Pixel 3 (and 6 Pro)

Build: SP1A.210812.016.C1.2022051100

![signal-2022-05-17-133350](https://user-images.githubusercontent.com/10135929/168905502-3d0626b0-ced2-4087-b17a-7d26b3882c30.jpeg)

**Comment by thestinger** [comment]
It's working as intended and we don't plan to change it.
