### ISSUE TITLE
Can't receive sms in secondary profile and some calls only received on this one

### ISSUE THREAD

**Issue by Aetaugan** [GrapheneOS/os-issue-tracker#1201]
Hello,

**Set up**
I currently have two profiles, the primary (which I use daily) and the secondary with google services enabled. The setting for receive calls and sms on the secondary profile is enabled.

**Problem 1**
I generally cannot receive sms on the secondary profile, either with the native app or the "Silence" sms app.

**Problem 2**
Also, very recently I received a call on the secondary profile that I did not receive on the main profile. This is only for Microsoft support calls (?), other calls are received on both profiles.

I actually don't know why it's acting like that, any idea ?

Thanks !

**Comment by thestinger** [comment]
Silence is obsolete, unmaintained and insecure. Most third party SMS apps don't work for receiving in secondary users. That's why it's not working. You should switch back to the Messaging app from the Silence app ASAP because that's insecure.

**Comment by Aetaugan** [comment]
Thank you for the advice about Silence which I did not know. However, please do not close this ticket as it does not solve my problems. I cannot receive sms on the secondary profile even with the NATIVE application. Also, there is a second problem which is not about sms but about calls on the secondary profile.

**Comment by thestinger** [comment]
Set it back to Messaging for both owner and the secondary user and reboot first. It's known that SMS notifications on secondary profiles aren't consistent but as long as you have it configured correctly in user settings you should be receiving them. Look at the user settings.

**Comment by Aetaugan** [comment]
Well I deleted Silence from both profiles and I realised that I have not SMS native app on the owner one ! Is there somewhere I can download it again ? I don't see it in the GrapheneOS store.
Plus : I have SMS notifications now on the secondary profile but I still can't see them

**Comment by thestinger** [comment]
It isn't possible to uninstall OS apps from the OS GUI and the Messaging app can't be disabled with the UI. It sounds like you made changes with ADB in which case it's your responsibility to keep track of all the changes, to avoid broken changes and to know how to revert them. It sounds like you've caused this problem that way.

**Comment by Aetaugan** [comment]
Yes, good point, thanks! Actually, the "SMS/MMS" application was disabled and affected other profiles, but now it works again. 

I'm not sure if it solved the second problem but I can't test it again, so we'll see next time. Thanks for your support! Keep up the good work, GrapheneOS is awesome.
