### ISSUE TITLE
Zello Walkie Talkie App - Cannot receive voice/text messages

### ISSUE THREAD

**Issue by gouger05** [GrapheneOS/os-issue-tracker#1202]
Hello,

Hardware: Pixel 3A
App:  [Zello App  https://play.google.com/store/apps/details?id=com.loudtalks&gl=US](https://play.google.com/store/apps/details?id=com.loudtalks&gl=US)

Issue:
App will not receive voice comms from others or text messages from others
I can send them just fine to others.  All permissions requested by the app are granted.  Tested on other non-graphene phones without issue.

The app also has an "Echo" contact for testing.  Messages cannot be received here either.

Thank you.

**Comment by thestinger** [comment]
Have you tested it with sandboxed Google Play, correctly installed / configured before installing this app?
