### ISSUE TITLE
Remove usage of android.net.NetworkInfo in Wi-Fi timeout code

### ISSUE THREAD

**Issue by flawedworld** [GrapheneOS/os-issue-tracker#1205]
It's deprecated since API 29. See: https://developer.android.com/reference/android/net/NetworkInfo

**Comment by muhomorr** [comment]
Implemented:
https://github.com/GrapheneOS/platform_frameworks_base/blob/SQ3A.220705.004.2022080500/services/core/java/com/android/server/ext/WifiAutoOff.java
