### ISSUE TITLE
Contacts opens a webpage with google maps when pressing the directions arrow

### ISSUE THREAD

**Issue by leonlag** [GrapheneOS/os-issue-tracker#1206]
When you press the directions arrow on a contact address it opens up a browser instance with google maps. I feel like the user should at least be warned that they will be redirected to a external google service. This doesn't happen when you press on the address itself, that opens up my map app(organic maps) though not at the correct location.

**Comment by flawedworld** [comment]
https://github.com/GrapheneOS/platform_packages_apps_Contacts/blob/12.1/src/com/android/contacts/util/StructuredPostalUtils.java#L38

**Comment by Zanthed** [comment]
That means we cannot change it unless the postal address can be understood by other services and we would want a setting in Contacts.

```
    public static Uri getPostalAddressUri(String postalAddress) {
        return Uri.parse("geo:0,0?q=" + Uri.encode(postalAddress));
    }

```

**Comment by flawedworld** [comment]
fixed
