### ISSUE TITLE
USB OTG is limited

### ISSUE THREAD

**Issue by ChrisBre** [GrapheneOS/os-issue-tracker#1213]
I have a trekstor SSD that I use as an external usb device. Filesystem is exFAT an disk space is 256GB. This device is not recognized by my Pixel 3a with build SP2A.220505.002.2022051100.
The same USB OTG device is recognized by any computer and also by my oneplus 3T running LOS 18.1. 
I suppose this is a matter of disk space? A similar SSD with 64GB is recognized by the Pixel 3a@grapheneos

**Comment by flawedworld** [comment]
Neither the exFAT kernel driver nor the FUSE implementation is used in production on Pixel devices.

If it's a matter of the device itself not being recognised at all by the OS, see: https://grapheneos.org/usage#usb-peripherals

**Comment by thestinger** [comment]
exFAT will probably be supported on newer Pixels at some point but it hasn't happened yet and we aren't going to be adding it ourselves since it would be adding kernel attack surface unless a new FUSE implementation was made.

**Comment by heyheyhello** [comment]
Is this now upstreamed? I didn't see it listed in the docs. I have a exFAT 1TB drive thst works on my friend's Samsung but on my Pixel 5A under Graphene returns "Issue with WD USB" notification and opens a full page dialog about needing to format the device before it can be used.

Android 13
Build `TQ2A.230305.008.C1.2023040400`
Kernel `4.19.261-g0360d746b689 #1 Thu Mar 30 08:50:39 UTC 2023`

**Comment by heyheyhello** [comment]
Drat ok, thank you! I'll look into Graphene's docs on building from scratch and see if there's a way forward.
