### ISSUE TITLE
Mouse cursor not appearing on GrapheneOS

### ISSUE THREAD

**Issue by S1BIOSE** [GrapheneOS/os-issue-tracker#1215]
Hi, I have a Logitech MX Keys keyboard and a Logitech MX Master 3 mouse.
They are both connected via bluetooth on my Pixel 6 with GrapheneOS.
The keyboard works, I can enter text, but the mouse does not work. The cursor does not appear.

Is it possible to use a mouse with GrapheneOS ?

I hope that one day it will be possible to enjoy Android 12L on an external screen, replacing a computer. It's so much more intuitive, secure, private and modern.

**Comment by thestinger** [comment]
Using a mouse is supported and should be working for you. Try using a USB mouse to see if it's working. You can use the adapter shipping with the phone if you only have mice with USB-A.

**Comment by S1BIOSE** [comment]
I have already tested this and it does not appear. It connects via bluetooth but the cursor does not appear. If I plug it in usb-c the cursor does not appear. It's really weird, I searched in the settings but I really don't

**Comment by flawedworld** [comment]
Cannot reproduce with Logitech G602 connected via USB OTG cable.

**Comment by S1BIOSE** [comment]
Apparently the USB cable is only for charging. Could there be a problem with bluetooth mice on GrapheneOS, because in the video below the old model seems to work on Android :
https://www.youtube.com/watch?v=ipNw_6hsZK4

**Comment by flawedworld** [comment]
Unable to reproduce with Bluetooth mouse.

**Comment by S1BIOSE** [comment]
@flawedworld You mean it worked with your bluetooth mouse ? Or that you have not tested with a bluetooth mouse ?

**Comment by flawedworld** [comment]
It works fine with a Bluetooth mouse. It's likely that the mouse is either doing something non-standard or has an issue.
