### ISSUE TITLE
Introduce a feature against unsolicited calls and SMS/MMS

### ISSUE THREAD

**Issue by S1BIOSE** [GrapheneOS/os-issue-tracker#1217]
This is a feature request. I would like to have on GrapheneOS a kind of firewall for unsolicited calls, SMS and MMS.
Would it be possible to add an optional option in the GrapĥeneOS settings that allows you to block all calls, SMS and MMS from phone numbers that are not in the contact list ?
Scam and canvassing campaigns by phone have become hell for some years, despite the laws (it has no effect).
There are solutions on the play store, with applications that indicate if the call is spam. But applications that do this are themselves spam, so it's not a solution.

I think the best option would be to let the GrapheneOS user block all numbers except those in their address book.

**Comment by flawedworld** [comment]
Blocking calls from numbers not in the Contacts list is already a feature and can be found at:

Phone -> 3 dots in top right -> Settings -> Blocked numbers

**Comment by S1BIOSE** [comment]
Ok thanks, I never noticed that. What does "block calls from unidentified people" mean? Only the numbers present in the "Contacts" application are authorized?

**Comment by S1BIOSE** [comment]
I found it, thanks for the info. I'll be quiet with that

**Comment by thestinger** [comment]
I don't think that option blocks non-contacts.

**Comment by thestinger** [comment]
We might already have an open issue requesting a feature to block people not on your contacts list though.
