### ISSUE TITLE
App Battery Settings are set to optimized after updates, media access permission are revoked after update

### ISSUE THREAD

**Issue by RueleuR** [GrapheneOS/os-issue-tracker#1219]
There are 3 battery profiles for most of the apps possibel: unlimited, optimized and limited. Most of my apps are set to limited. The default value ist optimized.

It noted that after every system update (not app update) this setting is reset to optimized for every app. It seems to me that apps are not altered when the option is set to unlimited.

The per app permission setting for file and media access has a similar behavior. The permissions are revoked after every update.

I updated my OS today but it happend already in the past.

**Comment by thestinger** [comment]
This is an AOSP issue triggered by your configuration. There are numerous other closed issues referring to it.

**Comment by catdevnull** [comment]
What are those closed issues? I can't find them.
