### ISSUE TITLE
Device stays in OTG charge mode

### ISSUE THREAD

**Issue by FetchFast** [GrapheneOS/os-issue-tracker#1223]
Steps to reproduce:

1) Install a fresh flash of GrapheneOS. 

2) Remain on the STABLE channel. Go through the initial setup wizard, including WiFi

3) Attempt to charge the device using a chargie from chargie.org using a non-standards compliant cable. 
**Other devices may cause this problem too**, perhaps even  with a good cable. I will add detail as I test this further

4) GrapheneOS will then switch into "Charge plugged device" and will not charge. 

5) Unplug the device

6) Plug the phone into a wall wart charger via a standards compliant cable. GrapheneOS will still not charge. GrapheneOS will not detect the charger. GrapheneOS will not switch back to charging the phone. 

7) The user will need to manually switch back from OTG Charging to "Charge this device" with the standards compliant cable plugged into the wall wart PSU. In one situation I cannot reproduce yet (will update as I test more), I was unable to switch back to charge at all. Until the user figures this out, they will only be able to charge when the phone is switched off. At least 2 users have taken their phone into repair before finding out that it was just software because the issue can start again shortly after a factory reset, so it can be a critical issue. 

Just to reiterate those workarounds:

A) Charge while the phone is off. There will be no indication that the phone is charging until you switch it on again.
B) Switch charge mode while using the cable that was used to successfully flash GrapheneOS. **New users need to be able to know which cable actually works, and if the flashing process was successful, that is the only way I know to judge it. 

Observations:

X) We need a way to test the quality of cables and whether they can be used. I don't have the original cable for my phone, for example. 

Suggested improvements:

1) Allow the user to manually switch back charge mode without the cable being plugged in
2) More testing with bad cables 
3) More testing with OTG devices
4) More testing with non-OTG devices

**Comment by thestinger** [comment]
This is outside the scope for GrapheneOS. Changes in these areas need to be done for the Pixel 6 USB controller firmware and the OS upstream.

**Comment by FetchFast** [comment]
> This is outside the scope for GrapheneOS. Changes in these areas need to be done for the Pixel 6 USB controller firmware and the OS upstream.

OK thanks. 
Just to let you know, I tested on a Pixel5. Hopefully others can confirm other models and if it affects Lineage, for example. 
I will search for Android's bug tracker. Hopefully we can get a link here to a bug over there for anyone to find this thread

**Comment by thestinger** [comment]
Pixels try to defend themselves against being ruined by a faulty cable / charger or worse starting a fire. Those are very real possibilities without this functionality. Seems like it's overly aggressively implemented but not much we can do about that.
