### ISSUE TITLE
Separate INTERNET permission for Wifi or Mobile Data

### ISSUE THREAD

**Issue by tzugen** [GrapheneOS/os-issue-tracker#1224]
I would like to grant specific apps the INTERNET permission only for Wifi. 
Is this possible (without using a VPN-Firewall)?

**Comment by thestinger** [comment]
It would be possible to have finer grained controls but 100% of indirect access would have to be blocked while using it. That means not everything would work. We don't currently have plans to implement the specific feature you're requesting. We wouldn't be willing to make an incorrect leaky implementation like other alternate OSes have done.
