### ISSUE TITLE
Pixel 6 Lockscreen

### ISSUE THREAD

**Issue by xander2m** [GrapheneOS/os-issue-tracker#1225]
Bottom 2 numbers of clock go underneath the fingerprint scanner icon (and sensor) on the lockscreen. On stock Google they do not. Can you raise the clock upwards by a couple of mm? Thanks

**Comment by thestinger** [comment]
We'll likely wait for changes in this for AOSP. We're not planning on changing the UI. Changes in the stock Pixel OS will likely be shipped in AOSP.

**Comment by xander2m** [comment]
Thanks for the feedback. It is very unsightly but I understand why you don't want to make the changes as you support multiple devices. Do you think it is likely that Google will push out any changes to the aosp UI?

**Comment by flawedworld** [comment]
It's an AOSP UI bug. Unless we obtain a patch to resolve it from the community, we aren't going to spend dev time on it.

**Comment by xander2m** [comment]
Okay, that sounds reasonable.
