### ISSUE TITLE
Automatic Display turning off somtimes doesn't work

### ISSUE THREAD

**Issue by vamsteuerungen** [GrapheneOS/os-issue-tracker#1226]
Hi,

it happens sometimes (maybe in 10% of the cases) that my display does't turn off automatically on the pixel 6, although I set an automatic turn-off-time of 15 or 30 seconds. I have to push the power button then to turn it off. 
I have not found out yet if its an app causing this or if its graphenos specific.

Has anyone an idea how to fix this or if its a bug?
Thanks alot

**Comment by thestinger** [comment]
Alternatively, you're using an app which is using a screen wake lock.

You should discuss this in the Matrix room until there's a reason to think it's an OS issue.
