### ISSUE TITLE
per-app user facing toggle for disallowing apps access to ptrace()

### ISSUE THREAD

**Issue by flawedworld** [GrapheneOS/os-issue-tracker#1230]
We do this globally right now as an opt-in toggle and it would be nice to be per-app for annoying apps like banking apps and games which do call ptrace() to debug themselves as a crude anti-reverse engineering measure.

**Comment by muhomorr** [comment]
Implemented by https://github.com/GrapheneOS/platform_frameworks_base/pull/406
