### ISSUE TITLE
Work application crashes after starting to sync, no errors

### ISSUE THREAD

**Issue by Faknit** [GrapheneOS/os-issue-tracker#1231]
An application called Capsule Workspace runs fine for a few minutes, but once synchronization begins it crashes with no error. Reopening the app will repeatedly do the same thing, until the application database is deleted. It will then run again for a few minutes, until it synchronizes and then it crashes again. Logs sent!

**Comment by flawedworld** [comment]
Contacting checkpoint to see if we can get them to fix it.

**Comment by flawedworld** [comment]
checkpoint fixed the issue following our report to them.
