### ISSUE TITLE
Launcher search improvements

### ISSUE THREAD

**Issue by pgera** [GrapheneOS/os-issue-tracker#1232]
The search function in the launcher is not intuitive. It has the following issues:

- It shows only one row of results.
- Typing a letter does not show apps starting with that letter. Instead, it includes other unrelated apps which may have the letter in their name while omitting actual apps starting with the letter.

Example:
Type 'A'.
Results:
![Screenshot_20220601-153445](https://user-images.githubusercontent.com/5542855/171513192-4e744329-a2f8-471f-88bd-892e7b8d0f47.png)

Notice the last two apps do not start with an A.

Type 'Au'
![Screenshot_20220601-153648](https://user-images.githubusercontent.com/5542855/171513317-8c052ef1-2069-49d3-8bee-8f5e7b37c3aa.png)

Typing 'Au' reveals these apps that should have showed up in the first attempt while typing 'A'.

**Comment by flawedworld** [comment]
It's unlikely that we will change how this works.

**Comment by prasun-cb** [comment]
A separate issue is that the current version of the pixel launcher (found on apkmirror) does not work either. Like other AOSP apps, it appears that upstream primarily works on the pixel launcher.
