### ISSUE TITLE
Trying to install the sandboxed google play store

### ISSUE THREAD

**Issue by pooofjolly** [GrapheneOS/os-issue-tracker#1234]
When I try to install playstore, GPS and GSF,, (And I get notifications of background update attempts) which say:
INSTALLATION FAILED
Your device has an app installed
with the same package name, but a
different signature

The notification never tells me which app
All my apps were installed thru f-droid or aurora but may have accidentally installed a version of GSF (banking app, Samsung Watch App, LeafSpy and MicroG)
I would retry the sandbox if I could figure which app to delete and let (sandboxed) google re-install it.
Is there a log or something?

**Comment by flawedworld** [comment]
Uninstall MicroG
