### ISSUE TITLE
Allow Network Permission when using app

### ISSUE THREAD

**Issue by Swoooshhh** [GrapheneOS/os-issue-tracker#1236]
Would it be possible to add an option so that instead of fully removing network permission, you could only allow network permission to a certain app when it is open? Just like the location permissions.

**Comment by flawedworld** [comment]
This doesn't make sense to implement.

**Comment by flawedworld** [comment]
An app can just send data when it's in the foreground.

**Comment by Swoooshhh** [comment]
Wouldn't that be better than if it were to always send data in the background?

**Comment by flawedworld** [comment]
It would make no different at all.

**Comment by Zanthed** [comment]
No it would not. What makes you think the app isn't collecting data in the background and just waiting to exfiltrate it as soon as you open the app again?

**Comment by thestinger** [comment]
Apps / libraries inherently need to handle network access being unavailable a lot of the time and prepare anything they want to do for when it's unavailable. It's already required without wanting to do anything sketchy to bypass a feature.
