### ISSUE TITLE
Gmail app fails to download attachments

### ISSUE THREAD

**Issue by basploeger** [GrapheneOS/os-issue-tracker#1237]
Whenever I try to download a mail attachment in Gmail, I get a message "Failed to download the attachment".

It looks like this is not an app problem but an OS-level security issue. E.g. OnePlus users have the same issue:
https://forums.oneplus.com/threads/unable-to-download-attachment-from-gmail-app.1497476/

I have tried several times to clear Gmail data, re-install app, and do the same for Google Play Services but nothing works.

**Comment by flawedworld** [comment]
Unable to reproduce. As is I don't see how it's a GrapheneOS issue.
