### ISSUE TITLE
Keyboard doesn't show numbers

### ISSUE THREAD

**Issue by mercertom** [GrapheneOS/os-issue-tracker#1239]
Gboard and at least some versions of AOSP keyboard have an option to show numbers (full keyboard). Current keyboard requires 2 keystrokes for every number, which is a terrible waste of human life.

**Comment by empratyush** [comment]
I am closing this for now, There is no plan (for now) to invest any time/resources in AOSP keyboard app.

**Comment by mercertom** [comment]
@empratyush the current keyboard isn't the AOSP keyboard app. The AOSP keyboard has numbers when you select the "full keyboard" option. The current GOS keyboard doesn't have that option. Does that make sense?

**Comment by thestinger** [comment]
GrapheneOS keyboard is a very lightly modified variant of AOSP keyboard and doesn't remove any features having to do with numbers.

**Comment by mercertom** [comment]
@thestinger at the time I created this issue, it removed this vital feature, costing ridiculous amounts of keystrokes/holds. I'd happily use the "lightly modified variant" if it didn't force me to effectively make two keystrokes for every number i ever type. Many users use alternative keyboards, like gboard or openboard, very likely because of the "light modifications" like this. I can't find the "full keyboard" option still when I checked just now.

**Comment by thestinger** [comment]
GrapheneOS did not remove this feature or any other feature from AOSP keyboard.

**Comment by thestinger** [comment]
AOSP keyboard displays the number row in certain cases. It doesn't have a toggle for it and never did. You must be thinking of an AOSP keyboard fork that's not AOSP keyboard itself.

**Comment by mercertom** [comment]
@thestinger so you have the "full keyboard" option that puts the numbers visible on your GOS keyboard? Maybe it changed where it is.

**Comment by thestinger** [comment]
That's not an AOSP keyboard feature. You're confusing AOSP keyboard with extended forks of it.
