### ISSUE TITLE
slab canaries uncover issues on most devices

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/os-issue-tracker#124]

**Comment by thestinger** [comment]
This is temporarily disabled. It may be an incompatibility caused by a change, or it could be a bug uncovered by the feature. It will need to be investigated soon.

**Comment by anupritaisno1** [comment]
@thestinger I just cherry-picked this onto my 4.14 kernel and had somewhat similar results. The device never boots

What's more, slub_debug=FZ also does the same thing. slub_debug=F boots but with redzoning it just doesn't 

Can you tell me about what you experienced on the pixels?

**Comment by thestinger** [comment]
It just doesn't boot and I wasn't successful in using my debug cables to figure out what was happening. IIRC, it was causing really strange crashes and I could see it with the debug cable but I couldn't figure out how to resolve it. You should check if there are usable logs in pstore.

The slab canary feature is very similar to the upstream redzones but they're designed for hardening rather than detecting bugs and debugging. It generates a random 8 byte value and masks the leading byte so that it's always zero, so it's zero followed by 7 random bytes, with a different random canary per slab cache (i.e. per kmalloc size class and per type for type-based allocators).

**Comment by thestinger** [comment]
If redzones break this too, that's a really good thing, because that's more designed for debugging and could also be reported upstream.

**Comment by anupritaisno1** [comment]
Sadly my manufacturer replaces pstore with their own proprietary implementation. While there's actually a way to dump the entire memory from that implementation I doubt anyone has so far done so on Linux and I doubt there's an easy way to do so on windows either so right now I'm stuck with zero usable logs

**Comment by thestinger** [comment]
Using slub_debug is a good idea though and someone in the GrapheneOS community with a debug cable could look into this. We have someone who can make the debug cables.

**Comment by anupritaisno1** [comment]
I have just left slub_debug=F in my kernel for now. Debugging this board is a serious nightmare and it took me 3 months to fix a rather simple panic. (Which BTW the issue could never be found without some of your past work, thanks for that!)

As for =P, the previous kernel maintainer decided to backport init_on_free and init_on_alloc

**Comment by renlord** [comment]
this can be closed now?

**Comment by thestinger** [comment]
It's only fixed for the most recent devices unless it happened to be fixed for the older ones without us noticing. It can be closed once we no longer support the older devices or once it's actually fixed for those too. It may already be fixed and we just haven't tried since it happened. I don't know.

**Comment by thestinger** [comment]
We're no longer going to be working on this for 3rd generation devices.

**Comment by r3g-5z** [comment]
We added this back for 6th/7th gen devices, but don't want to do it for rest of 4th/5th gen due to some complex/incompatible changes

https://github.com/GrapheneOS/grapheneos.org/commit/80631fab54d9663951be1aac3cb59dd03180a806
