### ISSUE TITLE
Emergency calls cannot be blocked

### ISSUE THREAD

**Issue by anonaddict** [GrapheneOS/os-issue-tracker#1241]
Despite having no SIM card you can still connect to cellular with emergency call which disables airplane mode as well. There doesn't appear to be any way to completely block cellular while retaining the ability to use wifi

**Comment by thestinger** [comment]
Not having a SIM card isn't supposed to disable cellular. That's a misunderstanding of the function of a SIM card.

Airplane mode disables cellular and doesn't prevent using Wi-Fi. This is documented in our FAQ.
