### ISSUE TITLE
Protonmail

### ISSUE THREAD

**Issue by LutraLutris** [GrapheneOS/os-issue-tracker#1242]
Hi! I cant launch the protonmail app after the latest update (both grapheneos and protonmail 3.0.0) 

It seems to have the same issue as the Tor Browser did. Just crashes on startup.

**Comment by LutraLutris** [comment]
I'll post this on Protonmails support page just incase this is only an protonmail issue and not because of grapheneos

**Comment by Zanthed** [comment]
Both have nothing to do with GrapheneOS. It's an app bug.
