### ISSUE TITLE
"give a battery optimization"?

### ISSUE THREAD

**Issue by BeholdersEye** [GrapheneOS/os-issue-tracker#1243]
https://grapheneos.org/usage#sandboxed-google-play-installation

"You should give a battery optimization exception to Google Play services for features like push notifications to work properly in the background. It isn't needed for the other 2 apps."

How is this done precisely?

**Comment by Zanthed** [comment]
Settings ➔ Apps ➔ Sandboxed Google Play ➔ Play services system settings ➔ Battery ➔ Unrestricted

Or Settings ➔ Apps ➔ See all apps ➔ Google Play services ➔ Battery ➔ Unrestricted

It isn't necessary for Play Store or Google Services Frameworks. Just Play services.

**Comment by Zanthed** [comment]
You should join one of our platforms for further support: https://grapheneos.org/contact#community

The OS issue tracker is meant for tracking feature requests, bugs, etc with GrapheneOS rather than questions.
