### ISSUE TITLE
Opening battery usage causes Settings app to crash

### ISSUE THREAD

**Issue by mariobrostech** [GrapheneOS/os-issue-tracker#1244]
On my Pixel 5a, opening the Battery Usage section of the Settings app causes an instant crash. This was first noticed today, after the application of the latest GrapheneOS security update.

**Comment by flawedworld** [comment]
https://gist.github.com/flawedworld/1bc3f80aa9a85ec11f6a78d6fa9d7119

**Comment by thestinger** [comment]
Let us know if this is still an issue on Android 13.
