### ISSUE TITLE
Skip tracks with volume button.

### ISSUE THREAD

**Issue by greenerk** [GrapheneOS/os-issue-tracker#1246]
A feature enhancement that I miss from Motorola smartphones and LineageOS.

There is a setting that, when enabled, skips audio tracks forward or back with a double-press of the volume up or down buttons, respectively.

There are apps that can mimic this feature, but not when the screen is off.

The command initiated is the "skip" command but this will skip an entire track or just jump forward/back depending on the application playing (skip forward 30s or back 10s for podcast apps for example).

The volume can still be controlled by holding the volume button.

Even if the feature was reversed (i.e. holding the button to skip), this would be OK also.

**Comment by flawedworld** [comment]
It's unlikely we would implement this ourselves, but we may consider including such a feature if it was submitted by the community.

**Comment by djvs** [comment]
This would be a fantastic feature... I would help implement with a little guidance

**Comment by pflanzenandi** [comment]
This is the only feature missing for me on GrapheneOS. 
Would be great if you could have another look into it.

**Comment by awsms** [comment]
> This is the only feature missing for me on GrapheneOS. Would be great if you could have another look into it.

Same here, true bummer

**Comment by djvs** [comment]
Using "volumee" app until this hopefully gets implemented.

**Comment by starbrights** [comment]
Maybe a better alternative are this open Source app:

keymapper (FDroid) or
https://github.com/Cilenco/skipTrackLongPressVolume
