### ISSUE TITLE
SMS - Search Bar

### ISSUE THREAD

**Issue by ToddCrimson** [GrapheneOS/os-issue-tracker#1251]
Please could you add a search bar on top? This is so basic, yet critical. Otherwise I have to keep using QK SMS (but its one year old) and Simple SMS has many bugs.

If you do not wish to make changes to Legacy SMS app, could you please provide alternatives, or release one that is more functional?

**Comment by akc3n** [comment]
> We don't actively develop the SMS/MMS app. It's the AOSP Messaging app. We don't plan to add assorted features, especially frills like this. SMS/MMS are insecure and should be avoided. It's not a bad thing if users are pushed to use proper secure messaging.

Full context #1012 and explained^ [here](https://github.com/GrapheneOS/os-issue-tracker/issues/1012#issuecomment-1057579325) 

Close #1251

**Comment by ToddCrimson** [comment]
Thanks Juri, while I understand that it should be phased out, and I support that.
It is not possible to stop using it completely. People are people, and they will use that feature.
Company's also use that feature.

I don't feel this is an unreasonable request to have a search bar. 
The philosophical debate that users should be pushed to use proper secure messaging won't happen overnight. It is a slow and painful transition.

While that transition is happening, we still need to be able to Search SMS messages. 
I would really like NOT to close this but request you add this as enhancement.

**Comment by Zanthed** [comment]
If people insist on using SMS, then they should find another SMS app.

**Comment by ToddCrimson** [comment]
You don't have to be so insulting. 
This makes me want to move away. 
Why are you even answering on a public forum as you don't care about anyone else's opinion but your own.

Stop saying things like this and stop closing out requests just because you have a "feeling" that people should not use it.

If you think it is insecure, remove and disable SMS app. 
All your people here and anywhere else will stop using GrapheneOS. 

Please don't be a bully here. 
SMS is widely used, and no matter what your personal feeling / opinion is, it will still be widely used.

So while you don't want to add search bar as an option, don't bully and don't be insulting.

You can just be polite, and say "we don't intend to add this functionality".

**Comment by Zanthed** [comment]
You've been answered above by akc3n. You're creating problems for no reason.
