### ISSUE TITLE
SMS - Dark Theme

### ISSUE THREAD

**Issue by ToddCrimson** [GrapheneOS/os-issue-tracker#1252]
Just like LineageOS that uses Legacy AOSP messaging app, please allow the messaging app to use system Theme VS forcing the light theme,

Thank you

**Comment by akc3n** [comment]
Explained here #406#issuecomment-742581419
See #406, #819, #787

Please consider searching the issue tracker prior to posting similar or duplicate questions.

Thank you.

Close #1252
