### ISSUE TITLE
UI crash / freeze

### ISSUE THREAD

**Issue by MxMarl** [GrapheneOS/os-issue-tracker#1253]
I use profiles. On one profile I use entertaiment like emulators, Netflix, games, ...
As soon as I go to the profile (use an game-emulator for example) and spend a little time there, and return to my main profile, the profile freezes. After entering the PIN, the PIN field appears again for a short time. I land on the home screen. After opening an app, and returning to the home screen, freeze again. The last screen of the previously opened app is still.
The only remedy is a restart.

**Comment by akc3n** [comment]
Do you get an error message prompt or a system ui popup asking to wait or close?

**Comment by MxMarl** [comment]
No nothing. Drawer is just lost (frozen) for seconds.

**Comment by MxMarl** [comment]
> Do you get an error message prompt or a system ui popup asking to wait or close?

No nothing. Drawer is just lost (frozen) for seconds.

**Comment by jorgeluiscarrillo** [comment]
Sounds similar to what is being reported in #866

**Comment by thestinger** [comment]
Let us know if you still experience this on Android 13.
