### ISSUE TITLE
Default Messaging & Telephone apps not working

### ISSUE THREAD

**Issue by nielznl** [GrapheneOS/os-issue-tracker#1254]
On my Pixel 6 I failed to make phone calls and send text messages with the default applications. The messages show up as not sent and the following error message is given: `Can't send message with carrierName, error 255` where carrierName is the carrier.
I also tried a different sim card from another carrier which may have given error 65 instead of 255 if I remember correctly.
Using Signal or Google Messages to send SMS messages and Phone by Google works fine though. Should I try switching to a more popular carrier or can this be fixed somehow?

**Comment by flawedworld** [comment]
The default apps work fine. We can't provide support without knowing more details. See https://grapheneos.org/usage#carrier-functionality
