### ISSUE TITLE
[Question] Do I need to install google play services in my main profile and work profile

### ISSUE THREAD

**Issue by JoonasC** [GrapheneOS/os-issue-tracker#1255]
I have installed google play services on my main profile, and I also have a work profile. Do I need to have google play services installed in both or is having it in just the main profile enough?

**Comment by thestinger** [comment]
Please ask questions in our main #grapheneos:grapheneos.org Matrix chat room (https://grapheneos.org/contact#community) or the discussion forum (https://discuss.grapheneos.org/).
