### ISSUE TITLE
Apps crashing after sufficient system uptime

### ISSUE THREAD

**Issue by artificialparanoia** [GrapheneOS/os-issue-tracker#1256]
**Device:** Pixel 6

**Build number:** SQ3A.220605.009.B1.2022060701

**Info:** Severe possible OS bug causing most if not all apps/processes to crash, increasing in severity until the device rapidly becomes unusable and forces the user to restart. This bug did not occur prior to the most recent OS version, and seems to not be specific to any individual app. Cannot generate substantial bug report using on-device tools as this is occurring due to the bug seemingly affecting all apps, including system components. 

The only fix is to periodically restart the phone whenever this occurs, though this is not a permanent solution and the problem occurs if the system uptime is around a day or more.

**Steps to reproduce:** 

Do not turn off or restart your device for over 24 hours (time may vary, as testing proves that this isn't completely consistent) on a standard/daily use device. Apps and other processes will crash constantly and repeatedly until a device reboot. May not be applicable to all devices but has consistent repro on my P6.

**Comment by artificialparanoia** [comment]
Can confirm that it's less than or around 24 hours between restarts that this is happening. Whether or not the device is "awake" or not doesn't seem to affect when the bug starts. It seems to get exponentially more severe (apps and other processes start crashing while using them, then crash quicker and more often to where you can't use them at all, etc. etc.), and while restarts temporarily fix it the issue occurs consistently pretty much every day. Sent a bug report generated via ADB through email.

**Comment by thestinger** [comment]
This appears to be a hardware issue and we're not going to be able to help.
