### ISSUE TITLE
Options for software updates and other features

### ISSUE THREAD

**Issue by maanz79** [GrapheneOS/os-issue-tracker#1257]
Hi. I would like to see a feature of having to choose update bugfixes/software with wifi. Reason is whenever there is new updates available, it would automatically download and update with my data (wifi is off, not present), hence this will drain the phone battery more (than using wifi) as well as wasting my LTE data unnecessary. Hope to see this be implemented.

It would be nice if System Profile feature and Network Data monitor on Statusbar can be implement.

**Comment by flawedworld** [comment]
If you want to prevent them being downloaded automatically on LTE, don't allow updates on metered networks within the system update settings.
