### ISSUE TITLE
Quality of life issue: Location notification when screen is turned on distracts from battery percentage

### ISSUE THREAD

**Issue by mpelley92** [GrapheneOS/os-issue-tracker#1258]
This is a low priority concern, but nonetheless, one that I wish to air. My wife and myself enjoy using GrapheneOS on our Pixel 4a 5G's. Kudos to all the project contributors, as well as the lead Daniel for all of your hard work.

Some background: I have an app called "Net Info Widget". It's useful to us to be able to quickly turn off WiFi and mobile data, for battery life and privacy. This app allows us to simply tap once and it's done. Mobile data is always an extra step, but more convenient than the way Android is set up to do it at the current moment.

The issue: Currently with the way the app and Android both work, the widget will ask for location in order to toggle the WiFi state. Helpfully, the OS reports this action every time the screen is turned on. What this does in effect though, is it takes about 4-5 seconds for the green indicator to disappear before you can see the current battery level. This is simply just a minor annoyance.

The proposed solution: Enact the ability for the privacy request indication function to ignore specific apps from displaying an indicator. In my mind I think that this could potentially be exposed to abuse or allow for a false sense of security by the user of the device, but if there are apps that are trustworthy, they should still be allowed to be put on an exemption list for that function.

I hope this is helpful, and thank you again for all your hard work.

**Comment by flawedworld** [comment]
We won't be doing this as it would weaken the feature.
