### ISSUE TITLE
GrapheneOS calling while abroad broken

### ISSUE THREAD

**Issue by Joseph-33** [GrapheneOS/os-issue-tracker#1260]
**Expected Behaviour:**

I dial someones phone number and it calls them normally

**Actual Behaviour:**

I call someone using the official Phone app from GrapheneOS and the screen is stuck on "Calling...", the phone hangs up after a while by itself with no error messages.
In one of the previous update, my phone would also suddenly lose mobile data coverage shortly after calling for around 5 seconds.

Texting and using mobile data both work well.

I have contacted my mobile operator multiple times and they seem to have assured me it isn't an issue on their side

I have also taken my SIM out and tested it with my Samsung galaxy S8 and calling seems to work perfectly.

**Specifications:**

- Model: Pixel 6
- Android Version: 12
- Release channel: Stable
- Android security update: 5 June 2022
- Build number: SQ3A.220605.009.B1.2022061600

**Comment by flawedworld** [comment]
Please follow: https://grapheneos.org/usage#carrier-functionality

Roaming functionality works fine on GrapheneOS. My guess is that you LTE only mode on and the country you are in doesn't support VoLTE for roaming customers on your carrier.

**Comment by Joseph-33** [comment]
Thank you, this solved my problem
