### ISSUE TITLE
Reproducible build verification 

### ISSUE THREAD

**Issue by aunger** [GrapheneOS/os-issue-tracker#1263]
Validation of builds by a third party (and an automated [validation process](https://grapheneos.com/build)) would add assurance of the build system and build personnel.

This is especially important given GOS's combination of rapid updates and security focus.

Consider partnering with https://reproducible-builds.org/

**Comment by thestinger** [comment]
Resources need to be provided to us if we're going to do more in this area: build machines, developers to work on the OS and on automated infrastructure, etc. We have no additional resources to dedicate to this and our existing support for it not really being used in a beneficial way.

**Comment by aunger** [comment]
@thestinger Thanks. Would it make sense to reopen this issue to track the need, in hope it's picked up by someone new? Developers can be found, and orgs like the one I linked above appear to be well resourced.

@Zanthed The build is reproducible only by some definitions. The GOS build page you linked admits this is a "gradual" effort. The build instructions do not list version numbers for most of the required tools. An English-language description of the build process isn't precise enough to create a bit-perfect image. Automaton is needed.

GOS is asking for a lot of trust from its users.  Supporting those who wish to audit builds would help. I've been using GOS in a low-trust scenario for 6 months and I love it. I trust your approach, and think it's the **only** usable mobile OS doing security and privacy the right way. I badly want to switch to GOS fully, but can't do that without further build assurance. I doubt I'm the only one.

**Comment by thestinger** [comment]
> The build instructions do not list version numbers for most of the required tools

The relevant build tools are shipped as part of the source tree and the build is done in a partial sandbox. That's a standard AOSP build system feature.

> The GOS build page you linked admits this is a "gradual" effort

It does no such thing.

> An English-language description of the build process isn't precise enough to create a bit-perfect image

It's not an English-language description of a process. The build system is automated. It takes 1 command to set up the build environment in a shell, 1 command to choose the target and 1 command to build. You clearly haven't tried or read our instructions.

> GOS is asking for a lot of trust from its users. Supporting those who wish to audit builds would help. I've been using GOS in a low-trust scenario for 6 months and I love it. I trust your approach, and think it's the only usable mobile OS doing security and privacy the right way. I badly want to switch to GOS fully, but can't do that without further build assurance. I doubt I'm the only one.

Not clear what you want and I don't see any actual real value from it only theatre. If you want to work on theatre, feel free. We have much higher priorities and aren't wasting our time on entirely useless things which don't actually help or improve things in reality.
