### ISSUE TITLE
Silent + Minimized notification is hiding his Lockscreen setting

### ISSUE THREAD

**Issue by paradiseturtle** [GrapheneOS/os-issue-tracker#1265]
When you use the Minimize toggle on a Silent notification the Lockscreen sub setting is removed from the UI. The issue is that when you go to the emergency dialer while the screen is locked the notification is displayed in the dropdown panel according his default/lastest Lockscreen setting. 
Either the Lockscreen sub setting shouldn't be removed when toggling on Minimize or should be set to "dont display notifications at all' while hided, otherwise it's confusing and can cause privacy issues if you aren't aware that the Lockscreen setting is still used despite of it being removed from the notification setting ui.

**Comment by thestinger** [comment]
You're going to need to clarify what you mean.

**Comment by thestinger** [comment]
I don't think this is unexpected / unwanted.

**Comment by thestinger** [comment]
That's not what it does. There's no problem here. Silent means it's not shown in the status bar or on the screen not that it's inaccessible in the lock screen notification tray. This is basic Android functionality. That's not a privacy or security feature, it's the notification priority.

**Comment by thestinger** [comment]
This is not going to be changed.

**Comment by thestinger** [comment]
No, it always works as expected.

**Comment by thestinger** [comment]
It's not a bug. It's working as intended. Silent is not supposed to hide notifications in the tray on the lockscreen. It's not a privacy setting. It's a notification priority setting as in how intrusive it is. There's nothing to fix.
