### ISSUE TITLE
Wi-Fi broken on Pixel 4 and 5 Android version 12

### ISSUE THREAD

**Issue by Rocket01666** [GrapheneOS/os-issue-tracker#1269]
Hi there, 

I am having very similar issues as issue #1071
I have confirmed wifi with WPA2 passkey works as intended on Android 12 on both the Pixel 4 and 5, after following the instructions to flash GrapheneOS wifi will accept the WPA2 passkey and initiate connection but seems to get stuck at "Connecting..." change Mac Randomization settings doesn't make a difference. 
Currently connected to my SSID without issues on Pixel 5 and pixel 4 running Vanilla Android from google.
Any assistance resolving this issue are appreciated as using data for updates is not ideal.

**Comment by Rocket01666** [comment]
Not sure if this helps at all but I used the Web install method, I will try the cli method and report back.

**Comment by thestinger** [comment]
Install method isn't relevant.

**Comment by OpenSourceGhost** [comment]
I have a similar issue with WPA3, but when it gets stuck on "Connecting...", I force-disconnect, and phone connects to WiFi immediately after that. Also, make sure WiFi is configured correctly. Sometimes my phone doesn't like SSID name or the complicated 62-character password. 

Also, WPA3 accepts more than 62 characters for password, but Android OS still limits it to 62.

**Comment by flawedworld** [comment]
As-is I don't really see why this would be a GrapheneOS issue. I can only suggest moving to per-network random mac addresses. 


@OpenSourceGhost That sounds at the very least like an implementation issue in WPA3 on your AP/in AOSP and the password limit sounds like an AOSP bug. It's not related to this.
