### ISSUE TITLE
Battery Share in Quick Settings

### ISSUE THREAD

**Issue by factorial52** [GrapheneOS/os-issue-tracker#1270]
While editing quick settings tiles, battery share is displayed as "Battery Saver" along side the real battery saver tile, although with unique icons. When finished editing it is displayed correctly. Also if the edit tiles page is brought back up with battery share added, battery saver has vanished altogether. Possibly because of the naming conflict, but I'm not sure.

**Comment by thestinger** [comment]
cc @empratyush

**Comment by flawedworld** [comment]
fixed
