### ISSUE TITLE
Certain apps can't be installed in a user profile if they are already installed in the owner profile

### ISSUE THREAD

**Issue by athyla** [GrapheneOS/os-issue-tracker#1271]
I have the Owner profile with F-Droid and Aurora Store and a user profile with Google Play installed.
On the Owner profile, I have installed F-Droid from the web. I also installed NextCloud and KeePassDX from F-Droid.
On the user profile I was able to install KeePassDX from Google Play, but cannot install F-Droid from the web, nor NextCloud from Google Play. It just gives a generic error that the application cannot be installed.

I tried clearing the cache and data of Google Play, but it does not help.

**Comment by flawedworld** [comment]
https://discuss.grapheneos.org/d/63-f-droid-second-profile-issue
