### ISSUE TITLE
Contact birthdays

### ISSUE THREAD

**Issue by ksanf3** [GrapheneOS/os-issue-tracker#1272]
In the contacts app there should be a "birthday" field.
In addition, contact's birthdays should be allowed to show up in the user's preferred calendar

**Comment by viktoriasee** [comment]
The first point is already implemented. The birthday is not shown by default only as you tap "more fields".

The second point can be achieved using a calendar app such as [aCalendar+](https://play.google.com/store/apps/details?id=org.withouthat.acalendarplus)

**Comment by empratyush** [comment]
we include AOSP calendar and contacts apps which doesn't have these features but we don't actively add features to these apps, you can use any third party apps.
