### ISSUE TITLE
FIDO2 NFC keys fail

### ISSUE THREAD

**Issue by viktoriasee** [GrapheneOS/os-issue-tracker#1273]
Using latest GrapheneOS and Firefox I try to [log in to Github](https://github.com/login) using a Yubikey NFC in hardware key mode.

This works with USB but not with NFC. 
<p float="left">
<img src="https://user-images.githubusercontent.com/11464744/175767570-bf4731f0-609f-4281-85b2-dd452f4712ea.png"  width=200>
<img src="https://user-images.githubusercontent.com/11464744/175767572-21c35a62-44d2-4d69-b523-0372677c9b11.png"  width=200>
<img src="https://user-images.githubusercontent.com/11464744/175767573-7e64b614-500d-4329-adba-b220fff5bc79.png"  width=200></p>
<p float="left">
<img src="https://user-images.githubusercontent.com/11464744/175767574-76a5c265-bb38-4e73-a73e-aa8de2aa791d.png" width=200>
<img src="https://user-images.githubusercontent.com/11464744/175767575-36403a40-30d0-4099-9dc6-2350c34ab722.png"  width=200>
<img src="https://user-images.githubusercontent.com/11464744/175767577-21ae9042-484a-470a-a9b3-cb71b1381722.png" width=200>
</p>

I succeed to log in by NFC (and USB as well) on a Wordpress site having [wp-webauthn](https://de.wordpress.org/plugins/wp-webauthn/) enabled. That means it works in principle but not on important sites such as Github.

Sidenote: At the same time of the successful login (NFC) you get a popup message asking to "complete action with" and a prompt for different apps. The choice is "just this time" and "always". But there is no option "never" after an NFC FIDO2 tap.
<img src="https://user-images.githubusercontent.com/11464744/175768979-e28269e6-7634-4154-a92d-6760f28988a4.png" width=200>

**Comment by flawedworld** [comment]
Not a bug. You need to hold it down for longer and hold it really still.

**Comment by viktoriasee** [comment]
Can you confirm it works for you? Or is it speculation?

I get the "Security key authentication failed" error message after a very short time (100-200 ms) so there is very little room for movement. When the key touches the phone the error message basically already pops up. Leaving it there does not make the error message to disappear (which would surprise me anyway).

**Comment by flawedworld** [comment]
It works fine. It can be a little fiddly, tested with my Titan security keys.

**Comment by flawedworld** [comment]
Take off your case or flip the key over or try another.

**Comment by viktoriasee** [comment]
Thank you for the clarification. It does not work for me for some reason. Tested without cover and with another NFC key (Badgeo) also makes no difference.

**Comment by Zanthed** [comment]
We're using a temporary workaround to make Vanadium whitelisted. It is whitelisted when using GrapheneOS.

**Comment by thestinger** [comment]
@viktoriasee Play services may need the media permission for this to work if you haven't done that already.

**Comment by viktoriasee** [comment]
Good to hear that Vanadium is whitelisted. But I get the exact same behaviour on Vanadium.

If Play Services are not granted media permissions it throws a message asking to enable them so that was not the issue.

Reinstalled play services does not solve the problem.

**Comment by thestinger** [comment]
What about the Nearby devices permission?

**Comment by viktoriasee** [comment]
It's not about nearby devices. 

Why does it work on wordpress with wp-webauthn and not on github? If it would be a classical permissions issue or me holding the key too shaky it would not work with wordpress either, isn't it?

The only difference I see is that the wordpress plugin is passwordless while for github the key is a second factor.

BTW I do not manage to use the NFC Yubikey on Vanadium (in NFC mode) with wordpress/wp-webauthn while the same combo works fine with Firefox.
