### ISSUE TITLE
Face Unlocking is possible while data is at rest after unlocking sim via puk

### ISSUE THREAD

**Issue by ruru4143** [GrapheneOS/os-issue-tracker#1274]
testet on Pixel 4.
steps to reproduce:
* restart your phone
* fail to enter your sim via pin 3 times
* enter puk
* enter new pin twice
* now you're able to unlock the device to the "phone is starting..." screen via face unlock

**Comment by thestinger** [comment]
Upstream issue and I don't plan to track those here unless they don't impact the stock OS.
