### ISSUE TITLE
Integrate OpenEUICC app into GrapheneOS to replace Google-proprietary eSIM provisioning tooling

### ISSUE THREAD

**Issue by ThePowerOfDreams** [GrapheneOS/os-issue-tracker#1276]
The [existing implementation](https://github.com/GrapheneOS/os-issue-tracker/issues/159) leaves much to be desired from a privacy standpoint, as it requires the use of Google-proprietary tooling.

[This](https://gitea.angry.im/PeterCxy/OpenEUICC) is a solution which seems to be able to fully replace that proprietary code.

GrapheneOS should evaluate it for inclusion, to replace the dependency on Google code.

**Comment by flawedworld** [comment]
OpenEUICC as-is doesn't meet our standards, though it could be brought up to them, and Pixels would also need an open source firmware loading app. See: https://github.com/GrapheneOS/os-issue-tracker/issues/1079 https://github.com/GrapheneOS/os-issue-tracker/issues/1072

**Comment by flawedworld** [comment]
Pixels use a secondary secure element which is dedicated to eSIM, which is what the firmware loading app would be for.
