### ISSUE TITLE
Bluetooth automatically turned off while Pebble 2 is connected

### ISSUE THREAD

**Issue by anmith** [GrapheneOS/os-issue-tracker#1278]
Hi,

I have an issue with Bluetooth and my Pebble 2:

When I activate the "Bluetooth timeout", Bluetooth gets turned off while my Pebble 2 is connected after the "Timeout" set in the options. The Pebble is visible in the Bluetoot settings as connected device, I'm using Gadgetbridge to communicate with the watch.

![bttimeout](https://user-images.githubusercontent.com/3750050/176251044-f8484ae9-a47d-4d56-9b84-1e07ac47d905.png)

When other devices are connected (Car, speaker, ...), the timeout works as expected.

Device is a Pixel 4a with the latest Graphene OS release and also the latest Gadgetbridge version (FDroid).

**Comment by keatonhasse** [comment]
I had a similar issue with my PineTime. I haven't used it for a bit so I can't speak on specifics, but I remember it disconnecting almost right after I locked my phone with a 2 minute timeout.

**Comment by muhomorr** [comment]
Check again with the current OS version (2022080300), it contains improvements that are likely to resolve this issue.

**Comment by anmith** [comment]
I checked with version SQ3A.220705.004.2022080500, problem still exists as Pebble gets disconnected after the timeout period.

**Comment by muhomorr** [comment]
Do you have access to the logcat?

**Comment by anmith** [comment]
Afaik, logcat is a adb command to get the logs from a device. Which logs do you need and what should I try while logging?

**Comment by muhomorr** [comment]
Reproduce this issue and then obtain the logs with `adb logcat -d > log.txt`

**Comment by anmith** [comment]
Hi,
I created the log: I turned on bluetooth, started Gadgetbridge, connected the pebble, waited for the disconnect and then run the command above.
Where should I send the log?

**Comment by muhomorr** [comment]
Matrix: @muhomorr:matrix.org

**Comment by anmith** [comment]
Hi, afaik Matrix is some sort of communication protocol. Is there a way to send files without a specific client using a web interface or something else? Or is there some old fashioned e-mail I can send it to? Unzipped size is ~500k

**Comment by anmith** [comment]
Hi,
the log has hopefully arrived.  Thanks for all the work and if you need something else, please let me know.

**Comment by anmith** [comment]
I can confirm this still happens with build TP1A.220624.014.2022083000 and also with an Amazfit device.

**Comment by thestinger** [comment]
Fixed by latest release.

https://grapheneos.org/releases#2022090600
