### ISSUE TITLE
MP4 videos do not play

### ISSUE THREAD

**Issue by zupatisc** [GrapheneOS/os-issue-tracker#1279]
Hello, after the recent update I noticed that mp4 videos no longer play either in Vanadium or when trying to watch them through the file manager. Webm's do work however. I used www.learningcontainer.com/mp4-sample-video-files-download/ as an example so someone else can try to confirm this.
Phone: Pixel 4a
Build Number: SQ3A.220605.009.A1.2022062200

**Comment by Zanthed** [comment]
Unable to reproduce, need more details. Have you tried rebooting?

**Comment by zupatisc** [comment]
Shame on me, I thought about testing it in-browser and out of it but I didn't think about restarting. It's now fixed.
