### ISSUE TITLE
Secondary profile notifications navigation 

### ISSUE THREAD

**Issue by Chromatros** [GrapheneOS/os-issue-tracker#1281]
Doesn't work at all. No matter what app. Newpipe, Spotify.....

**Comment by Zanthed** [comment]
Your previous issue was closed because it's extremely unclear and does not tell us anything. You were also asked a question and you need to respond to it.

Please don't open multiple issues. Communicate in the previous issue: https://github.com/GrapheneOS/os-issue-tracker/issues/1280

**Comment by thestinger** [comment]
@Chromatros If you're talking about certain media apps not having visible media buttons on their media notifications in secondary users, that's an issue not specific to GrapheneOS and doesn't impact every application. For example, it doesn't impact Vanadium, which is an indication that those apps could be handling things differently to avoid the problem. It's an issue on the stock OS and on AOSP too so we aren't going to track it in our issue tracker.

The 2 issues you filed are very unclear and I'm just guessing that this is what you were referring to.
