### ISSUE TITLE
Google Pixel 3XL rear (Main) Camera stopped working since i installed Google Play Services 

### ISSUE THREAD

**Issue by MichMourra** [GrapheneOS/os-issue-tracker#1282]
I have a google pixel 3XL. with grapheneos installed on it. Last month I installed the Google Play Services package on my device because I wanted to download some bank application available only on Google Play Store. A day after the main (rear) camera started to fail, an later on couldn't be detected anymore on the device. Now, it is not working at all.  
Can you help me to restore it´s functionality ?
Thank you !

**Comment by flawedworld** [comment]
It's nothing to do with sandboxed Google Play. You should check to make sure you didn't disable the camera globally (Settings -> Privacy -> Camera Access). Otherwise just sounds like a hardware issue.
