### ISSUE TITLE
Cell connection randomly failing on Pixel 4 XL

### ISSUE THREAD

**Issue by TheMCNerd2017** [GrapheneOS/os-issue-tracker#1283]
I've been having issues that may be similar to #1071 for a few months now. Basically my cellular network connection and ability to receive calls would randomly fail for random periods of time. The status bar is inconsistent when this happens doing one of the following: displaying full bars with LTE, displaying full bars with LTE and an exclamation point, or displaying no bars with no network type and an exclamation point.

Going into settings when this happens sometimes claims that connections are available, but otherwise states that there is no connection. Going into the APN settings works as intended and shows a list of APNs. Bringing up a list of available networks by toggling the "automatically select network" option also works as intended, showing other available cellular networks. Additionally, connecting to WiFi networks seems to work fine when this issue happens.

Attempting to fix the issue by clicking the "fix connectivity" button rarely fixes the issue, usually causing the status bar to display no bars with no network type and an exclamation point. I've tried various methods to fix the issue like toggling airplane mode, using the "fix connectivity" button, restarting the device and powering off the device for a while. If I simply leave my device in the broken cellular connection state, it sometimes fixes itself without any input after a random amount of time (a few minutes to several hours).

I generated multiple bug reports when the issue would come up. I'm not sure if they're any good but if you'd like me to submit them I will.

If it's important, my cell carrier is T-Mobile.

Device: Pixel 4 XL
OS Build: SQ3A.220605.009.A1.2022062200

**Comment by Zanthed** [comment]
I don't really see how this could be a GrapheneOS-specific issue. We haven't touched carrier stuff in months and it certainly can't be because of the June QPR3 update since you said it's been happening for a few months. In fact most people reported *better* carrier and cellular connectivity with QPR3 than before.

Best we can tell you is to follow https://grapheneos.org/usage#carrier-functionality but it's very likely a hardware failure.

**Comment by TheMCNerd2017** [comment]
> I don't really see how this could be a GrapheneOS-specific issue. We haven't touched carrier stuff in months and it certainly can't be because of the June QPR3 update since you said it's been happening for a few months. In fact most people reported _better_ carrier and cellular connectivity with QPR3 than before.
> 
> Best we can tell you is to follow https://grapheneos.org/usage#carrier-functionality but it's very likely a hardware failure.

OK thanks for telling me. I'm guessing it could be hardware failure since no one else in my area is having issues and the issues when I first encountered them were nothing like what I'm encountering now (when it first started it was usually a dropout that lasted less than a minute). I'll also try to get a new SIM card as that page states and see if the issue persists. Also should I delete the bug report files I generated since there seems to be no use to them now?

**Comment by TheMCNerd2017** [comment]
Sorry for leaving another comment, but after more testing, it turns out this issue is being caused by the carrier network in my area and not my phone, as all of the issues I was encountering disappeared when I traveled to another location for a good period of time.
