### ISSUE TITLE
Update to 2022063000 disabled Developer Mode on Pixel 4a

### ISSUE THREAD

**Issue by ph00lt0** [GrapheneOS/os-issue-tracker#1285]
I noticed that after the update I had today to version 2022063000 the developer mode on my Pixel 4a had been disabled.

**Comment by thestinger** [comment]
This is a known issue which occurs sometimes on AOSP and the stock OS too. It's only more frequent on GrapheneOS because the OS updates are more frequent. It will likely be resolved by Android 13 around August/September.
