### ISSUE TITLE
Can't turn off/on wireless via non-owner users - is there way for owner to authorize this (if not, then submitting request)

### ISSUE THREAD

**Issue by vtimon1** [GrapheneOS/os-issue-tracker#1286]
Currently have 3 users defined:  Owner / User2 / User3
User2 is my general user (stay in this 90% of time)
User3 is for Google sandbox features  
Owner is not normally used unless I have to make global changes, etc.

This setup is working great for me.  For the few exceptions when I have to access an app via Google sandbox (User3), almost everything else is done via the general (User2) user.

When in User2/User3, I'm often using 'local' features and don't need wireless and can use Wi-Fi or via usb wired connection.  HOWEVER, often I may need to turn wireless off/on to access web and then turn off when finished.
Currently, this requires switching back/forth between Owner and the other users (including password authorizations, etc.) in order to turn on/off the wireless internet (data).

Since Wi-Fi can be turned off/on WITHIN a user account, is there any reason why you can't allow user accounts to also turn of/on wireless Internet data access.  (Or at least allow the Owner account to authorize a user to have that privilege, thereby maintaining control as desired)

Thank you in advance for your consideration.

**Comment by flawedworld** [comment]
Owner is the only user which can control actions related to carrier functionality. It's how AOSP has implemented multiple users.
