### ISSUE TITLE
Notification forwarding allows profile switching during phone calls

### ISSUE THREAD

**Issue by daniel4ka** [GrapheneOS/os-issue-tracker#1288]
I've noticed consistent unexpected behavior with the new notification forwarding feature (GrapheneOS 2022063000 on Pixel 6).

Both before and after the introduction of notification forwarding, the following normal behavior occurs: During a phone call, I can't switch user profiles. The quick settings user selection menu and the "Multiple users" Settings section disable the ability to switch between user profiles.

Now, with notification forwarding, if I'm in the middle of a phone call in Owner and I tap the "Switch to Auxiliary" button of a forwarded notification, I switch to Auxiliary and the phone call doesn't end. I can't see any indication of the phone call except for the microphone indicator saying "Being used by Phone call", but each participant of the call can still speak to and hear the other participant normally. And I can't switch back to Owner except using the "Switch to Owner" button of another forwarded notification.

**Comment by thestinger** [comment]
Fixed for next release.
