### ISSUE TITLE
Boot and login GrapheneOS without starting wireless connections

### ISSUE THREAD

**Issue by GH2204** [GrapheneOS/os-issue-tracker#1289]
Sometimes it is desirable/advisable/required to start the device and log in without establishing any data connection. For example, you want to read a phone number, appointments or message in the memory, but not leave any digital traces in the digital environment. Or more simply: at the new location, you do not want to use the (still) active WLAN without a manual VPN.

However, if you forgot to deactivate the connections when you shut down your smartphone or if you were not yet able to take the new situation into account, the connections will be established faster than it is possible to deactivate the interfaces after logging in. At least I do not recognise any possibility. I can't seem to log in without entering the SIM PIN. In the meantime, WLAN or LTE is setting up.

A solution would be desirable.
- login with device-PIN after boot, or
- enable flight-mode bevor login, or
- ...

**Comment by natert** [comment]
turn off "Auto-connect"
"Turn off Wi-Fi automatically"
"Bluetooth timeout"

**Comment by thestinger** [comment]
This lacks a concrete proposal and is therefore invalid. Logging in is not what enables networking.
