### ISSUE TITLE
forwarded notification appears for signal messenger when no message has been received

### ISSUE THREAD

**Issue by natert** [GrapheneOS/os-issue-tracker#1290]
2 secondary profiles both with sandboxed google play: signal messenger installed in profile A using signal messenger's push implementation. login to profile B and forwarded notification present for Signal, timestamp "now". Close notification, switch back to profile A and then to profile B, notification reappears.
Switch to profile C or D without sandboxed google play and no notification is present.

**Comment by natert** [comment]
reinstalled signal using fcm for notifications and forwarded notifications work as expected.

**Comment by thestinger** [comment]
That's because of the foreground service notification.
