### ISSUE TITLE
"Fake" loginscreen?

### ISSUE THREAD

**Issue by LutraLutris** [GrapheneOS/os-issue-tracker#1291]
Hello! I've been getting these weird looking login (pin) screens from time to time ![Screenshot_20220706-042156.png](https://user-images.githubusercontent.com/72753530/177455024-4a021ce5-3255-4372-b257-5095e60cb090.png)

The strangest part as well is that i can take a screenshot of it which i normally wouldnt be able to do in the normal "circular" pin login.

Latest grapheneos update and Pixel 5.

(Trying to take a screenshot of my normal pinscreen ![Screenshot_20220706-042332.png](https://user-images.githubusercontent.com/72753530/177455284-abb46246-3a4c-4d57-bf7a-96db648280be.png)
)

**Comment by thestinger** [comment]
Please get support in our Matrix room or discussion forum. The issue tracker is for bug reports.
