### ISSUE TITLE
"Install unknown apps" turned off for all apps on every boot

### ISSUE THREAD

**Issue by lbschenkel** [GrapheneOS/os-issue-tracker#1292]
Running `SQ3A.220605.009.B1.2022063000` on Pixel 6.

Every time the phone reboots, "Install unknown apps" permission is revoked for all apps. This includes system apps such as Apps.

**Comment by thestinger** [comment]
It's a known AOSP issue also impacting the stock OS, caused by one of the apps you have installed.

**Comment by lbschenkel** [comment]
> It's a known AOSP issue also impacting the stock OS, caused by one of the apps you have installed.

Interesting. Do you happen to have a link or reference to this? I was not able to find any bug report against AOSP.

**Comment by thestinger** [comment]
It's a more general issue than specifically for unknown sources. It mostly impacts all special access permissions including battery exceptions.
