### ISSUE TITLE
allow more fine grained access control for contacts

### ISSUE THREAD

**Issue by maxbachmann** [GrapheneOS/os-issue-tracker#1294]
It appears that similar to stock android it is only possible to give an application access to the all contacts or none. E.g. Whats App requires access to the contacts to show the name of the person you're writing with and even start a conversation. However giving the app access to all contacts violates privacy laws in my country, since they might not use the service and did not agree with me sharing their data. It would be helpful have more fine grained control which contacts are shared with apps. Interesting controls would be:
- which contacts should be accessible
- which parts of their information should be accessible (e.g. only name + phone number)

**Comment by thestinger** [comment]
Apps can request case-by-case access to contacts with the contact picker but they mostly choose not to bother similar to how they request access to all your profile's media. For now you can work around these issues using profiles. In the future we plan to provide forced case-by-case access.

**Comment by W1zardK1ng** [comment]
looking forward for the Contact Scopes implementation, seeing many of my apps are requesting for contacts permissions and waiting for the new Graphene os way of giving contact permissions.

**Comment by W1zardK1ng** [comment]
For those who are waiting for Contact Scopes implementation, i found a work around for the time being.
Use Simple Contacts app and store the contacts under Phones storage (not available by other apps) option.
The contacts stored under Phones storage (not available by other apps) are accessible by other simple apps (also use Simple Dialer and Simple SMS Messenger default apps) so we see the contact name when we get a call or sms.

**Comment by thestinger** [comment]
Replacing with https://github.com/GrapheneOS/os-issue-tracker/issues/2130.
