### ISSUE TITLE
Shortcut for bluetooth devices in pinned media player disables fingerprint

### ISSUE THREAD

**Issue by h2dden** [GrapheneOS/os-issue-tracker#1295]
![IMG_20220708_155448](https://user-images.githubusercontent.com/58838470/177926730-4d72c7ad-d241-4666-b30a-9af261aa00c0.jpg)
On my Pixel 3, the media player (antennaPod and vlc) is pinned to quick settings, as shown in the picture.
When I try and click Phone Speaker to select an audio device (bluetooth), the locked screen pops up and the fingerprint sensor is disabled.
The cure is to end the secondary profile and then bring it back up: sensor works just fine afterwards
The alternative to select a bluetooth audio device is to long press the bluetooth button, but the way is described above is much quicker... I would appreciate a fix
PS: this is not app specific, caused by antennapod... same thing happens with vlc

**Comment by r3g-5z** [comment]
Can't reproduce this anymore on stock OS and GrapheneOS, likely fixed upstream.
