### ISSUE TITLE
starting a 2nd secondary profile with play services closes another secondary profile

### ISSUE THREAD

**Issue by h2dden** [GrapheneOS/os-issue-tracker#1296]
On my Pixel 6, I have the owner profile and usually logged in 2 secondary profiles: one without play services, the other with play services.
When I log into a 3rd secondary profile with play services, while the other 2 are active, one of the 2 previously mentioned is being closed

**Comment by thestinger** [comment]
You probably have a work profile and the limit is currently 3 active profiles. The OS will also close apps / profiles in the background based on memory pressure. It's just how it works in AOSP and isn't a bug. We can tune configurations over time.

**Comment by h2dden** [comment]
I do not even know where to check if I have a work profile...
Can you guide me? I have created secondary profiles the usual way...

**Comment by thestinger** [comment]
Ask in the Matrix room or our discussion forum (https://discuss.grapheneos.org) about this.
