### ISSUE TITLE
Option to route data to wifi network without internet connection

### ISSUE THREAD

**Issue by ASerbinski** [GrapheneOS/os-issue-tracker#1297]
If you are connected to a cellular network with internet connection and simultaneously a wifi network withOUT internet connection, the system will conclude that the wifi network is invalid and prevent routing of data to that network.

This is a very frustrating situation since there are many cases where it is necessary to use a network that simply is not connected to the internet. Either that local network's WAN connection is down, or maybe it doesn't even have one.

Currently in order to access resources on that network, it is necessary to disconnect from the cellular network. There are two downsides to this; (1) it has to be done manually, and (2) there will be NO internet connection available until it is reversed.

Solution; have it connect to both networks simultaneously. If internet connectivity test fails for the wifi network, leave DEFAULT route on cellular connection, but keep routing local network IP addresses to the wifi network. DNS server provided by non-internet wifi network should be added at highest priority for local DNS resolution.

**Comment by thestinger** [comment]
We're not going how this works. If you want the feature you need to ask for it in AOSP.

**Comment by ASerbinski** [comment]
That's too bad. Its not worth the energy to ask upstream for it, best I would expect is for them to maybe accept a patch.
