### ISSUE TITLE
Upgrade the clock app to Material You

### ISSUE THREAD

**Issue by BluePixel4k** [GrapheneOS/os-issue-tracker#1298]
LineageOS has created a new clock app with Material You (LineageOS Clock 12). Would it be possible if you use / forked their app?

Screenshots:
<img src="https://user-images.githubusercontent.com/77979781/178105594-f8f8fed4-e225-4619-b14f-60af7d1ebd46.png" width="250" /> <img src="https://user-images.githubusercontent.com/77979781/178105600-1ed75e0e-53c0-4639-887e-2de9aaa5621f.png" width="250" />

**Comment by thestinger** [comment]
They didn't create a new Clock app. They made changes to AOSP DeskClock. We have no plans to incorporate these changes at this time due to the difficulty of maintaining it.

**Comment by thestinger** [comment]
If someone who substantially contributes to GrapheneOS maintenance is willing to work on this and to keep it maintained, they can submit the changes.

**Comment by Zanthed** [comment]
Looking at the changes they've made to DeskClock, it's WAY too many with dependencies on each other and very very large changes. I could submit a few tiny miniscule ones, but there's no way we're taking their DeskClock changes all together. Especially the Material You changes.

**Comment by BluePixel4k** [comment]
> but there's no way we're taking their DeskClock changes all together. Especially the Material You changes.

Very sad, the Material You design would improve the app and OS a lot.
