### ISSUE TITLE
Add support for black themes (AMOLED)

### ISSUE THREAD

**Issue by deadbeef2000** [GrapheneOS/os-issue-tracker#1299]
Hallo GrapheneOS crew,

I'd really love to see an option to make the dark mode in the Display Settings completely black.
It is easier on the eyes at night and it drains less battery on AMOLED devices.
I've seen this feature on quite a lot of other ROMs and I'm quite sure that it can be implemented without any security issues.

**Comment by thestinger** [comment]
The operating system fully supports apps choosing dark colors from the palette. We're not going to be override what's chosen by apps or changing a bunch of color palette choices across the OS. If we did, it wouldn't be an option.

> It is easier on the eyes at night and it drains less battery on AMOLED devices.

The dark theme colors are already very dark. The first claim isn't true. The 2nd is hardly true because the power savings are miniscule for black compared to dark grey.

This is not what GrapheneOS does.

**Comment by Zanthed** [comment]
The power savings myth was debunked so no, it is not going to save you any more power than using a normal dark theme.

https://www.xda-developers.com/amoled-black-vs-gray-dark-mode/

**Comment by CuriousApe2020** [comment]
Are you serios? You are not adding a true black option because you guys don't like it?

**Comment by ae5960e8-a6fc-491f-b252-898ecf59af95** [comment]
Seems like they don't want to add it. Regardless, pure black is a Google recognized system theme with most dark-mode supporting apps also supporting pure black. This theme increases accessibility, usability, and for some people just looks better. We get GOS is for security first and foremost, but the presence of the pure black color could not possibly be an attack vector or weaken the security, could it?

**Comment by ae5960e8-a6fc-491f-b252-898ecf59af95** [comment]
> > pure black is a Google recognized system theme with most dark-mode supporting apps also supporting pure black.
> 
> No, it isn't. It involves overriding the lightness levels apps want to use and hoping it doesn't cause compatibility issues.

Pure black is already a system theme in Android. There is light, dark, and pure black. GOS lacks pure black which like I've said improves ascetics and helps the visually impaired navigate the UI. I and others think it would be a good addition to the OS.

If any issues arise—though I haven't encountered any so far—simply to switch to a different theme for that specific app.


> > This theme increases accessibility, usability
> 
> [citation needed]

You can look up how high-contrast themes aid in visibility. It's known they help visually impaired people use the UIs and read written text.

**Comment by coolymike** [comment]
> This is not a standard feature and your claims are not backed up with evidence.

The feature is present in LineageOS. This is enough of a dealbreaker for me that I am using LineageOS, despite all the security improvements of GOS. "Pure Black" or OLED black mode might not "improve" much statistically speaking, but it is the way I (and many others) prefer to use a phone. If GrapheneOS does not support the way I prefer to use my phone, despite there being no technical challenges or security drawbacks to allowing an *optional color setting*, then I am not willing to use GOS. By disallowing this simple option, it is obvious that you do not have the end user in mind when developing the rom.

> > It is easier on the eyes at night and it drains less battery on AMOLED devices.
>
> The dark theme colors are already very dark. The first claim isn't true.

Where's your source on this? Pure black, having no background pixels turned on on AMOLED devices, produces less light (given the same display brightness setting). Having a background of any sort has those pixels turned on, which produces more light. It is completely irrelevant with any other light source present, but at night in pitch black, it is a lot more light.

> > pure black is a Google recognized system theme with most dark-mode supporting apps also supporting pure black.
> 
> No, it isn't. It involves overriding the lightness levels apps want to use and hoping it doesn't cause compatibility issues.

I haven't gone into the code for pure black myself, but having used it on LineageOS for a few years I have not run into "compatibility issues".

> > GOS lacks pure black which like I've said improves ascetics and helps the visually impaired navigate the UI. I and others think it would be a good addition to the OS.
> 
> This is not a standard feature and your claims are not backed up with evidence.

Considering that it is a feature on LineageOS, a rom that provides essentially only the "basic" features to get a device running, I'd consider it relatively standard. Also of note is that iOS has the feature, which is known for being well behind in "standard" features.

In addition, *your* claims are not backed up with any evidence. I have not seen you cite one source, or give one example of how it causes "compatibility issues". You can't complain about others not doing something you yourself don't do either.

On that note, here's a short selection of apps I have used on LineageOS with "Pure Black", that seamlessly integrate with the setting, alongside the LineageOS default apps that support Material You:
https://github.com/beemdevelopment/Aegis
https://github.com/patzly/doodle-android
The entire suite of [Fossify](https://github.com/FossifyOrg) apps
https://gitea.angry.im/PeterCxy/Shelter

And a short list of apps that have their own pure black option, which matches very well with the system pure black option:
https://github.com/bitwarden/mobile
https://codeberg.org/Bazsalanszky/Eternity
https://github.com/florisboard/florisboard
https://github.com/TeamNewPipe/NewPipe
https://github.com/ImranR98/Obtainium
https://github.com/SchildiChat/SchildiChat-android
