### ISSUE TITLE
Add fixed time to autoreboot

### ISSUE THREAD

**Issue by Retroman445** [GrapheneOS/os-issue-tracker#1307]
Is it an idea to add fixed times to the auto-reboot options so a device gets a reboot no matter what happens? Somehow it feels safe to reboot at night and yes I know it can be done with the options available but these are all relative to last unlock time.

I personally would like to start the morning adding my ridiculously long password into my phone to get the synapses flowing. ;-)

**Comment by flawedworld** [comment]
I don't not sure that this can be safely done due to the risk of introducing a bypass potentially. Would suggest using a longer auto reboot time if it's rebooting during the day.
