### ISSUE TITLE
Audio output chooser crash

### ISSUE THREAD

**Issue by loganb-aja** [GrapheneOS/os-issue-tracker#1313]
Device: Pixel 4a 
GrapheneOS patch level: 2022071100

I am experiencing a bug where tapping on the audio device chooser in the playback notification crashes the system UI. This has persisted through multiple systems updates and does not appear to change with playback application or what audio output device is connected / currently in use. 

Tapping on this button causes the screen to go black and then the System UI reloads and brings you back to the lock-screen. 
![image](https://user-images.githubusercontent.com/104534255/178791619-7098e34e-1e26-4b00-8d8d-0a846aa02baa.png)

**Comment by thestinger** [comment]
@loganb-aja Please let us know if this is still an issue on Android 13.

**Comment by BluePixel4k** [comment]
The bug is already gone. At least with me.
