### ISSUE TITLE
Camera Inversion

### ISSUE THREAD

**Issue by factorial52** [GrapheneOS/os-issue-tracker#1317]
Is it just me, or does the option to save image as previewed do exactly the opposite of what it's supposed to do?

**Comment by thestinger** [comment]
It depends on the device. Which device are you using?

**Comment by factorial52** [comment]
pixel 6. Also wow. That response time.

**Comment by thestinger** [comment]
What it does on non-broken devices is making it so that the saved image for images taken by the front camera will match the preview instead of being flipped. It does what it's meant to do. Compare captured image to preview.
