### ISSUE TITLE
Notification forwarding bug when receiving a notification during profile switching

### ISSUE THREAD

**Issue by daniel4ka** [GrapheneOS/os-issue-tracker#1318]
I've noticed unexpected behavior with the new notification forwarding feature (GrapheneOS 2022071300 on Pixel 6).

If I get a notification from an app in a certain profile right during the switch to that profile, the notification appears normally, but I sometimes get additional unexpected notifications from Android System's "Other users" notification channel.

Here's an example screenshot from a profile named Google of a notification from Element:

![4](https://user-images.githubusercontent.com/36897292/179071510-6fd84dd7-c26a-4dbf-862a-c7635e386af3.png)

**Comment by Zanthed** [comment]
If you're comfortable with running adb on your device, enable it and run `adb shell setprop log.tag.NotificationService DEBUG`

Then reproduce the bug and generate a bug report and if you have Matrix send it privately to me: `@june:grapheneos.org`

**Comment by daniel4ka** [comment]
Sorry, I'm not comfortable with running adb on my device.

But here's how I can reproduce the bug:
- Both profiles are set to forward notifications to each other.
- Send a Matrix message from another device to the phone (to get a new notification).
- Try to time it so that the notification is received roughly in the middle of the "Switching to <profile>..." message. It can take several tries to get the timing right.
