### ISSUE TITLE
No audio playback

### ISSUE THREAD

**Issue by svent1nel** [GrapheneOS/os-issue-tracker#1319]
Pixel 4a, SQ3A.220705.003.A1.2022071100

My phone cannot play any audio, including system sounds, alarms, and ringtones. Some non-system apps give errors when trying to play audio, but other than that there are no noticeable error messages or crashes.
I tried reinstalling GrapheneOS with the web installer but it did not fix the issue.

**Comment by flawedworld** [comment]
This sounds like a hardware issue.
