### ISSUE TITLE
"add account" button broken - unable to create accounts to link carddav/caldav

### ISSUE THREAD

**Issue by ak1n** [GrapheneOS/os-issue-tracker#1322]
To try and link the default graphene contacts app with carddav, only option in contact settings is "add account" which links to general settings "password & accounts" page. However, on this page clicking "Add account" just seems to refresh the page, not allowing addition of any type of account (I just have Signal account appearing there now).

This might be a related issue: https://github.com/GrapheneOS/os-issue-tracker/issues/131

However, the response there about needing additional backend services doesn't seem to explain why the "add account" button does nothing.

I furthermore am unable to discern how to link caldav, even with additional apps. Tried the "Simple Calendar Pro" app and trying to activate caldav results in "no synchronizable calendars" error.

If additional local backend (on the phone rather than remote server) is required for card/cal-dav, any guidance/recs would be appreciated.

**Comment by lbdroid** [comment]
You need to install a caldav client.
Try DAVx5.
