### ISSUE TITLE
Adjustment of default background

### ISSUE THREAD

**Issue by Turantel** [GrapheneOS/os-issue-tracker#1324]
The grapheneos web page https://grapheneos.org/ has levels of gray as its background which look pleasant to the eye. 
In contrast, the pitch black background seems to make less of a polished impression after a fresh first install.
Would it make sense to adjust the colors to follow the theme of the webpage, which also has a simplistic yet nice looking color palette?

**Comment by thestinger** [comment]
I think we're keeping this as is for now until a nice background fitting what I want is created.

**Comment by thomasbuilds** [comment]
@thestinger you like this? It's an svg so easily modifiable

<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/e49b61dd-1c82-4aac-8903-b81ca00cadcd" />

**Comment by thestinger** [comment]
No, not really.

**Comment by thomasbuilds** [comment]
ok yeah
I'd agree that when you have apps on top it's ugly
