### ISSUE TITLE
Ability to set Camera to always default to Latency

### ISSUE THREAD

**Issue by novocaiin** [GrapheneOS/os-issue-tracker#1325]
If you want to snap a quick photo (short on time or busy place) you probably don't want to wait for all the stabilization etc. to happen that happens in Quality.
Naturally in those situations you also don't have time to dig in settings to switch to Latency.

I think it would be beneficial to have the ability to set Camera to default to Latency, and if the user _does_ want to use Quality (which means they're not in a hurry), then that can be activated through Settings.

This would be similar to being able to set iOS's Camera to always default to Live Photos or the default filter.

**Comment by thestinger** [comment]
Not clear what you mean by this. The setting is persistent.
