### ISSUE TITLE
Dual SIM Dual Standby on Pixel 3

### ISSUE THREAD

**Issue by neunzehnachtneun** [GrapheneOS/os-issue-tracker#1329]
Disclaimer: I am using my old Pixel 3 and am aware that the device is no longer fully supported.

It seems there is dsds support missing on Pixel 3 phones. Without any technical reason Google removed this feature in Beta 3 of Android Q. Although Google removed it, it's still activable. Unfortunately it requires root access, which is why I am asking for general support for DSDS activating on Pixel 3.

Workaround with root access:
```
setprop persist.vendor.radio.multisim_switch_support true
*#*#4636#*#*
Phone Information
Enable DSDS
```
Further information: https://www.xda-developers.com/android-q-dual-sim-dual-standby-support-pixel-3/

Thank you!

**Comment by flawedworld** [comment]
We won't be making changes to 3rd generation Pixel devices at this time.

**Comment by thestinger** [comment]
It was disabled **because it doesn't work properly**.

**Comment by neunzehnachtneun** [comment]
> We won't be making changes to 3rd generation Pixel devices at this time.

Hi,
could you clarify what you mean by saying 'at this time'? Ist there a realistic chance to get this feature enabled?

Would be great! Thanks a lot!

**Comment by thestinger** [comment]
No, they're legacy devices and we're making our last release based on Android 12.1 soon. GrapheneOS will be strictly based on Android 13 and it won't be available for legacy devices.

**Comment by neunzehnachtneun** [comment]
Yeah, I still know that.

I never expected to get Android 13 on a Pixel 3. But I would like to see a tiny component, which seems to be a one- or two-liner in "init.blueline.rc".

**Comment by Zanthed** [comment]
As mentioned already, DSDS was *disabled* because it *does not work* properly on 3rd-gen devices.
