### ISSUE TITLE
fix incompatibility of RROs (dynamic overlays / themes) with wrap and exec spawning

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/os-issue-tracker#133]

**Comment by teatimetom** [comment]
Night mode and night light do not change automatically with the Pixel 2XL.

**Comment by thestinger** [comment]
I don't know what you mean. If you mean with the sunrise feature, that probably isn't going to work without a coarse location service which we don't currently have.

**Comment by teatimetom** [comment]
Yeah i mean the sunrise feature. Thanks for the answer. Is that currently still in the planning stage?

**Comment by thestinger** [comment]
https://github.com/GrapheneOS/os_issue_tracker/issues/24

**Comment by kenktk** [comment]
Are there plans on continuing to fix RROs?

**Comment by thestinger** [comment]
Still an issue on Android 13.

**Comment by r3g-5z** [comment]
Should be resolved by https://github.com/GrapheneOS/platform_frameworks_base/pull/355
