### ISSUE TITLE
Modified lockscreen pin pad

### ISSUE THREAD

**Issue by prayingmantis287** [GrapheneOS/os-issue-tracker#1330]
Over the last couple weeks I have noticed a modified pin pad (see screenshot) instead of the native one. The occurrence is sporadic; approximately once or twice a day, but not necessarily every day.

Issue occurs in secondary profile. Have not seen it happen in the primary profile yet, however the primary profile is not normally used either.

Environment:
- Fingerprint unlocking is configured to not allow unlocking the phone.
- There are no lockscreen modifying apps installed as far as I know.
- Issue has occurred with only two or three apps active, but no specific ones trigger the issue from what I can tell. One time it occurred with only VLC running.
- I cannot recall if the issue started happening after a specific GrapheneOS build.
- Pixel 5 build SQ3A.220705.003.A1.2022071300

I have not yet entered my pin on this pin pad, as it is unclear whether it is a bug or possible malware. The only way to avoid entering the pin on the modified pad is to tap 'End Session', then switch back to the secondary profile.

![Screenshot_20220718-175657](https://user-images.githubusercontent.com/39395422/180029237-56d0bc82-1ed8-443d-94f3-e04bee6b9db2.png)

**Comment by thestinger** [comment]
This is a known AOSP UI rendering issue. Not going to be fixed by GrapheneOS.
