### ISSUE TITLE
Research Weaver slot counts on Titan M and M2

### ISSUE THREAD

**Issue by flawedworld** [GrapheneOS/os-issue-tracker#1331]

**Comment by flawedworld** [comment]
Titan M2 confirmed to have 64 slots on 6th generation Pixel devices

**Comment by Zanthed** [comment]
Titan M appears to also have 64 slots.

Debug code that was used to determine both the Titan M (redfin) and Titan M2 (raven) values: https://github.com/HomestuckOS/platform_frameworks_base/commit/52e2c1334cedfc2cfb35ac02b4fb95be2e648f5f#diff-c700ca221704e5dfae18b3d0688fa405983a906695f88b7b33b32f20f68062f5R412

**Comment by Zanthed** [comment]
We need to validate this is consistent across 4th gen devices too.

3rd gen devices are EOL so they are out of scope here.

**Comment by Zanthed** [comment]
I had someone with a 4th gen device (Pixel 4a) test using my debug code. I confirmed it has 64 slots as well.
