### ISSUE TITLE
When implementing Contact Scopes, do it differently from Storage Scopes

### ISSUE THREAD

**Issue by FieryBinary** [GrapheneOS/os-issue-tracker#1332]
I noticed that the project plans to implement a Storage Scopes-esque feature for contacts. It is best to implement this differently from Storage Scopes, so instead of picking certain contacts to give to an app, the user can give a completely separate list of contacts instead.

The user would make multiple lists of contacts. Then, when an app requests Contacts permission, the system prompts the user to select one of them, and presents it to the app as the full list.

This approach would (I think) be easier to develop since you can extend the system contacts provider to have multiple contacts lists. You would be making app-specific lists either way, and this just lets the user have more control over the list content.

Additionally, the user can give a different list of contacts whose names and non-essential fields are wrong. Messaging "Fiery Binary" could become "John Smith", "Daniel Micay" could become "Adam Thomas", and so on. This could confuse or fool the app, making it harder to figure out the user's social network.

**Comment by thestinger** [comment]
Merging this into https://github.com/GrapheneOS/os-issue-tracker/issues/1294.
