### ISSUE TITLE
Lock Screen Numpad Buttons Animations Tearing

### ISSUE THREAD

**Issue by seniorm0ment** [GrapheneOS/os-issue-tracker#1333]
I notice the animations when pressing the numpad buttons on the lockscreen flicker in a way that looks like screen tearing although it's contained within the buttons only.
This could potentially be a result of setting a high dpi (570dpi) in developer settings, although I have not confirmed that is the cause. I notice this on no other screens.

**Comment by thestinger** [comment]
https://github.com/GrapheneOS/os-issue-tracker/issues/1330
