### ISSUE TITLE
Add button or toggle to auto reject further requests to unblock camera/microphone if denied once

### ISSUE THREAD

**Issue by TempUser13** [GrapheneOS/os-issue-tracker#1338]
If you use an app such as Snapchat with the camera blocked through the quick setting tile, it will keep asking over and over to unblock rendering the app unusable unless you unblock camera or use the sensors off tile. The auto reject could mark the camera or microphone as unavailable to stop the app requesting again or something.

**Comment by thestinger** [comment]
You can accomplish this by disabling the permission for the app if the app is being annoying.

**Comment by thestinger** [comment]
I don't think we're going to change this downstream. Android 13 has some improvements.
