### ISSUE TITLE
'Turn on Wi-Fi automatically' not working

### ISSUE THREAD

**Issue by lbschenkel** [GrapheneOS/os-issue-tracker#1341]
- Pixel 6
- GrapheneOS: `SQ3A.220705.003.A1.2022072000`
- Turn on Wi-Fi automatically: on
- Turn off Wi-Fi automatically: on
- Wi-Fi scanning: on
- Google Play Services: installed
  - Location permission: granted
  - Location accuracy: on
  - Reroute location requests to the OS: off
- Reset Wi-Fi, mobile & Bluetooth: already tried, no change 

Is 'Turn on Wi-Fi automatically' supposed to be working? I could never make it work on my device. If I walk out of SSID range, let Wi-Fi turn off by itself (this works), then walk back into SSID range, Wi-Fi never turns on even after many hours. Tried with different networks in different places.

Does it work for you developers if you set a short auto-off timeout (like 30 seconds), walk out of Wi-Fi range, wait until Wi-Fi turns off, then walk back into range? 

I have first reported this to the discussion forum at https://discuss.grapheneos.org/d/307-turn-on-wi-fi-automatically-not-working/ and included some logcat outputs, including some suspicious errors that might be related. For the sake of brevity I am not replicating those here, but in case you prefer that please let me know.

**Comment by thestinger** [comment]
It works but there isn't an OS network location service and it doesn't use the location API in a way that works with GNSS since it would use too much power and wouldn't be fast enough. If we ever add a network location service, which we would do via a local implementation using a cell tower / Wi-Fi network database, then this would start working. We could consider removing the option until then. It's working as intended though.

**Comment by lbschenkel** [comment]
Right, so it does not actually work a the moment (from a user-facing perspective). I understand why now.

Are there any plans to make GmsCompat be a network location provider by delegating to Play Services? Completely opt-in, of course. It is a bit frustrating that apps using Play Services can use it but not others or the system.

**Comment by thestinger** [comment]
The location provider list used by the OS is meant to be statically configured and based on system components alone. It isn't per-profile and it wouldn't be straightforward to support that.

**Comment by lbschenkel** [comment]
I know this isn't a discussion forum, but please bear with me.

> The location provider list used by the OS is meant to be statically configured and based on system components alone. It isn't per-profile and it wouldn't be straightforward to support that.

Isn't GmsCompat an always-installed system app? Couldn't it be an always installed network provider that returns no results / fails by default (whatever is appropriate), *or* (1) if GMS is installed and has location permissions and (2) user has opted in, then forwards the network location request to GMS and then provides back the results? It's basically the opposite of the current setting in which it "captures" requests sent to GMS (enabling GMS->system and system->GMS at the same time don't make sense of course). Probably viable if it happens only in main profile, just like eSIM provisioning.

A follow-up thing I don't fully understand: to debug this problem I was looking at logcat and I also inspected https://github.com/GrapheneOS/platform_packages_modules_Wifi to understand how it works (I am a Java developer myself and I'm comfortable reading the source code). I am confused as to why network-based geolocation is necessary or where it happens, because my reading is that all the WakeupController needs is the list of SSIDs from the wi-fi scan, it does not need to "locate" them in any way. I can confirm via logcat that the wi-fi scans actually take place, what I could not determine is where/how the SSIDs get filtered because the listener does not see them. Can you please point me out to where the wi-fi wake-up code depends on the network location functionality?

**Comment by froman753** [comment]
Any update on this? I am also interested in it

**Comment by HansCronau** [comment]
> It works but there isn't an OS network location service and it doesn't use the location API in a way that works with GNSS since it would use too much power and wouldn't be fast enough. If we ever add a network location service, which we would do via a local implementation using a cell tower / Wi-Fi network database, then this would start working. We could consider removing the option until then. It's working as intended though.

I see this issue is closed (as are related issues #2016) but from a UX standpoint this remains unresolved. The option "Turn on Wi-Fi automatically" reads: "Wi-Fi will turn back on near high-quality saved networks, like your home network". At the moment, this is a broken promise, which confuses users (and leads then to add comments to years old GitHub issues).
@thestinger's suggestion to remove the setting until it's dependencies work sounds like a reasonable solution to this problem.

**Comment by HansCronau** [comment]
@thestinger Was this "completed" as in:

> We're just going to add support for network-based location

or as in

> It is possible to use this by using an app which keeps the location cache filled with a fresh location by querying it regularly.

?

If the latter:

1. I'm having a hard time finding an app that does this. Which app can you advise?
2. Would it be possible to add your explanation to the relevant Settings screen, so that users don't get angry/frustrated because they don't know why the feature doesn't work out of the box?

**Comment by AtavisticPuma** [comment]
> We added our own network location implementation you can enable in Settings > Location > Location services > Network location along with optionally enabling Wi-Fi scanning in the Location services menu to make it work with Wi-Fi off.

I have these set, and the feature _does_ show `Wi-Fi turns back on automatically` however wifi only comes back on automatically if Location gets turned on by an app.  I would have expected that instead the OS should periodically enable and check the location for itself.

**Comment by marvinestreet** [comment]
> We added our own network location implementation you can enable in Settings > Location > Location services > Network location along with optionally enabling Wi-Fi scanning in the Location services menu to make it work with Wi-Fi off.

@thestinger can you or someone explain to me the complete steps to make Wifi turn on automatically...?

**Comment by rmsa5** [comment]
Hello, running updated GOS on Pixel9Pro, I have:

- "Turn on Wi-Fi automatically" ON
- "Location Services > Wi-Fi scanning" ON
- "Location Services > Network location" set to "GrapheneOS Apple proxy" (which info says "currently, "Wi-Fi networks and cell towers are used")
- full 5G network coverage

And yet, not a single time have I ever seen my phone switch on Wi-Fi automatically and connect to one of my saved Wi-Fi networks (including my home one).

Am I missing something or is the feature still broken?
