### ISSUE TITLE
No more Internet on Pixel4a / GrapheneOS

### ISSUE THREAD

**Issue by ulph0** [GrapheneOS/os-issue-tracker#1342]
Hi, i am just posting this error description by a friend. SHe is an Enduser and i don't use GrapheneOS. If anyone has a solution/suggestions, i will forward it. Regards.

I have the phone google pixel 4a with grapheneos operating system now 
since about 6 weeks in use and we even managed to install the esim 
without reinstalling the operating system. until yesterday 
night everything was great...

i arrived in berlin last evening and last night my phone turned off, most likely because the battery was low, but actually
i still had 40% battery before going to sleep. in the morning the battery was empty then 
and after i charged it and started it the internet did not work 
it doesn't work over wifi either, something seems to be blocking it... 
maybe there was an update during the night or something...  at 
system settings it says system update: updated to android 
12, but not when the update taked place. anyway now only phone and sms works.

The stupid thing is also that I have internet only by
handyhotspot, so now also no internet at home. I have already asked in the 
in the computer store of my trust, but they say that no one knows. don't know what to do. 

do you have a tip for me? maybe you will find something?

Translated with www.DeepL.com/Translator (free version)

**Comment by thestinger** [comment]
We're unable to provide support on the issue tracker. Please use the Matrix chat room or discussion forum, Providing support through someone else also isn't practical.
