### ISSUE TITLE
3rd Party keyboards crashing.

### ISSUE THREAD

**Issue by VulcanElf** [GrapheneOS/os-issue-tracker#1343]
Even after clearing cache, storage, or reinstaling, 3rd party keyboards are crashing, including Gboard and Florisboard. The keyboard is displayed for a fraction of a second and then disappears.

**Comment by Zanthed** [comment]
The issues you're opening appear to be of some kind of hardware failure and nothing related to GrapheneOS.

**Comment by VulcanElf** [comment]
I am using a Pixel 5. No hardware, issue prior to beta release

**Comment by thestinger** [comment]
This is almost certainly a configuration issue due to you changing system component settings.

**Comment by VulcanElf** [comment]
Uninstalling, then reinstalling GSF, play services, and Play store resolved this issue.
