### ISSUE TITLE
Work profile apps crash

### ISSUE THREAD

**Issue by VulcanElf** [GrapheneOS/os-issue-tracker#1344]
All work profile apps are unusable EXCEPT VPN profile when selected as Always On VPN

**Comment by Zanthed** [comment]
The issues you're opening appear to be of some kind of hardware failure and nothing related to GrapheneOS.

**Comment by thestinger** [comment]
This is almost certainly a configuration issue due to you changing system component settings.

**Comment by VulcanElf** [comment]
Uninstalling, then reinstalling GSF, play services, and Play store resolved this issue.
