### ISSUE TITLE
Force Stop not functioning

### ISSUE THREAD

**Issue by VulcanElf** [GrapheneOS/os-issue-tracker#1345]
Force stopping apps is not functioning as apps do not close.

**Comment by VulcanElf** [comment]
This includes music and video apps

**Comment by Zanthed** [comment]
You need to be more specific.

**Comment by VulcanElf** [comment]
When attempt ing to force stop an app, the app does not respond. There also is no greyed out Force Stop button. Apps keep playing music, navigating, etc

**Comment by thestinger** [comment]
This is almost certainly a configuration issue due to you changing system component settings.
