### ISSUE TITLE
Some Apps crash on launch

### ISSUE THREAD

**Issue by noone-one** [GrapheneOS/os-issue-tracker#1351]
e.g. Garmin Connect App crash on launch and no connection to clock (venu2)
DWD Weather app also crashed on launch.

**Comment by muhomorr** [comment]
Unable to reproduce these crashes.

Which device do you have? Have you installed sandboxed Google Play?

**Comment by thestinger** [comment]
Make sure to install apps depending on sandboxed Google Play after sandboxed Google Play.

**Comment by noone-one** [comment]
Device is Pixel 6.

sandboxed Google Play installed.


Regards
