### ISSUE TITLE
Camera app freezes the phone and forces a reboot

### ISSUE THREAD

**Issue by crepecom** [GrapheneOS/os-issue-tracker#1352]
The camera app sometimes freezes the entire device when taking a picture and forces the device to reboot.
I also experienced the same only launching the app sometimes.
Right now it appears to happen randomly, i did not notice any specific conditions when this happens. 

Device: Pixel 4a 5g
Default configuration
No gapps installed

**Comment by thestinger** [comment]
Likely caused by overheating due to a hardware issue.
