### ISSUE TITLE
Cannot install specific apps from another user account, when installed on owner account.

### ISSUE THREAD

**Issue by JamieMair** [GrapheneOS/os-issue-tracker#1353]
I am having the same issue as https://github.com/GrapheneOS/os-issue-tracker/issues/1271 but the solution posted here does not work, and I still get the generic error "App cannot be installed as it appears to be invalid", even when using the newest download. Specifically this is for F-Droid and DuckDuckGo Privacy Browser.

**Comment by thestinger** [comment]
In that case it seems you installed variants of those apps from elsewhere or the downloads are corrupt.

**Comment by JamieMair** [comment]
I restarted the phone and redownloaded the F-Droid APK and now it seems to work, it was possibly a corrupt download.

Would it be possible to change the error message from "the apk is invalid" to something more specific, like - "This app is installed on another user with a later version, try installing the latest version."

**Comment by thestinger** [comment]
It's a standard AOSP error message and we don't currently have plans to change these.
