### ISSUE TITLE
Step counter doesn't count since 2022072700

### ISSUE THREAD

**Issue by haary** [GrapheneOS/os-issue-tracker#1354]
I am using the step counter app from https://f-droid.org/de/packages/de.j4velin.pedometer/ and it was working flawlessly. Since the update to 2022072700 on my Pixel 4a it doesn't count the steps anymore. I tried another step counter (https://f-droid.org/de/packages/org.secuso.privacyfriendlyactivitytracker/) which doesn't work either. Reinstalling the app had also no effect. 

I did read in the changelog for 2022072700

>  enforce ACTIVITY_RECOGNITION sensor permission for target API < 29 apps (fixes upstream Android privacy flaw)

and I suspect this has something to do with it?

**Comment by thestinger** [comment]
These apps are unmaintained, still target below API 29 and wouldn't be allowed on the Play Store anymore as either new apps or updates to existing apps. They'd also be unlisted from the Play Store in the near future. We decided to fix this privacy flaw in a way that drops support for legacy apps using this feature. It was an explicit choice.

F-Droid has issues with lots of unmaintained, insecure apps still being included in the repository with no warnings.

cc @muhomorr

**Comment by thestinger** [comment]
To clarify: apps below API 29 (below Android 10) could access the activity sensors without any permission. Apps targeting API 29 and above need to use a permission. We decided to drop support for the legacy apps.

Android 12 is the current release (API 32) and Android 13 is about to come out. The Play Store requires API 30+ for new apps and app updates. Apps not targeting current API levels are going to be unlisted from the Play Store. It's unfortunate other app stores have lower standards but we base our decisions on this stuff around the Play Store app ecosystem and our expectation is that another app ecosystem tries to do at least as well.

**Comment by muhomorr** [comment]
https://f-droid.org/de/packages/org.secuso.privacyfriendlyactivitytracker/ has targetSdk of 30 and shouldn't be affected by the ACTIVITY_RECOGNITION enforcement change.

The other one (https://f-droid.org/de/packages/de.j4velin.pedometer/) targets SDK 26, which is 5 years old at this point.

**Comment by thestinger** [comment]
We'll be making a change to improve the compatibility of this privacy fix with legacy apps.
