### ISSUE TITLE
Alphabetical Sorting of User Profiles

### ISSUE THREAD

**Issue by inferenceus** [GrapheneOS/os-issue-tracker#1355]
I heavily use the user profiles feature of GrapheneOS to compartmentalise my apps and data. I have a specific naming scheme for my user profiles, and I have noticed that creating or deleting user profiles causes them to move around in the user selection dialog/list in an unordered fashion.

It would be nice to be able to sort user profiles alphabetically, so they are pinned to the same location (at least A-Z) in the user profiles list so creating or deleting them doesn't cause the rest to lose their place where they were (including if creating new user profiles which are added to the end of the dialog/list, despite their names being letters before the other ones).

I believe such a user profiles sorting feature would make it a lot easier and more efficient for people who use numbering or other specific user profile naming schemes, such as myself. Of course, the user should be checking which user profile they are logging into, but, despite knowing this, it is too easy to currently accidentally log into a user account which you subconciously remember being in one place before creating or deleting others, causing me to log into other profiles, which could potentially cause a security/privacy risk, depending on where the user logs into the user profiles, such as in public. It would also be a nice organisation feature even for general use cases.

**Comment by lfq33dl5** [comment]
To improve this: An option to manually move profiles.
This could work like with the apps on the ```Select user``` screen, or also in the user settings.

**Comment by thestinger** [comment]
Ended up being too complex unless a better way is found to do it. Will be closed if there isn't a simple way to do it in a few lines of easily maintained code.
