### ISSUE TITLE
Fake call permission

### ISSUE THREAD

**Issue by enduring78** [GrapheneOS/os-issue-tracker#1356]
This is more of a enhancement than a issue, but some apps request the phone permission and refuse to work without it. 

GrapheneOS already implemented faking the internet permission and the storage permission.

It also implemented faking the phone permission, but only for the sandboxed Google Play. The goal of this 'issue' is making a toggle which tells apps they have the phone permission, but get all 0's instead of the real IMEI.

**Comment by Zanthed** [comment]
Apps don't have access to IMEI since Android 10. Phone permission doesn't give them that.

**Comment by enduring78** [comment]
Apps like Samsung Health and a few messaging apps require the phone permission, if the user does not give it, they simply refuse to work. 

Since GrapheneOS did it with a few other permissions, why not with this one?
