### ISSUE TITLE
Pixel 6a Spectrum Mobile Mobile Data not working

### ISSUE THREAD

**Issue by Ericarthurc** [GrapheneOS/os-issue-tracker#1359]
![Screenshot_20220806-165744](https://user-images.githubusercontent.com/22304079/183269987-911a6a38-c353-465b-a8b3-b5e63ab40e8c.png)
![Screenshot_20220806-165947](https://user-images.githubusercontent.com/22304079/183269989-5e864317-ac49-4d8b-a223-10407fa20353.png)

I am on the new Pixel 6a stable build and my mobile data is not working. Sms and MMS and calls are all working; and it looks like 5G and LTE are connecting, but if wifi is off, everything is offline.

**Comment by Ericarthurc** [comment]
All APN settings look correct too for Spectrum Mobile

**Comment by Ericarthurc** [comment]
I clean flashed Graphenos manually from the bootloader over fastboot

**Comment by Ericarthurc** [comment]
I got it correctly working with the: vzwinternet APN settings
No problems now; getting 5G, sms, mms and calls great!

**Comment by coupa-mattm** [comment]
Hey @Ericarthurc. Can you elaborate more or link to instructions on how you achieved this?

**Comment by Ericarthurc** [comment]
> vzwinternet

I just created a new APN profile and used all the verizon (vzwinternet) settings and then it worked correctly. Spectrum Mobile uses Verizon call towers. I haven't used this rom in a long time though, so not sure of the current status of this support.

**Comment by Ericarthurc** [comment]
> Hey @Ericarthurc. Can you elaborate more or link to instructions on how you achieved this?

I just created a new APN profile and used all the verizon (vzwinternet) settings and then it worked correctly. Spectrum Mobile uses Verizon call towers. I haven't used this rom in a long time though, so not sure of the current status of this support.
