### ISSUE TITLE
Always on VPN not available for IKEv2/IPSEC RSA connection

### ISSUE THREAD

**Issue by dle-grapheneos** [GrapheneOS/os-issue-tracker#1363]
I've configured a new VPN connection to my own pfSense server.  I use a self-signed CA with client and server certificates.  The VPN connection itself works fine.  I believe I am updated with the most recent build: 2022080500.

However, the "Always on VPN" checkbox is disabled on the VPN configuration screen.  If I were to select the "MSCHAPv2" or "PSK" VPN types, the "Always on VPN" checkbox becomes enabled as soon as the respective authentication fields are filled in.   I can't find any reason why the "RSA" authentication type VPN should be special in not supporting "Always on VPN". 

Possible bug: frameworks/base/core/java/android/net/Ikev2VpnProfile.java, line 632:
>           case TYPE_IKEV2_IPSEC_RSA:
>               if (profile.ipsecSecret.isEmpty() || profile.ipsecUserCert.isEmpty()) {
>                   return false;
>               }
Since there is no place to enter a "Secret" field for "RSA" configuration, the call to `profile.ipsecSecret.isEmpty()` will always return true.  A fix would be to remove the first half of the conditional.

**Comment by dle-grapheneos** [comment]
I think I found your upstream bug report: 241819497.  Looks like customer support is not very proactive, even though it seems like this issue would be trivial to reproduce.  

Naturally, I try to minimize my association with Google and do not have any kind of account to upload their requested video demonstration.  

If I were to provide a patch file, could you put that in front of the appropriate code owner instead?

**Comment by thestinger** [comment]
If you want this fixed, I suggest you submit a patch to AOSP. We're likely to backport it if it's merged. We don't have time to work on this.

**Comment by r3g-5z** [comment]
Is this still an issue?

**Comment by r3g-5z** [comment]
Closing assuming this was resolved upstream or the issue doesn't persist anymore, but self-signed certificates for enterprise Wi-Fi and VPN connections is being rapidly phased out upstream and your setup will break in the future.
