### ISSUE TITLE
Limited Features Google Messages

### ISSUE THREAD

**Issue by charlesknoppenhoffer** [GrapheneOS/os-issue-tracker#1364]
google messages:  20220721_04_RC01.phone_dynamic
graphene: 2022080500
pixel 5

Stock android google messages on an old pixel 3a shows a number of options in the app settings menu not present when using the same on graphene on a pixel 5. See screenshots. Also unable to schedule send messages. Same version of Messages app both phones. My technical acumen is limited and I assume I am missing something obvious. Forgive me.

Thank you.

![grapheneos](https://user-images.githubusercontent.com/101299726/183744023-0e5fe694-3431-4128-a4ee-0d1e6d12166e.png)
![stockandroid](https://user-images.githubusercontent.com/101299726/183744053-f89ceeaa-1f4b-44ad-8472-c60726bf1747.png)

**Comment by jorgeluiscarrillo** [comment]
You will need to set up [sandboxed Google Play](https://grapheneos.org/usage#sandboxed-google-play) if you want that functionality. Chat features will work as well if you grant Play services Phone and SMS permission.
