### ISSUE TITLE
Incorrect connectivityManager.activeNetworkInfo.isConnected=false value

### ISSUE THREAD

**Issue by lgommans** [GrapheneOS/os-issue-tracker#1365]
Apps such as Signal, StreetComplete, and F-Droid ask the OS whether there is an active network connection before doing internet stuff. When the OS is wrong, you literally cannot use those apps' online functionality. There is no override. Signal also gives no indication: you have to open up another affected app to know whether Signal is working.

I started having this problem on a Samsung stock Android 11 device. Now that I've got GrapheneOS installed on a Pixel 6, I noticed it here as well. There shouldn't be anything special about my GrapheneOS setup, like I don't have any app to mess with iptables rules. The updater says my system is up to date.

Internet works fine: I can receive messages/emails in other apps and use a browser without noticing any impairments. Then I open up F-Droid and it says "no internet connection". StreetComplete is even funnier: I can pan around the map (which downloads data for rendering, similar to google maps), everything works fine, until I hit the upload button: "You are offline". Sometimes this means I need to stop using the app, since otherwise it will bundle uploads for a large area which makes the openstreetmap history light up like a christmas tree.

There is no reliable way to fix it: turning connections off and on sometimes works, sometimes doesn't (at least not before I give up and try again in an hour).

This happens daily on my main driver (Samsung). GrapheneOS is not my daily driver and I don't have as many `isConnected`-dependent apps installed there (just F-Droid), so I can't say how frequently it happens there.

There are no obvious steps to reproduce. It seems to be more likely the longer I'm connected to a network (on the order of hours, including while the phone is sleeping), and more often on mobile data than on WiFi, but I'm not sure about either. I'm fairly sure it starts spontaneously and isn't tied to reconnecting, but the code does seem to reevaluate its status after reconnecting so this is often the way to get Signal/F-Droid/StreetComplete to work again.

Link to the relevant code in an app that does this: https://github.com/streetcomplete/StreetComplete/blob/0b292ae71aeb5d95e0c316d26f323d3c0b5b4cef/app/src/main/java/de/westnordost/streetcomplete/screens/MainActivity.kt#L218-L219

On my other device (Samsung), I have installed some privacy apps like AFWall and TrackerControl (which set iptables rules and create a vpn to block trackers). I imagine this does not happen in the plain Samsung firmware without anyone else having noticed, so at least on Samsung I brought this upon myself by installing these privacy apps. Perhaps this helps narrow down the cause. Again, the Pixel device where I have GrapheneOS installed is completely separate from all this. The only commonality are some installed apps like F-Droid, train app, etc. The SIM is different, the mobile network is different, the country is often different, etc.

Setting this `isConnected` flag permanently to true would solve the problem for me. I don't know of any adverse effects since apps would simply get 'no route to host' instantly, pretty much equally fast as checking this OS flag before sending packets. I'd be happy if there was just an option somewhere, perhaps in developer settings, to force returning true here.

**Comment by thestinger** [comment]
It sounds like you're blocking the connectivity checks.

**Comment by thestinger** [comment]
> I started having this problem on a Samsung stock Android 11 device.

As you said, it's happening elsewhere, so it doesn't sound like an issue caused by GrapheneOS.

You should get a notification if the connectivity checks detect that the internet is down unless you disabled it.

GrapheneOS has the added feature of being able to toggle the connectivity check server. It uses our own server by default and if you like you can disable the feature. If you disable the feature then everything will always think that the device has internet access when any network is available even if it's not working or not internet connected. The connectivity checks make that work properly and provide fallback to other networks when one lacks connectivity.

**Comment by thestinger** [comment]
This would be a better fit for discuss.grapheneos.org. I suggest reposting it there if you still have problems.

**Comment by lgommans** [comment]
> It sounds like you're blocking the connectivity checks.

No I am not. "There shouldn't be anything special about my GrapheneOS setup, like I don't have any app to mess with iptables rules." I am having this problem on a default install, not using any VPN, on a normal network that anyone else in Germany should also have.

Furthermore, as I understood it, `isConnected` just returns whether you have a network connection without caring about the reachability of particular systems on the Internet.

To double check that (the [docs](https://developer.android.com/reference/android/net/NetworkInfo#isConnected()) are ambiguous), I just made a hotspot on another phone with no other connection whatsoever and, after connecting to it, `isConnected` returns true. I can see by the WiFi symbol blinking that it does the connectivity check, this fails and it shows the exclamation mark next to the WiFi symbol in the status bar, but StreetComplete still happily tries to download data (both during and after the check) because the network is, in fact, connected. When I turn off WiFi, StreetComplete shows "You are offline" as expected, so then `isConnected` is correctly false.

The connection test you mention does not seem to impact this variable. Even if GrapheneOS' connectivity checking server were offline, it shouldn't cause this problem. (Such a scenario would also break many thousands of apps, so this dependency would be risky; makes sense that it is not the case.)

I shouldn't be surprised bringing up another device and giving too much information would lead to a misunderstanding and it being closed immediately... lesson noted. I was making the comparison with another device only because it might help narrow down what the cause might be, e.g. maybe GrapheneOS makes the AOSP code take the same faulty path as having a fake VPN enabled does. **I do not in fact have any connection blocking installed on the device with GrapheneOS, nor on the network** (that would be difficult on mobile data from a mainstream carrier).

> As you said, it's happening elsewhere, so it doesn't sound like an issue caused by GrapheneOS.

I would presume it doesn't happen on the AOSP code that GrapheneOS is based on, or a billion people would be reporting this problem to their respective hardware or app vendors. It does happen on a device with GrapheneOS and no other modifications. I followed the regular installation instructions on the website, using the webusb installation method.

**Comment by thestinger** [comment]
You said above that the issue is occurring for you outside GrapheneOS:

>I started having this problem on a Samsung stock Android 11 device. Now that I've got GrapheneOS installed on a Pixel 6, I noticed it here as well. There shouldn't be anything special about my GrapheneOS setup, like I don't have any app to mess with iptables rules. The updater says my system is up to date.

**Comment by thestinger** [comment]
We've never seen anyone report a similar problem before. You have the problem on a non-GrapheneOS device and a GrapheneOS device. It's almost certainly something you have done on both devices or an issue with your network.

> I would presume it doesn't happen on the AOSP code that GrapheneOS is based on, or a billion people would be reporting this problem to their respective hardware or app vendors. It does happen on a device with GrapheneOS and no other modifications. I followed the regular installation instructions on the website, using the webusb installation method.

No one has ever reported a similar kind of issue with GrapheneOS. The only person to report the issue (yourself) says they have the problem on a non-GrapheneOS device too.

**Comment by lgommans** [comment]
> something you have done on both devices

The GrapheneOS device is fairly new and from work, so I haven't done much to it. These are the steps I took there:

1. Install GrapheneOS on the device following the default instructions
2. Install F-Droid via the default installed browser on the device itself.
3. Install Google Play Store and dependencies via the default-installed GrapheneOS app repository, and create a fresh Google account for this device to be able to use it.
4. Install other apps such as Signal messenger, a 2FA authenticator for work, Deutsche Bahn app for finding train connections and showing train tickets, and other apps that don't mess with the network. Nothing I installed here uses root, pretends to be a vpn, or messes with system or kernel settings.
5. I don't recall if I changed settings in the regular Android OS settings menu, but I seem to remember that (nearly?) all the defaults on GrapheneOS were already as I wanted them.
6. Find that the problem exists on GrapheneOS and being glad that this is *not* a one-off issue that I cannot reproduce on other Androids but a broader problem that might be solvable.

My GrapheneOS device is from work; it isn't mine. I don't install crap on there and mess with it the way that I do with my private phone.

> or an issue with your network.

The SIM is different, the SIM's owner is registered to my employer for the Pixel device and to my person (in another country) on my private device, the mobile network for my private sim (O2) and the work sim (Telekom) are different... what else could I check?

There is no commonality in network, at least for mobile data. No other device (other Androids) has this problem on the WiFis I use either.

> The only person to report the issue (yourself) says they have the problem on a non-GrapheneOS device too.

Hence I tried tracking down and eliminating commonalities that I might possibly have introduced. If there is anything I haven't already ruled out that this isConnected flag depends on, then I'd be happy to check it (on the Samsung I can go deeper using root, if that would help).

**Comment by thestinger** [comment]
Please try resetting app settings / permissions via Settings app settings reset option.

**Comment by muhomorr** [comment]
Have you used VPN at any point on GrapheneOS?

**Comment by lgommans** [comment]
VPN: No. I installed wireguard in anticipation, but haven't gotten around to configuring it; pretty sure I didn't even launch it once yet. Let me just uninstall it for the time being as I'm not using it anyhow currently.

Reset app preferences: done. Will report back if it happens again! (Will be at least a few days, as I won't be using this phone while I'm not working the next few days.)
