### ISSUE TITLE
Cell data not available after connecting to Wifi

### ISSUE THREAD

**Issue by nker150** [GrapheneOS/os-issue-tracker#1366]
It seems every time I connect to a WiFi network cellular data becomes inaccessible. Cellular data indicator shows empty with an exclamation point as if I'm in a dead zone. 

I've tried toggling cell data on and off, that doesn't seem to help. The only solution I've found is to completely restart the device. 

I'm running build SQ3A.220705.004.2022080500 on a Pixel 6. Issue seems to have persisted for a few minor updates.

**Comment by thestinger** [comment]
Please use the discussion forum or Matrix room for this. Not much reason to think there's a bug.
