### ISSUE TITLE
Web app shortcuts disappear

### ISSUE THREAD

**Issue by knomdivad** [GrapheneOS/os-issue-tracker#1367]
Home screen shortcuts for web apps or pages are removed at various times. This has happened with different browsers, including vanadium, and with different launchers, including the Graphene one. It is not consistently repeatable. But it happens frequently, sometimes multiple times a day associated with a normal restart. 
The longest I've gone without them disappearing was several says using the Brave browser and Lawnchair 2 launcher. The most consistent was prior to the most recent update with Vanadium and the default launcher happening at most reboots. 

Pixel 6 Pro
SQ3A.220705.004.2022080900

**Comment by thestinger** [comment]
Sounds like you're clearing browser data. There are multiple backends for this and the one not requiring a Google service to generate and sign an app has them cleared after clearing data.

**Comment by knomdivad** [comment]
I have all default settings and am not clearing browser cache.

**Comment by knomdivad** [comment]
I've tried this with 3 browsers and 2 launchers. Perhaps it's the OS webview causing it. I am clearing no caches or data of any kind. You could investigate some before just dismissing

**Comment by Zanthed** [comment]
You can't reasonably attribute this being caused by a WebView / OS update at all. There's very little if anything to investigate.

**Comment by Zanthed** [comment]
WebView has nothing to do with home shortcuts.

**Comment by knomdivad** [comment]
It's not the browser or the launcher.
