### ISSUE TITLE
PIN entry keypad changes size randomly

### ISSUE THREAD

**Issue by cooltacokid1** [GrapheneOS/os-issue-tracker#1368]
https://ibb.co/0G8G15h
https://ibb.co/mNtKdvt

These two screenshots were taken on the same Pixel 5 running latest release, and I can't determine what causes these buttons to change shape/size. It causes me to miss my initial few digits frequently.  70-90% of the time, they're the 'correct' larger size, but will randomly shrink down.

**Comment by Zanthed** [comment]
Known upstream AOSP bug that also occurs in stock OS, not worth our time investigating it.

https://github.com/GrapheneOS/os-issue-tracker/issues/1330
