### ISSUE TITLE
Pixel 4a, Swipe Up Fails and Phone is Freezing following Update

### ISSUE THREAD

**Issue by bethhd** [GrapheneOS/os-issue-tracker#1369]
After taking an update today, my phone is frequently freezing. In portrait orientation, swipe up doesn’t work at all; and the keypad doesn’t work most of the time. In landscape orientation, swipe up and typing work when the phone doesn’t freeze. This is a pixel 4a. I haven’t had any issues with it before this upgrade.

**Comment by thestinger** [comment]
Please get support in the Matrix room or discussion forum. It's not a bug with the OS.

**Comment by bethhd** [comment]
It happened following an upgrade, but it’s not a bug… right.

**Comment by thestinger** [comment]
Every issue you encounter will always be shortly after an update because there are frequent updates. It doesn't mean that it's because of an update.

**Comment by Zanthed** [comment]
You cannot attribute issues caused by updates when we have so frequent updates and our updates are not a random set of changes. We document every single change made.

**Comment by bethhd** [comment]
I rebooted to install and then it started, immediately. Writing me off without doing any due diligence and saying it has nothing to do with the upgrade is straight laziness.

**Comment by thestinger** [comment]
It doesn't have to do with the latest update. We know exactly what changed in the update, and we know that this isn't caused by it. It's not laziness
