### ISSUE TITLE
Alarm Sound List in Pixel 6

### ISSUE THREAD

**Issue by Ryu945** [GrapheneOS/os-issue-tracker#1373]
Device:  Pixel 6
Android: 12
Build Number:  SQ3A.220705.004.2022080900

Problem:

1)  Cesium is listed twice and it is the exact same sound.

2)  Platinum is listed twitce and it is the exact same sound.

3)  Hassium and Helium have the exact same sound.

Thoughts:

1) & 2)  It is just wasting space being double listed and one should be removed.

3)  I suspect one of these sounds never made it into the build.   It got its neighbors sound instead so while the name for the sound is there, the sound itself is just a copy of its neighbor.

**Comment by Zanthed** [comment]
AOSP bug, not worth our time.

**Comment by thestinger** [comment]
We could strip down what's included in the AOSP build system. It's a low priority and doesn't need an issue open because it's just an aesthetic AOSP gripe.

**Comment by PanderMusubi** [comment]
On Android 16, problems 1 and 3 are fixed. Problem 2 I have reported here https://issuetracker.google.com/issues/493304615 Please add a +1 there.

**Comment by PanderMusubi** [comment]
See also https://github.com/GrapheneOS/os-issue-tracker/issues/4664

**Comment by PanderMusubi** [comment]
I think the Google issue got closed a bit too easily. Anybody care to add useful comment to it to get it fixed?
