### ISSUE TITLE
[BUG?] android.permission.INTERNET is reported as granted when it is clearly not

### ISSUE THREAD

**Issue by MuntashirAkon** [GrapheneOS/os-issue-tracker#1375]
**Steps to reproduce the error**
1. Install a sample app with the INTERNET permission where the status of the permission was checked before opening any socket connection (you can find an example here: https://github.com/MuntashirAkon/AppManager/issues/833), e.g.
   ```java
   if (ContextCompat.checkSelfPermission(context, Manifest.permission.INTERNET) != PackageManager.PERMISSION_GRANTED) {
     return;
   }
   // INTERNET is granted.
   // TODO: Open a socket connection.
   ```
2. Revoke its INTERNET permission
3. Run the app

**Expected behaviour**
The framework will return `PERMISSION_DENIED` and the function above will return normally.

**Actual behaviour**
It goes ahead as if INTERNET is granted and throws the following error:
```
java.lang.SecurityException: Neither user 10186 nor current process has android.permission.INTERNET.
...
Caused by: android.os.RemoteException: Remote stack trace:
	at android.app.ContextImpl.enforce(ContextImpl.java:2242)
	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2270)
	at com.android.server.NsdService.getMessenger(NsdService.java:605)
	at android.net.nsd.INsdManager$Stub.onTransact(INsdManager.java:94)
	at android.os.Binder.execTransactInternal(Binder.java:1201)
```

**Comment by thestinger** [comment]
When the Network toggle is disabled, we have compatibility code to tell apps that the permission is still granted to improve compatibility since it cannot be revoked on the stock OS. We've made it so that sockets return IOException rather than SecurityException. We've also done it for other APIs but there are likely still APIs throwing SecurityException. Gradual compatibility improvement is required. Returning that the permission is granted is completely intended though.

**Comment by MuntashirAkon** [comment]
> We've also done it for other APIs but there are likely still APIs throwing SecurityException.

Yes. It was just the case for me. As it was throwing a runtime exception, it was difficult for me at first to figure out what went wrong.

**Comment by muhomorr** [comment]
@MuntashirAkon
Add `<meta-data android:name="android.permission.INTERNET.mode" android:value="runtime" />`
declaration inside <application> element of AndroidManifest.

This is a marker that the app is aware that INTERNET can be a runtime permission, INTERNET self permission checks are not spoofed for such apps.

**Comment by MuntashirAkon** [comment]
Thanks.

**Comment by MuntashirAkon** [comment]
A bit off-topic: Is there any standard way to detect GrapheneOS? I want to hide the rooting options in GrapheneOS to prevent asking stupid questions such as how to root the OS.
