### ISSUE TITLE
 How to disallow Google Play Store to access and update Apps installed manually or by F-Droid?

### ISSUE THREAD

**Issue by SebastianBerlin** [GrapheneOS/os-issue-tracker#1385]
I'm a bit confused. I installed a lot of apps, which are available in the Google Play Store, but at the same time also at others stores like f-droid. Of course in those cases I will always prefer the f-droid-version, which is often NOT similar to the version in the Play Store.

For example I installed the signal-app manually via the official [apk-file](https://signal.org/android/apk/) – and also I've installed a repository in the f-droid-store for [Collabora](https://www.collaboraoffice.com/releases-en/collabora-office-on-mobiles-supporting-password-protected-documents-and-available-on-f-droid/), but both apps will be detected by the Google Play Store and further more Google forces to update those apps with its own Store. That's really odd.

So 1) how to prevent Google to even see or check (!), which app I've installed NOT by the Play Store?

And 2) how to avoid that Google is hijacking the update-process, because – of course – I want to continue with f-droid or other ways with the better versions of some apps.

One tiny temporary, but dirty solution could be to add a new option to the _Storage Scopes_ (which GrapheneOS introduced not long ago) to prevent/disallow access for custom folders (e.g. the app-folder) in the Google Play Store-App.

Or is there a better way? ...yes, except not using the Google Play Store ;)

**Comment by thestinger** [comment]
Please ask questions in our discussion forum:

https://discuss.grapheneos.org/

The issue tracker isn't for questions.

**Comment by thestinger** [comment]
F-Droid wrongly reuses the app ids of the official variants of apps for their own builds. That's an F-Droid repository design flaw and bug which they refuse to fix. The only people hijacking anything are F-Droid.

> One tiny temporary, but dirty solution could be to add a new option to the Storage Scopes (which GrapheneOS introduced not long ago) to prevent/disallow access for custom folders (e.g. the app-folder) in the Google Play Store-App.

Sandboxed Google Play are regular apps with the same app sandbox and permission model. They can't do anything special. They can't access data of other apps on shared storage. Not sure what you mean.

**Comment by thestinger** [comment]
> For example I installed the signal-app manually via the official [apk-file](https://signal.org/android/apk/) – and also I've installed a repository in the f-droid-store for [Collabora](https://www.collaboraoffice.com/releases-en/collabora-office-on-mobiles-supporting-password-protected-documents-and-available-on-f-droid/), but both apps will be detected by the Google Play Store and further more Google forces to update those apps with its own Store. That's really odd.

It does not 'force' anything. It's F-Droid's fault that they wrongly reuse app ids not belonging to them.

**Comment by thestinger** [comment]
> For example I installed the signal-app manually via the official [apk-file](https://signal.org/android/apk/) – and also I've installed a repository in the f-droid-store for [Collabora](https://www.collaboraoffice.com/releases-en/collabora-office-on-mobiles-supporting-password-protected-documents-and-available-on-f-droid/), but both apps will be detected by the Google Play Store and further more Google forces to update those apps with its own Store. That's really odd.

It does not 'force' anything and it's F-Droid's fault that they wrongly reuse app ids not belonging to them for their own builds which essentially claim to own domains not under their control.
