### ISSUE TITLE
Cellular connection is randomly not available Pixel 5

### ISSUE THREAD

**Issue by bhulk** [GrapheneOS/os-issue-tracker#1390]
Sometimes after reboot or just randomly throughout the week, cellular connection completely disappears as on an option and the phone says Sim card not inserted (sim card is in fact inserted). Sometimes it takes 5-6 reboots and now for instance it will not come back on no matter the reboots, going into airplane mode, etc. Resetting the SIM card works sometimes for about 2 minutes then the SIM card magically disappears again.  

Phone: Pixel 5
GrapheneOS: 12(SQ3A.220705.004)

What I expect: Cellular will always work.
What actually happens: Cellular does not always work.

**Comment by bhulk** [comment]
Maybe I should add the problems started after a particular update. I will roll back a few updates and see if that fixes the problem.

**Comment by thestinger** [comment]
It's likely not tied to updates. Try cleaning the SIM card with 99% isopropyl alcohol. It could be something on the contacts for the SIM card or in the phone. It's most likely an issue like a loose connection in the phone.
