### ISSUE TITLE
Create GOS-native mock location service/app

### ISSUE THREAD

**Issue by gordonel** [GrapheneOS/os-issue-tracker#1391]
Android allows to mock location using specialised apps, but unfortunately FOSS apps get regularly abandoned and proprietary apps are undesirable. Having a native GOS app or service that allows mocking location would be a good differentiator for GOS against other privacy-focused custom ROMs. There are a lot of good obvious use cases for that, so I'm not gonna list them at this point, but will do if requried

**Comment by TimoGoetze** [comment]
He wasn't asking for developer options. He was asking for building in in the partial geolocation implementation.

**Comment by r3g-5z** [comment]
Mock location is a developer option and creating a privacy theatre app for mock location is not something the OS should be doing.

**Comment by ruvilonix** [comment]
> Mock location is a developer option and creating a privacy theatre app for mock location is not something the OS should be doing.

I'm curious for why not. Seems like a helpful privacy improvement to the OS. I have an app I need to use that requires location. If I could have Graphene just tell that app that location is on, and give it any constant coordinates, like 0.00, 0.00, that would be helpful.
