### ISSUE TITLE
Unable to prevent Google Play Store from using mobile data for Play Services updates

### ISSUE THREAD

**Issue by felixwiemuth** [GrapheneOS/os-issue-tracker#1393]
In the last months, I repeatedly noticed Google Play Store to use considerable amounts of mobile data without opening the app and with automatic app updates disabled for mobile data. The same happens when data saver mode is enabled. When it happens, a notification can be seen saying "Updating xxx" with a progress bar, where I think xxx is "play services" or similar. It amounts to several hundred megabytes in a very short time (depending on network speed).

Mobile background data is disabled for GSF/Google Play Services, Google Play Store. However, the data usage is listed under foreground data under app info.

Google Play Services used 20-30MB in each of the last four months, Google Play Store nearly a Gigabyte per month (which includes a bit of explicit app updates).

The only solution I found to prevent Google Play Store to use mobile data on its own is to deactivate the app.

There should be an option to disable these automatic updates when on mobile data.

Current versions of the apps (I think the issue showed also recently, within the last days):
- Google Services Framework: 32
- Google Play Services: 222413044
- Google Play Store: 83111410

**Comment by thestinger** [comment]
Configured it in the Play Store itself.

**Comment by thestinger** [comment]
> Google Play Services used 20-30MB in each of the last four months

This is normal and unavoidable if you want to use it.

> Google Play Store nearly a Gigabyte per month (which includes a bit of explicit app updates).
>
> The only solution I found to prevent Google Play Store to use mobile data on its own is to deactivate the app.

Need to do it with configuration in the app. We don't make these apps.

**Comment by felixwiemuth** [comment]
I thought it might have something to do with the compatibility layer; but if it is a pure Google Play Store app issue, then wow, that's quite disappointing.

**Comment by thestinger** [comment]
It has configuration in the app you can use. The reason disabling background data doesn't work is because it's always in the foreground when it's running as part of sandboxed Google Play since the compatibility layer connects to it from a foreground service.

**Comment by thestinger** [comment]
It has configuration in the app you can use. The reason disabling background data doesn't work is because it's almost always in the foreground when it's running as part of sandboxed Google Play since the compatibility layer connects to it from a foreground service.

**Comment by felixwiemuth** [comment]
I'm not sure which configuration you mean, I cannot find anything in the Play Store app which is not just about updating apps.
