### ISSUE TITLE
Display is always 90 Hz on Graphene 13 / Pixel 6

### ISSUE THREAD

**Issue by lbschenkel** [GrapheneOS/os-issue-tracker#1398]
GrapheneOS `TP1A.220624.021.2022082100` on Pixel 6. This is an upgrade from previous GrapheneOS based on Android 12.

Display is always running at 90 Hz according to "show refresh rate" (in developer options), irrespective of settings.

Already tried:
- toggling "smooth display" (in display settings) on and off
- toggling "force peak refresh rate" (in developer options) on and off

Another report: https://discuss.grapheneos.org/d/556-pixel-6-animations-much-smoother-since-todays-alpha-update

**Update 1**: display was stuck in 90 Hz in the very first boot after the upgrade. When rebooting one more time, it went back to 60 Hz.

**Update 2**: display was definitely running at 60 Hz for a while, then I unlocked the phone and it jumped to 90 Hz (both settings above are disabled) and now it is stuck at 90 Hz again.

**Update 3**: upgraded to `TP1A.220624.021.2022082300`, same thing. However, I noticed that refresh rate only gets stuck in 90 Hz when using fingerprint. I believe it is related to the changes in https://github.com/GrapheneOS/platform_frameworks_base/commit/b0511770ee7b77577e44d091fa502ecf80b94ba1.

**Update 4**: `TP1A.220624.021.2022082400` seems to have fixed it.

**Comment by maade69** [comment]
works fine on flame too

**Comment by lbschenkel** [comment]
> does not seem to be reproducible on oriole, newly flashed android 13

That is very strange. Is yours a clean flash? Mine is an upgrade.

**Comment by lbschenkel** [comment]
Update: display was stuck on 90 Hz in the first boot after the upgrade, but when rebooting it reverted back to 60 Hz.

**Comment by lbschenkel** [comment]
New update: after unlocking phone, display jumped to 90 Hz and now it is stuck again.

**Comment by verbumfeit** [comment]
Pixel 6 Pro, graphene 13 here, after reboot display is 60Hz, after turning screen off and on again it is stuck at 120Hz.

**Comment by lbschenkel** [comment]
Update 3: upgraded to `TP1A.220624.021.2022082300`, same thing. However, I noticed that refresh rate only gets stuck in 90 Hz when using fingerprint. I believe it is related to the changes in https://github.com/GrapheneOS/platform_frameworks_base/commit/b0511770ee7b77577e44d091fa502ecf80b94ba1.

**Comment by muhomorr** [comment]
> I believe it is related to the changes in https://github.com/GrapheneOS/platform_frameworks_base/commit/b0511770ee7b77577e44d091fa502ecf80b94ba1.

Why do you think that?

**Comment by lbschenkel** [comment]
Update 4: last update `TP1A.220624.021.2022082400` fixed the problem for me.

**Comment by lbschenkel** [comment]
> > I believe it is related to the changes in [GrapheneOS/platform_frameworks_base@b051177](https://github.com/GrapheneOS/platform_frameworks_base/commit/b0511770ee7b77577e44d091fa502ecf80b94ba1).
> 
> Why do you think that?

Note that I didn't say the commit *causes* the problem, I said it was *related*. If you look at the code, it is dealing with temporarily locking the refresh rate for the sake of the fingerprint reader. The bug manifests as raising the refresh rate when the fingerprint reader kicks in, but the refresh rate doesn't come back down later. So it looks like the bug in the same general area of the code that this commit touches.

I don't think I was very off-base: the recent changes to the framework that fixed the issue all touched this very same `UdfpsHbmProvider`:
- https://github.com/GrapheneOS/platform_frameworks_base/commit/fbdb42f3a05f39f234ee7d3dfe9fdbbb60a3d3de
- https://github.com/GrapheneOS/platform_frameworks_base/commit/d14d992f49afdd7050e970ba590782e64a05e968
- https://github.com/GrapheneOS/platform_frameworks_base/commit/757a328c6b999a663d109f228d725efe25ede392
- https://github.com/GrapheneOS/platform_frameworks_base/commit/0f2f68f4830e94d276c48b77df3e2b31dc707a36
