### ISSUE TITLE
[13] [Pixel 6] WiFi hotspot not working properly

### ISSUE THREAD

**Issue by Wonderfall** [GrapheneOS/os-issue-tracker#1402]
Some users are reporting that WiFi hotspot turns off instantly after toggling it on. Some users aren't affected or probably could not reproduce in the same conditions.

Hotspot works for me after a fresh reboot but doesn't work once I turn on airplane mode at least once. Will probably gather more details later.

**Comment by blackxwater** [comment]
I am having this issue with hotspot after upgrading to GOS 13.

**Comment by Pixel6test** [comment]
Pixel 6, I have the issue after a factory reset, i don't remember if it worked before the factory reset.

I tried airplane mode, data on/off, reboot, factory reset again, wifi on/off, spamming the toggle, changing every wifi hotspot settings... I didn't find any case to make it work.

**Comment by lbdroid** [comment]
For those with root...
```# setenforce 0``` is a workaround until a build with the fix.

**Comment by lbdroid** [comment]
Obviously, but at the same time, nobody should be running experimental builds on a production device either.

**Comment by lbdroid** [comment]
You know, and I know that we will not see eye to eye on this, but the security model is only undermined by root if combined with irresponsibility.
