### ISSUE TITLE
Exempt GmsCompat from appearing in Foreground Services Task Manager (Active apps)

### ISSUE THREAD

**Issue by jorgeluiscarrillo** [GrapheneOS/os-issue-tracker#1407]
This isn't really meant for system-level apps and we already have a notification

**Comment by W1zardK1ng** [comment]
This is something i wish if it was implemented as every time i pull down the notification bar it shows "1 app is active" and its the GmsCompat and doesn't needs to be there.

**Comment by Niko4u5** [comment]
It seams like it is only there when GPlay is running which is not a system app, so I think it should stay.

**Comment by thestinger** [comment]
Not planned since it does this to keep Play services in foreground.
