### ISSUE TITLE
Unable to Connect to VPN Following Android 13 Update (Factory Reset Resolves; Recurs on Subsequent Updates; Multiple Devices)

### ISSUE THREAD

**Issue by broujos** [GrapheneOS/os-issue-tracker#1412]
I because unable to connect to VPN on mobile data after updating from Android 12 to Android 13. This problem was resolved by a factory reset but recurs following subsequent next Android 13 updates.

Some information on what I have tried to help prove this is not a network issue (OP please confirm if you are also on Android 13. If you are not, I can delete my responses and create a new defect so as not to confuse your issue):

Problem with ability to connect to VPN over mobile presented immediately following update to Android 13 on Pixel 6a.
Rebooted and confirmed VPN over mobile did not work but VPN over WiFi did.
Disabled kill switch and confirmed with kill switch off mobile data functioned.
Reset WiFi, Bluetooth, and Network settings, confirmed mobile data, and re-established VPN profile. Unable to connect.
Connected to WiFi and able to connect to VPN.
Rebooted and confirmed VPN over mobile did not work but VPN over WiFi did.
Swapped from eSIM to physical SIM. Loaded SIM in Pixel 6 Pro on Android 12 and confirmed VPN over mobile worked.
Updated Pixel 6 Pro to Android 13 and VPN over mobile stopped.
Rebooted and confirmed VPN over mobile did not work but VPN over WiFi did.
Purchased prepaid SIM on an MVNO that rides a different carrier and confirmed on Pixel 6 Pro and Pixel 6a that VPN over mobile still does not work.
Rebooted and confirmed VPN over mobile did not work but VPN over WiFi did.
Removed and reinstalled VPN application and VPN profile on 6a. Confirmed VPN over mobile did not work but VPN over WiFi did.
Rebooted and confirmed VPN over mobile did not work but VPN over WiFi did.
Factory reset Pixel 6a and reinstalled VPN. VPN over mobile started working.
Installed the next update for Android 13 and VPN over mobile stopped working, but VPN over WiFi still works.
Rebooted and confirmed VPN over mobile did not work but VPN over WiFi did.
Logcat output for both VPNs tested reports a network unreachable error with or without kill switch enabled.

This has persisted for me across 2022082100, 2022082200, 2022082300, and 2022082301. Both Pixel 6a and Pixel 6 Pro list MP1.0 as the hardware version.

**Comment by broujos** [comment]
Update - Disabling "Block Connections Without VPN" and rebooting allows the VPN to connect over mobile (it does not do so without a reboot), but if turned back on the VPN dies (with or without a reboot). Interestingly this seems to not be an issue after a factory reset - the VPN works fine over mobile with the kill switch enabled until the next update is applied.

**Comment by 7ArxS2PrqAUF9Gom** [comment]
Same thing for others - https://github.com/GrapheneOS/os-issue-tracker/issues/1411. I am going to try AdGuard for Android. It uses local VPN to tunnel DNS requests and has very good logging system.

I wish developers could provide instructions on the kind of logs they'd like to have to troubleshoot reported GrapheneOS issues.

**Comment by thestinger** [comment]
This happens on the stock OS and AOSP too:

https://www.reddit.com/r/GooglePixel/comments/wpcy0n/psa_dont_upgrade_to_android_13_if_you_use/

It's not caused by GrapheneOS. We think it's caused by inbound traffic leaks being more thoroughly prevented in Android 13. It's very likely an issue with your carrier's network. Eventually your carrier will likely fix it once a lot of people are on Android 13. The number of people using Android 13 and using a VPN with blocking connections not through the VPN enabled is low, so whatever the cause, that's the reason it hasn't already been fixed as part of the Android 13 betas, etc.
