### ISSUE TITLE
Double-line clock setting does not persist across profile change

### ISSUE THREAD

**Issue by Tonux599** [GrapheneOS/os-issue-tracker#1420]
Build: TP1A.220624.021.A1.2022082400. Device: Pixel 6a

When setting option Display -> Lock screen -> Double-line clock to off. And changing profile and back again. The option will remain off but it is not in effect (double-line clock will be on lock screen).

To re-enable it, toggle must be turned on, then screen locked, unlocked, then turned off again.

**Comment by tyler-reclen** [comment]
I also have this bug

**Comment by tyler-reclen** [comment]
> Can you confirm that this is still reproducible on the latest version of the OS?

On my device this appears to be fixed and works as expected. Thank you graphineOS team : )

Device:
pixel 4a
GraphineOS Android 13
Up to date on stable channel as of 12/12/2023
