### ISSUE TITLE
New Android 13 text copy share menu cant share to app/contact

### ISSUE THREAD

**Issue by kausban** [GrapheneOS/os-issue-tracker#1422]
New Android 13 text copy share menu cant share to app/contact. Signal and element crash when selected in the menu. Copying to clipboard works.

 Build: TP1A.220624.021.A1.2022082400
Phone: pixel 6a

**Comment by thestinger** [comment]
Likely an app bug. Going to close this unless someone can confirm it doesn't occur on stock OS.

**Comment by kausban** [comment]
Update: The function seems to works now on Signal.
Your hypothesis of it being an app bug is likely true.
