### ISSUE TITLE
Using Adaptive Brightness to remember preferred brightness level

### ISSUE THREAD

**Issue by githupper** [GrapheneOS/os-issue-tracker#1426]
E.g. Main Profile is at 80% brightness. When switch to Profile 1, it resets to around 50%. I adjust it to 80% again then go back Main Profile. This time Main Profile is at 50%. If I change to Profile 1, brightness again drops to 50%

Basically once I change profile, it never remembers the previous brightness level and will always reset to around 50%. 

Adaptive Brightness is supposed to remember the user's preferred brightness over time but I had never got this adaptive brightness to work.

It is very jarring to keep redoing the brightness level on each profile change. Is there a workaround for example a user customizable default brightness to fix this?

Thanks

**Comment by thestinger** [comment]
We don't plan to change how this works from AOSP.
