### ISSUE TITLE
Alarms by stock Clock app no longer snoozable/dismissable from lockscreen via overlay when "lockdown" mode is engaged

### ISSUE THREAD

**Issue by ghost** [GrapheneOS/os-issue-tracker#1432]
Device: Pixel 6
Build: TP1A.220624.021.2022082400

### Problem

When setting an alarm through the stock Clock app, when the alarm triggers, the alarm is not snoozable or dismissable from the lock screen when the "lockdown" lock screen is enganged because the blue overlay surface/activity of the Clock app that has these buttons is no longer displayed over the lock screen. While the alarm is ringing, I have to unlock the device with my password to get into the system. After unlocking, I also do not see the blue Clock app activity but the Clock app runs as a notification with 2 buttons snooze/dismiss only, so I suspect the fullscreen snooze/dismiss activity never gets launched in the first place in this scenario.

The behaviour is different when I just lock the screen but keep it unlockable with biometrics -- in this case, the overlay from the Clock app shows properly, allowing the typical snooze/dismiss actions.

This is a behaviour change from Android 12 where the Clock app properly showed its blue activity overlay over the lock screen when an alarm rang, both when unlocking with biometrics and from full lockdown mode. I am unsure if this is intentional or not because from a security POV it is of course desireable to not allow an app to show an activity to the user bypassing lock screen with "maximum lock security" engaged.

### Context / other settings

While the behaviour changed between Android 12 and Android 13, the following configurations were the same before and after upgrading to Android 13:

 * Fingerprint/biometrics unlock enabled
 * Main screen lock method is "password"
 * GrapheneOS is set to not display any notifications or notification contents on the lock screen.

**Comment by thestinger** [comment]
I think this is an intentional change in Android 13 and the Clock app isn't really actively developed so while it perhaps could have done something to work around it with a different design, it didn't. We don't plan to change this.
