### ISSUE TITLE
Data warning and limit settings reset after update to Android 13

### ISSUE THREAD

**Issue by planiitis** [GrapheneOS/os-issue-tracker#1435]
Release: 13 (TP1A.220624.014)

All settings under _Data warning and limit_ were apparently silently reset after the last GrapheneOS update:

- _Mobile data usage cycle_ / _Usage cycle reset date_ was reset to the day of the update (different from my old setting).
- _Data warning_ was reset to 2 GB (higher than my old setting) and the _Set data warning_ toggle was reset to the off position, IIRC
- _Data limit_ was reset to 5 GB (higher than my old setting) and the _Set data limit_ toggle was reset to the off position, IIRC

As a result, the data usage reporting was effectively reset and the data limit was not working (historical usage numbers were still there, and the data usage count was restored to the correct value once the _Usage cycle reset date_ was corrected). Losing control of data usage in this way is especially bad when relying on it to avoid the wild charges that some providers impose for excess data usage.

**Comment by thestinger** [comment]
That's unfortunately but it's too late for us to do something about this now.
