### ISSUE TITLE
Enable video output over USB C

### ISSUE THREAD

**Issue by Maio-msdos** [GrapheneOS/os-issue-tracker#1442]
If possible please enable video output over USB C, from prior conversations with devs iirc I believe the hardware supports it but it is software disabled in the kernel :) thankyou

**Comment by thestinger** [comment]
Contributions are welcome. We aren't going to have this on our roadmap. If someone wants it they need to work on it.

**Comment by r3g-5z** [comment]
> I believe the hardware supports it but it is software disabled in the kernel 

there is no evidence that supports that. a random option in the kernel that has zero other context beyond the name of the function is not evidence that it's "disabled in the software".
