### ISSUE TITLE
All notifications disappear after re-unlocking phone

### ISSUE THREAD

**Issue by thevigilante0** [GrapheneOS/os-issue-tracker#1444]
**Device**: 6P
**Description**: I notice all of my notifications will disappear from the notification tray after I lock down my phone and re-unlock it. After that, all push notifications will not pop up even though the notification sounds still ring. 

I can only see my notifications in full when I restart my phone/profile. After locking and unlocking, the issue will happen

**Step to reproduce:**
Start/Restart your profile
Have a bunch of notifications popping up and not dismiss them
Lock-down
Unlock it
All notifications received earlier will be gone

**Comment by PatrykMis** [comment]
I have opposite issue: I get notifications in secondary profiles but I can see them only after locking and unlocking the device. Only on A13.

**Comment by thestinger** [comment]
@PatrykMis Seems unrelated.

**Comment by thestinger** [comment]
@thevigilante0 This is a side effect of an upstream security fix. We'll likely leave it to them to fix this since they broke it and it's not at all GrapheneOS specific and impacts stock OS.
