### ISSUE TITLE
DNS-Over-HTTPS Support Timeline

### ISSUE THREAD

**Issue by p0da** [GrapheneOS/os-issue-tracker#1445]
Apologies for the issue as I am sure that this has been asked before (can't seem to find an issue on this tracker though), but as Android 13 seems to finally be adding DOH support is there any intention to also integrate DOH into GrapheneOS? And if so, is there any sort of timeline where it will become available or anywhere to track development progress of it?

**Comment by thestinger** [comment]
It's available in GrapheneOS. The current AOSP / stock OS implementation has an allowlist of providers which we plan on extending.

**Comment by p0da** [comment]
Great! Parts of the documentation that I was reading seemed to indicate that only DOT was supported. Additionally, would you consider allowing users to specify their own custom DOH providers as I run a private, very small, DOH resolver and ran up against the aforementioned restrictive allowlist in stock Android which prevented me from adding my own resolver.

**Comment by hmenke** [comment]
@p0da Only Google and Cloudflare resolvers are supported right now for DoH:
https://cs.android.com/android/platform/superproject/+/master:packages/modules/DnsResolver/PrivateDnsConfiguration.h?q=mAvailableDoHProviders&ss=android
By default the “Private DNS” will try DoT on the supplied hostname unless it is one from the list of `mAvailableDoHProviders` in which case it is substituted by the listed DoH endpoint.

It would be really great if GrapheneOS would allow a user-defined resolver.

@thestinger Could you please reopen this issue until this is implemented (or rejected)?

**Comment by thestinger** [comment]
No.

**Comment by thestinger** [comment]
The list of DoH providers can be extended instead. It's not a valid issue report to file though. If you want it extended, help with doing it.
