### ISSUE TITLE
OS doesn't list installed certificates

### ISSUE THREAD

**Issue by rynkowsg** [GrapheneOS/os-issue-tracker#1449]
I added a Charles Proxy certificate to by adding CA certificate (Settings -> security -> encryption and credentials -> install a certificate -> CA certificate) and I noticed that list of installed certificates show nothing (encryption and credentials  -> trusted credentials -> User). Same, there is list of System certs is empty.

Usually, System certs are possible to disable. Here GrapheneOS do not even list them.

Device: Pixel 6
Build Number: TP1A.220624.021.2022083000

**Comment by thestinger** [comment]
It's being rejected as invalid. Same as AOSP / stock OS.

**Comment by rynkowsg** [comment]
@thestinger no no, wait, how about all the other certificates that are preinstalled on the system? They are valid.

They should be listed. I'm not sure how that worked on previous GrapheneOS versions, but some other stock roms allow disabling pre-installed certificates. Here the OS doesn't list even one.

**Comment by r3g-5z** [comment]
Unable to reproduce, can see System certificates, likely fixed upstream in QPR1 or such.
