### ISSUE TITLE
Autofill service not working in some (not all) apps since update to Android 13

### ISSUE THREAD

**Issue by betweenwater** [GrapheneOS/os-issue-tracker#1450]
Hello,

I use keepass2android as my password manager and have it selected as my autofill service. Since the recent update to Android 13 however the autofill service stopped working in some, but not all, apps. For example in the Aegis authenticator app and the Starling bank app, trying to use autofill leads to a "contents can't be auto-filled" message. Strangely it still does work in the NHS app.

I tried rebooting after deselecting the autofill service, tried switching to Google as the autofill service (which leads to the same issue for the same apps) and do not know what else to try. Is this a bug related to the autofill service in general or are some apps not following some new specification for autofill in Android 13?

Device: pixel 4a 5G

**Comment by thestinger** [comment]
It's the same as the stock OS. Search for the error and you can see that. Probably an app issue.

**Comment by betweenwater** [comment]
I couldn't find specific reports for Android 13 and these apps (Aegis and Starling) were successfully using autofill service on Andrpid 12, should have made that more clear.
