### ISSUE TITLE
Sensors cease to work (Pixel 6 Pro)

### ISSUE THREAD

**Issue by andre4ik3** [GrapheneOS/os-issue-tracker#1457]
Not sure if this is hardware failure (although it seems VERY unlikely, never had this happen before) or software bugs, but all of the sensors in my Pixel 6 Pro refuse to work now. I ran some tests with the sensor test app:

- Accelerometer reports "no data from sensor (type 1 unsupported)"
- Light reports "type 5 unsupported"
- Proximity reports "type 8 unsupported"
- Magnetometer actually appears to be "working", but all the values are stuck at 0. "No data from sensor"
- Compass permanently points north ()
- Gyroscope reports "type 4 unsupported"
- Barometer reports "type 6 unsupported"

This pretty much means that Auto-Rotate doesn't work unless the app is forced into the desired orientation. This is especially problematic for e.g. camera shooting as my photos are permanently stuck in landscape. (could have been worse if they were stuck in portrait!)

**Comment by thestinger** [comment]
Either a configuration issue or hardware failure. Not a GrapheneOS issue.

**Comment by andre4ik3** [comment]
Alright, thanks for the info. I'll probably have to get a replacement phone then.
