### ISSUE TITLE
geolocation implementation breaks developer options/mock location 

### ISSUE THREAD

**Issue by TimoGoetze** [GrapheneOS/os-issue-tracker#1459]

**Comment by r3g-5z** [comment]
It's an app bug with it being very old:

https://stackoverflow.com/questions/68398557/android-10-java-lang-securityexception-not-allowed-to-delete-channel-mynotifica

**Comment by TimoGoetze** [comment]
It worked perfectly with pixel6 and stock android 12 before flashing grapheneos. So it seems to be an OS issue or at least a consequential error. But Ill have a look at this apps source as its oss.

**Comment by r3g-5z** [comment]
It's not an OS issue. It's Android 13 removing legacy and deprecated APIs.

**Comment by schklom** [comment]
FYI, a similar issue got fixed at https://github.com/warren-bank/Android-Mock-Location/issues/14 for my Pixel 6a with GrapheneOS.
The code workaround is dumb, but it works for me.
Maybe it works for you too @TimoGoetze?
