### ISSUE TITLE
[suggestion] Add option for high priority

### ISSUE THREAD

**Issue by PatrykMis** [GrapheneOS/os-issue-tracker#1460]
"Finalizing system update" stage takes long time. I would prefer to choose if it will be in background or takes more resources and finish it earlier.

**Comment by r3g-5z** [comment]
Need a fork of platform_system_update_engine.

Commit that solves this: https://github.com/r3g-5z/platform_system_update_engine/commit/23265c7f56a8fbf3a58df022a5609d19e9d22dba

Explanation:

so google decided to move it to the background cgroup with https://github.com/r3g-5z/platform_system_update_engine/commit/13bdba8cdca020c6731907b37b17c623091ba0e5
using the original write_pid method in update_engine.rc

they then did the same thing but with the new modern task profiles API in https://github.com/r3g-5z/platform_system_update_engine/commit/0a813e6aaca347385d726833a7712d20b2713dec

and then they made a profile for those 3 task profiles flags `OtaProfiles` which is a noop to the above^
https://github.com/r3g-5z/platform_system_update_engine/commit/ea7706471c8129b8450a04b838c7c3d205ea7587

then LineageOS added a performance toggle which is simply adding those 3 task profiles with a user-facing toggle https://github.com/LineageOS/android_system_update_engine/commit/4c376814ce62b90afb4b31c729a4fe6a52091368

which just moves it back to the foreground cgroup again. all i did was just add those profiles to update_engine.rc without the toggle mess and using the modern task groups API. effectively reverting what google did

**Comment by thestinger** [comment]
I do think we want what Google did by default.

**Comment by r3g-5z** [comment]
Doesn't seem like we're interested in changing how this is done, and Google might optimise this themselves later on.
