### ISSUE TITLE
Transparency issue with app drawer when animations disabled

### ISSUE THREAD

**Issue by ein-bandit** [GrapheneOS/os-issue-tracker#1463]
Hello, I encountered a minor bug, where the transparency is not reset when leaving the app drawer.
This only happens with animations disabled: [app_drawer-transparency_bug.png](https://i.postimg.cc/Gpyk8hwb/app-drawer-transparency-bug.png)

Steps to reproduce:
- disable animations (as in image above)
- open app drawer
- scroll to very bottom
- use home gesture to close drawer
- reopen app drawer -> app drawer has about 30% transparency active

Video for bug [webp](https://i.postimg.cc/QxjGfH0n/screen-20220907-170113.webp) (click on image to zoom in to start video)

This does `not happen when animations are enabled`, since "navigate back to home" has a "transparency reset" effect itself.

Hint: Image and Video will be deleted in 31 days.

device: pixel 4a
graphene os version: stable, TP1A.220624.014.2022090400

**Comment by inferenceus** [comment]
Unsure if related, but opening the notification shade with animations disabled also produces a very visible transparency effect around the notification list around 50% of the time on Pixel 6.

**Comment by r3g-5z** [comment]
It's known that disabling animations is still fairly experimental and causes most UI glitches and issues. Not a GrapheneOS bug. The same thing would happen on stock OS.

**Comment by thestinger** [comment]
No plnas to work on these upstream issues with animations disabled. Has to be fixed in AOSP.
