### ISSUE TITLE
Odd lock screen indicator alignments

### ISSUE THREAD

**Issue by cjseaslug** [GrapheneOS/os-issue-tracker#1465]
![Screenshot_20220907-205554](https://user-images.githubusercontent.com/83566426/189010325-a0123799-2876-4674-96f5-6026c56bd850.png)

OS version 13 (TP1A.220624.014), Stable Channel, Pixel 5

Expected alignment for the status icons: 
`Sun,_Sep._7_⏰8:20_⛔`

Actual alignment:
`Sun,_Sep._7⏰__8:20⛔__`

Not sure if this is an upstream problem.

Ideally (i dont know the backend here or whether this is desirable to others) i'd put the DND icon first as such:

`Sun,_Sep._7_⛔⏰8:20`

Thanks for your time! :)

**Comment by thestinger** [comment]
No plans to change these parts of the AOSP UI.

**Comment by cjseaslug** [comment]
Thanks for the input :) Just FYI that I filed as a bug report for this on AOSP issue tracker, as previous talks there indicate this was intended to be fixed in jan/feb (and then left out, after momentarily appearing in an Android 12 beta).

https://issuetracker.google.com/issues/214364307#comment3
