### ISSUE TITLE
Fido2 token access

### ISSUE THREAD

**Issue by jmue** [GrapheneOS/os-issue-tracker#1471]
Whenever I try to log in to a website that requires 2FA via a fido2 token using Vanadium or Firefox, I get an error message about a missing storage permission on Google Play services. As far as I can see, there is no storage permission available for Google Play services. Even when I allow photos and videos permission, I get this error message.

![blur1662886985825](https://user-images.githubusercontent.com/898577/189520588-94d055ac-7329-4f5d-9555-f0cf5217309d.jpg)

![Screenshot_20220911-110238](https://user-images.githubusercontent.com/898577/189520606-acb3ae87-1edd-4375-a065-4840cd33af2b.png)

**Comment by r3g-5z** [comment]
have you tried just giving it storage scopes?

**Comment by jmue** [comment]
Hey, yeah, that worked. I was able to log in now.
