### ISSUE TITLE
Frequent UI Crashes and Kicking Back to GrapheneOS Boot Logo

### ISSUE THREAD

**Issue by inferenceus** [GrapheneOS/os-issue-tracker#1472]
Pixel 6 seems to have a very frequent crashing issue with what seems to be SystemUI or related. When opening an arbitrary app in an array of secondary user profiles (even 1 app in 1 secondary user profile), I am often kicked back to the GrapheneOS boot logo, which then leads me to the admin user profile lockscreen, despite using a different user profile before the crash. When this occurs, the secondary profile sessions are not ended, and the admin user profile does not return to before-first-unlock, allowing me to immediately switch back to the secondary profile(s) I was using when the crash occured.

**Comment by thestinger** [comment]
Need logs showing the crashes (uncaught exceptions probably) in order for this to be a valid issue.
