### ISSUE TITLE
upstream Android 13 compatibility issue between VPN lockdown and 464XLAT (CLAT) setup breaking mobile data setup on some carriers

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/os-issue-tracker#1477]
This issue exists to track the upstream problem and work on resolving it downstream.

You can work around the problem by using an IPv4 APN with your carrier. You can temporarily disable VPN lockdown and toggle airplane mode on/off to reinitialize mobile data to temporarily work around it if that doesn't work for you.

Currently, we're not able to replicate this and it has proven to be unproductive attempting to blindly fix it without the ability to test quick development builds or dynamically debug it. We're not currently looking for help testing anything. We need help from developers only.

**Comment by 7ArxS2PrqAUF9Gom** [comment]
Not fixed in the latest October 2022 update. Does Google provide an official portal where non-developers can submit bug reports? How do we know Google is even aware of the issue? Is there some kind of a response Google provided about awareness of this problem?

**Comment by 7ArxS2PrqAUF9Gom** [comment]
Perhaps GrapheneOS can integrate a boot-up script and/or interface button that automatically performs necessary workaround actions (enabling airplane plane, disabling VPN lockdown, disabling airplane mode, re-connecting to VPN, re-enabling VPN lockdown)?

**Comment by thestinger** [comment]
@7ArxS2PrqAUF9Gom No, that's not happening... we're not creating a hole in VPN lockdown.

**Comment by Ry0OBSSc9H8VjeVE** [comment]
A bit off-topic, but why is VPN Lockdown necessary if "Always-on VPN" is enabled? VPN Lockdown is only needed to prevent any traffic from leaking in case VPN gets disconnected. If VPN continues to be connected, all traffic should be tunneled through VPN, even if VPN Lockdown is disabled. Such isn't the case for mobile and for WiFi on Android... If VPN Lockdown is not enforced, some apps try to resolve domains outside of VPN tunnel, even when phone stays connected to VPN.

**Comment by thestinger** [comment]
> If VPN Lockdown is not enforced, some apps try to resolve domains outside of VPN tunnel, even when phone stays connected to VPN

No, that's not how it works.

**Comment by Ry0OBSSc9H8VjeVE** [comment]
The latest October 28, 2022 update fixed this issue for me. HUGE thank you for that! I can use my phone with ease once again!

I hope the backported CLAT fixes didn't relax VPN Lockdown feature and didn't degrade security. It would be nice to know some more details about the backported CLAT fixes. Commit links should suffice.

**Comment by thestinger** [comment]
@Ry0OBSSc9H8VjeVE https://github.com/GrapheneOS/platform_packages_modules_Connectivity/commits/13

It's all there. We tried backports earlier and it didn't fully work so we needed more.
