### ISSUE TITLE
Apps have automatically access to the Google account

### ISSUE THREAD

**Issue by stephane-21** [GrapheneOS/os-issue-tracker#1478]
**Problem :**
For example, if I install "Google Maps" from "Google Play", "Google Maps" will be automatically logged in with my Google account.

**Observation :**
I believe "Google Maps" is not mandatory tied to a Google account, into the settings of the app, there is even an option to logout, and the app is still usable without being logged in.

**Idea :**
Would it be a good tradeoff that apps requests the access to my Google account at first launch ?
(like it is currently the case with the popup to get permission to get my location)

**Comment by thestinger** [comment]
You can use separate profiles for separate accounts. Apps within profiles can communicate with mutual consent.

**Comment by thestinger** [comment]
Google account / other app accounts / other app APIs provided to each other are not OS features. Cutting off Google Maps from talking to Play services and using that account implementation can be done via profiles. Google Maps even works without Play services too.
