### ISSUE TITLE
Settings: automatically disable hardened_malloc when 39-bit address mode is enabled

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/os-issue-tracker#1479]
Increasing class region size to 32GB has broken hardened_malloc with 39-bit address space. I expect it to be broken for good going forward. The address space may get smaller to accommodate larger PAC tags but 39-bit is way too small.

**Comment by muhomorr** [comment]
Addressed by https://github.com/GrapheneOS/platform_packages_apps_Settings/pull/187 in a different way:
39-bit VA mode is now not allowed to be enabled when hardened_malloc is enabled
