### ISSUE TITLE
TalkBack Screen Reader Two-Volume Button Shortcut Not working

### ISSUE THREAD

**Issue by CarlosM10011** [GrapheneOS/os-issue-tracker#1481]
Hi all!

I just installed and configured Graphene OS on an old Pixel 3a XL to play around with it. So far, I'm really liking the OS.

I use the TalkBack screen reader to use the phone. Everything appears to work well. I loaded a TTS engine and was able to configure it in Settings, but I can't figure out how to make the two-volume shortcut work to toggle the screen reader off or on. Toggling the box in the TalkBack settings page under Accessibility does not change anything.

Are the volume buttons controlled by a specific permission that is not enabled by default? I also have access to a setup with ADB and have USB debugging enabled.

Let me know if I should provide any info such as logs and also am happy to help with debugging.

- Carlos

**Comment by thestinger** [comment]
cc @PatrykMis

**Comment by PatrykMis** [comment]
Everything works fine like on StockOS. To enable 2-volume shortccut:

1. Settings -> accessibility -> TalkBack under Screen Readers.
2. Tap "TalkBack. Shortcut. off" (the text, not the switch).

	The warning message will display, click Allow.

3. Tap something like "Hold Volume Buttons" and don't forget to also tap Save button.

Note that for the first time you should press volume buttons for a longer time (even up to 15s). If you are visually impaired too, I suggest first use of this shortcut (after enabling it in the settings) while TalkBack is already running - the worst thing you can do is disabling TalkBack, but after repeating it will turn on again.

**Comment by CarlosM10011** [comment]
I see. Thank you. Holding it longer did the trick.

Even though this is likely the same behavior for stock Android, maybe consider adding a note in the usage guide under (https://grapheneos.org/usage#accessibility) reminding people that you have to hold the volume buttons for ~15 seconds when you do it for the first time. It's easy to get used to just waiting for three seconds for it to toggle, and forgetting that it took longer when first setting it up.

It doesn't have to be anything big; something like:

```
If you wish to enable and use the TalkBack accessibility shortcut (pressing the two volume buttons), remember that it may take longer than normal for it to trigger when doing it for the first time. Expect to hold the volume buttons for around 15 seconds initially. The shortcut should have the normal three-second delay after confirming.
```
