### ISSUE TITLE
Sim Pin window is interrupting the input of the device password

### ISSUE THREAD

**Issue by robovoice1** [GrapheneOS/os-issue-tracker#1482]
To reproduce:
- Enable screenlock (password) please choose a long password
- Insert a physical sim card
- Activate sim lock
- Reboot the pixel
- After booting, in the lock screen, swipe up immediately
- Start entering the password
- In the middle of entering the password, the sim pin screen kicks in (appears to be a timed event)
- enter the sim pin
- start again (from scratch) to enter the password to unlock the pixel

Entering the sim pin before or after completing the input of the password would give a smoother user experience.

Right now the "workaround" is simply to wait for the sim pin window, enter the pin, and then enter the password without interruption.

Pixel 6 pro
TP1A.220905.004.A1.2022091300

**Comment by thestinger** [comment]
Not an issue caused by GrapheneOS.
