### ISSUE TITLE
UX: one-press on/off for wifi

### ISSUE THREAD

**Issue by mfc** [GrapheneOS/os-issue-tracker#1485]
currently wifi is the only functionality that requires two-presses to enable and disable via quick tiles. bluetooth, nfc, etc all only require one press. with airplane mode one can disable/enable cell connection with one-press.

it is a UX regression introduced in Android 12, and it bothers me every day :)

--
maybe related issue, tho not explicit whether such quick tiles would be one- or two-presses: https://github.com/GrapheneOS/os-issue-tracker/issues/1055

**Comment by mfc** [comment]
ok thanks for the quick reply

**Comment by elebow** [comment]
People may be interested in <https://github.com/rostopira/wifi_qs>. This solves the problem for me on current (Android 13 based) GrapheneOS.
