### ISSUE TITLE
Fake system background colors an app can get

### ISSUE THREAD

**Issue by MatsG23** [GrapheneOS/os-issue-tracker#1491]
Material You introduced a theme based on your wallpaper and a color picker (which was recently added to GOS).
This app shows the wallpaper theme colors any app can see: [WallpaperID](https://play.google.com/store/apps/details?id=com.fingerprintjs.android.wallpaperid&hl=gsw&gl=US). This can be used to fingerprint users.

This is why I am asking:
Is it possible to fake the theme colors (return #000000 for every color) when I have selected a unrelated color in the color picker?

**Comment by thestinger** [comment]
The colors are accessible so that the theme can be applied by apps. That's the point of the feature. Setting it to black for every color would completely break apps using the system provided color scheme. It sounds like you want to disable the feature.
