### ISSUE TITLE
"Sensors Off" quick-tile resets after reboot

### ISSUE THREAD

**Issue by 7ArxS2PrqAUF9Gom** [GrapheneOS/os-issue-tracker#1492]
"Sensors Off" quick-tile needs to be enabled after each reboot on the latest GOS.

**Comment by 7ArxS2PrqAUF9Gom** [comment]
Its a hell of a lot more convinient to disablle all sensors with just one quick tile in times when you want extra privacy. Use of developer mode isn't nearly as dangerous as use of ADB, unlocking bootloader, and rooting. Some features in developer mode are very useful (like the "Sensors Off" Quicktile).

**Comment by thestinger** [comment]
This feature is a developer option and the design doesn't make sense anymore. There should be a dedicated user-facing global toggle for Sensors similar to Camera and Microphone. This one covers Camera and Microphone without the UI being aware of it like the proper Android 12 global toggles for those, which is beyond the scope of a proper Sensors toggle.
