### ISSUE TITLE
Switching users makes apps be blurry while switching to recents menu

### ISSUE THREAD

**Issue by catdevnull** [GrapheneOS/os-issue-tracker#1493]
A video is worth more than a million words:

https://user-images.githubusercontent.com/86896666/190880400-1b4553bb-5829-422d-b89f-2b2d4b6e2222.mp4

Expected behavior:

https://user-images.githubusercontent.com/86896666/190880387-36f02e4a-0bdd-4beb-8cb6-7f329c5306fc.mp4

**Comment by thestinger** [comment]
AOSP issue and not going to be fixed early by GrapheneOS.

**Comment by catdevnull** [comment]
I can't reproduce in a Pixel 5a 5G running stock and I (and others in Matrix) have noticed it since at least Android 12.

**Comment by thestinger** [comment]
Stock OS uses Pixel Launcher not AOSP Launcher, and an extended SystemUI. We can't track every AOSP animation issue here. It impacts other devices too.
