### ISSUE TITLE
Bluetooth calls in secondary profiles do not work on apps other than default phone app.

### ISSUE THREAD

**Issue by AuthenticPumpkin** [GrapheneOS/os-issue-tracker#1496]
Bug report: Bluetooth Calls in apps like Signal, in Secondary Profiles, broke for me with the 2022091300 and 2022091400 updates.

The same hadn't been working all year with Android 12, it got fixed with Android 13 (yay!) And now broke again since the above named updates.

Surprisingly, Bluetooth calls work perfectly in the default phone app even in secondary profiles.

Is anyone else able to replicate the issue?

--

My devices:
Pixel 4a
Galaxy Buds+
Latest GrapheneOS: 2022091400

**Comment by thestinger** [comment]
AOSP issue and not going to be fixed early by GrapheneOS.
