### ISSUE TITLE
[Bug] Random Freezing When Switching Apps

### ISSUE THREAD

**Issue by seniorm0ment** [GrapheneOS/os-issue-tracker#1497]
I am noticing when in an application, and I slide up to open the task view menu (where it shows all open applications and you slide between to pick one), often but not always, if I enter into an app it will be frozen. I cannot interact with it. I have to swipe up again, and close it, and then reopen it and it works. 
This isn't a sudden issue, it's something I've noticed for months.

Android 13, Latest Graphene OS, Pixel 6 Pro

**Comment by thestinger** [comment]
AOSP issue and not going to be fixed early by GrapheneOS.
