### ISSUE TITLE
[Bug] Lockscreen Pin Menu Sometimes Fails To Open

### ISSUE THREAD

**Issue by seniorm0ment** [GrapheneOS/os-issue-tracker#1498]
An issue I've noticed is, on occasion when swiping up on the lockscreen (or even holding down on the lock button) for it to open the lock pin menu, it will instantly close and I try a few more times and it keeps doing it and eventually it will work.
It's ACTING like I'm taking my finger off the screen before it fully swipes to complete the animation to open it up. 
This is not a sudden issue, I've noticed it for months. It happens on occasion. 

Android 13, Latest GrapheneOS, Pixel 6 Pro

**Comment by thestinger** [comment]
AOSP issue, not going to be changed by GrapheneOS.
