### ISSUE TITLE
Bluetooth timout not working since 2022090600

### ISSUE THREAD

**Issue by heuwerk** [GrapheneOS/os-issue-tracker#1500]
Hello dear developers,
I have the problem since the update 2022090600 that the bluetooth timeout function does not work anymore.
I have set it to two minutes, but even if no device is connected, Bluetooth does not turn off automatically on my device.
This could be an duplicate of #528 but I am not sure.
If you need any more Information I will be happy to provide it.

Device: Google Pixel 5
Graphene OS Version: Android 13 - 2022091400

**Comment by thestinger** [comment]
Unable to replicate.

**Comment by heuwerk** [comment]
Sorry @thestinger , I was able to track down the error on my end.
I use the Gadgetbridge app which automatically connects to my Smart Band when I enable Bluetooth.
Therefore, devices were still connected to the smartphone after all, although not visible in the connection list and Bluetooth remained on.
