### ISSUE TITLE
Camera From Lockscreen Power Button Not Working

### ISSUE THREAD

**Issue by seniorm0ment** [GrapheneOS/os-issue-tracker#1501]
The setting to allow camera from lock screen without requiring pin when double tapping the power button does not seem to work. 
It asks for the pin.

The only camera app installed is the stock one, unless Snapchat counts.

Pixel 6 Pro, Latest Graphene OS, Android 13

**Comment by thestinger** [comment]
It works fine. If you have multiple cameras there is a known AOSP issue. Not a GrapheneOS issue and won't be tracked here.

**Comment by seniorm0ment** [comment]
what is the proper link for the aosp tracker?

**Comment by landry314** [comment]
oh having two cameras causes a pin lock to come up... this would have become more clear if you didnt just delete my last issue and let some discussion happen.
