### ISSUE TITLE
Problem with auto-restart

### ISSUE THREAD

**Issue by pawelsu8** [GrapheneOS/os-issue-tracker#1508]
The problem has been around for a week.
I am set to automatically restart my phone after 20 minutes.
Recently, I noticed that when I make calls and the screen goes blank, after another 20 minutes the phone restarts despite an ongoing phone call. This is pain

**Comment by idk-r-n** [comment]
The two lowest times I see available are 10 and 30 minutes. How did you set it to 20 minutes?

**Comment by thestinger** [comment]
Intended. Unlock before the timer.

**Comment by pawelsu8** [comment]
Yes, I was wrong - I have a set time of 30 minutes. What's the solution to the problem?

**Comment by thestinger** [comment]
Wait for the improved feature.
