### ISSUE TITLE
Problem with update and auto-restart

### ISSUE THREAD

**Issue by pawelsu8** [GrapheneOS/os-issue-tracker#1509]
Recently, I've noticed that my phone is displaying a phone update message from time to time, and it's still running on an outdated software version. I looked into it and it appears that I have auto-restart enabled after 20 minutes of screen lock and when the Graphene update is downloaded and then the update verification and the whole process takes more than 20 minutes, the phone reboots and the update process starts again. Could you extend the life of one cycle to, say, 40 minutes at a time during the ongoing update process?

**Comment by thestinger** [comment]
No, this is working as intended. There's an existing enhancement filed about not rebooting repeatedly and updates can be done before first unlock.
