### ISSUE TITLE
Pixel 6 Losing All notifications and significant UI problems

### ISSUE THREAD

**Issue by NovaSm0k3** [GrapheneOS/os-issue-tracker#1510]
So yesterday or the day prior I updated to the current build of Graphene on my Google Pixel 6. Since then, I've had strange problems of losing all notifications whether new and incoming, or access to previous notifications (almost like DND is turned on). After a restart, this issue goes away for a period but will come back after 4-5 hours. I have been unable to replicate the steps prior to this happening, or able to detect a pattern.

The second issue is the OS feels like it is lagging in general. The UI also feels like it is having issues. Last night and right now I'm having issues inputting data through the clipboard or other navigation and keyboards. Anytime I click somewhere to input data, I have to swipe back like I'm trying to head back to the previous screen, and then the options show up. 

I will attach a screen capture to illustrate this in addition to the bug report. I am currently not having issues with notifications, and don't have a bug report during that issue as of yet.

>

**Comment by NovaSm0k3** [comment]
https://mega.nz/file/nklHzAyL#V42MqTHgKqGvRz3EcY4KnltqPLPS3SVbLdTUvsNOv8Y

**Comment by NovaSm0k3** [comment]
https://mega.nz/file/nklHzAyL#V42MqTHgKqGvRz3EcY4KnltqPLPS3SVbLdTUvsNOv8Y
Screen Recording of UI issues

**Comment by NovaSm0k3** [comment]
https://mega.nz/file/mo0nlJKI#xRzvFgbnXkE3t60NcbZTezGXXR0xPFQL5Y8v3nKXQck
Screen Recording of UI Issues

**Comment by thestinger** [comment]
You're using Alpha/Beta. You need to wait for the next release.

**Comment by muhomorr** [comment]
@NovaSm0k3 Have you tried restarting the device?

**Comment by NovaSm0k3** [comment]
> You're using Alpha/Beta. You need to wait for the next release.

![IMG_20220924_094712.jpg](https://user-images.githubusercontent.com/114265155/192101453-6dba86ac-7422-4c05-a0b8-8a6215e57861.jpg)

Nope, I'm using only stable releases.

**Comment by NovaSm0k3** [comment]
> @NovaSm0k3 Have you tried restarting the device?

Yes, at least three to four times each day or the device gets more difficult to use. It perfoms the best during the first hour after a restart.

**Comment by NovaSm0k3** [comment]
> You're using Alpha/Beta. You need to wait for the next release.

Is there a reason you closed this? I'm now getting constant issues with the UI crashing![Screenshot_20220924-123752.png](https://user-images.githubusercontent.com/114265155/192109278-9ad87e38-34b0-429a-978a-5a312ee306d2.png)

**Comment by NovaSm0k3** [comment]
I finally was able to get some bug reports while the Pixel 6 wouldn't display new or old notifications. But, I'm not sure if I should share them here since the problem is 'closed'?

**Comment by thestinger** [comment]
Please update to the latest release now that it's in Stable.

**Comment by NovaSm0k3** [comment]
> Please update to the latest release now that it's in Stable.

I'll try that, thank you!
