### ISSUE TITLE
Color Correction & Color Inversion cannot be turned off

### ISSUE THREAD

**Issue by cswitenky** [GrapheneOS/os-issue-tracker#1516]
Once you turn either setting to 'on', changing them back to 'off' has no effect. The color is stuck until you reboot the device.

Settings > Accessibility > Color and motion > Color correction
Settings > Accessibility > Color and motion > Color inversion

I'm experiencing this issue on a Pixel 6a on TP1A.220905.004.A2.2022092300 build.

**Comment by smdyv** [comment]
Duplicate. See #1437

**Comment by davidakerr** [comment]
I have the same issue, except rebooting with it enabled or rebooting with it disabled has no effect. My phone is permanently greyscale now :(

**Comment by louipc** [comment]
https://github.com/GrapheneOS/os-issue-tracker/issues/1437

**Comment by thestinger** [comment]
They can be turned off. There's an Android bug requiring a reboot after changing them. Android 14 will likely fix it in a week or two when we ship it.
