### ISSUE TITLE
How to reinstall the android factory image in my phone with Graphene os 

### ISSUE THREAD

**Issue by MichMourra** [GrapheneOS/os-issue-tracker#1518]
Hi, a few months ago I installed Graphene OS in my Google Pixel 3XL device but recently It started to have a lot of bugs. For example, the rear camera are disable and the phone disconnects from the Wifi for a long period of time. So I decided to uninstall Graphene OS and reinstall the original Android OS, but I don't know how to do it. I was wondering if you could explain 
 me how to achieve this process?

Thank you for your time!

**Comment by empratyush** [comment]
[check it out](https://grapheneos.org/install/web#replacing-grapheneos-with-the-stock-os)
