### ISSUE TITLE
Allow forwarding of work profile notifications

### ISSUE THREAD

**Issue by ph00lt0** [GrapheneOS/os-issue-tracker#1519]
In addition to forwarding notifications from the current user, it would be great if also the work profile notifications can be forwarded to other users.

**Comment by thestinger** [comment]
This isn't planned since we don't see the work profile feature as having much of a place in GrapheneOS over the long term. It's not meant for how people are using it. We're focused on user profiles.

**Comment by Pythoner6** [comment]
> This isn't planned since we don't see the work profile feature as having much of a place in GrapheneOS over the long term. It's not meant for how people are using it. We're focused on user profiles.

I'm very much in agreement here with ph00lt0. Are there plans to make user profiles much more convenient then? Without huge improvements there I simply cannot see myself using user profiles. E.g. with user profiles I cannot be in a discord call on one profile and switch to another profile while continuing the call, plus the process of switching takes way longer.
