### ISSUE TITLE
Option to remove navigation bar

### ISSUE THREAD

**Issue by lvlgl** [GrapheneOS/os-issue-tracker#1521]
I'm talking about this white line at the bottom of the screen. I insist on reviewing your decision on making the navigation bar not removable with a toggle at Gesture navigation settings

![image](https://user-images.githubusercontent.com/55913608/192533184-d8ce903c-a4bc-437a-84bf-d0ce6942a2ee.png)

1. the UI as a whole would look a lot crispier in apps that had spent no time at making the bar look crisp (maybe because their authors have had the bar disabled too)
2. this feature expands usable screen space
3. there was another request #753 which shows there's a market for this feature
4. it is infinitely easy to implement and maintain this feature as it would literally reuse the same code from sister projects

**Comment by thestinger** [comment]
Not planned as previously stated.

**Comment by thestinger** [comment]
Pull request may be accepted, feature request will not be accepted.

**Comment by Sn0whax** [comment]
> Pull request may be accepted, feature request will not be accepted.

Is there a way we could re-open this to indicate it's a somewhat popular feature? This may encourage people (possibly outside of your team) to work on solid pull request?

**Comment by thestinger** [comment]
No, this is requesting something that's not planned and is a duplicate.

**Comment by Sn0whax** [comment]
> Pull request may be accepted, feature request will not be accepted.

CalyxOS and Lineage (to list a few) do this, they may be key projects to pull from? if we're leaving the option to have a pull request, could we at least leave one of these nav bar removals as open?
