### ISSUE TITLE
Call History doesn't show used SIM for user profile

### ISSUE THREAD

**Issue by Morpheus0x** [GrapheneOS/os-issue-tracker#1524]
Phone: Pixel 5
OS: GrapheneOS 13 (TP1A.220905.004)

I use dual-sim in my phone. One physical and one eSIM. I mainly use a secondary user profile, since this provides more safety (clicking end session clears decryption keys from RAM). Unfortunately, only the main profile shows what sim was used for a call. The other user profile does not.

![call_history](https://user-images.githubusercontent.com/22265595/192719986-7bdfef32-93e6-414b-8d4e-cb83d8edc02e.png)

**Comment by thestinger** [comment]
It's expected Android behavior.
