### ISSUE TITLE
Secondary User login with Fingerprint even when Disabled

### ISSUE THREAD

**Issue by SB13X** [GrapheneOS/os-issue-tracker#1526]
Setting up a new user with a pin and enrolling a fingerprint then disabling Unlock with Fingerprint
SETTINGS>SECURITY>FINGERPRINT>ALLOW FINGERPRINT UNLOCKING [DISABLED]

RESTART

AFTER RESTART:
1- Use pin to log into owner
2- Switch to user account
3- Login to this user with pin (fingerprint does not work here)
4- Lock screen for the purpose of attempting to log back into user
5- User profile now accepts fingerprint for login

MUST toggle this setting to on then back to off the setting to stick and profile behave as expected, with Fingerprint unlock Disabled.

This has been replicated by myself and another user who raised the issue on the forum from which the replication steps above were taken:

https://discuss.grapheneos.org/d/1026-fingerprint-unlockcalls-allowed-after-reboot

**Comment by thestinger** [comment]
Seems the same as https://github.com/GrapheneOS/os-issue-tracker/issues/1451.
