### ISSUE TITLE
[request] Desktop expands to the left

### ISSUE THREAD

**Issue by jackydany** [GrapheneOS/os-issue-tracker#1529]
Hi,
i would like to adress a feature request.
would it be possible to extend the desktop not only to the right, but also to the left of the landing page?
i prefer to have my homescreen in the middle, apps one page to the right and my calender overview one swipe to the left.
In GOS it seems i can only add a new page to the desktop attached to the right side.

Thanks in advance!

ps: great work!

**Comment by thestinger** [comment]
We're going to stick with the standard way this works in AOSP. We can't devote resources to something like this. It works the way it does because on the stock Pixel OS, their extended Pixel Launcher has a special panel when you go to the left.
