### ISSUE TITLE
no automatic rotation in youtube

### ISSUE THREAD

**Issue by jackydany** [GrapheneOS/os-issue-tracker#1530]
Hi,
i have a question regarding rotation in apps.
I activated it on the upper menue and it worked to switch from vertical view to horizontal view (full screen).
But when i rotated the phone again.... it didnt switch back.
Also there is no rotation anymore in youtube at all.
Deactivated and reactivated the function in the menue, no success.
Its working in the video feed overview, but not when i start a video. It wont rotate to fullscreen and back.
Tried newpipe, it works there!

Anybody with the same issue? Am i just stupid or is there a bug?

Thanks a lot in advance
Stefan

**Comment by thestinger** [comment]
This is an app issue if it's happening. Make sure it's not an OS or app configuration issue with how you set it up.
