### ISSUE TITLE
Amoled Dark Mode missing

### ISSUE THREAD

**Issue by bcsti** [GrapheneOS/os-issue-tracker#1532]
In the settings only light and default dark mode are available, not the black Amoled.
It would be good for the battery since apps who support the Amoled Mode would automatically switch to this one, too.

**Comment by r3g-5z** [comment]
AMOLED does not save battery.

Please search for previously asked issues about this. It's not getting added.

https://github.com/GrapheneOS/os-issue-tracker/issues/1299

**Comment by bcsti** [comment]
As I wrote, it is not only for the settings app, but also for all other compatible apps which automatically switch to this mode. And in SUMMARY the difference between the power consumption is clearly visible.

It is not that complicated to code, but if the developers won't add it, then so be it.
