### ISSUE TITLE
GrapheneOS periodically connects to Google domains (*-dnsotls-ds.metric.gstatic.com)

### ISSUE THREAD

**Issue by hypocritical-defender** [GrapheneOS/os-issue-tracker#1533]
I have noticed via DNS tracking that GrapheneOS sometimes (e.g. on OS startup) connects to Google domains of the following structure:

[random letters and numbers]-dnsotls-ds.metric.gstatic.com

e.g.: e938f1ab-dnsotls-ds.metric.gstatic.com

From what I have gathered so far ([see this external link](https://help.nextdns.io/t/60hz6md/metric-gstatic-com-is-not-blocked-but-it-should-be)), this seems to be connected to secure DNS somehow for most/all Android derivatives. However, I do not fully understand why it is necessary and what GrapheneOS does not have a different (de-googled) solution.

Sometimes the connection happens even before the always-on VPN is connected. This means that Google is able to see the public IP address.

Slightly off-topic: something similar seems to happen with Vanadium and www.gstatic.com as well as possibly www.google.com and [update.googleapis.com](update.googleapis.com).

**Comment by empratyush** [comment]
maybe [this](https://cs.android.com/android/platform/superproject/+/master:packages/modules/NetworkStack/src/com/android/networkstack/util/DnsUtils.java;l=53;bpv=1;bpt=1?q=metric.gstatic.com) one?

**Comment by r3g-5z** [comment]
Vanadium will make connections to Google to receive critical security updates to components. That's normal.

**Comment by thestinger** [comment]
You're wrong, it's not a connection to the domain. It's a DNS query as part of DNS-over-TLS to check that it works. Set it to either disabled or force enabled with a specific host and I don't think it will test resolving the name.

**Comment by thestinger** [comment]
This issue makes inaccurate claims about connections and 'tracking' and is therefore being deleted.
