### ISSUE TITLE
[request] divide ringtone / message tone volume control

### ISSUE THREAD

**Issue by jackydany** [GrapheneOS/os-issue-tracker#1535]
Hi,

is it possible to seperate the ringtone from the message tone?
i would prefer to have my messages (signal, whatsapp, ebay and all others) to be vibration only, but keep the ringing of a phonecall loud to not miss the call.

Thanks a lot! Keep up the good work!

**Comment by vchrizz** [comment]
I would be interested in this 'feature' too. Why is notification and ringing tone volume combined at all? Is there a reason for that?

I also get many notifications and want them to be rather silent but do not want to miss phone calls because of silent ringing tone volume.

**Comment by flawedworld** [comment]
This is just how Android works.

**Comment by vchrizz** [comment]
So do I understand correctly, that CyanogenMod/LineageOS and /e/OS use 'custom' patches that accomplish that?
If so, wouldn't it be possible to include those patches in GrapheneOS too?

**Comment by flawedworld** [comment]
Any patches need to be minimal and easy to maintain. We would accept a patch from the community to do this if it meets that criteria. It's not something the core dev team will focus on.

**Comment by vchrizz** [comment]
Sidenote, while searching the web on this topic I found following "workaround", which may not be the exact solution but definetly helps in the short run:
When you get any notification from this application that annoy you,pull down notification bar,hold long press on notification and chose more options,and you have many with options to:
Turn off on sound
Turn on off vibrate
Change sounds..
