### ISSUE TITLE
Frequent problems with phone calls

### ISSUE THREAD

**Issue by MrDiscordMan** [GrapheneOS/os-issue-tracker#1538]
Hello,
I'm having trouble getting calls. Occasionally when someone calls me and I answer, it tells the person on the other end that I am unavailable and phone shows me a missed call.
When the call manages to start, there is a possibility that I can't be heard or or after a short time we can't hear each other and then call get disconnected.
I reseted the APN, VoLTE is off and the network type is set to LTE (recommended). 
The problems are on the sim, sms works without any problems, on esim connection sometimes drops to 2G for a few seconds.
In brief testing on a stock Google Pixel 6A, calls worked without issue.

Graphene OS: TP1A.220905.004.A2.2022092800

**Comment by thestinger** [comment]
Not enough information to attribute this to GrapheneOS. Likely a carrier issue.
