### ISSUE TITLE
Rotate Suggestion not working in 2 button navigation

### ISSUE THREAD

**Issue by sevmonster** [GrapheneOS/os-issue-tracker#1541]
Gesture nav sticks to the bottom of the screen in landscape instead of moving to the side like with 3 and 2 button nav, so I am forced to use 2 button so that I am able to type effectively in landscape... In switching I discovered the screen rotation hint is not present on 2 button but is on 3 and gesture nav.

Issue and fix from another project: https://github.com/PixelExperience/android-issues/issues/2389

Pixel 6 Pro, GOS latest stable (TP1A.221005.002.2022100300)

**Comment by r3g-5z** [comment]
2 button navigation is deprecated and legacy. It's already removed in stock OS and most other OS's. It's not being maintained by GrapheneOS or AOSP.

https://grapheneos.org/usage#2-button-navigation

**Comment by thestinger** [comment]
I think we should likely remove the 2 button option since it's not being maintained in AOSP.

**Comment by sevmonster** [comment]
Do you know of any potential changes from upstream to allow the gesture nav bar to be on the side of the screen in landscape? Or if not would you be against a patch in Graphene to support this?
I know the industry and most consumers have moved away from 2 button, and even I would say gesture is better, but this single capability of 2 button makes it superior to gesture, so important is typing in landscape for me.

**Comment by neelchauhan** [comment]
I have a patch to remove two-button gestures here: https://github.com/GrapheneOS/platform_packages_apps_Launcher3/pull/12

**Comment by r3g-5z** [comment]
2 button navigation overlay was dropped in https://grapheneos.org/releases#2023012500
