### ISSUE TITLE
[Suggestion] More tiles in quick settings

### ISSUE THREAD

**Issue by tjk918** [GrapheneOS/os-issue-tracker#1543]
I often need to switch my audio to mono if im only wearing one earbud. It would be cool to have more quick settings tile to toggle mono, as well as other things. There is an developer tile that toggles sensors as well. It would be nice if that were avaliable to those who dont use developer options. Im dont have many other ideas, but im sure others could chime in with good suggestions if there was any interest

**Comment by thestinger** [comment]
Not planned.
