### ISSUE TITLE
Bluetooth Mic audio input not detected/selectable in apps

### ISSUE THREAD

**Issue by NukeManDan** [GrapheneOS/os-issue-tracker#1545]
I hope I am simply missing how you can manually specify the default/global device for all apps to use as the mic input. Specifically I can connect to any headset that _does_ include a mic and allow for phone calls, media audio, and contact sharing (and tried with both LDAC on and off). I have tested the devices work on a desktop via Bluetooth for audio in/output.

I cannot get applications/calls to use the mic on the bluetooth device, it defaults to the speaker phone input (apps tested: signal and telegram, using the voice note as a test)

Perhaps it could be related to https://forums.androidcentral.com/showthread.php?t=925504&s=03461f53af7126015d434f6c1538ee14&p=6557005&viewfull=1#post6557005 where only "mono" connections are supported? I have tried on a Sony WH-1000XM5, Sennheiser HD1, and Treks devices, all to no avail.

Am I missing an OS setting? Or will I need to get an app to try and control behavior?

**Comment by thestinger** [comment]
It needs to be supported by the app. It hasn't been implemented for GrapheneOS Camera yet. I think it works the same way as the stock OS already.
