### ISSUE TITLE
Request: Add option to remove the Gesture hint (bar at the bottom)

### ISSUE THREAD

**Issue by ledgeri** [GrapheneOS/os-issue-tracker#1546]
Example of the function [https://youtu.be/khECTJ1qfew?t=35](url)

Reasons why it should be there:
-Minimalist design could be cleaner
-If someoe uses full gestures, after a week-or less, the hint is unnecessary
-Even more screen-space
-Possible burn-in of static images sadly still a thing (the system keeps it in contrast to other things almost all the time)
-Other OSs have it. (I am unsure on this, because i saw it only on android 12 (samsung's, and calyx too), and my first GOS is 13)

I do not see any reason why it is missing. (if there is any, please shine light onto those)

**Comment by thestinger** [comment]
This is not currently planned. It's outside the scope of what we work on. We're aware LineageOS and OSes based on it have a toggle for it. There were existing issues filed about this so we don't really need another. If someone wants this they need to submit a clean, minimal patch implementing it as a starting point. We won't accept it as a feature request.
