### ISSUE TITLE
Private DNS not working anymore

### ISSUE THREAD

**Issue by iyanmv** [GrapheneOS/os-issue-tracker#1547]
Private DNS stopped working over wifi (using mobile data is fine) since two stable releases ago. In particular, I am using `adblock.doh.mullvad.net`. I can replicate in different wifi APs, and as soon as I'm back on LTE, it works again.

**Comment by thestinger** [comment]
This is likely your VPN blocking the connection. Try without it or with a different one.

**Comment by iyanmv** [comment]
I'm not using a VPN.

**Comment by iyanmv** [comment]
And it's not a question, it's an issue. It was working perfectly fine until a recent update. I can replicate all the times without a VPN by connecting or disconnecting to a wifi network.

**Comment by iyanmv** [comment]
I have tried 5 different wifi networks (including `eduroam`)

**Comment by thestinger** [comment]
This is a network or configuration issue on your end or with the DNS provider you're using.
