### ISSUE TITLE
Notification-Forwarding to current user stopped working

### ISSUE THREAD

**Issue by lqed** [GrapheneOS/os-issue-tracker#1549]
Notifications (any, from all apps) don't get forwarded to the current user anymore (in every profile). The toggle to enable Forwarding is set in all profiles. 
Everything worked before, all notifications got forwarded (started ~2 weeks ago). Profiles are active in the background, e. g. when I get a call in profile B, I can hear the ringtone in profile A.
I was always on the latest stable release.

Restarting sessions/device and retoggeling forwarding didn't solve it.

**Comment by thestinger** [comment]
Make sure you haven't disabled the notification channel. The feature is still working fine.

**Comment by lqed** [comment]
Indeed. The channel 'other users' in Android System was disabled. Now I know what I messed up. I think I tried to disable a specific notification from another user but by that I disabled the whole user channel.

Thank you!
