### ISSUE TITLE
VPN based ad-blockers do not work over Wi-Fi

### ISSUE THREAD

**Issue by guy-amun-ra** [GrapheneOS/os-issue-tracker#1552]
Envrionment: GrapheneOS (Based on AOSP 13)

What's not working:
Any VPN over Wi-Fi such as:
  1. Net Guard
  2. RethinkDNS
  3. NextDNS
  4. AdAway - the non-root feature as VPN

I know, from past experience, that AdAway works out of the box, 
My question, is it something specific to GrapheneOS?

**Comment by thestinger** [comment]
They work fine. Not an OS issue.
