### ISSUE TITLE
Notifications which are muted in secondary profile still are displayed in main

### ISSUE THREAD

**Issue by t-nil** [GrapheneOS/os-issue-tracker#1555]
I use whatsapp (WA) in a user profile (for obvious reasons). In WA I have multiple group chats which I have muted indefinitely; the checkbox for displaying notifications is not checked.

On my user profile, I don't get any notifications but on main, every time I receive a group message, I get the "WhatsApp on GApps Profile" notification, which is very annoying and defies the purpose of the feature.

Thank you for your time.

**Comment by t-nil** [comment]
I tried unmuting and muting every group in WA with no effect

I am running newest stable build TP1A.221005.002.2022100300

**Comment by thestinger** [comment]
Where did you mute the notification? The OS settings?

**Comment by t-nil** [comment]
> Where did you mute the notification? The OS settings?

Nope, I muted the group conversations inside WA. I recognize that the issue could be caused by WA not using the notification API properly, but since I don't get a notification in the secondary profile, maybe GrapheneOS can still work around things.

Do you need screenshots?

**Comment by t-nil** [comment]
Yes. The issue is still happening. I don't think it happens everytime I get a message in a muted chat, but it happened yesterday and today.

thestinger: You closed this as not planned. Is this issue definitively out of scope for GrapheneOS, or would you consider investigating if more infos were provided (e.g. instructions to reproduce)?

**Comment by empratyush** [comment]
@t-nil  if you can provide the steps to reproduce the bug then we can reopen the issue.
