### ISSUE TITLE
Apps not getting location even though gservices and framework are installed

### ISSUE THREAD

**Issue by linuxitomio** [GrapheneOS/os-issue-tracker#1558]
I download the framework and the services apps from the grapheneos.
I install aurora store.
Download an app called togoogtogo
open it but is not possible to get location 
download and app called midttraffik live
open but it will say that I need google play services installed.

Same procedure but installing google play 
I download the apps from the store 
the app works proper

**Comment by muhomorr** [comment]
https://grapheneos.org/usage#sandboxed-google-play-installation

> Play services and the Play Store depend on each other, one will not work properly without the other.
