### ISSUE TITLE
Since GOS 13 building with additional apps partly not possible

### ISSUE THREAD

**Issue by 12aw** [GrapheneOS/os-issue-tracker#1563]
Hi,
I used to build GrapheneOS with F-Droid and other additional apps and it worked without any problems on GOS 12 but since GOS 13 these apps doesn't show up on the phone anymore after flashing my build. I didn't see any error while building GOS 13. Strange thing is that some apps appear and some not anymore.
Can anyone help? Thanks!

**Comment by thestinger** [comment]
It works fine, you're doing something wrong.

**Comment by 12aw** [comment]
I know you don't have much time, do you nevertheless have an idea what I'm doing wrong?
Thanks anyway for your work!

**Comment by thestinger** [comment]
Not enough info about how you're trying to do it. Make sure you're adding the packages to PRODUCT_PACKAGES.

**Comment by 12aw** [comment]
Did. I added them in "handheld_product.mk" and create a folder in "external" with an Android.mk and a subfolder "prebuilt" with the APK.
For example like this:
`LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := davdroid
LOCAL_MODULE_CLASS := APPS
LOCAL_PRODUCT_MODULE := true
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_SRC_FILES := prebuilt/davdroid.apk
LOCAL_OPTIONAL_USES_LIBRARIES := androidx.window.extensions androidx.window.sidecar

include $(BUILD_PREBUILT)`

**Comment by thestinger** [comment]
That defines a package, it doesn't add it to the build.

**Comment by r3g-5z** [comment]
You need to append it to [PRODUCT_PACKAGES](https://github.com/GrapheneOS/platform_build/blob/13/target/product/handheld_product.mk#L24) after defining the package.

**Comment by TopFox** [comment]
Hey, I would be interested to know how you would add it to the build if creating the Android.mk and adding the app name to handheld_product.mk is not enough. Is there any other step you could indicate or maybe a documentation somewhere?
