### ISSUE TITLE
Persistent notifications use theme colors of the previous user profile

### ISSUE THREAD

**Issue by Anonymous1157** [GrapheneOS/os-issue-tracker#1564]
This issue is probably easiest to describe by just showing the problem with a screenshot, so I've attached one.

Persistent notifications, or notifications that were otherwise not cleared before switching user profiles, will sometimes switch to the Material You color theme of the other user profile, and will be the wrong color for the theme in use by the user. In the below screenshot notice that the charging and System Updater notifications have a different background color from the others; these notifications were received after switching back to this user profile and are the correct color, and the others are persistent background app notifications that are the wrong color for this theme.

This happens not every time but frequently. Usually the notification background color will be wrong but sometimes the icon color will also be wrong. The correct colors for the current user's theme are used in any new notifications received while that profile is active, and this includes restarting background apps with persistent notifications but not hiding and un-hiding them from Settings -> Notifications.

Two notifications with different color themes behave slightly differently and will sometimes break the rounded corners for groups of notifications. For example if I use the "Clear all" button then multiple persistent notifications that do not get cleared will have large rounded corners like they are the only notification on screen.

I've reproduced this issue on a Pixel 6 Pro and a Pixel 4a both running the 20221003 update. IIRC this was happening in A12 but I don't remember how long ago or if it was ever not happening. I don't know if this is also an issue on AOSP or stock. I didn't report it earlier because I had assumed this was an obvious enough issue that surely someone else noticed and it would be fixed soon...

![Screenshot_20221014-150751](https://user-images.githubusercontent.com/8900271/195923125-79cf0d8e-00b9-4192-8621-40d4c928fbe5.png)

**Comment by thestinger** [comment]
Upstream AOSP issue. Not going to be addressed by GrapheneOS downstream.
