### ISSUE TITLE
Duress fingerprint and pin/password

### ISSUE THREAD

**Issue by SisyphusRising** [GrapheneOS/os-issue-tracker#1569]
Request: Option to add a distress fingerprint or pin/password in Security Settings. Not a novel concept but surely useful.

Problem: Someone finds themselves in a situation where an adversary can compel you to scan a finger or input your pin/password

Solution: Using a particular fingerprint, say your ring finger, will open the phone, but will just lead to a "generic" homepage with "normal" apps. Your true account would be hidden and no one would be the wiser.

**Comment by r3g-5z** [comment]
https://github.com/GrapheneOS/os-issue-tracker/issues/29
