### ISSUE TITLE
Storage permission not possible?

### ISSUE THREAD

**Issue by YugiFanGX** [GrapheneOS/os-issue-tracker#1571]
When using the bitwarden app with a security token,
GrapheneOS tells me, that I have to unlock storage permission.

There is no Storage permission showing up on the recent GrapheneOS version,
after selecting permissions option. How can I / we fix this?

**Comment by thestinger** [comment]
It works fine, there's nothing wrong with it. Issue tracker is for filing issues and we don't use it as a support platform. Please use the Matrix rooms or discussion forum for questions.
