### ISSUE TITLE
Dialer app Ussd font is very hard to read with dark theme enabled

### ISSUE THREAD

**Issue by ni-ka** [GrapheneOS/os-issue-tracker#1572]
Hi!

I live in Senegal and need occasional access to some ussd services. Unfortunately when using the dark theme the font is almost impossible to read (black on dark grey)

![Screenshot_20221018-071155](https://user-images.githubusercontent.com/1225776/196363942-d5c02e68-a5f6-4223-9bbb-f999bb9061a5.png)

**Comment by thestinger** [comment]
Color scheme is app specific. You need to be clear about which app this is and how to reach the menu. Is it the Dialer app? In that case it's an issue about the Dialer app. It's not an overall OS issue.

**Comment by ni-ka** [comment]
@thestinger sorry should have been specific. This is indeed the dialer app when using a USSD short code.

**Comment by empratyush** [comment]
Unable to reproduce this seems like the issue has been already fixed.
