### ISSUE TITLE
Banking app crashing after last OS update

### ISSUE THREAD

**Issue by proudhon** [GrapheneOS/os-issue-tracker#1575]
After 1.5yrs without a problem my bank's app crashes each time i try to login.

Phone: Pixel 4a
Build: TP1A.221005.002.2022101600

Error output:

```
type: crash
osVersion: google/sunfish/sunfish:13/TP1A.221005.002/2022101600:user/release-keys
package: com.vipera.chebanca:560
process: com.vipera.chebanca

java.lang.ClassCastException: java.lang.NoClassDefFoundError cannot be cast to java.lang.Exception
	at com.vipera.login.viewmodel.LoginViewModel$postLogin$1.invokeSuspend(SourceFile:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:3)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:18)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7904)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

```

**Comment by akc3n** [comment]
This could be that your banking app had a recent update that switched over from the SafetyNet API to the new Play Integrity API. 

More info here: https://developer.android.com/training/safetynet/deprecation-timeline

**Comment by proudhon** [comment]
I should've stressed that I tried installing last 3 versions of the app from the aurora store and they all behave the same way. It really looks related to the last  OS update.

**Comment by r3g-5z** [comment]
A more verbose crash log like a full bug report needs to be sent privately to a developer. This crash alone is extremely vague and only indicates it's an app bug because of how lacking it is.

**Comment by proudhon** [comment]
I just inspected the full bug report myself. Apparently it complains about Play Services and Play Store missing and, in fact, started to work again after installing those via GOS "Apps". The weird thing is that the app hasn't been updated since the last GOS update which introduced the "bug" and always worked with GSF alone.
I'm attaching the full bug report if it can be of any interest.
[bugreport-sunfish-TP1A.221005.002-2022-10-21-21-09-05.zip](https://github.com/GrapheneOS/os-issue-tracker/files/9842041/bugreport-sunfish-TP1A.221005.002-2022-10-21-21-09-05.zip)

**Comment by thestinger** [comment]
It's not a bug.

**Comment by proudhon** [comment]
Sorry, i was in a rush and couldn't explain me better (but, that's why the word bug is inside quotes).

The sudden change of behavior that led to the app crashing because of missing gps and play store happened after last OS update and not after an app update (i would't have reported it otherwise).
I'm totally fine installing those packages if an app explicitly requires them, still, it is a bit strange that this requirement pops up after an OS update.

**Comment by thestinger** [comment]
It's not from the OS update.

**Comment by thestinger** [comment]
Apps usually depend on services run by the app developers which can change behavior without an app update. That includes shipping new feature flag configurations to the app enabling / disabling code. They can ship features as disabled and then enable them via feature flags later. This is extremely common for Google's apps but other developers do it too.

Not everything that goes wrong is because of an OS update. There are ALWAYS recent GrapheneOS OS updates because we do frequent releases. You can't assume stuff happened because of an OS update since there was always a recent OS update.

**Comment by proudhon** [comment]
Thanks for the explanation, it is clear now. Just for the record, i didn't want to assume anything,

**Comment by proudhon** [comment]
Thanks for the explanation. Just for the record, i didn't want to assume anything, OS update was the only aknowledgeable change i could see and i used successfully that very app 20 minutes before os update and stopped working right after rebooting to apply update changes.
Sorry for the loss of time and, again, thanks for the meaningful explanation.
