### ISSUE TITLE
Ninja fails compilation, help

### ISSUE THREAD

**Issue by N1co1asB1ancon1** [GrapheneOS/os-issue-tracker#1576]
I am probaly doing some misconfiguration.. 
But i dont have a clue where it might be.

I am trying to build and i keep getting this error:
Exception in thread "Main"  java.lang.OutOfMemoryError java.heap.space

I dug around and changed this in the scripts/envsetup.sh 
export _JAVA_OPTIONS="-XX:-UsePerfData -Xms16G -Xmx16G"

#echo $_JAVA_OPTIONS
-XX:-UsePerfData -Xms16G -Xmx16G

Stills fails to compile, same error.
I am building for qemu on x86_64, in the choosecombo menu i choose "debug" "userdebug" "aosp_x86_64" 
I have 16GB RAM + 16 SWAP

**Comment by r3g-5z** [comment]
Ask for support in [#dev:grapheneos.org (GrapheneOS Public Development)](https://grapheneos.org/contact#community). OS issue tracker is for tracking GrapheneOS issues, not for build support.
