### ISSUE TITLE
Sometimes top bar doesn't display. 

### ISSUE THREAD

**Issue by MaxsimLionel** [GrapheneOS/os-issue-tracker#1579]
Pixel 4, TP1A.221005.002.2022101800
Top bar sometimes has to be touched or pulled down on to display. After the displays normally for awhile until it gets stuck again.

**Comment by thestinger** [comment]
Unable to reproduce. It sounds like you're talking about apps using immersive mode. GrapheneOS changes nothing about this and it's very unlikely that any new UI bugs are added with this compared to standard Android 13 via AOSP or the stock Pixel OS.
