### ISSUE TITLE
Camera Stuttering/Framerate issues on Pixel 6a

### ISSUE THREAD

**Issue by link444112** [GrapheneOS/os-issue-tracker#1581]
The Camera has severe stuttering issues, when using ANY Camera app, including Graphene OS Camera, Google Camera, Google Camera Go, Open camera, etc. It varies with each app, but they all stutter. This renders taking videos impossible. Sample videos, and screen recordings are provided here: https://drive.google.com/drive/folders/1vteZbnURBADyZ9rZ8QOqlOTV-BPbc-Ld?usp=sharing
Thank you, please fix as soon as possible, as the Camera is a crucial feature. 
Steps to reproduce: 
On Pixel 6a, 
Open GrapheneOS Camera.

**Comment by thestinger** [comment]
This is a configuration issue with your device or a hardware issue, not a GrapheneOS issue. There's nothing for us to resolve. If you're using an accessibility service, turn it off.
