### ISSUE TITLE
Mint Mobile on GrapheneOS

### ISSUE THREAD

**Issue by diib1** [GrapheneOS/os-issue-tracker#1582]
I am on latest release GOS for Pixel 6 Pro, and a week ago I switched to Mint Mobile/US from T-Mobile. 
Mint Mobile requires me to add a new APN and every time I enter one, it gets auto-deleted. I finally able to enter one by entering only partial information such as APN name, type. After a couple days, I tried to modify it to enter MMSC, MMSC port, MCC and MNC. 
But MNC is going back to 240 every time I change it according to Mint suggested value, 260. 
Also, Carrier settings version continue to show tmobile_us-400000000138.54. I don't know if it should say Mint Mobile instead. 

Is anyone with the similar issues here?

**Comment by jorgeluiscarrillo** [comment]
https://discuss.grapheneos.org/d/245-pixel-6-data-connectivity-issues-mint-mobile/2

**Comment by bigOconstant** [comment]
I'm having the same issue

**Comment by bigOconstant** [comment]
> @bigOconstant Follow the instructions on the Mint Mobile website, just make sure to set the MVNO type as GID and the MVNO GID as 756D

Doesn't work. When I hit save it just deletes it. Even when I put the GID like you said. I can link a video if you want.
