### ISSUE TITLE
NFC Inop

### ISSUE THREAD

**Issue by gbkelley** [GrapheneOS/os-issue-tracker#1583]
New install on Pixel 4XL 10-21-22 via Web Installer

Will not accept a Contact Share via NFC from another phone (LG G7)

Other phone shows 'Tag Not Supported'

Does not show option to share via NFC when sharing a Contact

Can turn NFC on and off but no response with it on

Play apps installed and tried a different Contacts app

**Comment by thestinger** [comment]
You likely haven't granted the required privileges to Play services. Please try again after doing that.
