### ISSUE TITLE
Storage Scopes don't work

### ISSUE THREAD

**Issue by piotrKantor** [GrapheneOS/os-issue-tracker#1588]
App have permissions only to Network and Sensors.
In storage scopes of the app I added only one image with "ADD IMAGE" button.
In the app itself I can see 63 pictures from my gallery, but not all of them.
Clearing cache and deleting storage didn't help.

**expected behavior:**
In the app I should see only the images I put to storage scopes. 

**Additional info:**
Pixel 6a
build number: tp1a.221005.003.2022101800
name from playstore: Mushroom identification from p
author: Dominik Steinhauser
rozpoznani hub
com.mushroom.recogniser
versionCode 20507
targetsdk 25
minsdk 16

**Comment by thestinger** [comment]
Please read https://grapheneos.org/usage#storage-access.

**Comment by thestinger** [comment]
> Additionally, both modern and legacy Android apps can open the system file picker interface to have the user store or load one or more files/directories on their behalf. This type of access doesn't require any of the permissions listed above. Using this approach gives the user control over where files are stored in their home directory and which files/directories can be used by the app. This is based on the Storage Access Framework (SAF) introduced in Android 4.4. SAF allows the user to grant access to files/directories in their home directory, external drives and also app-based storage providers such as network shares, cloud storage, an encrypted volume, an external drive with a filesystem the OS doesn't support for external drives, etc. This is the only way to use those app-based storage providers and modern Android has removed the legacy approach for accessing external drives.
