### ISSUE TITLE
Split screen is not working

### ISSUE THREAD

**Issue by trancephorm** [GrapheneOS/os-issue-tracker#1591]
Latest version, if you try to put 2 apps in split-screen mode, launcher crashes.

**Comment by thestinger** [comment]
It's working fine across our test devices. Not enough information provided about your device model, OS version and configuration.

**Comment by trancephorm** [comment]
Pixel 6, OS version is the last stable one... Anyways, how can I check which is the version?

**Comment by thestinger** [comment]
Settings -> About phone

Which launcher are you using? The standard one?

**Comment by thestinger** [comment]
And which navigation mode are you using? Gesture vs. 2-button vs. 3-button.

**Comment by trancephorm** [comment]
Is it a build number? If so, it's TP1A.221005.002.2022102300. I'm using Nova7 launcher, newest version. I didn't think it has to do with launcher. I use 3-button navaigation mode.

**Comment by thestinger** [comment]
Try the default launcher.
