### ISSUE TITLE
Voicemail menu gone from Phone app

### ISSUE THREAD

**Issue by lake-effect** [GrapheneOS/os-issue-tracker#1592]
I believe this took place sometime over the last 2-3 updates? 

Voicemail used to be an item in the stripe menu at the bottom of the phone app, but now there are only three: Quick Access, Call History, and Contacts.

In the extended menu at the upper right, Call History and Settings are available. In Settings, Voicemail is an option, and it contains Notifications and Advanced Options, which contains a Service setting and a Setup option. In Setup, there's only an unchangeable voicemail number.

### Environment

- Model: Pixel 5
- Build: TP1A.221005.002.2022101800
- Kernel: 4.14.276-g1688b087f227
- Security update: 2022-10-05

**Comment by thestinger** [comment]
It's still working fine. It sounds like your carrier isn't providing it in a compatible way. This is carrier-dependent and you haven't said your carrier.

**Comment by lake-effect** [comment]
Oops, I didn't realize that was relevant. Carrier is Ting Mobile (MVNO renting T-Mobile network)

**Comment by lake-effect** [comment]
Per #1629, reset APN and network settings with no change. Carrier settings string is `tmobile_us-40000000124.44`

**Comment by lake-effect** [comment]
Google dialer also does not allow access to visual voicemail.

**Comment by ilikenwf** [comment]
Try changing your voicemail number in voicemail setup to your actual full number +1XXXXXXXXXX then attempt again in google dialer. Fixed it for me with Visible
