### ISSUE TITLE
Override Force-Dark Feature Does Not Persist Upon Reboot

### ISSUE THREAD

**Issue by g1t3m** [GrapheneOS/os-issue-tracker#1595]
Platform: Google Pixel 6 Pro
GrapheneOS version: TP1A.221005.002.2022102300

Steps to Reproduce:
1. Enable Developer Options
2. Navigate to Override Force Dark setting
3. Toggle this setting on
4. Reboot phone
5. Navigate back to Developer Options > Override Force Dark setting
6. Setting is disabled upon reboot, and does not persist.

Please let me know if you require additional information about this issue.

**Comment by r3g-5z** [comment]
It's not a bug, it's intentional for it to not persist because it's a debugging/developer only feature and not an end-user feature.

https://github.com/GrapheneOS/os-issue-tracker/issues/656
