### ISSUE TITLE
Notification control for certain apps disabled

### ISSUE THREAD

**Issue by rehejuhan** [GrapheneOS/os-issue-tracker#1598]
GrapheneOS TP1A.221005.002.2022102300
Pixel 6 Pro
Notifications can't be switched on (switch "greyed out") for Calculator, PDF Viewer and Jami (installed from F-Droid) and can't be switched off for Phone and Files.

**Comment by thestinger** [comment]
If the apps don't support notifications, you can't turn it on. Phone and Files are part of the base OS beyonds just being bundled apps and it's required.

**Comment by rehejuhan** [comment]
I can understand the logic of the above, but why is GraoheneOS disabling notifications for third party app Jami?

**Comment by thestinger** [comment]
It's not disabling it. I suggest you check whether you've enabled a device manager, accessibility service or notification manager via special access grants.
