### ISSUE TITLE
Launcher App Grid 5x6

### ISSUE THREAD

**Issue by jaedog** [GrapheneOS/os-issue-tracker#1599]
With larger phone screens it would be great to be able to squeeze more widgets/app icons onto the screen. 5x6 or 6x6 would be great options.

**Comment by r3g-5z** [comment]
Going to assume this isn't wanted by GrapheneOS based on historical PRs submitted that did not land.

**Comment by thestinger** [comment]
There's a pull request we may accept but the feature on the issue tracker doesn't need to remain open.
