### ISSUE TITLE
Google Camera 8.6.263.471358013.15 not working on Pixel 4a 5G

### ISSUE THREAD

**Issue by Barnatu** [GrapheneOS/os-issue-tracker#1600]
I tried today to install GoogleCamera on my Pixel 4a 5G GOS, build number TP1A.22.10.05.002.2022102300.

The app was taken from another stock Pixel 4a 5G that I have in Android 13 build TP1A.220905.004 build number with this command:
`adb pull /data/app/~~TIF65P6REHlVkHo01zbl3w==/com.google.android.GoogleCamera-hLb0MUZ4rxZZ8i-cyhn7Yg==/base.apk GoogleCamera.apk`
Google Camera is in version 8.6.263.471358013.15

Then I transferred it to my Pixel 4a 5G GOS and installed it after installed GSF.
The app keeps crashing.
it seems that I can find some hints in my bugreports :
`bugreport-bramble-TP1A.221005.002-2022-10-26-19-06-08.txt:10-26 18:53:21.726  1000  1619  2521 I am_crash: [5789,0,com.google.android.GoogleCamera,551271492,java.lang.UnsatisfiedLinkError,dlopen failed: library "libgcastartup.so" not found,Runtime.java,1077]`

**Comment by r3g-5z** [comment]
Try getting it from a more official source like Play Store. I don't think pulling the APK from a stock device has all the libraries and such.

**Comment by Barnatu** [comment]
Installing it from Aurora Store solved the issue. Thanks a lot.
