### ISSUE TITLE
suggestion:   use usbguard to limit USB access

### ISSUE THREAD

**Issue by noci2012** [GrapheneOS/os-issue-tracker#1601]
For linux there is usbguard (available for several years) to filter what devices are allowed to access the system.
If a device is blocked it won't be usable.

This might prevent attacks through the USB port, unless it is a known (to usbguard) device.
The device can be identified including it's serial number. 

https://github.com/USBGuard/usbguard

**Comment by r3g-5z** [comment]
There is already a setting to block USB peripherals in the kernel.

https://grapheneos.org/usage#usb-peripherals

**Comment by thestinger** [comment]
There's an issue filed about implementing per-device prompts but it wouldn't be this approach and wouldn't use serial numbers at all.
