### ISSUE TITLE
Alarm clock disabled overnight

### ISSUE THREAD

**Issue by crankc** [GrapheneOS/os-issue-tracker#1602]
Last night was the second time my set alarm was disabled by its own overnight. Details below, some more or less important:

- Device is Pixel 5.
- I use the stock alarm clock which has battery restrictions disabled (by default, it seems).
- Alarm is set at 6 AM on Mon-Fri, and 7 AM on Sat-Sun.
- Do Not Disturb is set between 7:30 PM and 6:30 AM every day, and alarms are allowed to override DnD.
- ~~I use a custom recorded alarm sound.~~ Apparently it's a stock sound after all, i was mistaken.
- I use Lawnchair as my launcher.
- The alarm works most of the time just as intended, making this an intermittent occurrence.
- The OS is set to NOT auto-reboot after an update, making this bug separate from #1476 (i believe).

With LineageOS the above configuration woke me up reliably at 6 AM every weekday morning, overriding DnD. I flashed GrapheneOS a couple weeks ago and the alarm has now failed to ring twice. Today I was woken up by a family member at 6:05 and noticed:

- No alarm was shown by the clock widget, despite alarms being enabled in the stock clock app.
- DnD was disabled even though no alarm had been rang.
- Notifications log didn't display anything about an alarm, calls, or messages at the time when the alarm was supposed to go off.

How can i troubleshoot this further? Obviously i can no longer rely on the stock app, but i wonder if i can rely on the phone as an alarm at all anymore.

**Comment by crankc** [comment]
Looking at the app permissions, the stock alarm app does _not_ show up in Special app access -> Alarms & reminders, even if "show system apps" is selected.

I don't know how relevant this is, but the Simple Clock app (on F-Droid) is displayed in the special app access list, as being allowed to set alarms and reminders. Probably not very relevant, since i seem to be the only user with this problem, and i'm certain many Graphene users use their phones as alarm clocks as well.

**Comment by thestinger** [comment]
You should check uptime to see if it rebooted overnight. In that case, it is the same  as the one that's filed along with an issue causing a reboot. I don't really think that's the issue though.

It's not reproducible by others and likely a configuration issue. The only known issue is a regression with Android 13 after rebooting due to something being wrong with direct boot support. If you're unable to provide more information, there's not much we can do.

**Comment by crankc** [comment]
Uptime 54 hours at the moment, so a reboot has not occurred. It should ask for a SIM card PIN after a reboot in any case. I'm afraid there is no additional information to be provided, as i don't have many ideas i could try.

I can turn off Do Not Disturb, and see if that helps, considering DnD (along with the alarm) was turned off by itself both times this has occurred - about half an hour before it was scheduled to end. Maybe related, maybe not.

I thought about trying another alarm clock app, but from what i can tell, Google has made/will make it harder for 3rd party apps to do reliable alarms, so i'm not sure if relying on them is a good idea either.

What about a flash issue? I had LineageOS (A12) installed before i flashed Graphene, and so my OEM unlock was already enabled and i didn't issue a manual wipe at any time during the flashing process. Does the install script wipe the device first, or did i unknowingly perform a dirty flash?

In any case, i am getting a Pixel 7 Pro shortly, so we'll see if i run into this issue with that device.

**Comment by thestinger** [comment]
Locking wipes all data. You have the bootloader locked for verified boot to be enabled, right? There's no such thing as a dirty flash when you have a proper locked GrapheneOS install.

**Comment by crankc** [comment]
Yes, i locked the bootloader after installing. Locking wipes all data = user data, though? I was thinking whether flashing Graphene on top of of Lineage would be a problem, because i wasn't aware of a system wipe being performed during the installation of Graphene. I'm not too familiar with how it works, so if you believe this cannot be the cause for my issue, then i won't bother with a reflash. I'll reply if the P7P introduces this issue too. I doubt it.

Thanks.
