### ISSUE TITLE
Gifs are unable to play

### ISSUE THREAD

**Issue by NXTler** [GrapheneOS/os-issue-tracker#1603]
Hello,
I have a Google Pixel 4a 5G and naticed a problem with displaying animated .gif files.
Animated .gif files do not get played on any galery app I tested, in some cases even the thumbnail doesn't load.
I'm willing to give more information when needed.

**Comment by Tim-Potratz** [comment]
The Apps I tested 100% support .gif files. I sanity checked them on a another device without GrapheneOS. The problem has to be the OS or did I missed something?

**Comment by NXTler** [comment]
Thats exactly the problem. I tested several apps and sanity checked them on another device without GraphenOS. Even the official galerie app was not able to display animated .gif files.

**Comment by NXTler** [comment]
So what now? Should I just go away and life with this problem?

**Comment by thestinger** [comment]
Use an app supporting it. We don't actively develop AOSP Gallery.

**Comment by NXTler** [comment]
I did try to use several apps that support it. Though for some reosen they are not able to show animated gifs. They don't even work when trying to open them via browser (file://sdcard/).

**Comment by NXTler** [comment]
To be clear, I'm not requesting you to make a galerie for gifs or anything like that. It's just that for some reason apps are not able to gather the information they need to play gifs.
This is not linked to the app or gif I use either! I doupple checked my data with a second device that isn't running GrapheneOS, with the same apps and gifs.

**Comment by thestinger** [comment]
Can you specify which app is not working on GrapheneOS but is working elsewhere?

**Comment by NXTler** [comment]
One was Simple Gallery Pro, the other was the already build in gallery and the other was the Vanadium browser with file://sdcard/

**Comment by Roy-Orbison** [comment]
Fossify Gallery is the current open-source fork of Simple Gallery Pro.

**Comment by Roy-Orbison** [comment]
It would be great if this was one of those fixes that the Graphene crew could advocate for inclusion into upstream. GIFs don't even show in the stock messages app, just a blank space where an image would be in virtually every other messaging app.

[The Android developer docs say that GIF support is built in since API level 28.](https://developer.android.com/social-and-messaging/guides/media-animated-gif)
