### ISSUE TITLE
Cannot find `Device Controls`

### ISSUE THREAD

**Issue by varchar-42** [GrapheneOS/os-issue-tracker#1604]
Hello,

I'm on pixel 7, version TD1A.220804.031.2022102600,
I cannot find the quick tile for Device Controls or any way to access it.
Also I can find the toggle in the settings to access it from the lockscreen but nothing shows up on the lockscreen:
![IMG_20221027_123516](https://user-images.githubusercontent.com/12401635/198262849-20ec4e21-e2a2-4c00-8bd2-ac4a01e530cf.jpg)
xml here :
https://github.com/GrapheneOS/platform_packages_apps_Settings/blob/13/res/xml/security_lockscreen_settings.xml#L60

For reference it's supposed to look like this:

![Screenshot_20221027-123900_System UI](https://user-images.githubusercontent.com/12401635/198263572-94a0c97c-428d-41e0-bce5-4e0ec2cd1488.png)

**Comment by SirCypher** [comment]
Hi, I'm struggling to find these device controls as well.
According to https://companion.home-assistant.io/docs/integrations/android-device-controls/ (the very bottom of the page) I should be able to see the homeassistant controls with Android 13, but they are nowhere to be found.

I'm on a Pixel 6a with the latest official GrapheneOS version (2022111000).

Do you have any ideas / suggestions what the issue might be?
Thank you very much and best regards

**Comment by thestinger** [comment]
Please don't bump issues.

**Comment by thestinger** [comment]
This quick tile was removed by mistake and will be added back as part of the port to Android 13 QPR1 in the next release.

**Comment by SirCypher** [comment]
Can anybody confirm that this is working?
I upgraded to the latest release (2022120700) but I can't see the device controls or any new tiles to tap. Am I missing something? Thanks a lot!

**Comment by qcasey** [comment]
Yes, both Device Controls and Wallet tiles are showing for me on `TQ1A.221205.011.2022120700`

In case it's not clear, you need to edit your tiles and drag both of them up.

**Comment by SirCypher** [comment]
@qcasey Thank you very much for your clarification! I haven't used this feature before so I was a bit confused where exactly to look. But now I can confirm that it works too.

For future reference, in case anyone else has problems:
Unlock your phone. There is a normal quicktile called "device control". Add that to your regular quicktiles. Then tap on it, and you can select the device controls you want on your lockscreen. Select whatever you need. Lock your phone, bring up the lockscreen, and for example with homeassistant there will be a small icon in the lower left corner of the lockscreen.

@thestinger Thank you very much for fixing this!
