### ISSUE TITLE
Google services not working in Shelter

### ISSUE THREAD

**Issue by laraib07** [GrapheneOS/os-issue-tracker#1606]
I installed shelter and made a work profile. I installed google store, framework and gms in the work profile. Yet I am unable to sign in to it.
Usually on other devices, after following above procedure, I can see google as an option in Settings > Passwords and accounts > work. But on graphene OS it is not available.

**Comment by thestinger** [comment]
Please ask on discuss.grapheneos.org or our Matrix room.
