### ISSUE TITLE
Reroute location requests to the OS APIs not working

### ISSUE THREAD

**Issue by ggrzeczkowicz** [GrapheneOS/os-issue-tracker#1608]
I installed the latest update ([TD1A.220804.031.2022102300](https://github.com/GrapheneOS/platform_manifest/releases/tag/TD1A.220804.031.2022102300)) yesterday on my Pixel 7 Pro.
I have Play Services sandboxed in the work profile using Shelter.
Since this update, when "Reroute location requests to OS" is enabled, apps installed in the work profile that need Play Services do not get location (ex: Google Earth).
Applications in the work profile that work fine without Play Services do (e.g. GPS Status) and when the option is disabled, all applications get a location.
How can I help you by providing some logs (I am a new GrapheneOS user) ?

**Comment by ggrzeczkowicz** [comment]
[bugreport-cheetah-TD1A.220804.031-2022-10-27-17-54-53.zip](https://github.com/GrapheneOS/os-issue-tracker/files/9881745/bugreport-cheetah-TD1A.220804.031-2022-10-27-17-54-53.zip)

**Comment by muhomorr** [comment]
Log shows that Google Earth is considered to be a background app and is forbidden from accessing location because of this.
This is likely a work profile bug, though I'm unable to reproduce it in both full and work profiles.
Try to reproduce it on your device in a full user profile.

**Comment by thestinger** [comment]
Seems like an AOSP issue with work profiles.

**Comment by ggrzeczkowicz** [comment]
When I remove the work profile, uninstall Shelter, install it again and creating a new work profile, location with the OS APIs in Google Earth work again.
But I do not know why the GrapheneOS update tempers with location in work profile.

**Comment by muhomorr** [comment]
It's unlikely that this is a GrapheneOS-specific issue. Work profiles are known to be buggy in general.

**Comment by r3g-5z** [comment]
Is this still an issue? Location-related improvements to GmsCompat have been done since this was posted.
