### ISSUE TITLE
MitID app stopped working on 2022102600

### ISSUE THREAD

**Issue by lbschenkel** [GrapheneOS/os-issue-tracker#1609]
- Pixel 6
- GrapheneOS TP1A.221005.002.2022102600
 - [MitID app](https://play.google.com/store/apps/details?id=dk.mitid.app.android) version 2.3.4 (version code 55)

MitID is the official authentication app in Denmark. It is used to authenticate against all government services, banks, and other private websites. It is basically indispensable and you cannot do anything digitally in Denmark without it.

I upgraded GrapheneOS and suddenly this app refuses to work and claims that the device is rooted. This *could* have been because  the app is now enforcing SafetyNet attestation, however 2 other users tried the exact same app version on an older version of GrapheneOS and it does work without showing the "rooted" screen.

Given the report above, I believe that this is due to some change in 2022102600 that is tripping some check inside this app. I tried looking at logcat but could not see anything relevant.

I also tried playing with the compatibility mode, native app debugging and secure app spawning but none of those affected the outcome.

I understand that this is a closed source app but given that it might be **the** most essential app for Danish users, if it stops working it is a complete deal breaker for the adoption of GrapheneOS in the country. I urge the developers to help investigating why it stopped working. Verification is as simple as installing the app and opening it: if it does not like the device then the "rooted screen" will show up  immediately. Network permissions can even be revoked for the purpose of this test.

Forum discussion: https://discuss.grapheneos.org/d/1520-mitid-stopped-working-urgent-help-needed

**Comment by thestinger** [comment]
This app is deliberately going out of the way to prevent itself from being used. It's not valid as a bug report. If you or others in Denmark want the app working, you'll have to determine why it doesn't work and resolve it. The moment they stop using their homegrown checks and switch to Play Integrity, that's over.

**Comment by thestinger** [comment]
No way for us to test this and we're not rolling back correct improvements even if we did identify what caused it. I'm not convinced it was caused by an update with no relevant changes though.

**Comment by thestinger** [comment]
Someone has tested this and found it works for them with and without sandboxed Google Play on a Pixel 6 on the latest release. It could simply be a bug in the app.

**Comment by lbschenkel** [comment]
> Someone has tested this and found it works for them with and without sandboxed Google Play on a Pixel 6 on the latest release. It could simply be a bug in the app.

I'm sure it's a bug in the app, as it's states that the device is "rooted" when it's not. I'm not trying to assign blame to GrapheneOS, I'm pleading the developers to help narrowing down the change that caused this despite that the blame is with the app due to the reasons I explained in https://discuss.grapheneos.org/d/1520-mitid-stopped-working-urgent-help-needed/19

I'm totally invested in doing whatever I possibly can, but I will need some guidance regarding what I can do to help.
