### ISSUE TITLE
Track last successful check for updates/error out when check failed?

### ISSUE THREAD

**Issue by Peter-Easton** [GrapheneOS/os-issue-tracker#161]
One of the Matrix members mentioned in the chat room that they'd been accidentally running an older version of the operating system until checking the releases page manually, even after tapping "Check for updates" manually. It looks like they had some proxy settings set with Orbot and that may have interfered with it and caused the update check to fail silently. 

If the update client can't reach the update server when it's time to check for an update, would it be advisable to get the update client to fail loudly rather than fail silently and produce a "cannot reach the update server" error when an update is requested.

Some advantages I see of this approach is that it provides immediate feedback and lets the user know when their proxy settings for any reason aren't letting the phone reach the update server. Some disadvantages I could see of this approach would be that it continues to rely on user interaction, with the associated Pandora's box of shifting the responsibility back onto the user and desensitizing them to the error messages. 

Another option that occurred to me might be to take the approach that the Factory OS does, and keep a record of the last successful check for an update in the update client. 

An advantage I could see of this approach is that it could be made much quieter and also it'd let the users know when their device is out of date without having to nag and desensitize them to warnings. 

Neither of these options are mutually exclusive. 

What do you guys think?

**Comment by renlord** [comment]
addressed in https://github.com/GrapheneOS/platform_packages_apps_Updater/pull/14

**Comment by jpds** [comment]
> Another option that occurred to me might be to take the approach that the Factory OS does, and keep a record of the last successful check for an update in the update client.

There should definitely by a row in the "System update settings" that shows when the last check was carried out. :+1:

**Comment by thestinger** [comment]
There's now much more visibility into this. It could be improved more but I'm fine with the approach for now.
