### ISSUE TITLE
Significant image degradation while editing screenshots in gallery app

### ISSUE THREAD

**Issue by fenndev** [GrapheneOS/os-issue-tracker#1610]
While editing screenshots in the Gallery app, I've noticed a large amount of text blur/smearing. I've tested this with photos that I've taken as well as other text-based images, but cannot replicate the issue with anything other than a screenshot.

Here's a [link](https://imgur.com/a/VpG66xZ) so you can see an example of what I mean.

**Comment by thestinger** [comment]
Known issue AOSP Gallery. It's not our Gallery app and while we'll accept a proper patch for this we won't accept issue reports for the lack of features and poor way it does things like this. A long time ago, someone submitted a patch, but without a proper explanation or response to code review.
