### ISSUE TITLE
Android For Work via VMWare Intelligent Hub does not work on Graphene

### ISSUE THREAD

**Issue by ixanza** [GrapheneOS/os-issue-tracker#1612]
I am on a Pixel 6 Pro. 
My company uses gsuite and VMware Workspace One to setup a work profile with certs. The setup doesn't get to be completed because the work profile created does not have any play services. 

For this to work I believe Graphene would need to be able to set up play services on the work profile without installing apks manually as the work profile created from the app doesn't have a browser or any way to install apks 

Would something like this be a possibility in Graphene in the future?

**Comment by thestinger** [comment]
There's "install available apps" for multiple users which could in theory be extended to the work profiles, but there are work profile apps already supporting that. It seems the issue is that this one doesn't support it before it expects stuff to be there.

**Comment by ixanza** [comment]
Yeah. There's a retry button I can tick at any point before doing an enterprise wipe which deletes the work profile so maybe they "install available apps" could still work. 

Work profile gets created> Next step fails> Install available apps> Retry.

**Comment by thestinger** [comment]
You could work around it with ADB for now.

**Comment by thestinger** [comment]
Not a GrapheneOS issue. We can consider adding new features in the future.
