### ISSUE TITLE
Default gallery app shows screenshots as blurry on first open

### ISSUE THREAD

**Issue by spogulis** [GrapheneOS/os-issue-tracker#1613]
Phone: Pixel 6 Pro

Issue: When creating a screenshot with "Power + vol down", the screenshot is created. When clicking on the thumbnail in the left corner, gallery app opens by default if none other is installed and the image is blurry. Doesn't happen if opened via other gallery app or if closed and reopened with the stock app.

**Comment by thestinger** [comment]
Known limitation of AOSP Gallery.
