### ISSUE TITLE
Black homescreen with Muzei live wallpaper after reboot

### ISSUE THREAD

**Issue by tw-hx** [GrapheneOS/os-issue-tracker#1614]
Running GOS latest on a Pixel 6 Pro. This issue has occurred under Android 13; never noticed it on Android 12.

After rebooting, the system shows a normal lockscreen and prompts to enter password onscreen to unlock as expected. It then unlocks, the homescreen wallpaper shows, but widgets and icons don't appear. To the top left of the statusbar an icon looking like a cog/chainring with a "T" inside its lower half appears. If this icon disappears the homescreen generally displays OK; on about half the first boots however the icon disappears and the homescreen switches to entirely black. I can still swipe down the statusbar and interact with Quick Settings etc., and the navbar pill is visible at the bottom of the screen but nonfunctional. No visible crash notices are displayed.

I then reboot the phone via the power menu; sometimes it reverts to the previous OS release in the old slot, and other times (like today, on 20221028) boots the new OS release normally and it works like nothing was ever the problem. I've not had this occur on manual reboots but don't do those often.

I've attached a logcat of "Error" severity messages obtained today after the crash; no visible "Fatal" messages were recorded. In terms of non-standard setup, I had the old settings provider model enabled on Android 12 to use separate wifi/cell toggles, but have since reset my QS tiles on A13 which made no difference. Device isn't rooted and system is stock. Hope this helps!
[error.log](https://github.com/GrapheneOS/os-issue-tracker/files/9895551/error.log)

**Comment by thestinger** [comment]
I think you just need to wait longer for it to load.

**Comment by tw-hx** [comment]
The attached logfile to the above post runs for 20 minutes after boot; the homescreen doesn't fix itself in that period. And after some first boots the homescreen appears in seconds as expected. It's definitely some kind of intermittent bug, potentially in the GrapheneOS launcher.

Will experiment; I'm using the Muzei live wallpaper app from F-Droid and perhaps this is triggering an issue somehow.

**Comment by tw-hx** [comment]
For what it's worth I disabled the Muzei live wallpaper, and an upgrade went fine today (not conclusive as bug only appears ~50% of the time).

**Comment by tw-hx** [comment]
More data -- did half a dozen updates since the above post with plain JPEG backgrounds, all went well. Three updates with Muzei active on home+lockscreen, and one of those three blackscreened.
Any other brave souls want to [install it](https://f-droid.org/en/packages/net.nurik.roman.muzei/) to see if it can be replicated?

**Comment by quamok** [comment]
> More data -- did half a dozen updates since the above post with plain JPEG backgrounds, all went well. Three updates with Muzei active on home+lockscreen, and one of those three blackscreened. Any other brave souls want to [install it](https://f-droid.org/en/packages/net.nurik.roman.muzei/) to see if it can be replicated?

I'm having the same issue with Muzei enabled. If I disable it, the black screen at reboots after OS update aren't an issue.

**Comment by tw-hx** [comment]
Thanks for confirming! This could be a potentially severe bug; forcing a reboot after it occurs sometimes comes up with the new OS version and sometimes the old version (both boot fine on the second attempt). If the upgrade involves a new bootloader with anti-rollback protection incremented (e.g. the Android 13 one), that could brick the device?

Hope @thestinger enjoys artwork 😉️. Here's the [Play Store link](https://play.google.com/store/apps/details?id=net.nurik.roman.muzei) if preferred to F-Droid.

**Comment by thestinger** [comment]
> Thanks for confirming! This could be a potentially severe bug; forcing a reboot after it occurs sometimes comes up with the new OS version and sometimes the old version (both boot fine on the second attempt). If the upgrade involves a new bootloader with anti-rollback protection incremented (e.g. the Android 13 one), that could brick the device?

No, that's not how upgrades and anti-rollback work at all. The anti-rollback indexes for firmware and the OS are only incremented after rollback has been disabled. Rollback isn't disabled until the progress bar shown for the post-upgrade process finishes.

**Comment by thestinger** [comment]
If you reboot before that progress bar finishes, it's supposed to roll back the upgrade. That's how the A/B update feature works when atomic data rollback is supported via the f2fs checkpoint disable feature. If that feature isn't available, the cutoff is early in the boot process right before it mounts the data partition and starts modifying it with the new OS version including migrating things to the new OS version format but otherwise it works the same way.

**Comment by thestinger** [comment]
Seems to be a problem with Muzei that may not be specific to GrapheneOS. Has anyone seen this issue occur outside GrapheneOS?

**Comment by tw-hx** [comment]
Couldn't find anything on Muzei's Github issue tracker mentioning it; I presume if it were a generic Android 13 issue it'd affect other users there. Can confirm that #1875 is the same issue as this one.

**Comment by thestinger** [comment]
That assumption is wrong.

**Comment by tw-hx** [comment]
Issue is still present, but I've found you can fix it without a reboot by:

1) Swiping down notification shade all the way
2) Tap cog for Settings
3) Display -> Wallpaper
4) Set wallpaper to a static image

Launcher3 then displays a homescreen and phone is usable. Hope this helps.

**Comment by tw-hx** [comment]
The [Android 13 QPR3 beta 3 changelog](https://developer.android.com/about/versions/13/release-notes) may fix this as it includes:

- Fixed an issue that could sometimes cause the system to get stuck on the home screen with no app icons and either the normal background or a blank, black background.
- Fixed an issue where the system UI crashed when trying to access the Wallpaper & style screen both in the system settings app or by long-pressing from the home screen.

The second fix sounds like #2063 which is already tagged as "upstream".
