### ISSUE TITLE
Ethernet Connection / USB Preferences

### ISSUE THREAD

**Issue by Hyper-Unknown** [GrapheneOS/os-issue-tracker#1616]
ETHERNET CONNECTION
I am currently testing the newest version of GrapheneOS on the new Google Pixel 7 Pro, the device is not connecting to internet through ethernet cable, it recognize the cable as a charger and rather than getting data it only tries  to charges it self.

USB PREFERENCES
When connecting the 7 Pro by USB-C to my computer the device blocks USB preferences by default blocking the option to choose between ( Connected device / This device )  it stays always on ( Control by Connected device ) even though when I only want to charge the Pixel 7 Pro off my computer and it gives the computer full access to the device.

Thank you for reading and technical support !

**Comment by thestinger** [comment]
That's not how USB works. Connected mode is for controlling how the phone acts as a USB device, not a peripheral. Please read the info on our site. If you have questions please ask them in the forum or Matrix chat.

**Comment by Hyper-Unknown** [comment]
Yes We do completely understand that, What We are trying to explain is that We are not able to control the device as how it acts when connected to USB Type-C.

When We connect the device to our desktop OS, We are not able to charge just the phone but rather it gives full access to the device, making it a security flaw when connecting let's say to a USB charge station at the airport, due to this issue We are not able to choose the option ( Not data transfer ).
Our colleagues at Hyper-Unknown.World have tried 10 different cable brands all of them ending with the same issue.
Now redacting all of the mention above the options for ( USB control by ) inside GrapheneOS are permanently grey out making it impossible for the user to select their prefer option.

Besides the above issue, the Pixel 7 Pro is not responding to ethernet connections, the Pixel 7 Pro works perfectly when connected to WIFI, but when connected through ethernet the Pixel 7 Pro reads the signal as a charger cable, rather than as it suppose to, which is getting the phone online.


We have tried this on the Pixel 7 Pro with stock OS and it does not seems to have any issues at all.

Thank you for answering our report, good luck !

This conversation is being recorded and will be available to the public at hyper-unknown.world social media platforms

Hyper-Unknown.World

------- Original Message -------

**Comment by thestinger** [comment]
Control by connected device does not mean what you think. You're misinterpreting the UI. It doesn't mean the device has any access.
