### ISSUE TITLE
Can't adjust call volume in dialer

### ISSUE THREAD

**Issue by Syberkonda** [GrapheneOS/os-issue-tracker#1620]
Exactly what it sounds like. I cannot adjust the volume of a call in the stock phone app. Pixel 6 Pro, build number TP1A.221005.002.2022102800.

**Comment by thestinger** [comment]
Volume is controlled at the OS level, not within the app.

**Comment by Syberkonda** [comment]
> Volume is controlled at the OS level, not within the app.

When I adjust the system call volume, that change is not reflected in the actual volume of a call.

**Comment by thestinger** [comment]
There are different volumes.
