### ISSUE TITLE
Double-line clock option in settings didn't work

### ISSUE THREAD

**Issue by KagurazakaSetsuna** [GrapheneOS/os-issue-tracker#1621]
Turning off the double line clock option in lock screen settings did not work.

Expected result: A single line clock is shown on the AOD and lock screen

Actual result: A double line clock is shown even when the toggle is turned off

OS version 2022102800
![Screenshot_20221103-164358](https://user-images.githubusercontent.com/44059716/199679576-5c9b9cd8-970a-4aae-ac8b-c43efbba329a.png)
![Screenshot_20221103-164401](https://user-images.githubusercontent.com/44059716/199679601-d1d37399-3709-439c-ab8d-b7b58130e052.png)

**Comment by thestinger** [comment]
Did you reboot? This is a known AOSP deficiency, not GrapheneOS specific.
