### ISSUE TITLE
Custom Icon Support ?

### ISSUE THREAD

**Issue by Taero6** [GrapheneOS/os-issue-tracker#1624]
Will there be support for custom icon packs in the near future?

**Comment by thestinger** [comment]
No. There's already Android 13 themed icon support for the home screen though and Android will probably support that for the rest of the OS in the future..

**Comment by ThatOneCalculator** [comment]
Could you reconsider this issue? The stock launcher is by far the smoothest, but not being able to choose an icon pack is not great.

**Comment by thestinger** [comment]
No.

**Comment by ThatOneCalculator** [comment]
Any reason why not? Most custom launchers have this functionality, and I can't think of a good reason not to add it.

**Comment by thestinger** [comment]
It's not what we work on in GrapheneOS.

**Comment by ThatOneCalculator** [comment]
I'm sorry, but that doesn't really seem like sound reasoning.  "It's not what we work on in GrapheneOS" is so vauge, is what you're not working on user customization? Listening to feedback? Adding features you personally wouldn't use?

**Comment by thestinger** [comment]
The feature is available via custom launchers. It doesn't need to be added by us to be available.

**Comment by thestinger** [comment]
GrapheneOS exists to develop privacy and security improvements along with alternatives to things like Google Play services. We aren't trying to add a bunch of additional customization. You can use your preferred launcher. If someone wants to make a fork of the AOSP Launcher with our minor changes and icon packs, they can do that, and people can use it without us shipping it. It doesn't need to be part of the OS.

**Comment by ThatOneCalculator** [comment]
Except that Launcher3 is the best integrated with the system by far, and the closest thing now (Lawnchair) is officially discontinued. I can't understand the apprehension to adding a basic feature :/
