### ISSUE TITLE
Empty/ghost app name and icon in Battery Usage settings

### ISSUE THREAD

**Issue by qcasey** [GrapheneOS/os-issue-tracker#1626]
TD1A.220804.031.2022102800

I have AOD and the suite of Google Play Services sandbox enabled, although Ambient Display appears further down the Usage list. 

![Screenshot_20221103-131918](https://user-images.githubusercontent.com/1429672/199825724-577003a1-cf2b-4d93-9461-8102e6f460c1.png)

![Screenshot_20221103-131931](https://user-images.githubusercontent.com/1429672/199825735-c2928eea-4570-4e47-916c-af72f739cff9.png)

**Comment by thestinger** [comment]
It's a known issue likely inherited from AOSP.
