### ISSUE TITLE
Crash after sys update on Pixel 4a

### ISSUE THREAD

**Issue by Andforyou1666** [GrapheneOS/os-issue-tracker#1630]
Sandboxed google services in separate profile.

```
type: crash
osVersion: google/sunfish/sunfish:13/TP1A.221005.002/20221028xx:user/release-keys
package: com.google.android.gms:xxxxxxxxx
process: com.google.android.gms.persistent

java.lang.SecurityException: You need MANAGE_USERS, CREATE_USERS, QUERY_USERS, or GET_ACCOUNTS_PRIVILEGED permissions to: get user name
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3021)
etc......

```

**Comment by thestinger** [comment]
Please search before filing an issue. You caused this issue by updating Play services with Aurora Store. It has nothing to do with an OS update. You're only supposed to update Play services via our app repository client and optionally the Play Store itself. Updating to GmsCompat config v14 and rebooting would resolve this specific issue for you but you aren't meant to be on this version of Play services yet.
