### ISSUE TITLE
Sim not registering in 3rd party app

### ISSUE THREAD

**Issue by Minerme** [GrapheneOS/os-issue-tracker#1636]
I have installed an app to manage sim “SIM card changer notifier” but it is not registering the SIM card. 

How can we we give the 3rd party app access to read the sim used? When I insert the sim the app shows blank for sim registered. Can I add the app to a whitelist to allow it to read the sim?

any help is much appreciate

**Comment by akc3n** [comment]
@Minerme not sure what specific app that is as there are many returned search results. It would be help to provide the exact source of where you go the app included a link that apps profile. 

From what I've gathered based only on assumption is that these types of apps are quite dated (2014-2018)....

Suggest reading https://grapheneos.org/faq#hardware-identifiers
And providing more details.

However, third-party app issues should be directed to their developers.

**Comment by Minerme** [comment]
Thanks for the reply.
The link to the app is below. I have read that link you provided and it indicates that only system apps get access to the hardware identifiers. 

Is there a way to easily add the app to allow to read the sim identifier?

https://m.apkpure.com/sim-card-change-notifier/instigate.simCardChangeNotifier

thanks

**Comment by akc3n** [comment]
@Minerme This won't work.
> SIM Card Change Notifier 
> Version 3.2.4
> _Updated on_: _**2018**_-10-05

Close #1636
