### ISSUE TITLE
Wallpaper alignment issue on secondary user profiles

### ISSUE THREAD

**Issue by gittyhubby-sex** [GrapheneOS/os-issue-tracker#1637]
The pictures are misaligned and zoomed regardless of the picture's size, not correctly displayed as the wallpaper preview page
![Screenshot_20221104-223356.png](https://user-images.githubusercontent.com/117465250/200109609-cf5baea8-d4a4-4acc-8738-79bfaeafe2f3.png)![Screenshot_20221104-223347.png](https://user-images.githubusercontent.com/117465250/200109603-d5ad4b72-6505-464b-ac47-b7757b749c2f.png)

**Comment by thestinger** [comment]
https://github.com/GrapheneOS/os-issue-tracker/issues/1633
