### ISSUE TITLE
"Voice" audiobook player crashes System UI

### ISSUE THREAD

**Issue by Olexorus** [GrapheneOS/os-issue-tracker#1638]
When using the "Voice" audiobook player, the system UI repeatedly freezes with the error message "System UI isn't responding". At first it's not obvious that using this app is causing this, because the error message doesn't mention the app, the app itself keeps working, and it takes a while after starting to use the app for this to happen, so at first it seems like just an unrelated OS problem.

Someone else made a bug report for this to the repository of the app, however it was closed there because it seems to be specific to GrapheneOS, and as far as I can tell noone else has reported it here: https://github.com/PaulWoitaschek/Voice/issues/1486

**Comment by thestinger** [comment]
No indication that this is caused by GrapheneOS. It's likely an issue occurring on Android 13 in general. We can't track upstream app issues here.

**Comment by arjan-s** [comment]
Too bad this issue is closed, as it's still a problem. Voice fully crashes my phone, making it reboot. Both GrapheneOS (2024121200) and Voice (8.2.3) are fully up to date
