### ISSUE TITLE
Pixel 7 Request...

### ISSUE THREAD

**Issue by citynetcomputing** [GrapheneOS/os-issue-tracker#1639]
More of a request than an issue:

Change text app default color. Green sucks... lol
Change brightness to full when playing videos.

Pixel 7 - Everything else works great! Keep up the great work!!

**Comment by thestinger** [comment]
> Change brightness to full when playing videos.

That's up to the app. You can use an app with custom brightness.

> Change text app default color. Green sucks... lol

We have no plans to develop our own texting app or to take over development of AOSP Messaging. You can use a different app if you don't like it. If we had our own app it would use the Material You system theme.
