### ISSUE TITLE
Sandboxed Google Play keeps crashing

### ISSUE THREAD

**Issue by CloudsClinic-IT** [GrapheneOS/os-issue-tracker#1640]
Dear Graphene-OS development-team

Since the 3rd of November, i am having the issue, that all of the common apps i use, keeps crashing after i tried to start them. It is not a pattern of apps, they are fully random. sometimes it is the Mailprogram, sometimes social media, sometimes online-shops and even the banking-apps are crashing.

After the apps starts, it take 0.5 - 3 seconds to crash the app. The Error: "Sandboxes Google Play keeps crashing, tap to see the details" displays it constantly

The Error:
[Sandboxed Google Play Crash-Error-Details.txt]
(https://github.com/GrapheneOS/os-issue-tracker/files/9944545/Sandboxed.Google.Play.Crash-Error-Details.txt)

Please inform me, if you need any more informations

Regards

a thankful OS-User :)

**Comment by thestinger** [comment]
You aren't supposed to update Play services and the Play Store with Aurora Store. You updated to a newer version than what's supported by the compatibility layer. You're only supposed to update them via our app repository client and optionally also through the Play Store itself. The issue you're reporting was resolved by GmsCompat config v14 but you haven't updated to it.
