### ISSUE TITLE
music stops playing after a few seconds after display is turned off when listening through USB-C earphones

### ISSUE THREAD

**Issue by b3K1ndRw1nd** [GrapheneOS/os-issue-tracker#1643]
Approximately a week or so ago, I found that if I have some music playing (I use the app https://github.com/AdrienPoupa/VinylMusicPlayer) and I turn off the display, the music coming in through the headphones stops. I have to turn the display back on, unlock the phone, disconnect and re-connect the headphones and then pause and re-play the song again to get it to resume.

I was going to see if the logs might shed light on what is going on but then realized that given that Pixels have only 1 port, I was not actually sure how to see the logs via `adb logcat` while duplicating the issue with my earphones.

I tried with https://github.com/OxygenCobalt/Auxio as well and same issue

This is happening on a Pixel 6 running Android 13

**Comment by SigmaBonder** [comment]
> given that Pixels have only 1 port

Have you considered using a splitter? You would have to find one that handles two full-fledged USB devices, not just one device and power delivery, but there have to be some.

**Comment by b3K1ndRw1nd** [comment]
I've tried to find a splitter that allows one port to support data transfer and one to support headphone usage. Wasn't able to.

I will note that this issue is not occurring on my Pixel 4 and that is also running grapheneOS, so this seems to be isolated to Pixel 6 for the time being.

**Comment by thestinger** [comment]
@b3K1ndRw1nd Logs are persistent. You can clear all the logs with `adb logcat -c` to have a fresh slate, replicate the issue and then use `adb logcat`. There's no particular reason you need to be running it at the same time as replicating the issue.

**Comment by b3K1ndRw1nd** [comment]
probably should have realized that myself but thanks for letting me know :sweat_smile:

**Comment by maade69** [comment]
@b3K1ndRw1nd can you provide information about the DAC you're using?

**Comment by psz1234** [comment]
I use three different DACs. They all work on Pixel 6. No problems on any ROM except GOS.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by thestinger** [comment]
@psz1234  Please stop posting noise in this thread / elsewhere. Final warning.

**Comment by psz1234** [comment]
I won't post anymore, but I use GOS and I donate to the fund monthly. I have discovered a bug and just wanted to report it. If you just want to ignore your supporters, I guest that' your prerogative.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by b3K1ndRw1nd** [comment]
@psz1234 I get the feeling your comments got removed cause you were inadvertently spread misinformation, and also cause you added nothing to the discussion. Paying monthly does not give you the license to do that.

**Comment by SigmaBonder** [comment]
@b3K1ndRw1nd We probably shouldn't continue this topic, but I'm curious: what misinformation are you referring to?

**Comment by unoexperto** [comment]
I'm on Pixel 6 with Android 13 (build TQ2A.230305.008.E1). After today's security update all my DACs stopped working when screen is locked. I tested with iBASSO DC-03 Pro and two other tiny DACs.

I also confirm that changing default USB setting in Dev Options from "File Transfer" to "None" is workaround. But I've always had "File Transfer" mode on before FOR YEARS.

**Comment by thestinger** [comment]
Please reset developers options to default by toggling it off. Changing that setting is broken.
