### ISSUE TITLE
Add VPN access support for Hotspot device(Feature Request)

### ISSUE THREAD

**Issue by Che15ea** [GrapheneOS/os-issue-tracker#1644]
Hello
I found that Grpahene OS device cannot share VPN access through hotspot(wifi or tether). I wish that Graphene OS will be able to add this function so it is possible to share the VPN on my laptop.
Thank you!

**Comment by thestinger** [comment]
This is a duplicate and sharing the same VPN tunnel between multiple devices is counter to the privacy goals of GrapheneOS. It's more private to make a separate tunnel for each one. There are per-profile VPNs already, so why would we take a major step backwards and even start using them across whole devices?
