### ISSUE TITLE
Preinstall F-Droid

### ISSUE THREAD

**Issue by Che15ea** [GrapheneOS/os-issue-tracker#1645]
Hello
I think it would be helpful to preinstall F-Droid (or let the user choose whether to install) and privilege extension so it is much easier to download apps automatically after flashing the System. I believe F-Droid is an essential app for every user.

**Comment by thestinger** [comment]
That's not happening and it's definitely not an essential app. F-Droid has severe usability and security issues. We don't recommend it as a source of apps...
