### ISSUE TITLE
Proximity sensor broken after setting up

### ISSUE THREAD

**Issue by qdrop17** [GrapheneOS/os-issue-tracker#1646]
Hi there.

I installed GrapheneOS on a Pixel 6 Pro. After installing my apps and transferring my data I noticed that the proximity sensor was not working anymore.

I installed a diagonstics app and it showed 5cm distance all the time even I was covering the screen with my palm.

Before opening this issue, I decided to reset the phone to factory settings to test that. Surprisingly this worked. But it's still an OS bug because why would an app be able to decalibrate the proximity sensor?

I switched off sensor access by default but expect that apps that need it (phone for instance) should do fine when enabling it nevertheless. What I did not expect is to break it systemwide.

Any help is highly appreciated. I'm running the newest version of GrapheneOS as of this date.

**Comment by thestinger** [comment]
This doesn't sound like a software issue but rather a hardware issue such as a screen protector incompatible with proximity sensors. No other reports of any issues with this other than people using broken screen protections. Make sure you didn't revoke Sensors access from system components.
