### ISSUE TITLE
Some configuration is reset after system update

### ISSUE THREAD

**Issue by sebastianha** [GrapheneOS/os-issue-tracker#1652]
Hi,

after updating to TD1A.220804.031.2022110600 I noticed that some settings have been reset or changed. Especially in the "Special App Access" category I had to restore some settings. At least the following items are affected:

- Wi-Fi control: All changed to allowed
- Install unknown apps: All were removed
- All files access: All were removed
- VPN permission had to be given again (Wireguard did not work from the quick menu until I went to settings and gave my permission again)

Other users suspected system reboots are causing this but this is nothing I could reproduce so I think it is related to system update or at least this specific update.

Here is the thread in the forums: https://discuss.grapheneos.org/d/1649-special-app-access-keeps-resetting-to-allow

Thanks for this great operating system, keep up the good work!

**Comment by thestinger** [comment]
This is a known upstream issue with special access grants. There are existing issues filed. It occurs on the stock OS too. GrapheneOS just has much more frequent updates.

**Comment by sebastianha** [comment]
Thanks for the quick answer!

Is known what exactly is all reset after a system update?

**Comment by thestinger** [comment]
Special access grants are sometimes reset due to an AOSP bug we haven't figured out yet.

**Comment by thestinger** [comment]
Special access grants are sometimes reset after updates due to an AOSP bug we haven't figured out yet. Normal permissions don't get reset.
