### ISSUE TITLE
Speaker don't work while making a phone call

### ISSUE THREAD

**Issue by j4nnnn3s** [GrapheneOS/os-issue-tracker#1656]
So i can't make a phone call using the phone in a "traditional" way (holding it next to your head😂). The speaker on the top of the phone only work after every second system update for a few minutes after rebooting but not consitantly. I would really appreciate some advice on what I should try to fix it (haven't found the issue anywhere else). I'm using a Pixel 5 with the latest GrapheneOS version.

Thanks in advance

**Comment by thestinger** [comment]
This is almost certainly a hardware issue and outside our control. The connection to the top speaker is likely loose which is why your other speakers still work.
