### ISSUE TITLE
would you bring back battery saver limit to 5%?

### ISSUE THREAD

**Issue by o13e** [GrapheneOS/os-issue-tracker#1665]
hello, this A13 commit changed the minimal value for the automatic battery saver to 10% instead of 5% and it's frustrating to the point that now i just disable the automatic battery saver because 10% is too much for my usage. thanks

https://github.com/GrapheneOS/platform_packages_apps_Settings/commit/878dae3db0bf5e84faa58bd58a3b4e21fa9380e2

**Comment by thestinger** [comment]
We don't want to change the default but it could become configurable at some point. Not planned by us though.

**Comment by thestinger** [comment]
Ah, I see.
