### ISSUE TITLE
VPN permission / App store premissions gone after reboot (sometimes)

### ISSUE THREAD

**Issue by joeyboon** [GrapheneOS/os-issue-tracker#1677]
Hi,

I currently run GrapheneOS version TP1A.221105.002.2022110800 on a Pixel 6. Sometimes when I reboot the device VPN app permissions or App store permissions are reset. Because I run NetGuard as a firewall this causes network issues at boot. I need to approve all VPN apps again and when installing updates to apps need to allow the permission "Allow install from this source" again. Any idear why this is happening? If you need more information let me know!

**Comment by thestinger** [comment]
It's a known AOSP issue. Special access grants can be reset after an OS update in certain configurations. There have been multiple issues filed about it upstream. It happens more often on GrapheneOS simply because we have updates every few days or every week instead of only monthly.

**Comment by thestinger** [comment]
It's being worked on.
