### ISSUE TITLE
Battery ussage by system high

### ISSUE THREAD

**Issue by joeyboon** [GrapheneOS/os-issue-tracker#1678]
I'm on build: TP1A.221105.002.2022110800 on a Pixel 6.

After one of the last updates my phone is hotter then normal and my battery drains faster then normal. On the battery usage statistics page system (at least an Android icon) seems to be the  culprit (see screenshot at link below). Any ideas on what's causing this? Rebooting does not solve the issue. 

https://cloud.netjoe.nl/index.php/s/FTNRTH8R8ktYiF6

**Comment by thestinger** [comment]
It's not caused by an update and battery statistics being marked that was is a known AOSP issue and not a bug in GrapheneOS or something that occurred in a recent update. You'll need to resolve your app issue that's causing battery drain.
