### ISSUE TITLE
Note: VPN settings defaulted to blocking connections by default without VPN, breaking split setups

### ISSUE THREAD

**Issue by ilikenwf** [GrapheneOS/os-issue-tracker#1682]
I just finally narrowed this down, but my always on VPN settings (wireguard) with the latest beta channel update today defaulted itself to blocking connections not using the VPN - may want to make a note for this somewhere in case people have issues, or not default this setting to on for existing VPN connections (or maybe prompt?).

**Comment by thestinger** [comment]
Not sure why that would happen. It's not specific to the latest update. We've set it as the default for a while. Maybe your previous VPN settings were lost.
