### ISSUE TITLE
When leaving home wifi, 5G has no Internet connection without workaround

### ISSUE THREAD

**Issue by yaomtc** [GrapheneOS/os-issue-tracker#1683]
I've been having issues with mobile data for a few days. When I leave home and go out of range of my wifi, it can't connect to 5G. Restarting my Pixel 4a (5G) does not change anything. Only one workaround I've found: switching from 5G to LTE, then back to 5G. 

While the issue is occurring, the signal bar has a ! on it.

The workaround works until I restart the phone.

I've tried resetting APNs to default, but that didn't change anything.

After I use the workaround, if I then reconnect to the same wifi I disconnected from, and then disconnect from it, the problem doesn't come back at that point. Time might be a factor? Or connecting to a different wifi network?

**Comment by thestinger** [comment]
Unable to reproduce this issue and other users don't appear to have it. Could be a hardware problem. Very unlikely that it's GrapheneOS specific and you have to narrow it down as not being a carrier related issues by trying another carrier.

**Comment by yaomtc** [comment]
Nothing changed with my wifi router, and my phone hasn't been dropped or anything recently so I don't think a hardware issue is likely... GrapheneOS is the only thing I know of that has changed, what with updates, but if nothing's changed with it and 5G connectivity recently, maybe the local 5G has an issue? Maybe I'll ask Mint Mobile about it.
