### ISSUE TITLE
Regular deletion of "Special App Access" - Pixel7Pro

### ISSUE THREAD

**Issue by esntngv** [GrapheneOS/os-issue-tracker#1687]
I use several apps on my Pixel7Pro that have permission to install apps, such as AuroraStore, NeoStore/F-Droid, but also Signal, Vanadium and others.
The problem is, I give permission, which works, but then an hours / days later the permission is gone again, so for example with AuroraStore I have already given permission at least 5-10 times, such a problem was not existent with the Pixel6. I do not know yet exactly how much time passes until GrapheneOS reverses the permission.

Also "access to all files" keeps resetting, other permissions could be affected too, it's extremely annoying as for example in VLC I regularly lose my playlists due to lack of file access permissions.

**Comment by esntngv** [comment]
Other users also report this, see: 
https://discuss.grapheneos.org/d/1661-several-problems-with-grapheneos-and-pixel7pro

**Comment by thestinger** [comment]
Has already been filed repeatedly and is an upstream issue not a GrapheneOS issue. You need to search the tracker before filing.

**Comment by esntngv** [comment]
> Has already been filed repeatedly and is an upstream issue not a GrapheneOS issue. You need to search the tracker before filing.

Thanks for the comment, can you point me to where this upstream issue can be found?
I'm not very familiar with it unfortunately.

**Comment by thestinger** [comment]
No, I can't do a search for you.

**Comment by thestinger** [comment]
There were multiple issues filed about this here. You'll have to search and filter through the duplicates.
