### ISSUE TITLE
LTPO display of the Pixel7Pro works exclusively with 60hz or 120hz

### ISSUE THREAD

**Issue by esntngv** [GrapheneOS/os-issue-tracker#1688]
The Pixel7Pro has an LTPO display and should thus be able to switch variably between 10hz-120hz. If you activate the "Show refresh rate" function in the developer settings, where the current frame rate is displayed at the top left, it switches exclusively between "60Hz" and "120Hz". It never goes lower than 60hz, so if the numbers are correct, the LTPO display doesn't seem to work properly.

This problem is also described by others here:
https://discuss.grapheneos.org/d/1661-several-problems-with-grapheneos-and-pixel7pro

**Comment by pikatchu2k3** [comment]
Check this report on XDA, why the device itself can't show the correct refresh rate. 
https://www.xda-developers.com/google-pixel-7-pro-display-review/#lab-testing-display-refresh

**Comment by thestinger** [comment]
No sign of this not working as intended. Need evidence it doesn't work like the stock OS to have an issue open about it.
