### ISSUE TITLE
Uniform system processes icons

### ISSUE THREAD

**Issue by gordongw** [GrapheneOS/os-issue-tracker#1689]
All system processes (Android System, Bookmark Provider, Calendar, Calendar Storage, Carrier Default App, com.samsung.slsi.telephony.oemril.OemRilApp, Download Manager, Downloads, Live Wallpaper Picker, MusicFX, Phone and Messaging Storage, Phone Calls, Phone Services, RadioConfigService, Rcs Service, Search, Settings Storage, Settings Suggestions, Storage Manager, etc) could share the  
default icon:
![Default](https://user-images.githubusercontent.com/78707469/201537774-2197fe1b-7bbf-465e-bf4b-0f8e652ce918.png)
 It will improve and simplify that section of the GUI, ridding it of many outdated icons, while not adding complexity.

**Comment by thestinger** [comment]
Not planned.

**Comment by gordongw** [comment]
Ok, thank you.
