### ISSUE TITLE
Clipboard editor exposes passwords copied from a password manager

### ISSUE THREAD

**Issue by steel-steven-87** [GrapheneOS/os-issue-tracker#1690]
Android 13 has introduced a feature called clipboard editor which I think makes the use of a password manager less secure

When I'm in public, I cannot simply copy a password anymore because as soon as that's done, the clipboard editor appears:

![clipboard-editor-issue](https://user-images.githubusercontent.com/89798696/201540452-bec71ffe-a264-4f76-9590-34da00ae55f6.png)

**Comment by thestinger** [comment]
Apps are supposed to mark sensitive data they aren't displaying on screen as sensitive when copying it and it shows it censored in the clipboard notice. The clipboard notice is an important feature.

Password managers are supposed to take the approach of using the OS autofill API designed primarily for this use case and the proper way to provide a fallback for apps without support is providing a keyboard for inputting passwords. Your password manager is out-of-date and not using modern Android APIs which is not an OS issue.
