### ISSUE TITLE
Camera unavailable on Pixel 4a

### ISSUE THREAD

**Issue by bohlender** [GrapheneOS/os-issue-tracker#1694]
I've been using GrapheneOS on a Pixel 4a (sunfish) without any issues for some years now, but have recently started experiencing issues with accessing the camera. I'm currently using build `TP1A.221105.002.2022111000` but I think I've first noticed the issues sometime in September this year.

**The problem is that no matter which camera app I use the OS seems to report the camera as unavailable/closed**. In the default "Camera" app the screen stays black and switching to the rear camera reports _"Could not detect rear camera. Please try again later!"_. Not sure if it's relevant but the privacy dashboard shows that the right to use the camera, which I've granted to the default "Camera" app, has not been requested recently.

I've [recorded a video (70MB)](https://www.dropbox.com/s/frqquls73yayiv5/screen-20221114-202525.mp4?dl=0) to give you an idea of the issue I'm facing. I'm typically using the default "Camera" app but have installed "Open Camera" to understand whether I'm facing a bug of the "Camera" app or it's a lower-level issue which stops all camera apps from working.

The issue didn't bug me at first since it was not consistent -- restarting the device did seem to help. Nowadays restarting doesn't do the trick though.

Let me know if you need further information.

**Comment by thestinger** [comment]
This is a hardware failure.

**Comment by bohlender** [comment]
Thanks for your assessment. Given that the device was never dropped I didn't even suspect a hardware failure. However, now that you've hinted at the possibility, I've stumbled upon [reports suggesting this being a common issue](https://www.forbes.com/sites/paulmonckton/2020/09/29/google-pixel-camera-crash-problem-pixel-2-pixel-4/) :shrug:.
