### ISSUE TITLE
Turn off screenshot app sound

### ISSUE THREAD

**Issue by popogomo** [GrapheneOS/os-issue-tracker#1696]
The built-in screenshot app produces a sound every time a screenshot is captured by the user.

The only way to mute it is to turn off Ring and Notification volume but this also turns off ring and other notifications' sound.

Is it possible to add an option to disable screenshot sound so that there will be no sound when taking screenshots?

**Comment by Pauler221** [comment]
It's possible to do that.

Go to Settings -> Apps -> See all X apps -> press on three dots (top right) and then on "Show system" to show system apps -> System UI (or search for System UI) -> Notifications -> turn off Screenshots

**Comment by Pauler221** [comment]
> The built-in screenshot app produces a sound every time a screenshot is captured by the user.
> 
> The only way to mute it is to turn off Ring and Notification volume but this also turns off ring and other notifications' sound.
> 
> Is it possible to add an option to disable screenshot sound so that there will be no sound when taking screenshots?

It's possible to do that.

Go to Settings -> Apps -> See all X apps -> press on three dots (top right) and then on "Show system" to show system apps -> System UI (or search for System UI) -> Notifications -> turn off Screenshots

**Comment by JSchimmelpfennig** [comment]
Hi there,
I'm a new GrapheneOS user on my Pixel 6a and the screenshot sound annoys me aswell. I would love to be able to turn it off. Turning off the System UI notifications didn't turn off the screenshot sound.

**Comment by RecursiveCollapse** [comment]
Can confirm the issue. Followed the steps exactly, and the screenshot sound persists. In fact, it even persists if all notifications for System UI are blocked entirely. Having to mute ring and notification sounds results in occasionally forgetting to unmute, and subsequently missed messages. It would be fantastic if it was possible to disable this sound.

**Comment by r3g-5z** [comment]
Next release of GrapheneOS will make screenshot sounds follow the "Touch sounds" setting in Settings -> Sound & vibration -> Touch sounds.
