### ISSUE TITLE
Wireguard kernel?

### ISSUE THREAD

**Issue by Sn0whax** [GrapheneOS/os-issue-tracker#1700]
Would it be possible to implement wireguard at the kernel? My understanding is that its in the latest Linux kernels but google has chosen not to implement it in android.

Edit* I see there's some background with these requests. By adding the kernel modeule why wouldn't the app have access to it? Is this due to the sandboxing nature?

**Comment by thestinger** [comment]
That's not accurate and having the kernel module won't accomplish anything without userspace integration. Please don't file duplicate issues.
