### ISSUE TITLE
Option to remove references to Graphene OS when locked e.g boot  logo

### ISSUE THREAD

**Issue by Maio-msdos** [GrapheneOS/os-issue-tracker#1701]
When the duress password is available, it would be useful to have an option to remove any references that make it obvious that the user is using Graphene OS whilst the phone is locked e.g boot logo, so that a threat actor will not be aware of / able to look up the duress feature 

Thanks :D

**Comment by thestinger** [comment]
That's not going to be implemented. There's a screen showing it's an alternate OS with the key fingerprint.
