### ISSUE TITLE
Biometrics prompt delay between work and owner accounts

### ISSUE THREAD

**Issue by TheoKlizz** [GrapheneOS/os-issue-tracker#1702]
Pixel 7, the latest GOS installed. A work profile is configured via Shelter/Insular (both produce the same results). 

**Issue:**  

Open any biometrics-enabled app in Owner app. After that open any biometrics-enabled app in Work profile app. You will see the biometrics prompt will be delayed for 5-10 seconds. After this all apps in Work profile will instantly show biometrics window, however, if we try to open any app in Owner app, it will again have 5-10 seconds delay before showing the biometrics prompt. So biometrics prompt takes 5-10 seconds to load when opening apps between profiles (opening apps in the same profile doesn't cause this issue).

It seems the systems is "loading" biometric process for profile the app is located in and then uses that "process" for all apps in that profile so biometrics prompt opens instantly for all apps in that profile. But when we open an app in another profile, the system is  "loading" biometric "process" for that other profile and this takes 5-10 seconds to show the biometrics prompt.

Biometric prompt works instantly between profiles in stock OS both via Shelter and Insular.

**Comment by thestinger** [comment]
AOSP issue impacting stock OS too.
