### ISSUE TITLE
Apps in work profile are unable to act as the default SMS app.

### ISSUE THREAD

**Issue by MTPeyton** [GrapheneOS/os-issue-tracker#1704]
**Device:**
Pixel 4a running Android 13

**OS Build Number:**
TP1A.221105.002.2022111000

**Issue:**
My GrapheneOS is setup to have a main profile and a work profile. Only the work profile has sandboxed Google Play Services installed. I currently have the Beeper app (https://www.beeper.com/) (version 2.4.12) installed in the work profile. One of Beeper's features is that it can act as an SMS bridge for Matrix. In order to do this, it needs to be the default Android SMS app. However, when I try to set this up, it fails with a toast message that says "ROLE_SMS isn't available in this device".

![Screenshot_20221116-205733](https://user-images.githubusercontent.com/13069044/202361653-15159ff2-2043-40e7-b2e8-fb71f9ea1360.png)

**It looks like this might be a limitation inherent to Android.** See https://support.google.com/work/android/thread/169355596/sms-in-work-profile?hl=en and https://support.google.com/work/android/answer/6275589?hl=en This is also what Beeper support told me upon reaching out to them.

Additionally, cloning the app to my personal profile is not a solution. Since my personal profile lacks Google Play Services, it is unable to receive notifications. That means that Beeper, an app meant for instant messaging, would lose one of its core features.

Furthermore, I already tried installing the app in BOTH profiles. The personal one had notifications turned off. This also didn't work, as some SMS messages were not bridged. The Beeper support team mentioned that notification support was needed for the instance of the app receiving SMS messages, in order for those messages to be bridged to Matrix properly.

However, I figured I would still post about this issue here, in the hopes that maybe someone knows of a workaround... or if there are plans for GrapheneOS to support this use case in the future. (Doubt it... but can't hurt to ask.)

If there is no way around this, and no plans to support this in the future, then feel free to close this issue.

**Comment by thestinger** [comment]
This seems intended. I think you're better off asking on discuss.grapheneos.org. We definitely don't plan to change this since our focus is on user profiles, not work profiles, and we want to make them almost as usable as work profiles.
