### ISSUE TITLE
4g only mode doesn't work with Pixel 7

### ISSUE THREAD

**Issue by mollyuser** [GrapheneOS/os-issue-tracker#1705]
The 4g only mode does not work on a pixel 7, tested the sim card with multiple devices, to dismiss carrier issues. It works fine on older pixels with GOS. When the pixel 7 is set to 5g recommended, than 4g can be used, but switching it to 4g only breaks network and internet is lost.

**Comment by citynetcomputing** [comment]
I have P7 and have 2G and 5G disabled and mine works perfectly. Just an fyi.

**Comment by thestinger** [comment]
Not able to replicate. Not enough details provided to do any work on this.

**Comment by mollyuser** [comment]
What details would you need? If i put my pixel 7 on 4g only the internet does not work. Tge same sim card works perfectly with a pixel 6, and a 6a. Tried my friends device also and he has the same issue on rhe pixel 7. When you put 4g only mode on the internet is lost. What details can i provide more?

**Comment by mollyuser** [comment]
It s not about disabling 2g and 5g, have no idea how you do this but it about the 4g only mode. Only when u put 4g only this happens.

**Comment by mollyuser** [comment]
When u reproduce this, u have to put 4g only mode and after that try to use internet becauee the 4g mark will not dissapear immediatly. It only happens with pixel 7 i have tried several devices with the same sim card.

**Comment by mollyuser** [comment]
Well thanks a lot, this is a nice way to deal with issues. If you guys dont have the time to fix things just say that but dont act like the issue is not there. If u need more information than just say what u need so i can provide it. The 4g only mode doesnt work on a Pixel 7.

**Comment by thestinger** [comment]
4G only mode is working for other users on the Pixel 7 and Pixel 7 Pro. Your carrier may be broken when 3G support is disabled.

**Comment by mollyuser** [comment]
I have used 4g only mode with my carrier and same six for a year on the pixel 6, now i changed to pixel 7 and it s not working anymore. So your saying the carrier does not support google pixel 7 4g , and it does support it on a pixel 6 ? This is possible? When i change my sim back to my pixel 6 it eorks fine so this doesnt make sense.
