### ISSUE TITLE
Dark theme broken on notifications when...

### ISSUE THREAD

**Issue by mitchst2** [GrapheneOS/os-issue-tracker#1706]
Switching accounts from a light theme user back to a dark theme user account.

Broken
![Screenshot_20221117-205517](https://user-images.githubusercontent.com/118489659/202579999-41a4587c-ca66-45ce-a0ce-6cb0112048ce.png)

To fix issue shown in attached image theme needs switched dark>light>dark

Restored
![Screenshot_20221117-205538](https://user-images.githubusercontent.com/118489659/202580065-4e88ddeb-b8ed-4be4-9d8a-c0c14e0730f6.png)

**Comment by thestinger** [comment]
This is a known AOSP issue with existing issues opened here and upstream.
