### ISSUE TITLE
Permissions are withdrawn after update

### ISSUE THREAD

**Issue by basings** [GrapheneOS/os-issue-tracker#1707]
After each update, grapheneos withdraws permissions of apps. After each update I do not know which permissions were revoked and which service is not working properly anymore until I grant the permission again.
 
It does not withdraw all permissions of all apps, or all permissions of a kind, or all permissioms from specific apps, it appears to be random.

An example is syncthing which I had to grant storage permission again. 

- pixel 6
- A13 5 November update

**Comment by thestinger** [comment]
Known AOSP issue with special access permissions. Impacts stock OS too. Lots of duplicates filed already.
