### ISSUE TITLE
What is happening?

### ISSUE THREAD

**Issue by citynetcomputing** [GrapheneOS/os-issue-tracker#1708]
So i'm trying to figure this out and hoping someone has seen it or is familiar with the code to look at it in GOS.

Problem:
When adding a DNS-over-TLS server in graphineOS somehow that DNS-over-TLS address is pushed to Google and within two hours I am getting DNS-over-TLS recursion requests from Google DataCenter IPV4 and IPV6 addresses. I had to change the host name as since they were already blocked in adguard, the new hostname (dot2.mydomain.com) couldn't get pushed to them.

Steps to reproduce:

1. Create Fresh DOT server (Using AdGuard) at dot.mydomain.com
2. Apply dot.mydomain.com to GrapheneOS Internet settings under "Private DNS"
3. Wait about an hour.....
4. Watch DOT server logs and see 172.253.0.0, 74.125.0.0 and 2607:f8b0:4004:: start recursing. When I blocked 172, 74 started coming in then I block 72 and 2607 started coming in etc... All Google IP Blocks.
5. Using same Adguard server with google recursion blocks now in place (cant recurse *-dnsotls-ds.metric.gstatic.com) i destroyed the dot.mydomain.com host and created a new one dot2.mydomain.com.
6. Apply dot2.mydomain.com to GraphineOS "Private DNS" and since there are filter blocks in place for google the new address (dot2.mydomain.com) cant be pushed to them.
7. Delete old dot.mydomain.com from DNS.
8. No more recursions...

When the DOT server was initially added to graphineOS as soon as i hit save the push was sent to tmiqnw-dnsotls-ds.metric.gstatic.com. The prefix (tmignw) changes every time it tries to recurse them. There all blocked so they cannot get out now but interesting find from a security standpoint...

**Comment by thestinger** [comment]
Questions belong on the discussion forum or in the chat room. We know how DNS-over-TLS works and about the metrics query it performs. The issue tracker is for filing bug reports and in rare cases feature requests fitting what we want.
