### ISSUE TITLE
Google Camera very slow Portrait mode processing

### ISSUE THREAD

**Issue by TheoKlizz** [GrapheneOS/os-issue-tracker#1709]
As discussed here:
https://discuss.grapheneos.org/d/1815-google-camera-very-slow-portrait-mode-processing

Pixel 7 / 7 Pro owners experience issues with slow Portrait mode processing in official Google Camera app: it takes over 40 seconds to process each image. Other image modes (video, night sight, etc) are processing as expected, within a few seconds.  

It seems the app is struggling to process HDR+ properly.

In comparison, Portrait image processing takes 1-2 seconds in stock OS so is working fine. 

Older model owners (Pixel 6 and below) do not experience this issue with the same setup.

It can't be Google Camera app as both Pixel 6 and Pixel 7 users use the same latest version from Play Store / Aurora Store and Google services are installed from official GOS App store so its the same version. The issue occurs even on brand new GOS install with default settings and no apps installed, apart from Google Camera and Google Services.

As Pixel 6 owners do not experience this with the same setup, can it be that GOS for Pixel 7 is not utilizing Tensor G2 processor properly or something similar?

**Comment by thestinger** [comment]
> It can't be Google Camera app as both Pixel 6 and Pixel 7 users use the same latest version from Play Store / Aurora Store and Google services are installed from official GOS App store so its the same version. The issue occurs even on brand new GOS install with default settings and no apps installed, apart from Google Camera and Google Services.

Yes it can, because it has different code for different devices.

**Comment by thestinger** [comment]
People are welcome to work on this but we won't be tracking it on the OS issue tracker.

**Comment by ae5960e8-a6fc-491f-b252-898ecf59af95** [comment]
Oh god please don't ignore this bug

**Comment by thestinger** [comment]
Stop bumping issues without adding information.

**Comment by ASerbinski** [comment]
Wasn't there an sepolicy change needed for Pixel 6 for exactly this?
See comment 8: https://issuetracker.google.com/issues/227166806#comment8

Has that change been added to Pixel 7?

**Comment by gitubinator** [comment]
Same issue here, Pixel 7 with very slow processing speeds on portrait mode, means I can only take 3 photos before the shutter greys out.

**Comment by thestinger** [comment]
@ASerbinski The linked issue has no relevance to this.

GrapheneOS doesn't give privileged access to Google apps like Google Camera which is why it doesn't have privileged access to use non-standard hardware acceleration.

**Comment by thestinger** [comment]
This has be resolved in Google Camera by them improving the software processing to match the performance it has on other devices. No need for us to track it here.
