### ISSUE TITLE
Cant get into support site.

### ISSUE THREAD

**Issue by citynetcomputing** [GrapheneOS/os-issue-tracker#1710]
MatrixError: [403] You are not invited to this room. (https://matrix-client.matrix.org/_matrix/client/r0/join/%23grapheneos%3Agrapheneos.org)

**Comment by citynetcomputing** [comment]
Not it let me in. Disregard

**Comment by thestinger** [comment]
It's filed at https://github.com/matrix-org/synapse/issues/14481.
