### ISSUE TITLE
[feature request] allow inverting 2-button navigation bar

### ISSUE THREAD

**Issue by firefoxlover** [GrapheneOS/os-issue-tracker#1713]
Android 13 seems to have removed the ability to swap the back button to the right side, making it right-hand usable.

**Comment by thestinger** [comment]
It never had the option to swap it and 2 button navigation is deprecated. Gesture navigation is what's recommended:

https://grapheneos.org/usage#gesture-navigation

**Comment by firefoxlover** [comment]
Oh, so all these features were LineageOS specific. switcheable buttons, long press torch, accurate internet control (Cell data, VPN data, cell background data, any data)

on GrapheneOS you can only disable internet on install, which is a downgrade, even though even more secure if you dont want any internet.

**Comment by firefoxlover** [comment]
I tried it, weird that the 3 buttons are still supported, the 2 buttons are way better. poor choice of Google.

**Comment by thestinger** [comment]
> accurate internet control (Cell data, VPN data, cell background data, any data)

Their approach to that has major leaks and it doesn't work as a privacy feature at all.

**Comment by thestinger** [comment]
> I tried it, weird that the 3 buttons are still supported, the 2 buttons are way better. poor choice of Google.

Gesture navigation is what almost everyone is expecting to be using. 3 button navigation remains for accessibility reasons mainly. 2 button navigation was a step towards full gesture navigation without needing to reserve space for a huge navigation bar with buttons.

**Comment by firefoxlover** [comment]
> Gesture navigation is what almost everyone is expecting to be using. 3 button navigation remains for accessibility reasons mainly. 2 button navigation was a step towards full gesture navigation without needing to reserve space for a huge navigation bar with buttons.
swiping back is a huge gesture, opening the recent apps drawer is incredible, I have to move ovr 50% of the screen, accessing the home screen is not one click anymore but a weird swipe. It was Googles choice and I understand that capacities are limited, but gestures are awful.

**Comment by thestinger** [comment]
You don't need to do a long swipe for back. A small swipe works fine. You can adjust the sensitivity for it in the settings too. We have a guide on a lot of it at https://grapheneos.org/usage#gesture-navigation with tips.

**Comment by firefoxlover** [comment]
> You don't need to do a long swipe for back. A small swipe works fine. You can adjust the sensitivity for it in the settings too. We have a guide on a lot of it at https://grapheneos.org/usage#gesture-navigation with tips.

Thank you for the guide!
