### ISSUE TITLE
Allow DAVx5 as SeedVault Backup Target

### ISSUE THREAD

**Issue by tlambertz** [GrapheneOS/os-issue-tracker#1714]
I want to set up seedvault to do backups to a remote server.

In GrapheneOS, the supported options are:
- USB backup
- Internal Storage Backup
- Nextcloud Backup

The first two don't backup to a remote server, and the Nextcloud backup is proving really unreliable for me.
Upstream recommends using DAVx5's WebDav mounts instead.

In theory, SeedVault can backup to any SAF location, but is has to be whitelisted.
Upstream whitelists DAVx5 by default since Nov. 2021 (https://github.com/seedvault-app/seedvault/commit/0746af4304d154eb0f39ac7e1da71a3abf4ee04a).

The GrapheneOS fork does not whitelist anything except for Nexcloud:
https://github.com/GrapheneOS/platform_external_seedvault/blob/13/app/src/main/res/values/config.xml

I propose to add DAVx5 there as well, so reliable remote backups are possible.

**Comment by maade69** [comment]
It has been implemented in updated version of seevault
