### ISSUE TITLE
When case lid closed screen stays on

### ISSUE THREAD

**Issue by ZsZolee** [GrapheneOS/os-issue-tracker#1715]
This is my first Phone/OS which is not shutting off the screen if I close the lid of my case. It's a Pixel 7 Pro, but I checked the settings and I haven't found it where I can turn this feature on. The proximity sensor should allow this setting to be turned on, not?

**Comment by thestinger** [comment]
That's not implemented with the proximity sensor but rather a hardware feature using a magnet which may not be implemented by your case. I don't know if it's supported by the phone. Can't have an issue open about it when we don't know if it's supported.
