### ISSUE TITLE
Storage scopes not working as expected

### ISSUE THREAD

**Issue by Harrier-Du-Bois** [GrapheneOS/os-issue-tracker#1721]
Hi everyone,

I hope this is the right place, sorry if it ain't.

I'm trying to apply storage scopes limitations to an app called privacy blur (https://f-droid.org/packages/de.mathema.privacyblur/) but it doesn't seem to work the way I'd expect it to.

After denying the app file permissions and enabling storage scopes the app can still access all image files in all directories. Even after specifying a single folder the app still has access to all files.

Am I doing sth wrong or is this the way storage scopes ought to work? I was under the impression that the app shouldn't be able to access files it didn't create itself as long as storage scopes is enabled.

Thank you in advance for your help.

**Comment by thestinger** [comment]
It's working as intended. You're not understanding what the app is accessing vs. what the OS is accessing. The app doesn't provide the OS file picker.

**Comment by thestinger** [comment]
Please read https://grapheneos.org/usage#storage-access. Enabling Storage Scopes is an alternative to enabling storage permissions. It does not reduce access compared to not doing anything. It pretends the storage permissions requested by the app are enabled. Apps cannot access any files from other apps in shared storage by default and enabling storage scopes doesn't change that unless you add scopes. It allows them to store files where they could if they had been granted access via their requested permissions but not read files from other apps.

**Comment by Harrier-Du-Bois** [comment]
Thanks for your answer.
Just so I get this right, the thing I got wrong is the fact that the user may always access files manually (via file picker), even if no permission is granted. Permissions only affect what the app may access on its own, so to say?

**Comment by thestinger** [comment]
The system file picker is the system file manager, not the app. Permissions / storage scopes don't control what the system file picker can access, which is not part of the app. It's covered in https://grapheneos.org/usage#storage-access. Opening a file in the app with the system file manager is always something that can be done. The app is just opening the system file picker for you to do that, which is the recommended approach for apps. Storage Scopes is to work around apps insisting on using bulk access permissions (Photos, Videos, Media Management, Generic File Management, etc.) instead of that. Relevant part of that usage guide section:

> Additionally, both modern and legacy Android apps can open the system file picker interface to have the user store or load one or more files/directories on their behalf. This type of access doesn't require any of the permissions listed above. Using this approach gives the user control over where files are stored in their home directory and which files/directories can be used by the app. This is based on the Storage Access Framework (SAF) introduced in Android 4.4. SAF allows the user to grant access to files/directories in their home directory, external drives and also app-based storage providers such as network shares, cloud storage, an encrypted volume, an external drive with a filesystem the OS doesn't support for external drives, etc. This is the only way to use those app-based storage providers and modern Android has removed the legacy approach for accessing external drives.

**Comment by Harrier-Du-Bois** [comment]
Thanks once more for taking the time to clarify this aspect. I really did expect it to do things it ain't supposed to. I'll find another way to achieve the behaviour I'm after.

Sincerely

**Comment by thestinger** [comment]
You still seem to be misunderstanding what's happening because you seem to think the app can see those files and it cannot.

**Comment by Harrier-Du-Bois** [comment]
Not to worry, I've realised my initial mistake thanks to your explanation.

My worry is not about apps themselves being able to "see" files, like photos f.e., but the user(s) using the apps. I was hoping storage scopes would provide an easy method of hiding such files completely, I.e. from both app and user access but I guess I'll have to look for a way to hide or encrypt them instead in order to achieve the latter.

**Comment by thestinger** [comment]
If you don't want users to see them, they should be stored in internal app data, which is the normal default place for apps to store data.
