### ISSUE TITLE
Currently all overlay accessibility settings are not available

### ISSUE THREAD

**Issue by firefoxlover** [GrapheneOS/os-issue-tracker#1723]
I guess this is because apps with that permission can view all the content displayed and track you through that. Makes sense, but in general thats what the internet permission is for right?

I guess its in general good practice to block these overlay apps, but it removes a lot of functionality, like VolumeStyles (removed internet access in APK) being able to change the ugly volume indicator.

**Comment by thestinger** [comment]
That's wrong. This functionality is all available on GrapheneOS in the same way as the stock OS. If you're confused about Android 13 adding a restricted setting toggle, please look up information about that. Use https://discuss.grapheneos.org/ for support questions in the future. The issue tracker isn't for questions / support.

**Comment by thestinger** [comment]
@firefoxlover I don't know why you're opening another issue about it when you were told there's a restricted settings toggle which you can simply turn off. You just had to look up Android 13 restricted settings toggle to see that there's a toggle added for dangerous settings for apps not installed from an app repository. F-Droid uses the legacy package installation API therefore it doesn't count as coming from a modern app repository. It's F-Droid you need to get to change that, not GrapheneOS, and you could simply toggle on restricted settings for the apps as I suggested.

**Comment by firefoxlover** [comment]
Solved

The App first had to request accessibility settings, then I could enable the dangerous settings. Its Android 13s fault.

And if FDroid updates their APIs, it will work too?

**Comment by thestinger** [comment]
Yes, they just have to use session-based installation. They did it this way to apply the restriction for manually installed apps or apps installed by legacy app stores. It's less aggressive than doing it for all third party app sources. Play Store is considered a third party app source on GrapheneOS, so it would have the same restricted settings feature active for apps it installs if it worked that way.

**Comment by firefoxlover** [comment]
Interesting, AuroraStore apps work too for that reason. I will contact the dev of droid-ify, which seems way better than the original F-Droid app, includes some nessecary changes.
