### ISSUE TITLE
Broken Voice Message Transcription

### ISSUE THREAD

**Issue by HunterKurza** [GrapheneOS/os-issue-tracker#1728]
Voice Message Transcription support is currently broken on GrapheneOS and does not work as intended. Upon interacting with the "Transcription" button within the message, Google Messages will present the following prompt:

"
For transcriptions, install Speech Services by Google

This install adds the option for transcripts on your device.
"

Even after navigating the the Play Store and downloading the requested app, giving it all permissions, and additional permissions through the settings UI, the same message will continue to prompt every time and transcription will still not be available.

The option in the settings of the Messages application has been correctly set, all rights and permissions have been given to both applications, and the device has been rebooted with no help from any of this options.

**Comment by r3g-5z** [comment]
Is this still an issue?

**Comment by r3g-5z** [comment]
Closing assuming it's fixed due to inactivity and lack of other reports. If this is still an issue, let us know but we need some more clear details on how to reproduce it. Using Google Speech Services as TTS overall seems fine for me.
