### ISSUE TITLE
[Feature request] Enable Battery charge limit like on pixel phones

### ISSUE THREAD

**Issue by firefoxlover** [GrapheneOS/os-issue-tracker#1732]
On [rootable phones there is this module](https://forum.xda-developers.com/t/app-root-4-0-battery-charge-limit-v1-1-1.3557002/), which limits the charging to a defined value.

Pixel phones running Stock OS limit charging to 80% when playing games, but not in general.

For the durability of a phone battery, its important to keep it between 20-80% all the time. Please either add this module or another solution, as GrapheneOS cant be rooted.

**Comment by thestinger** [comment]
A pull request with a trivial amount of well written code could be considered but a feature request for this is out of scope. The person implementing it or someone else needs to commit to helping with maintenance of the feature and other things so that it doesn't hold back the project.

**Comment by thestinger** [comment]
Pull requests are welcomed for a broader range of things than feature requests. There are tends of thousands of things people could request as features but what ultimately matters is what people working on the project want to implement and maintain. If people want something they need to start working on the project to make that possible to consider.
