### ISSUE TITLE
Emergency calls not working with Pixel 6a (and probably others)

### ISSUE THREAD

**Issue by 77tom** [GrapheneOS/os-issue-tracker#1736]
There are multiple reports online that several Pixel devices have issues with calling emergency numbers.

I can confirm that there is an issue with this when using a Pixel 6a and the latest GrapheneOS version: [TP1A.221105.002.2022111800](https://github.com/GrapheneOS/platform_manifest/releases/tag/TP1A.221105.002.2022111800)

**This is what I observed:**
It's very scary. I was able to test it in Switzerland with the Swiss police number "117" and a Pixel 6a with the latest GrapheneOS. When you dial the number, the dialing screen immediately disappears. That Pixel 6a had a normal SIM + eSIM (not sure whether this is related to the issue).
I was also able to test it with a Pixel 4a running the latest GrapheneOS and there "117" works fine. That one only had a normal SIM.

**Potential workaround:**
I could imagine that a local fixed net police number should work as a workaround. Some police stations seem to offer that. But I didn't test this yet.

Based on the reports of other users (see links in the forum threads), it seems that this issue is also present in the stock OS, so I assume it's also in AOSP and not specific to GrapheneOS. But I'm hoping that the amazing developers of GrapheneOS can maybe help resolving this, as it doesn't seem that Google is fixing this soon.

Related forum discussions:
- https://discuss.grapheneos.org/d/1235-emergency-calls
- https://discuss.grapheneos.org/d/2003-pixel-phones-issue-with-calling-911

**Comment by thestinger** [comment]
We're unable to replicate any issue with this and if it's an AOSP issue also impacting the stock OS issue we don't track those here.
