### ISSUE TITLE
Google Play Services allows update via Play Store

### ISSUE THREAD

**Issue by whereskarlo** [GrapheneOS/os-issue-tracker#1737]
Google Play Services can be updated via the Google Play Store and it changes the version number of the app. Trying to update Play Services via Aurora Store does not work, which is expected behavior. When accepting the update via the Play Store, it updated Google Play Services and changed the version number.
![Screenshot_20221126-222003_1](https://user-images.githubusercontent.com/2850757/204134628-54182fba-54dd-4f28-8cc1-46146d931756.png)
![Screenshot_20221126-222059](https://user-images.githubusercontent.com/2850757/204134638-51b5da12-374d-4952-a9d6-e55e3f41b624.png)

**Comment by thestinger** [comment]
We've resolved this issue for the non-obsolete devices. We could ship an update for 3rd generation Pixels with this change but there are a lot of things we could backport to them beyond this and it's not currently planned.

**Comment by thestinger** [comment]
If you're on https://grapheneos.org/releases#2022111800 or later or if you have GmsCompatConfig v17, this shouldn't happen anymore. You likely updated it before that update. We currently have the same version in the app repository alpha and beta channels almost ready to be moved to stable anyway.

**Comment by whereskarlo** [comment]
I am on a Pixel 6a, GmsCompatConfig v17 and release 2022112500. I was able to update Google Play Services via the Play Store, and I understand that is not supposed to be possible. Do you have a Pixel 6a to test this on?

**Comment by thestinger** [comment]
It's supposed to be possible to 'update' it through the Play Store. It's not supposed to actually upgrade the version. Are you sure you didn't update it to our alpha/beta channel release, perhaps in a different profile? Can you check that if you have multiple profiles? App updates apply across all profiles since the installed packages are shared between each profile with the app installed.

**Comment by whereskarlo** [comment]
> It's supposed to be possible to 'update' it through the Play Store. It's not supposed to actually upgrade the version. Are you sure you didn't update it to our alpha/beta channel release, perhaps in a different profile? Can you check that if you have multiple profiles? App updates apply across all profiles since the installed packages are shared between each profile with the app installed.

I only use one profile, the owner profile. I am using the stable release channel under system/system update. The Play Services version I was upgraded to is visible in the first screenshot above. My version is ahead of the latest version available from apps.

**Comment by thestinger** [comment]
The developer working on this thinks it may be because it was queued before the fix was shipped. Please let us know if it ever happens again.

**Comment by thestinger** [comment]
Has been confirmed that it works that way. It persistently queues the updates. It should be resolved going forward.

**Comment by whereskarlo** [comment]
My phone updated to release 2022112500 yesterday. I also uninstalled GPS and re-installed from 'apps' yesterday to be on the GOS supported version. So, if Play Store can still download the GPS update after this I will let you know,
