### ISSUE TITLE
Display has a green tint when brightness is lowered

### ISSUE THREAD

**Issue by Ross2ww** [GrapheneOS/os-issue-tracker#1739]
Since the latest update my display has had a tint of green across the whole thing at brightness levels lower than 70%. The only time it dosnt is certain times when watching a video and the scene changes all of a sudden the tint is gone then the scene changes again and the tint is back. I also noticed the animation when unlocking the phone stutters with the same green tint.

**Comment by thestinger** [comment]
I don't think we can do anything about this. It sounds like a hardware issue.
