### ISSUE TITLE
Native Phone App Volume issue

### ISSUE THREAD

**Issue by Bouzenzel** [GrapheneOS/os-issue-tracker#1742]
The native GOS Phone app has an issue with call volume which when making a call the volume doesn't change when using the +/- buttons and the volume call is very high it hurts the ears.

Device : Pixel 6A.

**Comment by thestinger** [comment]
Unable to reproduce this.

**Comment by Bouzenzel** [comment]
Its confirmed among many 6A users on GOS discussion forum, i am not alone, the volume works fine on other apps like Whatsapp and Messanger

**Comment by thestinger** [comment]
Which volume is being adjusted when you do that, and have you checked if the other volume sliders change it?

**Comment by Bouzenzel** [comment]
- The call volume ! when using whatsapp for calling for example,
- yes i've checked all volume sliders but nothing changes, again this issue is present only on the 6A,

**Comment by Syberkonda** [comment]
As @thestinger mentioned using my post, I am also having this issue. I either get maximum volume through the earpiece or maximum volume through the speakerphone. The speakerphone hurts my ears, but the earpiece is too quiet to use in certain ambient situations (like a washer running in my apartment).

**Comment by Bouzenzel** [comment]
The issue is still going .. even after the last update and with multiple dialers .. however, for me the earpiece is so loud it hearts my ears when in a quiet environment, but in a busy environment it is fine, this issue is bothering me still.

**Comment by Bouzenzel** [comment]
The issue is still going .. even after the last update and with multiple dialers .. however, for me the earpiece is so loud it hearts my ears when in a quiet environment, but in a busy environment it is fine, this issue is bothering me still.

**Comment by Bouzenzel** [comment]
@thestinger @Syberkonda I've found the issue !! it turns out that hearing aids was activated by default and that made controlling the volume impossible, when i was playing with the phone app i headed to >> Settings >> accessibility >> hearing aids >> was ON ! i turn it OFF and made a call, Yaay!! i can control the volume, so it was not an issue as Daniel said ...

**Comment by davidhaley** [comment]
Same issue, and I don't have 'hearing' aids enabled. 6 Pro.
