### ISSUE TITLE
Add the possibility to use a different pin/password to unlock apps

### ISSUE THREAD

**Issue by ByJumperX4** [GrapheneOS/os-issue-tracker#1743]
Some apps such as KeePassDX gives you the option unlock them (or in the case of Keepass, store an encryption key) using the device's pin/password. 

It would be nice to be able to set a separate pin/password different from the lock screen's to have an extra layer of protection for those apps that can contain sensitive data.

**Comment by thestinger** [comment]
For cases where you need high security and can sacrifice convenience, there's the option of making a separate user profile. User profiles each have their own lock methods and encryption keys.

These apps could choose to implement their own passphrase, and some do, but usually without any additional layer of encryption. It's not really something that would make sense to implement in the OS.
