### ISSUE TITLE
face unlock (pixel 7)

### ISSUE THREAD

**Issue by Light-Wing** [GrapheneOS/os-issue-tracker#1746]
I just installed GrapheneOS, and saw that its missing face unlock.

I also saw:
1 closed issue saying its not planned  [#1607](https://github.com/GrapheneOS/os-issue-tracker/issues/1607) and 
1 issue resolved about it working in main user account and not in secondary user. [#748](https://github.com/GrapheneOS/os-issue-tracker/issues/748)

so I'm not sure if its meant to work and just isn't working, or its purposely left out.
can someone clarify? 

thanks.

**Comment by thestinger** [comment]
Pixel 7 face unlock is insecure and won't be included in GrapheneOS. It lacks the necessary hardware support for secure face unlock. It has fingerprint unlock anyway.

**Comment by thestinger** [comment]
https://github.com/GrapheneOS/os-issue-tracker/issues/748 was about the Pixel 4 and Pixel 4 XL where face unlock is supported on GrapheneOS since they have a secure implementation.
