### ISSUE TITLE
Wi-Fi on Pixel 7 is not connecting to DD-WRT router

### ISSUE THREAD

**Issue by Redback813** [GrapheneOS/os-issue-tracker#1748]
Before I installed the Grapheneos on the new Pixel 7, the stock Android 13 worked with DD-WRT, but since I installed Grapheneos it sees the network however connection fails to obtain an IP.

Thanks in advance.

**Comment by maade69** [comment]
This doesnt seem to be GrapheneOS issue. Check if DHCP is configured correctly on your router.

**Comment by thestinger** [comment]
This seems to be a network issue. You should reboot the router and check the DHCP table. Maybe it's filled up.
