### ISSUE TITLE
ADD support for Google Wallet / Google Pay  (fix safetyNet)

### ISSUE THREAD

**Issue by forrest96** [GrapheneOS/os-issue-tracker#1749]
Google Wallet / Google Pay is not fully supported on GOS.

Main Issue is that GOS is not whitelisted by google (CTS profile match Failed). 

![Screenshot_20221129-173918](https://user-images.githubusercontent.com/30241806/204599434-794aebbc-d173-46a6-ad4c-7db997fd0f3a.png)

To fix this you could ask Google to add GOS to the list of supported devices, but I do think it is very unlikely that they will do that.
Another approach would be that GOS just return system Strings of the stock Google firmware.
To prevent confusion of other apps it would be nice if these features could be implemented in a way, that the user can decide for any app (google services, google wallet etc.)  to use googles system strings or not.

To get Google Wallet working, I had to grant Google Play services access to my Phone and SMS. However, after the first run of Google Wallet I could revoke those permissions without any serious problems.

![Screenshot_20221129-175215](https://user-images.githubusercontent.com/30241806/204613322-95bfdb82-8009-412a-b38c-d7fe8571e065.png)

Maybe it’s a good Idea to Add for Phone and SMS (and other permissions) after Allow and Don’t Allow a third Option that return fake information and simulate write access.  In this way apps that need many permissions to work, should work without the permissions they have asked for. 

My specs:
![Screenshot_20221129-173925](https://user-images.githubusercontent.com/30241806/204613206-ea293176-4506-4302-a834-dd95135c13e3.png)

**Comment by thestinger** [comment]
SafetyNet attestation is deprecated. It's replaced with the Play Integrity API. Both APIs support strong attestation that cannot be spoofed. It will stop being possible to spoof a different OS. If you want there to be a temporary implementation of spoofing, you'll have to make a very clean and minimal implementation which works with sandboxed Google Play for us to consider. We don't take feature requests for stuff like this. We'll consider well written pull requests, not a feature request.
