### ISSUE TITLE
Block acces to the clipboard for apps, or implement an internal non-accessible clipboard

### ISSUE THREAD

**Issue by firefoxlover** [GrapheneOS/os-issue-tracker#1751]
## Alternative solution
Integrate FlorisBoard as the standard keyboard, with presets:
- enabling the toolbar for "clipboard events", not "cursor"
- enable internal clipboard
- enable sync from system clipboard
- disable sync to system clipboard

## Other solution
A permission for apps to access the clipboard.

The notification since Android 12 is helpful, but doesnt solve anything.

Many people dont know about Keyboards like Florisboard, that provide this privacy feature. I cant say how secure it is though, but I think it is very secure, as the clipboard is stored in the container of the app.

---

This is a really critical issue, as people copy everything, passwords etc. to their Android clipboard. FlorisBoard circumvents that, but only when using the apps buttons, not the popup of the android system. So you may accidentally copy a password to the internal clipboard, which there is no permission for.

**Comment by thestinger** [comment]
FlorisBoard is not currently suitable for integration.

Please see https://grapheneos.org/faq#clipboard-access. The clipboard is only accessible to the focused app, not even to foreground apps which aren't focused. The clipboard access notice is only relevant to the focused app.

We already have an issue filed about https://github.com/GrapheneOS/os-issue-tracker/issues/347.
