### ISSUE TITLE
[Wishlist, no priority] Preinstall an advanced password manager

### ISSUE THREAD

**Issue by firefoxlover** [GrapheneOS/os-issue-tracker#1752]
This is low priority, but would be better than Keepass and encourage people to use a password manager.

The Database is encrypted using the lockscreen-password, an overlay service detects input fields. Unlike Keepass, more like on iOS, you dont have to once decrypt the whole database, but the entry locations are readable for the autofill-service when the phone is unlocked, and if there is a field, a dialog asks the user to enter a password, fingerprint e.g., which then decrypts the one entry. Every entry is encrypted differently, so a brute-force attack of one entry would not effect other entries.

The autofill service would know that there is an entry for that, but no information about it, unless you unlock that entry, for example using a fingerprint.

**Comment by thestinger** [comment]
Bundling apps that aren't strictly necessarily isn't something we want to do.
