### ISSUE TITLE
[Vanadium changes] Enable custom search engines

### ISSUE THREAD

**Issue by firefoxlover** [GrapheneOS/os-issue-tracker#1756]
This could be done via the OpenSearch format or a Firefox-android like manual adding, example:

https://searx.neocities.org/#q=%s&category_general=on

(where "%s" is the word you enter)

Custom Search engines reduce the centralization of all your web searches to one party and increase privacy drastically. The named search engine for example limits the traceabilty of done searches to other sites a lot (while knowing everything you search itself of course).

**Comment by thestinger** [comment]
Custom search engines are already supported.
