### ISSUE TITLE
System Tray does not need to be fully extended to be interacted

### ISSUE THREAD

**Issue by elfein727** [GrapheneOS/os-issue-tracker#1762]
Problem: touching top of phone when unlocked interacts with system tray/quick options.

Steps to reproduce:
1. install GrapheneOS
2. Unlock phone, go to any screen
3. Tap or hold at the top of the screen, where bluetooth or internet+data buttons are

Expected behavior: only start tray open
Actual behavior: tray open starts, but tray is interactive before fully extended, and so triggers data/wifi/bluetooth buttons

Why this is a problem: accidental touches or temporary grips in the wrong spot can lead to unintended behavior, wasting time and possibly leading to an unideal outcome in emergency situations.

Potential solutions:
1. Grab the phone diffrently
2. Adjust the tray interactivity so there's an opening threshold to prevent accidental interaction
3. Allow custom DM/WM

**Comment by thestinger** [comment]
This is how it works in AOSP / stock OS and we aren't planning on changing the UI.

**Comment by elfein727** [comment]
Should i open an issue upstream then?

**Comment by thestinger** [comment]
They're probably already aware. It's just not possible for us to fix every standard Android UI issue ourselves. We need to limit our focus much more than that.

**Comment by elfein727** [comment]
Oh. I didn't realize the level of concentration. That explains a lot lol
