### ISSUE TITLE
OS appears to run fine, "device is corrupt" message on boot

### ISSUE THREAD

**Issue by BringerofD** [GrapheneOS/os-issue-tracker#1768]

**Comment by BringerofD** [comment]
Ok, so again as per the instructions i flashed back to android, flashed Graphene again. No more corrupt message until an hour or so later while I was installing my apps. Phone suddenly rebooted and gave me the "device is corrupt" message again.

**Comment by thestinger** [comment]
This is either an issue with how the OS is being installed or hardware failure. It would be worth trying to sideload the latest release as an update to work around that. You should try it after that, and then try it again a 2nd time to test the potentially problematic part of the SSD again.

**Comment by BringerofD** [comment]
Reflashed back and forth again this morning, so far so good. Thanks for all the help.
