### ISSUE TITLE
Manage all files permission sometimes reset

### ISSUE THREAD

**Issue by xbillion** [GrapheneOS/os-issue-tracker#1769]
I grant permissions to applications for full disk access
and after 2-3 days, after restart phone - all apps don't have grant access to files, they ask permissions again
it happened twice

Pixel 6a, Android 13

**Comment by thestinger** [comment]
Known AOSP issue also impacting the stock OS. It happens after OS updates. It impacts all special permission grants. We've have other issues filed about it and we're working on resolving it. It should be fixed upstream though...
