### ISSUE TITLE
WiFi Failes to Reconnect Automatically on PEAP-MS-CHAP v2

### ISSUE THREAD

**Issue by ajDeWolfe** [GrapheneOS/os-issue-tracker#1770]
Authenticating against AD. Device fails to automatically reconnect to WiFi it has been successfully authenticated on. Manual reconnect fails. To manually reconnect the connection settings have to be modified to change the CA Certificate from the saved one to "Trust on First Use". Then a popup from the OS has to be accepted and WiFi connection will reestablish. WiFi reconnects automatically on other networks.

**Comment by spicydll** [comment]
As a work around, I found that changing CA certificate to "use system certificates" after first connection will allow your device to reconnect.

**Comment by ajDeWolfe** [comment]
That did not work on my first try. I'll experiment more with it.

**Comment by ajDeWolfe** [comment]
> It's unlikely this is an issue in the OS. Consult your helpdesk for support.

I am the lead admin at this site. There are hundreds of devices on the network working properly. Another user in this issue reported the same issue and a work around that worked for them. Clearly there is a real issue.

**Comment by ajDeWolfe** [comment]
> It's unlikely this is an issue in the OS. Consult your helpdesk for support.

I am the lead admin at this site. There are hundreds of devices on the network working properly. Another user in this issue reported the same issue and a work around that worked for them. Clearly there is a real issue.

**Comment by ajDeWolfe** [comment]
There are plenty of Android 13 devices on the network.

**Comment by ajDeWolfe** [comment]
yes

**Comment by ajDeWolfe** [comment]
self signed

**Comment by flawedworld** [comment]
It is a WPA2-Enterprise or WPA3-Enterprise network?

**Comment by ajDeWolfe** [comment]
wpa2-enterprise

**Comment by flawedworld** [comment]
It's likely going to be an AOSP bug, be it intentional or not by Google, with how the OS deals with self signed certificates for enterprise Wi-Fi networks. I'm not really totally surprised this is happening, Android intentionally breaks insecure enterprise network configurations over time to force organisations to move to safer standards. We don't change how this works compared to the stock OS.  You'll likely have no choice in future but to deploy a proper CA for your Wi-Fi networks, expect this configuration to break in a future Android version.

In the meantime in this specific case, please provide information of the stock OS Pixel device running Android 13 -- What device and what build? Does it still work fine if you forget the network and try add it again?

**Comment by ajDeWolfe** [comment]
pixel 6 pro TP1A.221105.002.2022112500. The issue persists if I forget the network and reconnect. I can install AOSP 13 on a oneplus 5T and test with that too.

**Comment by ajDeWolfe** [comment]
the stock one is Pixel 6 pro TP1A.221105.002

**Comment by flawedworld** [comment]
If you are ok with installing an alpha, please try this OTA: https://releases.grapheneos.org/raven-ota_update-2022120600.zip

**Comment by ajDeWolfe** [comment]
I believe it installed by enabling alpha channel updates.  build TW1A.221205.011.2022120600 no change in behavior. Even when I manually connect it fails, I have to change the certificate to allow on first use.

**Comment by maade69** [comment]
two people are unable to replicate this issue. Using FreeRadius server, WPA2-EAP/WPA3-EAP as security standard and PEAP MSCHAPV2 as authentication method.

**Comment by maade69** [comment]
It might be a AP/Radius server misconfiguration or certificate not being compatible with Android 13+. See https://source.android.com/docs/core/connect/wifi-tofu#background

**Comment by flawedworld** [comment]
Please test this on QPR2 - the latest release.

**Comment by r3g-5z** [comment]
Pinging again, is this still an issue on the latest GrapheneOS release?

**Comment by r3g-5z** [comment]
Going to assume this is fixed as of QPR2 Android 13 due to no response, no one else has reported this issue recently, and we're unable to reproduce this on our end.

If this is still an issue let us know but we need very clear reproduction steps and your environment and configuration.

**Comment by iMonZ** [comment]
Still persists in the latest version of the OS. Tried a self signed Certificate from Unifi for testing. With all my other Devices and custom ROMs its acutally working.
