### ISSUE TITLE
pixel 5; forgetting bluetooth blocks device from future pairing

### ISSUE THREAD

**Issue by EpicTMC** [GrapheneOS/os-issue-tracker#1771]
latest grapheneos
recently i 'forgot' my headphones as they were playing up when connecting
when i rescan i can see devices around me but the headphones do no show on the pixel
other devices can see the headphones

*headphones are shure aonic tw2

**Comment by thestinger** [comment]
Is this still an issue for you?

**Comment by EpicTMC** [comment]
> Is this still an issue for you?

all good now bro
