### ISSUE TITLE
GMSCompat Hints for pairing a Pixel Watch

### ISSUE THREAD

**Issue by ojoeth** [GrapheneOS/os-issue-tracker#1772]
When pairing a new Pixel watch to a GrapheneOS device, Google Play Services requires access to Location and Nearby Devices permissions to pair successfully. GMS Compat should prompt for those permissions to be granted.

**Comment by jecrento** [comment]
+1. But for me worked with only adding "Nearby Devices" permission to Google Play Services.

**Comment by MichelBaie** [comment]
Thanks !!

**Comment by wreckedcarzz** [comment]
> +1. But for me worked with only adding "Nearby Devices" permission to Google Play Services.

Thank you, this worked!

**Comment by muhomorr** [comment]
Addressed by https://github.com/GrapheneOS/platform_packages_apps_GmsCompat/commit/ec8e0006d5a66a1bde485337bff21d34a423677d
