### ISSUE TITLE
Telegram getting past DND

### ISSUE THREAD

**Issue by Silent-Hunter** [GrapheneOS/os-issue-tracker#1775]
Do not disturb is somehow letting Telegram get past do not disturb mode. It's making noise and vibration as if the mode wasn't on. I'm using GrapheneOS 13 (TP1A.221105.002) on a Pixel 6.

**Comment by thestinger** [comment]
What is making noise and vibrations? The notifications? It's still supposed to be able to do that from the app.

**Comment by Silent-Hunter** [comment]
Yeah, the notifications. Even if the app isn't open. It used to be that even with it open it wouldn't make sound or pop on screen if DND was on. Is DND not handled by the OS? I'm confused about how an app can ignore it.

**Comment by thestinger** [comment]
Settings -> Sound and vibration -> Do not disturb. You'll need to confirm it's not a configuration issue with the choices you made for DND.

**Comment by Silent-Hunter** [comment]
It was my mistake. I had my boyfriend as a starred contact, and an update to GrapheneOS seems to have allowed it to realize the Telegram contact and the regular phone contact were the same person.
