### ISSUE TITLE
Possibility to improve the clock app

### ISSUE THREAD

**Issue by Franz-Straus** [GrapheneOS/os-issue-tracker#1776]
The AOSP clock app used in GrapheneOS can be replaced by this project : https://github.com/qw123wh/new-clock .It has several advantages over the current app. For instance, it has proper dark mode support and Material v3 design. Or maybe only the UI could be ported instead. The license is the Apache-
![Screenshot_20221203-134940](https://user-images.githubusercontent.com/119739182/205441726-f460350c-0582-424b-bf20-41a420afb1ac.png)
2 so there should not be any issues.

**Comment by thestinger** [comment]
They didn't port to the new AOSP Clock app code and the project appears to be dead.

**Comment by thestinger** [comment]
It could be used as a reference but we can't use this directly. They didn't really use Git properly, etc. and that makes it a lot harder to review. Maybe they could do a new fork of the current AOSP Clock app code but some major issues need to be fixed with the AOSP app before improving the UI.
