### ISSUE TITLE
Emergency Information Crash

### ISSUE THREAD

**Issue by Franz-Straus** [GrapheneOS/os-issue-tracker#1777]
When entering Emergency Information for the first time, after filling the name, address, blood type fields it crashes returning you to the main settings screen when you press to enter the allergies. If you have already filled the information this bug can be replicated by clearing all the information and entering it again. 

Device: Google Pixel 6 Pro
13 (TP1A.221105.002)

**Comment by JarekLB** [comment]
unable to replicate on p7 120700.

**Comment by thestinger** [comment]
@Franz-Straus  Please test this on the latest release.
