### ISSUE TITLE
Dark theme for Calculator and Messaging

### ISSUE THREAD

**Issue by w9925** [GrapheneOS/os-issue-tracker#1779]

**Comment by r3g-5z** [comment]
The built-in SMS app is incredibly dated and has far more issues than lack of dark theme. It will either be replaced in the future, or eventually AOSP will implement dark theme themselves.
https://github.com/GrapheneOS/os-issue-tracker/issues/406#issuecomment-742581419

A clean and small patch for dark theme ExactCalculator may be accepted.
