### ISSUE TITLE
Display Not Auto Sleeping at Set Time

### ISSUE THREAD

**Issue by skykingisepic** [GrapheneOS/os-issue-tracker#1784]
New install on Pixel 5

Set for either 15 or 30 seconds, will occasionally not shut off until I press pwr btn then sleeps at set interval after that

**Comment by thestinger** [comment]
Apps can hold a screen wake lock while in the foreground. Do you have an app running that may be doing it like a navigation app or video player?

**Comment by gbkelley** [comment]
Retired IT, php developer no Android apps though...

No apps running in foreground. In  background just GmsCompat and Clipt which is a clipboard sharing app. If screen gets stuck again, I'll turn that off but it is handy to share text quickly with desktop.

**Comment by gbkelley** [comment]
I have changed the timeout for display sleep to 30 sec from 15 and it seems to be working. Maybe it doesn't like 15 sec for some reason.

**Comment by hrrd** [comment]
same for me. if swipe up from an app out (without closing) to the home screen it doesn't timeout the screen. i have set 15 seconds. this occurs in the owner profile but i have enabled second profile.

**Comment by r3g-5z** [comment]
Merging into https://github.com/GrapheneOS/os-issue-tracker/issues/1268

**Comment by thestinger** [comment]
Should be resolved by upstream QPR2 release.
