### ISSUE TITLE
Problems with Bluetooth and Meshtastic app

### ISSUE THREAD

**Issue by heinrichat** [GrapheneOS/os-issue-tracker#1787]
Hi,

Meshtastic is an app which lets you configure a µc via Bluetooth, but it doesn't work on GOS. I can see the µc devices in the Bluetooth menu (Figure 1), but it needs to be done inside the app for it to work. The Meshtastic app is installed in the main profile. Inside the app it just doesn't see any devices at all (Figure 2). All Permissions are granted (Figure 3). Meshtastic runs great on an unmodified stock Android and sees the all Bluetooth devices nearby. I am highly confident, that it has something to do how GOS handles Bluetooth.

You don't need to have the µc to test this. If *any* Bluetooth devices are showing up inside the Meshtastic app, assume it works.

Somewhat related/similar issue - the Jabra Sound+ app also uses Bluetooth to connect to the earbuds, but in this case the app was installed in the work profile, but the app only connected to the earbuds successfully when installed in the main profile.

Using Pixel 4a updated to latest stable branch.

Figure 1
![Screenshot_20221207-140849](https://user-images.githubusercontent.com/5469642/206199324-19309419-e5f4-4fae-ae9a-35d38dab8443.png)

Figure 2
![Screenshot_20221207-140940](https://user-images.githubusercontent.com/5469642/206199436-b0ad39c0-88ed-4176-8bb4-3aab2133caff.png)

Figure 3
![Screenshot_20221207-141025](https://user-images.githubusercontent.com/5469642/206199379-51818330-2e1a-4cca-a294-f595ccadbbf7.png)

**Comment by heinrichat** [comment]
No change.

**Comment by mcayea95** [comment]
Having the same issue with stock android. 

App version 2.0.6
TBeam Firmware 2.0.6.97
Running android 13 on a Galaxy A53

**Comment by thestinger** [comment]
@heinrichat It's possible it has issues on some devices and the device being used with GrapheneOS is one of them. Therefore, it's not necessarily a GrapheneOS issue just because it works on stock OS on a different phone, even if that phone is a different Pixel.

**Comment by mcayea95** [comment]
@heinrichat After an update from 2.0.6 to 2.0.7, I can now see and pair with my boards.
