### ISSUE TITLE
System Storage taking up 45% of storage space

### ISSUE THREAD

**Issue by rshxyz** [GrapheneOS/os-issue-tracker#1788]
Hello, 

I have system storage taking up 55GB of space, close to 45% of my storage, and unable to use any of that space. I have about ~3GB of free space and a game app tried downloading 4GB of game content which eventually fails saying there is not enough space. I also tried making a video with google camera and it eventually stops recording once it hits roughly 2GB, saying I don't have enough space. Looking at a stock android phone it should be less than 20GB of system storage space taking, How do I fix this problem?

**Comment by thestinger** [comment]
System storage includes far more than just the OS, which is a fixed amount of reserved space. This is a support question and you should ask on https://discuss.grapheneos.org/. There's no indication of a bug. We can't provide support here.
