### ISSUE TITLE
New Pipe screen dimming

### ISSUE THREAD

**Issue by nlindesmith** [GrapheneOS/os-issue-tracker#1790]
When using NewPipe and rotating the screen to the horizontal position when a video is playing the screen will auto-dim even with the brightness setting being set to full brightness.

**Comment by whereskarlo** [comment]
This is not an issue, it is working as intended. To control the brightness of newpipe, swipe up or down in the left hand part of the screen while in landscape mode. Swiping in the right corner up/down controls volume.
