### ISSUE TITLE
Switching users while getting a WhatsApp call

### ISSUE THREAD

**Issue by Nxtmaster10** [GrapheneOS/os-issue-tracker#1791]
Device: Pixel 6
If you have multiple users with notification forwarding and calls turned on, let's call them _"Main"_ and _"Secondary"_ and you are logged into the user _"Secondary"_ while getting called on WhatsApp on _"Main"_ you are unable to switch users (like when getting a normal call). Although you have to be on the user _"Main"_ to accept the call. I am unsure if that is something WhatsApp needs to fix or if this is a AOSP/GrapheneOS bug. Let me know if you need further information

**Comment by cyruseuros** [comment]
Any chance you could link the upstream issue if you're aware of it? My search is coming up blank
