### ISSUE TITLE
USB Accessories stop working

### ISSUE THREAD

**Issue by F1VWdk** [GrapheneOS/os-issue-tracker#1792]
It appears there is indeed an issue in GrapheneOS with the "`USB Accessories`" setting as I initially reported in [USB DAC crashes when phone is locked #1631](https://github.com/GrapheneOS/os-issue-tracker/issues/1631)

#1631 was closed based on the ground that "`Default USB Configuration`" setting in Developer options was modified from the default "`No data transfer`" to "`File Transfer`" - but in reality, this settings is irrelevant for the issue to occur, it just with modified settings the issue manifests immediately and without it, it takes about 30 min but it still occurs.

On stock OS a USB accessory (USB headphones or USB DAC) works regardless if "`Default USB Configuration`" in Developer options was changed or not - it just works. Always.

On GrapheneOS:
1. Developer options enabled
	1.a	"`Default USB Configuration`" changed:

	If Developer options "`Default USB Configuration`" was changed to "`File Transfer`" from the default "`No data transfer`", USB accessories (USB DAC or USB headphones) will stop working as soon as phone screen is locked. This happens regardless of what "USB accessories" is set for in "`Security`".

	1.b "`Default USB Configuration`" not changed:
		USB accessories will stop working in about 30 min after screen is locked, just as in #2 below

OK, the devs recommendation was - DO NOT TOUCH DEVELOPER SETTINGS, but the issue is still present even with Developer options disabled

2. Developer options disabled
	Once a USB accessory connected as authorized per "`USB accessories`" settings, it will stop working in about 30 min after locking the screen (for some reason the time varies from 25 to 40 in my testing, I have no idea why)

I apologize for raising this issue again but in my opinion it was initially dismissed prematurely and the issue is still present, but if devs decide not to look into again, well, ok.

**Comment by r3g-5z** [comment]
At the end of the day, the original issue was still caused by messing with developer options that shouldn't need to be messed with.

Plenty of people are unable to reproduce your issue, the people who had the issue reverted their developer options changes which solved it, and because you were found leaving out critical details in this bug report it's extremely likely this is your own issue caused by some changes you're not telling us.
