### ISSUE TITLE
Unable to register additional fingerprints on Pixel 6a

### ISSUE THREAD

**Issue by seanlano** [GrapheneOS/os-issue-tracker#1795]
I'm trying to add an additional fingerprint with GrapheneOS build TQ1A.221205.011.2022120700 on my Pixel 6a.

I can see that I've got 4 registered fingerprints already, but when I choose the "Add fingerprint" button, the "Touch and hold the fingerprint sensor" screen doesn't actually show the fingerprint sensitive area. I've tried touching and holding where the area would be, but it doesn't register.

The reader itself works fine, I can use it e.g. to unlock the screen, but it seems like it doesn't activate when I try to add new fingerprints.
![Screenshot_20221209-134848](https://user-images.githubusercontent.com/16694351/206613835-2220a10d-132e-4da1-8d34-1d688e817ada.png)
![Screenshot_20221209-134856](https://user-images.githubusercontent.com/16694351/206613844-dfc51b42-533a-451f-8e34-586bc60de322.png)

**Comment by seanlano** [comment]
Interestingly I have another user profile which also has fingerprints set up, although only two of them – and within that profile the sensor does work as expected to add additional fingerprints

**Comment by seanlano** [comment]
Ahh OK so in that other profile I can add up to four fingerprints, but if I try to add a fifth then it has the same bug, it lets me choose the "Add fingerprint" button but then won't let me actually do the registration process. Is there a four fingerprint limit per profile? If so, the UI should disable the "Add fingerprint" option when the limit is reached.

**Comment by maade69** [comment]
I can reproduce it on Pixel 7 as well

**Comment by thestinger** [comment]
We'll probably leave this up to them to fix.

**Comment by 5georgeK** [comment]
Same in my Pixel 7 Pro.
![Screenshot_20230107-101528](https://user-images.githubusercontent.com/66057987/211143270-9c82e970-22f3-4b5c-a43c-4412b9e2c7de.png)
![Screenshot_20230107-101455](https://user-images.githubusercontent.com/66057987/211143275-b9cad1c3-2bca-43ed-ad5e-e08a3c3b32a4.png)

**Comment by C4yrslf** [comment]
Can reproduce on my Pixel 6a. With very touchy sensor it sucks that we can't add more finger prints. 

All four are for only one of my fingers to try and have the device remember as many different versions of my finger as possible to encounter as less possible the issue of the scanner not recognizing my print.
I used to add a new fingerprint when for some reason the scanner didn't recognize my finger.

**Comment by thestinger** [comment]
This is not relevant to the issue. If you're using a screen protector, that's likely your issue. It's not related to this.

**Comment by C4yrslf** [comment]
The Google Pixel 6a is known to have a difficult fingerprint scanner, my way around it is registering multiple times the same finger. I just added this to explain that to help the phones usability having more than 4 fingerprints available does help.

**Comment by flawedworld** [comment]
Stock OS on the Pixel 6a limits max fingerprints to 4. This is likely why this is happening.

android:integer/config_fingerprintMaxTemplatesPerUser = 4

**Comment by thestinger** [comment]
I wonder if the fact that we're using many more user profiles could be an issue since there are many more total fingerprints registered. Not directly related to this issue but something to consider.
