### ISSUE TITLE
Expanded volume panel doesn't always expand

### ISSUE THREAD

**Issue by lokesh-krishna** [GrapheneOS/os-issue-tracker#1797]
Pressing the volume button to bring up the volume panel and then tapping on the three dots to bring up the expanded volume panel, the panel only contains the header (Sound and vibration) and the buttons for Settings and Done. No sliders. 
Dismissing it and bringing it back up does display everything as intended. Usually happens the first time I'm bringing it up after a reboot.

**Comment by lokesh-krishna** [comment]
![Screenshot_20221213-223402](https://user-images.githubusercontent.com/20235646/207611138-2299e653-1ab2-41bb-bb22-0e4ddf91149d.png)

Screenshot of what this looks like.

**Comment by flawedworld** [comment]
It will come in QPR2, so I'm going to close this issue. No action is needed, just need to wait.

**Comment by flawedworld** [comment]
Misread issue. Ignore my actions.

**Comment by lokesh-krishna** [comment]
Faced this exact same issue on a Xiaomi Pad 5 running ArrowOS which makes me suspect that this might be an upstream issue. If that is the case then should I close the issue?

**Comment by r3g-5z** [comment]
Is this still an issue on latest GrapheneOS release (QPR2)?

**Comment by lokesh-krishna** [comment]
Haven't been able to reproduce it on QPR2 so far.
