### ISSUE TITLE
[FEATURE REQUEST] Graphene OS implementation of Digital wellbeing

### ISSUE THREAD

**Issue by laraib07** [GrapheneOS/os-issue-tracker#1798]
Digital wellbeing is a fantastic feature to lower your SOT and keep addictive apps in check.  I know implementing google's digital wellbeing requires deeper system integration of google.  
Why not graphene OS develop its own digital wellbeing feature.

**Comment by akc3n** [comment]
Duplicate #920

**Comment by r3g-5z** [comment]
@laraib07 GrapheneOS isn't interested in developing something like this. We barely get enough community support on our own apps as-is.
