### ISSUE TITLE
Lock screen showing a bold text/clock after version update "2022120700"

### ISSUE THREAD

**Issue by NuiceT** [GrapheneOS/os-issue-tracker#1799]
# This is how it looks like:
![_20221209_095215](https://user-images.githubusercontent.com/35931666/206663446-93ae2613-b73d-48a2-acae-c80148ac53c8.JPG)

# How it should look like:
![Screenshot_20221209-095231](https://user-images.githubusercontent.com/35931666/206663547-fc1214a4-b620-4771-8528-d4d5626276fe.png)

**Comment by thestinger** [comment]
AOSP change, not ours.

**Comment by bungabunga** [comment]
also, the other clock looks like this on lock screen ...
![signal-2022-12-09-18-23-06-818](https://user-images.githubusercontent.com/2994878/206759724-0e3b81a0-325e-4719-82a8-4f0b51975807.jpg)

**Comment by bungabunga** [comment]
![Uploading signal-2022-12-09-18-23-06-818_1.jpg…]()

**Comment by bungabunga** [comment]
![signal-2022-12-09-18-23-06-818_1](https://user-images.githubusercontent.com/2994878/206760533-62b9cf8a-e354-457b-866d-9afa4eb9fa66.jpg)

**Comment by r3g-5z** [comment]
This isn't a change made by GrapheneOS and there aren't any plans to invest resources into this.

**Comment by thestinger** [comment]
GrapheneOS may end up changing the appearance but this change was made by AOSP. It looks like it might not be fully compatible with all display size configuration options.
