### ISSUE TITLE
WiFi calling not working on pixel 7 pro

### ISSUE THREAD

**Issue by ASerbinski** [GrapheneOS/os-issue-tracker#1803]
Exactly the same issue as https://github.com/GrapheneOS/os-issue-tracker/issues/1648 except that @flawedworld insists that its different.

**Comment by flawedworld** [comment]
Provide information on your device and carrier and the exact issues you are seeing here if you want support.

**Comment by ASerbinski** [comment]
Details: https://github.com/GrapheneOS/os-issue-tracker/issues/1648#issuecomment-1344514964

**Comment by ASerbinski** [comment]
Factory reset cleared it up. What a pain in the a**.
