### ISSUE TITLE
Safra banking app crashing on startup.

### ISSUE THREAD

**Issue by empratyush** [GrapheneOS/os-issue-tracker#1804]
[app link ]( https://play.google.com/store/apps/details?id=br.livetouch.safra.net)
[logs.txt](https://github.com/GrapheneOS/os-issue-tracker/files/10198121/logs.txt)

**Comment by flawedworld** [comment]
[34m12-10 02:30:20.879  3289  3289 D BoundBrokerSvc: onBind: Intent { act=com.google.android.gms.safetynet.service.START pkg=com.google.android.gms }[0m
[34m12-10 02:30:20.879  3289  3289 D BoundBrokerSvc: Loading bound service for intent: Intent { act=com.google.android.gms.safetynet.service.START pkg=com.google.android.gms }[0m

may be SafetyNet related

**Comment by thestinger** [comment]
Looks like it's intentionally not working. Spoofing software SafetyNet checks or Play Integrity checks to trick it into passing the certification check in addition to the basic integrity check it already passes is possible but there isn't someone to work on it and it likely involves awful hacks.
