### ISSUE TITLE
Calls end unexpectedly after 1 second when "call over 4G" is on

### ISSUE THREAD

**Issue by mathiser** [GrapheneOS/os-issue-tracker#1805]
Im on pixel 7 build TQ1A.221205.011.2022120700

As the title states, calls simply end after about one second when 4G for calls is activated. When turning the setting off, the problem disappears.

I can provide more info if needed, but please direct me to what is needed.

Mathis

**Comment by flawedworld** [comment]
Your carrier likely does not support VoLTE properly in your area and/or on the Pixel 7.

**Comment by flawedworld** [comment]
See: https://grapheneos.org/usage#carrier-functionality

**Comment by mathiser** [comment]
Dear @flawedworld 
Thanks for asking and for closing this so quickly. In fact my provider does support VoLTE and it has working fine on my previous iPhone.

**Comment by flawedworld** [comment]
You've been given the most likely reason for this to occur alongside instructions to troubleshoot. I suggest you follow the guide which was sent and provide further details following doing so.

>In fact my provider does support VoLTE and it worked on my previous iPhone.

It working on another device is not relevant.
