### ISSUE TITLE
Grant notification permission on Pixel 6 a

### ISSUE THREAD

**Issue by VRT-secure** [GrapheneOS/os-issue-tracker#1806]
I have installed the [Wasted](https://github.com/x13a/Wasted) application from _F-droid_ on my _Pixel 6 a_, but I can't give him permission to read my all notifications, to wipe all data in my phone. When I try give him the permission, I see a the message _Restricted setting_ 
_For your security, this setting is currently unavailable._

However on my _Pixel 4 a_ with _GrapheneOS_ and _Android 13_  I can do it and all functions work. 

Please help me, how to enable this?

**Comment by thestinger** [comment]
Standard Android 13 feature not specific to GrapheneOS. F-Droid uses legacy package installation API so apps are restricted from using extremely dangerous special access grants. You can disable it in the standard way via the 3 dot menu in app settings.

**Comment by VRT-secure** [comment]
Thank you!
