### ISSUE TITLE
My number shows up as suppressed/private sometimes on some devices

### ISSUE THREAD

**Issue by M0M097** [GrapheneOS/os-issue-tracker#1808]
I run Graphen OS (Android-Version 13) on my Google Pixel 5. The language is set to German. In the phone app, I made sure that I set „Einstellungen/Anrufe/Zusätzliche Einstellunen/Anrufer-ID“ to “Rufnummer Anzeigen” which probably translates to Settings/Calls/additional Settings/Caller-ID” -> “show number”. However when I call someone their phone says that my number is “private” more often than not. This only happens since a short amount of time (probably since the last update). Using third party phone apps does not change this behavior. Rebooting, and resetting all App settings and all network settings does not solve this issue. I have not yet tried to hard reset the whole device. 

I consider this to be a major bug. It already brought me into huge trouble when colleagues (which block suppressed numbers or do not pick up on a suppressed number) complained that I did not call them, although I did.

**Comment by M0M097** [comment]
I performed a factory reset (hard reset) right now and this did also not solve the issue

**Comment by flawedworld** [comment]
Toggle between the 2 modes, making a call inbetween switching between them. This is likely a carrier issue and not a GrapheneOS issue.

**Comment by M0M097** [comment]
To verify your assumption I reinstalled stock Android. This “solved” the issue. I made sure that I used the same carrier. So it seems to be a issue related the OS and not the carrier. I hence suggest to reopen the issue.

**Comment by thestinger** [comment]
This is not a GrapheneOS issue.
