### ISSUE TITLE
Broken app overview in landscape mode in secondary user profiles

### ISSUE THREAD

**Issue by MatsG23** [GrapheneOS/os-issue-tracker#1811]
# Steps to reproduce
1. Create secondary user
2. Download e.g. YouTube and play a video in fullscreen mode (anything in landscape orientation)
3. Swipe up the fullscreen gestures bar to open app overview

**Comment by Snailhail** [comment]
Can confirm the above with prior update.
Owner profile non affected transitions smoothly. Screenshotting,  or touching the screen will count as backing out will temporary fix It while in this state. 
I tried the newest update same issue with same over all results. Maybe worst with a rare freeze while recreating it on this page.

**Comment by Snailhail** [comment]
A temporarily work around intill It's fixed.
Go into Portrait Mode then rotate to Landscape Orientation won't work for everything.

**Comment by octocorvus** [comment]
Known upstream issue
