### ISSUE TITLE
Files: "Copy to..." doesn't show protected folders

### ISSUE THREAD

**Issue by Omrigan** [GrapheneOS/os-issue-tracker#1813]
I am trying to copy a file into the "Andriod/data/nodomain.freeyourgadget.gadgetbridge/files"

When I am browsing it, I can see the folder. When I am invoking "Copy to...", theere is no "data" folder

**Comment by thestinger** [comment]
Standard way this works.

**Comment by thestinger** [comment]
Apps should not need you to this. The app should be fixed.

**Comment by Omrigan** [comment]
> Standard way this works.

You mean the behavior I am observing is the one I would get on the stock android?
I was under the impression the stock android doesn't let you even browse `Android/data/...`, but I may be wrong.
 
I was able to do this with adb shell, so it is a bit inconsistent that I can't do the same from Files app.

> Apps should not need you to this. The app should be fixed.

Yes, probably so, but when you are already at the point where the app does that, there isn't much of a choice. The alternative to GadgetBridge would be going back to proprietary wearables app to sync, which is way worse privacy-wise.
