### ISSUE TITLE
Apps pinging when in restricted battery. 

### ISSUE THREAD

**Issue by Franz-Straus** [GrapheneOS/os-issue-tracker#1817]
I use a service called NextDNS. In case you have not heard of it it can be used as a dns-over-tls provider which can be customized. But the important detail here is that it has a tab which displays logs of connections made by your device, and i would notice apps which I have not opened in a long time, which I have also set in restricted battery mode in the settings, would be making connections, Tutanota for example would ping mail.tutanota.com or Google Translate translate-pa-googleapis.com. This happens after the phone is rebooted. I wanted to ask if it is normal for restricted apps to behave like this.

**Comment by flawedworld** [comment]
Them being restricted has nothing to do with them (not) being able to make connections.

**Comment by thestinger** [comment]
Restricted battery use means they cannot start themselves via jobs, alarms, etc. and don't receive most broadcasts. The apps can still be started by other apps, including by the user via the launcher or another app. If they use FCM, it will continue waking them when they receive push messages, and the same applies to anything else like that. If you want the app disabled, you should use our feature for disabling the app.
