### ISSUE TITLE
Organic maps over the lock screen

### ISSUE THREAD

**Issue by abkil** [GrapheneOS/os-issue-tracker#1819]
Hello,

When Organic maps is open, if I turn the screen off then turn it on again, Organic maps is still open and I can use all functionalities. If I press on the **back** button, the lock screen appear. 

I get this bug only with that app.
My phone is locked with pin + fingerprint

Little precision: after turning off the screen, I wait a bit before turning it on again. Even one minute.

Phone: Pixel 6
Build number: TQ1A.221205.011.202212110

**Comment by TheTacomancer** [comment]
That's a feature of Organic Maps. It's so you can view your map without unlocking the screen while driving. You can turn it off in the settings
![Screenshot_20221214-170510](https://user-images.githubusercontent.com/103864390/207741824-88bd87a5-7aef-4489-8a69-b1c101fb6199.png)
