### ISSUE TITLE
SMS sending blocks after MMS sending prompt

### ISSUE THREAD

**Issue by MDingas** [GrapheneOS/os-issue-tracker#1820]
1. Open messages app
2. Send MMS
3. Receive prompt saying I cannot send MMS unless i activate that feature in the settings
4. All future attempts to send SMS would block 
5. After activating the MMS feature in the settings, SMS would start working as expected

I would assume that those two features shouldn't collide, and after MMS fails, SMS shouldn't be affected

**Comment by thestinger** [comment]
This seems like a carrier issue.

**Comment by thestinger** [comment]
We're not going to change this. It's not specific to GrapheneOS.
