### ISSUE TITLE
App Overview "App not available"

### ISSUE THREAD

**Issue by heuwerk** [GrapheneOS/os-issue-tracker#1822]
Hello dear developers,
I have noticed a problem with the app overview for about two weeks.
After a few hours of operation, apps that have been closed for a long time are displayed in the app overview and are marked as "App not available".

Newly opened apps are not displayed there at all.
Closing all apps with the button at the end of the app overview does not solve the problem. Only a restart improves the situation in the short term.
However, the problem then reappears after a few hours.

Device: Google Pixel 5
OS version: GrapheneOS 13, QPR1
Build: TQ1A.221205.011.2022121400

I have recorded this behaviour with Screen-Capture, unfortunately the file is to large, and I have no tool available to reduce the size.
I will try to upload it to this thread if you can't replicate this Issue.

**Comment by thestinger** [comment]
It's an upstream Android 13 QPR1 issue impacting secondary users. It's not GrapheneOS specific.

**Comment by heuwerk** [comment]
Thank you for the answer,
I have noticed this behavior so far only on my main profile. But that may be because I don't use the secondary much lately.

**Comment by thestinger** [comment]
We currently think it happens after switching user profiles. Can you replicate it after rebooting without doing that?

**Comment by heuwerk** [comment]
I tried to replicate without switching profiles for ~30 min, seems to work just fine.
I'll update this thread if I find any problems.

**Comment by heuwerk** [comment]
Since the latest update, the problem seems to have been solved.
At least it no longer occurs on my device.
So I will close the issue now.

**Comment by heuwerk** [comment]
The Issue appers to be back again on my devices after I changed profiles. So same state as before.

**Comment by r3g-5z** [comment]
This should be solved in the next GrapheneOS release. A fix was found.
