### ISSUE TITLE
Screen stopped working in Pixel 6A

### ISSUE THREAD

**Issue by cherez0ff** [GrapheneOS/os-issue-tracker#1824]
Can't be sure if this is a software or hardware issue, but yesterday noon I have installed latest update and yesterday evening screen stopped working. It makes sounds, by an accident even made an emergency call, but I can't seem to do anything with the screen. Can't even reboot it blindly. Tried "adb devices" - list is empty. Right before the issue I opened a case with Bluetooth buds, so they likely have connected, maybe related to the issue.
Any thoughts?

**Comment by thestinger** [comment]
You can hold power to force it to shut down. This isn't enough info for us to act on it. It could be a hardware issue.

**Comment by cherez0ff** [comment]
It's not enough to hold power button to force shut down, btw. It's "volume up" and "power" buttons at the same time for 10 seconds - to reboot. That's for anyone who come here for a quick fix of a screen issue

**Comment by whereskarlo** [comment]
> Can't be sure if this is a software or hardware issue, but yesterday noon I have installed latest update and yesterday evening screen stopped working. It makes sounds, by an accident even made an emergency call, but I can't seem to do anything with the screen. Can't even reboot it blindly. Tried "adb devices" - list is empty. Right before the issue I opened a case with Bluetooth buds, so they likely have connected, maybe related to the issue. Any thoughts?

I also noticed this issue while streaming music over bluetooth, but it has happened when not connected to bluetooth as well. We need some log files.

**Comment by thestinger** [comment]
#1830
