### ISSUE TITLE
Fake permissions data to apps

### ISSUE THREAD

**Issue by BetaAthe** [GrapheneOS/os-issue-tracker#1826]
Similarly to what happens with Storage Scopes, I was wondering if it would be feasible to implement something similar for the rest of the permissions.

I know that xprivacylua exists and I've already read the thread on reddit about it: https://www.reddit.com/r/GrapheneOS/comments/ch5kv8/is_magisk_and_edxposedxprivacylua_working/

From that thread, I can see that no app could provide that data forgery flawlessly, but I was wondering if the OS itself might be able to do it. Some use cases I thought are:
* Disallowing access for certain apps to some or all phone accounts.
* Only allowing apps to see and interact with a defined set of apps. Maybe I want an app A to see that I have installed an app B, but I don't want it to see that I have app C.
* Being able to run apps that refuse to work unless you provide them with enough permissions.

I know that some of these use cases can be solved with user profiles, but this would mean that for each app I would nearly need an equivalent amount of user profiles.

**Comment by thestinger** [comment]
This needs to be handled case-by-case. We already have a planned Contact Scopes feature.
