### ISSUE TITLE
Pixel 5 - SMS / MMS

### ISSUE THREAD

**Issue by LunchBoxC** [GrapheneOS/os-issue-tracker#1827]
Since the last stable update pushed I can't send SMS or MMS messages.

"Sending..." Is the message status. Upon reboot all messages change to "Not sent!"

To verify its not my carrier, I took my sim card out and put it into an old Samsung I have and it works on that phone.

Also the battery usage since the last update is a lot worse but I can't seem to pin it down to anything. I haven't installed or changed anything. Just wanted to mention it in case its connected to this.

Thank you.

**Comment by thestinger** [comment]
Unable to replicate this. Please reset your network settings via Settings -> Reset where that's an option.

**Comment by thestinger** [comment]
Try without LTE only mode if you're using that, which should be handled by resetting network settings among other things.

**Comment by LunchBoxC** [comment]
Hi there,

I've done a Network reset, restarted the phone for good measure and made sure I'm set to 5G (Reccomended) and not LTE or LTE Only and still the text message problem persists. 

Any insight would be great. I'm texting from my Samsung at the moment until I can get this figured out.

Thank you.

**Comment by LunchBoxC** [comment]
OK, something I just figured out...

Large amount of text SMS messages will cause "Sending..." And delay all other SMS messages from sending.

Short messages will send and MMS messages if there isn't a pending large text SMS waiting to send.

I can work around this but it would be great to send large texts again as in the past.

Thanks kindly

**Comment by thestinger** [comment]
Unable to reproduce this and it's likely a carrier issue.
