### ISSUE TITLE
Lock screen clock exceeds display border (Pixel 6a)

### ISSUE THREAD

**Issue by unnavailable** [GrapheneOS/os-issue-tracker#1828]
On lock scren, if display size setting is set to more than minimum vallue (which is the default), the clock display on the lock screen exceeds off-screen. (On pixel 6a running android 13 december 5th security update)

This isn't observable if the double-line clock is in effect, which only happens if no notification is displayed on lockscreen. This would explain why it is not visible when testing with default settings and no notification.
The effect gets worst as the display size is set to bigger vallues.

This issue started two stable updates ago ( android 13 november security update) on my pixel 6a.

(Please re-direct me if I'm not isuing this in the right place, I'm new to this.)

**Comment by r3g-5z** [comment]
Known AOSP issue, no plans to work on it on our end. A clean patch from the community may be accepted solving this.

https://github.com/GrapheneOS/os-issue-tracker/issues/1225
https://github.com/GrapheneOS/os-issue-tracker/issues/968
