### ISSUE TITLE
Cannot add new Do Not Disturb schedule to secondary profile

### ISSUE THREAD

**Issue by kizniche** [GrapheneOS/os-issue-tracker#1829]
I am unable to add new Do Not Disturb schedules to secondary profiles. I've tested with several secondary profiles, including newly-created ones. This does not affect the primary/owner profile. A user in the GOS Dev chat has reproduced this issue.

Version: GOS TQ1A.221205.011.2022121400.

Steps to reproduce:

 - Create new secondary profile
 - Log in to new profile
 - Open Settings -> Notifications -> Do Not Disturb -> Schedules
 - Press "+ Add more"
 - Select either Event or Time
 - Enter a name and press "ADD"
 - Observe that a new schedule is not created

**Comment by thestinger** [comment]
This is an upstream Android issue. We're unable to fix all Android bugs ourselves.

**Comment by r3g-5z** [comment]
Is this still an issue on latest GrapheneOS release (QPR2)?
