### ISSUE TITLE
Pixel 7 rebooting randomly after 2022-12-14 update

### ISSUE THREAD

**Issue by 128bitpotato** [GrapheneOS/os-issue-tracker#1832]
Since last update my Pixel 7 has rebooted 3 times randomly. It's happened when I'm just casually using it, both when browsing the web and checking my mail through the FairEmail app. It doesn't boot all the way back at the yellow info where it states another OS  is running, but rather from where the GrapheneOS logo is displayed. After accessing the lock screen again all previous sessions and processes have ended and starts booting again, so previous unsaved work is lost.

Thanks for any help!

**Comment by thestinger** [comment]
Not reproducible and not enough information provided to do something about it. There are already similar issues filed. It may be a hardware issue with your device or an upstream Android issue.
