### ISSUE TITLE
Night Light does not turn off on schedule, colour correction (colourblind mode) and colour inversion cannot be turned off without restart.

### ISSUE THREAD

**Issue by xxxmlgglmxxx** [GrapheneOS/os-issue-tracker#1833]
I have put Night Light on the default schedule 10 pm start 6 am end, and it does not stop turn off automatically, but can be turned off manually. I have also noticed that it is possible to disable colour correction or colour inversion (but not together) by turning one off and the other on.

I am using a pixel 7.

**Comment by thestinger** [comment]
Please search before filing issues. This is also an upstream issue, not caused by GrapheneOS.

**Comment by nkgrush** [comment]
Same issue
