### ISSUE TITLE
Automation feature

### ISSUE THREAD

**Issue by 8473795** [GrapheneOS/os-issue-tracker#1834]
Would be great to include a simple automation feature in GrapheneOS such as Bixby Routines on  Samsung devices.

For example to turn on BT when a connection to home wifi is lost and to turn on tethering when connected to a certain BT device, to turn off tethering when BT connection is lost etc...

IMHO it would not only add to convenience and overall usage experience, but also improve privacy and security if implemented and used properly.

For example, there is no reason to have BT turned on unless I'm in my car. But the average user will not manually turn it on and off all the time, they will just leave it on permanently.

As far as I am aware, third party apps such as tasker are not able to do that any more. They also require a ton of very intrucive permissions, have trackers and are far from secure.

Would be great to see this implemented into GrapheneOS in a secure way.

**Comment by thestinger** [comment]
These aren't the kind of features we work on in GrapheneOS. It's already possible to use apps to provide most of this kind of functionality, and anything doable with an app is explicitly out of scope for GrapheneOS. That includes apps which can be written but aren't yet written. It's not our role to write a good implementation of every possible useful app.
