### ISSUE TITLE
Restrict access to wallpaper images

### ISSUE THREAD

**Issue by ph00lt0** [GrapheneOS/os-issue-tracker#1838]
It seems that any app has access to the wallpaper image. This may put users as unknown and unintended risk. 
Please add an option to (by default) restrict access to the wallpaper image by third party apps.

related somewhat to https://github.com/GrapheneOS/os-issue-tracker/issues/1495

**Comment by thestinger** [comment]
We don't need multiple issues about the same topic. It's part of that.

**Comment by thestinger** [comment]
There's a permission check for this. If you think otherwise please explain what you mean.

**Comment by thestinger** [comment]
It can be considered part of the same issue.

**Comment by ItamiWasNotTaken** [comment]
> It might actually be, didn't think of this possibility. I never heard of this being possible, you may be right. But it is also odd because other things placed on the homescreen are not visible like existing app shortcuts and widgets, so how would that work?

It seems it may work similarly to how the AOSP phone app works. The AOSP varient is currently translucent allowing the user to see the wallpaper.

**Comment by thestinger** [comment]
It needs to be confirmed that apps can access this without the relevant media permission before we can have an issue open about it.
