### ISSUE TITLE
[FEATURE REQUEST] Add call recording option

### ISSUE THREAD

**Issue by W1zardK1ng** [GrapheneOS/os-issue-tracker#1839]
Hi Team,

Please add option to record the calls in default phone app, there are lots of third party apps to to record calls but none of them really works, either they wont record the voice or the recording is not clear.
Call recording have helped to prove something legally so this will be a nice addition to have.

**Comment by r3g-5z** [comment]
Requested numerous times, please use the search feature.

Not planned to be worked on our end. Various implementations people have suggested have too many issues, concerns, lack of code quality, etc. 

A clean and proper patch from the community may be accepted provided they make any changes we request.

**Comment by tdbe** [comment]
> Requested numerous times, please use the search feature.
> 
> Not planned to be worked on our end. Various implementations people have suggested have too many issues, concerns, lack of code quality, etc.
> 
> A clean and proper patch from the community may be accepted provided they make any changes we request.

Just for clarity's sake:
- you're saying you don't know how to do it, and don't want to research it
- you want someone else to figure out a way to do it and propose it to you

Cool.
You (graphene) may not work for bounties, but perhaps someone can organize a bounty that people can crowdfund to get this dealbraker feature figured out. 

To the average user calling without recording sounds like saying "Our camera app can't record video and we don't plan to add this feature." 🙃
