### ISSUE TITLE
Manual installation fails if the directory contains a space

### ISSUE THREAD

**Issue by kittencatten** [GrapheneOS/os-issue-tracker#1840]
Initially submitted to the forum

See an attempted installation on Debian 11 in a directory that has a space in its path:
```
user@PC:~/Documents/Pixel 7$ export PATH="$PWD/platform-tools:$PATH"
user@PC:~/Documents/Pixel 7$ fastboot --version
fastboot version 33.0.3-8952118
Installed as /home/user/Documents/Pixel 7/platform-tools/fastboot
user@PC:~/Documents/Pixel 7$ cd panther-factory-2022121400/
user@PC:~/Documents/Pixel 7/panther-factory-2022121400$ ./flash-all.sh 
./flash-all.sh: 45: /home/user/Documents/Pixel: not found
./flash-all.sh: 45: [: -ge: unexpected operator
fastboot too old; please download the latest version at https://developer.android.com/studio/releases/platform-tools.html
user@PC:~/Documents/Pixel 7/panther-factory-2022121400$ which fastboot
/home/user/Documents/Pixel 7/platform-tools/fastboot
user@PC:~/Documents/Pixel 7/panther-factory-2022121400$ 

```

it appears to me that the line `if ! [ $($(which fastboot) --version | grep "version" | cut -c18-23 | sed 's/\.//g' ) -ge 3303 ]; then` fails if the directory contains a space. I'm not really good enough at bash to know how to fix this but I do know it's a "bash" type of issue. It seems to me the message about fastboot being out of date is caused by this command not being evaluated properly rather than fastboot actually being out of date.

removing the space from "Pixel 7" works around this issue

**Comment by thestinger** [comment]
The upstream AOSP flash-all.sh script is not written to handle spaces in paths. This code wasn't written by us.
