### ISSUE TITLE
Sepolicy change for Pixel 7 / 7 Pro

### ISSUE THREAD

**Issue by popogomo** [GrapheneOS/os-issue-tracker#1841]
Google Camera's processing speed is very slow on Pixel 7 / 7 Pro devices, especially, Portrait processing that take over a minute to process. Many people reported this issue on GOS forums: https://discuss.grapheneos.org/d/1815-google-camera-very-slow-portrait-mode-processing/25

There was an sepolicy change needed for the Pixel 6 / 6 Pro in order to allow the camera software to access the DSP for accelerated image processing. Before that, Google Camera on Pixel 6 was slow too (please see here: https://issuetracker.google.com/issues/227166806#comment8

Was that change incorporated in the Pixel 7? Has it been properly validated that it doesn't need some tweaking for the minor differences? Thanks.

**Comment by thestinger** [comment]
It works fine on the Pixel 6 without privileged hardware access. It will likely get fixed in Google Camera.

**Comment by r3g-5z** [comment]
The sepolicy being referenced was intentionally removed by GrapheneOS to simply prevent it having privileged direct hardware access as attack surface reduction. Nothing is blocking it from using the hardware unprivileged at the cost of processing performance, it just does not have privileged direct access like it does on stock OS.

No plans to add this sepolicy back. Said issue will likely get fixed.

**Comment by Rubber-Duckie** [comment]
In summary, it appears that GrapheneOS restricts apps (including the Camera app) from utilizing the powerful image processing DSP hardware found in Pixel devices. Consequently, this could result in either severely impaired or substandard image processing. This approach seems contradictory to the project’s overall purpose. Essentially, GrapheneOS undermines the phone’s camera functionality, which is a significant selling point. Perhaps this restriction should be optional, allowing users to toggle it on or off.

Regarding privileged direct access to the DSP, could it be firewalled? For instance, could API calls be intercepted and only expected ones allowed?
