### ISSUE TITLE
Unopened apps appear on multitasking screen; 

### ISSUE THREAD

**Issue by buttke** [GrapheneOS/os-issue-tracker#1851]
Hello, when I open an app and close it, it remains available in multitasking with a gray preview and  gives the message "App isn't available."

I am using the Pixel 4a 5g
Build TQ1A.221205.011.2022122000

![Screenshot](https://user-images.githubusercontent.com/88161263/209427016-067faebd-ccf6-4abe-97d4-73ecacc4fe3f.png)

**Comment by r3g-5z** [comment]
Duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/1822

Known upstream bug

**Comment by r3g-5z** [comment]
A fix was found and will be included in the next GrapheneOS release.

**Comment by AJP2030** [comment]
Thanks for letting me know

-------- Original Message --------
