### ISSUE TITLE
Cannot play Clash of Clans on GrapheneOS

### ISSUE THREAD

**Issue by vpngall** [GrapheneOS/os-issue-tracker#1852]
Device info: oriole, TQ1A.221205.011.2022122000

Recently, Clash of Clans applied patch to block playing game on emulators, rooted phones.After updating Clash of Clans App on Play Store, I cannot open/enter the game. I can only see black screen like opening game on emulator/rooted phone. I never unlocked Bootloader/modified system.
Please give me a advice/workaround. Thanks for the great OS?

**Comment by r3g-5z** [comment]
They now require ptrace syscall access.

```
12-25 04:37:03.125  9521  9521 W ll.clashofclans: type=1400 audit(0.0:20575): avc: denied { read } for name="ptrace_scope" dev="proc" ino=1290166 scontext=u:r:untrusted_app_30:s0:c186,c256,c512,c768 tcontext=u:object_r:proc_security:s0
tclass=file permissive=0 app=com.supercell.clashofclans
12-25 04:37:06.353  9826  9826 W ll.clashofclans: type=1400 audit(0.0:20782): avc: denied { read } for name="ptrace_scope" dev="proc" ino=1298478 scontext=u:r:untrusted_app_30:s0:c186,c256,c512,c768 tcontext=u:object_r:proc_security:s0
tclass=file permissive=0 app=com.supercell.clashofclans
```

Solvable by simply enabling Settings -> Security -> Enable native code debugging.

https://grapheneos.org/usage#banking-apps 
> Many of these apps have their own crude anti-tampering mechanisms trying to prevent inspecting or modifying the app in a weak attempt to hide their code and API from security researchers. GrapheneOS allows users to disable native code debugging via a toggle in Settings ➔ Security to improve the app sandbox and this can interfere with apps debugging their own code to add a barrier to analyzing the app. You should try enabling this again if you've disabled it and are encountering compatibility issues with these kinds of apps.
