### ISSUE TITLE
Phone toggle into off mode not working completely.

### ISSUE THREAD

**Issue by Snailhail** [GrapheneOS/os-issue-tracker#1854]
I toggle it off to on back to off, updated my phone & restarted, but I still receive phone calls;
yet SMS & call logs are not recorded along with SMS being toggle off correctly all this Is done in  a secondary profile & tested In other ones with toggle off with same result. 
Owner profile not tested for this.
I have access to the default telephone app, but not the data unsure if I'm supposed to be restricted such as default Messaging app with a prompt blocking me.

**Comment by thestinger** [comment]
It's normal to always receive calls. It's just how this works. It's different than texts.

**Comment by Snailhail** [comment]
I see, thank you. It's just the toggle naming misleads me with it saying "Turn phone calls & SMS on." other than that no further issues on this.
