### ISSUE TITLE
"Recent/open apps" is not accessible.

### ISSUE THREAD

**Issue by VulcanElf** [GrapheneOS/os-issue-tracker#1858]
"Recent/open apps" will not show recent apps used, nor is each app tappable. Upon clearing all recent apps OR swiping each app away, they reappear when "recent/open apps" section is accessed again.

https://wormhole.app/bxrX9#fHOFtTl4LsBsn7Ize1IXWg

**Comment by octocorvus** [comment]
Duplicate of #1822

**Comment by octocorvus** [comment]
A fix was found and is included in the next release of GrapheneOS

**Comment by VulcanElf** [comment]
Thank you for a quick prognosis.
