### ISSUE TITLE
AOD with flaws and differences compared to Google's AOD

### ISSUE THREAD

**Issue by fbfrank** [GrapheneOS/os-issue-tracker#1859]
Font has been updated just recently - good.
However, the alarm clock icon is set right next to the date or playing music information, and not being closer to the set alarm time, (where it links to). And the alarm clock icon is doubled, refer to screenshot.
![Uploading PXL_20221229_085629307~2.jpg…]()
![Uploading PXL_20221229_085534365~2.jpg…]()

In Google's AOD version, alarm time information is located in a different line.

**Comment by thestinger** [comment]
Your images didn't upload. We don't plan on changing the lockscreen UI.

**Comment by fbfrank** [comment]
"closed, as not planned"?
Seriously? So only issues which are known AND planned to be solved, are relevant?

In case this is an AOSP issue (general design flaws of AOD), what would you recommend?

Thank you!

Frank

29.12.2022 16:27:47 Daniel Micay ***@***.***>:

**Comment by fbfrank** [comment]
![PXL_20221229_085629307~2](https://user-images.githubusercontent.com/46959669/209978262-2888dd3f-5b19-4d65-959c-657dcc668a68.jpg)
![PXL_20221229_085534365~2](https://user-images.githubusercontent.com/46959669/209978301-a165c71e-8793-4d3e-8496-1b63059e2ffe.jpg)

**Comment by thestinger** [comment]
You can file issues about AOSP in the AOSP issue tracker. We can't track all upstream issues with AOSP in our issue tracker. It's simply unrealistic. We'll accept pull requests with fixes for AOSP deficiencies if they're well implemented, minimal and uninvasive.

**Comment by fbfrank** [comment]
So you're saying the reported issue is an AOSP one, right? So i will address it in the AOSP issue tracker then.
The updated font is an update you accepted from AOSP then?

Thank you!
