### ISSUE TITLE
Race condition when searching apps

### ISSUE THREAD

**Issue by bootlesshacker** [GrapheneOS/os-issue-tracker#1861]
When pulling up the app drawer and searching for an app, the list of apps filters to your search input as I would expect. In my instance, I search for an app using a search string that returns only one app result. This one result then appears in top left of app drawer as you'd expect, but tapping this app sometimes loads the GrapheneOS Apps app. This happens sometimes but seems easy to repeat if you try it enough. I presume the Apps app loads instead as it normally appears as the first app in the unfiltered list, so appears like it may be some sort of race condition. I've noticed this problem for a while but only worked out today what may be causing it.

Current build is TQ1A.221205.011.2022122700

**Comment by thestinger** [comment]
Apps version 8 has been released with fixes for these things. It's currently in the Beta and Alpha channel of the app repository.

**Comment by bootlesshacker** [comment]
I'm also still observing this issue following the update to version 9 this morning

**Comment by bootlesshacker** [comment]
That's exactly the problem I'm seeing

**Comment by maxammann** [comment]
> Pixel Launcher with the modifications they make to it.

Are we actually sure that the two launcher share code?

**Comment by yumeo-ch** [comment]
Does it really make it an upstream bug if it happens on no other os than grapheneos? It doesn't happen on pixel stock os. How are we so sure it's an aosp bug ?

**Comment by flawedworld** [comment]
The stock Pixel OS uses a proprietary fork of the AOSP Launcher - the Pixel Launcher - which has this fixed. The AOSP launcher is part of the upstream project GrapheneOS is based on, which is AOSP, hence this is an upstream issue. AOSP is filled to the brim with bugs, we cannot fix every bug and we have to prioritise more impactful issues. The goal of the project is not to fix every bug which appears in AOSP.

**Comment by maxammann** [comment]
Can we install the AOSP launcher on stock pixel? If yes, than this could reveal whether is is an OS bug or a launcher bug (I suspect launcher).

**Comment by r3g-5z** [comment]
No, AOSP Launcher3 depends on some privileged functionality and platform APIs.

**Comment by thestinger** [comment]
@yumeo-ch Android is a huge operating system and it's unreasonable to expect us to quickly fix all upstream Android Open Source Project bugs or even for us to be regularly working on those rather than on our own code. Using our issue tracker to attack the project this way is completely inappropriate. You can contact me and ask for your suspension to be lifted if you will avoid doing this again going forward.
