### ISSUE TITLE
GOS Gallery Location Detail

### ISSUE THREAD

**Issue by tomasdurham** [GrapheneOS/os-issue-tracker#1862]
I am not sure if I am in the right place for my input for the gallery app. 
The context first. I was testing the GOS camera and the location tag. After making some pictures I could not check on the same phone if the pictures have the location tagged. The Issue was, that the Gallery app not showing details for the location when I open the details from the picture. I could check the location tag on the computer and could approve that the GOS Camera works with location tag. 

**Issue/Improvement:** GOS Gallery App should also able to show details about the location and making automatic albums with locations. At this moment the GOS Gallery cannot show the details about location. Also the app don't make automatic albums for location. It just shows one Album with "no location".

**Comment by flawedworld** [comment]
The Gallery app will be replaced in future.
