### ISSUE TITLE
USB DAC sound distortion

### ISSUE THREAD

**Issue by JohannesFleischer** [GrapheneOS/os-issue-tracker#1864]
Device: Pixel 6a
Version: TQ1A.221205.011.2022122700
USB DAC: Audioquest DragonFly Cobalt
Occurances: Tidal (hifi & master) & Antennapod (MP3)

Problem:
The playing sound is distorted irregularly (every 15 to 60 minutes) for a few (approx. 5-10) seconds. It is independent of the quality of the sound, since this occurs with podcasts as well as with high-resolution music. It is also independent of the input, since it cannot be reproduced by replaying a passage where the problem occurred. 
So far, the problem has only occurred with streaming and not with local files, but I have also tested it mainly with streaming. 

Hardware damage is not a possible cause. Since I have tested all external parts individually and the phone is only a few weeks old and has not shown any abnormalities in tests for loose contacts. 

I suspect the problem is related to the previous DAC issues that the Pixel 6 series had in the past. As summarized [here](https://www.reddit.com/r/GooglePixel/comments/ri7ibv/issues_with_usb_dacs_on_the_pixel_6_series_an/) for example.

**Comment by thestinger** [comment]
Not much we can do about this. We'll continue shipping upstream changes which may improve it if it's a software or firmware issue.
