### ISSUE TITLE
Weather data never loads from OpenWeather

### ISSUE THREAD

**Issue by Syberkonda** [GrapheneOS/os-issue-tracker#1865]
I have used the app for a few months now, and have not been successful in getting OpenWeather to work. Accuweather works though. Using a Pixel 6 Pro on the latest release of GrapheneOS.

**Comment by thestinger** [comment]
Please ask for help on https://discuss.grapheneos.org/. There's no indication of a bug.

**Comment by thestinger** [comment]
You aren't giving details about your setup such as whether you're using sandboxed Google Play, whether you're using the default location rerouting or other information. Please give that when asking on the forum.

**Comment by Syberkonda** [comment]
Sorry, meant to post this in the Geometric Weather forum. Not sure why I posted it here.

**Comment by thestinger** [comment]
Posting on the GrapheneOS forum may get you help. Someone else can try the app or may have already tried it.
