### ISSUE TITLE
Pixel Buds Pro No Widget Option, and Poor Integration

### ISSUE THREAD

**Issue by seniorm0ment** [GrapheneOS/os-issue-tracker#1866]
# Missing Widget

This is my most desired feature, can't figure out how to get it working.
There is no widget for the Pixel Buds. I've seen many people with it, and I have seen how they do it.
It seems like it should appear under the Pixel Buds app under More Settings and there should be an option to add widget. There is not. 
However I have also seen people grab it from a widget categorized under "Settings Services" or "Battery". It shows the phone battery and pixel buds battery levels.

https://9to5google.com/2021/08/25/pixel-buds-update-adds-android-home-screen-widget/
Example showing add to home screen in the app: ![App](https://9to5google.com/2021/08/25/pixel-buds-update-adds-android-home-screen-widget/)
![Settings Services Example](https://imgur.com/a/RyrQBwp)
![Battery Example](https://i.imgur.com/fxoA3d5.png)

# Poor Settings Integration

As far as I am aware, on Pixel devices when you have Pixel Buds connected and go to bluetooth, click the gear icon next to the Pixel Buds, it should take you to a screen to change pixel buds settings (the Pixel Buds app). Instead it takes you to generic bluetooth device settings.

I already have the Pixel Buds app installed, as well as Google Services (not signed in). The Pixel Buds themselves work fine.
Example of how it is expected to work at 1:45 in this video: https://www.youtube.com/watch?v=1OVuiBznnws&t=102

# Blank Icons

The one other small thing I notice is in the Pixel Buds App, the little icons under my devices are completely blanl for the earbuds and the case when it's connected. 
Example of what the icons should look like at 1:45; https://www.youtube.com/watch?v=1OVuiBznnws&t=104

It's little things like this that make Graphene feel a bit unpolished compared to stock OS or Apple iOS. Whether or not any of these are Graphenes fault, I am not sure. However I know missing images in Settings are an issue still. 
I love Graphene and just want it to feel and look good and retain as much functionality as possible from stock os as possible while obviously being as privacy friendly as possible. I appreciate the developers time and work.

**Comment by maade69** [comment]
Regarding the widget, its specific to stock OS and is not a part of AOSP. Im not sure why there is no icons, but its definitely not a GrapheneOS problem. There is not much we can do about it.

**Comment by seniorm0ment** [comment]
Understandable about the icons.
As far as the widget goes, is there anything we can do to integrate this or replicate it? It would be extremely nice.
