### ISSUE TITLE
Option Request: Auto Lock After User Defined Idle Time Interval

### ISSUE THREAD

**Issue by jsaccountsignup** [GrapheneOS/os-issue-tracker#1867]
**Issue:** use of fingerprint phone unlocking opens user up to compelled unlock by government officials (or other malicious actors). A user cannot be compelled (legally) by government officials to enter or give up their PIN.

**Current workaround:** To more securely use fingerprint unlocking, the user can long hold the power button and force a lockdown when not using the phone. Alternatively, the user can enable automatic restart if not unlocked within x time.

**Issues with current workarounds:** Use of a force locked down requires the user to always remember to manually lock the phone. Automatic restarting has at least two issues: 1) it causes the phone to restart even when not previously unlocked after the restart (needlessly cycling the phone every x interval). 2) a restarted but not yet unlocked phone will not show any new notifications (even with the option enabled) until the phone is unlocked, thereby preventing glancing at the phone.

**Proposed solution:** Create an option to require the phone to be unlocked via PIN after x time of idling. This prevents all issues with the workarounds listed above, while simultaneously increasing user trust in their ability to securely use fingerprint unlock without fear of compelled fingerprint unlocking.

**Comment by thestinger** [comment]
The primary lock method is already required after a certain amount of time and we have an issue open about making it configurable. The auto-reboot feature is much better because it puts everything back at rest.

**Comment by thestinger** [comment]
https://github.com/GrapheneOS/os-issue-tracker/issues/14

**Comment by thestinger** [comment]
It requires primary unlock once every 48 hours by default. It's not based on how long the phone has been left locked but rather it's mandatory at that interval in general.
