### ISSUE TITLE
Unable to disable "Always allow auto-updates of config files and resources"

### ISSUE THREAD

**Issue by dln949** [GrapheneOS/os-issue-tracker#1869]
Pixel 6, Graphene 2022122700

In the Graphene "Apps" application, in Settings, there is a setting for "Always allow auto-updates of config files and resources", that on my device is enabled.  When I try to disable that setting, it doesn't "stick" - When I go back into those settings it is enabled again.  

Why am I not able to disable that setting?

**Comment by thestinger** [comment]
Fixed for the next release.
