### ISSUE TITLE
screen freezes and graphene appears to reboot itself

### ISSUE THREAD

**Issue by dln949** [GrapheneOS/os-issue-tracker#1870]
Pixel 6, graphene TQ1A.221205.011.2022122700

In the past few days I noticed that at seemeingly random times, no matter what I may be doing with the phone, it "semi" reboots to the grapheneOS splash screen, and then I have to re-enter the passcode to access the phone again.  In more detail what I experience is this:  The screen I'm working on becomes non-repsonsive for perhaps ten seconds, the the screen turns black for maybe five seconds, and then the phone is at the graphene logo splashscreen for like five seconds while the phone completes what looks to me like the final stage of booting itself.  Then I'm back at a normally working graphene phone, but whatever windows/applications I had running are no longer in their previous state.  I don't know how to diagnose and fix this.  

After the last time it happened, and after I regained access to the phone, I did the "Bug report" thing under developer options, but that produced a whole bunch of files, I don't know which one of those would be of interest (nor do I know how to read them to recognize if there's any personally sensitive data in them - sorry, I'm very new to this stuff).  If someone could advise me on which file would be useful for this I can attach it.

**Comment by thestinger** [comment]
It's easier to get logs with `adb logcat` but you can also get them from the relevant bugreport txt file in there and cut out the relevant portion. It's easier with adb logcat in practice.

**Comment by dln949** [comment]
I ran the adb logcat command, it produced a large file.  I knew that an unexpected reboot happened sometime between 4 PM and 5 PM on Jan 2, so that is the selection of the file that I'm uploading here.  Tell me if you need more.  (I don't know how to interpret any of the stuff in this file.)  
[logs.txt](https://github.com/GrapheneOS/os-issue-tracker/files/10334523/logs.txt)

**Comment by muhomorr** [comment]
@dln949 Need to see earlier portion of the log. The interesting part (what caused the `OutOfMemoryError`) is missing.

**Comment by dln949** [comment]
this version goes back an extra five hours, the log doesn't have any entries earlier than what is shown in this attachment.  file:///home/main1/Desktop/bug/logs2.txt

**Comment by dln949** [comment]
file:///home/main1/Desktop/bug/logs2.txt

**Comment by dln949** [comment]
This version goes back to the earliest entry in the log file, back an additional five hours.  

[logs2.txt](https://github.com/GrapheneOS/os-issue-tracker/files/10334791/logs2.txt)

**Comment by muhomorr** [comment]
@dln949 The system log is still cut off from the same point. Try `adb logcat -d`, might help if the log hasn't rotated yet.

**Comment by dln949** [comment]
The files I provided were the result of running this command:  adb logcat -d

**Comment by muhomorr** [comment]
@dln949 The logs rotated then, or were cleared for some other reason.
The next time this issue occurs, capture a bug report immediately:
`adb bugreport`

**Comment by dln949** [comment]
Ok, I will do that and report back here.  

Question:  How does   adb bugreport   differ from    adb logcat   ?

**Comment by muhomorr** [comment]
bugreport includes much more info about overall system state:
https://source.android.com/docs/core/tests/debug/read-bug-reports

**Comment by dln949** [comment]
The mystery reboot happened again, so within a couple minutes of the phone rebooting I ran  adb bugreport  , it produced an 11 MB zip file.  Do you want me to upload here the entire zip file, or just a certain file within it?  (The bugreport text file inside the zipped archive is almost 40 MB.)

**Comment by muhomorr** [comment]
Send the entire zip file to my Matrix: @muhomorr:matrix.org

**Comment by dln949** [comment]
I'm sorry..... I've never communicated with an individual's matrix address.  How do I send that to your matrix address?  I'm assuming my email application won't be able to do that???

**Comment by muhomorr** [comment]
Send it to my e-mail: muhomor.dmitry@gmail.com

**Comment by dln949** [comment]
I sent it to your gmail email address.

**Comment by thestinger** [comment]
This appears to be an upstream issue. We'll continue trying to work on issues like this but I don't think we need to keep open issues about each.
