### ISSUE TITLE
Pull Request: SystemUI: Implement hide gestural navigation hint bar

### ISSUE THREAD

**Issue by Sn0whax** [GrapheneOS/os-issue-tracker#1872]
Please note this is a reference to: https://github.com/GrapheneOS/os-issue-tracker/issues/1521

This is a request to pull the following from LineageOS:
https://review.lineageos.org/c/LineageOS/android_frameworks_base/+/337879
https://review.lineageos.org/c/LineageOS/android_packages_apps_Settings/+/337876

**Comment by r3g-5z** [comment]
We're not keeping issues like these open.

The commits you linked are not something we can merge. They depend on LineageOS's APIs that are not in AOSP and we do not want.

**Comment by r3g-5z** [comment]
The comment from https://github.com/GrapheneOS/os-issue-tracker/issues/1521#issuecomment-1260001396 still applies here.

**Comment by thestinger** [comment]
We could consider a toggle to hide the hint, but not the reserved space for non-edge-to-edge compatible apps. It needs to be pull requests, not a feature request, and needs to be done how AOSP would do it in a minimal uninvasive way.
