### ISSUE TITLE
More info about changes

### ISSUE THREAD

**Issue by jcz1** [GrapheneOS/os-issue-tracker#1873]
Hello.

Please can you add a link to the changelog in the update notification and also a list of changes to the update menu in the configuration?

I would also greatly appreciate a brief summary on mastodon :-)

Thank you.

JK

**Comment by thestinger** [comment]
We can't maintain this in a bunch of different formats. It's provided on the website. We could link to it from the notification.

**Comment by thestinger** [comment]
https://github.com/GrapheneOS/platform_packages_apps_Updater/issues/22 is filed already.
