### ISSUE TITLE
Phone boots up to a black screen

### ISSUE THREAD

**Issue by mbkv** [GrapheneOS/os-issue-tracker#1875]
https://user-images.githubusercontent.com/9276556/210824635-a3f925aa-156c-4210-acf0-6bfc449f4e9b.mp4

The launcher seems to be busted since the last stable update. I have it set to automatically install updates, it updated itself last night and it won't get back into the launcher anymore. All other apps work just fine

Posting random values I found in "About phone" should it be necessary:
Model: Pixel 6
Hardware version: MP1.0
Hardware SKU: GB7N6
Build number: TQ1A.230105.002.2023010300

I also don't know if this is important but Google Play services is at version 22.48.14 (190400-493411920)

**Comment by thestinger** [comment]
There haven't been any changes to the launcher since the initial December release. You'll need to obtain logs since there's nothing to go from based on this. No one else has reported an issue so it must be something closely tied to your configuration.

**Comment by mbkv** [comment]
Sorry, wasn't familiar with what code lived where and wasn't aware it didn't change this update. rebooted and ran `adb logcat > file`. let me know if there's a different command you need. I'm not exactly familiar with android software development

[phonelogs.txt](https://github.com/GrapheneOS/os-issue-tracker/files/10355421/phonelogs.txt)

**Comment by thestinger** [comment]
@mbkv Have you tried rebooting the phone?

**Comment by mbkv** [comment]
yes I rebooted to get the logs just now and the same thing happened

**Comment by thestinger** [comment]
Can you try clearing the data of the launcher app?

**Comment by thestinger** [comment]
cc @muhomorr

**Comment by mbkv** [comment]
cleared cache and rebooted, then data and rebooted. same thing happens. I noticed there were some weird behavior with Muzei (a wallpaper app I use)

I disabled it and rebooted twice and it worked both times

**Comment by mbkv** [comment]
hmm. I just reenabled muzei and rebooted twice, worked both times. I think I also cleared the data for it, so maybe there's some edge case there?

Either way, I can't replicate it anymore and I don't know how common of a problem. Up to you on how to prioritize this. Thanks for the help!

**Comment by thestinger** [comment]
It's a known issue with Muzei. It's not specific to GrapheneOS as far as I know. We could add a warning about it somewhere but I don't think we'll do anything more about it.
