### ISSUE TITLE
Incorrect lock password after reboot - Phone lockout

### ISSUE THREAD

**Issue by nikosdano** [GrapheneOS/os-issue-tracker#1876]
I have a Pixel 6 running GrapheneOS. There are two profiles, the main and a guest one with sandboxed applications.
After rebooting, I saw a "optimizing x out of Y applications". Once is was finished, I was prompted to add my SIM password, I did. It worked properly and then I was asked my Password to unlock the phone. (I don't use a PIN or a fingerprint). The password is taken as incorrect and I have already tried over 40 times. It goes without saying that I am more than sure that I am entering the correct password. I tried to see if anything changed with the keyboard layout but there were no changed (although, I tried both with default simple keyboard and the English GrapheneOS keyboard). I have updated my phone so the recently found bypass (SIM swap) won't work. How could this be possible? What can I try to do?

**Comment by thestinger** [comment]
You aren't entering the correct password.

>  I have updated my phone so the recently found bypass (SIM swap) won't work.

GrapheneOS discovered that vulnerability in June. It was fixed upstream in the November security update. That's not really recent. Have you been going months without applying updates? That's really not good, and if you think this was one of the more severe vulnerabilities, you're very wrong.

**Comment by thestinger** [comment]
You might have recently changed the password or you forgot your owner profile password and were only using a secondary user for weeks or longer.

**Comment by nikosdano** [comment]
Hello, 

I am constantly updating the OS - maybe we mean differently what recent was. That's not the case. I know that the team constantly fixes the issues, and that's why I use it with my Pixel phone. I am not using the Guest profile that much and I have never ever changed my password. I can see the point that you would guess that, it's totally valid but it's not the case. The Guest has no password (I use a PIN) that I could be even confused with. It makes no sense to me and the only weird thing that happened worth to mention is the app optimizing for a few app +  that I the phone got accidentally wet but cleared immediately. There is no issue with the keyboard as it recognizes my SIM password.

**Comment by thestinger** [comment]
You must have forgotten the password which commonly happens right after people change it. If you've forgotten the password, then there isn't any solution beyond wiping data in recovery. You should try to get it unlocked before resorting to that. There's not really any way that we can help. You can try using a USB keyboard if you think it's somehow tied to the virtual keyboard not working properly.

**Comment by thestinger** [comment]
> app optimizing for a few app

This happens every single update. We started showing the progress a while ago.
