### ISSUE TITLE
Pixel 5A: Echo heard by other party on all calls

### ISSUE THREAD

**Issue by bjmuld** [GrapheneOS/os-issue-tracker#1877]
Title is fairly self-explanatory.

**Comment by thestinger** [comment]
Likely a hardware issue, particularly if it doesn't occur for speaker phone mode. Try speaker phone and if it doesn't occur there then this is likely a microphone hardware issue.

**Comment by vkde** [comment]
I had a normal voice call today and explicitly asked the remote party if they can hear themselves, and they said NO. The remote number was one of the people previously complained - same Pixel 6a w/ stock OS, same carriers (not one and the same for both, the same respectively). So some of the calls, not all. Will monitor and update if I can spot a pattern. Sorry I cannot help with more definitive clues. If you cannot at once spot the problem, please pause this issue, I'll update it if I have more info.
