### ISSUE TITLE
Clock app could include some more alarm features

### ISSUE THREAD

**Issue by VividLemon** [GrapheneOS/os-issue-tracker#1878]
There isn't a dedicated repo for the built in clock, so I'm not sure if this is a good spot to put this feature request

The default clock app lacks some basic alarm features that makes it a bit difficult to use.
I think the alarm app should be expanded to: 
1. Have a select date feature for creating an alarm, allowing you to create an alarm and set it on a specific future date. 
2. Allow you to specify if snooze is allowed
3. Naming alarms when creating them
4. The background color for the app could be a better color, but this is subjective.
5. Set an alarm to increase in volume over time.

The main issue is setting an alarm for a specific day, this is a feature I use often on my other devices. This is technically possible through setting it to "repeat" on a single day, but the focus is to set it, then not have it repeat.

**Comment by r3g-5z** [comment]
There aren't any plans to expand AOSP Clock until the existing severe upstream regressions with AOSP Clock are resolved. Currently, AOSP Clock is on AOSP 11 source code because of this.

If AOSP Clock is going to have changes, it needs to be based on AOSP 13.

It's better if you use a different alarm/clock app for now.

**Comment by VividLemon** [comment]
> There aren't any plans to expand AOSP Clock until the existing severe upstream regressions with AOSP Clock are resolved. Currently, AOSP Clock is on AOSP 11 source code because of this.
> 
> If AOSP Clock is going to have changes, it needs to be based on AOSP 13.
> 
> It's better if you use a different alarm/clock app for now.

Do you mind going into some detail about the issues?
