### ISSUE TITLE
Green location indicator very intrusive in the UI

### ISSUE THREAD

**Issue by pedro-araujo** [GrapheneOS/os-issue-tracker#1879]
Android 13 and GrapheneOS have now a location indicator in which it shows a green dot in the status bar every time the location is being accessed.

This is neat but it pops up whenever I am watching a full screen video. This is annoying and very distracting when we use apps like OwnTracks, which is an app that runs in the foreground all the time periodically sending the phone's location to a remote server.

For OwnTracks, the green dot is always constantly showing and interrupting the full screen video. Is there a way to disable the location indicator all together?

I appreciate the microphone and the camera indicators but I don't care so much about the location indicator. If I have already given location permissions to an app, most probably I don't want to micromanage every single location request the app makes.

I have tried to disable it with the following adb commands:
$ adb shell cmd device_config put privacy location_indicators_enabled false default
$ adb shell cmd device_config put privacy location_indicator_settings_enabled true default

But the only thing they do is to remove the list of apps in the indicator, it doesn't remove the green indicator itself.

I understand the original intent of the location indicator and I like it exists but it would be nice to either have an option to disable it all together or to manually add app exemptions. Or at the very least, make it so it won't interrupt full screen videos.

**Comment by lbdroid** [comment]
That green dot indicator very much has the same appearance when screen off, as a notification LED. Does anybody know where this is actually implemented? I'd love to be able to hijack it to make a fake notification LED.

**Comment by thestinger** [comment]
> Android 13 and GrapheneOS have now a location indicator in which it shows a green dot in the status bar every time the location is being accessed.

It's not a standard Android 13 feature and we had to finish their incomplete implementation of the feature.

**Comment by pedro-araujo** [comment]
Hi @thestinger,

Thanks for your reply but I don't agree with the closure of the ticket nor with this just being a "gripe".

I agree that my original post was very ambiguous but that was because I didn't know what to report something that was sensible for GrapheneOS developers, clearly from your comment, I didn't know where this location indicator was coming from (from Google or from GrapheneOS itself).

So if I have to report something, I will report that "location_indicators_enabled" doesn't actually disable the location indicator, it just removes the list of apps in that indicator.

I think this is a bug and "location_indicators_enabled" set to false should remove the location indicator altogether.

**Comment by thestinger** [comment]
It's not a bug and you're not meant to change the feature flags that way.

**Comment by pedro-araujo** [comment]
@thestinger How are they supposed to be changed then?

Enabling "location_indicator_settings_enabled" brings up a switch in the "Developer options" menu with the following description:
- "Status bar location indicator: show for all locations, including network and connectivity"

It seems that this option is supposed to disable the location indicator, right?

**Comment by thestinger** [comment]
If you're requesting that we add a toggle please file an issue requesting that specifically, nothing else.

**Comment by pedro-araujo** [comment]
Issue filed here: https://github.com/GrapheneOS/os-issue-tracker/issues/1886

**Comment by thariq-shanavas** [comment]
As of August 2025 (Android 16), the command to disable the notification about background location access **globally** appears to be this:
`adb shell cmd device_config put privacy location_indicators_enabled false default`

**Comment by thariq-shanavas** [comment]
Yeah, it looks like the feature flag is still there in QPR1, but the setting is not respected anymore. I'll keep checking if there is a way to disable the notification. For reference and as a pointer to anyone else who may want to poke around, `adb shell device_config list` shows you a list of all feature flags on your device.

The relevant flags are likely in the `location` or `privacy` group. You can filter the output by namespace, e.g.,  `adb shell device_config list privacy` or `adb shell device_config list location`. The location indicator flags are disabled on my device, but I am still getting spammed by the location access notification.

```console
thariq@desktop:~$ adb shell device_config list privacy
location_indicators_enabled=false
location_indicators_show_system=false
location_indicators_small_enabled=false
```

You can change the feature flags using the template `adb shell cmd device_config put privacy location_indicators_enabled false default`. Be warned though, **bad things will happen** if you muck around with feature flags without reading the documentation.
