### ISSUE TITLE
Tap on screen to wake and "lift to check" don't seem to work on Pixel 5 (on 4a it is fine)

### ISSUE THREAD

**Issue by mdotgru** [GrapheneOS/os-issue-tracker#1885]
Both options are activated in the lock screen options. When the screen goes dark, it disables completely the touch sensitivity so tap on screen to wake does not work. Interestingly, "lift to check" also does not work, though this can't have anything to do with the disabled touch screen.

I tried to disable and reenable these options in the lock screen settings, but they still did not work.
This issue is for the latest build number: TQ1A.230105.001.2023010300

**Comment by thestinger** [comment]
These definitely work fine. Perhaps you changed settings for OS, or you might have a hardware issue. Have confirmed it works though.
