### ISSUE TITLE
Make default setting for randomized MAC changeable

### ISSUE THREAD

**Issue by BluePixel4k** [GrapheneOS/os-issue-tracker#1888]
I didn't found an option to change the default setting "Use per-connection randomized MAC" to "Use per-network randomized MAC" or "Use device MAC".

It would be great, if there was an corresponding option for this in the "Network preferences" settings:
<img src="https://user-images.githubusercontent.com/77979781/211202208-df974050-3ba2-4667-bbac-0223490bc708.png" width="250" />
<img src="https://user-images.githubusercontent.com/77979781/211202204-d009bf67-0590-4af9-850c-b3bcdfd0f1d9.png" width="250" />

**Comment by thestinger** [comment]
This isn't planned. The current default is almost always what people want and using a per-network randomized MAC is an extremely rare situation. You should never need to use the device MAC.

**Comment by BluePixel4k** [comment]
I don't think this is a rare situation. 
With "Use per-connection randomized MAC" I get a new IP address every time I connect to the WiFi. This floods the "In use IPs" section of the router, and if the router owner has enabled notification for new devices (for security reasons), they will get a notification every time.
Therefore, I would prefer the "Use per-network randomized MAC" option as the default, since I only connect to known secure WiFis. 
And if I connect to an open WiFi, I would manually switch to "Use per-connection randomized MAC" for protection.

You don't always remember to change it manually to "Use per-network randomized MAC". Specially not technically savvy users remember on to change this setting for known secure WiFis (like my mother or sister).

Please think about it, I would be very happy to see this feature in GrapheneOS. 😇 
I think that shouldn't be difficult to implement for you.

**Comment by thestinger** [comment]
> With "Use per-connection randomized MAC" I get a new IP address every time I connect to the WiFi.

This is a good thing.

> This floods the "In use IPs" section of the router

That's normal and doesn't cause a negative impact. The least recently used IPs will get freed if the lease table is full.

> and if the router owner has enabled notification for new devices (for security reasons), they will get a notification every time

An actual attacker can simply mimic an existing MAC address, which they can see being broadcast over the air.

> Therefore, I would prefer the "Use per-network randomized MAC" option as the default, since I only connect to known secure WiFis.

Unsure what you mean by 'known secure' and how you know that to be the case. You're saying you believe each of the routers and each device on those networks is highly secure, receiving proper security patches and beyond that?

> And if I connect to an open WiFi, I would manually switch to "Use per-connection randomized MAC" for protection.

This is the opposite of the right way to do it. You have to remember to do that each time or there's a negative privacy impact when returning to the networks.

> You don't always remember to change it manually to "Use per-network randomized MAC". Specially not technically savvy users remember on to change this setting for known secure WiFis (like my mother or sister).

It doesn't need to be changed. You're also justifying why it doesn't make sense. The best default is the most private one.

**Comment by thestinger** [comment]
> I think that shouldn't be difficult to implement for you.

It makes far more sense for you to set it to per-network on the few networks where you want that. The per-network option is only there as a way to work around broken or annoying networks. If it's your network, you shouldn't need to use it. You're requesting that we implement and maintain an additional toggle indefinitely because toggling it to what you want a couple times is too hard for you. It just doesn't make sense. There's no way that the number of Wi-Fi networks you own is high enough for this to really help you.

It's not be implemented. It doesn't make sense as a feature. The current approach is already very good and very few people have even a minor gripe with it.

**Comment by BluePixel4k** [comment]
Thank you for your detailed explanations. You have convinced me. 😄 
So I will continue my existing procedure for some selected networks and change this setting to "Use per-connection randomized MAC".
