### ISSUE TITLE
Change network permission/access procedure

### ISSUE THREAD

**Issue by BluePixel4k** [GrapheneOS/os-issue-tracker#1889]
Currently, if I install a new app, there is the option to allow/disable the network permission.
<img src="https://user-images.githubusercontent.com/77979781/211203866-a57659a8-c8db-4372-a864-14ed43aa4846.png" width="250" />

It would be consistent/harmonious, if the permission is disabled by default and on the fist startup of the app an popup displayed like this:
<img src="https://user-images.githubusercontent.com/77979781/211204154-98dbad34-bea1-4f63-aec9-b03389f05012.png" width="300" />

The "while using the app" and "only this time" options would also be useful features.

**Comment by thestinger** [comment]
This isn't how apps are built to work.
