### ISSUE TITLE
Change sensor access procedure

### ISSUE THREAD

**Issue by BluePixel4k** [GrapheneOS/os-issue-tracker#1890]
Currently, if the option "Allow Sonsor permission to apps by default" is disabled, and I open a new app sometimes a notification appears:
<img src="https://user-images.githubusercontent.com/77979781/211204844-79f0c1d9-fc54-411d-91a3-e04aeea13041.png" width="250" />

It would be consistent/harmonious if sensor permission is disabled by default. When an app tries to access it, a popup is displayed:
<img src="https://user-images.githubusercontent.com/77979781/211205601-01498299-0918-49e4-bf46-43a702402c7e.png" width="250" />

**Comment by thestinger** [comment]
It doesn't work that way because apps do not request access to sensors and aren't prepared to handle it.
