### ISSUE TITLE
Overlooked Illustration

### ISSUE THREAD

**Issue by ItamiWasNotTaken** [GrapheneOS/os-issue-tracker#1891]
In a recent update, the missing illustrations were hidden since they would leave behind a large black box.

I am creating this issue since the "Quickly open camera" illustration background was overlooked.

![Screenshot_20230109-103044](https://user-images.githubusercontent.com/122293093/211345535-36b4c2d3-6ee1-4f0e-a254-f4e17df8bc12.png)

**Comment by flawedworld** [comment]
Fixed in https://github.com/GrapheneOS/platform_packages_apps_Settings/pull/135
