### ISSUE TITLE
[Pixel 7] Mismatching GPU driver version in the latest update

### ISSUE THREAD

**Issue by pedro-araujo** [GrapheneOS/os-issue-tracker#1893]
The 2022121400 release notes mention that the GPU driver for the Pixel 7 phones was bumped to r38p1:
- "kernel (Pixel 7, Pixel 7 Pro): update Mali GPU driver to r38p1"

I have the very latest update  on my Pixel 7 (TQ1A.230105.011.A2) and if I open "chrome://gpu" in Vanadium, the driver information is listed as:
- DRIVER_VERSION=36.0.001eac0 ACTIVE
- OpenGL ES 3.1 v1.r36p0

It seems that the phone is actually using the older Mali driver r36p0 rather than the newer r38p1. Is this expected?

The link to the release notes for 2022121400 can be accessed here:
- https://grapheneos.org/releases#2022121400

**Comment by thestinger** [comment]
It's supposed to be that way. We shipped the new kernel driver for the kernel privilege escalation vulnerability fixes, not the new userspace driver. The driver is backwards compatible with the old userspace driver. We do plan to update the userspace driver but haven't had time to do that yet.

**Comment by thestinger** [comment]
Also, the January release of AOSP has backports of most of the security patches to r36p0. Looking at the userspace driver version doesn't tell you what's patched or not due to backports and the kernel / userspace split.

**Comment by pedro-araujo** [comment]
Thanks for the answer.

Out of curiosity, what does it take to upgrade the GPU driver? Is it just pointing the build to the right GPU driver binary or does it need more work than that?

**Comment by thestinger** [comment]
Setting up build system to include a newer Mali userspace driver and making sure that works. Since they backported the same security patches that are in QPR2 Beta to the January release, we don't have much reason to rush that. We do want to sort this out so we can remain ahead of where they are going forward.
