### ISSUE TITLE
Tapping top of screen activates quick settings tiles

### ISSUE THREAD

**Issue by AnonRS3** [GrapheneOS/os-issue-tracker#1894]
Device: Pixel 4
OS version: Android 13, November 1st security patch (updated to latest via extended support release)

Steps to produce:

1) Tap the top part of the screen

2) The top left or top right quick settings tile activates, depending on what portion of the screen is tapped

This is especially annoying if one has the Bluetooth toggle in the top of their quick settings, as it causes frequent accidental disconnects. 

Here is a video showing this problem:

https://user-images.githubusercontent.com/54009117/211977027-3117e255-39e2-47b9-8f86-3d7ab28253b1.mp4

**Comment by thestinger** [comment]
It's an upstream AOSP quirk and has already been filed before.
