### ISSUE TITLE
Emergency menu not available from secondary profiles

### ISSUE THREAD

**Issue by bootlesshacker** [GrapheneOS/os-issue-tracker#1896]
Whilst on the lock screen for secondary profiles, the emergency button does not do anything. Only when unlocking the device does the emergency menu finally show. Works fine for primary profile

Pixel 6

TQ1A.230105.002.2023011000

**Comment by thestinger** [comment]
Normal upstream AOSP implementation. Not something that we're going to implement ourselves.

**Comment by bootlesshacker** [comment]
@thestinger wouldn't this be a bug, even if from upstream? I would have thought it wouldn't be a specific design choice to not allow emergency calls when on a secondary profile. I'm happy to raise the issue upstream if that's where the issue is?

**Comment by thestinger** [comment]
We can't track every upstream Android issue here. That's unrealistic. We close issues known to be upstream issues also occurring on the stock OS unless it's a special case. There's an upstream AOSP issue tracker.

**Comment by bootlesshacker** [comment]
@thestinger Thank you. I'll file the issue upstream
