### ISSUE TITLE
microphone issue joining conference call

### ISSUE THREAD

**Issue by RefinedSoftwareLLC** [GrapheneOS/os-issue-tracker#1901]
1st phone called a 2nd phone then conference called a 3rd phone. The joining 3rd phone can hear everyone but others can barely hear anything from joining phone, thinking 3rd phone did not connect.

1st and 3rd phones are both GrapheneOS Pixel 6a (Unlocked Model) on Verizon Wireless. Build number TQ1A.230105.001.A2.2023011000.

Is anyone else having this issue?

**Comment by thestinger** [comment]
Sounds like a hardware or carrier issue.
