### ISSUE TITLE
Scheduled Energy saving mode triggers at 10% despite being configured to start at 5%

### ISSUE THREAD

**Issue by wrnod** [GrapheneOS/os-issue-tracker#1903]
Hardware: Pixel 7
GrapheneOS: TQ1A.230105.001.A2.2023011000

Energy saving mode, when scheduled to be triggered at 5% state of charge, is triggered at 10%. When then manually deactivated it does not restart at 5%.

**Comment by thestinger** [comment]
Seems changing the setting minimum may not have been enough.

**Comment by thestinger** [comment]
We'll just revert this change.
