### ISSUE TITLE
[Feature Request] Changelogs

### ISSUE THREAD

**Issue by ItamiWasNotTaken** [GrapheneOS/os-issue-tracker#1904]
The ability to quickly view the changelog for the current release would be nice since GOS does get updated often, it would make it easier to keep up with the changelogs.

The way I imagine this working is with every update, there is a notification that when tapped, opens the current releases changelog using the HTML Viewer already included in the system

**Comment by wrnod** [comment]
The changelog is also available as an [atom feed](https://grapheneos.org/releases.atom) usable in any standard feed reader.

**Comment by ItamiWasNotTaken** [comment]
I actually used this for a bit, but I actively make changes to reduce the number of apps on my phone, hence, removing the feed reader

**Comment by ItamiWasNotTaken** [comment]
having the changelog integrated into the OS would negate the need to have an additional app for the atom feed, thus reducing the attack surface

**Comment by r3g-5z** [comment]
Already tracked in https://github.com/GrapheneOS/platform_packages_apps_Updater/issues/67
