### ISSUE TITLE
"Package not installed, conflict with existing one"

### ISSUE THREAD

**Issue by firefoxlover** [GrapheneOS/os-issue-tracker#1905]
This bug must have something to do with cached app versions or IDs.

If I try to update Spotify from an unofficial version, or Signal from another source, I get this message.

It stays even if I uninstall the app, and even after I rebooted the device!

Device: Pixel 4a
latest GrapheneOS 13 update from January

EDIT: It stays after
- deleting the app from all profiles
- rebooting the device
- stopping the package installer and deleting all its storage

**Comment by firefoxlover** [comment]
> Have you made sure to remove these apps from all of the user profiles that they may be isntalled in? All user profiles, and the work profile too, if you use that.

Yes the package is not existing on the work profile or other profiles.

I also stopped the Package installer and deleted all its saved data. So caching in there should not occur.

**Comment by thestinger** [comment]
Are you sure it's not installed on a disabled work profile, and isn't installed in a user profile where you disabled rather than removing it? That's likely the problem.

**Comment by thestinger** [comment]
If you can't determine the issue, you can factory reset. This issue isn't caused by GrapheneOS. It may be an upstream bug but it's much more likely that you do have the apps in a profile.

**Comment by firefoxlover** [comment]
It seems this was an issue with Nova launcher? Weirdly I never had this happen before. I could still access the apps info page and it said

`x not installed for user`

I could completely remove it and that worked. Seems to be an issue with externally installed APKs.

So I guess the issue is fixed, as it works normally through the Android settings
