### ISSUE TITLE
Pixel 5 5G - Wifi Calling not available when SIM card turned off

### ISSUE THREAD

**Issue by m333d1um** [GrapheneOS/os-issue-tracker#1906]
Wifi Calling is not available in settings when SIM card is turned off.

**Comment by thestinger** [comment]
What do you mean when the SIM card is turned off?

**Comment by m333d1um** [comment]
If i turn off "Use Sim" in Settings/Network and Internet/SIMS. Apologies if this is a newb question.

**Comment by thestinger** [comment]
This is expected. You need the SIM to do Wi-Fi calling.
