### ISSUE TITLE
Pixel 6 - battery problems

### ISSUE THREAD

**Issue by h-2** [GrapheneOS/os-issue-tracker#1909]
I bought a Pixel6 last June, and although battery life was not as good as with other phones it lated well over a day, at least 36h, I would say.

In Nov/Dec, I first noticed that battery was draining very quickly, sometimes the phone would get warm. Battery Monitor would say that "System(CPU)" was using most. See first screenshot.
![Screenshot_20221224-195343](https://user-images.githubusercontent.com/2996863/213882434-d2450a79-63cd-4446-a00c-5a30fe823ffd.png)

After a while it got better again, but since sometime it is quite bad again. It doesnt even last from morning to night while JUST LYING AROUND.
I do not realise it being warm anymore, and now CPU as not listed... just the usuals, however also a "wakelock".

![Screenshot_20230121-005925](https://user-images.githubusercontent.com/2996863/213882539-a6c7d1d9-13f2-4406-98ae-76c7d65b7034.png)

What's going here?

**Comment by r3g-5z** [comment]
Have you tried using LTE Only mode?

**Comment by thestinger** [comment]
This is almost certainly an app or cellular / Wi-Fi connection issue, or combination of those things. Looks like it's mostly cellular.

**Comment by h-2** [comment]
> Have you tried using LTE Only mode?

This improves battery time slightly, up to 24h *when the device is not being used at all.* This is still too little.
Also, the phone now sometimes has problems coming out of WiFi: both sims show the !-mark for no connection. Toggling flight-mode "fixes" this, but it is annoying.

> This is almost certainly an app or cellular / Wi-Fi connection issue, or combination of those things. Looks like it's mostly cellular.

How do I debug this? I have never had such problems with previous phones running other Androids.
I have posted battery usage screenshots above; they don't show any suspicious apps.
