### ISSUE TITLE
Repainter support 

### ISSUE THREAD

**Issue by TempUser13** [GrapheneOS/os-issue-tracker#1910]
Is there any plans to ship built in repainter support?

**Comment by r3g-5z** [comment]
Repainter works fine using ADB provided you're aware of the risks of using ADB. No plans to add the patches into the OS.

**Comment by TempUser13** [comment]
Even with adb, without the patches you can't do much within the application

**Comment by r3g-5z** [comment]
This isn't in the scope of GrapheneOS, and we're not interested in maintaining said patches. It's more workload for something extremely niche and irrelevant for the OS.
