### ISSUE TITLE
Pixel 6a - connected emergency service without my knowledge, no record of call in history

### ISSUE THREAD

**Issue by Dc222333** [GrapheneOS/os-issue-tracker#1911]
Just upgraded to a Pixel 6a from a Pixel 4.   The phone was in my pocket and connected to emergency services.  They had recorded my voice for some time. I do have a screen lock.  I did not know of the call until law enforcement arrived.  They confirmed that they received a call from my number and confirmed what I was speaking about.  There is no record of this call in my call history.

**Comment by thestinger** [comment]
You made an emergency call. It's not a bug. You probably pressed power 5 times in a region where that's enabled.
