### ISSUE TITLE
Request - Allow users to set Flag Secure option

### ISSUE THREAD

**Issue by vithusel** [GrapheneOS/os-issue-tracker#1913]
Is there a way to allow users to disable the Flag Secure option? I occasionally have to screenshot my banking app which proves to be a impossibility as the app itself doesn't allow it. I did this previously using a Magisk module but I would like to keep my phone as close to stock GOS as possible. If its not possible for security reasons then completely understand and ill have to just keep my old phone around to perform these tasks.

**Comment by thestinger** [comment]
There can be a toggle to allow taking screenshots of secure flag activities but we won't provide a toggle for disabling the secure flag feature as a whole. It does more than disabling screenshots. You can file a new issue requesting that instead.

**Comment by anerb** [comment]
Hi. I'm new to GrapheneOS, and I am already a fan.  Can I somehow try to take on this feature request of "Allow screen capture"?  I imagine it would be under App info > Advanced > Screen capture.  This would be similar to Picture-in-picture.   I think it would be a boolean toggle for [Allowed, Not allowed] on Screenshots and Long screenshots.
 - The explanation fine-print would say that this will always allow screeshot to capture the app, even in incognito or other situations where an app is programmed to prevent the screenshot for only some of its screens.
 - If video screen record comes along for the ride, that should be explained too.  If that is a separate permission, it can be considered for later addition as a second toggle. Cheers.

**Comment by thestinger** [comment]
See https://github.com/GrapheneOS/os-issue-tracker/issues/1915.
