### ISSUE TITLE
2023012500 killed all network on Pixel 4a 5G

### ISSUE THREAD

**Issue by GY8VSdYYzvL8-K6T** [GrapheneOS/os-issue-tracker#1916]
This update made it impossible to connect to cellular network and to WiFi on both Pixel 4a 5G phones I have. Enabling WiFi doesn't result in any WiFi AP's showing up. SIM cards are not detected at all.  Factory reset has no effect on resolving these issues.

**Comment by vtimon1** [comment]
I have exact same issue!!!   (FYI: I was able to connect to Internet using usb-c ethernet network adapter)

Don't know how relevant this is:  I was using phone as another user after update downloaded and I had turned off cellular and set it to airplane mode while it verified/installed.

**Comment by GY8VSdYYzvL8-K6T** [comment]
Pixel 4a (non-5G) is not affected by this issue.

**Comment by vtimon1** [comment]
Found out that using the Ethernet (wired via USB-C) connection drains the battery quickly

BTW, do I need to open as another issue to help draw attention that our phones are essential dead?

**Comment by vtimon1** [comment]
Confirming when turning WIFI on -- receive "No networks are available" message (even though I had active WIFI hotspot within 1 foot of phone.

**Comment by pandrien** [comment]
Same exact issue. No network and no sim service. I'm also on 4a (5g). This appears to be a severe bug with 2023012500.

Fresh install of bramble-factory-2023011000 (stable) fixed the issue.

**Comment by thestinger** [comment]
There will be a new release for the Pixel 4a (5G).

**Comment by lqramen** [comment]
I have same issue, hmm doing a fresh install and making everything as I want it again is annoying. What is the feeling will there be an update available over USB tethering that would be better to wait for ?

**Comment by thestinger** [comment]
It was just stated that a new release will be available fixing the issue.

**Comment by thestinger** [comment]
There is no reason to factory reset or reinstall.

**Comment by thestinger** [comment]
The new release is now available. You can either do an over-the-air update to the new Alpha / Beta channel release via USB tethering from another device or you can download https://releases.grapheneos.org/bramble-ota_update-2023012600.zip on a computer and sideload it with these instructions: https://grapheneos.org/usage#updates-sideloading.
