### ISSUE TITLE
Slide 3 fingers down to take a screenshot

### ISSUE THREAD

**Issue by mecuricat** [GrapheneOS/os-issue-tracker#1917]
The current method of taking a screenshot is Power + Volume Down. It's great if you are left-handed. If you are using your phone rested on a table or bed, you have to lift your phone to take a screenshot. Is it possible to implement this feature?

###### Also discussed [here](https://discuss.grapheneos.org/d/3071-request-for-taking-screenshot-by-sliding-3-fingers-down).

**Comment by thestinger** [comment]
You can take a screenshot with the button in recent apps.

We don't plan on adding this.
