### ISSUE TITLE
One time data limit with mobile hotspot

### ISSUE THREAD

**Issue by mecuricat** [GrapheneOS/os-issue-tracker#1918]
To explain where I come from, I have a daily limit on my data plan. You share your personal hotspot with a friend or family member and you would sound like a miser everytime you ask how much data they need before sharing. Once in a while, after sharing, you realize that much of your data is gone. Is there a way to add a one limit data limit that you want to share with other devices?

![One-time data limit](https://user-images.githubusercontent.com/112750975/215036494-e8620eaa-a486-4fe1-8895-1250147e952a.jpg)

**Comment by thestinger** [comment]
This could be added to AOSP but isn't in the scope of what we work on in GrapheneOS. It sounds like a reasonable feature, just not what we work on.

**Comment by mecuricat** [comment]
How can I request the same with AOSP? I don't have a google account. Is everyone allowed to open an issue?

**Comment by thestinger** [comment]
Anyone can open an issue but it's quite possible it was already proposed there.
