### ISSUE TITLE
Recent pixel 7 stable update causing issues

### ISSUE THREAD

**Issue by Random616** [GrapheneOS/os-issue-tracker#1919]
Since most recent pixel 7 stable channel update (TQ1A.230105.001.A2.2023012500) two new issues have emerged immediately

Phone is both running unusually hot and;

All music apps are frequently randomly pausing and resuming at random intervals (YT music and VLC). This issue is new and happens regardless of lock screen status, even when screen on and phone face up with no intervention. Pausing happens on almost every track. 

Have changed battery settings on both music apps, multiple reboots, bluetooth unpairing/pairing, but issues remain.

Fingerprint reader also seems somewhat unreliable but this is not update specific.

I love this project. Well done and thankyou for an incredible OS.

Random 616

**Comment by thestinger** [comment]
These issues are not able to be reproduced.

**Comment by thestinger** [comment]
Likely caused by hardware failure.
