### ISSUE TITLE
Inclusion of new carrier configs introduced in stock QPR2 Beta 2 and later?

### ISSUE THREAD

**Issue by mmoduu** [GrapheneOS/os-issue-tracker#1920]
According to this forum post: https://forum.xda-developers.com/t/january-20-2023-qpr2-beta-2-1-t2b2-221216-008-pixel-7-pro-cheetah-thread-also-for-future-major-android-betas.4508257/page-11#post-87853203

..there are new carrier configs available in stock QPR2 Beta 2. Now, I have seen from GrapheneOS release notes that some QPR2 Beta 2 stuff has been included (kernel), but would it be possible to get the latest carrier configs also? I'm currently waiting for the new **fi_telia** config to enable 5G, and maybe later they will update it even further to enable VoLTE.

**Comment by maade69** [comment]
currently, carrier configs are handled by [carriersettings-extractor](https://github.com/GrapheneOS/carriersettings-extractor), which gets protobufs from stock factory images (extracted by adevtool) and convert them to AOSP XMLs. 
that means that carrier configs are tied to the version of google's release. we use only **stable** builds as a base for proprietary files and carrier configs.

**Comment by maade69** [comment]
when google adds these configs to next stable release of their OS, it will be included in GrapheneOS as well

**Comment by thestinger** [comment]
We're going to stick to the stable releases.
