### ISSUE TITLE
Camera toggle bypasses Sensors Off

### ISSUE THREAD

**Issue by TempUser13** [GrapheneOS/os-issue-tracker#1921]
On Pixel 6 (TQ1A.230105.002.2023012500), the sensors off qs tile isn't blocking the camera when both are enabled. Previously sensors off would block camera regardless of the camera toggles state. I'm not sure what update changed it but it's an issue on this update.

**Comment by thestinger** [comment]
This is a development option, not a supported feature. Upstream issues with it aren't something we'll address. Adding a proper toggle for Sensors (Camera and Microphone already have one and are separate) is planned.

**Comment by TempUser13** [comment]
Is there a way for someone like me to report it upstream? The main reason I used this was since sensors off reported the camera as disabled rather than blocked which gave a better experience inside specific apps that continually ask for the camera to be unblocked. Thanks for the reply though.
