### ISSUE TITLE
Gesture navigation bar appears in the middle of the screen after rotation

### ISSUE THREAD

**Issue by firefoxlover** [GrapheneOS/os-issue-tracker#1923]
## Error
The navigation gesture bar, that is on the bottom of the screen, appears in the middle of the screen, when rotating back from landscape view.

## Reproduce
I use LibreTube, watch a video in landscape mode and rotate my screen back.

## "Fix"
Use the gesture bar normally, switch back to the homescreen, it appears back.

Device: Pixel 4a, newest updates

**Comment by thestinger** [comment]
We're not planning on working on this upstream issue or tracking it here.
