### ISSUE TITLE
Update Seedvault

### ISSUE THREAD

**Issue by nazar-pc** [GrapheneOS/os-issue-tracker#1924]
GrapheneOS ships 11-2.3, while latest upstream version is 13-3.3.

To some of the issues upstream responds that we're using version that is too old.

Please consider updating Seedvault to the latest version.

**Comment by thestinger** [comment]
It may be updated again before it's removed but it's not currently a high priority.

**Comment by nazar-pc** [comment]
So the plan is to remove it?
If that is the case, what is the replacement backup mechanism?

**Comment by cactushydrocodone** [comment]
Since seedvault is still the backupprovider, can it be updated until it is removed? I currently cannot do backups because of an issue that has been fixed in upstream.

**Comment by thestinger** [comment]
We'll update it for the next release.
