### ISSUE TITLE
Feature request: Double tap screen to sleep

### ISSUE THREAD

**Issue by NielsDav** [GrapheneOS/os-issue-tracker#1925]
One handy feature I'd love to see on GOS is double tapping the screen (while on home screen) to lock the device and go to sleep.

Brands like Samsung and Oneplus already have this as a standard feature on their launchers, and I'm pretty sure many users will like it.
It saves you from reaching for the power button, similar as to waking to screen with a single tap - which you thankfully already integrated.

**Comment by thestinger** [comment]
We don't plan to add this.

**Comment by peterge1998** [comment]
This is possible with the App TapTap, Pixel Devices do not even need root for this 🥳🥳🥳
See this repo https://github.com/KieronQuinn/TapTap or my blog post (german):
https://blog.peterge.de/quick-tap-gesten-auf-google-pixel-geraten/

**Comment by eiqnepm** [comment]
All the phones I've ever had have had this feature. I know it seems small but being able to lock the screen without adjusting your grip to press a physical button is such a convenience.

> We don't plan to add this.

Is there a technical reason it isn't planned or is it just not a priority?

If it's just not a priority could get this issue reopened and tagged as an enhancement with priority-none?

**Comment by peterge1998** [comment]
> All the phones I've ever had have had this feature. I know it seems small but being able to lock the screen without adjusting your grip to press a physical button is such a convenience.
> 
> > We don't plan to add this.
> 
> Is there a technical reason it isn't planned or is it just not a priority?
> 
> If it's just not a priority could we get this issue reopened and tagged as an enhancement with priority-none?

It’s possible with lawnchair, a foss Home Screen replacement app, too. You can activate double tap to lock on homescreen in it’s settings.

**Comment by eiqnepm** [comment]
> > All the phones I've ever had have had this feature. I know it seems small but being able to lock the screen without adjusting your grip to press a physical button is such a convenience.
> > > We don't plan to add this.
> > 
> > 
> > Is there a technical reason it isn't planned or is it just not a priority?
> > If it's just not a priority could we get this issue reopened and tagged as an enhancement with priority-none?
> 
> It’s possible with lawnchair, a foss Home Screen replacement app, too. You can activate double tap to lock on homescreen in it’s settings.

I have tried third party launchers. Unfortunately the recent apps overview likes to bug out when using third party launchers.

I have resorted to using MacroDroid to create a widget on my home screen which locks the phone when pressed.

I still hope that this makes it into the GrapheneOS launcher, that and disabling the top shadow. It may be just a small feature, however it makes a worlds of difference for convenience, for me at least.

**Comment by ralph303** [comment]
Why couldn't this really practical and often requested feature be added?
I had a malfunctioning powerbutton on my last smartphone, because of locking the device countless times a day.
So this feature would be a real benefit in terms of sustainability to extend the hardware lifetime.

**Comment by NielsDav** [comment]
> If it's just not a priority could we get this issue reopened and tagged as an enhancement with priority-none?

Seems like a good suggestion.
Still, after years of using GrapheneOS, I'd love to see this feature added :)

**Comment by eiqnepm** [comment]
I understand why GOS doesn't prioritize or even aspire to implement non-privacy related features, as that's not the project's aim and a line has to be drawn somewhere.

I have been using a third party launcher with this support for a while now, although there is one issue with this, third party launchers don't support Private Space, so I cannot use both Private Space and double tap to lock at the same time, which is inconvenient and forces me to make a choice between privacy and convenience.

I hope this gets implemented as it seems really inoffensive and easy to maintain, although I don't have any Android dev experience so I cannot be certain.
