### ISSUE TITLE
remove dangerous opt-in add users on lockscreen toggle

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/os-issue-tracker#1927]
I don't see a valid use case for this feature and accidentally toggling it on would be quite bad.

**Comment by thestinger** [comment]
Rather than just removing the preference UI, it should likely be prevented from functioning as a whole. This is dangerous enough that we added it to the current limited set of OS verified state for Auditor.

**Comment by robcle** [comment]
This issue should be closed.
