### ISSUE TITLE
Cant't update apps anymore through Play store on my work profile (stalled)

### ISSUE THREAD

**Issue by bungabunga** [GrapheneOS/os-issue-tracker#1928]
It seems that I can no longer update apps through Play store on my Pixel 6 on work profile for some time (a month or so). If I click to update they just get "stalled" and remain stalled forever. I don't know if it work or not on my main profile, because I am not logged in to Google account there, but I tested it on a newly established "test" user and it works just fine there.

device: Pixel 6
release: 2023012500

**Comment by thestinger** [comment]
It sounds like it's already trying to install an app and you haven't accepted/denied the request. When it happens in the background, it makes a notification via the compatibility layer. You need to handle those notifications. If you turn off those notifications, it will be stalled and you won't know. Please make sure this isn't what's happening.

**Comment by bungabunga** [comment]
To my best knowledge I have the all the needed notification turned on.

![2023-01-31 17 18 01](https://user-images.githubusercontent.com/2994878/215821670-2fcac1c8-da5e-4a60-bee3-f6d9032337f5.png)

![Screenshot_20230131-171747](https://user-images.githubusercontent.com/2994878/215822079-2a7cf32f-3a08-4225-9a73-c3c543466b07.png)

PS - oh, and it's not 'stalled', it's 'pending'.

**Comment by Zeit08** [comment]
Can't reproduce on 6a. Google play installs apps just fine on my work profile (used Shelter). Try to make sure google Play has all the notifications on. Try to clear data of play services, play store and log back in

**Comment by thestinger** [comment]
@bungabunga

> PS - oh, and it's not 'stalled', it's 'pending'.

Pending is what it says when it's stalled waiting for another action to complete. Have you tried either reboot or force stop already?

**Comment by bungabunga** [comment]
Reboot and force stop/clear cache of Play Store didn't help but clear storage did the trick. Thank you!

**Comment by muhomorr** [comment]
Which version of Play Store and GrapheneOS are you on?

**Comment by bungabunga** [comment]
It happened to me again shortly after I cleared the storage of Play Store. Always on the latest stable Play Store (installed through Apps) and GrapheneOS.

**Comment by muhomorr** [comment]
Have you tried cancelling the download and trying again? I've seen this issue on stock OS before.

**Comment by muhomorr** [comment]
Do you use a VPN?
