### ISSUE TITLE
Scheduled battery saver crashes UI

### ISSUE THREAD

**Issue by ph00lt0** [GrapheneOS/os-issue-tracker#1929]
Every time the battery saver turns on it completely crashes the UI when turning to dark mode. All apps UI's restart, this a very annoying UX problem I now had for quite a while. It causes all apps to lose their current state and therefore I lose the things I am working on, my music or video ques, very frustrating.

**Comment by thestinger** [comment]
Not much we can do about this unless there's some reason to think it's a GrapheneOS caused issue.
