### ISSUE TITLE
figure out what's wrong with pre-optimization for android-prepare-vendor apps and restore it

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/os-issue-tracker#193]
See https://github.com/GrapheneOS/os_issue_tracker/issues/190 for background.

Re-enabling full pre-optimization with the speed filter started causing issues which were never present in the past, due to some kind of duplicate / mismatched method definitions. It's unclear if this is still an issue without pre-optimization. It doesn't get detected without it. Perhaps it falls back to using the unoptimized bytecode or perhaps optimizing it within the OS works differently.

The current workaround is disabling dexpreopt for the apps included by android-prepare-vendor which is undesirable:

GrapheneOS/android-prepare-vendor@85d206c

**Comment by anupritaisno1** [comment]
@thestinger as you can see in the referenced commit above I just tested this on my phone and I'm unable to reproduce any issue

Also you've just left this issue at "there's an issue". If people don't know what to look for what are you expecting?

**Comment by thestinger** [comment]
That's a different device with different prebuilt apps. I'm specifically talking about android-prepare-vendor with the supported devices.

**Comment by anupritaisno1** [comment]
I understand but also request you to read my message carefully

Csm you describe the issue in detail? Like expected vs actual behaviour and preferably a log along with what apks are misbehaving?

**Comment by thestinger** [comment]
The issue title starts out with "figure out what's wrong with [...]" because a substantial part of the task is figuring out the basics of what's actually happening. The second part of the title makes it clear what causes the issue which is all that's needed to reproduce it "[...] pre-optimization for android-prepare-vendor apps and restore it". I don't know what else you expect. The apks hitting the issue are the ones added to /system by android-prepare-vendor which contain bytecode. If you don't have one of the supported devices, then I don't think there's any way to work on this.

**Comment by thestinger** [comment]
It's easy to reproduce by simply removing my workaround:

https://github.com/GrapheneOS/android-prepare-vendor/commit/85d206cc28a6d1c23d3e088238b63bc2e6f68743

This will break those apps from starting as can be seen from `adb logcat` upon booting the OS.

**Comment by thestinger** [comment]
This doesn't appear to be an issue anymore.

**Comment by thestinger** [comment]
Nevermind, still broken.

**Comment by anupritaisno1** [comment]
While this issue doesn't stop the pixel 4 from booting

Use this:
Revert the workaround
Boot pixel 4
Go to settings > about phone > sim status and tap it
Observe logcat. Similar crashes are seen on pixel 4

**Comment by anupritaisno1** [comment]
This is the app causing the breakage for me https://github.com/GrapheneOS/android-prepare-vendor/blob/10/flame/config.json#L32

Maybe we can:
1) remove the app
2) only disable preopt for that one app

Your thoughts?

**Comment by anupritaisno1** [comment]
This is the app causing the breakage for me https://github.com/GrapheneOS/android-prepare-vendor/blob/10/flame/config.json#L32

Maybe we can:
1) remove the app
2) only disable preopt for that one app

Your thoughts?

**Comment by thestinger** [comment]
https://github.com/GrapheneOS/os-issue-tracker/issues/716 should resolve this.
