### ISSUE TITLE
Fix Contacts App Unfilled Text Color in Dark Mode

### ISSUE THREAD

**Issue by seniorm0ment** [GrapheneOS/os-issue-tracker#1930]
With all the apps getting dark mode which looks beautiful, there is one major flaw with the contacts app. 

The text that is unfilled is way too dark when you are in edit mode. It blends in with the background and makes it very hard to read, especially if brightness is turned down, you're in a dark room, etc.

**Comment by r3g-5z** [comment]
Going to merge this with https://github.com/GrapheneOS/os-issue-tracker/issues/1847
