### ISSUE TITLE
Location Services Wifi/bluetooth not working

### ISSUE THREAD

**Issue by NotAPerso** [GrapheneOS/os-issue-tracker#1934]
Settings > Location > Location Services 

Toggling Wi-fi Scanning and Bluetooth scanning on appears to do nothing. When Wi-fi and bluetooth themselves are off location services still do not have access to check these for location regardless of toggle. 

Example scenario: Opening Pokemon Go inside a building with Wi-fi and bluetooth switched off results in location undetermined, toggling the scanning options on should fix this but nothing changes. Toggling wi-fi and bluetooth themselves on results in location determined correctly.

**Comment by r3g-5z** [comment]
Wi-Fi and Bluetooth scanning don't do anything on their own. They require a location provider using sandboxed Google Play and using Google location APIs, not the OS ones.

**Comment by thestinger** [comment]
They control the ability for apps with Location / Nearby devices to scan in the background when those are off.

**Comment by thestinger** [comment]
They control the ability for apps with Location / Nearby devices to scan in the background when Wi-Fi / Bluetooth are otherwise turned off.

**Comment by NotAPerso** [comment]
> They control the ability for apps with Location / Nearby devices to scan in the background when Wi-Fi / Bluetooth are otherwise turned off.

Yes, I'm aware of what they are supposed to do. They do not do this. Regardless of toggle being on or off. They still act as if they are off.

**Comment by thestinger** [comment]
No, that's not what it does. The toggles allow apps with those permissions to do scanning. There isn't a network-based location service in AOSP or GrapheneOS. Read https://grapheneos.org/usage#sandboxed-google-play-configuration for instructions on using the Google Play one. There will be other options in the future but it requires us to develop them.

**Comment by NotAPerso** [comment]
> No, that's not what it does. The toggles allow apps with those permissions to do scanning. There isn't a network-based location service in AOSP or GrapheneOS. Read https://grapheneos.org/usage#sandboxed-google-play-configuration for instructions on using the Google Play one. There will be other options in the future but it requires us to develop them.

???
I have already setup Google play services and location works normally. The problem is that precise location only works when the wi-fi and bluetooth radios are toggled on. 

> **Wi-fi Scanning** Allow apps and services to scan for Wi-fi networks at any time, even when Wi-fi is off. 
> **Bluetooth Scanning** Allow apps and services to scan for Wi-fi networks at any time, even when bluetooth is off. 

These are both toggled on. When i am using precise location and disable wi-fi or bluetooth it will lose the location immediately. So it clearly does not allow the wi-fi or bluetooth to work for location as the scanning states it does.

**Comment by thestinger** [comment]
Have you granted the battery optimization exception?
