### ISSUE TITLE
Missing: Emergency info on lockscreen

### ISSUE THREAD

**Issue by Evrey** [GrapheneOS/os-issue-tracker#1936]
I can’t find the setting where my medical emergency info and emergency contacts list appear on the lockscreen. This is a super important safety feature, and lets people call relatives etc. on a mere button click without unlocking. Also handy when you simply lost your phone. It seems to appear in the settings search results, but is not clickable.

**Comment by thestinger** [comment]
It's in safety settings.

**Comment by Evrey** [comment]
It’s not. That’s why i opened this issue.

I got, under »Safety and Emergencies«:
![Screenshot_20230204-210855](https://user-images.githubusercontent.com/6483505/216787806-faedec8a-c533-4c66-b5c7-af07700d75eb.png)

And there’s zero documentation on whether that’s intended or not or something else entirely.

**Comment by r3g-5z** [comment]
@Evrey It seems to work fine? The toggle doesn't exist which is an upstream missing addition that won't be tracked here, but I'm able to hold the power button, select Emergency, and see my info.

**Comment by Evrey** [comment]
Ah, the power button thing works, good to know!
