### ISSUE TITLE
notification popping in other account

### ISSUE THREAD

**Issue by aurelpere** [GrapheneOS/os-issue-tracker#1940]
Hi,
I have made two accounts on my graphenos phone: one called user for bad playstor apps (google maps, tinder, whatsapp, instagram, etc.) and one called owner with a few playstore apps and a lot of android apps.
I had an issue with a notification popping in owner account that came from the user account. I dont recall well if it was a notification from playstore or googlemaps but it did cross the account sandbox boundary.

**Comment by thestinger** [comment]
You enabled notification forwarding.
