### ISSUE TITLE
Build in adblocker

### ISSUE THREAD

**Issue by yagarea** [GrapheneOS/os-issue-tracker#1942]
Since grapheneOS does not offer rooted enviroment the non VPN adblocker does  not work.

It would be nice to have official tool for adblocking.

**Comment by r3g-5z** [comment]
No plans to integrate something into the OS. You can provide your own ad-blocking software. VPN ad-blocking works fine, and you can use Private DNS for ad-blocking too. 

See the following in the FAQ:
https://grapheneos.org/faq#ad-blocking

https://grapheneos.org/faq#ad-blocking-apps

**Comment by yagarea** [comment]
VPN based adblocking is reasource heavy and drains your battery.

In general adblocks are esential tool for privacy and security. It helps block trackers and ads which can be used to spy on users.

I think it is inconsitent with project philosophy to ignore such a important tool. I understand that it is not simple task but it definetly deserves to be added to road map.

**Comment by thestinger** [comment]
This is not being added. Enumerating badness is not consistent with the project's approach and neither is bundling functionality which can be done fine via apps or other approaches.

> VPN based adblocking is reasource heavy and drains your battery.

It's not any more resource heavy than using another VPN service and the VPN service can provide both this and a VPN implementation. If you want more lightweight filtering, use DNS-based filtering. A VPN service can provide only DNS without rerouting other traffic if you want that approach.
