### ISSUE TITLE
Only allow rebooting if battery is above a certain level

### ISSUE THREAD

**Issue by louiskram** [GrapheneOS/os-issue-tracker#1946]
It would be nice if there was a setting to only download an update if the battery level is above a certain level. Last night the update was automatically downloaded causing my phones battery to be drained the next day. 

Another problem that could arise is that you press the "reboot now" button in the update notification when the battery is almost drained, causing the battery to drain while the update is being installed. 
It would be nice if this kind of behaviour would be prevented by only allowing updates to be installed if the phones battery level is above e.g. 70%.

**Comment by thestinger** [comment]
> Another problem that could arise is that you press the "reboot now" button in the update notification when the battery is almost drained, causing the battery to drain while the update is being installed.

That's not how updates work. They're installed before you reboot and the installation is atomic. Interrupting it doesn't cause problems. The inactive slot is switched to active once the update is installed, and then that's what boots next time. If booting fails it rolls back the update and doesn't persist any changes to data by the new update.

**Comment by thestinger** [comment]
There's already a toggle for only updating when the battery level isn't critical. That's what's supported by the job scheduler rather than requiring a specific level. We could do our own check and defer the update ourselves but that's not really the way we want to do things since then the job scheduler has no idea why it was delayed.

**Comment by louiskram** [comment]
When a friend of mine installed the [2023012500](https://grapheneos.org/releases#2023012500) update, it caused the phone to be stuck on the google safety screen. He also opened a [topic in the grapheneos forum](https://discuss.grapheneos.org/d/3136-pixel-6-doesnt-boot-after-failed-update) detailing on what happend. 

But as I understand you now, this was a different bug, not caused by installing the update when the phones battery was almost drained? 

> There's already a toggle for only updating when the battery level isn't critical. 
My friend has this setting toggled but the update still failed to install correctly.

After the second to last update the phone is back to working normal after having displayed the "insecure boot" message when starting the phone.

**Comment by thestinger** [comment]
They're similarly misunderstanding how update installation works. This issue you filed isn't a bug but rather a request for a feature we already provide with less configuration flexibility than you requested. It's not clear what happened with the situation that person opened a thread about on the forum but both of you are misunderstanding how update installation works.
