### ISSUE TITLE
Add support to further reduce minimum color temperature in Night Light

### ISSUE THREAD

**Issue by 1over137** [GrapheneOS/os-issue-tracker#1948]
Recent versions of Android supports Night Light feature, in which the colors of the display are shifted in order to reduce blue to mitigate the effect of blue light on the circadian rhythm and/or eye strain. 

In the past, CF.Lumen (root only) provided a way to change the screen all the way to full red for the same reason and also for stargazing, where exposure to blue light has to be minimized in order to not lose the dark adaptation. It is very useful to be able to look up information with phone screen emitting only red light. More recently, there is a way to leverage the Night Light feature to do the same thing [1], by reducing the minimum color temperature it allows the user to set. However, this requires root, which is not compatible with GrapheneOS users' security requirements. 

The only way to provide such a functionality is by implementing a way to change the limit in the system. I think the simplest way to do so is to directly change the limit in the system. If it is desirable to retain the current limit by default for most users (I believe GrapheneOS already has a lower limit than other systems), then it can be hidden behind a "Extend color temperature range" toggle, which when toggled sets the lower limit to 0K or less. I wish I could implement this myself, but I lack knowledge of Android development. 

1. https://forum.xda-developers.com/t/night-light-display-red-only-tweak.4220829/

**Comment by r3g-5z** [comment]
The limit is already *substantially* reduced to 686K from 2596K.

https://github.com/GrapheneOS/platform_frameworks_base/commit/95a6152b1c7bcf8bf81b574124317be6fcfc308d

The value 686K was chosen with an actual proper reason in https://github.com/GrapheneOS/platform_frameworks_base/pull/193#issuecomment-1107871558

> If I were to suggest a less arbitrary value, I would choose 686K, as this is where the blue intensity function hits zero.

Unless this change is not working or there's a better and more relevant reasoning, there is no reason or interest to drop it down to 0.

**Comment by 1over137** [comment]
With respect to the circadian rhythm, green light also has a noticeable impact. The relative impact of light of varying wavelengths is described by the melanopic spectral efficiency function, which reflects the light sensitivities of photosensitive retinal ganglion cells. 

With respect to the use in maintaining dark adaptation, the rods in eye is also far more sensitive to green than it is to red (peaking at 530 nm, which is green). Even a relatively small amount of green "bleaches" the rods, causing them to lose sensitivity, which is the origin of dark adaptation. Even though there is already relatively little green present in the current amber setting, there are good reasons to think that less would be even better. 

The specific value of 0 arbitrary. Based on gradient values on the spec, red is not affected by the color temperature at all, so the reducing it as far as possible should result in the least amount of green possible. By solving the equation with the parameters on the spec, green reaches zero when t=-2238.34. According to the XDA forum thread, minus values should be acceptable for this.


References:
Melanopic spectral efficiency function: https://luminusdevices.zendesk.com/hc/en-us/articles/4409868024461-What-is-the-Melanopic-Ratio-
Dark adaptation: https://en.wikipedia.org/wiki/Adaptation_(eye)#Accelerating_dark_adaptation

**Comment by 1over137** [comment]
Can someone else look at this @thestinger
