### ISSUE TITLE
Can't delete a corrupted download in the Files app

### ISSUE THREAD

**Issue by steliyan** [GrapheneOS/os-issue-tracker#1949]
I've tried to download a podcast (an `mp3` file), but for some reason the download failed or got cancelled.

Now I have a 0 byte file show up in the `Files` app, `Downloads` section, but I am unable to delete it. I get "deleting a file" toast when I try do so, but the file remains afterwards. Note that additional options like: `Copy to`, `Move to`, `Rename` are _NOT_ available for this file.

I read the following [issue](https://github.com/GrapheneOS/os-issue-tracker/issues/215). Which means there is a file somewhere, tagged as a "download", but I can't seem to find it.

Steps I've tried:
1. Re-download the same file
2. Try delete through the `Vanadium` browser "Downloads" history - nothing there
3. Delete the cache of the `Files` app
4. Delete the cache of the `Vanadium` browser app (used for downloading the file)
5. Reboot the device (a couple of times)
6. Try to locate the file using `adb shell` and using `ls -lR /sdcard | grep -i "xxx"`

I've also tried the [Google Files](https://play.google.com/store/apps/details?id=com.google.android.apps.nbu.files&hl=en&gl=US), but the 0 byte file is _NOT_ shown in the "Downloads" section.

I've read somewhere that deleting the `Media Storage` app cache may resolve this issue, however, when I open it through `Settings -> Apps -> All Apps -> Show system -> Media Storage -> Storage`, both options `Clear storage` and `Clear cache` are disabled.

Any suggestions/workarounds are welcomed.

**Comment by steliyan** [comment]
@Sigmund-Reiss tried this, but the file does NOT reside in `/sdcard/Download/` dir. My understanding is this has been marked as a "Download" (check #215).

EDIT: The file disappeared from the "Downloads" section by itself, no action was taken by me. :|

**Comment by steliyan** [comment]
@thestinger, can we reopen this one, as it happened again? How I've hit this problem, well, as last time, I tried to download a podcast from a platform that supports downloading an MP3 file and not some stupid proprietary app. 

I have a 0 byte file which is listed, but can't be moved/deleted through the **Files** app. I am not sure where the problem resides, is it the browser (list 0 byte files in its "Downloads" section) itself or the Files browser (just be able to delete this file)?

**Comment by thestinger** [comment]
Have you tried clearing downloads in the app?

**Comment by steliyan** [comment]
The "Downloads" list in Vanadium is empty. Trying to delete the file from the Files app doesn't work, it says "Deleting 1 item", but the file is still listed with file size 0B.

**Comment by BlazeWinterstorm** [comment]
Hello there, I am having the same exact issue as well so can we reopen this? I've tried deleting the file and clearing the browsers downloads but none of that seems to get rid of it. If it helps the file on mine is named "6767276c-6891-4dd5-9f4a-5790a8a0410f" and has been there since around last week.

**Comment by khemarachuon** [comment]
Please reopen I am also having this issue with the zero byte file. Clearing the cache does not help.

**Comment by thestinger** [comment]
It's an issue with the app you used. Clear the app data. If that doesn't work, open a new issue.

**Comment by khemarachuon** [comment]
I'm using the default Files app that ships with GrapheneOS. Clearing the storage and cache of the Files app does not resolve.

**Comment by thestinger** [comment]
No, clear storage in the app which downloaded the file and owns it.

**Comment by khemarachuon** [comment]
Cleared storage and cache  in Vanadium and Files apps again and the zero byte files are still present. I'll open a new ticket tomorrow.
