### ISSUE TITLE
Enabling 5G on giffgaff network requires 5G enabled on device or calls fail

### ISSUE THREAD

**Issue by Boggin** [GrapheneOS/os-issue-tracker#1952]
Note that this may well be carrier specific.

With the UK carrier giffgaff which piggybacks on O2 you have to enable 5G in the settings on their website to have access to 5G.  Importantly, you are now not able to degrade the service setting with giffgaff from 5G to 4G.

Next enable 5G on the device, in this case a Pixel 6.

Degrade your setting on your device from 5G to 4G (and if you aren't in a 5G area you probably should do this to save power).
*If you set your device to 4G you will not be able to make or receive calls.*

operator: 4G -> 5G
device:    4G -> 5G
operator: locked to 5G
device:    5G -> 4G
result:     no calls (although device is on network)
device:    4G -> 5G
result:     calls, make and receive

Can anyone else confirm? Note that your device will be stuck on 5G if you do this.

**Comment by thestinger** [comment]
This sounds like a carrier issue. I recommend posting this at https://discuss.grapheneos.org/ rather than as an issue here. You're unlikely to get any useful feedback here and it doesn't seem like an OS bug.

**Comment by flawedworld** [comment]
@Boggin It sounds like they are doing some really strange nonsense with handing back to LTE for calls/texts as part of their 5G NSA (Non StandAlone) deployment. You will probably encounter similar behaviour on the stock OS from my point of view.
