### ISSUE TITLE
Dial: Speed dial setup is confusing

### ISSUE THREAD

**Issue by nettnikl** [GrapheneOS/os-issue-tracker#1954]
The speed dial functionality is how i usually initiate my calls.
However there is an issue with this feature - however i'm not sure whether this is the correct place to ask for this (or somehow better in AOSP, with which i'm not familar with, however), so please redirect me if this is not the correct way to propose.

Adding new numbers here is not really something done daily, but it still very much impacts the UX.

Currently there can only a contact be selected, not a specific number, and on the speed dail page itself, you can also cannot select the number you call - you can only use the default number.
So, the people i call most often can only be added once, even if i also would like to call them on their secondary number.

Additionally, the current implementation does seemingly not allow a search for users. The intent opens the contact list, but when a search result is clicked, the number is called instead of returned by the intent, which is obviously unexpected when you are in the middle of setting up speed dial.

### Relevant code:
https://github.com/GrapheneOS/platform_packages_apps_Dialer/blob/55cea8d0fa6732e85afa4b4671fb43d85a02e10a/java/com/android/dialer/speeddial/SpeedDialFragment.java#L643

**Comment by thestinger** [comment]
We're not planning on changing these kinds of things about the AOSP Dialer UI.

**Comment by thestinger** [comment]
You can use a different Dialer app if you prefer another one.
