### ISSUE TITLE
Custom camera app doesn't open unless phone is unlocked

### ISSUE THREAD

**Issue by nazar-pc** [GrapheneOS/os-issue-tracker#1957]
If I make Open Camera the default, nothing happens on double click on power button until I unlock the phone. This only works properly when default system camera is selected, which is annoying because I find default camera very lacking and wouldn't use it for anything at all otherwise.

Seems similar to https://github.com/GrapheneOS/os-issue-tracker/issues/742, but probably not the same.

**Comment by thestinger** [comment]
Known Android 12+ issue with multiple camera apps which can be worked around by setting the app as a default in a certain order. Not specific to GrapheneOS and we don't plan to address it downstream.

Not sure what issue you have with the system camera app. It works better than Open Camera.

**Comment by nazar-pc** [comment]
There is no order as far as I can tell. It is either set or it is not. And I can set it to a different one only once I clear defaults of the currently selected camera app.

As to "better", I find it lacks a lot of useful settings. Even something as basic as used video framerate is not shown and not configurable, let alone RAW images and video compression level. It might work better (I have complaints about Open Camera), but it is not necessarily better camera overall and I don't think it is the goal of yours to add more settings to it, so it'll likely stay that way.

**Comment by thestinger** [comment]
> I don't think it is the goal of yours to add more settings to it

I don't know why you say that since it contradicts the fact that we have a bunch of planned features on our Camera issue tracker.

**Comment by thestinger** [comment]
> It might work better

It provides better image and video capture quality along with better focus, etc. It automatically switches cameras based on zoom level (ultrawide, telephoto) like Google Camera. It also has modes for HDR, Night, Portrait and others on devices providing support for those via CameraX extensions which unfortunately doesn't include Pixels yet, but does include the past couple years of Samsung devices.

**Comment by nazar-pc** [comment]
> I don't know why you say that since it contradicts the fact that we have a bunch of planned features on our Camera issue tracker.

Apologies then, I had an impression you're fairly conservative about adding features (on the OS level at least), but I'm happy to see that camera will get more featureful :+1:

> It provides better image and video capture quality along with better focus, etc.

I'm not entirely sure how to compare. I made a few pictures with stock camera and Open Camera and I can't find any notable difference between them.

> It automatically switches cameras based on zoom level (ultrawide, telephoto) like Google Camera. It also has modes for HDR, Night, Portrait and others on devices providing support for those via CameraX extensions which unfortunately doesn't include Pixels yet, but does include the past couple years of Samsung devices.

Looks like most of those things are already working on Open Camera too. Switching camera on Pixel 7 Pro works for sure (though none of the cameras give explicit control over which sensor to use for some reason, like zero from those that I checked), all of the modes like HDR and such are working too, whether with camera's implementation or via vendor extensions. So it is hard to find the actual quality differences between different good cameras, it is just UI and collection of settings (I'd be happy to read some sources on the topic if I'm wrong here).

**Comment by thestinger** [comment]
Open Camera's HDR is not the same thing but rather is a very bad implementation of traditional HDR. It takes very low quality HDR images with lots of motion blur.

**Comment by thestinger** [comment]
> all of the modes like HDR and such are working too

This is clearly wrong and I don't know why you're saying it.

**Comment by thestinger** [comment]
> So it is hard to find the actual quality differences between different good cameras

There are clear quality differences and differences in focus, etc. and it is not "just UI and collection of settings" at all. There are major differences in capture latency and how they're capturing photos.

GrapheneOS Camera is based on the CameraX library which has a lot of advantages but does not yet support all the configuration you want added. We added EIS based on the Camera2Interop API but that's not an option for everything.

I don't know why you're making all these assumptions but the end result is I see what you're doing as spreading misinformation / concern trolling and will be deleting your issue.
