### ISSUE TITLE
Repeated loss of 4G connection on physical SIMs (Pixel 6a)

### ISSUE THREAD

**Issue by fatopek** [GrapheneOS/os-issue-tracker#1959]
I ran across some issue and couldn't find similar cases and solutions on the GOS forum or here. I consulted with GOS community with no luck regarding solution. While using 4G on my physical SIM (I tried 2 different ones from different providers - the same problem), my connection keeps being completely lost (labeled as disconnected in "Network") and regained in short time intervals, rendering it unusable. It happens regardless of using mobile data or not. I tried different settings (LTE only and LTE as preferred), reboot, reinsert, reset in System settings. Nothing helped. Everything is perfectly fine on 3G and 2G. Wi-Fi works great as well. 4G works fine with these SIMs on another device. GOS is up-to-date.

**Comment by thestinger** [comment]
You would need to test the stock OS to confirm it doesn't happen there. It's likely not a GrapheneOS issue.

**Comment by thestinger** [comment]
I would recommend trying SIMs from friends particularly from a different carrier. There's a high chance that it's a carrier issue where they don't follow standards correctly and have a compatibility issue with the phone, but it could be a hardware issue. You should try other SIMs from people you know if you can to see if it occurs with those. If it happens with other SIMs and also with other carriers, then it's probably a hardware issue. If it doesn't, then you should switch carriers to resolve it.
