### ISSUE TITLE
Repeated com.android.systemui crashes

### ISSUE THREAD

**Issue by PuridsGit** [GrapheneOS/os-issue-tracker#1960]
I've got repeated com.android.systemui crashes on both Pixel 4a and Pixel 6a.
These crashes usually happen when I try to disconnect a Bluetooth headphone but sometimes it just crashes when I turn the screen off or on.

Pixel 4a Build number TQ1A.230205.002.2023021000
Don't have the Pixel 6a in front of me right now but it has all updates on the stable branch.

Here is a log excerpt from a recent Pixel 4a crash:

02-12 22:50:15.127  1665  5280 I ActivityManager: Done dumping
02-12 22:50:15.129  1665  5280 E ActivityManager: ANR in com.android.systemui
02-12 22:50:15.129  1665  5280 E ActivityManager: PID: 5146
02-12 22:50:15.129  1665  5280 E ActivityManager: Reason: Broadcast of Intent { act=android.intent.action.SCREEN_OFF flg=0x50200010 }
02-12 22:50:15.129  1665  5280 E ActivityManager: ErrorId: 75f57cfa-4902-4994-ac82-4d21795bb05d
02-12 22:50:15.129  1665  5280 E ActivityManager: Frozen: false
02-12 22:50:15.129  1665  5280 E ActivityManager: Load: 1.69 / 1.66 / 1.62
02-12 22:50:15.129  1665  5280 E ActivityManager: ----- Output from /proc/pressure/memory -----
02-12 22:50:15.129  1665  5280 E ActivityManager: some avg10=0.00 avg60=0.00 avg300=0.00 total=10504884
02-12 22:50:15.129  1665  5280 E ActivityManager: full avg10=0.00 avg60=0.00 avg300=0.00 total=6301703
02-12 22:50:15.129  1665  5280 E ActivityManager: ----- End output from /proc/pressure/memory -----
02-12 22:50:15.129  1665  5280 E ActivityManager: 
02-12 22:50:15.129  1665  5280 E ActivityManager: CPU usage from 18078ms to 0ms ago (2023-02-12 22:49:52.489 to 2023-02-12 22:50:10.567):
02-12 22:50:15.129  1665  5280 E ActivityManager:   101% 5146/com.android.systemui: 99% user + 2.3% kernel / faults: 40758 minor

Tell me what else I can do to help solve this issue.
Thanks.

**Comment by thestinger** [comment]
We're unable to replicate the issue and there isn't enough information provided about triggering the issue. We're unable to replicate it and others are also unable to replicate it.

**Comment by PuridsGit** [comment]
> @PuridsGit Do you use KDE Connect?
No.

What logs or further information do you need from me?
I don't know anything about android so I would appreciate any help.

**Comment by thestinger** [comment]
There's a more recent issue someone filed with instructions for reproducing an issue and for now we'll have to assume this is the same one.

https://github.com/GrapheneOS/os-issue-tracker/issues/1971

**Comment by PuridsGit** [comment]
> > @PuridsGit Do you use KDE Connect?
> 
> No.

Give that 1971 is about KDE connect and I don't use it i doubt it's the same issue.

Also after the last update the crashes changed. Now the full GUI crashes to sometimes white screen sometimes to black screen and then restarts.
I have a bug report and logcat files. Do you want me to upload them here or somewhere else.

**Comment by PuridsGit** [comment]
After the latest update the symptoms changed again. Now the pull down Android quick settings menu becomes completely unresponsive but does not crash. So I either have to restart the phone or wait and at some point it refreshes and works again. I have created a new bug report. 
Give the private information in that report I would rather send it to you directly and not upload it publicly. Would you please tell me what your preferred way of doing so is?
Cheers
