### ISSUE TITLE
National (presidential) WEA alert can be disabled

### ISSUE THREAD

**Issue by github3939** [GrapheneOS/os-issue-tracker#1964]
* Device: Pixel 7 (Panther)
* Build number: TQ1A.230205.002.2023021000
* Was this issue tested with the stock OS: No

Per [FCC](https://www.fcc.gov/public-safety-and-homeland-security/policy-and-licensing-division/alerting/general/wireless), [CRTC](https://crtc.gc.ca/eng/television/services/alert.htm#AlertsMobile) (and probably other countries) rules, users are not supposed to be able to disable national alerts.

I'm unsure whether or not switching the toggle off would actually disable national alerts, but (on other Android operating systems) this option is usually enabled and grayed out.

https://user-images.githubusercontent.com/125405202/218855224-e549c84b-f5af-4e20-805e-1ec41902dc38.mp4

**Comment by thestinger** [comment]
It's a feature of GrapheneOS.

**Comment by r3g-5z** [comment]
> I'm unsure whether or not switching the toggle off would actually disable national alerts

It does work. A good example of this feature working is in Canada where presidential alerts are sent for everything when they aren't supposed to be presidential alerts.
