### ISSUE TITLE
Google-enabled Geolocation not working

### ISSUE THREAD

**Issue by Segment0895** [GrapheneOS/os-issue-tracker#1965]
I can't get Google-enabled Geolocation working.
Steps done:

- Disable Location requests reroute to the OS
- Grant Play Services Location: always; Nearby-Devices: yes; Battery optimization: off
- Allow Google location services
- Allow Bluetooth scanning and Wifi scanning in Location settings

Attached you can find two logs:

- maps.log
- here.log

HERE Maps doesn't use Google-enabled Geolocation services but is included for comparison of hardware usage (it also has its own Wifi location)

PS: logs are adb logcat, since adb bugreport seems to expose too much info; adb logcat are from secondary profile.

here.zip -- logs removed
maps.zip -- logs removed

Thanks!

DEVICE: Pixel 6a
GrapheneOS version: TQ1A.230205.002.2023021000

**Comment by thestinger** [comment]
Apps using the OS location API won't use the Google Play location service since GrapheneOS doesn't use / integrate Google Play. Only apps using the Google Play location API will use it. It doesn't work the same way as the stock OS. This is working as intended. In the future there could be a way to use the Google Play network location provider in the OS but it's not a bug that it's not used and it shouldn't be used unless users opt into it.

**Comment by Segment0895** [comment]
@thestinger off-topic: can you please add this to the FAQ then?

> Day to day use
>> Will I be able to use Google Maps normally?
>>> Yes and no. Outside, Google Maps will function well using GPS, AGPS and SUPL.
>>> Inside however, it will not work as well as stock. Even if you install the whole Google Services, Google Maps uses _OS location API_ which, in GOS, is **never** redirected to Google Play location API (and will not in the foreseeable future). So unless GPS signals reach your phone, Google Maps will never get a location fix inside a building.

>> Will I be able to use <another Maps software> normally?
>>> Maybe. If you install the whole Google Services, and <another Maps software> uses specifically Google Play location API, you will probably have that specific app working as well as in stock.

>> Which <another Maps software> works well indoors?
>>> Here Maps is reported to work well indoors indoors in GOS.

**Comment by thestinger** [comment]
Google Maps does use the Play API at least if you install it after Play.

**Comment by Segment0895** [comment]
@thestinger hum then it should work indoors? But it isn't and I can't understand why. Installed after Play.

**Comment by thestinger** [comment]
Did you grant the battery optimization exception?

**Comment by thestinger** [comment]
It should be working.

**Comment by Segment0895** [comment]
Agreed. [I pasted some interesting lines on the forum](https://discuss.grapheneos.org/d/3289-google-enabled-geolocation-not-working/4) but honestly I'm not sure what I am looking for.

**Comment by thestinger** [comment]
cc @muhomorr

**Comment by muhomorr** [comment]
@Segment0895 GmsCompatConfig v34 should resolve this issue. It's currently in the alpha channel in Apps app.
Note that in this particular case, Play services app needs to be restarted after GmsCompatConfig update. In the majority of cases this is not needed.

**Comment by Segment0895** [comment]
@thestinger not fully working yet -- got a "Wifi" fix but lost it after 1 min. Will submit further logs when possible, can you reopen?

PS: rebooted device after GmsConfig update.

**Comment by muhomorr** [comment]
@Segment0895 How did you determine that the fix was lost?

**Comment by Segment0895** [comment]
@muhomorr visually, Google Maps had blue dot, became gray. Probably just Wifi fix because radius was a lot smaller than GPS and a bit larger than stock.
I accept ideas for a better way to determine this :))

**Comment by muhomorr** [comment]
Which Play services version are you on?

**Comment by Segment0895** [comment]
@muhomorr exactly, probably not a good one. Uninstalling GMaps, HERE, GSF, Play Services, Play Store. Will report back.

**Comment by Segment0895** [comment]
@muhomorr @thestinger problem was on my side. Google-enabled Wifi geolocation is working!
Thank you for your time!

**Comment by thestinger** [comment]
The original issue was definitely a compatibility layer regression caused by newer Play services versions but I guess the remaining issue you had was something else.
