### ISSUE TITLE
Smooth Display toggle on non-owner profiles not working

### ISSUE THREAD

**Issue by Soup333** [GrapheneOS/os-issue-tracker#1970]
The Smooth Display toggle has no effect when toggled from non-owner profiles. It works just fine in the owner profile and takes effect in the other profiles. (I tested this by going to https://testufo.com and also I can notice the difference clearly)

This is happening on my Pixel 7 but someone said it was also happening on their Pixel 6

**Comment by thestinger** [comment]
Upstream issue not going to be addressed by GrapheneOS downstream.
