### ISSUE TITLE
KDE Connect causes System UI to crash

### ISSUE THREAD

**Issue by FarisZR** [GrapheneOS/os-issue-tracker#1971]
I have faced this issue on multiple devices running Graphene OS, and I could replicate it by installing KDE connect, connecting to a PC, disabling notifications and then leaving it for a day.
It will show up next day morning.

The only post I have seen related to this is:
https://discuss.grapheneos.org/d/2750-system-ui-not-responding-pop-ups/
With a user of a Pixel 4a along with OP also facing the same issue.

Disabling KDE connect immediately solves it.

**Comment by r3g-5z** [comment]
Need logs / a bug report.

**Comment by FarisZR** [comment]
How would I generate a report when it pops up?

**Comment by r3g-5z** [comment]
https://developer.android.com/studio/debug/bug-report

**Comment by FarisZR** [comment]
The file is huge, which part is needed? `DUMPSYS CRITICAL`?

**Comment by r3g-5z** [comment]
It's intended for it to be large. You can email it to june@girlboss.ceo.

**Comment by FarisZR** [comment]
I'm not really comfortable sending it fully, it has a lot of sensitive data.

**Comment by r3g-5z** [comment]
That's the nature of bug reports. If you're not interested in sending it, then you need to give us reproduction steps otherwise this is not a valid issue and will be closed because we cannot action it.

**Comment by FarisZR** [comment]
Ok replication steps:
- Install Gsconnect/KDE connect on a Linux device
- Enable all features except keyboard sharing
- leave it on for about two days with presistent notifications turned off
- System UI pop up should then show up.

I managed to replicate it by following these exact steps on multiple phones, disabling the app fixes it.
Also, the frequency of the pop-up increases with how long the app has been running.

**Comment by telans** [comment]
I'm encountering this same issue on my Pixel 6a. I have my device set up similar to your replication steps; the only difference is that I have less enabled permissions/features for KDE Connect.

One thing to note - it appears to me that once System UI crashes once or twice KDE Connect remains functional yet no further crashes appear even after a week or two.

**Comment by r3g-5z** [comment]
We won't track this here if it's an issue impacting stock OS too. Patch solving the issue may be accepted if identified, but we aren't going to track the upstream bug here.

**Comment by FarisZR** [comment]
But I didn't face this issue on CalyxOS?

**Comment by thestinger** [comment]
@FarisZR  The issue has been confirmed to occur on the stock OS due to a recent AOSP regression. Don't promote scams here.

**Comment by jchoneandonly** [comment]
Pixel 7 pro, started experiencing the system UI crash thing. Happened as soon as I installed the app and got it running. No clue why is doing it but it sucks because kde connect is the best of these kinds of software I've ever had
