### ISSUE TITLE
Phone froze after using Organic Maps for an hour

### ISSUE THREAD

**Issue by steliyan** [GrapheneOS/os-issue-tracker#1972]
Yesterday I was running Organic Maps, at some point during the navigation the app froze, as well as the whole operating system. Gestures (swipe up, swipe back, etc) were unresponsive, nor the side buttons (Pixel 7).

The phone rebooted itself (I saw the GrapheneOS logo), but the phone was still unresponsive. I couldn't enter the SIM PIN code as the touch-screen wasn't responding well (it seems a couple of screens where blending on top of each other). I had a hard-time rebooting the phone manually using the "Lock" button, too.

I was using the main profile ("Owner"), no Google Play Services are installed, I have developer options turned on, but unfortunately, didn't generate a bug report yesterday. I have another profile where I have Google Play Services installed, I am not sure if I ended the session for it, though.

**Comment by thestinger** [comment]
Not going to be able to act on this without further information. It sounds like a hardware issue, not a software one, since there are issues persistent between reboots. Check that the power button isn't broken and being held down without you touching it.

**Comment by steliyan** [comment]
What is the hardware issue, the non-responding gestures, the manual reboot or the initial freeze?

**Comment by andre4ik3** [comment]
Have been having this for last few months, looks like an Organic Maps issue. I don't have consistent steps of reproducing it but for me it only happened when these 4 things were both happening at the same time:

1) Battery saver enabled
2) Airplane mode enabled
3) Listening to music via bluetooth headphones
4) Walking route in Organic Maps

Also not a hardware issue. I have two Pixel 7 Pros and it happens on both of them.

I'll report in organic maps repo and link back to this issue

**Comment by thestinger** [comment]
I don't think reporting it as an Organic Maps issue makes sense and it's quite possible that it's tied to Bluetooth rather than Organic Maps. I would guess that it's more likely related to Bluetooth.

**Comment by andre4ik3** [comment]
Maybe something to do with Organic Maps' voice instructions? I'm starting to narrow it down here, sounds like attempting to play TTS audio over bluetooth whilst something else is playing causes the device to freeze. I'll test tomorrow morning if turning off TTS fixes it.

**Comment by biodranik** [comment]
It looks like a Pixel 7 or Android 13 issue. @steliyan you can send us bug reports at android at organicmaps dot app

**Comment by biodranik** [comment]
Please, also try to type `?gl` in the search box of Organic Maps, and restart the app. Maybe it is related to Vulkan drivers embedded in the OS.

**Comment by biodranik** [comment]
It could be a TTS engine issue. Let's check this hypothesis. Do you all use the same TTS engine? Can you please try to install/activate something else?
Can you please try to reproduce the issue with TTS _disabled_ in Organic Maps?

**Comment by andre4ik3** [comment]
Update from the test: It wasn't really scientific, I only opened it for 2 minutes, typed in a destination, saw that it didn't crash, and moved on, as I didn't really have time. From what I've heard, and from my experience looking back, it takes 5-10 minutes or so to kick in. I'll repeat again several times but I will have it on for the whole commute and see whether or not it crashes.

I use Google TTS engine with GSF and GMS (no Play Store). None of the 3 apps have any permissions, including network and sensors. I only turn on network for TTS to update it once in a while and then turn it off again.

I'll try a few combinations, trying different TTS engines and GL on/off. One question - how do I know the GL input worked (or, rather, how to tell if it's using Vulkan or OpenGL)? I don't see any indicator in the app, or maybe I'm just not doing it right. (For context, I typed `?gl` into the search menu from the search button on the bottom, then hit enter, then go to android settings and force stop, then open again)

**Comment by biodranik** [comment]
Vulkan rendering does not recreate/redraw the screen when not needed. You can switch back to it by typing `?vulkan`.

**Comment by andre4ik3** [comment]
Ok. Today I tested it for around 30 minutes with `?gl`. No crash. Tomorrow will test with `?vulkan`.

**Comment by flawedworld** [comment]
If it is something to do with Vulkan, it may or may not be notable that Tensor Pixels have moved to Vulkan 1.3 now as of QPR2.

**Comment by andre4ik3** [comment]
Today I tested it for another 30 minutes on the same route with vulkan and it didn't crash again. Seems like the new update fixed it!
