### ISSUE TITLE
Contact name does not show up if number is stored without countrycode

### ISSUE THREAD

**Issue by damige** [GrapheneOS/os-issue-tracker#1974]
When receiving a phone call the number +31612341234 is displayed. In contacts number 0612341234 is stored as contact A.
The normal behavior is to show A is calling, but in staid its +31612341234.

**Comment by damige** [comment]
Yes it completely matches. I have noticed contacts not being displayed over a while. I just opened the call history again and i noticed it auto-completing the "unknown" numbers to the correct contact

The only thing i changed earlier today was: adding permission to Photos and Videos and location for the 'phone' app.
Could it be that the 'phone' app needs location permissions to match the country-code?

**Comment by thestinger** [comment]
No, it doesn't need location.

**Comment by thestinger** [comment]
Did you take away contacts access from the Phone app?

**Comment by damige** [comment]
I did not. 
Additional information: Contacts are synced from Nextcloud through DAVx. There were no changes to any settings other then posted above. Contacts were not resynced either. I did force-close the 'Phone' app and 'Contacts' app however. 
I dont believe the force-close should have done much as i reboot at every update (and this problem was first observed on jan16th.

If it does not use location, how does the phone app know which country-code to match. Or will all country-codes match a non countrycode stored phonenumber.

**Comment by thestinger** [comment]
Cellular country code doesn't require location.

**Comment by thestinger** [comment]
See the planned feature we have filed about supporting spoofing that.

**Comment by damige** [comment]
Alright, its typical that after >1 month of struggling with this it works again soon after posting an issue. It would have to be one of the things i did before. I will close the issue for now and monitor it in the future. Thanks for your time.
