### ISSUE TITLE
Clearing tracking elements from URLs in clipboard

### ISSUE THREAD

**Issue by surfaceflinger** [GrapheneOS/os-issue-tracker#1975]
As in title. This option could be disabled by default because of false positives rendering the URLs useless. After enabling it we could somehow exclude clipboard sources like specific apps.

This would improve privacy of both GrapheneOS users and people who use different operating systems. From the UX side, this would make user generated content like DMs more aesthetically pleasing.

On PCs it's already possible by installing clearurls.xyz extension. (ofc it's only available for browsers, but browsers are usually the only source of URLs in PC, on Android we have sharing option in apps like Twitter which adds t= and s= tags)
I'm not sure if they write rules for every single website or somehow detect what's worth of getting rid of.

**Comment by thestinger** [comment]
A keyboard can provide this as part of a clipboard manager. I don't think it belongs in the OS when the OS already provides what's needed to do it.
