### ISSUE TITLE
Airplane mode..

### ISSUE THREAD

**Issue by maanz79** [GrapheneOS/os-issue-tracker#1980]
Hi. With latest updates TQ1A.230205.002.2023022300 on my pixel 5a, when I'm on airplane mode, calls and sms can still be received and make through. Even wifi is on, when i press the airplane mode button, the wifi didn't turn off. I tried recieved a call on airplane mode and it gets pass through. Usually, wifi/network will turn off when I press the airplane mode button. Is this a bug? Thanks..

![Screenshot_20230226-120150_1](https://user-images.githubusercontent.com/40461702/221391732-cf894c7a-96e4-466e-8282-0a831cbc7baf.png)

**Comment by thestinger** [comment]
Airplane mode disables the cellular radio. It doesn't force Wi-Fi and Bluetooth to be disabled. It disables them the first time, but then remembers if you want them to remain enabled. Calls and texts can work via Wi-Fi if your carrier supports it.

**Comment by maanz79** [comment]
So meaning, i can still received calls and sms on airplane mode without wifi on?

**Comment by thestinger** [comment]
That's not what was stated. You said that Wi-Fi was on and didn't turn off when enabling airplane mode which is because it remembers the state. It's also possible to have internet via USB or Bluetooth.

**Comment by maanz79** [comment]
Okay. So, now I have an issue where I'm able to browse the internet on airplane mode with no wifi. How is this possible? Is it not a bug?

**Comment by thestinger** [comment]
It doesn't sound like you have airplane mode enabled unless you're using another form of internet access via USB or Bluetooth. You're going to be to provide more information. It's known that there's a UI bug where the quick tile state, etc. can get out-of-date in some cases so please check the Settings app.

**Comment by maanz79** [comment]
I don't use any internet access via USB or Bluetooth.
Okay, what would you like me to do?
What I've done is, from the quick tile: wifi off, turn on airplane mode. There will no network connected. I make a call and sent and sms to my 2nd phone and the call and messages gets through/received. The screenshot taken above is the proof to my issue.

**Comment by maanz79** [comment]
![Screenshot_20230226-231525_1](https://user-images.githubusercontent.com/40461702/221419494-607eb69e-bea5-45d9-9249-30bd27a0070e.png)

After a reboot with airplane mode on, I turn off airplane mode and it gives this exclamation mark. Tried to on back airplane and off still gives the mark.

**Comment by thestinger** [comment]
That doesn't seem relevant. It's expected that cellular will take some time to connect after enabling airplane mode. It sounds very much like you're providing internet to your device through Wi-Fi, Bluetooth or USB.

**Comment by maanz79** [comment]
No, i don't have any internet through wifi, bluetooth or usb.
