### ISSUE TITLE
Spell checker is missing a lot of languages

### ISSUE THREAD

**Issue by alexgirto** [GrapheneOS/os-issue-tracker#1983]
There are only 11 languages to choose for spell check. This is severely lacking compared to system language availability. The Keyboards for a language such as Romanian works, however spell check is missing.

Is there a workaround while we wait for a fix?
![signal-2023-02-26-111930_002](https://user-images.githubusercontent.com/5903406/221431991-e05d65b7-37cd-47b2-acba-df69914196cf.png)

**Comment by thestinger** [comment]
You can use a different keyboard. We're not going to develop support for more languages for AOSP keyboard.

**Comment by thestinger** [comment]
Please use https://discuss.grapheneos.org/ or the Matrix chat room for support, not the issue trackers.
