### ISSUE TITLE
Ensure Play Integrity API returns MEETS_BASIC_INTEGRITY

### ISSUE THREAD

**Issue by flawedworld** [GrapheneOS/os-issue-tracker#1985]

**Comment by flawedworld** [comment]
https://twitter.com/MishaalRahman/status/1631056496187396099 will be useful for debugging

**Comment by r3g-5z** [comment]
Seems to already pass MEETS_BASIC_INTEGRITY if you give Play services the Phone permission. May want to document this and/or make GmsCompat more user friendly for this.

**Comment by thestinger** [comment]
https://github.com/GrapheneOS/os-issue-tracker/issues/1987
