### ISSUE TITLE
Spoof CTS Profile checks in Play Integrity API checks to pass with MEETS_DEVICE_INTEGRITY

### ISSUE THREAD

**Issue by flawedworld** [GrapheneOS/os-issue-tracker#1986]
This has to be non-invasive and minimal.

**Comment by Segment0895** [comment]
Spoof? Isn't that contrary to GOS goals?

**Comment by r3g-5z** [comment]
In what way? If there's a non-invasive, sandbox-friendly, minimal, and safe way to improve app compatibility by passing this why would we not want to do it? It could possibly make apps like Google Pay work. What "goals" is it conflicting with?

**Comment by flawedworld** [comment]
> Spoof? Isn't that contrary to GOS goals?

It would have to be on an opt-in basis alongside an explanation that it is ultimately not a bulletproof mitigation, and that apps may suddenly break.

**Comment by Anleqq** [comment]
Hi, is there any progress on this feature or any ETA on when it will be available? I'm currently deciding between GrapheneOS and stock OS, and GrapheneOS not passing MEETS_DEVICE_INTEGRITY is the only thing that keeps me and my friends from using GrapheneOS.

**Comment by x0wllaar** [comment]
I would agree with that, a lot of banking / payment apps use CTS checks now :(

On a more personal note, this is the only problem that really keeps me on iDevices now

**Comment by shelvacu** [comment]
To avoid being just another "+1", "this is really important to me", "please do this", I'll put my money where my mouth is.

I'm willing to donate $500 to GrapheneOS once this is implemented, available on stable, and google wallet works. This expires 6 months after this is posted. (I would very likely be willing after that but just want to constrain my promises) HMU if you want to discuss details, talk to me on discord or gmail with the same username

**Comment by shelvacu** [comment]
I realize that google could change their proprietary code the day after this feature is finished and make it useless, I am willing to take that risk.

That said, I can understand people may not want to take the particular deal, that's fine. I hope I've at least brought more attention to the issue.

**Comment by oDinZu** [comment]
> The only reason not to do this would be because then people would be relying on these apps working and will be disappointed when it is no longer possible to spoof this in the future.
> 
> That said, there's no timeline for when that time will come, so having this in the meantime would be great for a lot of people!

The Uber Driver app currently doesn't work on GrapheneOS because it relies on Google Play. I presume this is an Attestation issue and another reason GOS should get this working. I rely on Free Software as an Independent Contractor; all the hefty fees and proprietary data on a bloated "stock" Android OS is a security nightmare.

**Comment by storopoli** [comment]
> The **Uber Driver** work app currently doesn't work on GrapheneOS because it relies on Google Play. I presume this is an Attestation issue and another reason GOS should get this working. I rely on Free Software as an Independent Contractor; all the hefty fees and proprietary data on a bloated "stock" Android OS is a security nightmare.

As  workaround you can use the PWA, which works flawlessly

**Comment by thestinger** [comment]
Spoofing Google certification without now requires spoofing a legacy device model that's either quite old or shipped with a broken hardware attestation implementation. Google appears to be actively banning the build fingerprints being used for spoofing at scale. GrapheneOS has far too many users for us to avoid this being detected and acted upon. It's not looking good for this.

**Comment by oDinZu** [comment]
It is quite upsetting what Uber Inc. is doing. 

As an Independent Driver and Business, it is our responsibility to secure and protect our hardware and software from any outside threats.

By disabling rooted devices from their `whitelist`, the drivers and business's are unable to protect their own business. We are forced to use insecure bloated Corporate software that tries to micro manage entire nations.

Maybe we need a lawyer to fight for small independent business's? 

It is absurd how these Corp. are _over stepping_ their boundaries and forcefully nesting their 3rd party services inside small business infrastructure.

**Comment by oDinZu** [comment]
If Uber reads this, a minimal solution would be to add GrapheneOS to their `whitelist`. 

They may do so here: https://grapheneos.org/articles/attestation-compatibility-guide

**Comment by oDinZu** [comment]
> 2) they use hardware-based attestation to support GrapheneOS per our guide with no loss of control over _the_ drivers.

**Comment by oDinZu** [comment]
> > The drivers are independent business's that do their own tax work.
> 
> They're controlling what people can do with their personal devices which shows they're employees. Uber committing fraud to avoid employment laws and taxes is their problem. This is simply evidence of that.

If that were true, then they would need to purchase our phones, vehicles and provide the necessary insurance and benefits. Their entire business model would collapse..

No thank you; I am responsible for my own Freedom.

**Comment by e-t-l** [comment]
I'm not seeing _when_ this issue was closed, but evidently it's closed now, so I guess that means devs are no longer considering it?

That's a shame. Even if the useful lifespan of spoofed CTS were limited, it would likely solve the problem of RCS messaging's instability on GrapheneOS: https://discuss.grapheneos.org/d/1353-using-rcs-with-google-messages-on-grapheneos/227. Especially since Apple is adopting RCS, and I believe it's becoming the default messaging protocol on all new Android phones, it seems like it would _really_ align with Graphene's mission to adopt a widespread, extremely secure, open-source, E2EE messaging protocol. (While I don't know what's happening behind the scenes with the core dev team, I'm actually surprised RCS compatibility _hasn't_ been a bigger goal so far.) 

And while there's clearly something at a system level that's interfering with Google Message's RCS provisioning, implementing CTS spoofing would be a much-welcomed stopgap to make RCS work until a more permanent solution is discovered.

**Comment by Z0pyrus** [comment]
Something interesting to consider, that would solve all these problems might be the DMA from the EU. https://discuss.grapheneos.org/d/11424-could-eus-dma-facilitate-verification-of-alternative-os-like-grapheneos

**Comment by locksec** [comment]
So what's the long-term solution here? It seems that the Uber Driver app, ChatGPT, Starbucks, American Airlines, Marriott, and a growing number of apps are using Play Integrity API and MEETS_DEVICE_INTEGRITY is the culprit? Are we going to be in a situation in 6-12 months time where that list of apps has grown even more?

**Comment by locksec** [comment]
> Beyond that, there's nothing we can do.

Yeah this is my concern. So far the apps that use Play Integrity API are not breaking my daily usage, I can live without them, but it might get to a point where more app developers use it, rendering my GrapheneOS device impractical for daily usage.

**Comment by locksec** [comment]
> you're turning to us for a solution

No I totally agree. I'm gathering information here so I understand this correctly. I didn't want to step on to my soap box if I were missing something, which it turns out I'm not. I'll do my part to highlight this and yes.... I agree with the meaningless checks part!

**Comment by Segment0895** [comment]
In addition to us pressuring the companies, one can keep a topic label on
the forums to keep track of which have problems with a secure, non-Google,
OS, and periodically contact the European Comission/Federal
Government/EFF/FSFE in order to raise awareness.

It is my naive opinion this constitutes a constriction of the existence of
a single market, which seems to be highly valued by certain government
bodies as a necessity to achieve better market competition.

**Comment by Curve** [comment]
> In addition to us pressuring the companies, one can keep a topic label on
> the forums to keep track of which have problems with a secure, non-Google,
> OS, and periodically contact the European Comission/Federal
> Government/EFF/FSFE in order to raise awareness.
> 
> It is my naive opinion this constitutes a constriction of the existence of
> a single market, which seems to be highly valued by certain government
> bodies as a necessity to achieve better market competition.
> 
> > Message ID: ***@***.***
> > com>
> >
> 

Totally agree, competition is absolutely hindered when some apps decide to restrict access to their service based on a false idea of security - even those that have no real purpose to "block" an "insecure" OS.

**Comment by oDinZu** [comment]
> Users contact us about it instead of bothering app developers and convincing them to implement https://grapheneos.org/articles/attestation-compatibility-guide. If you want apps to do that, you're going to need to make a concerted effort to bring it on their radar by having many people persistently contact their support, engineers, etc. on a daily basis until it becomes noisy enough for them to consider it.

Where is _their_ contact information or phone numbers? :smile: They make it so you have to know the developer and have the technical know how to even understand the issue..

**Comment by aly-k** [comment]
> Users contact us about it instead of bothering app developers and convincing them to implement https://grapheneos.org/articles/attestation-compatibility-guide.

Expecting companies to allocate expensive developer time on an OS-specific implementation when an API that covers all stock android phones exists is a bit unrealistic, don't you think? 
Unfortunately, I also don't have solutions for you but "pressuring the developers" isn't it.

**Comment by aly-k** [comment]
Apologies i am not a developer. From what i understand, Apps that use the play integrity API currently leave all the work of hardware attestation to google and they just check the returned pass/fail value.
On the other hand using the linked android API, apps would have to implement or fork a function to verify keys and they would also have to keep track of keys for all different devices on custom ROMs that meet their security requirements.

**Comment by cryi** [comment]
Hmm, can't we use pKVM and virtualize some lightweight android to provide CTS checks for us? Or even to provide entire wallet experience? Like separate user profile for banking.

**Comment by Segment0895** [comment]
> Hmm, can't we use pKVM and virtualize some lightweight android to provide CTS checks for us? Or even to provide entire wallet experience? Like separate user profile for banking.

Maybe. But that's probably a lot of dev hours, getting an unfair feature working, without knowing if corporate overlords would get annoyed with GOS and block GOS wrappers or something. Don't poke the bear.

Honestly, I think this is better handled with a forum topic instead of commenting. I'd suggest closing the issue and blocking further posts.

**Comment by Z0pyrus** [comment]
Yeah. I think that as well. But maybe link the forum post here.

**Comment by Segment0895** [comment]
I suggest this topic to be moved to the forums [Spoof CTS Profile checks in Play Integrity API checks](https://discuss.grapheneos.org/d/13716-spoof-cts-profile-checks-in-play-integrity-api-checks).

**Comment by cryi** [comment]
Well point of pKVM wasn't really spoofing. It would be perfectly ok if we just get VM abstracted as separate user profile. That should look as any other android, be upgradable as one... etc.

**Comment by mxsrm** [comment]
I guess we can only hope the lawsuit I read about against Google moves something. I would immediately switch my Pixel 9 (Pro soon to be) to GrapheneOS and never look back, if CamAPS FX ([Play Store Link](https://play.google.com/store/apps/details?id=com.camdiab.fx_alert.mgdl)) didn't rely on Play Integrity check and is simply not allowing connection to the insulin pump (and CGM) if that check fails... Sadly that is one app I can not replace with anything else short of buying a new insulin pump for >3k € of my own money... :/

**Comment by mxsrm** [comment]
The company behind this medical product is probably not even technical capable of implenting this. They are working on a iOS version of the app for almost 5 years now (mind you; this is a product that costs >1000€/year and they are still not able to supply the vast amount of possible clients with iOS; so huuuuuuge incentive to get this done as fast as possible).

I wish it was as simple. Keep up the good work!

**Comment by e-t-l** [comment]
Because they're crappy devs, they don't know what Play Integrity actually does, and they don't care. @mxsrm I'm sorry that you have to deal with such terrible biotech/insurance companies. I don't know what exactly you need the app to do, besides be connected, but frankly your best option right now might be to buy a small cheapo smartphone (like a $30 one) with default Android and no sim card, install your CamAPS app on it, then wifi-tether it to your main smartphone for internet connectivity. It's another thing to carry around and keep charged, but it would at least allow you to use that app while still having GOS on your daily driver.

**Comment by iMonZ** [comment]
> You can't pass the Play Integrity device integrity check with the stock Pixel OS fingerprint, etc. You need to pretend to be an insecure old device without hardware attestation or hardware attestation is required. There's no spoofing for the strong mode and the device mode is gradually moving towards closing the loophole of old devices without hardware attestation. Faking hardware attestation requires vulnerabilities, although those can be used to leak keys to reuse but they'll get blacklisted.

Wait. But what if you use the keys from a second pixel with the stock rom that you extract. But this second pixel stayed offline so Google can’t detect you activating everything twice.

**Comment by jason-eu** [comment]
> People who care about alternative OSes should be pressuring these companies into dropping these meaningless checks. I understand that you're turning to us for a solution, but we're the wrong party to turn to, in this case. We aren't the ones imposing arbitrary restrictions.

Is there a place where people can go to support GrapheneOS's endeavours in this regard ?

Like a dedicated page where GrapheneOS allows people to add their vote/signature to a kind of petition towards change ?

**Comment by jason-eu** [comment]
> Users contact us about it instead of bothering app developers and convincing them to implement https://grapheneos.org/articles/attestation-compatibility-guide. If you want apps to do that, you're going to need to make a concerted effort to bring it on their radar by having many people persistently contact their support, engineers, etc. on a daily basis until it becomes noisy enough for them to consider it.

I think the most effective way to achieve this may be the singular targeting of apps.

For example, a channel on Discord dedicated to announcements of which app is being targeted at that point in time, coupled with a template of what should be put in the mail/message from each user.

As well as a template for a message to be put into 1 star play store reviews.

If done en masse, at least with the numbers on the discord/telegram/Reddit/dedicated forums, it is likely to effect at least one of two things, the change needed to tech blogs beginning to publish articles of it further pushing its traction.

It's almost as if GrapheneOS requires a department dedicated to fighting the propaganda that makes it get treated like a run-of-the-mill custom ROM.
