### ISSUE TITLE
Transition UI artifact with animations disabled

### ISSUE THREAD

**Issue by chagar** [GrapheneOS/os-issue-tracker#1988]
Reproduction:
* Disable animations in Settings -> Accessibility -> Color and motion
* From the home screen, open any app (Clock, Settings, Messaging, etc.)
* Close it to go back to the home screen, with any of these methods:
  * If Gesture navigation is enabled, swipe right to "go back".
  * If 3-button navigation is enabled, press the back button (first button) or home button (middle button)
* You should see a large logo displayed briefly in the upper-center of the screen:
  * It quickly goes away (a few hundred ms?).
  * The home screen is displayed first or at the same time.
  * The logo is the logo of the app you just closed (large white circle with app logo inside).

Expected:
* Just display the home screen. No UI artifact. No quick blip.

**Comment by thestinger** [comment]
This would need to be reported upstream to AOSP.

**Comment by r3g-5z** [comment]
Disabling animations is known to be very buggy on both stock OS and AOSP and has caused various kinds of issues before. It's an option that originated in Developer options and I'm not sure why they moved it to Accessibility settings without improving or fixing bugs with it, or at least put a warning that UI glitches or bugs may occur from it.

This is something that upstream should deal with and we won't be tracking this here.

**Comment by chagar** [comment]
Okay. Thank you.
