### ISSUE TITLE
Swipe to close notifications on lockscreen 

### ISSUE THREAD

**Issue by sm131313** [GrapheneOS/os-issue-tracker#1990]
Currently, it is only possible to remove notifications on lockscreen if you have show sensitive content enabled on lockscreen. 

If sensitive content is not enabled, it is not possible to remove the notifications on lockscreen. Causing an unnecessary password entry and unlock of the phone, just to swipe them away and have them removed.

**Comment by thestinger** [comment]
We don't plan on adding an Android UI feature like this.

**Comment by thestinger** [comment]
We're not going to be changing how this works. It already works in a reasonable way and we're not going to add a configurable feature for this very niche request. This really isn't what GrapheneOS works on.
