### ISSUE TITLE
Notifications are not synced across devices if device is locked

### ISSUE THREAD

**Issue by sm131313** [GrapheneOS/os-issue-tracker#1991]
In current design. GrapheneOS is leaving traces of notifications on lockscreen if the notification has been adressed already on another device. 

To reproduce:
Lock phone
Send an email to an IMAP address you have set up on GrapheneOS.
Use the webclient from another device to read the email. 
The notification is not removed and email is not marked as being read. 

If you unlock the phone the notifications are synced and any notifications which has already been addressed on another device are being removed from GrapheneOS. 

Another example to reproduce
You are logged in on Telegram desktop, Skype or whatever other instant messenger service and send/receive messages there. The notifications from these are being loaded on your device lockscreen when they have already been read and thus should be removed also from lockscreen. 

If your device is not locked, the notifications are synced and gets automatically removed from your device since they have already been marked as read. So above issue occurs only when device is locked.

**Comment by thestinger** [comment]
This is up to the app not GrapheneOS. Apps make notifications and choose if they want to remove them.
