### ISSUE TITLE
Contact Groups?

### ISSUE THREAD

**Issue by QuestioningEspecialy** [GrapheneOS/os-issue-tracker#1994]
The one thing the Contacts app seems to be missing is Groups. While [OpenContacts](https://gitlab.com/sultanahamer/OpenContacts) has it, that app lacks photos/images. 🤷🏿‍♂️
Any chance of Groups being added? Admittedly, people can just use [Simple Contacts](https://github.com/SimpleMobileTools/Simple-Contacts) instead, so there's really no hurry. >.>

**Comment by thestinger** [comment]
We don't plan to add features like this to AOSP Contacts.
