### ISSUE TITLE
Configure FeliCa support on Japanese Pixels

### ISSUE THREAD

**Issue by flawedworld** [GrapheneOS/os-issue-tracker#1995]
Relevant SKUs:
Pixel 4: G020N
Pixel 4 XL: G020N
Pixel 4a: G025M
Pixel 4a 5G: G025H
Pixel 5: G5NZ6
Pixel 5a: G4S1M
Pixel 6: GR1YH
Pixel 6 Pro: GF5KQ
Pixel 6a: GB17L
Pixel 7: GO3Z5
Pixel 7 Pro: GFE4J

This may work on some (all?) non-Japan Pixels. Needs testers, but it 100% works on Japan SKUs.

**Comment by flawedworld** [comment]
Working implementation is at https://github.com/petterroea/graphene_platform_packages_apps_PixelNFCStub

**Comment by flawedworld** [comment]
Device integration:
https://github.com/GrapheneOS/device_google_coral/pull/43
https://github.com/GrapheneOS/device_google_sunfish/pull/30
https://github.com/GrapheneOS/device_google_redbull/pull/29
https://github.com/GrapheneOS/device_google_gs101/pull/26
https://github.com/GrapheneOS/device_google_gs201/pull/4

Testing can be done with https://play.google.com/store/apps/details?id=com.felicanetworks.mfm.main

**Comment by r3g-5z** [comment]
Now shipping the app from stock OS and deprivileged it in https://github.com/GrapheneOS/adevtool/pull/53
