### ISSUE TITLE
Pixel 4a: Fingerprint Sensor not working anymore

### ISSUE THREAD

**Issue by kaleresan** [GrapheneOS/os-issue-tracker#1998]
Device: Google Pixel 4a
Android version: 13
Build nr: TQ1A.230205.002.2023030400

Since this Morning the fingerprint sensor of my device doesn't work anymore. The Option for enabling the Fingerprint sensor has dissapeared from the settings. Even swiping down on the sensor to open notifications doesn't work. It is as if the phone didn't have a fingerprint sensor.

**Comment by thestinger** [comment]
This must be a hardware failure.

**Comment by kaleresan** [comment]
After Installing yesterdays Update it works again. So it doesnt seem to have been a Hardware failure.
Current Build Nr: TQ2A.230305.008.C1.2023032000

**Comment by thestinger** [comment]
That doesn't mean it's not a hardware failure.

**Comment by thestinger** [comment]
If there's a flaky connection that only sometimes connects to the OS will sometimes work and sometimes not depending on whether it connected at boot for initialization.
