### ISSUE TITLE
Expose wireguard kernel module in frameworks and settings

### ISSUE THREAD

**Issue by renlord** [GrapheneOS/os-issue-tracker#200]

**Comment by shortcak** [comment]
Is the ideal thing is to get WireGuard integrated into AOSP upstream first so that GrapheneOS does not need to maintain it downstream?

**Comment by renlord** [comment]
Yes.

**Comment by renlord** [comment]
> Is the ideal thing is to get WireGuard integrated into AOSP upstream first so that GrapheneOS does not need to maintain it downstream?

Yes

**Comment by vzlcn0** [comment]
@shortcak I think they working to add it only on the new kernels (5.4), I do not know if they will enable it for older kernels
https://android-review.googlesource.com/q/WireGuard

I think is good idea to support IKEv2 also since it's almost done
https://android-review.googlesource.com/q/IKEv2

**Comment by thestinger** [comment]
I don't see any work to add it there.

**Comment by thestinger** [comment]
Enabling the kernel feature doesn't make a difference without implementing support for it in userspace. The kernel support isn't accessible to apps from their sandbox.

**Comment by jpds** [comment]
Android gained native WireGuard support with this commit: https://android.googlesource.com/kernel/common/+/99761f1eac33d14a4b1613ae4b7076f41cb2df94%5E%21/

The userspace Android app already opportunistically uses the kernel implementation if it's found: https://git.zx2c4.com/wireguard-android/about/ (not sure how the sandbox would affect this).

GrapheneOS could use either of the methods here to integrate the module while waiting for the Android commit to land: https://git.zx2c4.com/android_kernel_wireguard/about/#method-b-integrating-into-roms

**Comment by thestinger** [comment]
> Android gained native WireGuard support with this commit

No, it didn't. It was enabled in one of the common kernel configurations. That doesn't mean it gained support for WireGuard even with that kernel.

> The userspace Android app already opportunistically uses the kernel implementation if it's found: https://git.zx2c4.com/wireguard-android/about/ (not sure how the sandbox would affect this).

Nope, it can't do that without breaking the whole security model with app-accessible root.

> GrapheneOS could use either of the methods here to integrate the module while waiting for the Android commit to land: https://git.zx2c4.com/android_kernel_wireguard/about/

Neither of those approaches results in having WireGuard support. You're missing the point of this issue entirely.

**Comment by thestinger** [comment]
As I said above already:

> Enabling the kernel feature doesn't make a difference without implementing support for it in userspace. The kernel support isn't accessible to apps from their sandbox.

**Comment by jpds** [comment]
Ah, apologies, I have done some more research and I now see that the Android kernel implementation requires the device to be rooted.

**Comment by anupritaisno1** [comment]
There is at least one Qualcomm driver that is confirmed to cause a kernel panic when a kernelspace wireguard tunnel is brought up. We don't ship it in grapheneos but we don't know if google does on their stock ROM. The userspace implementation is fine

In any case, it has to be upstream who starts working on the feature and preferably on a kernel that comes with the wireguard driver as it was mainlined (so we need a 5.x kernel). Google has to enable it and work with Qualcomm to address issues in their drivers

**Comment by jpds** [comment]
More news from Google: https://www.xda-developers.com/google-adds-wireguard-vpn-android-12-linux-kernel-5-4/ - though nothing on the API yet.

**Comment by thestinger** [comment]
We're going to wait for the upstream implementation. This doesn't offer improved privacy/security compared to the userspace implementation. It only offers better performance, which only offers very negligible improvements to battery life. This isn't needed to use wireguard.

**Comment by thestinger** [comment]
Performance optimizations for a VPN protocol is simply out-of-scope. Just wait for the upstream implementation. OpenVPN is never going to have a kernel implementation and of course it works fine.
