### ISSUE TITLE
Pixel6a not booting complete after update

### ISSUE THREAD

**Issue by DVANTON** [GrapheneOS/os-issue-tracker#2004]
Hello! After automatic update yesterday Pixel 6a continuously freeze on GrapheneOS bootloader and not go through.
I try to reinstall update by Sideloading - no effect.
I have not had time to make a backup yet, I just set up and installed applications and transferred the photo.
How can i save data?

**Comment by thestinger** [comment]
You can use the system backup functionality. This doesn't seem like a GrapheneOS issue but rather hardware failure.

**Comment by DVANTON** [comment]
is there some workearound to use slot b fro booting?

**Comment by DVANTON** [comment]
The phone won't go past the loading screen.

**Comment by thestinger** [comment]
If it fails to boot a single time, it will automatically roll back. If it booted at least once successfully, it won't roll back, You can boot recovery and sideload the same update if the issue is a partial SSD failure.
