### ISSUE TITLE
Lock Screen Clock Icon Misalignment

### ISSUE THREAD

**Issue by JayXT** [GrapheneOS/os-issue-tracker#2006]
Device: Pixel 6a
OS version: TQ1A.230205.002.2023030400 (latest stable)
It looks that the clock icon indicating the time for the upcoming alarm isn't separated with date. I assume there should be at least one or two whitespaces between the icon and the day:

![Lock Screen With Bug Indicated](https://user-images.githubusercontent.com/8045344/224004596-8cc4ee26-ad00-4aa1-8418-ab0f9d8dabe1.png)

**Comment by r3g-5z** [comment]
Won't be fixing this downstream. This is an AOSP bug.
