### ISSUE TITLE
Pixel6a stuck in boot after update bluejay-ota_update-2023030400

### ISSUE THREAD

**Issue by DVANTON** [GrapheneOS/os-issue-tracker#2009]
Hello! 
After automatic update Pixel 6a continuously freeze on GrapheneOS bootloader and not go through.
I try to reinstall update by Sideloading - no effect.
The phone won't go past the loading screen.(photo attached)
Please see the logs attached.
![Booting](https://user-images.githubusercontent.com/127389047/224246908-dab8e636-189a-4b4d-b970-0612697c2f04.jpg)
![logs1](https://user-images.githubusercontent.com/127389047/224246953-22ddeb47-8570-4707-9d04-cd9d0a8dfe31.jpg)
![logs2](https://user-images.githubusercontent.com/127389047/224246974-23d50d52-032c-4d1f-ad6c-57376ea79802.jpg)
![logs3](https://user-images.githubusercontent.com/127389047/224246996-6f89ae14-8920-46e0-a32f-eb3e1b16ef48.jpg)
![logs4](https://user-images.githubusercontent.com/127389047/224247011-fe148389-9438-40db-b5af-d0bc3ff3e5a0.jpg)
![logs5](https://user-images.githubusercontent.com/127389047/224247020-895f4342-2147-40e9-be11-74d9f31161d3.jpg)
![logs6](https://user-images.githubusercontent.com/127389047/224247037-6436445c-b3b9-4614-acc0-a4a8a76326cc.jpg)
![logs7](https://user-images.githubusercontent.com/127389047/224247055-29df44a1-5fcb-4999-8ff2-dd7d38c9ec8f.jpg)

**Comment by thestinger** [comment]
You can try sideloading the latest version with recovery.

**Comment by thestinger** [comment]
Duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/2004.

**Comment by DVANTON** [comment]
Yhank you for your answer.
Could you please provide the correct sequence of steps.

PS I could not find a suitable item in the FAQ

**Comment by thestinger** [comment]
https://grapheneoe.org/usage#updates-sideloading

**Comment by thestinger** [comment]
https://grapheneos.org/usage#updates-sideloading

**Comment by thestinger** [comment]
It won't erase data.

**Comment by DVANTON** [comment]
Cool!
and last question:
final version for 6a is
1. https://releases.grapheneos.org/bluejay-factory-2023030400.zip
2. https://releases.grapheneos.org/bluejay-ota_update-2023030400.zip

which one should I use?
FACTORY VS OTA_APDATE?

**Comment by DVANTON** [comment]
Thank you so much! best wishes!

**Comment by DVANTON** [comment]
unfortunately it was not worked :(

**Comment by r3g-5z** [comment]
You need to get a replacement device, it has a hardware failure.

**Comment by DVANTON** [comment]
i don't think so. I was use "Wipe data/factory reset" point in GrapheneOS Recovery section. It rebooted and work again.
unfortunately i lost all my data.
i will be backup more often!

**Comment by thestinger** [comment]
That is still potentially a hardware failure such as data corruption from SSD failure.

**Comment by DVANTON** [comment]
ок. will see.
but could  you probably add a check for data integrity during automatic updating.
