### ISSUE TITLE
Waking up to frozen black screen

### ISSUE THREAD

**Issue by PrimoDev23** [GrapheneOS/os-issue-tracker#2010]
Hello altogether,
I recently bought a Pixel 7 to replace my old phone. The installation was super easy and everything went fine until today's morning. I woke up to a not responding phone, having a black screen. I first tried to charge it, but there was no charging indicator at all. I left it charging for about 5 minutes and nothing happened. I also tried to force reboot, but that didn't work either and also booting into bootloader didn't work. The phone was basically 100% dead until it suddenly rebooted out of nowhere. Battery was charged about 90% so this could not be the issue. Since it is not really reproducible, it would be quite hard to fix it if it's really an OS related issue

**Comment by r3g-5z** [comment]
Nothing really indicates this is a GrapheneOS problem. Sounds like a hardware failure. No one else has reported a problem like this and all other Pixel 7 users are running the exact same image as you with verified boot.
