### ISSUE TITLE
Feature request: Automatically wipe clipboard

### ISSUE THREAD

**Issue by JoonasC** [GrapheneOS/os-issue-tracker#2011]
It would be nice to have a feature which automatically wipes the clipboard if nothing has been copied/pasted from/to it for a while. This would lessen the likelihood of malicious applications reading sensitive data from the clipboard.

**Comment by thestinger** [comment]
Android does have this as a standard feature already (1 hour).

**Comment by JoonasC** [comment]
Ok, in that case could the timeout be made configurable?

**Comment by thestinger** [comment]
Yes, it could be, but can you file a new feature request about that?
