### ISSUE TITLE
Wi-Fi fails to turn back on automatically when in range of known networks

### ISSUE THREAD

**Issue by jeames00** [GrapheneOS/os-issue-tracker#2016]
Graphene OS does not automatically turn on Wi-Fi when back in range of either of the two WPA-2 Personal networks that I often use (at different geographical locations). Wi-Fi needs to be turned back on manually, the phone will then automatically reconnect to the known network.

Network Type: Wi-Fi 5
Network Frequency: 5 GHz
Graphene OS build: TQ1A.230205.002.2023030400
Device: Pixel 5

Wi-Fi scanning is on.

**Comment by r3g-5z** [comment]
Please try latest beta and see if this is still an issue.

**Comment by jeames00** [comment]
I switched to the beta release channel, restarted phone the next day, update installed... but unfortunately the issue persists.

Build number: TQ2A.230305.008.C1.2023031300

**Comment by Max-Q** [comment]
This Bug report is likely relevant: https://github.com/GrapheneOS/os-issue-tracker/issues/1341

**Comment by thestinger** [comment]
Known limitation of not having a network-based location service in the OS.
