### ISSUE TITLE
migrate whatsapp data to grapheneOS

### ISSUE THREAD

**Issue by asheetal** [GrapheneOS/os-issue-tracker#2018]
I am trying to migrate from a Samsung phone to pixel 7 pro. While reinstalling most apps did not pose any major problem. Now I am in a confusion how to migrate my whatsapp (the regular + business) along with the message history. How do I instruct grapheneOS to download the backup from Google cloud? Currently I get a blank popup screen that leads to "create a new google account". Is there is a tutorial anywhere how to migrate whatsapp along with the data?

**Comment by YousifYaldo** [comment]
> I am trying to migrate from a Samsung phone to pixel 7 pro. While reinstalling most apps did not pose any major problem. Now I am in a confusion how to migrate my whatsapp (the regular + business) along with the message history. How do I instruct grapheneOS to download the backup from Google cloud? Currently I get a blank popup screen that leads to "create a new google account". Is there is a tutorial anywhere how to migrate whatsapp along with the data?

I did that by copying the local backup of Whatsapp from my old phone to the new one. You can do that using a file explorer by going to internal memory>Android>media>com.whatsapp, then copy the Whatsapp folder and transfer to the new phone. Make sure you have a fresh install of Whatsapp and don't open it before copying the files over. I hope this helps.
