### ISSUE TITLE
Feature request: Button shortcuts for more functions like toggle flashlight

### ISSUE THREAD

**Issue by Abductcows** [GrapheneOS/os-issue-tracker#2019]
My old MIUI phone had more functions for button combinations like double tap power button. I set it to toggle flashlight and it was really useful for situations like when the lights time out in my apartment building.

From what I understand there is only an option to set/unset double power button to camera.

**Comment by thestinger** [comment]
Double tap power opens camera as a standard Android feature. We don't plan to make this configurable or to bind something else to flashlight. It's already quick to use the flashlight via quick tile. You can see the screen in the dark.
