### ISSUE TITLE
Expose existing support for using fingerprint scanner for apps only in Settings

### ISSUE THREAD

**Issue by stfnhh** [GrapheneOS/os-issue-tracker#202]
Fingerprints aren't secure and can easily be bypassed.  Would it be possible like in iOS to disable the fingerprint scanner for unlock but still allow it to be used for apps?

**Comment by stfnhh** [comment]
Closing #160 includes this request.

**Comment by thestinger** [comment]
#160 isn't the right approach to implementing these features.

**Comment by thestinger** [comment]
This is already implemented by the OS and a toggle could be exposed. It's a UI feature.
