### ISSUE TITLE
Audible app auto starting with bluetooth.

### ISSUE THREAD

**Issue by W1zardK1ng** [GrapheneOS/os-issue-tracker#2022]
After recent updates started noticing the audible app is showing the media control in notification bar and on the lock screen every time i turn on the Bluetooth, even if i didn't connect to any device.
I need to force stop the app to get rid of it but it shows up again if i turn on the Bluetooth, anyone having this behavior or is there any workaround to stop getting these media playback control.

**Comment by thestinger** [comment]
This sounds like the app choosing to do this.
