### ISSUE TITLE
[Feature Request] Change clock UI from blue to black

### ISSUE THREAD

**Issue by russianbot91** [GrapheneOS/os-issue-tracker#2027]
It's odd that the included clock app has a blue UI when the rest of GrapheneOS is Black & White. It gives off an unpolished vibe. Both CalyxOS and LineageOS's versions of the AOSP Clock match the rest of the system UI.

**Comment by r3g-5z** [comment]
No plans to modify AOSP DeskClock beyond minimal critical changes until the codebase for it is updated to Android 13 which is low priority. Currently it's on Android 11 due to upstream regressions. Consider using a different clock app.
