### ISSUE TITLE
[Feature Request] Caffeine Mode QuickTile

### ISSUE THREAD

**Issue by russianbot91** [GrapheneOS/os-issue-tracker#2028]
Include the Caffeine QuickTile that is included in CalyxOS and LineageOS. It should only be a few kB in size.

**Comment by r3g-5z** [comment]
Not adding stuff like this, not in scope for this project. An open feature request for a user-facing way to keep the screen temporarily awake is open at https://github.com/GrapheneOS/os-issue-tracker/issues/1007 already.
