### ISSUE TITLE
[Feature Request] Torch Button Gesture

### ISSUE THREAD

**Issue by russianbot91** [GrapheneOS/os-issue-tracker#2029]
Include the option to toggle the torch by long holding the power button as is included with CalyxOS and LineageOS.

GrapheneOS doesn't support root or Xposed in official builds which is a good thing for security, but if a user wants to re-add this feature they have to use a keymapper app that requires Accessibility access which is a potential security vulnerability. Also, without root remapping keys doesn't work when the screen is off or locked.

**Comment by r3g-5z** [comment]
Duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/2019 and https://github.com/GrapheneOS/os-issue-tracker/issues/1301

Please search before creating issues.

Far more better uses for the power button than a flashlight.

**Comment by thestinger** [comment]
@russianbot91 Please look for duplicates first and don't try to push us into doing stuff by bringing up CalyxOS and LineageOS.
