### ISSUE TITLE
[Feature Request] Option to toggle Bluetooth Auto-Connection per Paired Device

### ISSUE THREAD

**Issue by russianbot91** [GrapheneOS/os-issue-tracker#2030]
Right now when Bluetooth is enabled your phone will auto-connects to any paired device in range which is undesirable and a potential security risk. Also, if you are connected to an audio device and another device becomes available (such as getting in your car) it will also connect and switch the audio output with out the users consent. This is a pretty big privacy risk.

There should be an option to disable this on a per device basis or at least system wide.

**Comment by r3g-5z** [comment]
Not really useful when Bluetooth timeout already exists, and doesn't matter if auto pair is disabled if you have Bluetooth scanning enabled at the same time as well.

Set Bluetooth timeout to a low interval.

**Comment by russianbot91** [comment]
> Not really useful when Bluetooth timeout already exists, and doesn't matter if auto pair is disabled if you have Bluetooth scanning enabled at the same time as well.
> 
> Set Bluetooth timeout to a low interval.

I already have the timeout set to 2 minutes.

The issue is if you're using bluetooth headphones the audio output will automatically switch to a new device like a speaker or a car stereo the moment it becomes available. If you live with someone else or share a car with a family member issue this becomes a daily issue. You'll be listening to something and all of a sudden it cuts off and someone 200 ft away is listening to what you were.

**Comment by onlycparra** [comment]
I also find Bluetooth auto-connect to be an annoyance.

I turn on my headphones to connect to my laptop, and zap! it auto-connects to my phone.

I turn on my car, and the phone auto-connects to it.

A simple "auto-connect" toggle in the paired device details would be awesome

**Comment by jerlam06** [comment]
How is this feature request going? Auto-connect is highly annoying, there should be an option per device to toggle auto-connect, please.

**Comment by JTJ8** [comment]
Any progress on this? These days with all the surveillance and digital fingerprinting, this is more critical than ever... IMHO

And thank you in advance!

**Comment by Auztiin** [comment]
Also interested
