### ISSUE TITLE
Misaligned background behind the search bar

### ISSUE THREAD

**Issue by flexagoon** [GrapheneOS/os-issue-tracker#2032]
After an update, the search bar in the launcher has a misaligned background

![IMG_20230316_083605](https://user-images.githubusercontent.com/66178592/225524579-9267d653-d979-4045-bcd0-2092825a2475.jpg)

**Comment by lokesh-krishna** [comment]
Just curious. The duplicate was closed as "not planned" while this has been left open. Does this mean fixing this is under consideration even though it's an upstream issue?

**Comment by flexagoon** [comment]
@lokesh-krishna all duplicates are closed as "not planned"

**Comment by thestinger** [comment]
Issues can either be closed as not planned or completed.
![github](https://user-images.githubusercontent.com/1505226/226138752-5aa10bd4-f638-4fbd-8414-5a701b2e7bd1.png)

**Comment by lokesh-krishna** [comment]
Thanks! I thought not planned was only reserved for when the issue was deemed won't fix. Didn't know it also applied to duplicates.
