### ISSUE TITLE
stub implementation of the Google Play Services APIs

### ISSUE THREAD

**Issue by shortcak** [GrapheneOS/os-issue-tracker#204]
Adapted from @thestinger on #grapheneos

GrapheneOS does not include Google Play Services. Some apps will break because of the lack of Play Services.

Ideally, there should be a per-app opt-in toggle to turn on fake stub Google Play Services as an app compatibility layer. This stub implementation would say that the Google servers are down via return codes / exceptions. It shouldn't really implement anything for real since we just want stub APIs and not implementations of those Google services. It can be scoped to _only_ allow faking the Google Play Services signature and only by the specific stub implementation, not as a generally available permission. It shouldn't be possible to spoof signatures other than the specific Play Services one.

Since this would be targeted at specific apps to implement (partial) compatibility with them, a per-app toggle is important. If you just stick something that looks like Play Services, apps aren't going to use their non-Play Services code. The toggle should be hidden from most apps, and it should be off by default for every app because it's going to break some apps by making them use Play Services code.

For example, Signal detects whether the device has Play Services installed. Notifications for Signal are handled using GCM/FCM if Play Services is installed, and handled using a websocket connection to the Signal servers if Play Services is not installed. So if Signal is toggled to use the stub Play Services, you aren't going to get Signal notifications anymore.

**Comment by thestinger** [comment]
For some reason I thought I already had an issue about this. It must have been on https://github.com/AndroidHardeningArchive/legacy_bugtracker/issues.

**Comment by thestinger** [comment]
Thanks for filing it with some of what I said about it on #grapheneos. Could edit in some more of what I said if you want to provide more context for people including about signature spoofing, etc.

**Comment by shortcak** [comment]
Found the old issue at https://github.com/AndroidHardeningArchive/legacy_bugtracker/issues/649, I'll edit in some parts from there

**Comment by LumenReaper** [comment]
Hi, 
I'm new to the GrapheneOS project and have been using the OS for a week and I'm very pleased.

I'm sure I don't have the knowledge to work on the toggle or the signature spoofing, but I'd like to offer to help with faking the Google Apis.

Already faked the minimum Api to keep the Google Camera app from crashing, at the end it was just a single class. I made it available in a repository anyway. If you are interested here is the [link](https://github.com/LumenReaper/Gcam-Services-Provider).

Is it true if I assume that there is nothing for me to do until someone with more knowledge implements the toggle? Also, I assume that this ticket has a very low priority as it does not improve the security of the OS, but only improves the compatibility to proprietary apps.

Thanks for reading anyway

**Comment by renlord** [comment]
@LumenReaper what really? Is it just that simple?

**Comment by LumenReaper** [comment]
@renlord What do you mean exactly? My Google Camera "Hack" or the faking of the Google Api in general?

Regarding the camera fake, yes, the solution is that simple. I just grabbed the exception from the log and searched the microg code with keywords from the exception. Found a promising class and took the idea into an separate app.

But there are some strange behaviors, e.g. the app does not always switch between front and rear camera on the first click. But until now I can live with it. Not sure what it is, I haven't invested more time yet.

To refocus on this issue: I haven't noticed any side effects from using my fake yet. Maybe we can consider integrating **carefully selected** apis before the toggle is implemented, where the chance of other apps crashing or apps not using their fallback code is low.

**Comment by beerisgood** [comment]
Maybe this helps?:

The [corona-contact-tracing-germany](https://codeberg.org/corona-contact-tracing-germany) team use only the relevant microg parts which are added as a library: https://codeberg.org/corona-contact-tracing-germany/cwa-android/src/commit/4edcbec69c69ce8d6863d85dfcf811076d9f83b8/Corona-Warn-App/build.gradle#L377-L379

```
implementation 'org.microg.gms:play-services-nearby:0.2.14.204215'
implementation 'org.microg.gms:play-services-nearby-core-ui:0.2.14.204215'
```

The libraries are downloaded from [mavenCentral.](https://mvnrepository.com/artifact/org.microg.gms)

**Comment by thestinger** [comment]
It's not really relevant.

**Comment by thestinger** [comment]
We're going to consider this again in the future. The situation has changed due to the sandboxed Play services compatibility layer. Our thinking about this would need to be changed. It doesn't really make sense to replace only the server-side portion of Play services while still using the client-side portion since a lot of that can still connect to the services and use them including the Ads library. I think our planned improvements to profiles and scoped app feature (essentially a form of profile) are the real solution.
