### ISSUE TITLE
Auto reboot feature does not seem to be working. 

### ISSUE THREAD

**Issue by Klejdi-Bozho** [GrapheneOS/os-issue-tracker#2045]
I have set the auto reboot feature to 4 hours,  but when I wake up from sleep,  I notice the phone has not rebooted. 

Device: Google Pixel 6 Pro
OS: 13 (T2B3.230109.009)

**Comment by thestinger** [comment]
How are you determining if it rebooted?

**Comment by thestinger** [comment]
Are you using secondary users?

**Comment by thestinger** [comment]
We're unable to replicate an issue with the feature.

**Comment by thestinger** [comment]
You need to provide more details. How are you checking if it's in the first unlock state?

**Comment by thestinger** [comment]
No one has been able to replicate this.
