### ISSUE TITLE
[Enhancement] Re-add VoLTE and other baseband related toggles

### ISSUE THREAD

**Issue by russianbot91** [GrapheneOS/os-issue-tracker#2046]
With the the recently announced Exynos baseband vulnerabilities, Google recommend users to disable VoLTE (a toggle switch they removed from Android).

This and any other baseband related switches should be reintroduced as new vulnerabilities will be found in the future that may take awhile to patch (if ever).

I appreciate that GrapheneOS has a LTE only mode and allows the user to modify APN settings for carriers that block it for this very reason.

**Comment by r3g-5z** [comment]
This is being tracked in https://github.com/GrapheneOS/os-issue-tracker/issues/956 as CarrierConfig overrides to override things like VoLTE, VoWi-Fi, Video carrier calling (VT), etc

**Comment by thestinger** [comment]
VoLTE toggle still exists. It wasn't removed.
