### ISSUE TITLE
Storage Scopes individual file applies to whole folder

### ISSUE THREAD

**Issue by GitGetGott** [GrapheneOS/os-issue-tracker#2051]
Using TQ2A.230305.008.E1.2023032000 on a Pixel 6. While attempting to apply a storage scope to an application, I only gave the application access to a single file: Main\ storage/Pictures/Screenshots/file.png, then when selecting the file that the application had access to I noticed it had access to the entire parent directory, that is Main\ storage/Pictures/Screenshots. And this is inside of the application, not what it has access to via the Android file picker.

**Comment by thestinger** [comment]
Please show screenshots of the Storage Scopes configuration and what you're seeing in the application. Storage Scopes also isn't the only way to grant apps access to files. You could have also granted it via SAF previously.

**Comment by GitGetGott** [comment]
Its not allowing me to upload the screenshots. I assume they're too large. Please bare with me while I find a file host or compress them or something.

**Comment by GitGetGott** [comment]
[Here](https://www.reddit.com/user/Spajhet/comments/11yad0q/grapheneos_storage_scopes_issue/) you go. With all the important stuff redacted.

**Comment by thestinger** [comment]
You haven't previously given it access to those files via SAF?

**Comment by GitGetGott** [comment]
After doing some more testing it appears you may have been correct about it being due to the SAF

**Comment by muhomorr** [comment]
Any app can create new files and access them afterwards, without any storage permissions. Storage Scopes feature doesn't change this. See https://grapheneos.org/usage#storage-access
