### ISSUE TITLE
Mobile payment does not work after the latest update

### ISSUE THREAD

**Issue by snp42** [GrapheneOS/os-issue-tracker#2054]
After the latest update to version TQ2A.230305.008.E1.2023032000 on the Pixel 6a, the banking app com.s_payment.mobiles_bezahlen causes an error and the payment process is aborted.
Before the update, there were no problems with the app and paying via NFC.

**Comment by treequell** [comment]
Have you had a look at the banking report for this app?
https://github.com/PrivSec-dev/banking-apps-compat-report/issues/160

This is part of a community maintained list of banking apps:
https://privsec.dev/posts/android/banking-applications-compatibility-with-grapheneos/

It gives some tips on ways to get the app working. If you can't get it working I suggest you file an update to the report I linked above.

I'd also recommend reading this information from the official documentation:
https://grapheneos.org/usage#banking-apps

**Comment by snp42** [comment]
I added an update to the report cause the app doesn’t work any more.

**Comment by treequell** [comment]
Thanks!

**Comment by thestinger** [comment]
Can potentially be fixed but the issue may just be your configuration. Someone else will need to try the app. No reason to think that it's an OS issue.
