### ISSUE TITLE
TZ Database Update

### ISSUE THREAD

**Issue by sijad** [GrapheneOS/os-issue-tracker#2058]
it seems are some missing TZ Database updates.
My country no longer observes DST but time on my phone has been changed.

TZ change logs: https://data.iana.org/time-zones/tzdb/NEWS
more info: https://en.wikipedia.org/wiki/Tz_database

**Comment by sijad** [comment]
not that.

timezone GMT 3:30+ is missing ATM: https://en.wikipedia.org/wiki/UTC%2B03:30

**Comment by thestinger** [comment]
I'm unsure why Iran Standard Time is shown as +4:30 instead of +3:30 because tzdata appears to be up-to-date until March 2023 changes.

**Comment by thestinger** [comment]
Despite 2022g being included in the AOSP source tree, the OS ends up using 2022a. We'll need to figure out why that happens and how to fix it.

**Comment by thestinger** [comment]
Implemented for the next release.

**Comment by Kop3sh** [comment]
I have a similar problem...
My clock doesn't get updated to observe DST although it has been enforced for about 1 week now in Egypt (information can be found in the linked tz change log in the beginning of the thread)
And consequently I can't use 2FA apps

**Comment by thestinger** [comment]
Those kinds of time checks are based on the actual stored time, not the displayed local time. It can't fail due to the offset being wrong for your time zone unless you have your time set incorrectly. The timezone database was also already updated and is being updated regularly now.

**Comment by Kop3sh** [comment]
I believe I've set mine correctly to Egypt's time zone
What do you propose for a solution?
I've tried to reboot my device, and recheck the time settings from manual to automatic, enabling and disabling GPS but doesn't seem to work

**Comment by thestinger** [comment]
Time-based checks like TOTP are not based on time zone.

**Comment by Kop3sh** [comment]
From my humble understanding, it depends on the client's clock being in sync, and if not (like in my case) it can't be used for authentication (provide an expired OTP). I totally agree that TOTP works across different timezones.
But in my case I tried to manually update my clock settings, to account for DST; basically adding 1 hr (where the problem arised)

Please let me know if there is something that I'm getting wrong...

**Comment by thestinger** [comment]
> But in my case I tried to manually update my clock settings, to account for DST; basically adding 1 hr (where the problem arised)

This is the issue. Instead, set a time zone matching the expected offset and leave the time on automatic.

**Comment by Kop3sh** [comment]
> > But in my case I tried to manually update my clock settings, to account for DST; basically adding 1 hr (where the problem arised)
> 
> This is the issue. Instead, set a time zone matching the expected offset and leave the time on automatic.

 Yep, this fixes things up
