### ISSUE TITLE
Dead man switch

### ISSUE THREAD

**Issue by nutts0** [GrapheneOS/os-issue-tracker#206]
Delete device data if password is not provided in the set timeframe.

**Comment by beerisgood** [comment]
This would create a high false positive rate

**Comment by nutts0** [comment]
@beerisgood don't have to use it if you don't know what you do.

**Comment by willemkuijpers** [comment]
This option will be ideal for privacy/criminal lawyers, let's hope it's gets soon implemented.

**Comment by nutts0** [comment]
Seems the Titan m has a counter itself. Not sure if the it could be programmed to do the the key eviction. This would be a killer feature for sure. No one has this. If only the Titan could perform this action to delete the key without the os would be nice

**Comment by 1989gironimo** [comment]
If torture/death is part of your threat analysis, then you shouldn't rely on technical measures like this.

**Comment by nutts0** [comment]
I think the majority doesn't understand what this is actually useful for. It is definitely helpful if one can factory reset the device without having access to it or being able to reach it over the network. If the Titan M could directly be programmed to delete the keys this would be a very very good feature.

**Comment by juestr** [comment]
Just the presence of the feature provides plausibly deniability whether you use it or not, if the "deleted" state cannot be detected.

**Comment by nutts0** [comment]
The phone basically does a factory reset which deletes the encryption keys.

**Comment by churchthecat** [comment]
would also be good thing to have a factory reset done on X number of wrong attempts to unlock.

**Comment by thestinger** [comment]
@churchthecat https://github.com/GrapheneOS/os_issue_tracker/issues/85 is already filed for that. It's supported already but just not exposed via the Settings app and requires a device manager to enable it.

**Comment by thestinger** [comment]
There's now an optional auto-reboot feature which I prefer over this. An attacker could turn off the device to bypass a wipe feature anyway.

**Comment by thestinger** [comment]
It'd be possible for Titan M to actually force wiping the keys as soon as it gets power again but if it's a sophisticated attacker aiming to compromise the security element, it wouldn't really deter them.
