### ISSUE TITLE
Multi User app installation via settings not possible after update to TQ2A.230305.008.2023032600

### ISSUE THREAD

**Issue by olerichter** [GrapheneOS/os-issue-tracker#2060]
Dear Graphene Developers,

Bug description:

To install apps in my compartmentalized user accounts I log in to the Owner Profile -> Settings -> System -> Multi User -> <user account> -> install available apps.
since the last update this list is blank and I cant add new applications to my users.

User story:

On my phone I have different users:
- Owner (does nothing except manage the phone)
- Users that I use, and are compartmentalized for different things like Work, Personal, Travel (prohibited from installing applications)
- Installation Users (only installs and updates applications, does not exec them, different ones for different sources)

why:
 - The google play store install user has full google services activated for installing and updating and i can end the session after the update stopping all related services, while I can install the applications on users that do not have google play services activated as long as the apps function ok without (most of my apps).
 - I can prevent accidental/unwanted installations from my daily user accounts as they don't have the system rights to update/install apps and as a bonus maybe limit the attack vector if one user account is compromised.
 - I can install/update applications into vault users that have some form of restricted internet access.

thanks for your effort and time!

**Comment by Juliaria08** [comment]
> "Install available apps" is only possible for apps installed in Owner, not other secondary profiles. It was briefly possible to install apps from other secondary profiles to others using this feature, but it was reverted because it requires more thought put into it to make it safe to use and not enable and social engineering vectors in cases where multiple people are using the same phone.
> 
> https://grapheneos.org/releases#2023020200
> 
> > drop our extension to the install available apps feature (which is still available, without this extension) making it work for apps not installed in Owner since this is risky in a situation where there are actually separate people using secondary users and while we want to provide this feature, we'd need to come up with a way to address this to add it back

I don't need this feature but I think I have a idea which maybe could be implemented but I think it'd be a lot of effort.
My idea is having the Owner user be able to install apps from other users, adding a extra menu option, to the Install apps activity to let you choose a user, (probably it'll need to ask you to authenticate as that user as I think those users are encrypted with other keys right?), and when you choose that user it'll list the apps of that user, and then you'd be able to complete the process as usual. This also gave me the idea of adding another option in that menu to let the owner install apps even when the not allowed to install apps checkbox is ticked, so you'd be sure that no app is able to somehow install another app but still able to update/install apps.
