### ISSUE TITLE
Can't switch users when receiving a call

### ISSUE THREAD

**Issue by franklinblanco** [GrapheneOS/os-issue-tracker#2062]
As the title says. While a call is ringing you cannot switch users. This wouldn't be problematic if it was only standard carrier calls. But for example, I only have whatsapp on my second user, and I notice that when I get called through whatsapp while on my first user I have to sit there and wait for the call to finish ringing, as I can't hit decline or hit the switch to second user button. The user button also greys out.

**Comment by thestinger** [comment]
Known AOSP limitation. Has been discussed on the tracker before. No current plans to change it.
