### ISSUE TITLE
Microphone and Camera Access Timeout

### ISSUE THREAD

**Issue by EdgeCon** [GrapheneOS/os-issue-tracker#2064]
Similar to the Bluetooth timeout function where if no active Bluetooth connection is in use, then Bluetooth turns itself off.

Now apply that function to the microphone and camera access features. When the microphone or camera is not being used for a set period of time, then it will turn off. 

I want to keep the microphone and camera access off as often as possible. But after I am done with a phone call or taking a quick pic of the cat, I forget to turn off the microphone and/or camera access until much later in the day. It would help increase privacy by having an user defined timeout period since it doesn't always need to be on and we can be forgetful.

**Comment by thestinger** [comment]
Only grant one-time access. You don't need to toggle them off globally. It's a worse way to do this.
