### ISSUE TITLE
No Wifi on Flight mode, sometimes no internet, very buggy

### ISSUE THREAD

**Issue by firefoxlover** [GrapheneOS/os-issue-tracker#2068]
I have a weird issue that I can't enable wifi when on Flight mode. I go to the internet settings and toggle the switch, but get "you are in airplane mode" and the switch doesnt move. But this is about Wifi, which should not be affected.

Also when using the "Internet button" I toggle wifi but it doesnt show anything.

Cell data is similar, I have to reboot and sometimes it works, often it doesnt. This of course only applies when airplane mode is off. I often have no connection nonetheless.

Some maybe related settings:
- LTE (if possible)
- No automatic Wifi on
- Auto Wifi off 10min
- No notification about public wifis
- no custom certificates
- Airplane mode on
- Data saver off
- VPN on, custom DNS server (no problem connecting to the internet)
- connectivity check GrapheneOS
- Attestation key GrapheneOS Proxy

developer options:

- reduced wifi search
- randomized mac
- mobile data not always on
- no limit for downloads

It may have a reason that I tried [this Android 11-12 hack](https://www.androidpolice.com/get-old-wifi-toggle-back-android-12/) to get seperate Wifi and Cell data toggles back with basically this command:

```
settings put global settings_provider_model false
settings put secure sysui_qs_tiles "wifi,cell,$(settings get secure sysui_qs_tiles)"
```

It doesnt work on Android 13, which is a pain. I know LineageOS 20 has it and its very useful for practical privacy. This combined toggle is a trick from Google to have you connected 24/7.

I am not sure if this is the cause, but would be happy if I could reset all related settings somehow. I already resetted the internet settings.

Also it seems after using that command I can't rearrange the quick tiles anymore, they stay how they are. This is a rather big issue.

**Comment by thestinger** [comment]
You need to remove the change you made with adb.
