### ISSUE TITLE
Problem opening an application

### ISSUE THREAD

**Issue by florian-sabonchi** [GrapheneOS/os-issue-tracker#2069]
Sometimes another application opens when you try to open an app via the app drawer using the search See Video

https://user-images.githubusercontent.com/54689374/229093234-ae3803b6-6cf9-429a-8711-3b08ea43ff45.mp4

**Comment by thestinger** [comment]
Known AOSP issue. Happens when quickly opening without giving it time to finish searching.

**Comment by florian-sabonchi** [comment]
> 

Okay, is there an workaround to fix it?

**Comment by thestinger** [comment]
Wait a fraction of a second longer for the search results to finish loading. It's a known AOSP launcher issue. There are previous issues filed.
