### ISSUE TITLE
Certain apps that require geocoding do not function properly

### ISSUE THREAD

**Issue by Micim987** [GrapheneOS/os-issue-tracker#2070]
I am unable to fully use the PioneerRx Delivery app with the latest stable version of GrapheneOS installed. PioneerRx uses a method called geocoding to load customer addresses onto a map and create a route. It also uses geocoding to give the store and customers a rough idea of where prescriptions are left when delivered.

Troubleshooting steps are difficult to reproduce because addresses are geocoded at collection and collection can only happen when connected to the stores network. So far I have tried downloading and install google play services and maps as well as with "Reroute location requests to to the OS" disabled although geocoding is not real time location request and more a "lookup this address and put a pin on the map" there is a location request done at time of collection but afterwards no location requests are done until a prescription is dropped off or deliveries are upload to the system at the store. 

If needed I can provide information and possibly logs if they exist as long as they do not violate HIPAA.

**Comment by thestinger** [comment]
See https://github.com/GrapheneOS/os-issue-tracker/issues/23.

If those apps use Play services for this functionality it should work via sandboxed Google Play.

**Comment by Micim987** [comment]
So just to confirm this issue is currently unfixed and probably won't be fixed in the future and there is currently no option to toggle default geocoding support. It does not work via sandboxed Google Play and seems to rely on something built into android but their (PioneerRx) dev team barely supports android and can't give me more specifics.

**Comment by thestinger** [comment]
Android Open Source Project doesn't have a geocoding implementation included. We need to implement one which includes choosing how to do that. Sending requests to a remote service is far from ideal, especially a third party service. It's a missing optional feature, not a bug, and I'm not sure where you get the idea that it won't be implemented. We have an official planned feature filed.
