### ISSUE TITLE
Bug in Color Correction Setting

### ISSUE THREAD

**Issue by Rgbaked** [GrapheneOS/os-issue-tracker#2072]
I have discovered a bug in the Color Correction setting on my Pixel 6a. The toggle for the correction does not work, and it stays on the previously selected correction. Even after rebooting my device, I am still stuck on the same color correction.

I tried to screen record the issue, but it doesn't show up in the recording.
I'm happy to provide any additional information that could help diagnose this issue.

**Comment by flawedworld** [comment]
https://github.com/GrapheneOS/os-issue-tracker/issues/1437
