### ISSUE TITLE
Automatic Time is incorrect for UTC-6 zones

### ISSUE THREAD

**Issue by Fre148** [GrapheneOS/os-issue-tracker#2075]
Good afternoon!

The Mexican Government has eliminated Summer Time (https://newsrnd.com/news/2022-10-26-mexico-eliminates-summer-time--what-are-the-reasons-and-when-does-the-new-law-come-into-force-.SkCfSHDNo.html), but https://time.grapheneos.org/generate_204 did the change and it is one hour past the real time.

At the moment of writing, the official and correct time is 5:00 PM, but GrapheneOS show 6:00 PM.

I think this needs to be fixed immediately, as thousands of people arrived to work late and in general it is a big inconvenience. If there is other temporary solution, please tell me which one :D

Thank you. Have a nice day!

**Comment by thestinger** [comment]
The issue name doesn't make sense because UTC-6 is a fixed offset, not a region. The timezone data has been updated for the next release already.
