### ISSUE TITLE
Full-system backup like Titanium Backup

### ISSUE THREAD

**Issue by gasull** [GrapheneOS/os-issue-tracker#2077]
Enhancement  proposal.

The backups should backup the whole system, including apps that opt out of backups, like it would work with Titanium Backup on a rooted phone.

Ideally, if my phone dies, I should be able to buy a new phone, restore the latest backup, and be ready to go, without having to install or configure anything else.  All the data, apps, and settings should be there already.

**Comment by dm17** [comment]
Is the inability to backup vanadium data like bookmarks an AOSP or GOS limitation?

Also:
https://discuss.grapheneos.org/d/3302-we-plan-on-replacing-seedvault-with-a-new-backup-implementation
"Not a priority" -> but this is kind of a blocker to migrate to new Pixel devices without a load of work, isn't it?

**Comment by thestinger** [comment]
> Is the inability to backup vanadium data like bookmarks an AOSP or GOS limitation?

It's a Chromium limitation we plan to address. They rely on having their Sync feature available.
