### ISSUE TITLE
Network connectivity fails upon switching networks (mobile/wifi) while connected with Tailscale VPN

### ISSUE THREAD

**Issue by cstromblad** [GrapheneOS/os-issue-tracker#2087]
I'm not entirely sure how to phrase this issue report. But the simple fact of it is that Tailscale (Wireguard P2P VPN) renders the network connectivity unusable when switching between different network types such as WiFi or Mobile networking.

Reconnecting to the VPN fixes the issue. This does work on a regular "standard" Android device, but not here. Not sure what information I can provide? Running the latest version of GrapheneOS on a Pixel 7 Pro.

**Comment by thestinger** [comment]
> This does work on a regular "standard" Android device, but not here.

On which device? Is it Android 13?

**Comment by cstromblad** [comment]
OnePlus 9 Pro (running Android 13) works just fine. I can switch between networks (WiFI or Mobile) without issues. But I need to dig deeper to make sure I can provide some useful troubleshooting, but my inexperience with mobile OS makes me anything but skilled in this :-)

**Comment by cstromblad** [comment]
Ok, this can probably be closed as an issue not related to Graphene. I tried doing the same thing (running Wireguard) with another provider, disconnecting from Wifi and checking network... and it worked. Therefore I must conclude that this is an issue with Tailscale not being able, for some reason, move across networks on Graphene.

This issue can be closed.

**Comment by patriiiiiiiiiick** [comment]
I don't understand why this was closed. I have some connectivity issues and I would say that the original description matches one of the behaviour I'm observing.

**Comment by thestinger** [comment]
It's almost certainly an app issue and not a GrapheneOS issue.

**Comment by patriiiiiiiiiick** [comment]
Damn, I'm blind! I had not seen I had changed repository. It's indeed either Tailscale or upstream. If you have interesting pointers, please shoot! And thanks for replying already!

**Comment by ParetoOptimalDev** [comment]
You can get around this bug if you disable the GrapheneOS network setting “block connections without VPN”.

Not sure about the privacy security/implications if any, but there's a workaround I just found:

https://forum.tailscale.com/t/how-to-access-public-internet-grapheneos/5305
