### ISSUE TITLE
It is possible to init with a user different than "root" by default?

### ISSUE THREAD

**Issue by M3cubo** [GrapheneOS/os-issue-tracker#2093]
Every time I start GrapheneOS, I log in as "root" only to log in as my "user" right after. Can I set the default login to start as "user" automatically? (even if it asks me for the root PIN beforehand, for security).

**Comment by thestinger** [comment]
It's not a root user. It's the Owner user. It has to be logged in first because a lot of system data is encrypted with a key protected by the Owner lock method. We can't realistically change this ourselves.

**Comment by M3cubo** [comment]
Is there a way to "Prompt" inmediatelly to select another user, every time the phone inits?
