### ISSUE TITLE
eSIM does not work anymore since 2023040400

### ISSUE THREAD

**Issue by stephan-rehfeld** [GrapheneOS/os-issue-tracker#2097]
Since the update to 2023040400, the eSIM in my Pixel 6a does not work anymore. The release notes say, that there were some changes regarding to the eSIM. I already opened a thread in the GrapheneOS BBS here: https://discuss.grapheneos.org/d/4334-esim-does-not-work-anymore-since-2023040400

The phone does have a multi SIM configuration. In the past, the phone askeed directly for the PIN of the physical SIM. Since update to 2023040400, the Phone does not detect any SIM directly after start up. Options about the SIMS are greyed out in the settings. After about 2 minutes, it detects the physical SIM and asks for the PIN.

The downloaded eSIM is in the list but is inactive. When I try to activate it, it states, that the carrier could not be disabled. I'm also not able to delete the eSIM from the phone. Enabling or disabling privileged eSIM mode, does not change the behavior. When I try to download a new eSIM, the eSIM tool states that the EID can not be determined.

I created a bug report on my phone. Where I could submit it?

**Comment by muhomorr** [comment]
> I created a bug report on my phone. Where I could submit it?

Send it to my Matrix: @muhomorr:matrix.org

**Comment by stephan-rehfeld** [comment]
Submittet via matrix

**Comment by thestinger** [comment]
Appears to be an upstream firmware issue. Very little we can do ourselves. The cause appears to be us updating the firmware which we have to do. There are reports of the same issue for stock Pixel OS. You'll need to try using the stock OS to wipe it. If the issue still occurs there, that will fully rule it out as caused by GrapheneOS.
