### ISSUE TITLE
Voice call while roaming doesn't work

### ISSUE THREAD

**Issue by Max-Q** [GrapheneOS/os-issue-tracker#2101]
Voice call (outgoing) doesn't "ring" and fails when roaming. Tested with two providers and Pixel 6 and 6a. Connection to cell network is ok. Sending SMS works. Build is TQ2A.230305.008.E1.2023040400.

**Comment by r3g-5z** [comment]
Does your carrier support VoLTE and/or VoWiFi?

**Comment by Max-Q** [comment]
> Does your carrier support VoLTE and/or VoWiFi?

I don't know, I have disabled both settings on both devices.

**Comment by Max-Q** [comment]
More info it works with a Pixel 4a with version TQ2A.230305.008.C1.2023040400

**Comment by Max-Q** [comment]
More info 2: I just tried roaming with another countries cellular provider (original Problem was Germany now tried with France) and the call worked.

**Comment by flawedworld** [comment]
Some carriers when roaming require VoLTE or may require you to use 3G for calls. It varies based on home carrier, home region, roaming carrier and roaming region. I don't think this is anything to do with us.

**Comment by euakll** [comment]
Same device, same issue. SMS works, outgoing Phone calls don't ring, no connection. Tried different carrier with different SIM settings (WiFi calling, LTE calling, 3G, 2G) no success. Is this a Germany only issue? Tried with O2 and Telekom.de
Build: TQ2A.230405.003.E1.2023041100
