### ISSUE TITLE
AptX HD codec not selectable on Pixel 7 Pro 

### ISSUE THREAD

**Issue by RAYs3T** [GrapheneOS/os-issue-tracker#2107]
Hardware: Pixel 7 Pro
OS: TQ2A.230405.003.E1.2023041100

When paired with senheiser Momentum True Wireless 3, you can't select aptX HD  / adaptive as codec.

This worked on the stock installation. Is the HD codec not part of graphene /AOSP? 

Any way to get this working? 
Is this intentional or just a bug?
Normal AptX sounds like a garbage can :)

**Comment by thestinger** [comment]
Pixel 7 Pro supports SBC, AAC, aptX, aptX HD and LDAC. aptX Adaptive is not supported. Your headphones don't appear to support aptX HD.

**Comment by thestinger** [comment]
GrapheneOS should support the same codecs as the stock Pixel OS.

**Comment by RAYs3T** [comment]
OK then something must be off. Will check in detail later as there is a clear difference when compared with the stock Rom of the Pixel 7 Pro on the same device.
