### ISSUE TITLE
No vibration if battery saver is enabled 

### ISSUE THREAD

**Issue by 24coding** [GrapheneOS/os-issue-tracker#2108]
Device: Pixel 6 Pro
OS: TQ2A.230405.003.E1.2023041100

- All non-system apps do not vibrate if the battery saver is enabled. 
- Ringtones / sounds ( not set to vibrate) work fine regardless of the battery saver. 

This is important because encrypted calls (e.g. Signal) can easily be missed.

**Comment by r3g-5z** [comment]
Not a bug, this is intended and works the same way not only on stock Pixel OS, but across many other Android OS's. Turning off vibration is apart of saving power. We're not going to change this.

**Comment by 24coding** [comment]
Alright, thanks for the quick reply.
