### ISSUE TITLE
flash-all.sh fix for non-sense logic redirect to /dev/null in https://github.com/GrapheneOS/platform_manifest/releases/tag/TQ2A.230405.003.2023041100

### ISSUE THREAD

**Issue by gyrusdentatus** [GrapheneOS/os-issue-tracker#2110]
I could not find the original file so could not create a PR
This check ` if ! command -v fastboot > /dev/null; then echo "err"; fi ` does not do anything other than flushing the potential stderr to the toilet and then it would crap out if the `fastboot` is not in the `PATH` anyway I am assuming. 

Here is a proposed check. Referencing 3 year old issue just in case. Also it gives less-technical user more details on how to add anything to `PATH`. People simply struggle with these things

 ```

 if ! command -v fastboot > /dev/null 2>&1; then
   echo "fastboot not found; please download the latest version at https://developer.     android.com/studio/releases/platform-tools.html and add it to the shell PATH."
   echo "\nFor example add this line to the end of your ~/.bash_profile:"
   echo 'export PATH="~/.local/android/platform-tools:$PATH"'
   exit 1
 fi
```

_Originally posted by @maximbaz in https://github.com/GrapheneOS/os-issue-tracker/issues/376#issuecomment-716240262_

**Comment by thestinger** [comment]
It gives a proper error message already.
