### ISSUE TITLE
Volte greyed out. 

### ISSUE THREAD

**Issue by Klejdi-Bozho** [GrapheneOS/os-issue-tracker#2114]
Hello, as I read in the 2023032600 changelog, carrier configuration for disabling voLTE and voWiFi is ignored, allowing the user to toggle it manually. While this works when there is no SIM card present in the device, the moment one is inserted, the options are greyed out again. Is this the intended way this is supposed to work? 

Device: Pixel 6 Pro
OS: 13 (TQ2A.230405.003.E1)
Carrier: Vodafone Albania

**Comment by flawedworld** [comment]
Google does not support VoLTE for your carrier officially then.

**Comment by r3g-5z** [comment]
We have not implemented CarrierConfig overrides yet. We simply removed the carrier configuration that prevents the user from controlling VoLTE and VoWiFi *when it's already provisioned*. We already have an open feature request to implement CarrierConfig overrides.
