### ISSUE TITLE
Pixel 5 Updater Incorrect Baseband Vers. (T-Mobile)

### ISSUE THREAD

**Issue by Mcflorple** [GrapheneOS/os-issue-tracker#2116]
Hello, for the past couple of months my phone has been almost unusable putting the "!" over the 5g signal. No amount of restarts/airplane mode or data toggle seemed to stick. Had a strange few days of cold shutdown as well. I know T-Mobile has been making a lot of changes in their network lately maybe having the updater blanket install the g7250-00247.1-230113-B-9488784 (Telus) baseband is the culprit? The official google images show g7250-00247.1-230211-B-9595156 (T-Mobile) as the baseband for my phone. I just changed out the battery today thinking maybe that was it and symptoms are still there so I am checking here. If I am in the wrong please let me know trying really hard to avoid flashing to stock to test
![baseband](https://user-images.githubusercontent.com/105847289/231949390-58890d2f-5af5-49c6-84a8-173899a704a3.jpg)
.

**Comment by thestinger** [comment]
We're using the generic release for this device, not the T-Mobile one. It's highly unlikely that it has anything to do with your issue because as you said it has been happening for months. You should start by resetting your network settings to provision the mobile connection again.

**Comment by thestinger** [comment]
If this is not fixed by resetting network connections, the issue can be reopened.

**Comment by Mcflorple** [comment]
That unfortunately did not help. I noticed the T-Mobile specific releases started appearing after android 13 but yeah if you've been using generic this whole time that's interesting. I'm gonna go get a new sim (highly doubt it's that) then I'll backup the important stuff, revert to stock and see if it does it on stock then let you know?

**Comment by Mcflorple** [comment]
Flashed to stock firmware problem still seems to not be fully gone so yeah, think I just need a new phone.
