### ISSUE TITLE
Bug Report: Call recording quality significantly muffled and low on other party's side

### ISSUE THREAD

**Issue by BogDrakonov** [GrapheneOS/os-issue-tracker#2118]
Device Config
--------------
Phone: Pixel 6a (Unlocked)
Carrier: Google Fi
SIM: eSIM
Google Play Sandbox: Yes
GrapheneOS: [bluejay-factory-2023041100.zip](https://releases.grapheneos.org/bluejay-factory-2023041100.zip)

Steps To Reproduce
--------------------
1. Initiate or receive a phone call where the call recorder button appears
2. Begin recording the call
3. Listen to the recorded call

Expected Behavior
-------------------
1. Call quality of your side of the conversation is extremely high quality due to mic level recording.
2. Call quality of remote party's side of the conversation is roughly similar in quality to what you heard over the phone during the call

Observed Issue
----------------
1. Call quality of your side of the conversation is extremely high quality due to mic level recording.
2. Call quality of remote party's side of the conversation is roughly 40-65% lower in volume than the original phone call.
3. Call quality of remote party's side of the conversation is significantly muffled. This coupled with the low volume makes it very difficult to listen to the recorded calls in any useful way.

Device Logs
------------
If instructions are provided I can provide them.

**Comment by thestinger** [comment]
Not enough information provided. You need to try the options in Call recording for audio output format and audio source.

**Comment by BogDrakonov** [comment]
@thestinger Why was this closed? It's still a bug and I could provide more information now that you've asked me to test another method.

**Comment by BogDrakonov** [comment]
Oh, I see. That makes more sense. I guess I'll report the issue to AOSP.

Thanks

**Comment by thestinger** [comment]
Did you try the 2 options in Dialer's Call Recording settings?

**Comment by BogDrakonov** [comment]
I believe so. I'm testing with the factory image now along with the [call recorder app](https://callrecorder.skvalex.com/get) I've used for years. Seeing similar issues in quality so it very well may be an AOSP issue on the Pixel 6a.

**Comment by r3g-5z** [comment]
If you're using other call recording apps and see the issue persist then the same behaviour would occur on other OS's that use Android's standard MediaRecorder APIs. This would be an upstream issue.

**Comment by BogDrakonov** [comment]
> If you're using other call recording apps and see the issue persist then the same behaviour would occur on other OS's that use Android's standard MediaRecorder APIs. This would be an upstream issue.

That's what I'm hoping to find out via testing. I will report back here so that anyone else coming across this can send a bug report to the correct place.

**Comment by PaulosV** [comment]
@BogDrakonov by any chance, have you managed to file the report? I'm having the same issue with Pixel 7 and I cannot find the issue yet in the tracker, and I'm also struggling to put it in the correct category.

**Comment by BogDrakonov** [comment]
> @BogDrakonov by any chance, have you managed to file the report? I'm having the same issue with Pixel 7 and I cannot find the issue yet in the tracker, and I'm also struggling to put it in the correct category.

I haven't had time yet since I'm currently running a rooted stock ROM with Skvalex's call recorded for testing.

**Comment by PaulosV** [comment]
> > @BogDrakonov by any chance, have you managed to file the report? I'm having the same issue with Pixel 7 and I cannot find the issue yet in the tracker, and I'm also struggling to put it in the correct category.
> 
> I haven't had time yet since I'm currently running a rooted stock ROM with Skvalex's call recorder for testing.

No worries, I was just curious. 
Maybe you'll confirm my observations then - I've discovered that the issue is much worse when the call is on the earphone, as ooposed to the speaker. Unfortunately on stock Pixel I did not have the recording capability and I did not want to root it.
