### ISSUE TITLE
Contacts app saves to device by default

### ISSUE THREAD

**Issue by zzyzx-dc** [GrapheneOS/os-issue-tracker#2122]
Hi, I love using GrapheneOS but the default AOSP Contacts app bundled with Graphene will only save new contacts to device. This is vulnerable to device deletions or system resets. Additionally, many people use DAVx5 to back up their contacts to Nextcloud, or perhaps they're even backing up to their Google account or other cloud services - however, these backups only pull from their respective "accounts" on the phone, and do not back up device-only contacts.

**Comment by thestinger** [comment]
Those sync apps can certainly back up device contacts.

**Comment by zzyzx-dc** [comment]
@thestinger They do not, i.e. DAVx5 will only back up the WebDAV account. Within the Contacts app you can see all contacts-capable accounts in the menu bar; the sync apps associated with those accounts will only back up their own contacts (can they access another account's contacts? how would they keep them distinct within their backup?).
