### ISSUE TITLE
Microsoft Excel app consistently loses "network" permission, despite "pause activity if unused" is unchecked

### ISSUE THREAD

**Issue by zzyzx-dc** [GrapheneOS/os-issue-tracker#2123]
The Excel app loses the network connectivity permission every 24 hours or so, or perhaps after every phone reboot. The feature to pause inactivity is turned off, and other permissions such as "notifications" remain granted. 

This is not a normal behavior on Graphene with other apps that I have noticed, so I'm wondering if it's something to do with the app itself. Additionally, other Microsoft apps do not lose network permission.

Thanks!

**Comment by thestinger** [comment]
Not able to replicate.

**Comment by thestinger** [comment]
Not able to replicate. Will be closed without more information.

**Comment by zzyzx-dc** [comment]
This is occurring on a 6a; I had to grant it again this morning (no reboot). I happen to be upgrading to a Pixel 7 next week, and can report back whether it does or does not occur there if you want. I am not sure how to furnish logs of what is occurring. If it doesn't occur on the 7 I will conclude it's just a fluke. Thanks.

**Comment by thestinger** [comment]
Uninstall and reinstall the app.

**Comment by thestinger** [comment]
Likely an upstream permission / package manager bug. Best option is reinstalling the app. If you have a device manager, that could be the issue.

**Comment by thestinger** [comment]
Can reopen if it persists after reinstalling the app.
