### ISSUE TITLE
App icons go in front of the search bar padding

### ISSUE THREAD

**Issue by flexagoon** [GrapheneOS/os-issue-tracker#2124]
https://github.com/GrapheneOS/platform_packages_apps_Launcher3/pull/21 introduced a padding below the search bar in the app list. However, if you scroll the list, you can see that this padding is located below app icons and titles, which should not be the case.

![Screenshot_20230417-134046~2](https://user-images.githubusercontent.com/66178592/232461863-de21d75a-98ef-4ea2-9463-94c04fdb3510.png)

**Comment by r3g-5z** [comment]
Resolved in the next release
