### ISSUE TITLE
Reenable multiple VPN connections in one profile

### ISSUE THREAD

**Issue by RhizomaticNomad** [GrapheneOS/os-issue-tracker#2129]
Since an update around 5 or 6 weeks ago it's not possible anymore to have multiple VPN connections, which before worked flawlessly.
Nowadays, as soon as one VPN gets connected, the other prior one gets disconnected, which makes several setups impossible:
Tor-enable some Apps (which are missing the proxy setting) via Orbot VPN Mode and configured as Always-on VPN to prevent access by the torified Apps without Tor VPN. But to have the ability to connect to an OpenVPN instance at the same time, to access resources behind the VPN (home/work). 
Similar setup without Orbot, but OpenVPN & Wireguard, in which case is not anonymity but accessibility is the goal: Access a home/work network via OpenVPN and make, at the same time, another resource behind a Wireguarded network accessible.

**Comment by thestinger** [comment]
It was never possible to have multiple enabled VPNs at the same time in the same profile. You need to put them in separate profiles. Using per-app VPN configuration as opposed to dedicated profiles for apps you want using a VPN vs. don't want using a VPN will also be prone to leaks from app communication which is only possible within profiles.

**Comment by RhizomaticNomad** [comment]
> 

As I mentioned in the OP, I assume there might be leaks due to this setup, but it's not meant to be bulletproof against observation of the devices traffic but to be able to access different resources. And this broke. Or was working by mistake/error in VPN implementation before 12th of March, but definitely worked.
