### ISSUE TITLE
Developer Setting Not Crossing Profiles

### ISSUE THREAD

**Issue by seniorm0ment** [GrapheneOS/os-issue-tracker#2134]
Developer options not available to select on different profiles.
Assuming it follows the main profile's developer settings.. However "Smallest Width" setting is manually set on my device and it does not replicate the setting across profiles. It only changes on the primary profile.

Pixel 6 Pro, latest GrapheneOS release

**Comment by thestinger** [comment]
That's working as intended. Developer options are for development.

**Comment by Orisphera** [comment]
I think this should be changed as a workaround for an issue in AOSP: the option to show taps is not where it should be
