### ISSUE TITLE
Charging Message on Lock Screen long after Charging Terminated

### ISSUE THREAD

**Issue by nick-perry14** [GrapheneOS/os-issue-tracker#2138]
![Screenshot_20230419-092755](https://user-images.githubusercontent.com/6935777/233090570-3397ec16-2919-4e3e-9083-c84c495a2d4c.png)

Sometimes when I stop charging, the message on the bottom of the screen remains even long after charging is done/terminated.  In the screenshot, see the message and the battery percentage do not match.  The battery is discharging and the message still exists.

**Comment by andrew-drogalis** [comment]
Nick,

I was about to post the same issue. This has been a problem for sometime now.

I have a similar screenshot.

![Screenshot_20230621-153344](https://github.com/GrapheneOS/os-issue-tracker/assets/108765079/27b5e2d6-04e2-454e-bdcd-21c4209a0f54)

**Comment by andrew-drogalis** [comment]
Is this resolved? I believe the error is resolved for me. If true for everyone else, I think OP can close the issue.
