### ISSUE TITLE
No option for storage scopes on some applications

### ISSUE THREAD

**Issue by Seb-135** [GrapheneOS/os-issue-tracker#2140]
Some applications (Aurora Store, ONLYOFFICE Documents) don't request the storage permission, but they do request "access to manage all files." As they don't request storage, there is no way to enable storage scopes from within app info.

With ONLYOFFICE Documents, this isn't much of an issue, as I am shown this popup when it requests the permission:
![image](https://user-images.githubusercontent.com/76539951/233261780-09fb259f-ccaa-4769-a5f8-6f8f3deec1f5.png)
And from there, I can turn on storage scopes.

The issue is with Aurora Store. Pressing "GRANT" in-app doesn't show the popup, but instead immediately takes me to settings (the same behaviour as clicking "Allow (in Settings)" on the popup in the above screenshot)
![image](https://user-images.githubusercontent.com/76539951/233262375-1246233b-9821-4b86-9950-245d536b1a26.png) ![image](https://user-images.githubusercontent.com/76539951/233262388-640afe00-7c81-4aa2-8865-2442c451db76.png)

Yes, Aurora allows me to skip this and simply press "Finish", but this may result in some other apps being unusable without actually granting the manage all files permission, as the app can clearly see it has not been granted the permission (I have tested, the green GRANT does become a grey GRANTED if I tick the "Allow access to manage all files" tickbox).

As a small sidenote, I actually have enabled storage scopes for Aurora previously, several months ago in my main profile. It is still enabled. I am currently installing it in my work profile, which is how I ran into this. Perhaps it used to request the regular storage permission, or maybe the popup worked?

**Comment by r3g-5z** [comment]
This is already fixed and will be available in the next GrapheneOS release.
