### ISSUE TITLE
Pixel 6 went black during update of the google play services

### ISSUE THREAD

**Issue by sdaro** [GrapheneOS/os-issue-tracker#2144]
During the installation of the Google Play Services my Pixel 6 went black.
Restarting the phone isn't possible (I tried long pressing of power button for 30 seconds as well as pressing power button + volume up for 20 seconds).
Plugin a power supply doesn't make a sound and I can't call my phone number. The phone seems to be off.
Nothing works anymore.

What can I do now?

**Comment by thestinger** [comment]
This is a hardware failure.
