### ISSUE TITLE
Hotspot traffic is not routed through (Wireguard) VPN

### ISSUE THREAD

**Issue by Sjors** [GrapheneOS/os-issue-tracker#2145]
I configured my Pixel 7 to only connect via WireGuard. I enabled the Always-on VPN setting as well as the setting to block connections without a VPN.

But when I use the device as a hotspot for my laptop, either via wifi or USB, the traffic goes straight to internet. I only noticed this after a few hours by going to one of those "check my IP address" sites. Alternatively, when I close the WireGuard connection, my phone browser correctly refused to load any page, while the laptop happily keeps going.

Ideally hotspot traffic would be router through the VPN. But if not, then it should either be blocked or there should be a big warning in the settings screen that it is not blocked.

**Comment by thestinger** [comment]
Android has a per-profile VPN system. Owner profile VPN is for the owner profile and system components, not other user profiles, work profiles or devices. This is it working as intended and it's designed this way for important privacy reasons.

https://github.com/GrapheneOS/os-issue-tracker/issues/30 is already filed and there isn't an obvious correct approach to implementing it so it cannot be worked on at the moment.

It doesn't make sense to include a warning for the per-profile VPN feature working as designed. It could be explained that it's per-profile for privacy reasons somewhere in the UI. We're unlikely to make downstream changes to the UI to add documentation. Suggest filing it with AOSP.
