### ISSUE TITLE
Unresponsive buttons in apps

### ISSUE THREAD

**Issue by xkuza** [GrapheneOS/os-issue-tracker#2147]
in app buttons dont work, like switch off waze from slide down menu work grapheneos, some "locate me on map" buttons in apps.

Apps like bolt, waze works and tracks fine. 
![Screenshot_20230424-083854~2](https://user-images.githubusercontent.com/43542323/233909334-33000318-3216-480a-8d82-78fbd7385787.png)

**Comment by thestinger** [comment]
You need sandboxed Google Play and it needs to be properly set up / working. More info required if you want to file an issue.
