### ISSUE TITLE
Audio-related Tasks Not Functional (Google Pixel)

### ISSUE THREAD

**Issue by Ethobling** [GrapheneOS/os-issue-tracker#2149]
I recently updated my Pixel 4a 5G and now anything related to audio doesn't work. Before the update, things worked fine and then after I updated and restarted the phone, they didn't. 

-I can call, but cannot receive audio and the person on the other end cannot hear me. 
-Spotify doesn't play sound. 
-Camera app will take photos, but videos lag the phone when initiated and has to be forceably shut down. 
-Cannot play videos and if I can, they don't play audio. 

I had not restarted the phone in perhaps 14-15 days. 

I heavily use this phone for work and am pretty desperate. I know y'all are busy, but I really don't want to have to buy a new phone, especially considering I've only had this one for less than a year. 

Please save me $400!

Thanks.

**Comment by Ethobling** [comment]
> 

Probably not? I just installed the OS when I first got it and have used it since. 

What constitutes Dev Options? (I assume if I have to ask, I probably didn't)

**Comment by thestinger** [comment]
Likely a hardware failure. You can confirm with a factory reset.

**Comment by thestinger** [comment]
If you have an accessibility service, device manager or developer options enabled, turn that stuff off.

**Comment by Ethobling** [comment]
Well this sucks.
