### ISSUE TITLE
Wi-Fi Privacy: Phone shows as "android-dhcp-13" on Wi-Fi router

### ISSUE THREAD

**Issue by Perflyst** [GrapheneOS/os-issue-tracker#2150]
From https://grapheneos.org/usage#wifi-privacy
> Wi-Fi on GrapheneOS is very privacy-friendly and is essentially anonymous as long as apps do not leak uniquely identifying information to the network

On a FRITZ!Box Wi-Fi router a device with GrapheneOS shows up with a generic name and randomized MAC address but also as  `android-dhcp-13`.

![image](https://user-images.githubusercontent.com/26308977/234630342-83f18523-7a3c-4a38-a427-6e556b668588.png)

Maybe this information can be removed or changed to a generic string to be more anonymous

**Comment by thestinger** [comment]
That is a generic string.

**Comment by thestinger** [comment]
Changing this would make GrapheneOS different than other Android devices. It should only be changed in AOSP.
