### ISSUE TITLE
GPU HW overlays broken after skipping driver update

### ISSUE THREAD

**Issue by andre4ik3** [GrapheneOS/os-issue-tracker#2154]
I have a Pixel 7 Pro I haven't used in a while because I upgraded to a higher capacity model, now I want to give it to a friend to use. After updating it to latest, I noticed an issue where system overlays are not properly drawn. The issue can be temporarily fixed until next reboot by enabling "Disable HW overlays" in developer options.

Permission popup in Vanadium without the overlay:

![Popup in Vanadium](https://i.imgur.com/77UuyTA.jpg)

Screenshot of that same popup:

![Popup screenshot](https://i.imgur.com/rDJ1pLq.jpg)

**Comment by andre4ik3** [comment]
Unfortunately I can't test out the older software (before any GPU updates) because it's no longer available. Is there another mirror of older releases?

<img width="406" alt="CleanShot 2023-04-28 at 21 04 01@2x" src="https://user-images.githubusercontent.com/62390580/235221114-1c2c90f5-ae22-4d6d-ae56-44a18050ceb6.png">

**Comment by r3g-5z** [comment]
GrapheneOS does not host older releases.

**Comment by thestinger** [comment]
What do you mean after skipping driver update?

**Comment by thestinger** [comment]
Can't replicate an issue. Try disabling / resetting all developer options.

**Comment by andre4ik3** [comment]
> What do you mean after skipping driver update?

Not updating the OS for a while. I went from late fall 2022 update (around 2022113000
) to the latest one (2023041100)

> Can't replicate an issue. Try disabling / resetting all developer options.

Already tried, as well as factory reset. Trying to re-flash it now.

**Comment by andre4ik3** [comment]
Re-flashing didn't work. I also tried stock OS and it is also affected. Seems it will stay like this until next driver update.

Also somewhat related (on the topic of GPU bugs): on my other Pixel device this issue is not present, however there is a different graphical glitch. During boot, the GrapheneOS logo jitters a few times, shrinking slightly and moving top-left (as if the screen size was made smaller) before returning back, it does this 2-3 times during boot. This phone does not have this issue. Maybe I should make another issue for that, but I digress.

Any chance of GPU drivers getting rolled back or updated to a fixed version next update?

**Comment by r3g-5z** [comment]
We're not rolling back GPU drivers. They contain critical security fixes.

Since this issue impacts stock OS, we'll leave it up to Google to fix it.

**Comment by thestinger** [comment]
@andre4ik3 Unable to replicate an issue. Can you please fully explain how you trigger it and what happens?

**Comment by andre4ik3** [comment]
Ok.

1. Flash a relatively old version before recent GPU updates (e.g. 2022113000 if anyone still has it).
2. Boot up the device, go through setup, overlays should work (can quickly test by checking if power menu has shade behind it).
3. Flash latest.
4. Boot up the device, go through setup, check power menu, overlays should be gone.
5. Go to dev options and disable HW overlays. They'll work again until next reboot.

**Comment by thestinger** [comment]
I can't replicate overlays being missing.

**Comment by andre4ik3** [comment]
> We're not rolling back GPU drivers. They contain critical security fixes.
> 
> Since this issue impacts stock OS, we'll leave it up to Google to fix it.

Maybe you can update the drivers if there is a newer version? In the changelog it says (quite a while ago):

> update Mali GPU driver to QPR2 Beta 3 release

So it is a beta release. Maybe a new one has come out that fixes the issue?

**Comment by andre4ik3** [comment]
Is there any way for me to wipe device to the GPU drivers it shipped with?

**Comment by thestinger** [comment]
No, it's not a beta release. QPR2 is released and we didn't update the drivers to QPR3 beta so they are QPR2 stable drivers.

**Comment by thestinger** [comment]
> Re-flashing didn't work. I also tried stock OS and it is also affected. Seems it will stay like this until next driver update.

I thought you said it happened on stock OS too.

**Comment by andre4ik3** [comment]
Yes it does. Also happens on stock april 2023 too.

**Comment by andre4ik3** [comment]
So I flashed both top and bottom links on stock nexus software, which was october 2022 and april 2023. Both of them still have the issue.

**Comment by thestinger** [comment]
Maybe the hardware is screwed up.
