### ISSUE TITLE
Phone Call Rings Through On Alternate Profile

### ISSUE THREAD

**Issue by NeverHeardThat** [GrapheneOS/os-issue-tracker#2155]
Hello.  I'm submitting a simple bug report.  On a Pixel 5 running the current OS (build TQ2A.230405.003.2023041100) a cellular phone call rang while I was inside a non-owner profile.  The incoming call screen was not the normal full screen window I typically see.  This was a fairly small window that dropped from the top of the screen with a simple message.  I don't know the exact wording but it was something like "incoming call from xxx-xxx-xxxx."  I did not accept or decline the call.  Back on the owner profile, I checked the alternate profile options and "Turn on phone calls and SMS" was already disabled.

Thank you to the developers and contributors of GrapheneOS!  This project is awesome!

**Comment by thestinger** [comment]
This is the intended way for it to work by default. Please see https://source.android.com/docs/devices/admin/multi-user#effects. We don't plan to change this especially since carrier-based calls and texts aren't encrypted so they aren't secure anyway.

**Comment by thestinger** [comment]
You can receive calls while locked which is why it makes sense that you can receive them while using another profile.

**Comment by thestinger** [comment]
You can receive carrier-based calls while locked which is why it makes sense that you can receive them while using another profile. It's up to apps to decide how to do this for app-based calls.

**Comment by thestinger** [comment]
You can receive carrier-based calls while locked which is why it makes sense that you can receive them while using another profile. It's up to apps to decide how to do this for app-based calls but they can't support receiving them across profiles.
