### ISSUE TITLE
Phantom clock alarm

### ISSUE THREAD

**Issue by Ampnbsp** [GrapheneOS/os-issue-tracker#2157]
Phone: Pixel 4a (sunfish)
Version: TQ2A.230405.003.2023041100

So, the problem as i wrote. Sometimes appears a new clock alarm with random time, but in clock app has no one. When it comes to alarm time, this alarm just disappearing without any sound or other signal.
![Screenshot1](https://user-images.githubusercontent.com/41110719/235340639-5a54bfc8-3aee-46b4-b54d-a9ef375f6194.png)
![Screenshot2](https://user-images.githubusercontent.com/41110719/235340642-f0e4c62b-25bc-4a31-abd6-4953295223a7.png)

**Comment by thestinger** [comment]
This isn't only for the clock app. It's likely another app you're using.
