### ISSUE TITLE
Lost pinch & zoom

### ISSUE THREAD

**Issue by rickr3** [GrapheneOS/os-issue-tracker#2160]
After last night's apparent update, I lost the ability to pinch & zoom in all apps - gallery, camera, Brave, Waze, security camera app QTView, etc. Also keyboard is erratic. Either touch pad calibration is out or routines have been comprised in the update.
Can't find a calibration app or touch screen settings in the app.

**Comment by r3g-5z** [comment]
Sounds like a hardware failure or you have a problematic accessibility service or messed with developer options.

**Comment by rickr3** [comment]
This was closed without resolution. Pease reopen.

**Comment by r3g-5z** [comment]
No one's able to reproduce your issue and no one's reported such a bug since our update. You have a hardware failure of somekind. You can try sideloading the update again but this is not a GrapheneOS bug. https://grapheneos.org/usage#updates-sideloading

> Can I roll back that update?

No.

**Comment by r3g-5z** [comment]
> I started having touch screen calibration issues when typing with the default keyboard. Other settings had changed as well, minor things like font colors. 

This even further confirms that you have a hardware failure.
