### ISSUE TITLE
Phone rebooted without asking and now doesn't boot anymore

### ISSUE THREAD

**Issue by Smoophyy** [GrapheneOS/os-issue-tracker#2161]
Hi,

I've had a problem with an update in the past (https://github.com/GrapheneOS/os-issue-tracker/issues/2071)
This time I wanted to wait until tuesday as I need my phone for work before that.

A few hours ago I saw the phone downloading an update.
Even tho I have it set to the manual reboot, it suddenly rebooted. Or at least it tried.
Just after the Google logo, theres a the Graphene logo very briefly and then it reboots into recovery mode (Cannot load Android system....) .

I have read about sideloading but I never used that. I installed the shell and started it but the phone is not detected.

Anything I can do to not loose my data again? The phone did not run out of battery, nor did I press anything.

Thanks!

**Comment by thestinger** [comment]
I suggest having the phone replaced via warranty. Others are not having these issues. The error you just stated of the OS failing to load is potentially a storage hardware failure. We don't have a way of solving it.

**Comment by Smoophyy** [comment]
It did boot but was stuck in the GrapheneOS logo now.

After 2 hours I forced a reboot and it's back to not loading anymore so I think you're right.
First time I actually have to use warranty on a phone :)

Thanks for your time

**Comment by thestinger** [comment]
It is likely the same issue as before but has gotten worse now.
