### ISSUE TITLE
Feature Request: Network 'Ask Every Time' Permission

### ISSUE THREAD

**Issue by keatonhj** [GrapheneOS/os-issue-tracker#2164]
As the title says, have the option for Network 'Ask Every time' Permission instead of just Allow or Deny. 
This means we can have apps like Tiktok unable to share data in the background but we can temporarily allow network whilst using it each time. It would be useful for so many apps.

**Comment by r3g-5z** [comment]
Doesn't make any sense. The entirety of this feature assumes the app is not malicious and is just waiting to exfiltrate data. An app you decide to turn off network can store data and wait until it has internet again to exfiltrate data or make contact with a server.

**Comment by thestinger** [comment]
They'll send the data they wanted to send while the network is unavailable when it's available again.

**Comment by keatonhj** [comment]
It's about any apps you don't want constantly using data in the background such as real time location but you are okay with sending when you open it. Why did you close this? It's a legitimate request.

**Comment by thestinger** [comment]
Location is a time sensitive permission and therefore has foreground-only and one-time grants. If you grant background location access to an app that logs it and sends it to a server, it will queue it up and send it to the server when the network is available.
