### ISSUE TITLE
Stuck on verifying it's you when using hardware security keys. 

### ISSUE THREAD

**Issue by Klejdi-Bozho** [GrapheneOS/os-issue-tracker#2168]
When I attempt to login to my account after I install Sandboxed Play Services I get stuck in this screen. Using one of the 10 backup codes or removing the hardware security key from another device is the only way I am able to login. Very likely it is related to #2089.
![000190](https://user-images.githubusercontent.com/127548208/235741095-de9f3160-0ce6-4b53-8841-ce9ce910e309.jpg)

Device: Pixel 6 Pro
Release: 13 (TQ2A.230405.003.E1)

**Comment by muhomorr** [comment]
I've reproduced this issue on my device, but it's not clear what is its root cause.

**Comment by muhomorr** [comment]
This issue happens on stock OS for me too, this is not GrapheneOS-specific.

**Comment by Reflux0301** [comment]
I've ran into this as well. 

I removed my security keys from the account, resigned in without them, reenabled them, and it worked.

I'm not a developer so I don't know if this is viable or not: is it possible to turn off or decline access from the security key on the phone using Titan M2 to get past this menu?

**Comment by natert** [comment]
My YouTube account that's enrolled in Gapp, I have no issue logging into the play store on GOS. My other accounts enrolled in Gapp fail to sign in to play store. I had to remove my yubikeys to even sign in.
