### ISSUE TITLE
Huge battery drain in Pixel 6 after a recent update

### ISSUE THREAD

**Issue by steel-steven-87** [GrapheneOS/os-issue-tracker#2173]
After a recent update, the battery life has become much worse.

When I checked the battery usage, it reported that the mobile network has drained around 30% of the battery when the phone was idle for a couple of hours.

The build version is TQ2A.230505.002.2023050100.

**Comment by thestinger** [comment]
Very unlikely that this has anything to do with GrapheneOS.
