### ISSUE TITLE
Bug with GrapheneOS file manager

### ISSUE THREAD

**Issue by ViktorKahu** [GrapheneOS/os-issue-tracker#2174]
I am unable to delete 2 corrupt .apk files with 0b size (screenshots below).

Observations:

1) These files only show up when downloads are accessed via the side panel of the files app.

2) They do not show up when the downloads folder is accessed by normal means (drilling down through folders).

3) These files do not show up on the computer via usb debugging.

4) These files do not show up in other 3rd party file managers.

5) When attempting to download .apk from the internet again via the browser, these files are detected as existing and a prompt is displayed asking if I want to download again.

6) The ls command in yerminal emulator does not find these files.

Attempts to resolve:

1) tried to delete them - they are not deleting.
2) tried to move them - get an error, unable to move.
3) tried to rename a different .apk file with the same name and delete it from the same folder (Downloads), the second file successfuly deletes, but the original remains.
5) tried to delete via termux - no files found.
6) tried to delete vis computer (usb debugging) - no files found.
7) tried to clear cache and app data from the files app and restart phone - no change.
8) Tried to delete with multiple 3rd party file managers including google files - no files found.

It sems I have tried everything short of a factory reset and hit a dead end.

![Screenshot_20230505-141323](https://user-images.githubusercontent.com/125934998/236378494-513c141d-0c0a-44b8-913c-fb5ea2914967.png)

![Screenshot_20230505-141323](https://user-images.githubusercontent.com/125934998/236378525-9679f0de-14ca-4ea1-b9d3-8419ecad4606.png)

**Comment by thestinger** [comment]
What did you download them with? Try clearing browser app data.

**Comment by ViktorKahu** [comment]
I downloaded via the browser, tried clearing, no success. Also tried deleting the entire downloads folder, folder deleted successfuly, but these files still remain.

**Comment by thestinger** [comment]
Clear the browser's app data. It has pending downloads.

**Comment by ViktorKahu** [comment]
![Screenshot_20230505-141318~2](https://user-images.githubusercontent.com/125934998/236378984-a24fcf7e-bd16-443c-b2e3-98d3d89de88c.png)

**Comment by ViktorKahu** [comment]
Will try now

**Comment by ViktorKahu** [comment]
Browser app data and cache cleared, files still present.

**Comment by muhomorr** [comment]
Try clearing storage of "Download Manager" system app (`com.android.providers.downloads` package name).

**Comment by ViktorKahu** [comment]
> Try clearing storage of "Download Manager" system app (`com.android.providers.downloads` package name).

Thanks for the suggestion.

Tried it, but problem still persists.

Nothing at all has worked so far.

**Comment by ViktorKahu** [comment]
Update: the 0 kb files have disappeared after a week. They must have some sort of time out.

If you are in a similar situation and your search for answers has lead you here, no actions are needed, don't do a factory reset, just wait and they will time out after about a week.

**Comment by ProgrammerWhoPrograms** [comment]
Even if it will disappear after a week, it is still a bug. Please reopen.

**Comment by thestinger** [comment]
It's an app bug, not an OS bug. It works the same way on the stock OS.
