### ISSUE TITLE
password doing actions (some plausible deniability)

### ISSUE THREAD

**Issue by prebuffo** [GrapheneOS/os-issue-tracker#2175]
I have read the debate on the effectiveness of having a plausible deniability system that opens a convenient profile depending on the password entered.
As an alternative, I propose a system in which certain passwords are matched by an action that e.g. deletes certain apps or data from the device or even entire profiles.  An extension of the Duress Password.

**Comment by thestinger** [comment]
Not currently planned and there needs to be a more specific description of what you want it to do. Deleting apps, etc. isn't going to reliably remove data. Only profiles as a whole can be reliably deleted. We aren't going to do anything that's easily detected like this.
