### ISSUE TITLE
mobile_data1 does not always enable Internet

### ISSUE THREAD

**Issue by schklom** [GrapheneOS/os-issue-tracker#2176]
## What I have done
The new Internet tile in the Quick Settings really bugs me, so I have brought back the Mobile Data tile using Tasker.
My Quick Setting tile toggles Mobile Data by giving the value 1 or 0 to the global setting `mobile_data1`.

## Problem
Often, it works as it used to in previous Android versions (although it takes around one second instead of being instant).
The problem is that many times, Mobile Data is not actually turned on (I mean that Internet remains unavailable) until I open the new Internet tile. When I click on the Internet tile, the Internet window appears and Mobile Data turns on without me doing anything.

## Idea on the cause of the problem
I am far from an expert, but I believe that Android listens to changes of `mobile_data1` for some time after there are network changes, and stops listening after network is idle for some time. Clicking on the Internet tile lets Android know that there will be network changes, and therefore Android starts monitoring the state of `mobile_data1`.

**Comment by thestinger** [comment]
This is not a bug.

**Comment by schklom** [comment]
Ok, my bad.

I know you must be busy, but can you please provide some insight into what is happening? The fact that setting the value of `mobile_data1` to 1 only turns Internet on some of the time is really confusing to me.
