### ISSUE TITLE
Keyboard Language doesnt seem to work: Dutch

### ISSUE THREAD

**Issue by withdefiance** [GrapheneOS/os-issue-tracker#2179]
Hi, I wanted to report a small bug in the keyboard function. The Dutch auto-spelling doesn,'t seem to be working. Dutch however does not register any input. It is not making spelling proposals nor registers spelling mistakes.

 I do have German and English and they work just fine.

I have the phone with latest updates. I use a Pixel4a.

**Comment by thestinger** [comment]
It doesn't really support Dutch. You need a different keyboard.
