### ISSUE TITLE
feature request: integration of calendar in clock-widget

### ISSUE THREAD

**Issue by withdefiance** [GrapheneOS/os-issue-tracker#2180]
I know this seems like a general feature issue, or maybe it is a bug, but the clock-widget does show time and date, but when tapping the date, the widget doesn't have a calendar integrated. It would be great to have this feature.

A very light calendar would make it easier to quickly view which dates are on which day. Registering events on a date would make it even better, but priority for me has the first, together with it being secure and not gathering Intel on your agenda and activities.

**Comment by r3g-5z** [comment]
This depends on a user-facing calendar app being preinstalled. We have no plans on integrating a calendar app into our OS. Users should find a calendar app they prefer themselves.
