### ISSUE TITLE
Enable SIM toolkit

### ISSUE THREAD

**Issue by aboveagency** [GrapheneOS/os-issue-tracker#2183]
Hello there! 

We've noticed that the SIM toolkit app is unable to be launched. When tapping on the 'SIM toolkit' setting in search results it takes you to the app info screen. This app is typically available on all Android ROMs. 

Enabling SIM toolkit would be useful for users to fix their own APN issues with SIM cards. Currently you would need to transfer it to another Android phone. 

Thanks for all the hard work!

**Comment by thestinger** [comment]
Not able to replicate any issue with this. Please give device model and carrier.

**Comment by aboveagency** [comment]
Thanks for the quick replies. It sounds like this must be a carrier specific issue. 

The SIM/carrier is esim.me
The model is a Pixel 5 (have also seen this on other phones) 

With this carrier the SIM toolkit doesn't show up in app drawer (although it does show on all apps), and when you tap toolkit it takes you to this screen 

![image](https://user-images.githubusercontent.com/126202827/236862472-eb174d71-934c-47af-b99c-2d6f17d8c81d.png)

**Comment by flawedworld** [comment]
SIM Toolkit showing up is carrier dependent. Not all SIM cards will expose functionality to the OS for it to be leveraged. This is not a bug and is how it works.

**Comment by aboveagency** [comment]
Just to note - this SIM card/service does support the SIM toolkit and has a carrier menu on other phones. I will update this issue with anything else I find.
