### ISSUE TITLE
Feature Request: Battery Charge Limit

### ISSUE THREAD

**Issue by timedin-de** [GrapheneOS/os-issue-tracker#2188]
Would be nice to protect the battery with a charge limit to enhance its longevity.
Like Samsung or Apple has.

**Comment by thestinger** [comment]
Might be added eventually but isn't a priority and not planned in near term.

**Comment by Amund9** [comment]
To set or disable the 80% charging limit, as owner, go to Settings > Battery > Charging Optimization.
