### ISSUE TITLE
Attempting to 'Apps' menu in the Settings app crashes Settings.

### ISSUE THREAD

**Issue by alyxxox** [GrapheneOS/os-issue-tracker#2192]
When I attempt to open any app's details, or the 'Apps' section directly from the settings app, the Settings app proceeds to lock up then crash producing this crash report:
```
type: ANR
osVersion: google/panther/panther:13/TQ2A.230505.002/2023050500:user/release-keys
package: com.android.settings:33
process: com.android.settings

activity: com.android.settings/.homepage.SettingsHomepageActivity
cause: ANR Input dispatching timed out (9d31d9b com.android.settings/com.android.settings.homepage.SettingsHomepageActivity (server) is not responding. Waited 5000ms for FocusEvent(hasFocus=false))
info: ANR in com.android.settings (com.android.settings/.homepage.SettingsHomepageActivity)
PID: 13930
Reason: Input dispatching timed out (9d31d9b com.android.settings/com.android.settings.homepage.SettingsHomepageActivity (server) is not responding. Waited 5000ms for FocusEvent(hasFocus=false))
Parent: com.android.settings/.homepage.SettingsHomepageActivity
ErrorId: 25e3e1e2-7906-4450-9ac1-e80cc2aa32f0
Frozen: false
Load: 2.2 / 2.93 / 2.08
----- Output from /proc/pressure/memory -----
some avg10=0.00 avg60=0.03 avg300=0.63 total=9845615
full avg10=0.00 avg60=0.03 avg300=0.17 total=3048656
----- End output from /proc/pressure/memory -----
```
Some initial trouble shooting involved first checking apps using a lot of ram. I had been using Kiwi Browser with a decent amount of extentions and it had the highest ram usage, so I force quit that from developer options. This aleviated the issue until I tried to open any app details. After this I reset all developer options back to stock and then turned off developer options as a whole and reboot. This seemingly did nothing, so I attempted to uninstall Kiwi Browser as a whole which completely locked my device up and then hard rebooted. After this reboot, the same behavior exists, i.e. Settings app works fine until I attempt to open the 'Apps' section. I have not reopened dev options or anything to continue troubleshooting at this point.

**Comment by muhomorr** [comment]
Capture a logcat output after reproducing this issue with `adb logcat -v uid -d > log.txt`

**Comment by empratyush** [comment]
due to inactivity i am closing the issue if you are still having the issue feel free to reopen the issue
