### ISSUE TITLE
Wireguard client app "IVPN" crashes when Mock Location is enabled

### ISSUE THREAD

**Issue by cmonty14** [GrapheneOS/os-issue-tracker#2196]
Hello,
I'm using Pixel 6a with latest GrapheneOS.
To establish a Wireguard connection I'm using app [IVPN](https://github.com/ivpn/android-app).

I can enable feature "Mock Location", but then this app crashes.
If "Mock Location" is disabled, there's no issue.

Using another Pixel 6a with AOSP I cannot reproduce this issue. Therefore I think this issue is related to GrapheneOS.

This issue is similar to #1459, however I have not created a log, yet.

Please advise how to fix this issue.

THX

**Comment by thestinger** [comment]
I don't think there's a good reason to think this is related to GrapheneOS.

> Using another Pixel 6a with AOSP I cannot reproduce this issue

On the latest Android 13 release from May?

**Comment by cmonty14** [comment]
> I don't think there's a good reason to think this is related to GrapheneOS.
> 
> > Using another Pixel 6a with AOSP I cannot reproduce this issue
> 
> On the latest Android 13 release from May?

Both Pixel 6a devices are running with latest OS.

**Comment by muhomorr** [comment]
We've identified the underlying issue and are working on a fix.
