### ISSUE TITLE
Google Play Store can't search for updates

### ISSUE THREAD

**Issue by F60-11** [GrapheneOS/os-issue-tracker#2199]
When checking for updates in the Google Play Store, I get this error message; "Something went wrong. Try again"

**Context:** 
Clean install of GrapheneOS 20230516 on a Pixel 6a and no extra configuration apart from normal setup with wifi and passwords. Updated Apps before installing Google services & dependencies via Apps. Signed in into Google Play.

All Google apps have network permissions.
Unrestricted battery for google play services doesn't resolve it.
Using alpha versions of Google apps doesn't resolve it.

The issue is resolved temporarily after clearing Google Play Store's storage, but the issue reappears after reboot.

**Comment by F60-11** [comment]
Already tried, no difference.

**Comment by muhomorr** [comment]
Are you using a firewall or DNS blocking?

**Comment by F60-11** [comment]
My router has a NAT firewall but no DNS blocking.

**Comment by muhomorr** [comment]
Unable to reproduce this issue. 
Can you capture a logcat after reproducing it with `adb logcat -d -v uid` ?

**Comment by F60-11** [comment]
OK now I know one more key detail. The issue presents itself only after a reboot, or if Google Play Store updates itself (which restarts the app). Did you reboot after installing Play store & co?

I've run logcat (using alpha versions of Gapps), and instead of dumping the whole log which might contain sensitive information I've selected the part that log that's written when the "Try Again" button is pressed. Hope this is useful. I've replace a key of some sort with REDACTED

[logcat-excerpt.txt](https://github.com/GrapheneOS/os-issue-tracker/files/11520429/logcat-excerpt.txt)

**Comment by F60-11** [comment]
This dude seems to have the same issue; https://discuss.grapheneos.org/d/4160-problems-updating-apps-from-google-store

**Comment by muhomorr** [comment]
> Did you reboot after installing Play store & co?

Yes

> [logcat-excerpt.txt](https://github.com/GrapheneOS/os-issue-tracker/files/11520429/logcat-excerpt.txt)

Don't see any useful info there.

**Comment by pordini** [comment]
Having the same issue on a Pixel 5.

**Comment by F60-11** [comment]
OK I've now done some more troubleshooting. I missed one key detail when it comes to reboots inducing the issue. The bug only gets induced if the Gapps are installed, Play Store started and signed in, and then rebooting the OS without installing any other apps or granting any permissions. Did you reboot after signing in?

I've also seemed to have found a permanent fix. If one installs an app from the Play Store before rebooting, the issue never appears! It seems to also work if the issue have already appeared, by clearing storage for the Play Store and then before rebooting installing any app from the Play Store. It sometimes doesn't work to install the first app, but this seems to be more reliable if one grants permission to the Play Store to install unknown apps (and access to obb folder) beforehand.

**Comment by muhomorr** [comment]
> The bug only gets induced if the Gapps are installed, Play Store started and signed in, and then rebooting the OS without installing any other apps or granting any permissions. Did you reboot after signing in?

I've followed these steps, still unable to reproduce it.

**Comment by F60-11** [comment]
> I've followed these steps, still unable to reproduce it.

Thanks for trying. Very weird. What Pixel model are you using?

**Comment by muhomorr** [comment]
Pixel 6a.

Behavior of Play Store is controlled by server-side flags. Values of these flags are often changed for a subset of Play Store installs.

**Comment by scarecrow1636** [comment]
I have "Something went wrong. Try again" error reappear every time I either sign into Play Store with an existing account or a new one. The error is resolved for me by installing something from the Play Store and is not encountered again.

2023101300 (Pixel 6a), but the issue dates back a while.

![Screenshot_20231020-184111](https://github.com/GrapheneOS/os-issue-tracker/assets/147932510/207821a2-3ebc-4701-8592-44d8e688eab8)
![Screenshot_20231020-184228](https://github.com/GrapheneOS/os-issue-tracker/assets/147932510/83774146-1b7e-4e71-80d8-58e08dcfd0fb)
![Screenshot_20231020-184219](https://github.com/GrapheneOS/os-issue-tracker/assets/147932510/f083accd-095d-4f73-a8ed-a65c8eeaff41)

**Comment by thestinger** [comment]
It's expected for it to happen when there are no apps for it to update. That's not a GrapheneOS issue. If that's what this issue is about, it can be closed.
