### ISSUE TITLE
"Ask every time" for microphone not working in major apps

### ISSUE THREAD

**Issue by dm17** [GrapheneOS/os-issue-tracker#2200]
The two apps I've tested this a lot in are WhatsApp and Instagram. Selecting "ask every time" causes those apps to direct you to permissions to enable it always. I've seen it pop-up before with "allow this time" - but stopping/starting and retrying by touching the record button does not seem to trigger this functionality lately.

Reproducing this is merely holding the record button in the app in question. The app in question should have the permission "always ask" enabled for microphone. I have tried reinstalling and clearing the storage for the apps in question.
Thank you GOS experts & devs.

**Comment by thestinger** [comment]
https://github.com/GrapheneOS/os-issue-tracker/issues/2163

**Comment by thestinger** [comment]
Ignore the previous link.

**Comment by thestinger** [comment]
This is a choice by the apps on how they choose to request the permission. It's not up to the OS.

**Comment by dm17** [comment]
May I have your recommendation about how to probe this inconsistency? I was able to get the dialog sometimes - and others in the GOS community always get it.

**Comment by thestinger** [comment]
The app is choosing to direct you to the permissions menu. It's the precise series of what you're doing with it. I don't think we can do anything about this.

**Comment by dm17** [comment]
May I ask why other people using the same version of GOS and the same version of the same apps are not directed to the permissions menu but rather receive the "allow this time" dialog?

**Comment by thestinger** [comment]
You're doing something differently or getting a different variant of the apps. Issue tracker is not a good place to discuss this.

**Comment by dm17** [comment]
Apologies. I was told in the GOS matrix chat to file an issue.
