### ISSUE TITLE
Please enable VoLTE support for Chinese carriers

### ISSUE THREAD

**Issue by diskdance** [GrapheneOS/os-issue-tracker#2201]
First of all, thank you for this amazing OS!

AOSP and Pixel's carrier configs for three major Chinese carriers (China Mobile, China Telecom, China Unicom) are very outdated. All of them support VoLTE but this is not reflected in the config. As a result, when user making a call, phone will falls back to 2G which is apparent insecure (3G network has been shut down), which is not nice in a secure mobile system.

I hope GrapheneOS devs can override these configs, like this:
```xml
<boolean name="enhanced_4g_lte_on_by_default_bool" value="true" /> <!-- Enable LTE+/4G+ -->
<boolean name="carrier_volte_available_bool" value="true" /> <!-- Enable VoLTE -->
<boolean name="carrier_vt_available_bool" value="true" /> <!-- Enable video calling -->
<boolean name="vendor_hide_volte_settng_ui" value="false" /> <!-- Show VoLTE options in settings -->
<boolean name="hide_lte_plus_data_icon_bool" value="false" /> <!-- Hide 4G+ icon -->
<boolean name="show_4g_for_lte_data_icon_bool" value="true" /> <!-- Display LTE as 4G -->
```

Note that the configs above apply to all three carriers, and none of them support VoWifi, so options related to it should not be shown in settings.

5G is supported by them but is not enabled in Pixel's modem. If GrapheneOS devs can enable it, we can go one step further by enabling VoNR support:
```xml
<boolean name="vonr_enabled_bool" value="true" /> <!-- Enable VoNR -->
<boolean name="vonr_setting_visibility_bool" value="true" /> <!-- Show VoNR options in settings -->
```

Thanks.

**Comment by thestinger** [comment]
We can't maintain and test this for every carrier around the world. It needs to be improved in AOSP or at least for Pixels. We can provide overrides eventually.

> As a result, when user making a call, phone will falls back to 2G which is apparent insecure (3G network has been shut down),

None of these is secure, and there is always fallback unless you're using LTE-only mode or equivalent.

**Comment by flawedworld** [comment]
https://github.com/GrapheneOS/os-issue-tracker/issues/956 will deal with this, but it needs to be worked on.
