### ISSUE TITLE
Feature Request: Guided charging to prolong life of the LiPo battery to be more environmental friendly

### ISSUE THREAD

**Issue by mcctuxic** [GrapheneOS/os-issue-tracker#2202]
According to this ariticle:
https://batteryuniversity.com/article/bu-808-how-to-prolong-lithium-based-batteries there is a huge difference between charging to 100%/discharging to nealy 0% and a more moderate attempt to use the battery more below/above these extrema.

Since the battery voltage, the percentage of charge and the battery temperature can be monitored by the OS while chargeing/discharging it would be very handy to have a setting menu which allows to set these limits (min./max. voltage and
min./max. percentage of charge) and proactively stop charging when the level exceeds the upper level or send a alarm, when
the lower limit will be passed while discharging. An additional benefit would be, if the OS could pause charging when the battery becomes more warmer than a given maximum. The hardware based protections are only for preventing fire and not for prolonging the life of the LiPo since this is contra productive (pun intended).

This way it becomes irrelevant, whether my phone take 1 hour or 3 hours to charge, since the limits will be supervisioned and not exceeded automatically.

**Comment by thestinger** [comment]
It already throttles the charging based on capacity and heat.
