### ISSUE TITLE
Gallery Widget Broken

### ISSUE THREAD

**Issue by seniorm0ment** [GrapheneOS/os-issue-tracker#2208]
The widget for the Gallery app is broken.
When you go to widget > Gallery > Single photo
It will take you to the gallery app to select a photo. You click the photo, it offers to crop it, and then it will just flicker and not show up.

I am using Neo launcher if that matters.

**Comment by seniorm0ment** [comment]
When you say deprecated, does that imply it is planned on being replaced?

**Comment by flawedworld** [comment]
The app is just a sample AOSP app, we want to replace it wholly at some point.

**Comment by seniorm0ment** [comment]
Thanks for the reply, glad to hear that. I've really hoped to see something similar to Google Photos or Apple Photos come along.

Simple Gallery is nice but lacks a lot that those two bring.
Google will likely never update their AOSP apps because they want users on their closed source apps instead so they want the AOSP apps to feel outdated. :/
