### ISSUE TITLE
Setting default gps app

### ISSUE THREAD

**Issue by zifxify** [GrapheneOS/os-issue-tracker#2209]
I'm using an app called komoot for getting startpoint coordinates for a walk. In the past it was possible to click on "aanwijzingen tonen" and in a pop-up menu I selected magic earth as gps app. I'm only using magic earth as gps app but is there a way in GrapheneOs to set magic earth as default app as there's no longer a possibility to click om magic earth in the popup-menu when getting the cooridinates from komoot

**Comment by thestinger** [comment]
You can still set default apps for intents. Suggest you reset app associations from the current default.
