### ISSUE TITLE
All apps are forced closed after unspecific time

### ISSUE THREAD

**Issue by TheBready** [GrapheneOS/os-issue-tracker#2211]
Phone: Pixel 7 Pro
Build: TQ2A.230505.002.2023051600

All apps close after some time. This affects every app and all apps at once. Even music apps in the background are closed while the phone is not used otherwise.
Even the discarded 'sandboxed Play Store' notification is shown again. 
This started around the 22nd of May. 
Do you know if this is a known issue?
Will this be fixed with the next release? 

Update: I did the Vanadium 114 Update, which seems to fix the bug. Maybe it was WebView related.

**Comment by empratyush** [comment]
I am closing this issue as it seems the bug has been fixed. Feel free to reopen it.

**Comment by TheBready** [comment]
@empratyush It seems that the bug is here again. This happens every 5 minutes.
