### ISSUE TITLE
Android version mixup?

### ISSUE THREAD

**Issue by penultimateName** [GrapheneOS/os-issue-tracker#2214]
Some apps in the playstore say not for my phone version.  The phone clearly shows running Android 13.  In a communication with Google I checked what additional data is being sent to them.  It has the phone listed as Android 10.  This seems to explain the app issue in the playstore.  

Why is the phone broadcasting Android 10 when it should be Android 13?

**Comment by octocorvus** [comment]
Hi, can you tell us more information about it? Like phone model, GrapheneOS version and the name of the app. Also, how did you check that Android version is listed as 10?

**Comment by muhomorr** [comment]
Are you using Play Store through the Aurora Store?

**Comment by empratyush** [comment]
I think it's based on Vanadium browser user agent.

**Comment by thestinger** [comment]
Vanadium uses the standard frozen Chromium user agent. Chromium's frozen user agent pretends to be Android 10 to avoid leaking the OS version in the user agent. It's still provided via client hints, but we can address that in the future.

Phase 6 has been rolled out to 100% of Android Chrome installs now via the feature flags:

https://www.chromium.org/updates/ua-reduction/#updates
https://www.chromium.org/updates/ua-reduction/#sample-ua-strings-phase-6

We adopted this early, but it's standard now.
