### ISSUE TITLE
Google play store from Apps wont let me install some apps

### ISSUE THREAD

**Issue by divi0001** [GrapheneOS/os-issue-tracker#2215]
Hey,
i have graphene OS lässt Version installed. Also GMs compact, Google play services, ... From apps
When I go into google play store, I.e. try to install geometry dash, it doesn't even show, when redirected from the website linking to google play, it still won't let me install, saying something along the lines, that the app has been developed for an older android version. I tried it on a friends phone, who did not have the same problems, though we made sure the Version of graphene os is the same. Also we are both on a Pixel 6, I think his is a pixel 6a.
Anzone know a workaround?

**Comment by thestinger** [comment]
Play Store doesn't allow installing apps with legacy target API level anymore unless you already had them previously. This is likely the issue. You need to get it from another place. Your friend could send you the APK.
