### ISSUE TITLE
Pixel 6 Pro has no service with Google Fi since TQ2A.230505.002.2023050500

### ISSUE THREAD

**Issue by danhlee329** [GrapheneOS/os-issue-tracker#2220]
Pixel 6 Pro, Google Fi, Washington State

Since [this release (TQ2A.230505.002.2023050500)](https://github.com/GrapheneOS/platform_manifest/releases/tag/TQ2A.230505.002.2023050500), I've had no service on my phone.
![Capture2](https://github.com/GrapheneOS/os-issue-tracker/assets/7574767/481b2cc0-8445-42e6-b3c3-13c24999761c)

Can't tell when exactly this was installed, but can guess that it was on May 7th (no service since this date):
![Capture](https://github.com/GrapheneOS/os-issue-tracker/assets/7574767/79df1b5f-882a-4baf-9388-bc125f725b30)

I went through Google Fi's tech support + ordered a new SIM card for good measure, but no success.  

This issue (https://github.com/GrapheneOS/os-issue-tracker/issues/2044) seemed similar, but going through the steps that worked for some folks doesn't work for me.

I should note that I have tried the current SIM card in my old Samsung Note 9 (stock OS), which works no problem.

**Comment by danhlee329** [comment]
Got a new Pixel 7 Pro and confirming that it works (with both stock OS and GrapheneOS installed).  Also confirming that there are hardware issues on my old phone (Pixel 6 Pro), I've re-flashed the phone with the stock OS and still have no signal/data.  Closing ticket.

**Comment by thestinger** [comment]
May have a blacklisted IMEI or something.

**Comment by danhlee329** [comment]
> May have a blacklisted IMEI or something.

Did a basic check on https://www.imei.info/ and found the status to be `clean`.  Not sure I want to pay for the Pro service, will plan to take this phone in for repairs to see if it is indeed a hardware issue.

**Comment by danhlee329** [comment]
Took it into see what may be the issue and sussed out that it was the SIM card reader, which cannot be replaced, but have to replace the motherboard itself, hardware issue it is.
