### ISSUE TITLE
Duolingo app mic doesn't work

### ISSUE THREAD

**Issue by foodfan** [GrapheneOS/os-issue-tracker#2222]
For exercises that require speaking, the Duolingo app is not able to detect voice responses. I gave it microphone permission (while using app) and tried reinstalling from both play store and Aurora. Same issue. Is this an OS compatibility issue?

**Comment by thestinger** [comment]
Did you install Google Speech Services?

**Comment by foodfan** [comment]
No I was using RHVoice for TTS. Just realized it's only one way and installed Google speech services, as you suggested, and selected it as voice input provider. But it still doesn't work. I restarted Duolingo and toggled the mic permission off & on. Still same issue. Does it need a reboot? Or can it be something else? Thanks!

**Comment by thestinger** [comment]
I just thought it might depend on it. I didn't look into it.

**Comment by foodfan** [comment]
> https://discuss.grapheneos.org/d/1672-unable-to-use-microphone-with-language-apps Possible solution here?

That worked! I'll sum up the solution for anyone else having this problem:
1) Install Google Speech services
2) Select Google Speech Services as "voice input" provider
3) Give BOTH Google Speech Services AND Duolingo microphone permissions
