### ISSUE TITLE
com.android.imsserviceentitlement has a tracker

### ISSUE THREAD

**Issue by ViktorKahu** [GrapheneOS/os-issue-tracker#2223]
com.android.imsserviceentitlement has a firebase analytics tracker.

I wonder if that one has gone under the radar the entire time?

Is it necessary?
Is it disabled?
Is it possibe to remeve it with the next version?

I don't remember opting in to sending any kind of analytics.

Regards

**Comment by thestinger** [comment]
This is not true. You're viewing data from an inaccurate app misrepresenting having support for FCM as a tracker.

**Comment by thestinger** [comment]
This is not true. You're viewing data from an inaccurate app misrepresenting having support for FCM for carriers using it for provisioning as a tracker. It's only used for provisioning if the carrier uses it, requires sandboxed Google Play to be installed in Owner and it is not a tracker.
