### ISSUE TITLE
P7a (lynx) restart/boot anomaly 

### ISSUE THREAD

**Issue by fjfj765** [GrapheneOS/os-issue-tracker#2228]
On P7a, issuing restart command results in shut down instead of restart. Also, every time a boot command is issued, the "wrong OS" warning shows.

**Comment by thestinger** [comment]
Can't replicate this. Reboot is working fine.

There's supposed to be a message on boot showing the OS key fingerprint. Are you sure you have the OS installed correctly? This is covered in the install guide and you should confirm it shows the correct fingerprint.

**Comment by thestinger** [comment]
You can't remove it and it's quite useful for security that it's shown. You can double press power to skip the screen (pause, resume) instead of waiting for it to go away by itself.
