### ISSUE TITLE
Hotspot and wifi can't be enabled simultaneously on P7a (lynx)

### ISSUE THREAD

**Issue by fjfj765** [GrapheneOS/os-issue-tracker#2230]
Please see screen recording. Whenever hotspot is enabled, wifi is disabled. Is this a P7a or a GOS problem?

https://youtube.com/shorts/CzDPiGlYmB4?feature=share

**Comment by fjfj765** [comment]
Build number: 13 (TQ2B.230505.005.A1)

**Comment by octocorvus** [comment]
can reproduce this, need to confirm if this is an issue on stock OS too

**Comment by fjfj765** [comment]
Not an issue on p3a (a11, stock) or p7 (a13, stock). Have not attempted on stock P7a

**Comment by octocorvus** [comment]
Wifi and hotspot doesn't work simultaneously on stock OS either. Seems like an upstream bug or device specific issue or limitation (pixel 7a has a different wifi chip).
