### ISSUE TITLE
Pixel 6 - Certain https:// websites do not work on mobile data when accessed from the phone but work fine through Hotspot - EE UK

### ISSUE THREAD

**Issue by kuchtamartin** [GrapheneOS/os-issue-tracker#2233]
Hello,

I have a peculiar issue, where certain sites do not work when trying to access them over encrypted connection when using mobile data. They work perfectly when on Wi-Fi and even when accessing the Hotspot from another device. The issue manifests while trying to use a browser/app on the phone. Examples include github.com, twitter.com, duckduckgo.com etc... Websites I visit frequently.

I can complete a handshake using openssl s_client with all the above mentioned sites but curl -i just hangs.

I spoke to EE and they have no faults on the network and as mentioned, devices connected via Hotspot have no issues connecting. The issue persists also while travelling - I have travelled a span of 200 miles since it started.

Sometimes restart fixes it for a short while but then it happens again.

I am happy to provide any logs/screens/recordings you'd like to see as I have hit the limit of my knowledge.

Thank you.

**Comment by thestinger** [comment]
This really doesn't sound like an OS issue but rather a network issue. I don't see how it could be an OS issue. There isn't something special for port 80 vs. port 443.

**Comment by kuchtamartin** [comment]
Thank you for your response. 

What points this towards the OS is that I can run curl -i https://github.com on my laptop connected to the phone's Hotspot and sharing the mobile data connection and it works. 

At the same time it just hangs when run on the phone.

I have suffered with this behaviour for two weeks now and I have discussed it with my network support at length. However, since the Hotspot works perfectly, the network is definitely capable of establishing the connection.

**Comment by thestinger** [comment]
Try using the Settings feature for resetting network settings as a starting point. It could be a VPN issue. I don't see how it could be a DNS issue or an OS issue though.

**Comment by kuchtamartin** [comment]
Thank you very much for your help. I did not run any VPN.

I will try re-setting the APN even though my network support advised me against it, stating that if it used to work it should still be fine...

I will report any progress.

**Comment by kuchtamartin** [comment]
So I tried to edit the APNs but it looks like it has been disabled by my network. When I switch the Mobile data on and off it sometimes cures the problem temporarily but after about 5 minutes the problem comes back.

Here is a recent curl output:

`~ $ curl -iv https://twitter.com                                            *   Trying [64:ff9b::68f4:2a01]:443...                                      * Connected to twitter.com (64:ff9b::68f4:2a01) port 443 (#0)               * ALPN: offers h2,http/1.1                                                  * TLSv1.3 (OUT), TLS handshake, Client hello (1):                           *  CAfile: /data/data/com.termux/files/usr/etc/tls/cert.pem                 *  CApath: /data/data/com.termux/files/usr/etc/tls/certs                    * TLSv1.3 (IN), TLS handshake, Server hello (2):                            * TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):                    * TLSv1.3 (IN), TLS handshake, Certificate (11):                            * TLSv1.3 (IN), TLS handshake, CERT verify (15):                            * TLSv1.3 (IN), TLS handshake, Finished (20):                               * TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):                 * TLSv1.3 (OUT), TLS handshake, Finished (20):                              * SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384                     * ALPN: server accepted h2                                                  * Server certificate:                                                       *  subject: C=US; ST=California; L=San Francisco; O=Twitter, Inc.; CN=twitter.com                                                                       *  start date: Dec 25 00:00:00 2022 GMT                                     *  expire date: Dec 25 23:59:59 2023 GMT                                    *  subjectAltName: host "twitter.com" matched cert's "twitter.com"          *  issuer: C=US; O=DigiCert Inc; CN=DigiCert TLS RSA SHA256 2020 CA1        *  SSL certificate verify ok.                                               * using HTTP/2                                                              * h2 [:method: GET]                                                         * h2 [:scheme: https]                                                       * h2 [:authority: twitter.com]                                              * h2 [:path: /]                                                             * h2 [user-agent: curl/8.1.2]                                               * h2 [accept: */*]                                                          * Using Stream ID: 1 (easy handle 0x43ebd20000)                             > GET / HTTP/2                                                              > Host: twitter.com                                                         > User-Agent: curl/8.1.2                                                    > Accept: */*                                                               >                                                                           * Recv failure: Connection reset by peer                                    * OpenSSL SSL_read: Connection reset by peer, errno 104                     * Failed receiving HTTP2 data: 56(Failure when receiving data from the peer)* Connection #0 to host twitter.com left intact                             curl: (56) Recv failure: Connection reset by peer`

Between the Accept */* and Recv failure there is about 2 minutes of hanging. The connection is initially successful and handshake is performed perfectly. I have no knowledge of inner workings of the OS, so please excuse me if this is completely wrong but is OpenSSL bundled? Could there be an issue with it?

**Comment by thestinger** [comment]
Reset your network settings via the reset action.

**Comment by kuchtamartin** [comment]
I have tried the "Reset Wi-Fi, mobile & Bluetooth" and the problem persists. However, the error message has changed, please see below.

```
~ $ curl -iv https://duckduckgo.com
*   Trying 64:ff9b::348e:7cd7:443...
* Connected to duckduckgo.com (64:ff9b::348e:7cd7) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /data/data/com.termux/files/usr/etc/tls/cert.pem
*  CApath: /data/data/com.termux/files/usr/etc/tls/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=Pennsylvania; L=Paoli; O=Duck Duck Go, Inc.; CN=*.duckduckgo.com
*  start date: Oct 20 00:00:00 2022 GMT
*  expire date: Nov 20 23:59:59 2023 GMT
*  subjectAltName: host "duckduckgo.com" matched cert's "duckduckgo.com"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert TLS RSA SHA256 2020 CA1
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0xb400ce7b37afb800)
> GET / HTTP/2
> Host: duckduckgo.com
> user-agent: curl/7.81.0
> accept: */*
>
* HTTP/2 stream 1 was not closed cleanly before end of the underlying stream
* stopped the pause stream!
* Connection #0 to host duckduckgo.com left intact
curl: (92) HTTP/2 stream 1 was not closed cleanly before end of the underlying stream

```

**Comment by thestinger** [comment]
There's something actively interfering with the connections. I really don't see how it could be an OS rather than a network issue unless you have a VPN app messing with stuff.

**Comment by Hanouta** [comment]
According to the curl output it tries to connect via IPv6, even though both Twitter and Duckduckgo don't even have an IPv6 (AAAA) DNS record. Can you try if you can reach ipv4.google.com, and then compare it to ipv6.google.com?

My guess would be that your ISP doesn't provide you an IPv4 address, so it uses DS-Lite when trying to connect to an IPv4-only website. No idea why it causes issues when connecting via your phone, but not when using a hotspot though. Are you using the carrier DNS on both devices, or a different one?

**Comment by kuchtamartin** [comment]
Thank you very much for pointing me in this direction. When trying ipv4.google.com it also connects via IPv6 using the same '64:ff9b' prefix as the above Twitter and DuckDuckGo attempts. When trying ipv6.google.com, the address is in '2a00:' range.

I have left my laptop connected via Hotspot for a little bit longer and it also lost the ability to connect! I am sorry I didn't come across this earlier.

I will speak to EE and see what they say. Thank you.
