### ISSUE TITLE
Cellcom (Wisconsin, USA Verizon MVNO) cellular issues

### ISSUE THREAD

**Issue by Peliwont** [GrapheneOS/os-issue-tracker#2235]
When using Graphene (with everything Google Play installed and setup), SMS, MMS, and calls don't work, while mobile data generally does work fine.

**Comment by flawedworld** [comment]
Please read: https://grapheneos.org/usage#carrier-functionality For further support please use the Matrix rooms.

**Comment by Peliwont** [comment]
I have read that.  I have installed GrapheneOS on 3 separate occasions, to troubleshoot this.  I cannot get it to have any give.
There's a thread about this https://discuss.grapheneos.org/d/3442-cellcom-network-unavailable/7
