### ISSUE TITLE
Consider implementing charge limits (data and reference included)

### ISSUE THREAD

**Issue by gdonval** [GrapheneOS/os-issue-tracker#2237]
I know the current stance of GrapheneOS on this topic is twofold:

1. Explicit support (i.e. API) is not available in stock Android;
2. Some "random guy" posted an article about how charging hardware has become smarter, preventing catastrophic failure (I know he is not random ;)).

However there are two main problems with the article in question:

1. It only deals with undercharge, overcharge and "undue" stress caused by crude charging algorithms, it does not consider in particular the effect of staying at full charge (i.e. 100% SoC) over long periods of time. Actually the point of the circuitry is to be able to recharge as fast as possible while staying safe and avoiding charging-based degradations as much as possible. 
2. Google itself has implemented a mechanism to limit charge to 80% overnight which indicate this is a problem that is not solved in hardware.

Now regarding staying at 100% charging overnight, there is a [meta-analysis released in 2020](https://www.sciencedirect.com/science/article/pii/S2352152X19314227) (and [here on SciHub](https://sci-hub.wf/10.1016/j.est.2020.101231) if you don't have access to ScienceDirect) that says (Section 3.2):

> Zhang et al. show that a typical laptop battery stored at 25 °C and 100% SoC will irreversibly lose 20% of its capacity each year [[15]](https://www.sciencedirect.com/science/article/pii/S2352152X19314227#bib0015).

> Amiri et al. conclude that smaller changes in SoC during cycling increases battery lifetime [[66]](https://www.sciencedirect.com/science/article/pii/S2352152X19314227#bib0066). Millner specifies that the battery lifetime can be kept in an acceptable range for Plug-in Hybrid Electric Vehicles (PHEVs) by avoiding deep cycles (>60% DoD), high temperatures (>35 °C), and high average SoC(>60%) [[67]](https://www.sciencedirect.com/science/article/pii/S2352152X19314227#bib0067). Marano and Madella show that to reach 10 year/150,000 mile PHEV lifetime, overcharging and operation above 95% SoC should be avoided. They also show efficiency and [performance degradation](https://www.sciencedirect.com/topics/engineering/performance-degradation) if LIBs are discharged or operated at lower than ~25% SoC [[54]](https://www.sciencedirect.com/science/article/pii/S2352152X19314227#bib0054).
>
> Hoke et al. argue that if battery temperature and charge-discharge cycling are kept constant, minimizing time spent at high SoC minimizes degradation [[68]](https://www.sciencedirect.com/science/article/pii/S2352152X19314227#bib0068). If the next day's energy requirement is known, the battery can be charged to the minimum required level, rather than to the conventional full charge [[68]](https://www.sciencedirect.com/science/article/pii/S2352152X19314227#bib0068). Trippe et al. define 60% to 97% SoC as the safe window to preserve battery health [[40]](https://www.sciencedirect.com/science/article/pii/S2352152X19314227#bib0040).

There are obviously more details in the article considered. All these are Li-ion batteries and not old-tech. There is also a wealth of publications on electric vehicles (using Li-ion batteries) for instance [Fig. 9 in this reference](https://ieeexplore.ieee.org/abstract/document/6784141) (as well as the rest of the article) are damning: battery lifetime is **halved** if the battery is left charging all night as opposed to fast (and smart!) charging as late as possible before use.

So unless the guy writing that article can provide data from Google showing the battery is actually never reaching 100% SoC, this is a problem. And the fact Google itself is acting upon this does not bode well for such limit to have been implemented in hardware.

**Comment by thestinger** [comment]
We have not posted any article.
