### ISSUE TITLE
Application pinning & Auto-Reboot

### ISSUE THREAD

**Issue by Exclusion836** [GrapheneOS/os-issue-tracker#2238]
When you pin a application the phone does not autoreboot, now it's technically not a issue with auto reboot since auto reboot only works when the phone is locked but since application pinning basically locks the user to that app auto reboot should take affect as well because of the potential of a adversary with physical access being able to permanently keep a pinned phone unlocked. a separate toggle for application pinning which sets the autoreboot timer for it would be the most ideal solution from what I can immediately think of.

**Comment by thestinger** [comment]
I don't think we should do this.

**Comment by Exclusion836** [comment]
It's not the threat model if a adversary can unlock the phone it's the threat model of persay you as the user has a app pinned and the adversary takes your phone therefore keeping your phone from turning off and enabling them to have access to your phone in AFU, but just behind a pinned app.
