### ISSUE TITLE
Public key for SSH signatures?

### ISSUE THREAD

**Issue by adrelanos** [GrapheneOS/os-issue-tracker#2247]
Trying to verify a git tag for [Hardened malloc](https://github.com/GrapheneOS/hardened_malloc). Most of GrapheneOS git tags nowadays seem to be signed with the following SSH key.

> This tag was signed with the committer’s verified signature.
>
>@thestinger
>Daniel Micay
>SSH Key Fingerprint: AhgHif0mei+9aNyKLfMZBh2yptHdw/aN7Tlh/j2eFwM

Where do I get the SSH public key so I can verify the signatures?

**Comment by thestinger** [comment]
See https://grapheneos.org/build#stable-release. The `allowed_signers` file is available at https://grapheneos.org/allowed_signers and has a signature from the legacy GPG key at https://grapheneos.org/allowed_signers.asc along with a signature from our factory images signify key at https://grapheneos.org/allowed_signers.sig.
