### ISSUE TITLE
Allow disabling/uninstalling the default camera app. 

### ISSUE THREAD

**Issue by Klejdi-Bozho** [GrapheneOS/os-issue-tracker#2253]
Some time ago we were able to disable the Secure Camera app. I use Google Camera since it has more features.

**Comment by thestinger** [comment]
Only the system camera app (GrapheneOS Camera on GrapheneOS) can provide the system media capture intents. It would be broken to disable the app, and the UI not permitting this has prevented you from unknowingly breaking other apps. See https://developer.android.com/about/versions/11/behavior-changes-11#media-capture.
