### ISSUE TITLE
USB debugging timer - feature request 

### ISSUE THREAD

**Issue by foodfan** [GrapheneOS/os-issue-tracker#2256]
I use several apps that require USB debugging, but it is not secure to leave this activated. Would it be possible to add a timer that allows it for a specified period or customizable in hour increments? Thanks

**Comment by thestinger** [comment]
You shouldn't use apps requiring USB debugging, especially if you mean using network-based ADB...

**Comment by thestinger** [comment]
Developer options are not meant for production devices, **especially** network ADB.
