### ISSUE TITLE
Fingerprint unlocking not working when switching profiles

### ISSUE THREAD

**Issue by gaurav601** [GrapheneOS/os-issue-tracker#2261]
I have fingerprint-unlocking enabled. I have 3 profiles right now. Before installing the update, [TQ3A.230605.012.2023061402](https://github.com/GrapheneOS/platform_manifest/releases/tag/TQ3A.230605.012.2023061402) on a Pixel 6a, fingerprint unlock would be the first thing to show up when switching between profiles (after a 2-second delay). However, with this new update, I always have to enter my password to unlock a new profile. Once I have unlocked a profile, I can use fingerprint if I stay on the **same** profile, but **switching** to a profile once again requires my password as the first thing.

Disabling and re-enabling fingerprint unlocking does not fix this issue. Restarting the phone does not fix it. Waiting for a long time (>2 seconds) after switching a profile also does not work.

**Comment by pkhomyakov-rms** [comment]
Exact same behavior on Pixel 7a. One workaround I found is to use fingerprint with any app that requires biometric. This re-enables fingerprint scanner back on the lock screen until profile is switched again.

**Comment by akc3n** [comment]
This is an upstream bug unfortunately.

Duplicate #1611 #2034 #2039

Some discussions on this issue can be found in these threads:
https://discuss.grapheneos.org/d/5616-grapheneos-version-2023061402-released/23
https://discuss.grapheneos.org/d/5691-biometrics-not-available-after-switching-back-to-owner-profile
