### ISSUE TITLE
Google services framework is crashing

### ISSUE THREAD

**Issue by shabbirmahmud** [GrapheneOS/os-issue-tracker#2268]
Device-r5i (RMX2030)
Rom-Alphadroid v1.5.1 Dynamic
Log- https://paste.crdroid.net/PpOMzV

**Comment by thestinger** [comment]
This is the GrapheneOS issue tracker. What you're using is not GrapheneOS.

**Comment by shabbirmahmud** [comment]
> This is the GrapheneOS issue tracker. What you're using is not GrapheneOS.

It says to report here-
![Screenshot_20230624-052635_Apps](https://github.com/GrapheneOS/os-issue-tracker/assets/47573399/b37dd132-69a5-44b2-b160-10f4e1416ea4)
![Screenshot_20230624-052645_Apps](https://github.com/GrapheneOS/os-issue-tracker/assets/47573399/1fb4e3e6-baaa-4cd8-911b-37a74fcedd49)

This is included in alphadroid rom but its crashing.

**Comment by thestinger** [comment]
They should have set that to ask you to report problems to them, not to us. They included an incomplete and outdated implementation of our sandboxed Google Play compatibility layer. You aren't using GrapheneOS or the official sandboxed Google Play compatibility layer and can't report issues with it here. This issue doesn't exist on GrapheneOS.
