### ISSUE TITLE
Solved issue: Voice assistant apps not showing up on Pixel 7

### ISSUE THREAD

**Issue by whowantsmybigdata** [GrapheneOS/os-issue-tracker#2273]
I couldn't use any assistant apps (the list to select one in the default-apps settings was empty) on Pixel 7. 

The solution was to start an adb shell and issue:
`cmd role add-role-holder android.app.role.ASSISTANT {exact package name of any assistant app you have installed already e.g. org.stypox.dicio}` ([source](https://stackoverflow.com/questions/69926951/adb-command-to-set-voice-assistant)) 
afterwards everything worked and all the apps exposing the assist interface showed up normally

thought this could be helpful for sbd with a similar issue.

**Comment by gongoragarciayuberyusegmailcom-a11y** [comment]
Gracias

**Comment by gongoragarciayuberyusegmailcom-a11y** [comment]
Gracias
