### ISSUE TITLE
"Freezing" (hiding) an app in Work profile makes it lose the permission to install apps

### ISSUE THREAD

**Issue by schklom** [GrapheneOS/os-issue-tracker#2280]
## Problem

On my Pixel 6a, I have setup a Work profile using the app Shelter, then installed the Google apps there.
I do not need auto-updates on that Work profile, so I have Shelter "freeze" the Play Store frequently to save battery.

The problem is that each time I "unfreeze" and open the Play Store to update or install an app, it asks for the permission to install apps even though I granted it before. That permission is lost whenever Shelter "freezes" the Play Store.

## Details on "freezing"

As mentioned in https://github.com/seedvault-app/seedvault/issues/518, "freezing"
> uninstalls the app - but keeps the APK and data around, ready for re-install when you unfreeze/unhide

_Originally posted by @chirayudesai in https://github.com/seedvault-app/seedvault/issues/518#issuecomment-1451775111_

Technically, "freezing" is done via https://developer.android.com/reference/android/app/admin/DevicePolicyManager#setApplicationHidden(android.content.ComponentName,%20java.lang.String,%20boolean)

> Hide or unhide packages. When a package is hidden it is unavailable for use, but the data and actual package file remain.

**Comment by thestinger** [comment]
You can test if this occurs with another app like F-Droid. I think this is expected behavior.

**Comment by schklom** [comment]
This also occurs with F-Droid. It is not a big deal, but it gets annoying fast.

But the behavior is inconsistent because many other special permissions also get revoked, but not all.
After testing, when an app is granted a special permission then frozen,
`All files access`, `Picture in picture`, `Unrestricted data`, `Alarms & reminders`, `Wi-Fi control`, `Turn screen on` do not get revoked
`Display over other apps`, `Install unknown apps`, `Modify system settings`, `Usage access` get revoked.

I do not have apps in mind to test the few other special permissions.

To my unprofessional mind, this does not look expected, in particular because a somewhat dangerous permission like `All files access` persists after freezing.
