### ISSUE TITLE
emulated Message and Phone permission grants

### ISSUE THREAD

**Issue by W1zardK1ng** [GrapheneOS/os-issue-tracker#2281]
There are some applications which wont work unless we give phone and message permissions without no reason.
It will be nice to have Message and Phone scope option but doesn't needs to be like current storage or contact scope feature.
Giving a dummy permission which makes the app believe that they have the permissions but don't have it in real should be enough.

**Comment by thestinger** [comment]
This wouldn't be a scope feature.

**Comment by muhomorr** [comment]
Implementing this for "SMS" permission should be quite simple.

"Phone" permission protects many different APIs, it would require a lot of patching.

**Comment by W1zardK1ng** [comment]
Yes, that's understandable.
Maybe we can start with the "SMS" permission as a starting point then and proceed "Phone" permission later.
Thanks team for all the good work.

**Comment by thestinger** [comment]
SMS scope issue can cover this. Phone permission should be a separate issue with more specific plans.
