### ISSUE TITLE
Contact Birthdays not available (no, even not when you open "more fields") Pixel 7a

### ISSUE THREAD

**Issue by lathoudero** [GrapheneOS/os-issue-tracker#2282]
Hi,
Contact Birthdays (or other events) not available (no, even not when you open "more fields"). On a Pixel 7a
I've found another ticket, but this is not the case:
 Contact birthdays #1272 

Other apps that rely on importing events, (calendars, birthday-apps) also can't retrieve contact-events.

as example: com.minar.birday
(yes: bir-day)
It has the option to "import events from contacts", and it returns "no events".
Even though they should be imported.

An odd thing I've noticed is that when I _EDIT_ a contact, I can choose which source I want to edit that contact in. And it shows 2 times "device" as source.

**Comment by thestinger** [comment]
This is a duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/1272 where this was explained. Please report issues with apps to the apps developers. There isn't a reason to think that it's caused by GrapheneOS.

**Comment by lathoudero** [comment]
Please take time to read more thorough before closing.

1) get a pixel 7a
2) Install GrapheneOS
3) create a contact & try to add an event/birthday.

**Comment by thestinger** [comment]
There's no calendar backend included in GrapheneOS.

**Comment by thestinger** [comment]
There's no calendar backend included in GrapheneOS. You need to install one. Please read https://grapheneos.org/faq#bundled-apps about our philosophy on this. We used to bundle Etar Calendar but other people prefer different calendars or don't need one, and it's a third party app not aligned with our approach or goals. It makes choices conflicting with what we would do. We'll already have our hands full replacing apps like AOSP Gallery which need to be included and have no plans to make a calendar frontend or backend.

**Comment by lathoudero** [comment]
Events _are_  referenced in:

https://developer.android.com/reference/android/provider/ContactsContract.Data
https://developer.android.com/reference/android/provider/ContactsContract.CommonDataKinds.Event

**Comment by thestinger** [comment]
You need a calendar backend installed.
