### ISSUE TITLE
Pixel 4 - Always on Display function no longer works correct, phone unlock difficult

### ISSUE THREAD

**Issue by DieSteinhose** [GrapheneOS/os-issue-tracker#2290]
Hello,
When the "Always show time and info" function is enabled. It is very difficult to unlock the phone. The screen goes on and off during the unlocking process, until after a few attempts the unlocking works. It frustates.

Since I have been on the road for the last few weeks and have not applied any updates, I can not say the exact version from when the behavior appeared. The last version that was installed before my trip and worked was probably the [2023062800](https://grapheneos.org/releases#2023062800).

Currently i running [2023062800](https://grapheneos.org/releases#2023062800)

Greetings

**Comment by thestinger** [comment]
Not able to replicate this and not clear exactly what you mean. Could be a hardware issue.
