### ISSUE TITLE
Create a security/privacy slider to enable a preconfigured set off options similar to TOR browser

### ISSUE THREAD

**Issue by ihateprogramming88** [GrapheneOS/os-issue-tracker#2292]
I thought this would be a good idea for people wanting to migrate to the OS, but not having sufficient knowledge to enable certain features of the OS.

For example, there could be a "strict" mode where, the slider could configure the device to try to blend in with other users. e.g. choosing the google servers for the internet connectivity checks. 

Just an idea, obviously the developers would know better if this is worth it or not. 

Thanks :)

**Comment by thestinger** [comment]
Most privacy and security features in GrapheneOS are enabled by default and there are different compromises involved in the ones which have toggles such as memory usage, performance, app compatibility and other things. In some cases, including this, there are different privacy advantages and disadvantages. GrapheneOS connectivity check server is the best overall choice in the default configuration without a VPN. It makes sense to use the Google server instead if you use a VPN and want to blend in on Wi-Fi and mobile networks. This is a very specific choice and none of the other connectivity check toggles have this same tradeoff.

**Comment by thestinger** [comment]
Most privacy and security features in GrapheneOS are enabled by default and there are different compromises involved in the ones which have toggles such as memory usage, performance, app compatibility and other things. In some cases, including this, there are different privacy advantages and disadvantages. GrapheneOS connectivity check server is the best overall choice in the default configuration without a VPN. It makes sense to use the Google server instead if you use a VPN and want to blend in on Wi-Fi and mobile networks. This is a very specific choice and none of the other network connection or other configuration options have a similar compromise. This is unique to connectivity check server. It doesn't make sense to a slider for something where there is only one option involved with a very specific compromise.
