### ISSUE TITLE
Issues with location services since update to 2023062300

### ISSUE THREAD

**Issue by hermmd** [GrapheneOS/os-issue-tracker#2293]
The update to version 2023062300 broke some of the location services: For instance, the easyride feature of the SBB app (https://play.google.com/store/apps/details?id=ch.sbb.mobile.android.b2c) no longer works ("location accuracy too weak"; see screenshot below). Strangely, the same app can still use "current location" for other features. Before the update to graphene os #2023062300, everything worked fine on my Pixel 4a.

Location permissions for the app are set to "Allow only when using the app" (max. possible) and for Google Play Services to "Allow all the time" (and both are using "precise location"). Battery usage is set to unrestricted for the app and Google Play Services.

I haven't changed any of these features and before the update to #2023062300 it worked without any problems. The SBB app wasn't updated, either – so I'm pretty sure that the update of Graphene OS caused this issue.

![Screenshot_20230702-094635](https://github.com/GrapheneOS/os-issue-tracker/assets/109853585/55a5b9fc-6e0e-4776-98fd-0916b9da3b24)

![Screenshot_20230702-094802](https://github.com/GrapheneOS/os-issue-tracker/assets/109853585/4ef520ae-d3bf-441f-bec4-2506327d7762)

![Screenshot_20230702-094838](https://github.com/GrapheneOS/os-issue-tracker/assets/109853585/c9895277-7671-4778-9393-2fd87e64c278)

**Comment by thestinger** [comment]
Please read https://grapheneos.org/usage#sandboxed-google-play-configuration. There's no reason to give location permissions to Play services with the default location rerouting. You seem to be trying to use their network location instead of only satellite-based location but you didn't enable it.

**Comment by hermmd** [comment]
Thanks for the response. In fact I'm aware of the two options: Initially (i.e., before the update mentioned above) I tested with both ways of using the location services, but it turned out that only the Play services location was sufficiently accurate on trains (this app issues train tickets depending on the exact journey traveled) – which is why I ended up deactivating the re-routing. This worked perfectly before the update to 2023062300, so something must have changed (in the GMSCompat?) or so... As written originally, the app hasn't been updated since, and I haven't changed any of the settings (but of course, after the update I tested both options of using the location services, but neither works).

Is there a way to roll back to the previous graphene version (i.e., without a backup), or another way of narrowing down the issue?

**Comment by muhomorr** [comment]
This regression should be fixed by https://github.com/GrapheneOS/platform_frameworks_base/pull/387

It was introduced in https://github.com/GrapheneOS/platform_frameworks_base/pull/380

**Comment by hermmd** [comment]
Great, I look forward to testing it in the next release.

**Comment by hermmd** [comment]
Awesome, I can confirm that it works again after the update to 2023070500. Thank you!!
