### ISSUE TITLE
Bug/Security: call accidentally answered while phone in pocket

### ISSUE THREAD

**Issue by ASerbinski** [GrapheneOS/os-issue-tracker#2297]
Device is Pixel 6 Pro.

This has happened to me several times now; while the phone is in my pocket, somebody calls, and I hear faint voices from my pocket. Turns out that the phone call has been answered by accident while in my pocket!

This is a serious security problem, since it on occasion would allow a caller to listen to sound received by the phone's microphone without letting on that they are on a phone call.

I believe that it *may* have something to do with this commit that removes rejection of "false touches":
https://github.com/GrapheneOS/platform_packages_apps_Dialer/commit/f21e998882faaefbbdb1eb0d0a3d2fafe2aafbbd

I'd personally prefer to have a hard time answering than to have it answer without my knowledge.

Alternatively, another solution that could fix this issue is to disable the touchscreen while the proximity sensor reads as "near".

**Comment by thestinger** [comment]
We can try removing the change. We don't recall how bad the implementation of this in Dialer is so we can check to see if that's as bad as remembered. It will likely be disabled again.

**Comment by ASerbinski** [comment]
Thank you Daniel!
Hopefully it isn't too annoying when it comes to call answering.

**Comment by ASerbinski** [comment]
FWIW: Been running a few days with the 0705 build having this revert included, and I have NOT noticed any difficulty in answering calls.
