### ISSUE TITLE
Feature removal reversion request: SIP calling accounts

### ISSUE THREAD

**Issue by ASerbinski** [GrapheneOS/os-issue-tracker#2298]
Since dialer is deprecated by AOSP, GrapheneOS is now more free to implement customizations to the dialer without needing to follow the upstream implementation.

Some time ago, SIP calling was removed from the dialer by AOSP upstream. It would be nice to have this feature returned to the dialer.

**Comment by flawedworld** [comment]
This is not feasible, the APIs in the OS are deprecated and are going to be removed.

**Comment by thestinger** [comment]
You should use a SIP calling app.
