### ISSUE TITLE
Allow for colour tinting

### ISSUE THREAD

**Issue by RustoMCSpit** [GrapheneOS/os-issue-tracker#2300]
We can already invert colours and correct for certain colour blind conditions but I'd like to see this expanded to being able to colour tint to any hex decimal and to any percentage tinting.

Sidenote: not sure if this is the correct repo, apologies

**Comment by thestinger** [comment]
You can use an accessibility service for this. It will have performance overhead compared to the OS implementation but I don't really think we're going to implement this. If it was implemented in Android, we would have it in GrapheneOS.

**Comment by RustoMCSpit** [comment]
> You can use an accessibility service for this. It will have performance overhead compared to the OS implementation but I don't really think we're going to implement this. If it was implemented in Android, we would have it in GrapheneOS.

What repo would this be then for Android? I'm very new to this coding stuff and I struggle to get my head around it apologies
