### ISSUE TITLE
Add an option to invert 3 button navigation bar

### ISSUE THREAD

**Issue by artekote** [GrapheneOS/os-issue-tracker#2301]
Currently there is no method to invert the 3 button navigation so that the "back" button is on the right side and the "recent" button on the left side.
![grafik](https://github.com/GrapheneOS/os-issue-tracker/assets/35179608/1a82891c-c821-4df2-a92c-c68073adeaf5)

**Comment by thestinger** [comment]
We strongly recommend using gesture navigation. We have a guide at https://grapheneos.org/usage#gesture-navigation. It has a lot of advantages including making the action quicker and saving screen real estate. It also has additional functionality such as swiping between recent apps without using the recent apps screen. We have no plan to make changes to 3 button navigation, which is mainly still around as an accessibility feature for people who can't use gestures.
