### ISSUE TITLE
Blocket app unable to show location

### ISSUE THREAD

**Issue by LupitaRose** [GrapheneOS/os-issue-tracker#2302]
The main app in Sweden for second-hand anything is Blocket, and for the almost two years I've only had a GOS phone the function to see where an item is has been impossible to use cos it won't work, for some reason. It works on all the other Androids I've tried tho. 

The app is using the Google Maps API to open up the location within it's own app apparently, but I cannot get it working on GOS. I had a thread on the discussion forum about it (https://discuss.grapheneos.org/d/5953-blocket-unable-to-get-location) and someone there pointed out I could post the issue here, so here I go, I got the Sandboxed Google Play services set up like it's described in the manual on the website, and the location rerouting disabled even. 

Should maybe mention I actually succeeded in getting a location 2-3 times out of thousands of tries. I have no problem getting a location lock, nor opening any Google Maps links otherwise. Would really be handy to have this work! Thanks!

**Comment by thestinger** [comment]
Do you have Network disabled for Play Store or Play services? Did you remove Play Store?

Disabling location rerouting without doing more than that will break location detection. You should turn rerouting back on unless you want to use Google network location and do all the steps in https://grapheneos.org/usage#sandboxed-google-play-configuration for that.

**Comment by LupitaRose** [comment]
Thanks! Done the steps like in the configuration you're pointing out, even tried to enable the rerouting and revoke Play Services location permission, but I put things back like it's described in the usage description for Sandboxed Google Play after that cos that didn't make anything better.

**Comment by thestinger** [comment]
The usage description is for the option of using network-based location. If you want to use their network-based location, you should do it, otherwise you should have it at the default (rerouting enabled).

**Comment by LupitaRose** [comment]
Hm, not sure I'm in the loop now, so the Blocket app opening/showing a location in Google Maps in their own app, or in-app browser, or what it is, is not dependent on any of the two choices of having rerouting enabled or disabled?

**Comment by thestinger** [comment]
It's not directly related to that. Location rerouting is about whether location requests from apps to Google Play services are sent to Google Play services or whether the OS handles them via GmsCompat. By default, we handle them via GmsCompat, which means it works without Location permission granted to Google Play. If you disable rerouting, then Google Play services needs location access. It doesn't really accomplish anything unless you also enable network location (location accuracy toggle) in the Google Play services settings and also give the Nearby devices permission.

**Comment by LupitaRose** [comment]
Thanks, I think I got that, would you be so kind to try to open a location link yourself? It's this app https://play.google.com/store/apps/details?id=se.appcorn.Blocket

The moderator for the GOS Forum tried and didn't succeed anyway. Thanks!

**Comment by muhomorr** [comment]
Blocket app uses geocoding API to transform location description (eg street address) into coordinates:
https://developer.android.com/reference/android/location/Geocoder

This API is not supported on GrapheneOS (there's no backend for it).

**Comment by thestinger** [comment]
This is one of the things we need to implement. See https://github.com/GrapheneOS/os-issue-tracker/issues/23
