### ISSUE TITLE
Add a copy paste feature that only one app can access

### ISSUE THREAD

**Issue by RustoMCSpit** [GrapheneOS/os-issue-tracker#2305]
As copy and paste logs are shared between apps, I think it would be useful to have a copy paste that only one app can see. Not sure how this would work yet, maybe the copy paste logs get erased upon first usage or maybe the next opened app can only see it or maybe you select an app that can only see it. Regardless, extremely confidential info is at risk and I think this warrants extra protection

**Comment by thestinger** [comment]
See https://github.com/GrapheneOS/os-issue-tracker/issues/347.

**Comment by RustoMCSpit** [comment]
> See #347.

Does this mean any website I visit can see my copy paste logs or just Vanadium?

**Comment by thestinger** [comment]
Websites can't read the clipboard without explicit consent within the browser. It's not connected to this.
