### ISSUE TITLE
Navigation bar button inversion

### ISSUE THREAD

**Issue by TheLoneDev** [GrapheneOS/os-issue-tracker#2307]
Make an option to invert the 3-button navigation bar to be like in Samsung devices where the back button is on the right and the recents on the left. For me, it makes much more sense (Since the back button is used more often).

**Comment by TheLoneDev** [comment]
Made two relevant PRs.
Tested on SDK_PHONE_x86, seemed to work fine.
Please let me know if there are any issues with the code

**Comment by thestinger** [comment]
I don't really think we want to do this. The expectation is for people to use gesture navigation.

**Comment by OrginalS** [comment]
Please add this, the hardest part of switching to grapheneOS for me besides having no folders in the app drawer was getting used to the button layout and I hate gesture navigation.

**Comment by TheLoneDev** [comment]
> I don't really think we want to do this. The expectation is for people to use gesture navigation.

Well.. it's your project.
I'd like to see such feature, but if the answer is no, then I guess you can close it.

**Comment by robcle** [comment]
The three button navigation is being phased out slowly. I like the gestures better once I started using them more.

**Comment by thestinger** [comment]
There's a major downside to adding every feature. It takes the place of a privacy or security feature. We can only maintain and port forward a limited amount of code.

**Comment by TheLoneDev** [comment]
> There's a major downside to adding every feature. It takes the place of a privacy or security feature. We can only maintain and port forward a limited amount of code.

I don't mind maintaining it.
But if you are saying it doesn't fit the project, I guess you can close the issue and PRs.

**Comment by vaiium** [comment]
> I don't really think we want to do this. The expectation is for people to use gesture navigation.

My person, some of us do. Don't assume what other people want.

**Comment by blur231** [comment]
Imagination is also an education ;)

**Comment by please-knock** [comment]
The way how gesture navigation works on android is very inefficient and lacks user experience. The legacy version is more simple and efficient, and will be more better if the buttons are inverted. Even if this is a subjective opinion, I don't see a reason why GrapheneOS would recommend Gesture navigation anyways. Is it somehow more secure than the 3-button navigation bar?

**Comment by vaiium** [comment]
> The way how gesture navigation works on android is very inefficient and lacks user experience. The legacy version is more simple and efficient, and will be more better if the buttons are inverted. Even if this is a subjective opinion, I don't see a reason why GrapheneOS would recommend Gesture navigation anyways. Is it somehow more secure than the 3-button navigation bar?

THANK YOU! 

Ya'll wanna be like: we want to be user based, but also: "this specific method I think is more efficient should be the way"? you might as well change your name to "Musk OS" 

I will always and forever hate gestures, and you're not giving me the option.

It's the same reason i will never ever buy a pixel again. I can't choose. 

If your option also is: "not giving me choice", why is this OS even a thing?
