### ISSUE TITLE
Contact Fairphone outlining what they need to implement in order to be suitable for GrapheneOS

### ISSUE THREAD

**Issue by RustoMCSpit** [GrapheneOS/os-issue-tracker#2309]
I, along with everyone who uses GrapheneOS, don't trust Google. (I also find them to be immensely unethical.) Here's the thing, they may become an enemy of gOS or intentionally drop some desired feature(s) in the future for gOS, it is thus important to prepare now before that doomsday occurs and hell breaks loose for gOS and to get in contact with a more trusted and ethical phone company. **I am not asking you to add support for Fairphone** yet, I know this project needs extra funding to do that, I am saying to ensure Fairphone has the desired features in the future by getting in contact now in case down the line gOS needs to swap fast because of Google. I am requesting you to contact Fairphone, you know gOS best after all (maybe they could become a funder for gOS in return for help securing their phones?). TL;DR - Ensure gOS has a viable alternative now to counter a hostile Google down the line, have a convenient safe alternative that is ethical and cares about the consumer. Have a great day regardless. Sorry for the long paragraph.

https://www.fairphone.com/en/about/contact-us/?ref=footer

**Comment by flawedworld** [comment]
FairPhone has demonstrated clear negligence around the security of their customers by misleading them how long they are providing security patches for, and by literally signing their OS with public signing keys. We'd rather not work with a company who misleads consumers and can't get the basics done.

**Comment by RustoMCSpit** [comment]
> FairPhone has demonstrated clear negligence around the security of their customers by misleading them how long they are providing security patches for, and by literally signing their OS with public AOSP test signing keys. We'd rather not work with a company who misleads consumers and can't get the basics done.

Thank you for this I had no idea, I apologise for the suggestion

**Comment by RustoMCSpit** [comment]
> FairPhone has demonstrated clear negligence around the security of their customers by misleading them how long they are providing security patches for, and by literally signing their OS with public AOSP test signing keys. We'd rather not work with a company who misleads consumers and can't get the basics done.

Curious, thoughts on this https://arstechnica.com/gadgets/2023/07/fairphone-3-gets-seven-years-of-updates-besting-every-other-android-oem/?utm_brand=arstechnica&utm_social-type=owned&utm_source=mastodon&utm_medium=social

**Comment by thestinger** [comment]
It's misinformation.
