### ISSUE TITLE
Custom App Permissions not working

### ISSUE THREAD

**Issue by cyruscook** [GrapheneOS/os-issue-tracker#2318]
Hello,

I'm encountering an issue when trying to use the TLS decryption feature of PCAPdroid on GrapheneOS.

This feature involves a seperate APK (PCAPdroid mitm/`com.pcapdroid.mitm`) which is controlled by the main PCAPdroid app (PCAPdroid/`com.emanuelef.remote_capture`).
To manage control, PCAPdroid mitm defines a custom permission (https://developer.android.com/guide/topics/permissions/defining) `com.pcapdroid.permission.MITM` (https://github.com/emanuele-f/PCAPdroid-mitm/blob/21327d7d7768858d7dcf2729f52888bba7bf84d1/app/src/main/AndroidManifest.xml#L12-L18).

PCAPdroid declares it requires this permission in it's manifest (https://github.com/emanuele-f/PCAPdroid/blob/efa982c2c65c4fef60adcf47fa315c3b014e8608/app/src/main/AndroidManifest.xml#L14).
During the TLS decryption setup it requests this permission (https://github.com/emanuele-f/PCAPdroid/blob/efa982c2c65c4fef60adcf47fa315c3b014e8608/app/src/main/java/com/emanuelef/remote_capture/fragments/mitmwizard/GrantPermission.java#L64C17-L64C17), however this seems to throw an exception (unfortunately there is no proper handling so I do not have any details of the exception) and the process fails.

I have checked the "All Permissions" menu of both PCAPdroid and PCAPdroid mitm and neither show the `com.pcapdroid.permission.MITM` permission, so I am guessing this must be an error with GrapheneOS not supporting custom permissions?

Thank You

**Comment by thestinger** [comment]
App-defined permissions work fine on GrapheneOS.

**Comment by cyruscook** [comment]
Thanks @thestinger , could you clarify whether custom app permissions should be showing in the "All Permissions" menu?

**Comment by thestinger** [comment]
It will show up there, but this is a dangerous permission and it will show up as a toggle.

**Comment by cyruscook** [comment]
I think there is a problem then, as it is not showing up in the permissions menu, as a toggle or otherwise.

Do you have any ideas for how I could debug why it wouldn't be showing up?

I imagine it not showing up there is why when the app asks for the permission an exception is raised.

**Comment by thestinger** [comment]
Something wrong with how the app was built or the order you installed them. You have to install the app defining the permission before the one using it.

**Comment by cyruscook** [comment]
Ah - that makes a lot of sense! I will test that out.
Thanks for the help :)

**Comment by emanuele-f** [comment]
Hi @thestinger, this is the first time I hear about this limitation. I've always installed PCAPdroid (the app requiring the permission) before the mitm addon (the app declaring the permission) without any issue.
Is this specific of Graphene OS?

**Comment by thestinger** [comment]
No, it's in no way specific to GrapheneOS.
