### ISSUE TITLE
Haptics stops working after dropped cell reception

### ISSUE THREAD

**Issue by ZethiaZ** [GrapheneOS/os-issue-tracker#2319]
I recently discovered my haptics stopped working while on vacation in a rural area. I restarted my device and the issue occurred against the next time I lost cell service (haptics do not work once the phone reconnects to cell service).

I have not modified any Haptics related settings than I can recall, and upon checking settings do not see anything that would cause the behavior.

I attempted disabling and re-enabling haptics but that did not fix it. Only restarting my phone has fixed it.

Issue is occurring on my pixel 6a.

**Comment by thestinger** [comment]
It's not reproducible and is likely a hardware issue. It's definitely not related to cell service.
