### ISSUE TITLE
Work apps notifications aren't forwarded when the option is enabled

### ISSUE THREAD

**Issue by io43** [GrapheneOS/os-issue-tracker#2322]
When you receive a notification from work apps, have the forward notification feature on and using a secondary profile they aren't forwarded. Can anything be done to get it working?
 

- Enable Notification forwarding in main profile.
- Go to a secondary profile
- Receive a notification from an app in work apps from main profile
- It never get forwarded to your secondary profile so you are missing notifications

thanks

**Comment by empratyush** [comment]
Work profile and main profile [are not the same](https://support.google.com/work/android/answer/9563584). forwaring notification from work profile is currently unsupported.
