### ISSUE TITLE
Mock GPS location not working with last OTA

### ISSUE THREAD

**Issue by ConceptzX** [GrapheneOS/os-issue-tracker#2326]
My phone (pixel 6 pro) updated OTA the other night and my mock GPS location apps no longer work.  The apps seem to just revert to the last valid location from the phone GPS instead of recognizing the mock location.

**Comment by ConceptzX** [comment]
Tinder and bumble for starters. I haven't tried too many other apps where the mock location caused a conflict. 

⁣Get BlueMail for Android ​

**Comment by ConceptzX** [comment]
Sorry about 
https://play.google.com/store/apps/details?id=com.rosteam.gpsemulator 

https://play.google.com/store/apps/details?id=location.changer.fake.gps.spoof.emulator

**Comment by thestinger** [comment]
Not able to reproduce. Do you have the dependencies for the apps? Many of them depend on Google Play. You'll need to provide more details.
