### ISSUE TITLE
Planet Fitness (PFMobile) app stuck on loading screen

### ISSUE THREAD

**Issue by Slyfox88** [GrapheneOS/os-issue-tracker#2327]
Stuck on loading/logo screen. Sandboxed Google Play and associated services installed. I also tried on LineageOS with microG and was able to get past the loading/logo screen but got a popup saying something went wrong check that google play is installed and up to date. Since an actually version a google player services is installed on GrapheneOS sandbox I shouldn't be having any issue. GrapheneOS, Android 13, Stable channel, Google Play Services v23.22.15

**Comment by muhomorr** [comment]
Unable to reproduce this issue.

You refer to this app, correct? https://play.google.com/store/apps/details?id=com.planetfitness

Have you installed it through Play Store?

**Comment by Slyfox88** [comment]
Yes, I used Aurora Store to install it. I uninstalled and reinstated it as well and same issue.

**Comment by thestinger** [comment]
@Slyfox88 You're likely using Aurora Store's broken native installer mode. Install it with either the Session installer mode or through the sandboxed Play Store. Installing it from Aurora Store makes it an Aurora Store support issue unless you have a reason to think otherwise.

**Comment by Slyfox88** [comment]
Installation method for Aurora is on 'Session installer'.

**Comment by thestinger** [comment]
Try installing it from the sandboxed Play Store instead. Some apps depend on Play Feature Delivery or Play Asset Delivery. Not every app can be installed via Aurora Store.
