### ISSUE TITLE
Failed download in Vanadium leaves zero byte file in Files app

### ISSUE THREAD

**Issue by khemarachuon** [GrapheneOS/os-issue-tracker#2329]
Tried to download a file in Vanadium, but the download failed and left a zero byte file in the Downloads category of the Files app that can't be deleted. Subsequent successful downloads of the same initial file have a non-zero file size and can be deleted as expected.

Debugging steps:
1. Tried to delete the zero byte file in Files app. A toast appeared stating that it was deleting 1 file, but the zero byte file remained.
2. Tried clearing `Storage & Cache` of Vanadium and Files apps, but the zero byte file remained.
3. Tried viewing the `/storage/emulated/0/Download/` directory in the Amaze file browser and did not see the zero byte file.
4. Tried viewing the `/Android/data/app.vanadium.browser/files/Download/` directory, but did not see any files.

Found this closed issue that exactly matches this problem and was advised to open a new issue: https://github.com/GrapheneOS/os-issue-tracker/issues/1949

Hardware:
- Pixel 7 Pro

Software Versions:
- GrapheneOS 2023071100
- Vanandium 115.0.5790.85.0
- Files 13
- Amaze 3.8.4

**Comment by flawedworld** [comment]
This is an AOSP bug, it will eventually disappear.

**Comment by khemarachuon** [comment]
UPDATE: 5 days later the zero byte files did disappear on their own
