### ISSUE TITLE
initial login via fingerprint on secondary profile not working

### ISSUE THREAD

**Issue by mikrocon** [GrapheneOS/os-issue-tracker#2331]
When switching from main to secondary profile I'm not able to log in using my fingerprint. Instead I need to type the PIN. 
As long as I stay within the secondary profile and switch the display off an on again the login via fingerprint works as expected.
Switching back to the main profile works as well, no PIN needed.

Phone restart, disable/enable fingerprint and deleting/adding new fingerprint within the secondary profile did not help. 

Even a new user (third one in this case) has to type the PIN in although fingerprint has been enabled before (same as with the secondary user).

Pixel 4a5g
TQ3A.230705.001.2023071100

**Comment by natert** [comment]
You need to "allow running in the background" for that profile, from within the owner profile.

**Comment by mikrocon** [comment]
You are so right ... I don't remember why and when I've been switching this off.
Apologies for this unnecessary ticket.

**Comment by mikrocon** [comment]
Definitely a user error, sorry for that.
