### ISSUE TITLE
T-Mobile

### ISSUE THREAD

**Issue by pabogan** [GrapheneOS/os-issue-tracker#2335]
Yesterday I switched from AT&T to T-mobile on my Pixel 6 pro running latest graphene OS.  Now I am not able to receive data on the phone.  I can receive calls and text messages, just no data.  Open Vanadium and type in Google, it times out and tells me to check the connection.  All other searches do the same.  Before using AT&T I had no issues with data on the phone.

**Comment by thestinger** [comment]
You need to use https://discuss.grapheneos.org/.

**Comment by pabogan** [comment]
SOLVED:  Ok.  Added a new APN and under APN Type I set it to:  default, supl, internet+mms      The default T-Mobile APN for APN type was set to:  default, supl, mms without internet.   Seems to be working just fine now.  Fingers crossed.

Thanks for your help !!!!
