### ISSUE TITLE
Lockscreen Issues with Pixel 4 after June/July updates

### ISSUE THREAD

**Issue by EmmJSee** [GrapheneOS/os-issue-tracker#2336]
Hello.
I am now having issues with lockscreen since the latest round of updates. 

The issues can be broken down into the following:
 
_**Lockscreen either doesn't unlock*, or instantly locks once it has unlocked.**_  

*Face unlock and accessing the keypad to enter a pin are often impossible. Leaving the phone for a minute is a workaround, though not convenient. 

- Face unlock now usually doesn't work on addition profiles (though it did before)

Thanks
M.

**Comment by thestinger** [comment]
The issues you're describing are unclear and can't be replicated. It's likely a configuration issue with the device. Pixel 4 has also been end-of-life since after October 2022 and only has semi-official support via extended support releases.
