### ISSUE TITLE
screen recordings titled 'movies' in gallery

### ISSUE THREAD

**Issue by RustoMCSpit** [GrapheneOS/os-issue-tracker#2340]

**Comment by treequell** [comment]
That's expected. Movies is the name of the folder where videos get saved on your device. You can find the contents of that folder also by opening the Files app > Main menu (3 lines) > Pixel X > Movies. When you screen record, the videos automatically get saved in the Movies folder.

An exception would be videos you capture with your Camera app. Those are usually saved in the DCIM folder by default instead.
