### ISSUE TITLE
[Feature] Option to disable call recording button

### ISSUE THREAD

**Issue by wasabi-avalanches** [GrapheneOS/os-issue-tracker#2342]
In my line of work I am on the phone all day - which is all above board - however the second I record a phone conversation using my phone I am in serious deep water. The call recording button is way too conveniently placed on the dialler screen to completely rule out me never accidentally touching it. It would be great if I could permanently disable this in the system settings somewhere.

My threat model is someone in a very similar situation to me who did this (albeit intentionally) lost several of their liberties and is facing a years-long legal battle. Realistically, it's unlikely it would ever be discovered that I recorded a call accidentally; in saying that I'm not willing to find out.

**Comment by robcle** [comment]
Not really a security issue, but a privacy one. This may be a good first issue. I'm not sure how hard it would be for the devs to implement a toggle in the dialer app maybe.

**Comment by thestinger** [comment]
There are too many requests for extensions of this feature. I don't think we're going to do this.
