### ISSUE TITLE
SeedVault - Developers biggest crime/joke against end users

### ISSUE THREAD

**Issue by n3rdcub** [GrapheneOS/os-issue-tracker#2347]
Straight Honest question should easily warrant a straight honest answer; am I doing something insanely wrong or is this the most useless backup utility in the history of ever?

Restoring apps maybe restored 5-10, the other 160 I had to download from Play Store.
_Dont worry!_ the guided process says _after install your app data will then be restored_ ok cool let's see
The app forgot it was on step 2 when I came back from play Store, and **it began restoring from step 1 all over again**
After 15 crashes and restarts like this finally, FINALLY I can move to step 3. 
**no data found to restore**

# then why is the seedvault folder over 50gb? Where is my app data, settings, and device files? Why does this feel like something I could have done with pen and paper since I spent majority of my time the last **_12 hours_** in play store? Why am I downloading the app when I thought this was an app & device backup tool not a pointer service

**Comment by thestinger** [comment]
https://grapheneos.org/releases#2023020600

> Seedvault: update to latest revision (we plan on replacing this with a new backup implementation since Seedvault is buggy/unreliable, has consistently needed security fixes applied downstream, has failed to provide the originally planned core features and despite being initially created by a GrapheneOS community member for GrapheneOS was taken over by a group hostile towards it)

**Comment by thestinger** [comment]
We know it's a terrible app and we plan to replace it with our own in the future when we have a developer or two we can assign to working on it. There are much higher priorities. There's no reason that the standard Android backup infrastructure cannot be used to back up the vast majority of app data. Seedvault simply doesn't know how to properly use the Android backup infrastructure.

**Comment by thestinger** [comment]
Please submit any complaints you have about Seedvault to the Seedvault project, not here.

**Comment by n3rdcub** [comment]
> https://grapheneos.org/releases#2023020600
> 
> > Seedvault: update to latest revision (we plan on replacing this with a new backup implementation since Seedvault is buggy/unreliable, has consistently needed security fixes applied downstream, has failed to provide the originally planned core features and despite being initially created by a GrapheneOS community member for GrapheneOS was taken over by a group hostile towards it)

Buggy implies it can be fixed. Unreliable implies it sometimes works.
Correct me if I'm wrong but in the 12 hours I've tried to just get through step 2 this is nothing more than a glorified "Hey go 'restore' your apps play store. Ur welcome"

**Comment by n3rdcub** [comment]
> We know it's a terrible app and we plan to replace it with our own in the future when we have a developer or two we can assign to working on it. There are much higher priorities. There's no reason that the standard Android backup infrastructure cannot be used to back up the vast majority of app data. Seedvault simply doesn't know how to properly use the Android backup infrastructure.

This is branded and touted as the best degoogled os, and the current best and top rated suggestion for device backup and restore is to use Google one and hand my data to them on a silver platter?

**Comment by n3rdcub** [comment]
> Please submit any complaints you have about Seedvault to the Seedvault project, not here.

Maybe they sent me here since this is strictly related to GoSs implementation

**Comment by thestinger** [comment]
> degoogled os

GrapheneOS has never used the term "degoogled" ourselves. AOSP doesn't have Google apps, and that's what GrapheneOS is based on.

> top rated suggestion for device backup and restore is to use Google one and hand my data to them on a silver platter

You can't use Google's backup service on GrapheneOS. Not sure what you're talking about.

> Maybe they sent me here since this is strictly related to GoSs implementation

It has nothing to do with GrapheneOS. The developers of Seedvault are unfortunately both highly competent and dishonest. They've participated in an extreme harassment campaign against our developers. They're obviously going to go out of the way to mislead people and pretend these aren't issues with Seedvault. GrapheneOS has not made any significant change to Seedvault and has an up-to-date revision of it. Get support from Seedvault for Seedvault. It's not a GrapheneOS app.
