### ISSUE TITLE
Clarify third party app installation

### ISSUE THREAD

**Issue by robcle** [GrapheneOS/os-issue-tracker#2350]
If secondary profile is created and the permission slider 
"Allow installing apps from third party sources" in owner is deselected, the permission to install apps in secondary profile ->  settings for the play store is greyed out. It would be more UI friendly to label the play store as an third party source more directly if that is the intent of the devs. 

IMO if a user is trusting the play store in a secondary profile, then the user should be able to deselect the permission in owner, so that the play store in secondary can install apps. The current description of the permission slider in owner suggests to me that the play store in secondary can install apps but not third party stores like aurora. If the devs intend for it to be that way it should be included in the descriptions of the owner slider, and in secondary profile play store allow app installation. It should say "Third party apps including the Play Store"

**Comment by thestinger** [comment]
Improving the wording is planned but we don't want a special case for this.

**Comment by robcle** [comment]
I'm sorry for posting this here then. Sorry to bug you, i appreciate all that the GOS team does. Where would I put something like this next time? The matrix chat?  The mods always seems to turn down anything I say lol

**Comment by thestinger** [comment]
You can see the current work on this at https://github.com/GrapheneOS/platform_packages_apps_Settings/pull/182.

**Comment by robcle** [comment]
Oh, I see. Sorry for being blind lol.
Anyway I appreciate what you and the team have done and I will read next time before I submit a new issue. That matchbox guy is a really good mod btw.
