### ISSUE TITLE
GrapheneOS Keyboard: Deleting in Jetpack Compose TextField deletes previous spaces

### ISSUE THREAD

**Issue by soupslurpr** [GrapheneOS/os-issue-tracker#2352]
When typing in a Jetpack Compose TextField, deleting characters makes spaces get deleted even if they aren't reached yet. This seems to be an AOSP keyboard bug and does not happen on other keyboards.

https://github.com/GrapheneOS/os-issue-tracker/assets/92235850/cc48084d-0c02-4074-a57c-2c36c0f1a7ee

**Comment by thestinger** [comment]
They need to fix this, not us.

**Comment by onehalf3570** [comment]
The issue is still there. Does anyone know the upstream bug id perhaps? UPD: here it is https://issuetracker.google.com/issues/221636606?pli=1

**Comment by thestinger** [comment]
It's an Android Compose TextField bug and we can't fix that for them. We implemented a workaround which does avoid it triggering in practice. There hasn't been a new OS release since it was resolved yet.
