### ISSUE TITLE
GrapheneOS Keyboard: Cursor jumping and overwriting text in Jetpack Compose TextField

### ISSUE THREAD

**Issue by soupslurpr** [GrapheneOS/os-issue-tracker#2353]
When typing in a Jetpack Compose TextField, sometimes the cursor jumps around and overwrites lines when tapping and typing. This seems to be an AOSP keyboard bug and does not happen on other keyboards.

https://github.com/GrapheneOS/os-issue-tracker/assets/92235850/e324b6d3-c07b-4f63-ad6e-33d8c69259e7

**Comment by thestinger** [comment]
It's a Jetpack Compose bug. It being incompatible with AOSP keyboard (Android's reference keyboard) is their issue to fix.
