### ISSUE TITLE
User switching ends user session

### ISSUE THREAD

**Issue by Niko4u5** [GrapheneOS/os-issue-tracker#2355]
Edit: 
When in a second profile and the display size is set to the maximum this bug happens.
While locked swiping down to switch users the user icon exits the current session.

Old:
Sometimes when taping the user switching button in the quick settings the current session is ended.
It should show the menu to switch to a specific user.

I don't have a way to consistently reproduce it.

**Comment by Niko4u5** [comment]
It seams to happen every time i try to switch user without unlocking the current profile first

**Comment by natert** [comment]
This happens with "Allow running in background" enabled?

**Comment by Niko4u5** [comment]
Yes

**Comment by Niko4u5** [comment]
I think it registers a tap in the end session button which is in the same position but not visible in the quick settings

**Comment by treequell** [comment]
I wonder if the issue you describe is related to this one: https://github.com/GrapheneOS/os-issue-tracker/issues/2053 ?

**Comment by Niko4u5** [comment]
Looks linke it
