### ISSUE TITLE
Bubble conversation forgets its position on going home

### ISSUE THREAD

**Issue by stepech** [GrapheneOS/os-issue-tracker#2361]
Pixel 6 Pro - TQ3A.230705.001.2023072600

When using bubble conversations you can close the bubble by
- swiping back
- tapping the bubble
- swiping home from the bottom screen

the first two place the bubble back where it was before opening, but swiping home places it at the top of the screen (tested with Signal conversation, nothing else tested) which is especially on larger screens very inconvenient.

**Comment by thestinger** [comment]
It's an upstream issue. These need to be tracked in the Android issue tracker.
