### ISSUE TITLE
Apps restart whenever Work Profile is unpaused. (Shelter)

### ISSUE THREAD

**Issue by easesoft56485** [GrapheneOS/os-issue-tracker#2362]
Issue: For over 2 months, apps in main and work profile restart when I switch back and forth between them only when work profile is unpaused.  

What I've tried
-Factory Reset (did not change ANY dev. Options)
-Insular (same thing happens)

No I have not changed any other settings except have apps ask me to use Sensors. Which I’ve tried to see if that was the issue by allowing apps by default to access sensors and it wasn’t. 

I have contacted PeterCxy from Shelter who believes it is a problem with Android or GOS. I believe it is a problem with GOS because this does not happen in CalyxOS. 

I can't really seem to replicate it on my 2nd phone which is a Pixel 4 XL running GOS. Apps do close on my 4 XL but I am able to go back and forth between 4 maybe 5 apps that are running in both the main profile and work profile with out them restarting. After a certain number of opened apps, likely past 5 or 6 apps. Then other apps begin to restart when I switch back. I believe that is Standard and normal. I could be wrong. If I am then it is not as severe on my 4XL than my 6A.  

![signal-2023-07-30-105811](https://github.com/GrapheneOS/os-issue-tracker/assets/100045204/2d3246a0-b1aa-4462-96d7-81db12d314b5)

Here is a video demonstrating apps restarting with only Element and two browsers running. Apps are from the Main owner profile.

https://github.com/GrapheneOS/os-issue-tracker/assets/100045204/99e8ac10-3621-4d05-9a15-98455d977038

Please help, I do not want to go back to CalyxOS for my everyday device. 

Thank you!

**Comment by thestinger** [comment]
This isn't a GrapheneOS issue. Promoting CalyxOS here this way will result in a ban from the issue tracker.
