### ISSUE TITLE
SeedVault have gotten into a bad state

### ISSUE THREAD

**Issue by Andrewngabriel** [GrapheneOS/os-issue-tracker#2363]
I enabled SeedVault recently and set the backup target to be my phone in order to try it out initially. After a few days of using the phone, I observed one day that it was quiet slow and unresponsive. When I went into settings -> storage I noticed that a large portion of storage was being eaten up by documents & other. After some research and troubleshooting, it became clear to me that this was likely taken up by SeedVault backup files. At this point, I plugged my phone in the computer and used Android File Transfer to remove the SeedVault files which took up most of the space. Then I went into settings to disable SeedVault from backing up the device.

Ever since this incident happened, I think SeedVault have gotten into a bad state where I'm no longer able to see the same prompt to backup the device on a USB drive or external service. I've attached screenshots below showing the prompt I'm seeing for reference. I tried clearing app data & cache to see if it would resolve this problem but it did not help.

Happy to provide additional logs or information to help troubleshoot further.

![signal-2023-07-30-001556](https://github.com/GrapheneOS/os-issue-tracker/assets/11186948/c8eefec7-9296-4cff-abb9-e0f052f89a08)

![signal-2023-07-30-001546](https://github.com/GrapheneOS/os-issue-tracker/assets/11186948/a7a9d0e1-08e4-44ec-ac87-e771e1907fe2)

**Comment by thestinger** [comment]
Please go to Settings -> Apps, show system apps, search for Seedvault and clear the app data. We know Seedvault is quite buggy and plan to replace it. It has a separate issue tracker but the people who took over development are highly hostile towards GrapheneOS to the point they engage in an extreme harassment campaign and won't accept issue reports about the app if they know it's from a GrapheneOS user.
