### ISSUE TITLE
Make notification and ring volumes separate.

### ISSUE THREAD

**Issue by OfficialMuffin** [GrapheneOS/os-issue-tracker#2365]
Just one of my preferences to have the ring and notification volumes separate. 
I don't want to have to turn down the notification volume as well as having to turn the ring volume down also.

Is there a workaround for this?

**Comment by thestinger** [comment]
Having them together is how it works in Android and we aren't going to make invasive changes to split it. It's not what we work on.

**Comment by OfficialMuffin** [comment]
New Android 14 update confirms they have separated the ring and notification volumes are separate. Finally!!!
