### ISSUE TITLE
"Mobile data" option was turned off (Pixel 6a)

### ISSUE THREAD

**Issue by QuestioningEspecialy** [GrapheneOS/os-issue-tracker#2370]
Just wanna say real quick that the "Mobile data" option was turned off today and either I did so accidentally while touching the screen without being aware (unlikely), did it in my sleep (possible), or there was a bug of some sort. First time noticing this and restarting the phone didn't resolve the issue. Had to navigate to "Mobile data" and enable it.
I install the OS updates as they come and Google's when I feel like I have to.

Android v13
Apps v20
Auditor v74
Google Play services v23.22.15

**Comment by thestinger** [comment]
No indication of this being a bug.

> and Google's when I feel like I have to

Are you talking about sandboxed Google Play? Those are regular sandboxed apps and entirely unrelated to this.
