### ISSUE TITLE
Cannot install any app from the Play Store

### ISSUE THREAD

**Issue by francesco-p** [GrapheneOS/os-issue-tracker#2373]
# Bug

Whenever I try to install an app from play store, the download of the files goes smoothly but I don't receive the confirm popup to complete the action. 

# video
https://drive.google.com/file/d/1kkVIm7zxVV3tBS47VQbHYFk30m-B2wrt/view?usp=sharing

# os version
build version: TQ3A.230705.001.2023072600

# play store version

![services2](https://github.com/GrapheneOS/os-issue-tracker/assets/5663725/4a0fd428-b64a-4b17-b1da-699b1e6ee05c)

**Comment by muhomorr** [comment]
Unable to reproduce this issue. 

Is "Package Installer" system package enabled (`com.android.packageinstaller`)? Are you able to install APKs manually?

**Comment by oscarjimenezpro** [comment]
Same issue here: can't install or update apps on Google Play.
The download of the installation package seems to work, but then it gets stuck on "installing".

com.android.packageinstalle is enabled.
Manual installation of APKs through adb seems to work.

**Comment by muhomorr** [comment]
@oscarjimenezpro 
By manual installation of APKs I mean installing APKs through a file manager.
Do other app stores work?

**Comment by francesco-p** [comment]
after the update now works
