### ISSUE TITLE
Passthrough charging prevents OTG device from connecting.

### ISSUE THREAD

**Issue by Qenuwa** [GrapheneOS/os-issue-tracker#2375]
As per the discussion on the [forum](https://discuss.grapheneos.org/d/5667).

Uncertain whether this is a GOS or stock issue. 
The recent reply from Tealdragon (with a 6 and a 6a) would indicate that this is a GOS issue:
> Pass through worked on both and then stopped working once GOS was installed. 

I also have a 6a. I can't test stock as I only have this one phone, which I use as my daily driver. 

The replies to a related [Reddit post](https://www.reddit.com/r/Gamesir/comments/121i22y/) are most likely talking about stock. Pixels from the 4a to the 7 Pro are all mentioned.

**Comment by thestinger** [comment]
No reason to think this is a GrapheneOS issue right now.
