### ISSUE TITLE
phone app should display your phone number

### ISSUE THREAD

**Issue by RustoMCSpit** [GrapheneOS/os-issue-tracker#2376]

**Comment by flawedworld** [comment]
This sounds very easy but is a potentially massive pain to do, we won't be doing this.

**Comment by RustoMCSpit** [comment]
> This sounds very easy but is a potentially massive pain to do, we won't be doing this.

potentially? whats so tough

**Comment by thestinger** [comment]
You can obtain it in Settings.

**Comment by thestinger** [comment]
> > This sounds very easy but is a potentially massive pain to do, we won't be doing this.
> 
> potentially? whats so tough

It's not one the apps we built ourselves and we don't actively develop it.
