### ISSUE TITLE
make adaptive sleep resource match the stock OS for each device

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/os-issue-tracker#238]
Pull requests made by an account that is now deleted, so they can't respond to review:

* https://github.com/GrapheneOS/device_google_wahoo/pull/1 /
* https://github.com/GrapheneOS/device_google_crosshatch/pull/1
* https://github.com/GrapheneOS/device_google_bonito/pull/3 

It needs to be determined if this is used by the stock OS and for which devices. Pixel 4 will also need to be checked now. It would make sense to match the stock OS, but not to enable it if the stock OS doesn't do it. It also needs to be tested to make sure it's working properly.

**Comment by r3g-5z** [comment]
This functionality depends on the priv-app Android System Intelligence (Device Personalization) as you need to define the Attention service with `config_defaultAttentionService` as well.

`<string name="config_defaultAttentionService" translatable="false">com.google.android.as/com.google.android.apps.miphone.aiai.attention.service.AiAiAttentionService</string>`

We remove Android System Intelligence with adevtool.

See https://web.archive.org/web/20191004170424/https://twitter.com/MishaalRahman/status/1180164485262319616

This is only feasible/doable if we decide to ship Android System Intelligence.
