### ISSUE TITLE
Unknown tracker alert is non-functional

### ISSUE THREAD

**Issue by srappan** [GrapheneOS/os-issue-tracker#2380]
Currently trying to enable the Unknown tracker Alerts in Google Play Services, it's say Bluetooth needs to be enable, even when it already is. Pressing the "Turn On" causes Google play services to crash.

![Screenshot_20230811-232651](https://github.com/GrapheneOS/os-issue-tracker/assets/26847675/85c4be6d-95c8-4908-90b8-774638c9ee80)

**Comment by thestinger** [comment]
Try giving it background location access too. I doubt it will work without special support being implemented and that might be quite hard.

**Comment by srappan** [comment]
Figured it out!

Google Play Services requires "Nearby Devices" Permission. Importantly "Location" can stay completely disabled.

A little concerned on whether enabling that permission would decrease privacy in some way but unsure how so.
![Screenshot_20230812-100331](https://github.com/GrapheneOS/os-issue-tracker/assets/26847675/c689492f-2f14-4d2b-b89a-49ec16f4c2ac)
