### ISSUE TITLE
Wierd behavior when connecting to wifi - wont show up in saved networks

### ISSUE THREAD

**Issue by hovercats** [GrapheneOS/os-issue-tracker#2382]
Ive got this really wierd behavior with a network ive been connecting to recently.

Tldr; 
- no feedback in wifi menu when you connect to wifi (i.e. connecting, wrong passphrase and so on).
- network doesnt show up in saved network afterwards
- if I disabled wifi after connecting, it sometimes connect automatically, but seems to be mostly not.
- despite all of this, if you typed the correct passphrase, youd be connected to the network, but its only indicated by the icon on top of the screen

Pixel 4a
TQ3A.230805.001.2023080800

**Comment by thestinger** [comment]
Does not seem like an OS issue but rather the Wi-Fi AP not working properly.
