### ISSUE TITLE
Pixel 7a LAN communication: 100% packet loss

### ISSUE THREAD

**Issue by maschlr** [GrapheneOS/os-issue-tracker#2384]
I'm having issues communicating to devices in the LAN I'm connected to: I get 100% packet loss when trying to `ping` via a terminal emulator. Webinterfaces (e.g. Router or other HW like Starlink) are unreachable. 

I'm having no issues doing all that from another non-GrapheneOS Android or my Linux computer. 

I can access WAN from the GrapheneOS device (ping of IP addresses or url, normal communication via different protocols).

I can ping the GrapheneOS device from other devices. That doesn't work the other way around (100% packet loss).

Tried:
- different routers/networks: same result
- resetting the network on GrapheneOS
- using a static (device) MAC

**Comment by thestinger** [comment]
Are you using a VPN? Are you using Private DNS? This must be something about your configuration.
