### ISSUE TITLE
Proxy profile login 

### ISSUE THREAD

**Issue by Sai-Samuraij** [GrapheneOS/os-issue-tracker#2388]
It would be nice to be able to show something if pressured, but information stays hidden.

**Comment by thestinger** [comment]
There are existing issues about this but we can't keep them open without a viable design.

**Comment by thestinger** [comment]
Bear in mind you can already use a secondary user for sensitive data.

**Comment by Sai-Samuraij** [comment]
Do you mean I need to make better presentation or is there something else that makes it non viable?

**Comment by Sai-Samuraij** [comment]
Do you mean I need to make better presentation or is there something else that makes it non viable?

**Comment by thestinger** [comment]
There are things that make it non-viable. It's nearly impossible to hide that it exists and doing this in a flawed way is worse than not offering it.
