### ISSUE TITLE
Signal messenger randomly accessing location

### ISSUE THREAD

**Issue by DanBenHa** [GrapheneOS/os-issue-tracker#2395]
Related to https://github.com/signalapp/Signal-Android/issues/13105
They suggested that what I see might be a GrapheneOS issue, though I'm very doubtful about it. But maybe someone here has an idea:

> ### Bug description
> When I open Signal it queries location, even though I do not try to share location. (https://community.signalusers.org/t/randomly-accessing-location/55088)
> 
> ### Steps to reproduce
> - install signal via website APK in GrapheneOS 
> - grant location access
> - open the app
> - see location access label in top right corner
> 
> **Actual result:** Location queried even if not sharing
> **Expected result:** nothing
> 
> ### Device info
> 
> **Device:** Google Pixel 6 Pro
> **Android version:** Android 13 GrapheneOS TQ3A.230805.001.2023080800
> **Signal version:** Version 6.28.5
> 
> 
> org.thoughtcrime.securesms
> versionCode 131000
> 
> ### Link to debug log
> 
> https://debuglogs.org/android/6.28.5/86cab3d88a80d6dcbd1d9842911fa3a86391c6d09589817799624cb115bcb2fd

**Comment by thestinger** [comment]
It has nothing to do with GrapheneOS.

**Comment by thestinger** [comment]
It has nothing to do with GrapheneOS beyond the fact that we fully enable the location indicator and location permission history compared to Android 13 and 14 still not enabling it. They only have a developer option for **partially** enabling it.
