### ISSUE TITLE
Can't pay with norwegian card in Play Store or IAP

### ISSUE THREAD

**Issue by unchartedpopsicle** [GrapheneOS/os-issue-tracker#2396]
Online purchases in Norway require 2FA with BankID. When paying with a card online you generally get a choice between confirming with the BankID app, a bank-issued code generator, or the SIM-service "BankID på mobil". BankID på mobil has been superseded by the app, and is no longer issued by banks or transferred to new sim cards.
Play purchases on GrapheneOS default to BankID på mobil with no way of switching to active alternatives.

**Comment by thestinger** [comment]
Not clear what this has to do with GrapheneOS. It sounds like you just haven't installed what you need or granted the required permissions.

**Comment by unchartedpopsicle** [comment]
@thestinger The sandboxed play services demands the only version of BankID that can no longer be acquired. Generally payment services opens or embeds the BankID site where you can choose the version you use, but Google Play here seems to open its implementation of the defunct version.
I'd include a screenshot, but the payment screen does not allow it.

**Comment by unchartedpopsicle** [comment]
I searched around, and found that this is also a problem on vanilla Android. I did not even consider that Google might have had broken payments for the past 8 months! At least PayPal works.
Please disregard the issue.
