### ISSUE TITLE
VoIPstudio notifications greyed out

### ISSUE THREAD

**Issue by nturns** [GrapheneOS/os-issue-tracker#2398]
This VoIP app installed easily except it failed the final step. I had installed Google Play first. Then I went to the VoIPstudio website and installed the app and did the setup. The last test is to receive a call. A red banner appeared says "In order to receive incoming call alerts  please allow Notifications in VoIPstudio application."

In Settings -> Apps -> See all Apps -> VoIPstudio, the Notifications settings are set to "Off" and are listed separately above the settings for other Permissions. Inside Notifications it is greyed out and it says, "This app does not send notifications."

I did find a similar item here but it didn't help me.
https://discuss.grapheneos.org/d/1618-notification-not-working-anymore-for-different-apps/5

Also the info https://grapheneos.org/faq#notifications
is not clear what functionality installing the three packages for Google Play services is supposed to solve regarding notifications.

**Comment by thestinger** [comment]
This appears to be a buggy app targeting the latest Android release but not declaring the notification permission.

**Comment by thestinger** [comment]
> Also the info https://grapheneos.org/faq#notifications is not clear what functionality installing the three packages for Google Play services is supposed to solve regarding notifications.

It doesn't provide anything that directly has to do with notifications but rather many apps use Firebase Cloud Messaging for background push used to deliver the messages they send from their server to trigger notifications.

**Comment by nturns** [comment]
Thanks. I will copy to them the text of your reply, hoping they will fix it in the future. I have screened about 25 VoIP apps for those that provide a phone number and don't share my data. I tried about 6, and this is the only one that almost works.

I contacted them before I contacted you and this was their response,
--------------
Thank you for contacting our support.

Our app will not work with GraphineOS as we need Google push notification to "wake" the app up when a call comes in.

Please reinstall Android 13 to use our app on your Pixel 6a.
--------------

Then I replied that I had Google Play store installed, but there has not been a reply.

Garrick

**Comment by nturns** [comment]
I just got a reply from them. They said they are aware of that issue and it was caused by a recent security patch. A new version is due in a couple of weeks. Fingers crossed. Thanks for your help.

Garrick

**Comment by thestinger** [comment]
> Our app will not work with GraphineOS as we need Google push notification to "wake" the app up when a call comes in.

This is not correct since GrapheneOS supports sandboxed Google Play.

**Comment by nturns** [comment]
VoIP Studio has released version 1.8.2 and it works correctly with notifications when receiving a call. FYI there is also "VoIP Home." The only difference seems to be the pricing. Studio is a minimum monthly charge of $4.95, Home is pay as you go 1.4c a minute. Thanks again.

**Comment by thestinger** [comment]
Likely just an app bug on their end only occurring on Android 13.

**Comment by nturns** [comment]
Can you explain what app bug? Everything seems to be working now.

**Comment by thestinger** [comment]
They likely updated targetSdkVersion to 33 due to the deadline approaching but didn't actually test everything on Android 13 and hadn't declared/requested the notification permission introduced in Android 13. They probably just fixed that in the latest app version.

**Comment by nturns** [comment]
OK I agree. I've had to learn Java app development for one client who put the app on Google Play store. I know what you are talking about. I spent last weekend searching for a VoIP app that passed my requirements. Is there someplace one can review or add to a list an app that works on GraphineOS? Perhaps I might recommend it to the Aurora store?
