### ISSUE TITLE
Device id gets leaked to google play services between multiple users

### ISSUE THREAD

**Issue by amolpatravali97** [GrapheneOS/os-issue-tracker#2406]
Setup:

1. Pixel 4a
2. Sunfish GrapheneOS
3. Users on phone: Owner + User A + User B
4. Internet Connection: Phone connected to a 5G proxy server through ethernet connected to a laptop. Airplane mode-ON. Wifi, 
    Cellular & Bluetooth disabled. Unactivated US sim card inserted into the phone.
6. Owner profile has no google play services/store installed. Only User A & User B have google play services installed & I end user 
    session and enter into each user with a new IP from the proxy.

First account success: The first time I log into User A, download google play services & create a new google account i don't get asked for a phone verification.

Second account failure: After creating google account on User A, I end user, I change my IP address (rotate mobile proxy), & log into User B where I download google play services & create a new account. Here, I get asked for a phone verification.

I reflash the grapheneos & repeat the same exact steps above, I get the same results again and again. First google account is clean no phone verification on User A & then phone verification on User B.

Google must be detecting that the same phone is creating accounts between the users

**Comment by thestinger** [comment]
You're making incorrect assumptions.

**Comment by thestinger** [comment]
You're making incorrect assumptions leading to your conclusion that this is what's happening.

**Comment by amolpatravali97** [comment]
How do i go about creating multiple anonymous accounts then
