### ISSUE TITLE
Notifications for Package Manager

### ISSUE THREAD

**Issue by TempUser13** [GrapheneOS/os-issue-tracker#2411]
It'd be nice to have a notification when an app is being installed/compiled because of AOT it obviously does take a while. The notification I see would be like the one for system updates, having the name of the app being compiled and a progress bar with percent counter. This would be useful when installing/updating a large app or multiple apps.

**Comment by thestinger** [comment]
This is already made available via the app installing it reporting it as installing.

**Comment by thestinger** [comment]
The low-level infrastructure doesn't report a progress bar. There's no fine-grained progress bar for OS updates either. We aren't going to make substantial changes to support this.
