### ISSUE TITLE
[Health & Safety] Allow bypassing / aborting updates at start.

### ISSUE THREAD

**Issue by colleen05** [GrapheneOS/os-issue-tracker#2418]
Not allowing updates to be bypassed at startup is a major concern for health and safety. In the event of an emergency, someone who has a phone with GrapheneOS installed will currently need to wait for updates to be installed until they can call 911 (or any other emergency number). If updates were instant, and battery life was infinite, this wouldn't be a problem.

I live in an area that gets storms quite frequently which impact internet speed and access to power. I also live with someone who is at a higher risk of medical emergencies than me. I do not want to have to wait 10-15 minutes for updates during a storm before calling 911 if he needs help. Especially if the power is out, and these updates are draining the remaining time I have on my phone that I could be using to talk to an operator.

Please take this into consideration for the health and safety of GrapheneOS users.

**Comment by colleen05** [comment]
OR, at least allow people to make emergency calls during an update.

**Comment by thestinger** [comment]
Not clear what you mean. Updates are installed in the background. They don't block making calls. Nothing forces you to reboot into the new OS version where you'll need to wait for optimizing apps. Aborting that and rolling back the update via power off is already possible.
