### ISSUE TITLE
eSIM cannot be deactivated on Google Pixel 6 Pro

### ISSUE THREAD

**Issue by AndyB28** [GrapheneOS/os-issue-tracker#2420]
Hello, I have downloaded and used an eSIM sucessfully on a Google Pixel 6 Pro.

But now I am totally unable to delete that eSIM. I cannot even deactivate it.

The message is "Mobilfunkanbieter kann nicht deaktiviert werden" - "Ein Problem ist aufgetreten. Dein Mobilfunkanbieter konnte nicht deaktiviert werden."

Translation: 
"Cellular provider cannot be deactivated" - "A problem has occurred. Your mobile carrier could not be deactivated."

There is no way for me to remove the eSIM for the device, and it is blocking the space for another eSIM I want to use. Also it is constantly trying to look for a network when the mobile network is switched on, and does obviously not find it as the eSIM is old and not valid anymore.

How to permanently remove an expired eSIM?

**Comment by AndyB28** [comment]
Solved it myself after browsing the bug history here, enabling "privileged eSIM management" did the trick.

Sorry.

**Comment by thestinger** [comment]
Documentation could be improved but this isn't unexpected.
