### ISSUE TITLE
Feature Request: Network pemission scopes

### ISSUE THREAD

**Issue by bitrate16** [GrapheneOS/os-issue-tracker#2422]
In many cases some vendor apps are required for hardware devices to communicate with/configure/setup/e.t.c.

Is it possible to add network pesmission scopes and allow user to define the allowed subnets, where app can access network? That may be very useful for case of allowing some proprietary vendor app to access 192.168.1.0/24 or 192.168.1.31 (direct ip) to communicate with specific device/network, but disallowing access to external net. As i know, it is possible with iptables

Example use: IP Camera. 
Camera access to internet is blocked on router, but recordings can be fetched only with app and current status can be viewed only through the app. App always makes calls home, so it is insecure/unprivate to use it without blocking full network access for phone on router. 
This solution can allow app to communicate with only static camera IP on local network and nowhere else

**Comment by thestinger** [comment]
That's not going to work because the INTERNET permission is a single coarse thing. Indirect access via many APIs bypasses trying to implement filtering with a packet-based firewall approach. You can also use a packet-based firewall if it's what you want.

Revoking the INTERNET permission but making a special case for a bunch of APIs including direct socket access would be one approach but if the app depends on any of those things that are blocked like DownloadManager, it won't work anymore.

You're welcome to use a leaky firewall-based approach already.

**Comment by bitrate16** [comment]
@thestinger what packet firewall solution is compatible with GOS and does not rely on creating VPN connection?

**Comment by thestinger** [comment]
You're misunderstanding the VPN service feature. Apps providing a VPN service can have all DNS requests and optionally all other traffic from the profile routed through them. They don't have to create any VPN connection. They can simply filter traffic as a firewall if that's what they're designed to do. They can also both provide a firewall and optional support for a VPN connection if that's what they choose to implement. Many apps also use it simply to provide a local DNS resolver with features like alternate encryption approaches, ad filtering, etc. without routing other traffic through themselves.

**Comment by bitrate16** [comment]
@thestinger I understand, but the initial question problem is that, as I know, almost every network filtering app that works on vanilla android is based on on creating VPN service and selectively routing traffic through it without actually using VPN in any other way. 
I'm looking for solution that will be compatible with vanilla android/GOS (so, no ROOT iptables, ufw, e.t.c.) and won't use system VPN service because it is already used by wireguard/openvpn/e.t.c. VPN apps and there can be only one without composing

**Comment by thestinger** [comment]
> I understand, but the initial question problem is that, as I know, almost every network filtering app that works on vanilla android is based on on creating VPN service and selectively routing traffic through it without actually using VPN in any other way.

The point is that it's entirely possible for an app to do firewall filtering and then support using another VPN or forwarding the traffic to a proxy like NetGuard does.

> I'm looking for solution that will be compatible with vanilla android/GOS (so, no ROOT iptables, ufw, e.t.c.) and won't use system VPN service because it is already used by wireguard/openvpn/e.t.c. VPN apps and there can be only one without composing

It's entirely possible for them to support chaining through proxies or to directly support using a VPN without needing it.
