### ISSUE TITLE
Pixel 6a sensors off quick tile from developer options sometimes doesn't work on camera.

### ISSUE THREAD

**Issue by OrginalS** [GrapheneOS/os-issue-tracker#2426]
Sensors off quick tile from developer options prevents camera and microphone from working even if camera access and mic access quick tiles are on (expected behaviour), but sometimes it will prevent camera from working even when it's been turned off if it was previously on. Sometimes camera access will be allowed even though sensors off quick tile is turned on.

One way I found to consistently reproduce this:

1. restart phone
2. turn on sensors off quick tile
3. turn off sensors off quick tile
4. switch user profile
5. try to access camera

The camera can not be accessed.

1. restart phone
2. switch user profile
3. try to access camera

The camera can be accessed.

Build number:
TQ3A.230805.001.2023090200

**Comment by thestinger** [comment]
You should use the Camera and Microphone toggles. Developer options are not officially supported for more than development. This is an AOSP issue but not something within the scope of GrapheneOS.
