### ISSUE TITLE
Feature Request: support turning on Do Not Disturb when flipping phone over (Flip to Shhh)

### ISSUE THREAD

**Issue by pushkin-** [GrapheneOS/os-issue-tracker#2427]
Stock Android had a [Flip to Shhh feature](https://www.howtogeek.com/798418/how-to-mute-calls-by-flipping-your-android-phone/) where, when enabled, my phone would go silent (I believe Do Not Disturb mode) when I'd flip my phone over, and go back when I flip it back.

Can this be supported?

**Comment by thestinger** [comment]
> Stock Android

No, it's a feature added by certain OEM forks of AOSP. This isn't the kind of thing we work on.

**Comment by dbrgn** [comment]
As far as I know, "Flip to Shhh" is a Google-Feature on the Pixel line.

Since GrapheneOS runs only on Pixel devices, this is one of the features that I do miss. I'd appreciate if it could somehow be ported (but I suspect it's proprietary code by Google).
