### ISSUE TITLE
[duplicate issue refer to  #1968]  pixel 6a unable to load os with sim card 

### ISSUE THREAD

**Issue by hodhado** [GrapheneOS/os-issue-tracker#2429]
refer to https://github.com/GrapheneOS/os-issue-tracker/issues/1968

release: 2023090600

after lastest update grapheneos automatically powers itself off after asking for sim pin then boots again in recovery mode with options to try again or factory reset

after more tinkering it seems that if sim pin is typed almost immediately phone will proceed to showing the lockscreen and boot normally from there on. if there is a short delay of about 4 seconds and more before entering sim pin phone will reboot in recovery mode even after successfully proceeding to lock screen. also, phone will reboot to recovery mode if presented with pin screen and no pin entered.

thank you for your time and effort looking into this

**fixed when followed steps suggested here:** https://discuss.grapheneos.org/d/5592-grapheneos-version-2023061400-released/30

"Upon changing various settings, I came across the element that for me seems to have been causing the issue -- ImsService.

The SIM lock boot-loop problem begins if you make changes to the locations permissions of ImsService, with either:

you disable "precise location" for its location permission
you disallow the location permission for ImsService completely

In either of those scenarios, I am able to replicate the problem. And then re-enabling ImsService's location permissions, the problem goes away completely."

**Comment by hodhado** [comment]
release: 2023090600

**Comment by thestinger** [comment]
Revoking permissions of core system components like the IMS service is broken. You took away the ability for part of the core cellular services in the OS to access cellular data.
