### ISSUE TITLE
Call Recording Enabled but can't access in calls

### ISSUE THREAD

**Issue by MoldyTaint** [GrapheneOS/os-issue-tracker#2430]
Context: I do live in the US, my state is a one party state

I remember reading that it was disabled in the settings for US users but now see that the option in my call settings has it there as an option. About a week ago I noticed that I was able to record a call, which was saved. Now I do not see the option in the call screen where it allows me to record the phone call again. Not sure if it was removed recently or not.

**Comment by thestinger** [comment]
The option is there. You need to scroll if you have others filling it.

**Comment by MoldyTaint** [comment]
I was not aware of the scrolling feature at all, thank you so very much!
