### ISSUE TITLE
Feature request: call length notification

### ISSUE THREAD

**Issue by blaugrau3001** [GrapheneOS/os-issue-tracker#2431]
As in Signal, when you call with someone and you tab out of the call a notification is placed next to the time in the statusbar, where the call length is displayed. Is this possible to do in the Phone app of Grapheneos.

**Comment by empratyush** [comment]
It is up to the app to implement this feature sadly aosp dialer app doesn't.

**Comment by empratyush** [comment]
I am closing this issue as it is a feature request. We will consider this when we start improving the AOSP dialer or create a new one.
