### ISSUE TITLE
Slow gps

### ISSUE THREAD

**Issue by divi0001** [GrapheneOS/os-issue-tracker#2432]
When using Google maps or other map/location based applications, the acquiring of the phones location usually takes 20 seconds to multiple minutes depending on the cellular network (if it is e/lte/...).

**Comment by thestinger** [comment]
This depends on your configuration. PSDS and SUPL are enabled by default. Have you disabled them or blocked them in some way? It's normal for it to take 10-20s to get an initial GNSS lock. That's no different than the stock OS. The stock OS just has Play services built into the OS providing network-based location separately from GNSS.

**Comment by divi0001** [comment]
Havent found the options you mentioned. (Searched developer settings aswell). Is it possible to copy the behaviour oft stock os built into graphene?

**Comment by thestinger** [comment]
It already behaves the same way for GNSS. It just uses a GrapheneOS server by default for PSDS and SUPL.
