### ISSUE TITLE
GPU overheating and crashes on Pixel 6 Pro

### ISSUE THREAD

**Issue by lyphyser** [GrapheneOS/os-issue-tracker#2435]
When playing some GPU-using games in warm ambient temperatures (25-30 C) with a case on the device, the device sometimes overheats, which leads to frame-rate affecting throttling and even app freezes and app crashes (but not system crashes).

Obviously, heavy GPU usage should never cause an application to freeze or crash, and furthermore performance should be limited ahead of time if necessary so that thermal balance is maintained with limited throttling, rather than having to do heavy emergency throttling (or shutdown?), which seems to be what might be happening here.

**Comment by thestinger** [comment]
GrapheneOS doesn't handle this differently than the stock OS and it seems like a hardware issue with your device.
