### ISSUE TITLE
Feature request: re-add two button system navigation

### ISSUE THREAD

**Issue by t4moxjc7** [GrapheneOS/os-issue-tracker#2438]
Google removed this recently for some reason, despite it being a useful feature. Its more intuitive than the gesture-based navigation imo, and compared to three button navigation, you don't have to stretch your thumb so far to reach the keyboard change button, which you often need to do for keyboard-based password managers.

**Comment by thestinger** [comment]
It's not going to be added back. Gesture navigation has a tiny bit of a learning curve but is much better than this partial gesture navigation.

https://grapheneos.org/usage#gesture-navigation
