### ISSUE TITLE
Storage full when it shouldn't be

### ISSUE THREAD

**Issue by jjreyes92** [GrapheneOS/os-issue-tracker#2445]
My secondary profile running google play services has recently started showing that my storage is low when there is no reason for that. The used storage doesn't add up to what is showing. I delete things i don't really need and in a few days it will say the same thing. Do i assume this is possibly malicious activity by google play services and stop using it?

**Comment by thestinger** [comment]
> Do i assume this is possibly malicious activity by google play services and stop using it?

No.

**Comment by thestinger** [comment]
It sounds like your storage is nearing being full and you'll need to determine what's it to clear the data.

**Comment by thestinger** [comment]
There must be something using a lot of storage. We can't identify that for you.
