### ISSUE TITLE
Pixel 5: Black screen during calls, double tap to check not working

### ISSUE THREAD

**Issue by dazu89** [GrapheneOS/os-issue-tracker#2450]
I am an new GrapheneOS user, amazed and grateful for this project! 
Currently I am running build TQ3A.230901.001.2023091800 on my Pixel 5, unfortunately I have to deal with two rather annoying issues:

1. The screen is switched off during calls, albeit only when using certain applications such as the pre-installed caller app, when listening to Whatsapp voice messages, during Whatsapp calls but not using Element.
2. (Double)-Tap to check phone does not work, so power-button is in heavy use.

**Comment by thestinger** [comment]
> The screen is switched off during calls, albeit only when using certain applications such as the pre-installed caller app, when listening to Whatsapp voice messages, during Whatsapp calls but not using Element.

You have a faulty screen protector, case or something else blocking the proximity sensor.

> (Double)-Tap to check phone does not work, so power-button is in heavy use.

It's single tap, not double tap, and it works fine. Could be the same screen protector issue.
