### ISSUE TITLE
Web searches always bring back error ERR_ADDRESS_UNREACHABLE when connected to wifi

### ISSUE THREAD

**Issue by SleepzCat** [GrapheneOS/os-issue-tracker#2451]
I have a stable internet connection (I can watch videos online through newpipe) but I can't make any searches or use apps that rely on the web (like Kuroba) to function. I can however make web searches when connected to cellular data.

**Comment by SleepzCat** [comment]
I should add that I tried power cycling my modem, router and phone but that didn't fix the issue.

**Comment by SleepzCat** [comment]
A second note is that some websites seem to work perfectly fine and can be visited with a direct link while connected to WiFi, but many websites do not, and general web searches do not work at all.

**Comment by thestinger** [comment]
This is a network issue. It's very unlikely that it's a bug. You'll need to use the support platforms (Matrix chat or discussion forum).

**Comment by SleepzCat** [comment]
This is only happening in chromium based browser. Firefox works fine. I really doubt it's a network issue and no one in the matrix chat seems to be able to help me with this issue.

**Comment by SleepzCat** [comment]
> This is a network issue. It's very unlikely that it's a bug. You'll need to use the support platforms (Matrix chat or discussion forum).

This is only happening in chromium based browsers. Firefox works fine. I really doubt it's a network issue, as like I said it's only happening to ME on the network, and nobody who's using stock android. No one in the matrix chat seems to be able to help me with this issue. I'll open a new issue if I have to, because this issue NEEDS to be fixed ASAP and no one is helping me.

**Comment by thestinger** [comment]
It's caused by a configuration or network issue. Opening more bugs isn't helpful.

**Comment by SleepzCat** [comment]
> It's caused by a configuration or network issue. Opening more bugs isn't helpful.

This happened out of nowhere. Nothing was configured incorrectly to my knowledge because it just randomly started without me configuring anything. I will keep trying to ask over and over in the matrix chat and discussion forum this but if I can't get help from anyone by next Saturday and this starts to cost me money by driving my cellular data bill up, then I'm sorry but I WILL open another bug out of spite, because the fact that this happened out of nowhere without changing any network settings, only seems to affect my device and specifically only chromium, doesn't solve itself after resetting the network and its settings AND doesn't have documentation online that I can find leads me to believe that it's not just a "configuration or network issue". We will see though.

**Comment by thestinger** [comment]
You need to go through your configuration including VPN, Private DNS, Wi-Fi settings (forget the saved network), etc. You can reset network settings via the Settings app.
