### ISSUE TITLE
[Feature Request] Custom lock password that wipe the phone to prevent further access

### ISSUE THREAD

**Issue by Cartasiane** [GrapheneOS/os-issue-tracker#2455]
I'm a journalist and I'm always very afraid that someone at some not so democratic country airport / police station would ask for my phone password or force me to give it / would use some kind of Celebrite device to access it. Most of the time they ask for your password first so if you could give some custom password that wipe your phone, it would be a very interesting security measure!

**Comment by thestinger** [comment]
Duress PIN/password has been developed and is receiving finishing touches. It likely won't be shipped until after Android 14.
