### ISSUE TITLE
GPay selectable as contactless payment app although not installed

### ISSUE THREAD

**Issue by MatsG23** [GrapheneOS/os-issue-tracker#2458]
In the NFC settings, you can select the preferred app for contactless payment. The issue I have noticed is that you can choose _Google Pay_ for the list although I did not install [the Google Pay app](https://play.google.com/store/apps/details?id=com.google.android.apps.nbu.paisa.user).
I have setup Sandboxed Play Services + the playstore by downloading the apps from the GrapheneOS Apps repository client but I have not signed in.
Any idea what is causing this? Is this an OS bug?

**Comment by thestinger** [comment]
It's not a bug. Google Play provides it.
