### ISSUE TITLE
Sporadic "Tap again [to open]"

### ISSUE THREAD

**Issue by Hasshu** [GrapheneOS/os-issue-tracker#2464]
Every now and then, an attempt to tap a tile in quick settings on the lock screen would not work, instead producing mild haptic feedback and a notice at the bottom of the screen: "Tap again" / "Tap again to open".

It appears to be occurring at random, and the fairly short double-tap window leads to mistaps, which makes it highly annoying. One thing I noticed is that it happens less often when the screen lock is set to "Swipe" (as opposed to "PIN").

**Comment by thestinger** [comment]
Please update to the latest release. It's likely fixed.

**Comment by Hasshu** [comment]
> Please update to the latest release. It's likely fixed.

Already have. Will post an update if the issue persists.

**Comment by Hasshu** [comment]
Just hit this again when I tried to disable the Do Not Disturb mode after leaving the phone in the said mode for a while.

**Comment by Hasshu** [comment]
This issue is still relevant, so reopen it, please.

The "Do Not Disturb" tile seems to be the most common offender; it also happened with the "Flashlight" tile once. And earlier today I got the annoying prompt while trying to open a new SMS message from the lock screen.

**Comment by Hasshu** [comment]
> closed this as completed

I sure hope that it is...! Incidentally, I considered posting an update on several occasions, but every time I thought the issue's finally gone, it would come back after a system update.
