### ISSUE TITLE
Accidental call answer / emergency call possible

### ISSUE THREAD

**Issue by ASerbinski** [GrapheneOS/os-issue-tracker#2465]
With the dialer false gesture detection being once again disabled, we are again faced with the problem of accidental call answering and emergency calling. These can happen when the phone is in your pocket, especially when you are at all sweaty since this increases conductivity.

There is a workaround for the potential for making accidental outgoing emergency calls, which is to disable the emergency dialer component of the dialer package using the following;

```pm disable com.android.phone/.EmergencyDialer```

With that workaround, the emergency button remains visible on the unlock screen, but it won't do anything. This will effectively prevent emergency calling while the phone is in your pocket, however it also disables the quick access to emergency dialing -- now it becomes necessary to unlock, open the dialer, input the appropriate emergency number, and dial it. In addition to being cumbersome, it also puts your phone data at risk since now the phone is unlocked in an emergency situation.

It also does nothing to fix the problem of accidentally answering incoming calls while in pocket. This creates a major security vulnerability, since it allows for a caller to potentially listen in on a private conversation, while you, as the phone owner, are unaware that there is an active call.

I would like to propose that this feature be immediately RE-ENABLED, as the security implications of not having this feature vastly outweighs the inconvenience of the occasional difficulty in answering a call. A switch can be added to the dialer settings to enable/disable the feature if needed.

**Comment by thestinger** [comment]
This isn't a valid proposal. The status quo is that false gesture detection in the Dialer app is completely broken and cannot be enabled without making the Dialer app barely usable. The situation created by re-enabling it wasn't acceptable and the bar for re-enabling it will be much higher than before. A fixed implementation of false gesture detection will need to be implemented and well tested before it can be shipped. It could use the standard approach included in the OS instead of a poorly done custom implementation in Dialer.

**Comment by ASerbinski** [comment]
I strongly disagree. There are now reports in your own forum of pocket dialing of emergency numbers;

https://discuss.grapheneos.org/d/7959-a-lot-of-pocket-dialing-suddenly

This type of problem can in many jurisdictions be illegal, since it can tie up emergency numbers.

**Comment by thestinger** [comment]
The anti-falsing implementation is broken and isn't going to be enabled until it's replaced with working code.
