### ISSUE TITLE
Mobile data and phone calls work sometimes when I'm out even with mobile data turned off and not on Wifi 

### ISSUE THREAD

**Issue by dimyself** [GrapheneOS/os-issue-tracker#2466]
Hi there, 

I'm not sure how to test this as it only happens sometimes. Sometimes when I go out, I leave data turned off and only turn it on if I need to look something up or call someone.

I have triple checked and verified I had no data turned on while out, but still able to make/receive calls and look up search queries on browser with no data on. 

It looks like its off, the button is off/greyed out, but data works.

This doesn't happen every time. I have mostly noticed this by accident. 

for example, I leave with data off, but somehow I would receive a call or make a call. Then look at the buttons and data if still off. Also, one time I tried searching for something and data was working, but then I realized I still have data off in the toggles.

Now that I have reported this, I will do more testing of it to try to reproduce it. 

It has happened a handful of times that I've noticed it. 

Has this been reported before? I've searched, but dont see any issues about  this

Maybe I can do a screen record next time it happens and record data while its off

I'm using Tmobile and a Pixel 6 pro with latest GrapheneOS

I have wifi set to turn off when i lose wifi range, and I always leave home with mobile data off (I leave mobile data off at all times unless I need it when i'm out)

I mean is it possible somehow data actually stays on even if the OS is reporting it's off??

Thank you

**Comment by dimyself** [comment]
I have posted this issue in the past on the forum, and in the past the person said 

"you have to toggle airplane mode to turn off mobile data / calls"

so, everytime I leave home and want data off , I have to turn off also toggle airplane mode??

how come the mobile data toggle doesnt also turn off calls?

Is there a setting or way to turn off all mobile data including calls automatically (kind of like how wifi auto turns off after X number of seconds)?

thank you!

**Comment by thestinger** [comment]
You're misunderstanding the mobile data toggle. It's not a toggle for the cellular connection. That's the airplane mode toggle.

**Comment by dimyself** [comment]
What all does mobile data toggle do then?

Ok...just to make sure I got it right

This should be my workflow for data:

At home if I want only wifi calling and no mobile data:
- I have to toggle airplane mode and then turn on wifi (and bt or whatever
toggles airplane mode turns off)

Then when I'm away from home, if i want to turn on mobile data to look
something up or make calls, I have to:
- turn off airplane mode and toggle mobile data toggle on?

Thanks

**Comment by thestinger** [comment]
Mobile data toggle controls whether internet access (mobile data) is available through the cellular connection. You're mixing up the cellular connection with mobile data. Airplane mode controls whether cellular is enabled. Mobile data toggle controls whether mobile data (internet via cellular) is enabled.

**Comment by dimyself** [comment]
Ok thank you!

So Airplane mode controls cell service and data (making / receiving calls /
internet access outside of wifi), and mobile data is just for internet
outside of wifi and not cell tower calls

Also, instead of creating another post, is there a way to turn off
mic/camera after X seconds of non use? And then when it is requested (ex.
like making a phone call), it could enable mic again? I find mic / camera
are always on, even though i rarely use them. It would be nice if theres a
way for them to turn off when not in use, and turn on as they are used

Thanks
