### ISSUE TITLE
Nextcloud/DAVx5 buttons non-responsive during restore

### ISSUE THREAD

**Issue by schklom** [GrapheneOS/os-issue-tracker#2467]
![IMG_20231002_210118_613](https://github.com/GrapheneOS/os-issue-tracker/assets/23263086/8ee529b5-5ef4-4e61-b852-eff7f3745ae8)

After a factory reset, I have connected the Pixel 6a to Internet via Wi-Fi, but I cannot install any app during the restore phase. The DAVx5 and Nextcloud buttons are grayed and clicking on them does nothing.

Is this a GrapheneOS or a Seedvault bug?

**Comment by thestinger** [comment]
Those apps aren't bundled with GrapheneOS. It's not a bug. You can restore after setup or you can move the backup to a USB drive to restore from there.
