### ISSUE TITLE
Sim Card Lock/Corrupt Data Bug - Pixel 7 Pro

### ISSUE THREAD

**Issue by amnesiac-kid** [GrapheneOS/os-issue-tracker#2468]
If I have Sim Card Lock activated, sometimes after an update the boot process is allegedly corrupt. This happened to me twice now.
After boot during the password and pin input screen the device shuts down after a few seconds and reboots to a "data may be corrupt: try again/factory reset"  screen.

Solution: You have to hurry and put in your password before the pin input screen pops up (else it reboots) and then quickly enter the pin and then your password again.

First time this happened I managed to resolve the issue by deactivating sim card lock, rebooting and then reactivating it again. After the latest update it happened again and this fix didn't work anymore. I also checked my phone with the auditor.

**Comment by thestinger** [comment]
This sounds like a serious hardware issue, not a bug in the OS.
