### ISSUE TITLE
Provide a bash script to install build dependencies

### ISSUE THREAD

**Issue by dd-dreams** [GrapheneOS/os-issue-tracker#2471]
Currently there are some dependencies for every build target. It would be helpful if there was a bash script to install these builds for every platform. The main benefit is not needing to search for every dependency or to install manually such as `repo` on Debian.

This would be helpful for newcomers mainly, or new machine setups.

**Comment by thestinger** [comment]
Could just provide commands in the docs instead of script.

**Comment by thestinger** [comment]
> The main benefit is not needing to search for every dependency or to install manually such as repo on Debian.

Obtaining `repo` manually and putting it at `~/.local/bin/repo` with that directory added to `PATH` is a better approach. The `repo` command is just a bootstrap command for obtaining/updating/verifying the full `repo` checkout. It will regularly tell you that you need to update the bootstrap command by copying the new one from the repository it bootstrapped so it's best not to have an out-of-date distribution package. I don't even use the distribution package for it on Arch Linux.

**Comment by dd-dreams** [comment]
> Could just provide commands in the docs instead of script.

Yeah, but then you would have to copy each one. Maybe a one-liner.

> Obtaining `repo` manually and putting it at `~/.local/bin/repo` with that directory added to `PATH` is a better approach. The `repo` command is just a bootstrap command for obtaining/updating/verifying the full `repo` checkout. It will regularly tell you that you need to update the bootstrap command by copying the new one from the repository it bootstrapped so it's best not to have an out-of-date distribution package. I don't even use the distribution package for it on Arch Linux.

I meant some bash command to install `repo` automatically. Same instructions as manually, but just make it automatic.

**Comment by dd-dreams** [comment]
Also, I mentioned that it needs to be platform specific, such as for Debian/Ubuntu is `apt` and Arch its `pacman`, or nixOS and so on.

**Comment by flawedworld** [comment]
https://gist.github.com/flawedworld/4ab1b6d4063f47dbf03396cc667ce4bf this might help but I have never bothered to put this on the AUR or check this is actually all you need.

**Comment by dd-dreams** [comment]
Great. I believe something like that should be available in the website or a link to it.

**Comment by thestinger** [comment]
Should be filed as a documentation improvement request for grapheneos.org.
