### ISSUE TITLE
Bug: Pixel 6a - 'Issue' with Brightness-bar 

### ISSUE THREAD

**Issue by T1z3n** [GrapheneOS/os-issue-tracker#2473]
![IMG_20231007_004957.jpg](https://github.com/GrapheneOS/os-issue-tracker/assets/145705427/628be8da-b8fb-490a-9b54-a9b7d5b5d1c8)

Issue: Sometimes the bar don't change the Brightness by Tapping the bar.

Ver.: TQ3A.230901.001.2023100300 - Beta

**Comment by thestinger** [comment]
If you still have the issue with Android 14, please reopen. We're in the process of finishing up the port.
