### ISSUE TITLE
Lockscreen Shows Wallpaper Again After Pin Entry

### ISSUE THREAD

**Issue by seniorm0ment** [GrapheneOS/os-issue-tracker#2484]
When on the lock screen, you see the lock screen wallpaper, clock, notifications, and other buttons and information.
Swipe up to reveal numbers to enter your lock screen pin, after you hit enter the screen clears all of the interface and shows the lock screen wallpaper for a second, then takes you to your home screen.

Should it not be animated nicely to take you to your home screen, instead of showing your lock screen again? 
It makes the transition seem very not seamless 

Pixel 6 Pro, Version: 2023100300

**Comment by thestinger** [comment]
This might be fixed already in Android 14, which we're in the process of releasing to the Stable channel. It isn't in the Stable channel for all devices yet due to rolling it out in groups of devices to avoid the servers being completely overloaded.

**Comment by seniorm0ment** [comment]
Ok, I have not received the 14 push yet, so that might be why.
I will return back here when I can confirm if you'd like

**Comment by thestinger** [comment]
@seniorm0ment It's in the stable channel for the Pixel 6 Pro now. Please try updating. It will take a long time to install and then to compile your apps during boot.

**Comment by seniorm0ment** [comment]
The animation is smoother, not sure if it is as intended though?

For clarification, the wallpaper still shows for a second, the number pad animates upwards and then jumps into the home screen. I don't have anything to compare it too besides an iPhone, so that may not mean much but the lockscreen animation is a lot better. The whole screen is like an overlay that slides up in unison. This could just be an Android thing.
It is definitely improved from before the update however.

**Comment by thestinger** [comment]
It doesn't seem like a bug. We're not going to improve this animation.
