### ISSUE TITLE
After Update to 2023100900 "No valid operating system could be found. The device will not boot."

### ISSUE THREAD

**Issue by Beerman0815** [GrapheneOS/os-issue-tracker#2489]
After Update to 2023100900, I got the message "**No valid operating system could be found. The device will not boot.**"

After I had turned the phone off and on again several times, it booted finally into the "old" System (2023100300).

Other users had reported those in the forum as well.
https://discuss.grapheneos.org/d/7949-grapheneos-version-2023100900-released
https://discuss.grapheneos.org/d/7970-didnt-boot-after-update-now-does

Thx! :)

**Comment by thestinger** [comment]
@Beerman0815 Your device has a firmware or hardware issue. You need to install the update again.

**Comment by ViktorKahu** [comment]
I had the same problem.

You probably have your auditor app disabled. Go to apps and update auditor (you don't need to enable it, but the update is required). Solved it for me.

**Comment by thestinger** [comment]
Auditor being disabled doesn't cause this. It's a firmware bug on Pixels and you need to reboot to resolve it.
