### ISSUE TITLE
Both Wifi and Mobile Data claims to not have Internet access with the exclamation on their icon in the status bar

### ISSUE THREAD

**Issue by Yrlish** [GrapheneOS/os-issue-tracker#2491]
After receiving the `2023100900` update on my `Pixel 6a` this morning, the phone seems to now think I do not have internet access on either wifi or mobile data. It shows the exclamation mark on the icon in the status bar. Although there is no text saying that "connectivity is limited", which occur when there is actually a problem.

Most apps seems to not care about this and works fine because I do have Internet through these networks. But some apps believes in that and refuses to connect, e.g. Spotify that I cannot use now.

I have flipped airplane mode on/off and tried the "repair network" thing in the network settings without success.

**Comment by thestinger** [comment]
It sounds like you have an issue with your network configuration such as your DNS or VPN which is blocking connections to the connectivity check servers.

**Comment by Yrlish** [comment]
I'm using no VPN on the device and am using the provided DNS from DHCP. So for mobile data that would be my carrier's DNS.

Verifying the settings for DNS in my device, it seems that the "Private DNS" setting is set to "Automatic". Whatever that means. I have not actively set that to anything before.

**Comment by thestinger** [comment]
Is your system time set correctly?

**Comment by Yrlish** [comment]
The systems date and time is automatically set to correct values, with the correct time zone.

**Comment by Yrlish** [comment]
Now when I'm no longer waiting for a call, I rebooted the phone (didn't want to risk it before). And now the exclamation mark is gone... 🤔

So now the apps that didn't want to work before, works. 

Closing.
