### ISSUE TITLE
automatic call recorder apps for graphene os

### ISSUE THREAD

**Issue by kullanici32** [GrapheneOS/os-issue-tracker#2494]
I want to record calls automatically (I am weak at remembering conversations) but the internal call recorder of Graphene OS does not record them automatically. I tried the acr phone, acr unchained, cube acr applications and gave them accessibility permissions. After giving the permission for the first time, the first call is recorded properly, and if I receive another call sometimes after 1 hour, sometimes after 1 day, or sometimes after 5 minutes, the recording is silent. When I go to the accessibility settings, it says 'this service is running incorrectly' and I have to turn it off and on. This problem does not exist in lineage os. I wonder what is causing the problem? How can it be solved? I use multiple profiles, could it be because I switch between profiles?

**Comment by thestinger** [comment]
There's already https://github.com/GrapheneOS/os-issue-tracker/issues/2083 open about automatic call recording. Android apps aren't allowed to access what's required to do this. Accessibility services can do it, but they need to be properly implemented. You'll need to try on the stock OS and confirm that it works there before assuming it's not an app issue.

**Comment by kullanici32** [comment]
I haven't tried it since I don't use stock os, but according to the comments I read elsewhere, cube acr works without any problems in stock os.  I tried it with lineage os, there is no problem with it, I use it in graphene os, as I said, sometimes it says 'service is malfunctioning' in the accessibility settings.  I wonder if the problem is in the multi-user profile?  Or is it a result of graphene security hardening?

**Comment by thestinger** [comment]
GrapheneOS is based on Android 14.

> Or is it a result of graphene security hardening?

No.

**Comment by thestinger** [comment]
> but according to the comments I read elsewhere

You haven't tested or checked whether it works on Android 14.

**Comment by kullanici32** [comment]
> > but according to the comments I read elsewhere
> 
> You haven't tested or checked whether it works on Android 14.
I tested 13, and now I test 14
I tested it twice now, the result is as follows: I installed acr phone, I gave it all permissions except the internet permission, and I installed acr phone helper, I gave it all permissions except the internet, I made 3 calls, it registered without any problems, then I changed the user and stopped for 10 seconds, then I went to the main profile. When I went to the accessibility settings, it said 'this service is malfunctioning'.  So the problem is 100% in the multi-user profile.  I selected the option to receive calls and SMS on the second profile I opened, maybe this is what caused the problem?

**Comment by thestinger** [comment]
Not all apps are compatible with secondary users. Have you tried in the main user now?

**Comment by kullanici32** [comment]
> Not all apps are compatible with secondary users. Have you tried in the main user now?


I don't use any applications in the 2nd user anyway, I only use ACR in the main profile.

**Comment by thestinger** [comment]
It's expected that an accessibility service in the Owner user can't access secondary users, if that's what you're talking about.

**Comment by thestinger** [comment]
If the app is breaking from switching users, it's an app issue they need to resolve. We can't fix issues for app developers like this which would also occur on stock OS or AOSP.

**Comment by kullanici32** [comment]
> If the app is breaking from switching users, it's an app issue they need to resolve. We can't fix issues for app developers like this which would also occur on stock OS or AOSP.


Then this problem is an AOSP problem related to multiple user profiles.

**Comment by kullanici32** [comment]
I will test this multi-user profile issue thoroughly in stock rom and report back.

**Comment by thestinger** [comment]
> > If the app is breaking from switching users, it's an app issue they need to resolve. We can't fix issues for app developers like this which would also occur on stock OS or AOSP.
> 
> Then this problem is an AOSP problem related to multiple user profiles. Did I get right?

It's likely an app bug.
