### ISSUE TITLE
On Pixel 6a, when accessing the "See all apps" list from the main owner profile and selecting an app installed in another user profile, the screen goes black.

### ISSUE THREAD

**Issue by midtsveen** [GrapheneOS/os-issue-tracker#2495]
### Description
I am encountering an issue on my Pixel 6a running GrapheneOS with two user profiles. When I navigate to `Settings > Apps > See all apps` using the main owner profile, I can see the apps installed in the secondary user profile. However, when I click on any app listed there that is installed in the secondary user profile, the screen goes black. I am unable to go back to the previous screen unless I open the app switcher and close the settings.

### Steps to reproduce:
1. Open the main/Owner profile on a Pixel 6a.
2. Navigate to Settings.
3. Go to Apps > See all apps.
4. Select any app from the list that is installed in another user profile.

### Expected behavior:
Upon selecting an app from another profile in the list, the app info page should open normally without any black screen.

### Actual behavior:
When you navigate to `Settings > Apps > See all apps` using the main owner profile, You can se the installed apps from any other user profile. When you click on any apps from another profile, the screen goes black. 

### Additional information:
- Device: Pixel 6a 
- GrapheneOS version: [2023100900]
- Number of profiles: 2

**Comment by thestinger** [comment]
Please update to the latest release.

**Comment by thestinger** [comment]
If you're using a non-default launcher, that's likely causing the problem.

**Comment by midtsveen** [comment]
Just updated to the latest release of GrapheneOS and using the default AOSP launcher, I am still encountering this issue. Specifically, I am unable to view the app information for apps in my secondary profile via my main Owner profile app list.

No big worries, as I can simply enter my secondary profile and navigate to 'Settings > Apps > See all apps' to access the information for the apps.
