### ISSUE TITLE
scrcpy no longer interactive after update to 20231009900

### ISSUE THREAD

**Issue by cf100clunk** [GrapheneOS/os-issue-tracker#2496]
I have been using scrcpy for years to interact with my Android phones from my Linux desktop, and it has worked excellently with GrapheneOS until now. On my MX Linux machine (output of uname -a is "6.5.0-1mx-ahs-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.5.3-1~mx21ahs (2023-09-18) x86_64 GNU/Linux") I am using the packaged version of scrcpy (1.17-1) as usual. After my Pixel 6 updated to GrapheneOS 20231009900 there is no longer any mouse interactivity on the phone via scrcpy. All manual activity on the phone itself still appears properly on my Linux desktop via scrcpy but unfortunately it is no longer interactive. In Settings -> Developer options I have kept all USB settings as they were when scrcpy was functioning properly but I have tried activating the Disable adb authorization timeout setting and it made no difference.

**Comment by thestinger** [comment]
This sounds like an issue with this program, not GrapheneOS.

https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#mouse-and-keyboard-do-not-work

**Comment by cf100clunk** [comment]
scrcpy has been working perfectly until this update. Following the link given in the reply, it recommends to enable what I have always had enabled all along and which continues to be enabled. It was of zero help.

It seems that scrcpy and/or linux is not to blame for this, the latest GrapheneOS update is to blame. Please reopen this issue.

**Comment by thestinger** [comment]
See https://github.com/Genymobile/scrcpy/issues/4074. You likely aren't on a version with this fix included. It's an issue with the program and Android 14 compatibility.

**Comment by cf100clunk** [comment]
Follow up: I upgraded my Linux OS from MX 21.1 to 23.1 and then built scrcpy with the newest git pull and it works perfectly now. Thanks again.
