### ISSUE TITLE
Broken screen time in Battery usage

### ISSUE THREAD

**Issue by KileXt** [GrapheneOS/os-issue-tracker#2498]
Hello, 
Currently running build **UP1A.231005.007.2023100900** on a Pixel 7, I noticed the battery screen time  since last full charge (Settings > Battery > Battery usage) is completely broken, it is currently stuck at 1hour 6minutes but has a tendency to jump around, I used my phone way more than that today. 

It made me think of a previous issue: #892, the symptoms could match concurrency issues. 

Thanks for your time

**Comment by thestinger** [comment]
Please update to the latest release and give it time to adjust.
