### ISSUE TITLE
Android 14 Missing "Turn off Wi-Fi/Bluetooth automatically" feature on second profile

### ISSUE THREAD

**Issue by user434245** [GrapheneOS/os-issue-tracker#2499]
Device: Pixel 6
Release: 2023100900
After upgrading to Android 14 its not possible to set this feature on second profile.

**Comment by thestinger** [comment]
It makes sense for only Owner to be able to control it, doesn't it? It applies globally.

**Comment by user434245** [comment]
I had a problem today with bluetooth automatically turning off (it was enabled on the owner's account) so I thought it was related to the missing settings on the second profile, I'll check it out

**Comment by thestinger** [comment]
The issue with the feature not working correctly in Android 14 will be fixed in today's release.
