### ISSUE TITLE
Battery Share missing on 5th generation Pixels with Android 14

### ISSUE THREAD

**Issue by IsAliceOrBob** [GrapheneOS/os-issue-tracker#2500]
Hi there,
I am running UP1A.231005.007.2023100900 on Pixel 5 and since the latest update the battery share tile, as well as the corresponding page in settings, has just disappeared. Can't find it, tried everything I could think of.
Thank you for your time and effort.

**Comment by empratyush** [comment]
hey @IsAliceOrBob  can you please post the output of `adb shell lshal` ? 
you can also drop a message on matrix : `@pratyush:grapheneos.org`

**Comment by IsAliceOrBob** [comment]
Sure, anything that helps:

[Pixel5-Andr14-LSHAL-Output-101223.txt](https://github.com/GrapheneOS/os-issue-tracker/files/12886370/Pixel5-Andr14-LSHAL-Output-101223.txt)

**Comment by empratyush** [comment]
hey @IsAliceOrBob  thanks for help.
can you please also share the output of `adb shell service list`

**Comment by thestinger** [comment]
Will be fixed by today's release.
