### ISSUE TITLE
Bluetooth wont automatically switch off - Android 14

### ISSUE THREAD

**Issue by Muzzh** [GrapheneOS/os-issue-tracker#2501]
Hi, after I leave my car my Bluetooth no longer switches itself off even though I have it set to switch off after 30sec.

**Comment by thestinger** [comment]
It's fixed by today's release.

**Comment by Muzzh** [comment]
Awesome!!!! Thank you.

On 12 Oct 2023, at 8:30 am, Daniel Micay ***@***.***> wrote:

﻿

It's fixed by today's release.
