### ISSUE TITLE
New Android 14 lock screen fonts not present

### ISSUE THREAD

**Issue by ThatOneCalculator** [GrapheneOS/os-issue-tracker#2506]
I'm unsure if they're part of AOSP or not, but the new lockscreen fonts in Android 14 seem like a really fun feature for stock Android, and I'd love to see them in Graphene.

**Comment by ThatOneCalculator** [comment]
The original fonts were found and uploaded here: https://drive.google.com/file/d/1gSHzZ4ZwWGG2SDVHCcGz2FlJzEJfkH72/view

This seems like something that could somewhat easily be implemented

**Comment by thestinger** [comment]
We're only going to include open fonts.

**Comment by ThatOneCalculator** [comment]
Would you consider some open source fonts then to be added to the lock screen? It'd be nice to have a bit more customization.

**Comment by ThatOneCalculator** [comment]
Some examples:

- [Knewave](https://www.theleagueofmoveabletype.com/knewave)

![image](https://github.com/GrapheneOS/os-issue-tracker/assets/44733677/371d18af-d012-4afb-a406-67e9fa57bcfa)

- [Sniglet](https://www.theleagueofmoveabletype.com/sniglet)

![image](https://github.com/GrapheneOS/os-issue-tracker/assets/44733677/1e0b65e2-efcc-4433-a082-76554fcb3017)

- [The Neue Black](https://www.theleagueofmoveabletype.com/the-neue-black)

![image](https://github.com/GrapheneOS/os-issue-tracker/assets/44733677/1714d8a3-53a4-4d86-9059-2d21f72bb333)

- [Terminal-Grotesque Open](https://open-foundry.com/fonts/terminal_grotesque_open)

![image](https://github.com/GrapheneOS/os-issue-tracker/assets/44733677/878b30e4-94d6-47b1-b73f-1beb990fd3fd)

- [Fraunces](https://beautifulwebtype.com/fraunces/)

![image](https://github.com/GrapheneOS/os-issue-tracker/assets/44733677/f393c4cc-ca1a-4ae1-aae4-122efeef21ad)

- [Messapia](https://beautifulwebtype.com/messapia/)

![image](https://github.com/GrapheneOS/os-issue-tracker/assets/44733677/3c66dff1-518c-4681-a961-9021cb7c41b0)

- [Tilt (specifically Tilt Warp)](https://v-fonts.com/fonts/tilt)

![image](https://github.com/GrapheneOS/os-issue-tracker/assets/44733677/f45cf968-c0e5-4ce7-8d6d-ceaa4c9578b9)

- [Tiny](https://v-fonts.com/fonts/tiny)

![image](https://github.com/GrapheneOS/os-issue-tracker/assets/44733677/3fac95a8-430c-40bf-addc-731f56b18374)

- [Mixal](https://v-fonts.com/fonts/mixal)

![image](https://github.com/GrapheneOS/os-issue-tracker/assets/44733677/beda6ac4-f653-42fc-bb38-fdc0ff6fa9aa)

**Comment by thestinger** [comment]
It could be done but it's incredibly low priority, would need to match some kind of OS branding standards and is unlikely to happen without someone stepping up to work on those things per our specifications.

**Comment by ThatOneCalculator** [comment]
Can I ask where those specifications are? I'd love to take a look :)

**Comment by thestinger** [comment]
We mostly defer to the Material style guide and try to follow it, although we lack the resources to overhaul all our apps and especially the legacy AOSP apps to follow it completely. Google has far more resources to follow it but purposely deviates in many cases, including how they handle fonts since they want a unique Google brand differentiated from Android for their apps and Pixel devices (with the stock OS).

https://github.com/GrapheneOS/branding-extra and https://github.com/GrapheneOS/branding is where that kind of thing will happen in addition to the changes within the OS like the current logo mask for the boot logo.
