### ISSUE TITLE
[FEATURE REQUEST] - Battery Charging Rate / Capacity

### ISSUE THREAD

**Issue by LunchBoxC** [GrapheneOS/os-issue-tracker#2507]
Charging cut off at a defined level.  Eg: 75-80% to extend battery life.
Also an option to slow charge versus fast charging to keep battery temperature down an extend life.

As per Battery University study (see link below), battery useable life and capacity are drastically increased by undercharging the battery on a consistent basis and limiting how fast the battery charges to keep the temperature down.  

Samsung gives you an 85% charge option and a slower charge option, and Apple has a 80% capacity restriction option in their O/S.  It would be nice if we could do the same in Graphene natively.

This would be especially beneficial with Google extending updates for 7 years starting with the Pixel 8's and wanting to make sure the battery lasts that long with enough useable capacity preserved.

Battery University study for Reference:
https://batteryuniversity.com/article/bu-808-how-to-prolong-lithium-based-batteries

Thanks!

**Comment by LunchBoxC** [comment]
For anyone else reading this, there is sort of a workaround I've come up with to date that has worked flawlessly with my Pixel 5 and extended the battery to 90% useable capacity after 3+ years of intensive use daily (921 charging cycles).

Install the IFTTT app and setup an Android Notification applet triggered by the AccuBattery App with the trigger word "disconnect" and then have it turn off a smart plug attached to your charger.  I have mine set at 75% 

I also set the smart plug to come on 2 hours before I leave for the day (in the morning) to top off my battery so it's at ~75% before I leave.

Further I also use a 2.4a USB charger and not the included higher speed charger that came with my Pixel.

**Comment by heuwerk** [comment]
I think this is a duplication of #1182 #379

**Comment by LunchBoxC** [comment]
My bad, I thought I used the search feature properly.
