### ISSUE TITLE
Seedvault refuses to install apps from user-trusted source during restore on Android 14

### ISSUE THREAD

**Issue by wreps8Owt** [GrapheneOS/os-issue-tracker#2509]
May related to https://github.com/seedvault-app/seedvault/issues/78 and https://github.com/seedvault-app/seedvault/pull/502 .

I want to migrate data from another phone to a factory-resetted pixel 4a5g running GrapheneOS  2023101100 (Android 14), but Seedvault refuses to install apps from user-trusted source (in my case, [f-droid basic](https://f-droid.org/en/packages/org.fdroid.basic/) ) during restore. It only allows me to launch the f-droid basic to install the app via "Tap to install" when it is present (install f-droid basic via adb first, and try to restore again, since it has the same key as the old phone now).

In order to complete the migration, I have to downgrade my pixel 4a5g to an older version (Android 13) first (via bootloader unlock, fastboot, and relock). In that version, apps can be successfully installed and data restored, and I can upgrade it to 2023101100 later.

**Comment by thestinger** [comment]
Seedvault issues aren't tracked here. It's deprecated in GrapheneOS.

**Comment by thestinger** [comment]
Seedvault issues aren't tracked here.

Seedvault is also deprecated in GrapheneOS and we plan to replace it with a new GrapheneOS backup app which will work properly. We're aware that it's not a good app and we can't currently do much about that until we have more developers so we can assign people to building a new backup app, similar to needing a new setup wizard and other apps.
