### ISSUE TITLE
HTTP request headers expose device model and android version

### ISSUE THREAD

**Issue by DeepSeaUnited** [GrapheneOS/os-issue-tracker#2511]
When on Vanadium, according to the [Device Info](https://www.deviceinfo.me/) website it seems like HTTP request headers expose the device model, Android version, and some other information while these are spoofed/hidden at other sections of the page. This can be checked by directly accessing the website. If Vanadium is intentionally spoofing the information for Device Type/Model (→ Mobile Phone) and Operating System (→ Android version 10) section on the Device Info website (and for any other websites that collects such data), I think the HTTP request headers should also be changed.

**Comment by thestinger** [comment]
Chromium has a frozen user agent header feature which is enabled by Vanadium and mostly enabled by Chrome. The info previously available in the user agent header is still available via the client hint headers. Vanadium hasn't made changes to it yet as you can see.

**Comment by thestinger** [comment]
Filed https://github.com/GrapheneOS/os-issue-tracker/issues/2512 to track this already planned work.
