### ISSUE TITLE
Launcher doesnt start after recent update

### ISSUE THREAD

**Issue by DvJoe** [GrapheneOS/os-issue-tracker#2513]
Hi there,
as the title suggests, my phone boots after the recent update, but the launcher doesnt.
Also during update, i recognized how slow the updates would take. This was very unusual in my experience.
I was able to copy a crash report via Signal, since this is running in the background, and send it to Desktop Signal to show it here. This is what it says:

type: crash osVersion: google/bluejay/bluejay:14/UP1A.231005.007/2023100900:user/release-keys package: com.android.launcher3:34 process: com.android.launcher3 processUptime: 3027 + 442 ms java.lang.IllegalArgumentException: shortLabel cannot be empty 	at com.android.internal.util.Preconditions.checkStringNotEmpty(Preconditions.java:109) 	at android.content.pm.ShortcutInfo$Builder.setShortLabel(ShortcutInfo.java:1237) 	at com.android.launcher3.provider.LauncherDbUtils.migrateLegacyShortcuts(LauncherDbUtils.java:131) 	at com.android.launcher3.model.DatabaseHelper.onUpgrade(DatabaseHelper.java:273) 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:423) 	at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:347) 	at com.android.launcher3.model.ModelDbController.createDatabaseHelper(ModelDbController.java:117) 	at com.android.launcher3.model.ModelDbController.createDbIfNotExists(ModelDbController.java:99) 	at com.android.launcher3.model.ModelDbController.migrateGridIfNeeded(ModelDbController.java:290) 	at com.android.launcher3.model.LoaderTask.loadWorkspaceImpl(LoaderTask.java:371) 	at com.android.launcher3.model.LoaderTask.loadWorkspace(LoaderTask.java:344) 	at com.android.launcher3.model.LoaderTask.run(LoaderTask.java:210) 	at android.os.Handler.handleCallback(Handler.java:958) 	at android.os.Handler.dispatchMessage(Handler.java:99) 	at android.os.Looper.loopOnce(Looper.java:205) 	at android.os.Looper.loop(Looper.java:294) 	at android.os.HandlerThread.run(HandlerThread.java:67)

end of error code. 

at this point, my phone is not usable. But it just seems to affect the launcher. I can see everything else is running in the background (can slide system tray down, i see Signal symbol, etc.). Aside from that the screen is just black and im not able to do anything. Would be happy to find some help here!

thanks
Joe

**Comment by thestinger** [comment]
This upstream AOSP launcher bug was worked around in the latest release. You either need to clear launcher data or update to the latest release.

**Comment by DvJoe** [comment]
How do i update my phone, if i cant see anything? Do i just leave it turned on, until i see a notification tray to reboot? And how do i clear the launcher data? Thanks...

**Comment by thestinger** [comment]
You can access Settings via the notification tray via the gear icon. You can launch apps from there, can optionally clear the launcher data if you don't want to wait for the new release with a fix or you update and avoid clearing data.

**Comment by DvJoe** [comment]
Thank you! What would happen, if i clear launcher data?

**Comment by thestinger** [comment]
You'll lose your home screen setup. You can just update to the latest release instead:

https://grapheneos.org/releases#2023101100

> Launcher: delete broken legacy shortcuts instead of crashing (upstream bug)

**Comment by thestinger** [comment]
Do you remember how long ago you did your initial install? And do you remember if you had anything beyond regular app icons on your home screen? Did you use the shortcuts feature for adding shortcuts into apps, or maybe web pages pinned from a browser like Vanadium?

**Comment by DvJoe** [comment]
1. A year ago
2. yes, i used shortcut maker to modify my home screen a bit. 
it seems like im not able to do that anymore, with Shortcut Maker.

**Comment by thestinger** [comment]
That probably explains it. It might happen on stock OS with Pixel Launcher too, although they can ship an update via Play Store for it.

**Comment by DvJoe** [comment]
Thanks for your hell! But at this point, im not able to do shortcuts via Shortmaker anymore, right? And if yes, why? Because the app itself is not up to date?

**Comment by thestinger** [comment]
The app seems to be buggy and created broken shortcuts that are no longer accepted and caused the issue when you moved to Android 14.
