### ISSUE TITLE
Decreasing "Display size" leads to glitches in some apps

### ISSUE THREAD

**Issue by irgendwie** [GrapheneOS/os-issue-tracker#2520]
Starting with the **Android 14 releases**, **decreasing** the "Display size" setting leads to "graphical glitches" for me.

E.g. the overlay buttons in [OsmAnd~](https://f-droid.org/en/packages/net.osmand.plus/) get bigger. For another example, in [WarnWetter](https://play.google.com/store/apps/details?id=de.dwd.warnapp) the tablet mode? is activated although it makes no sense at all regarding the available space.

![diff](https://github.com/GrapheneOS/os-issue-tracker/assets/8360698/4b485e2f-ad66-46b0-89a7-3860cadb7810)
(Top is the default setting, bottom only the display size was decreased.)

Those differences in the picture are the most noticeable, but I have some additional artifacts in other apps also - which just don't feel right and did **behave as expected in the Android 13** releases.

**Comment by thestinger** [comment]
It's very likely the same as how it works in the stock OS and we're unlikely to make changes to it. These apps probably need to make adjustments for Android 14.

**Comment by thestinger** [comment]
It's unfortunate that stuff like this changes in ways that cause issues in apps but that's just how things are.
