### ISSUE TITLE
Second user can't use gesture navigation

### ISSUE THREAD

**Issue by jorgeah92** [GrapheneOS/os-issue-tracker#2522]
Secondary user is unable to use gesture navigation. Swiping home and recent apps is non functional. Switching to button navigation allows home to work but recent app access does not show anything. Back works on both navigation types.

Using a pixel 7. Second user has the ability to install apps but background running is disabled. Google services are active of second profile. Everything works fine on main user.

**Comment by thestinger** [comment]
Are you using a non-default launcher?

**Comment by jorgeah92** [comment]
Yes, that completely slipped my mind. Disregard this issue.

**Comment by thestinger** [comment]
There are issues with non-default launchers right now. It's unclear if these are bugs in Android 14 or the launchers. We also haven't had confirmation if the issues happen on the stock Pixel OS, which would be useful to know.

**Comment by thestinger** [comment]
It makes sense for us to have an issue open if it doesn't impact the stock Pixel OS since then there's a bug in AOSP impacting a component they don't use so we'll need to deal with it, but it's unclear right now.

**Comment by neunzehnachtneun** [comment]
I am experiencing the same issue with the default launcher on my 6a. Should I open a new issue?

**Comment by thestinger** [comment]
Yes.
