### ISSUE TITLE
gesture issues with non-default launchers in secondary users

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/os-issue-tracker#2526]

**Comment by neunzehnachtneun** [comment]
Might not just a gesture issue but lagging of everything.

https://discuss.grapheneos.org/d/8116-last-update-causes-serious-lags/

I can confirm and have created a bug report in such a situation, but unfortunenately I am not able to read it.

**Comment by marioxabel** [comment]
Gesture navigation with launchers like lawnchair and nova doesnt work

**Comment by krysor** [comment]
Is it just me or does the issue seems to have been resolved? No more problems since one of the latest updates on Pixel 6a.

**Comment by thestinger** [comment]
It should be resolved now.

**Comment by marioxabel** [comment]
Works on pixel 6 now but not on pixel 7 devices. Testing with lawnchair

**Comment by thestinger** [comment]
Should be the same on both, that sounds strange.

**Comment by marioxabel** [comment]
Works on pixel 6, but having problems with my pixel 7.  Works sometimes
