### ISSUE TITLE
APK files downloaded in Vanadium not launching (Install unknown apps is enabled)

### ISSUE THREAD

**Issue by antarctic3431** [GrapheneOS/os-issue-tracker#2528]
Since updating my Pixel 7 (currently on the 2023101100 stable release), I've been encountering an issue when trying to install or update apps via APK downloads.

I don't use Google services, so the few apps that I have installed (such as Proton Mail) need to be manually updated by fetching the latest APK from their website whenever an update rolls out. In the past. my workflow has been:

- Download the APK from, in this example, proton.me, using Vanadium (Incognito mode enabled). The file saves to the Downloads folder. Once downloaded, close Vanadium.

- Open Settings > Apps > Special app access > Install unknown apps > Vanadium > Enable "Allow from this source".

- Open Files > Downloads > Select the downloaded APK and run the update.

- After successfully updating the app, disable installing unknown apps in Vanadium (I only enable it when it's needed).

So far I've never encountered an issue, however, after the Android 14 update, an unexpected message appears:

- Following the same steps above, fetch and download the APK, save the file to the Downloads folder, and enable installing unknown apps in Vanadium.

- Open Files > Downloads > Select the downloaded APK.

Here's where the unexpected message appears.
Despite having "Allow from this source" enabled for Vanadium, a message window pops up which says: 

**"For your security, your phone currently isn't allowed to install unknown apps from this source. You can change this in Settings."** 

On one attempt, this message indicated that the app requiring allowing this permission was "Downloads"; on another attempt, the app was "Sounds".

Never experienced this before. Any advice on how to proceed?

**Comment by thestinger** [comment]
With the way you're opening it, it seems like it's the file manager which needs it.

**Comment by zeroadam** [comment]
I was experiencing this when I updated to 2023100900, though I want say it was mostly showing up as "Sounds" for me. Then after updating the the 2023101100 release, it seems to be consistently showing "Download Manager". However, almost every time, I then get the error "App not installed as package appears to be invalid."

As @antarctic3431 mentions, attempting this via the open action in Vanadium does not prompt for Download Manager permission, but does still result in the invalid package error.

**Comment by antarctic3431** [comment]
Issue was resolved with the 2023103000 update:

> Restore Android 13 behavior for installing APKs from the file manager by requesting permission for the app which created the APK (current Google Files behavior is a bit different and requests permission for Google Files, but the AOSP Files approach seems more useful)
