### ISSUE TITLE
Notifications not shown in quick actions

### ISSUE THREAD

**Issue by eauw** [GrapheneOS/os-issue-tracker#2530]
Before the update to Android 14 whenever an app had notifications I could press long on the app icon to see the notifications listed in the appearing quick actions popup. This is not working anymore. I still get the red dot on the app icon as a notification indicator. But when I long press to open the quick actions popup there are no entries for the notifications.

**Comment by thestinger** [comment]
This appears to have been removed on the stock OS too. It's just not a feature anymore.
