### ISSUE TITLE
Cannot enroll fingerprint on Pixel 7A with Android 14 Builds

### ISSUE THREAD

**Issue by wisnerca** [GrapheneOS/os-issue-tracker#2537]
I just bought a brand new unlocked Pixel 7A and installed GrapheneOS using the webUSB installer (UP1A.231005.007.2023100900). I am utterly unable to enroll a fingerprint. I tried first at initial setup, then several times afterward, including after reboots. I also updated 2023101100 build and the issue persists.

I get to the enroll screen. It detects my finger (the bright white light turns on where I press), and the progress indicator the increases each time I scan my finger. But just before the progress circle gets to half way, I get the following message box: "Can't complete fingerprint setup." "You can try again now or set up your fingerprint later."

I believe this is a bug in the Android 14 builds for the Pixel 7A, and NOT something I'm doing wrong. If people have steps I can use to gather further info using ADB from Windows or Arch Linux or Ubuntu, or another method, please let me know.

**Comment by thestinger** [comment]
Enrolling new fingerprints is still working on the Pixel 7a. It's not a bug in the latest release. You might have broken hardware.

**Comment by thestinger** [comment]
You could gather logs with `adb logcat` or the bug report capture tool. Before doing that, please run `adb logcat -c` to clear the current logs.

**Comment by wisnerca** [comment]
Hmmm, very strange. I ran adb logcat -c, then adb logcat, and while running it I was able to add a fingerprint. Then I tried to add another, and had the same issue as before. Then I killed logcat, ran -c again, then ran logcat again and was able to add again after 2 tries (first one got almost to the end then same error, second try worked.

Is there a "bug" upstream where if it has a lot of trouble reading the prints (perhaps because of my screen cover), it just gives up with my above warning message? That combined with random chance could explain my issues, in which case it is probably an upstream AOSP bug, where it treats a sequence of bad finger print reads as a fatal error for enrollment (that gives a very generic error message) rather than allowing you to keep trying til you get a print added (or at least giving a more specific error message). 

I can try again later and get a log file, but it's a huge mess of data, so I'll need to pipe it to a file and scan through it to make sure there's nothing sensitive in it like MAC addresses. Is this worth the effort, or should I just let it go?

**Comment by thestinger** [comment]
Also, even if the screen seems clean, try cleaning it with soap. There can be dirt which appears transparent but block it reading properly.

**Comment by wisnerca** [comment]
Yes, I have a screen protector. It was brand new the first time I tried to enroll.
This sounds like an issue with AOSP's upstream code not giving the correct error message, not a grapheneos issue, so you should close the ticket. Thanks for your help!
I really hate these new under-screen sensors. Now I see a shadow through the screen when I'm looking at white backgrounds, and they don't work as well, and are harder to use with anything except my thumb.

**Comment by thestinger** [comment]
They're getting better but the advantage of being able to do it without picking the phone up off a surface doesn't really pay off yet.

**Comment by jhiatt** [comment]
I don't know if anyone is going to see this but I had the same problem after getting a new screen and google approved screen protector. After days of trying decided to try just pushing really hard during the scan. It worked.

**Comment by wisnerca** [comment]
I ended up doing much the same thing. It seems like an upstream AOSP bug
that it fails after a certain number of bad fingerprint reads with a
confusing message.
