### ISSUE TITLE
Theme Icon not working

### ISSUE THREAD

**Issue by Zeno394** [GrapheneOS/os-issue-tracker#2538]
Hi,
Just installed latest 14 on my Pixel 6a.
Theme Icon doesnt work properly.  (on Home Screen > Wall paper and style > Theme Icon.
The monocrome Icons have a halo around it. It should be totally transperant.
Im unable to take the screen shot.

Thanks

**Comment by thestinger** [comment]
This can't be reproduced. Need a screenshot and further information. You're using the default launcher, right? Does this happen in the main user?

**Comment by Zeno394** [comment]
Hi, 
Yes I'm using the default launcher. It happens in main user.
I'm unable to take screen shot. Can you show me a way to take screen shot after pulling down drawr? It is possible?
Thanks

**Comment by thestinger** [comment]
Press the key combination for it. Power + volume up.

**Comment by empratyush** [comment]
I am closing this issue as there has not been any activity on this thread.

**Comment by Zeno394** [comment]
Sorry I had my mother having terminal sickness.
But the issue is genuine. I ve just raised it with Screen shots. But it was just closed.

**Comment by empratyush** [comment]
>  Sorry I had my mother having terminal sickness.

I am really sorry to hear that. hope you all are doing fine.

> But the issue is genuine. I ve just raised it with Screen shots. But it was just closed.

can you please share the screenshot ? i will look into it.

**Comment by Zeno394** [comment]
> > Sorry I had my mother having terminal sickness.
> 
> I am really sorry to hear that. hope you all are doing fine.
> 
> > But the issue is genuine. I ve just raised it with Screen shots. But it was just closed.
> 
> can you please share the screenshot ? i will look into it.

Sending you the Screen Shots
![Screenshot_20231021-164658](https://github.com/GrapheneOS/os-issue-tracker/assets/53417098/5285b2f0-8117-4c9b-9fe0-7243eead4dc3)
![Screenshot_20231021-164713](https://github.com/GrapheneOS/os-issue-tracker/assets/53417098/80fb74c7-fea5-43ce-bc07-c5eb8b95e4f5)

**Comment by Zeno394** [comment]
You can see round halo kind of thing around all the monocrome icons  (in first screen shot) and around Network Jio (in green) in second Screen Shot.
Thanks

**Comment by thestinger** [comment]
What do you mean by a halo?

**Comment by thestinger** [comment]
I don't think there's a bug, this is just how Android Material You theme looks.

**Comment by Zeno394** [comment]
Before Android 14 there was no slight tint around icon. There used to be just bare Icon.
