### ISSUE TITLE
"Downloads" doesn't clear up already deleted files

### ISSUE THREAD

**Issue by GY8VSdYYzvL8-K6T** [GrapheneOS/os-issue-tracker#2540]
"Downloads" displays some deleted files that no longer exist on my device. Wiping cache and data for "Downloads", "Download Manager", "com.android.providers.media", and/or "Files" does not resolve the issue.

This is now the third bug related to "Downloads", "Download Manager", "MTP Host", "Sounds" apps that are "effectively part of the same app" that share storage.

**Comment by thestinger** [comment]
This is an app issue.
