### ISSUE TITLE
System UI crashes at random (Pixel 7)

### ISSUE THREAD

**Issue by Whatnoww** [GrapheneOS/os-issue-tracker#2542]
Pixel 7 seemingly at random has the System UI crash. This has been happening since the first Android 14 alpha release, and is currently happening on the [2023101100](https://grapheneos.org/releases#2023101100) build.

Before the System UI has crashed dialogue shows up, the system UI is unresponsive:
- no back gesture
- home navigation works
- notifications don't work

If you navigate home, system UI continuously shows the crash dialogue.

If you lock the phone after these dialogues happen, it will be stuck on the lock screen, unable to unlock the device while the lockscreen displays normally.

Eventually, you'll either need to hard restart the device, or GrapheneOS will restart on it's own, after which, the device will be fine. If it doesn't restart on it's own and you don't hard reset, it doesn't start working after a while so you have an unusable device.

Will try to submit a debug log soon.

**Comment by thestinger** [comment]
Are you using the default launcher?

**Comment by Whatnoww** [comment]
Yes

**Comment by thestinger** [comment]
Please update to the latest release. Also need more information on how you're using the device including whether you use multiple user profiles, etc.

**Comment by thestinger** [comment]
Should be resolved.

**Comment by Whatnoww** [comment]
I believe so actually. Haven't had a repeated incident since you told me to update to the latest. I'll give it another 2 days if it sounds good, cause I could be on a good run.

**Comment by Whatnoww** [comment]
Seems to be ocurring again on the past two releases that went to alpha.
