### ISSUE TITLE
gcam crashes on pixel 6 pro with android 14

### ISSUE THREAD

**Issue by andrew-ld** [GrapheneOS/os-issue-tracker#2548]
grapheneos version: 2023101300
smartphone: pixel 6 pro
gcam version: 9.0.115.561695573.37
compatibility mode: enabled
hardware accelerator: enabled
compat va 39bit: enabled
log: https://gist.github.com/andrew-ld/0bdd0375297c557bb4bd9c2449eadb56

**Comment by thestinger** [comment]
We're unable to reproduce this issue.

**Comment by andrew-ld** [comment]
works with latest gcam version (received update from play store today)
