### ISSUE TITLE
SIM PIN scrambling not working.

### ISSUE THREAD

**Issue by Space-B** [GrapheneOS/os-issue-tracker#2551]
Device: Pixel 5
Build: 2023101300

Since updating to Android 14, PIN Scrambling no longer works when I input my SIM PIN. It did on Android 13.

**Comment by robovoice1** [comment]
Enabling scramble pin input layout does abolutely noting. Same behavior with this setting on and off.
Also tried multiple reboots.

UP1A.231005.007.2023101300
P6pro (raven)

**Comment by q9f** [comment]
Noticed the same on Pixel 4a and Pixel 8.

PIN scrambling works only the SIM input reverted back to normal.
