### ISSUE TITLE
Lockscreen bug, 2 conflicting UIs

### ISSUE THREAD

**Issue by irelativism** [GrapheneOS/os-issue-tracker#2553]
Bug in lockscreen/launcher codebase is triggering a conflict between two diferent UIs. The default orange and black popup window just works while the grapheneOS one, white and blue doesn't work and freezes

Making it impossible to unlock device, only after looping through the custom lock screen UI popup window 4 times on a loop while pressing "lockdown" one is able to reach default AOSP pop-up

Here pictures respectively:
![IMG_20231015_141605](https://github.com/GrapheneOS/os-issue-tracker/assets/75645715/57b5e6d3-32a4-4548-a7bb-99db13f6b040)
![Screenshot_20231015-141436](https://github.com/GrapheneOS/os-issue-tracker/assets/75645715/d29374ac-bf2b-4ce8-bfd8-11c9bdd25b9c)

Cheers for all the work making this project a reality and time and energy reviewing this bug.

Pixel4 (flame)
Android 13
2023100300

**Comment by irelativism** [comment]
Seems like this is duplicated with #2543, but will leave this issue open given other one doesn't note the 2 conflicting lockscreen UIs and I believe that to be the issue that is causing buggy UI here, so will leave it open until further feedback.

**Comment by thestinger** [comment]
@irelativism Toxicity not welcome here.
