### ISSUE TITLE
App closing lags when switching profiles after Android 14 update

### ISSUE THREAD

**Issue by NoisyCoil** [GrapheneOS/os-issue-tracker#2558]
As discussed on the forum by many users (https://discuss.grapheneos.org/d/8116-last-update-causes-serious-lags), the last updates to Android 14 caused serious lagging issues in the closing of apps. What I'm seeing on my Pixel 7a (also observed on 6a, 6 Pro and 7 Pro, see the forum discussion) is responses to app closing gestures lagging for about 5 seconds when I go back to the owner's profile after switching to the secondary profile and keeping it active for a while. Other users say they experience this behavior on multiple profiles (which they use). I cannot confirm this, as I only use a single secondary profile (and never use the owner's).

Could be a duplicate of #2526 since that one's also about gestures and profiles.

Edit: Exiting the lock screen lags too. I don't how the lock screen actually works on Android. If it's an app like on X11, this behavior is consistent with that shown by the other apps.

**Comment by timvak** [comment]
I'm experiencing the same on Pixel 7 mostly when switching back to main profile. Sometimes on other profiles. When the lag sets in I need to reboot it will not recover by itself.

**Comment by timvak** [comment]
> I'm experiencing the same on Pixel 7 mostly when switching back to main profile. Sometimes on other profiles. When the lag sets in I need to reboot it will not recover by itself.

The last update gravely improved the stability.
So far the issue seems to be resolved, I'll report back if the issue returns.

**Comment by jwgn** [comment]
I have the same issue on Pixel 5. After switching back to the Owner Profile, the launcher UI stops responding. Have to lock and unlock, black screen for a while, then the launcher comes back.

**Comment by krysor** [comment]
Is it just me or does the issue seems to have been resolved? No more problems since one of the latest updates on Pixel 6a.

**Comment by timvak** [comment]
So far so good. Not yet 👍 will check for a couple of day more just to be sure.
