### ISSUE TITLE
Duplicate entries in Hotspot & Tethering settings

### ISSUE THREAD

**Issue by q9f** [GrapheneOS/os-issue-tracker#2567]
- Device: shiba (Pixel 8)
- Channel: Stable (Experimental)
- Release: [2023101600](https://staging.grapheneos.org/releases#2023101600)
- Android: 14

Go to Settings > Network & Internet > Hotspot & Tethering, and find the following duplicated entries:

- Wi-Fi Hotspot
- USB tethering
- Bluetooth tethering
- Ethernet tethering
- Wi-Fi Hotspot
- USB tethering
- Bluetooth tethering
- Ethernet tethering

![signal-2023-10-17-090719](https://github.com/GrapheneOS/os-issue-tracker/assets/58883403/7625b5bf-082e-4fa7-b688-6f5a7c580da1)

**Comment by thestinger** [comment]
It's resolved for the next release.
