### ISSUE TITLE
Disable /Android and /Downloads storage restrictions for privacy-friendly App usage

### ISSUE THREAD

**Issue by firefoxlover** [GrapheneOS/os-issue-tracker#2571]
A common problem is this
- SyncThing can't sync the `Downloads` folder
- the `Android` folder is permitted too

[There is a Magisk module](https://github.com/Magisk-Modules-Alt-Repo/NoStorageRestrict) that fixes this problem.

## Why relevant?
GrapheneOS is a platform to use alternative services on. Nonsystem apps can't simply sync your Downloads, or do App Backups. The system should always work with user apps instead of system apps imo though, as they are transparently controlled through permissions.

## Why is this not harmful?
Storage scopes are a way better concept than restricting random folders. I dont get the reasoning for that.
The implementation on the OS level would highly improve GrapheneOSses usability, as currently these weird bugs appear.

Its among the things Google does to nonsystem apps, making them hardly usable, similar to background service restrictions, secure settings or others.

**Comment by empratyush** [comment]
There is many other ways to implement this functionality without requiring os level changes.

[you can read about it here](https://developer.android.com/training/data-storage/manage-all-files)

> Other use cases—such as file manager apps, backup and restore apps

**Comment by firefoxlover** [comment]
so the solution is to grant apps access over **all** files, just because /Android and /Downloads are not writable? 

with /Android that is understandable, but it makes no sense for /Downloads

**Comment by thestinger** [comment]
Storage Scopes exists.

**Comment by firefoxlover** [comment]
@thestinger okay so the solution would be 
1. have the app use the "access all files" permission
2. restrict it anyways using storage scopes

This is interesting, a bit weird but well.
