### ISSUE TITLE
App icon badge does not reveal notifications

### ISSUE THREAD

**Issue by scarecrow1636** [GrapheneOS/os-issue-tracker#2575]
Touching and holding the app icon displaying notification badge (also known as notification dot) does not reveal notifications since upgrading to Android 14. Notifications are only visible in notification drawer as well as on the left side of the status bar.

2023101300 (Pixel 6a)

**Comment by sec-oops** [comment]
I think this is a duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/2530 ?

**Comment by scarecrow1636** [comment]
> I think this is a duplicate of #2530 ?

Apparently yes. I should've searched more thoroughly.
