### ISSUE TITLE
VOIP app (cheogram) and audio output device issue

### ISSUE THREAD

**Issue by rkraken** [GrapheneOS/os-issue-tracker#2577]
I'm using cheogram app with the jmp.chat VOIP service and I'm noticing a strange problem with the audio output.  There's an option in the app to enable integration with the native android dialer, which enables using the android dialer to make calls through the jmp.chat account rather than using the SIM. 

The problem occurs with using a bluetooth headset with dialer integration enabled.  Audio for other apps (spotify, etc) works as expected when connected.  However, once I initiate a call with cheogram, the output device will switch from the headset to the phone speaker after 1-2 rings. After hanging up, audio output immediately returns back to my headset.  

Often, there will be no audio output at all, and a few times it rapidly oscillated back and forth between outputs. Sometimes it will work properly the first time, then fail for all calls afterwards. The problem also occurs when receiving calls - as soon as I answer, sound will switch from headset to phone speaker (or often no output).  It seems to be an audio device switching issue and not the bluetooth connection.

After turning off android dialing integration, directly using the cheogram app to dial calls works properly with no switching away from the headset.  

I experienced this problem on a Pixel 5 and also still after a recent upgrade to Pixel 7, both running GrapheneOS.   I ran the same test on a phone with LineageOS and it does not have this problem, working as expected.

I've also downloaded and used other android dialer apps instead of the default grapheneOS dialer and the problem still persists.

I have a vague recollection of similar problems previously with a different VOIP app (Linphone) - it was while ago and I might had assumed that the app itself was buggy.  I don't remember the exact details, but I mention this as the problem could be occurring with other VOIP calling apps.

**Comment by m4teh** [comment]
I spent hours recently determined to beat this identical experience. Figured it out eventually, after pretty much trying every possible option.

Permit 'Nearby Devices' in Cheogram permissions :)

**Comment by thestinger** [comment]
Seems like an issue with the app requiring a permission on modern Android but not requesting it.

**Comment by m4teh** [comment]
It does request that permission. We are probably the bunch to trigger finger deny these permissions by default generally however. At least that's what I had done at install and first launch. And then try figure out the edge case experiences l later, like this. Some apps work fine without it, adding to it's obscurity.

**Comment by thestinger** [comment]
I don't think it should need that permission for this, so you're right to deny it, but it's for them to resolve.

**Comment by rkraken** [comment]
> I spent hours recently determined to beat this identical experience. Figured it out eventually, after pretty much trying every possible option.
> 
> Permit 'Nearby Devices' in Cheogram permissions :)

Hi - I had already enabled this permission in the course of my troubleshooting.  But unfortunately it doesn't work for me.  Does it consistently solve the problem for you?  I noticed that audio output works properly the first 1 or 2 calls after enabling integration, then fails afterwards.

**Comment by rkraken** [comment]
This problem has been fixed in the latest Cheogram release version 2.15.3-1.
