### ISSUE TITLE
Swedbank app stop working after OS update

### ISSUE THREAD

**Issue by CalicoOI** [GrapheneOS/os-issue-tracker#2578]
```
type: ANR
osVersion: google/barbet/barbet:14/UP1A.231005.007/2023101300:user/release-keys
package: lt.swedbank.mobile:21541
process: lt.swedbank.mobile
installer: com.android.vending

activity: lt.swedbank.mobile/com.swedbank.mobile.app.MainActivity
cause: ANR Input dispatching timed out (ec6dc68 lt.swedbank.mobile/com.swedbank.mobile.app.MainActivity (server) is not responding. Waited 5005ms for MotionEvent)
info: ANR in lt.swedbank.mobile (lt.swedbank.mobile/com.swedbank.mobile.app.MainActivity)
PID: 7736
Reason: Input dispatching timed out (ec6dc68 lt.swedbank.mobile/com.swedbank.mobile.app.MainActivity (server) is not responding. Waited 5005ms for MotionEvent)
Parent: lt.swedbank.mobile/com.swedbank.mobile.app.MainActivity
ErrorId: 281d414e-4e7b-484f-bcd8-a22e070aa401
Frozen: false
Load: 1.02 / 1.14 / 1.36
----- Output from /proc/pressure/memory -----
some avg10=0.00 avg60=0.05 avg300=0.02 total=252470050
full avg10=0.00 avg60=0.00 avg300=0.00 total=137219292
----- End output from /proc/pressure/memory -----
----- Output from /proc/pressure/cpu -----
some avg10=2.93 avg60=2.72 avg300=1.32 total=1950805335
----- End output from /proc/pressure/cpu -----
----- Output from /proc/pressure/io -----
some avg10=0.03 avg60=0.16 avg300=0.12 total=483517959
full avg10=0.01 avg60=0.09 avg300=0.07 total=345043973
----- End output from /proc/pressure/io -----

CPU usage from 0ms to 14486ms later (2023-10-19 15:42:47.856 to 2023-10-19 15:43:02.342):
  60% 7840/lt.swedbank.mobile: 24% user + 36% kernel
  59% 7736/lt.swedbank.mobile: 1.4% user + 57% kernel / faults: 905 minor 7 major
  7.9% 1748/system_server: 4% user + 3.9% kernel / faults: 18984 minor 870 major
  4.4% 4328/com.android.systemui: 2.9% user + 1.5% kernel / faults: 18698 minor 632 major
  2.2% 129/kswapd0: 0% user + 2.2% kernel
  2.2% 6929/kworker/u16:14-kverityd: 0% user + 2.2% kernel
  1.8% 4594/.qtidataservices: 0.8% user + 0.9% kernel / faults: 3871 minor 3690 major
  1.7% 5952/com.android.nfc: 0.9% user + 0.7% kernel / faults: 4115 minor 2933 major
  1.5% 4751/com.android.phone: 0.8% user + 0.6% kernel / faults: 2043 minor 1171 major
  1.4% 6765/kworker/u16:7-kverityd: 0% user + 1.4% kernel
17% TOTAL: 5% user + 11% kernel + 0.1% iowait + 0.2% irq + 0.1% softirq
CPU usage from 90ms to 464ms later (2023-10-19 15:42:47.946 to 2023-10-19 15:42:48.321):
  60% 7736/lt.swedbank.mobile: 4% user + 56% kernel / faults: 3 minor
    64% 7736/swedbank.mobile: 4% user + 60% kernel
  56% 7840/lt.swedbank.mobile: 16% user + 40% kernel
  30% 1748/system_server: 10% user + 20% kernel / faults: 435 minor
    30% 7894/AnrAuxiliaryTas: 10% user + 20% kernel
  8% 129/kswapd0: 0% user + 8% kernel
  7.7% 6929/kworker/u16:14-memlat_wq: 0% user + 7.7% kernel
  2.6% 72/rcuop/7: 0% user + 2.6% kernel
19% TOTAL: 4.5% user + 14% kernel

```

**Comment by robovoice1** [comment]
https://github.com/PrivSec-dev/banking-apps-compat-report/issues/12

**Comment by vytskalt** [comment]
Same issue.

**Comment by akc3n** [comment]
@CalicoOI and @vytskalt 

Please see https://discuss.grapheneos.org/d/8330-app-compatibility-with-grapheneos for a step-by-step walkthrough for possible workaround solutions. 

Thanks @robovoice1

**Comment by vytskalt** [comment]
> @CalicoOI and @vytskalt
> 
> See [App compatibility with GrapheneOS](https://discuss.grapheneos.org/d/8330-app-compatibility-with-grapheneos) — a step-by-step walk through for possible workaround solutions.
> 
> Note: It's plausible that this is app-related, rather than a compatibility issue with GrapheneOS - acknowledging this factor must be considered.
> 
> Thanks @robovoice1

I tried the possible workarounds you linked and they didn't fix it. The app wasn't updated recently and stopped working for me around a week ago (presumably caused by the Android 14 update). I haven't changed anything in the settings during that time.

**Comment by CalicoOI** [comment]
> > @CalicoOI and @vytskalt
> > See [App compatibility with GrapheneOS](https://discuss.grapheneos.org/d/8330-app-compatibility-with-grapheneos) — a step-by-step walk through for possible workaround solutions.
> > Note: It's plausible that this is app-related, rather than a compatibility issue with GrapheneOS - acknowledging this factor must be considered.
> > Thanks @robovoice1
> 
> I tried the possible workarounds you linked and they didn't fix it. The app wasn't updated recently and stopped working for me around a week ago (presumably caused by the Android 14 update). I haven't changed anything in the settings during that time.

Disable of native code debugging helped me to solve the problem

**Comment by vytskalt** [comment]
> > > @CalicoOI and @vytskalt
> > > See [App compatibility with GrapheneOS](https://discuss.grapheneos.org/d/8330-app-compatibility-with-grapheneos) — a step-by-step walk through for possible workaround solutions.
> > > Note: It's plausible that this is app-related, rather than a compatibility issue with GrapheneOS - acknowledging this factor must be considered.
> > > Thanks @robovoice1
> > 
> > 
> > I tried the possible workarounds you linked and they didn't fix it. The app wasn't updated recently and stopped working for me around a week ago (presumably caused by the Android 14 update). I haven't changed anything in the settings during that time.
> 
> Disable of native code debugging helped me to solve the problem

That worked but it breaks some other programs (Smart-ID)

**Comment by AndrejsK** [comment]
> @vytskalt
> That worked but it breaks some other programs (Smart-ID)

Native code debugging can now be disabled for an individual app, by the way. This completely solved the issue for me :)

**Comment by b4n6-b4n6** [comment]
Swedbank app works with native code debugging disabled except notifications and biometric login
Smart-ID works ONLY if I open swedbank and smart-id in split screen and login WHILE they are in split screen

**Comment by vytskalt** [comment]
NFC payments stopped working after Android 15, app says "Loading failed" when you try to set them up. Does anybody else have this issue?
