### ISSUE TITLE
Keyboard replaces numbers with spaces.

### ISSUE THREAD

**Issue by q9f** [GrapheneOS/os-issue-tracker#2580]
pixel 8 (shiba) with grapheneos (android 14) build 2023101900

- use default keyboard to type a number followed by a space removes the number again

maybe an autocorrect issue?

https://github.com/GrapheneOS/os-issue-tracker/assets/58883403/35a67415-d16e-49b0-9282-f65194b3bf41

**Comment by empratyush** [comment]
Can you please confirm you are still having this issue? I am unable to reproduce this on my pixel 7.

**Comment by q9f** [comment]
Yes, however, it only happens in one specific app (Element Matrix) - so I guess it is related to that app not the keyboard.
