### ISSUE TITLE
Error flashing Pixel 7pro

### ISSUE THREAD

**Issue by firefoxlover** [GrapheneOS/os-issue-tracker#2582]
I am on Fedora, where the instructions are a bit different

```
groupadd plugdev
usermod -aG plugdev $USER

sudo dnf install -y android-tools signify unzip cat wget
fastboot --version
#fastboot version 33.0.3p1-android-tools
#Installed as /usr/bin/fastboot

mkdir -p ~/Downloads/Grapheneos && cd ~/Downloads/GrapheneOS
curl -O https://releases.grapheneos.org/factory.pub
wget https://releases.grapheneos.org/cheetah-factory-2023101300.zip
wget https://releases.grapheneos.org/cheetah-factory-2023101300.zip.sig

signify -Cqp factory.pub -x cheetah-factory-2023101300.zip.sig && echo "true" &&\
unzip cheetah-factory-2023101300.zip && rm -f cheetah-factory-2023101300.zip &&\
cd cheetah-factory-2023101300 &&\
.flash-all.sh
```

This did nothing, as for some reason fastboot still does not work, while ADB works.

So I used root,

```
sudo -i
./flash-all.sh
```

Everything started going until that happened:

```
--------------------------------------------
Bootloader Version...: cloudripper-14.0-10529422
Baseband Version.....: g5300q-230626-230818-B-10679446
Serial Number........: 28251FDH3005WH
--------------------------------------------
extracting android-info.txt (0 MB) to RAM...
Checking 'product'                                 OKAY [  0.000s]
Checking 'version-bootloader'                      OKAY [  0.000s]
Checking 'version-baseband'                        OKAY [  0.000s]
fastboot: error: device requires partition vendor_kernel_boot which is not known to this version of fastboot
```

I saw in the flash all script there is a check for the fastboot version. And I already flashed my Pixel 4a with this method? Why is this happening, did the requirements increase for some reason?

I will try with the binaries from Google and see if that works

**Comment by thestinger** [comment]
Fedora uses an unofficial build system for fastboot. The version they packaged was built incorrectly using outdated code. Our version check is still correct. Their fastboot is broken due to the unofficial build system. The issue was fixed in that unofficial project but Fedora didn't ship the update.

**Comment by firefoxlover** [comment]
okay, I already followed the instructions to link the official binaries to the bash path and it installed normally.

Interestingly the first boot it didnt start but boot to recovery where I did a factory reset. Now it has booted normally!

**Comment by thestinger** [comment]
@firefoxlover It sounds like you didn't lock the device.

**Comment by firefoxlover** [comment]
thanks, right. I guess this is an "anti-brick" measurement to not include it in the flash script?

Btw would you be interested in a Fedora version? I would write it. The packages are all called differently and I dont get these "bsd" which are not there on Fedora. I would simply not install android-tools at all and just use the official binaries.

**Comment by thestinger** [comment]
> thanks, right. I guess this is an "anti-brick" measurement to not include it in the flash script?

In some cases you don't want to lock such as development.

> Btw would you be interested in a Fedora version? I would write it. The packages are all called differently and I dont get these "bsd" which are not there on Fedora. I would simply not install android-tools at all and just use the official binaries.

Does Fedora have signify now? It should be possible to add it into the guide then. It just needs to say to use the official platform-tools, etc.

**Comment by firefoxlover** [comment]
yes signify is there since forever, was a year or so ago.
