### ISSUE TITLE
Unable to Grant Health Connect Permission on Pixel 8 - 20231019 Build

### ISSUE THREAD

**Issue by starraiderx** [GrapheneOS/os-issue-tracker#2583]
In the 20231019 build for the Pixel 8, there seems to be a problem regarding the health and connect feature. When attempting to grant apps the health connect permission, clicking on the permission option has no effect. Please refer to the attached screenshot for more clarity.

![Screenshot_20231019-203923~2](https://github.com/GrapheneOS/os-issue-tracker/assets/33199500/0f8f8793-2fbd-479b-b6f2-3816ce1e294a)

App used in this example: MyFitnessPal

Kind regards

**Comment by liamolua** [comment]
Not a answer to your issue apologies but have you tried/successful in setting up Google Fit on your phone? Mine keeps claiming that `Fit is having trouble connecting to google play services` even though, I have sandbox apps installed *sandbox permission issie maybe?*.

**Comment by starraiderx** [comment]
I've configured Google Fit on my device, and it functions as expected (e.g., step counting).


For your particular problem: Ensure that all Google Play services permissions are granted. This resolved the error on my end.

**Comment by liamolua** [comment]
> I've configured Google Fit on my device, and it functions as expected (e.g., step counting).
> 
> For your particular problem: Ensure that all Google Play services permissions are granted. This resolved the error on my end.

Cheers mate, I'll enable all then disable one by one that I think isn't needed until I find the troublesome permission.

Also had a look, my health connect permission works fine, maybe try going into `Settings>Privacy>Health connect *all the way down at the bottom*` and adding permissions that way.

**Comment by liamolua** [comment]
> Also had a look, my health connect permission works fine, maybe try going into `Settings>Privacy>Health connect *all the way down at the bottom*` and adding permissions that way.

You can also try Google's Health Connect from thebolay store if its just an issue with that one app. Not sure if that will fix your issue but worth a shot

**Comment by starraiderx** [comment]
Fixed as of 2023110700.
