### ISSUE TITLE
Allow accepting USB audio peripherals while locked

### ISSUE THREAD

**Issue by strugee** [GrapheneOS/os-issue-tracker#2587]
Problem: I have 3.5mm headphones, so I'm constantly using Google's USB-C to 3.5mm adapter. This counts as a USB peripheral, which means that unless I "allow new USB peripherals" in Settings > Security > USB peripherals, I can't plug in my headphones and have them start working without unlocking my phone. Doing this multiple times daily gets super annoying which is why I have this setting set to "allow new USB peripherals".

However, this is almost always the only USB peripheral I plug in. Therefore I would love to have an option to require unlocking for any USB peripheral that _didn't_ identify itself as an audio device, to reduce attack surface while still keeping my device  usable for audio. It's unclear to me how _much_ this reduces attack surface - it might be that it's so little that introducing this option would give users a false sense of security, which would obviously be bad.

Note that the Pixel Tablet's connection with the dock also appears to use USB and therefore is affected by this setting. I had 5-10 seconds of confusion today when I docked it, it didn't switch audio to the dock, and I assumed that Graphene had broken the feature, before I remembered this setting and tried it again with the tablet unlocked.

**Comment by thestinger** [comment]
This is the feature working the way it was designed and I don't think it makes sense to make an exception for it. By the time the type of peripheral can be detected, it's too late to serve the purpose.
