### ISSUE TITLE
no 5g connectivity on GrapheneOS latest update..

### ISSUE THREAD

**Issue by maanz79** [GrapheneOS/os-issue-tracker#2588]
Hi.
I installed GrapheneOS latest release/update on my Pixel 7 few days ago. Before this, i used/tested android 14 QPR1 beta 2 and i was able to get 5g connection. However on GOS, there is no 5g connectivity (Preferred network type is set to 5G (Recommended)). A user from GOS matrix chatroom told me to reset mobile network and re-add my carrier's APN which i have done so. But still, there is no 5g. I noticed that the operator settings version has changed from 400000000xx to 5000000002 after reset. Does anyone knows of any solutions? Or is it my carrier limiting its network?
Thanks..

**Comment by thestinger** [comment]
No indication of a bug rather than the carrier not having this supported with Pixels.
