### ISSUE TITLE
USB passthru and permissions for u2f

### ISSUE THREAD

**Issue by GrapheneDating** [GrapheneOS/os-issue-tracker#2596]
I am hoping developers will find a way (or share one) that allows USB C security keys like Yubikey and Nitrokey to be utilized for webauth on sites such as Proton Mail or Tutanota.

Vanadium's "use phone as a security key" 
leveraging the Titan chip appears only to apply to Google 2FA

More can be found here. Thanks!
https://support.nitrokey.com/t/nitrophone-u2f-usb-c-email/5531/1

**Comment by thestinger** [comment]
It already works in apps supporting it.

**Comment by thestinger** [comment]
Chromium and many other apps currently implement FIDO2 via a Play services library which is missing if you don't have sandboxed Google Play. There are alternatives available. https://play.google.com/store/apps/details?id=de.cotech.hw.fido.browser is an example demonstrating that it can be done without that. We plan to implement an alternative implementation for Vanadium which is tracked in the Vanadium issue tracker already.
