### ISSUE TITLE
"Optimizing apps 2 of 2" after each reboot

### ISSUE THREAD

**Issue by gerrix1701** [GrapheneOS/os-issue-tracker#2602]
Since updating to 2023102300 GrapheneOS is showing "Optimizing apps 2 of 2" after each reboot, then I need to tap to restart those apps. Upon first boot after upgrading there were around 50 apps to optimize, after all following reboots those 2 still show up. Unfortunately, I don't know which apps. I have sandboxed Google Play running, Pixel 7a.
Of course it's not a big deal, just a little annoying and I guess it's not supposed to work like this?

**Comment by gerrix1701** [comment]
It seems this happens if you update or install new apps. Upon next reboot those new apps will be optimized.

**Comment by h-h-** [comment]
Same on Pixel 6a. Optimizing 2 apps occurs after every reboot. Independent of previous app install/update.
How to determine which apos are optimized?

**Comment by robovoice1** [comment]
i had optimising apps (1/1) message and after newest update and 3 times rebooting this message is gone😄
pixel 6 pro raven UP1A.231005.007.2023103000

**Comment by thestinger** [comment]
It sounds like you had one which took a long time to optimize and weren't waiting long enough/

**Comment by h-h-** [comment]
At least with update to [2023110700](https://grapheneos.org/releases#2023110700) the issue has gone.
