### ISSUE TITLE
Airplane mode behavior change

### ISSUE THREAD

**Issue by scarecrow1636** [GrapheneOS/os-issue-tracker#2604]
I don't know whether this behavior is expected or not, but ever since Android 14, each time I turn on Airplane mode, my phone remember the previous setting and connects to one of the "Saved" networks when in range, which apparently [mirrors](https://support.google.com/pixelphone/answer/12639358?hl=en) stock Pixel OS way of doing things. This behavior, however, differs from GrapheneOS Android 13 port and, I believe, Android 12 too. Prior to Android 14, toggling Airplane mode resulted in disabling both Wi-Fi and Bluetooth, irrespective of any "Saved" networks.

This is accompanied by two notifications from Android System, one for when you first toggle Airplane mode, and another one for when you enable it this next time.

![Screenshot_20231020-191204](https://github.com/GrapheneOS/os-issue-tracker/assets/147932510/1b26be1e-4f2b-4238-8b17-89e2056ebff8)
![Screenshot_20231020-210029](https://github.com/GrapheneOS/os-issue-tracker/assets/147932510/d3e794aa-8b3f-4e11-a8cd-96109496e17c)

Bluetooth behaves the same way (remembers to stay on and displays two similarly worded notifications).

Screenshots are from 2023101300, but the behavior is also observed on the latest 2023102300 (Pixel 6a).

**Comment by thestinger** [comment]
This is intended. Airplane mode is primarily for disabling cellular radio. If you turn off Wi-Fi it will remember you want Wi-Fi off in airplane mode from last time.
