### ISSUE TITLE
Location Possibly Broken in 2023102300 inside Work/Clock App Paylocity

### ISSUE THREAD

**Issue by ilikenwf** [GrapheneOS/os-issue-tracker#2606]
Filing on behalf of my dad, he has a Pixel 7a with the google services compatibility layer enabled. Until just a few days ago he was able to clock in and out of his work's clock app, Paylocity (https://www.apkmirror.com/apk/paylocity/paylocity-mobile/)

Location wise, he can see his location and movements if he opens up a mapping app.

I had him try an old version, and ensured that he had high precision location enabled, but the application now just spins and says "Waiting for location updates..."

Has anything changed in 2023102300 that would have affected or caused this by chance?

![image](https://github.com/GrapheneOS/os-issue-tracker/assets/414778/1261b819-8949-4f55-980c-5cbe050b17bf)
![image](https://github.com/GrapheneOS/os-issue-tracker/assets/414778/357e837c-9a3a-422b-a528-61391c89a0dc)
![image](https://github.com/GrapheneOS/os-issue-tracker/assets/414778/92adfee3-e013-4c68-9459-e32c19800fd1)

**Comment by thestinger** [comment]
> Filing on behalf of my dad, he has a Pixel 7a with the google services compatibility layer enabled. Until just a few days ago he was able to clock in and out of his work's clock app, Paylocity (https://www.apkmirror.com/apk/paylocity/paylocity-mobile/)

Please check sandboxed Google Play compatibility layer configuration. Disabling location re-routing isn't correct if you don't set up Google Play location services. Some apps may require actual network location.

> Has anything changed in 2023102300 that would have affected or caused this by chance?

No.

**Comment by ilikenwf** [comment]
He hasn't altered any settings related to location, nor any play layer configs, and so I'm at a loss then when it comes to determining what could be causing it unless the app itself is awful.

**Comment by thestinger** [comment]
Check that location rerouting is enabled.

**Comment by thestinger** [comment]
If it's enabled, you could try using the sandboxed Google Play network location instead as a test:

https://grapheneos.org/usage#sandboxed-google-play-configuration

**Comment by ilikenwf** [comment]
Apparently, rerouting was not enabled. I have him trying again.

**Comment by ilikenwf** [comment]
I'm going to tentatively call it closed, he lives in a dead zone and so I'll have to follow up with him tomorrow. Thank you and apologies.
