### ISSUE TITLE
Auto-restart feature broken with recent update.

### ISSUE THREAD

**Issue by ViktorKahu** [GrapheneOS/os-issue-tracker#2608]
I have my phone set up to auto-reboot if not unlocked for 4 hours.

Lately, (after the last update), I've been waking up to find my phone shut down (not rebooted).

As far as I know, I have not done anything to cause this behavior change. No new software has been installed recently.

Dangerous on a work day if alarm does not go off due to phone shut down.

I wonder if it's related to #2489...?

Pixel 7 pro
2023102300

**Comment by thestinger** [comment]
This is likely a hardware issue. Nothing we can do about how the device behaves when the OS isn't running. It's likely not related to #2489.
