### ISSUE TITLE
Unable to share wifi (qr and share nearby)

### ISSUE THREAD

**Issue by chrispable** [GrapheneOS/os-issue-tracker#2609]
While migrating my device to graphene, I am trying to connect to wifi with credentials saved in qr codes or from another device. Scanning the qr code (in owner profile and secondary user with sandboxed Google play) in the camera simply shows the data, and I can manually transcribe as a workaround. When receiving the network via share nearby to a secondary profile with sandboxed Google play, after some time and fuss, the days transfer goes through, attempts to connect to wifi and a toast that it failed to connect is shown.

**Comment by thestinger** [comment]
This is done by scanning via the add network option in the Wi-Fi settings. It's not supported by the camera app.

**Comment by thestinger** [comment]
Sandboxed Google Play isn't a privileged app on GrapheneOS and can't do privileged things regular sandboxed apps can't do.

**Comment by thestinger** [comment]
This is done by scanning via the add network option in the Wi-Fi settings to scan the QR code. It's not supported by the camera app.

Sandboxed Google Play isn't a privileged app on GrapheneOS and can't do privileged things regular sandboxed apps can't do.

It would be possible to add more functionality to the camera app including privileged features but that's not a priority and lack of more sharing options isn't a bug.
