### ISSUE TITLE
Password autofill attempts to save system passwords in Android 14

### ISSUE THREAD

**Issue by metronidazole** [GrapheneOS/os-issue-tracker#2612]
Since updating to Android 14 I've noticed the password autofill system (with keepass2android) trying to save inappropriate passwords such as the phone's lockscreen password (e.g. when entering fingerprint settings). This didn't use to occur with Android 13.

I'm guessing it's an android/system issue not my PW manager since the autofill service is run by the OS.

**Comment by thestinger** [comment]
No indication of there being any GrapheneOS specific issue here or it not being an app limitation. Autofill services have to do a lot of work.
