### ISSUE TITLE
Fundamental U2F webauth method needed (browser function)

### ISSUE THREAD

**Issue by GrapheneDating** [GrapheneOS/os-issue-tracker#2613]
Although some apps/clients (i.e. Tutanota Mail) can utilize U2F Security Keys (i.e. Yubikey) when all 3 Google Play+Services+Framework are enabled, the more universal approach of a supportive browser (like the recommended but deprecated "U2F Browser" from de.cotech) would accomplish more. The Proton Mail app does not currently support security key U2F like the Tutanota app. Perhaps code from Brave Browser that supports security keys well could be used to provide Vanadium with this functionality.
![IMG_20231026_192738](https://github.com/GrapheneOS/os-issue-tracker/assets/148663953/3253939e-59a4-41cb-89f1-cee09489dbb8)

**Comment by thestinger** [comment]
There's already an issue filed in the Vanadium tracker for FIDO2 without Play services. This would ideally be done as a library usable by any apps and doesn't need to be GrapheneOS specific. Ideally AOSP would have it in a mainline module. It's very unfortunate that it was implemented in Play services before there were mainline modules.

**Comment by thestinger** [comment]
See https://github.com/GrapheneOS/Vanadium/issues/61.
