### ISSUE TITLE
Android 14 critical data access/loss bug with multiple profiles?

### ISSUE THREAD

**Issue by lyphyser** [GrapheneOS/os-issue-tracker#2617]
It appears that there is a critical bug in Google's Android 14 images that can cause inability to mount the main profile and perhaps corrupts the data when using multiple profiles: https://issuetracker.google.com/issues/305766503

Is GrapheneOS affected?

Unless GrapheneOS is definitely not affected, it may be wise to remove all Android 14 releases as soon as possible from stable and beta channels and possibly issue an Android 13 rollback release.

**Comment by thestinger** [comment]
There are no known issues like this. Anecdotes from people using a different operating system aren't a valid reason to file an issue report and certainly aren't going to result in rolling back important security patches and other improvements. This issue tracker is for GrapheneOS, not unconfirmed stock Pixel OS issues.
