### ISSUE TITLE
No Valid OS Found

### ISSUE THREAD

**Issue by Bluztravlr** [GrapheneOS/os-issue-tracker#2621]
Graphene on Pixel7 will not boot and says a "valid" os could be found. ID: 8b2c4cd5 Code:5

**Comment by thestinger** [comment]
It's a known firmware issue. Rebooting will resolve it. It's outside the scope of GrapheneOS.

**Comment by Bluztravlr** [comment]
Thanks for the info, helped me solve the issue. As a complete novice and first time Graphene user, I always appreciate being pointed in the right direction.

Sent from Proton Mail mobile

-------- Original Message --------
