### ISSUE TITLE
sometimes "open website" is shown when captive portal is not passed, "log in" should be shown

### ISSUE THREAD

**Issue by firefoxlover** [GrapheneOS/os-issue-tracker#2625]
"log in" launches the captive portal chromium intent (I guess?) that bypasses the VPN and allows to log in.

"open website" only works when you are already logged in, and will open the default browser, that will use a VPN when enabled.

Sometimes instead of the "log in" button the "open website" one is shown, which in my Case opens Mull and that doesnt work.

I think its a bug of the system falsely thinking it had an internet connection, even though every HTTP request would still be redirected to the Captive Portal.

**Comment by thestinger** [comment]
Not entirely clear what you mean but the OS captive porting handling isn't available for all types of captive portals.

**Comment by thestinger** [comment]
This is likely working as intended and the same way it works in the stock OS.

**Comment by firefoxlover** [comment]
it is always fixed by disconnecting and connecting again. The "open website" normally shows AFTER you connected, and the system has internet, but it is not true here. 

GrapheneOS uses custom Captive servers and connectivity check, and I also dont have an AOSP device to check. I cant exclude this is not GrapheneOS specific.

**Comment by thestinger** [comment]
@firefoxlover You can test with the standard connectivity check servers on GrapheneOS.

**Comment by thestinger** [comment]
> Also I dont get why "likely working" would be a valid reason to immediately close?

This can certainly be caused by the network's setup and there currently isn't a reason to think it's a GrapheneOS issue.

**Comment by firefoxlover** [comment]
Yeah, my "specific" setup would be using a VPN and logging in to random public wifis. This occurs on many Wifis and it is a general problem, as using a VPN in (not encrypted) public Wifis is a security measurement.

This has to be either an Android or a GrapheneOS issue. I will try to use the Google Captive Server and see if that solves it.

**Comment by flawedworld** [comment]
Several captive portals break when using Private DNS, you may wish to turn this off and test if this remediates the issue.

**Comment by firefoxlover** [comment]
this may very well be the origin. But as Private DNS normally never works at all with Captive portals, I just always assumed the systems Captive portal opener used some very insecure DNS given by the DHCP server, as that one knows the URL to the captive portal
