### ISSUE TITLE
Pixel 8 -> Pixel 6a - no coll goes out when caller ID is set to show number

### ISSUE THREAD

**Issue by BluePixel4k** [GrapheneOS/os-issue-tracker#2626]
I have a problem between my new Pixel 8 and the Pixel 6a with calling (on both phones GrapheneOS is installed).
Pixel 8: I changed the caller ID from "Network default" to "Show number", so that everyone can see my number when I call. 
<img src="https://github.com/GrapheneOS/os-issue-tracker/assets/77979781/55381505-34f6-4227-926e-9c5c41afed49" width="200" />
Now I can call nearly everyone without problems, but not the Pixel 6a. No call go through, the voicemail goes directly on. Calling from the Pixel 6a to the Pixel 8 is working fine. The error also occurred with the Pixel 8 stock OS. 
With my Pixel 5 (also GrapheneOS), there were no problems making calls to the Pixel 6a in the past (same SIM cards).
For testing purposes I put one SIM from the Pixel 6a in the Pixel 5 and I can call the Pixel 5 from the Pixel 8 without problems.

If I change the caller ID to "Hide number" or "Network default" (both settings doing the same) I can call the Pixel 6a from the Pixel 8 without problems. But this is not a solution for me because the other party cannot see my number (unknown caller).

I don't now, If this bug is related to GrapheneOS, android upstream or the mobile operator. Is this bug known?

Thanks in advance!

**Comment by thestinger** [comment]
This sounds like a carrier issue.
