### ISSUE TITLE
Pixel Watch can not connect to phone

### ISSUE THREAD

**Issue by LaluSys** [GrapheneOS/os-issue-tracker#2629]
Since installing Graphene OS it is not possible to connect the Pixel Watch with the Pixel Watch App, not in the main profile and also not in a secondary profile. 

Sometimes the watch app says that the google services app requires acess to nearby devices, even when the permission is granted. Also in the bluetooth paring process, there are multiple attemps to connect and new pairing codes get showed multiple times but it always fails again. 

I can provide more information if you tell me which ones you need :)

**Comment by thestinger** [comment]
You need to grant the Nearby devices permission to Play services and the app.

**Comment by LaluSys** [comment]
Thanks for the fast repliy, i did both.

**Comment by LaluSys** [comment]
Okaay it is resolved. 

Its important to do the intial pairing with the watch on graphene os and not on stock and then to swap to graphene. So if you paired the watch on stock first, you have to factory reset it to be able to pair it on graphene. 
After this, it works just fine also in a secondary profile. <3
