### ISSUE TITLE
Replace Google SIM Manager with OpenEUICC

### ISSUE THREAD

**Issue by dot-gov** [GrapheneOS/os-issue-tracker#2631]
I tried OpenEUICC (https://gitea.angry.im/PeterCxy/OpenEUICC) on pixel 6a and all the basic functionality (add/scan/enable/disable/delete esims) works fine. If we add this app to grapheneos, we can get rid of the dependency on google's proprietary sim manager. At the very least it should be added so users don't have to install google play services for esims.

**Comment by thestinger** [comment]
It's not currently complete. We have https://github.com/GrapheneOS/os-issue-tracker/issues/1079 filed about it.
