### ISSUE TITLE
Lock screen - clock touches the fingerprint reader circle

### ISSUE THREAD

**Issue by BluePixel4k** [GrapheneOS/os-issue-tracker#2636]
At the Pixel 6a on the lock screen, the clock touches the fingerprint reader circle, because the clock is placed lower then it should be.

Pixel 6a:
<img src="https://github.com/GrapheneOS/os-issue-tracker/assets/77979781/bc6003db-808d-4138-8c0d-806f1061381c" width="200" /> 

Pixel 8 (in relation):
<img src="https://github.com/GrapheneOS/os-issue-tracker/assets/77979781/62881a59-4c0a-4cba-991a-3622b67545ae" width="200" /> 
 
Newest GrapheneOS versions are installed on both. The bug already occurred with the Android 13 releases.

**Comment by robovoice1** [comment]
![Screenshot_20231101-152207](https://github.com/GrapheneOS/os-issue-tracker/assets/92784377/33973e8d-561d-4309-bcb2-506826234370)
pixel 6 pro raven

**Comment by mrxx0** [comment]
![Screenshot_20231101-154242 1](https://github.com/GrapheneOS/os-issue-tracker/assets/18289987/c3af5f07-ae0f-4e3c-a0ec-f661a653e090)

No issue on 6a running 2023103100

**Comment by thestinger** [comment]
Seems fixed.
