### ISSUE TITLE
[pixel 6a] Global problem with recording videos and taking pictures

### ISSUE THREAD

**Issue by pawelsu8** [GrapheneOS/os-issue-tracker#2637]
### Graphene OS release + hardware
Phone: Pixel 6a
Firmware: [2023103100](https://grapheneos.org/releases#2023103100)

Installed Google services: yes
Installed Google framework: yes
Installed Google play: yes

### Brief summary
1. The Google Camera app crashes immediately upon launch.
2. Trying to record a video longer than 2s on Snapchat causes the app to crash completely.
3. Trying to record a video longer than 2s on Whatsapp causes the app to crash completely.
4. Trying to record a video longer than 2s on signal causes the app to crash completely.
5. Trying to record a video longer than 2s on signal causes the app to crash completely.
6. Trying to record a video longer than 2s on Molly causes the app to crash completely.
7. Trying to send a recorded video through the whatsapp app is impossible - sending stops at the "sending..." stage.
8. Trying to send a recorded video through the messenger app is impossible - sending stops at the "sending..." stage.
9. Trying to send a recorded video through the Signal app is impossible - sending stops at the "sending..." stage.
10. Trying to send a recorded video through the Molly app is impossible - sending stops at the "sending..." stage.

11. Video recording WORKS only in the pre-installed Graphene Camera app.

### Expected behavior
The function of recording and sending video via external applications should work properly. The video recording and sending function stopped working when the first version of Android 14 was automatically installed in October 2023.

[EDIT] I am attaching a system trace in which I ran Google camera twice and received an immediate crash twice. 

[trace-bluejay-UP1A.231005.007-2023-11-01-11-14-14.perfetto-trace.txt](https://github.com/GrapheneOS/os-issue-tracker/files/13225804/trace-bluejay-UP1A.231005.007-2023-11-01-11-14-14.perfetto-trace.txt)

**Comment by mrxx0** [comment]
Can't reproduce the issue of Google Camera (now called Pixel Camera btw).
6a running **2023103100** with Sandboxed Google Play 23.43.13 installed
Tested on Pixel Camera version 9.0.115.561695573.37

**Comment by thestinger** [comment]
You have a broken or outdated variant of Google Camera and have it set as the default. There is no longer an app called Google Camera but rather it's called Pixel Camera. You need to install a working variant of it. Aurora Store installs the wrong variants of apps by default, if that's where you obtained it.
