### ISSUE TITLE
Pixele 6a: No way to remove the esim card from the phone. 

### ISSUE THREAD

**Issue by pawelsu8** [GrapheneOS/os-issue-tracker#2638]
![Screenshot_20231101-110350](https://github.com/GrapheneOS/os-issue-tracker/assets/102968699/52a3a7ef-a9a5-4b24-a1ef-728188ea5eba)
![Screenshot_20231101-110354](https://github.com/GrapheneOS/os-issue-tracker/assets/102968699/8c1adcd2-bd98-48a2-a8a3-856a4f1c1708)
![Screenshot_20231101-110356](https://github.com/GrapheneOS/os-issue-tracker/assets/102968699/b01cfcbf-613d-438f-abfb-a8abebc1fbe4)

**Comment by thestinger** [comment]
You need to enable privileged eSIM management for this.
