### ISSUE TITLE
KDE Connect - Not working!

### ISSUE THREAD

**Issue by DavidRLTG** [GrapheneOS/os-issue-tracker#2639]
Salutations!
Basically, KDE Connect refuses to work with my PC on GrapheneOS. I'm on a Google Pixel 8.
I have the same VPN, same server running on my PC and my Phone. When on, it doesn't connect. When off, it still doesn't connect.
My computer doesnt show up on my phone, my computer doesn't see my phone.
It works on my older phone which has ArrowOS on it. VPN on or Off, still works. The phone is a Poco F3.
If it matters, my computer is up to date, and running Xubuntu.

**Comment by thestinger** [comment]
This is caused by your VPN app not supporting allowing local network connections. It either doesn't have support for the option or doesn't do it properly. It's not a GrapheneOS issue. It's likely your older phone doesn't have a working leak blocking toggle or you didn't enable it.

**Comment by thestinger** [comment]
> Yeah but I turned off the vpn on both devices, still didnt work.

You need to disable it as a VPN completely. Disabling it within the app won't disable it as an active VPN in the OS, and blocking leaks is enabled by default and will still be happening.

**Comment by DavidRLTG** [comment]
Hm. Alright! but, I do wonder
Why'd it work with my old phone though?-

**Comment by thestinger** [comment]
You had a different setup. You'll need to figure out what's wrong. Turn off Private DNS if that's enabled.

**Comment by DavidRLTG** [comment]
Well, I disabled Private DNS, and also disabled blocking connections outside VPN in Android settings. Still no help! Darn.
Well still, Thanks for the help!

**Comment by thestinger** [comment]
Try removing it as an enabled VPN completely temporarily and try rebooting.

**Comment by DavidRLTG** [comment]
Apparently, 1.1.1.1 Warp has an Excluded Apps setting. Adding KDE Connect there fixed it!
Thanks for your help dude!

**Comment by thestinger** [comment]
Does the excluded apps feature work when blocking leaks is enabled?

**Comment by DavidRLTG** [comment]
You mean the Android VPN Setting thing? Well, Everything seemed to be working but then I realised..
My PC is connected, but no feature of KDE Connect works! Gosh, Tech is hard xd

**Comment by DavidRLTG** [comment]
And now it randomly works again! With VPN on, KDE Connect excluded, Android's block connections outside VPN setting off
God, tech is weird now!

**Comment by Chalsean** [comment]
Just adding a comment incase anyone stumbles across this thread in the future.  I had this issue with GrapheneOS and ProtonVPN.  I had to do three things:

1. By default GrapheneOS will scramble your MAC, this was causing my router to repeatedly move it to my default isolated subnet where they could not see each other.  In Settings / Network & internet / Internet / (WiFi SSID) / Privacy : switch to "Use device MAC"
2. Needed to add KDE Connect as an excluded application to VPN tunneling (aka split tunneling) so it could see local network
3. Under Settings / Network & internet / VPN / (Provider) : turn off "Block connections without VPN"
