### ISSUE TITLE
External Display Indicator

### ISSUE THREAD

**Issue by McIrco95** [GrapheneOS/os-issue-tracker#2641]
I dont see any indecation on screen of an external display being conected. That opens the possibility of capturing a screen recording when connected to what is believed to be a charging cable. The fact that the default is that the screen gets mirrored and most keyboards show the keys being pressed makes capturing passwords possible

I think when casting the screen with cromecast there is a notification and an indicator. There schould be something similar when conecting an external display

**Comment by thestinger** [comment]
@McIrco95 Did something change? Why close it?

**Comment by McIrco95** [comment]
Fixed upstream
![Screenshot_20231216-075232](https://github.com/GrapheneOS/os-issue-tracker/assets/115875304/aae6f6fc-0ef6-4616-b4de-08388e3a6b6c)
![IMG_20231216_075406](https://github.com/GrapheneOS/os-issue-tracker/assets/115875304/473a241b-4fed-4977-a7d7-1cd03d0a083e)
