### ISSUE TITLE
Minor tweak request

### ISSUE THREAD

**Issue by jayb-g** [GrapheneOS/os-issue-tracker#2642]
I see that in keyboard input languages, there are many but still a few missing like especially for India there are Hindi, Marathi etc present but some other like Punjabi, Gujarati are missing. Although I receive texts in those languages just fine.I need to use(type in) specifically these two but not able to. And I don't want to use a third party keyboard to use those languages.

I believe maybe AOSP already supports it so it might be easy to add? I don't know if it's only GrapheneOS related or AOSP related issue.

Thanks.

**Comment by empratyush** [comment]
It is not supported by upstream aosp keyboard.

**Comment by jayb-g** [comment]
If I do have to use a third party keyboard for that? Any recommendations ?

**Comment by thestinger** [comment]
Don't have a particular recommendation. It depends on what you want.
