### ISSUE TITLE
Fingerprint Missing on Pixel 6a

### ISSUE THREAD

**Issue by epplebepple** [GrapheneOS/os-issue-tracker#2644]
On my Pixel 6a (latest GrapheneOS) the option to use fingerprint sensor has been missing for a while now. So there is no fingerprint on lockscreen but also in privacy settings the fingerprint is not showing as an option. Therefore i cannot select it or play with the settings or integrate new fingerprints.
I have read about this issue not only for this phone or OS but as a common issue with different android devices. So far i haven't come across a fix and i guess hoped that some OS update will fix it randomly. 

From others threads i have read that even resetting the phone does not fix. Are there any solutions here?

**Comment by thestinger** [comment]
Not likely that this is a software issue. You could confirm via factory reset or by trying stock OS but that would be inconvenient.
