### ISSUE TITLE
Display only connects with device locked

### ISSUE THREAD

**Issue by McIrco95** [GrapheneOS/os-issue-tracker#2645]
My anker hub only connects to the display when i connect it while the phone is locked and the display is on. But then usb and Ethernet do not work. If i conect with the device unlocked its the opposite.  

Allow usb is set to allow usb when device is unlocked

**Comment by thestinger** [comment]
This is normal. USB has different modes. The device can't be both a peripheral and use USB devices at the same time. Our toggle is for controlling peripherals.
