### ISSUE TITLE
Feature request: Erase phone when alternative password is entered. 

### ISSUE THREAD

**Issue by gsture** [GrapheneOS/os-issue-tracker#2651]
I have the following feature request: An option to erase the phone when an alternative password is entered. You have a default password and a panic password for when someone is forcing you to enter the password or forcing you the hand it over. If you type in the panic password the phone will imidiatelly reboot and factory reset.

**Comment by flawedworld** [comment]
https://github.com/GrapheneOS/os-issue-tracker/issues/29

**Comment by flawedworld** [comment]
1.
