### ISSUE TITLE
com.abdroid.sdksanbox contains malicious code

### ISSUE THREAD

**Issue by manooll** [GrapheneOS/os-issue-tracker#2656]
Today Avast automatic scanner reported that sdksandbox contains malicious code (reported as malware risk). Please check and resolve as it seems suspicious.

**Comment by zWhdmB5T** [comment]
> Today Avast automatic scanner reported that sdksandbox contains malicious code (reported as malware risk). Please check and resolve as it seems suspicious.

maybe (I personally think probably) false positive?

**Comment by zWhdmB5T** [comment]
Have you tried other scanners like Kaspersky, Sophos or Malwarebytes? (These are the only ones I actually like a bit somehow — besides the raison d'être of scanners at all…)

**Comment by flawedworld** [comment]
Assuming you actually mean ```com.android.sdksandbox ``` - this is a false positive, and a good example of why most "antivirus" solutions on Android devices are almost useless.
