### ISSUE TITLE
Android 3 buttons menu at the bottom freezes sometimes

### ISSUE THREAD

**Issue by zWhdmB5T** [GrapheneOS/os-issue-tracker#2658]
### system:
* Google Pixel 6a
* Android 14
* Build Number UP1A.231005.007.20231003100
* no additional launcher/menu installed
* system configured to common 3 buttons menu (f.l.t.r. triangle, circle, square) at the bottom

### bug experience
* I come from #1857, esp. [my comment at #1857](https://github.com/GrapheneOS/os-issue-tracker/issues/1857#issuecomment-1793411335)
* now, the origin issue (full display freezes) seems to be resolved
* but I experience: sometimes, the 3 buttons menu at the bottom freezes. The rest of the display (all above the 3 buttons menu) stays usable. But I cannot use the 3 buttons menu at the bottom in those situations

### work-around (that works for me)
* press power button to lock screen
* press power button again to activate and show up fingerprint reader
* use fingerprint reader to login again
* continue regular use (also the use of 3 buttons menu at the bottom is available again)

### additional info
* I generated debug logs right after the issue occurred recently. See attachments.
[bugreport-bluejay-UP1A.231005.007-2023-11-05-23-21-15.zip](https://github.com/GrapheneOS/os-issue-tracker/files/13265565/bugreport-bluejay-UP1A.231005.007-2023-11-05-23-21-15.zip)
[bugreport-bluejay-UP1A.231005.007-2023-11-05-23-21-15-dumpstate_log-14910.txt](https://github.com/GrapheneOS/os-issue-tracker/files/13265566/bugreport-bluejay-UP1A.231005.007-2023-11-05-23-21-15-dumpstate_log-14910.txt)
[dumpstate-stats.txt](https://github.com/GrapheneOS/os-issue-tracker/files/13265567/dumpstate-stats.txt)
(Hope this is of some help, somehow.)

**Comment by LunchBoxC** [comment]
I'd like to confirm I noticed this on my Pixel 7a as well.  I just assumed it was the current app freezing those buttons.  Thanks for posting this.

**Comment by zWhdmB5T** [comment]
Phew, I'm not alone…

**Comment by MKBontwikkeling** [comment]
Same here

**Comment by zWhdmB5T** [comment]
But I have to admit, that it's not very often, at least.

**Comment by thestinger** [comment]
Is this still an issue on the latest releases?

**Comment by LunchBoxC** [comment]
I'm not seeing it on: 2023120800 on my Pixel 7a

**Comment by zWhdmB5T** [comment]
> Is this still an issue on the latest releases?

I actually don't really know since this issue has only occurred seldom. It has occurred several times, yes, but actually not very often and I cannot reproduce the circumstances. I will have an eye on it.

**Comment by MKBontwikkeling** [comment]
Doesn't seem to be an issue anymore on my P7pro

**Comment by thestinger** [comment]
All these problems in 14 seem solved now in 14 QPR1.

**Comment by thestinger** [comment]
All these launcher/gesture problems in 14 seem solved now in 14 QPR1.
