### ISSUE TITLE
Unexpected message when installing or updating apps via APK

### ISSUE THREAD

**Issue by antarctic3431** [GrapheneOS/os-issue-tracker#2672]
Recently started receiving an unexpected message during app installation / update with apps being installed / updated via APK files. The installation / update process appears to be successful from what I can tell.

Example: Proton VPN, downloaded directly from https://protonvpn.com/. The APK is downloaded using Vanadium, saved to the Downloads folder, and accessed via the Files app (com.android.documentsui).

Opening the APK file brings up the usual message: _Do you want to update this app_? The app icon and app name both display as Proton VPN.

After the update concludes, the unexpected message appears: **App installed - com.protonvpn.android.ProtonApplicationHilt**.

Meanwhile, if examining the Proton VPN application using Settings > Apps > Proton VPN, the app shows ch.protonvpn.android, which is correct.

**Comment by thestinger** [comment]
You have some software installed showing this message.
