### ISSUE TITLE
(Bug) No search results in settings for "themed icons" (beta)(android14)(android13)

### ISSUE THREAD

**Issue by robovoice1** [GrapheneOS/os-issue-tracker#2676]
Type in settings search "themed icons", 
Result is: No search results

I activated themed icons before, (settings, wallpaper and style, home screen), but simply forgot where i did this  .  LOL

This was already the case in android 13, but the position for enabling/disabling changed. 

Google Pixel 6 pro raven
UP1A.231105.003.2023110700

**Comment by thestinger** [comment]
We aren't going to change the indexing for standard options. This isn't part of Settings which is why it doesn't show up.
