### ISSUE TITLE
Creating QR Code Scanner shortcut not possible with standard camera app (android14)

### ISSUE THREAD

**Issue by robovoice1** [GrapheneOS/os-issue-tracker#2677]
Settings, display, lockscreen, shortcuts
Result is:
- Creating a camera and video camera shortcut is possible.
- tapping on the greyed out qr code scanner icon results in the message:
 Can t add shortcut, make sure a camera app is installed.

The Gos standard camera app has already qr code scanning functionality.

Google Pixel 6 pro raven
UP1A.231105.003.2023110700

**Comment by thestinger** [comment]
Lack of a feature being implemented is not a bug.

**Comment by empratyush** [comment]
need to resolve [#394](https://github.com/GrapheneOS/Camera/issues/394) first.

**Comment by empratyush** [comment]
fixed long time ago.
