### ISSUE TITLE
(Bug) Unresponsive keyboard shortcuts in settings search(android14)

### ISSUE THREAD

**Issue by robovoice1** [GrapheneOS/os-issue-tracker#2678]
Type in "keyboard" in settings search
Tap on keyboard shortcuts in the search results.
Result is:
Flashing keyboard shortcuts field, but nothing else happens.

In android 13, a new screen with "use on-screen keyboard" switch and "keyboard shortcuts" is displayed.
Tapping on keyboard shortcuts opens another screen with home, back, recents, and so on ........

Google Pixel 6 pro raven
UP1A.231105.003.2023110700

**Comment by thestinger** [comment]
@robovoice1 Is this still an issue on the latest release?

**Comment by robovoice1** [comment]
Yes ,tried with UQ1A.231205.015.2023120800 alpha release with p6pro with the same result as before.

**Comment by robovoice1** [comment]
I re tested this with 2024030800 release:

Keyboard shortcuts can not be found in os settings search and appear to be removed.

![Screenshot_20240309-131102](https://github.com/GrapheneOS/os-issue-tracker/assets/92784377/8901f10d-a2f4-4260-b2d4-f641ee72346d)
