### ISSUE TITLE
Feature request: "Record everything" option

### ISSUE THREAD

**Issue by luke-jr** [GrapheneOS/os-issue-tracker#2680]
Audio compression is pretty good. It might be nice to just record everything always, potentially split into files by hour/day/event for another app to prune later.

Maybe even the cameras? Store the last few seconds in RAM at full quality (which can be made to persist if the user desires) and gradually degrade until it's very small before writing to flash.

**Comment by thestinger** [comment]
You can use an app which runs a foreground service and records with the camera and/or microphone. It needs to provide a way to give up control of the camera to other apps. We don't plan to implement an app doing this since we have our hands more than full already.
