### ISSUE TITLE
No clear way to determine what commit of talkback was used for a build

### ISSUE THREAD

**Issue by flawedworld** [GrapheneOS/os-issue-tracker#2683]
It's not clear in https://github.com/GrapheneOS/platform_external_talkback/ which commit of https://github.com/GrapheneOS/talkback was used to make a build. This is necessary for build automation code which aims to build a 1:1 copy of GrapheneOS.

**Comment by thestinger** [comment]
It was the latest release but I added a tag.

**Comment by thestinger** [comment]
The latest revision was the current one but I've added a tag.
