### ISSUE TITLE
Spport for Slovenian Spell Checking in AOSP Keyboard

### ISSUE THREAD

**Issue by nimdajitam** [GrapheneOS/os-issue-tracker#2687]
Hi,

This is a feature request. Willing to help if pointed to helpful resources. Thanks in advance.

Please add support for Slovenian spell checking and suggestions in AOSP keyboard.

Dictionaries for spell checking, suggestions and even synonyms are available at (from Libre Office): 

https://extensions.libreoffice.org/en/extensions/show/slovenian-dictionary-pack?Tags%5B%5D=undefined

**Comment by thestinger** [comment]
You're welcome to work on it but we aren't going to leave issues open about AOSP keyboard improvements.
