### ISSUE TITLE
some feedback. three little annoying things i m facing after using graphene over 2 years

### ISSUE THREAD

**Issue by t4wE** [GrapheneOS/os-issue-tracker#2689]
First thanks to all the developers for maintaining this project. I think it's very important to have open projects like this these days.

So, as the title implies, I just want to provide some user feedback after I have been using GrapheneOS for a while. I am like 99% satisfied with everything, there are just some small things that bring my attention, so i wanted to share and hope they might get fixed.

1. Double-line clock bug:

It's not native for me, so I disabled it.
But when switch to another user (say, with GPS installed) and then return to main user, the double-line clock is there again. The toggle switch indicates that it is off (Settings > Display > Lock screen > Double-line clock), but it's actually not, so I have enabled>disable it each time I return from another user.

3. Internet menu slide

So I usually use mobile data, but once I am at work/home I switch to Wi-Fi. I slide from the top, push the Internet button, and now I am at the Internet menu. The Mobile data toggle switch is on. I natively want to turn on Wi-Fi first (it's closer to my thumb finger) so I do it, and I am now aiming at Mobile data toggle switch to disable it. But if I am too slow, the available Wi-Fi menu pops up and the whole thing slides up, and now my thumb is misplaced and i have to aim higher. 

Yeah, there are two obvious solutions:
1. Not to be slow and hit it instanly, before it slides up
2. Turn off the mobile data first

However, I personally feel like that whole window is supposed to be initially adjusted more to the top, so no matter how chaotically i toggle the switches, they don't change their initial position.

4. Mobile data toggle switch for another user.

This one is a picky one, i rarely face it, but still i thought it is worth mentioning.
I am not able to turn on mobile data as another user. I sometimes switch to a user that has GPS installed to use an app that can't work without it. But if i forgot to initially turn Mobile data on while on the main user profile, i cant do it and i have to switch back again. This is obviously for security seasons, but in my case i am the only owner of the phone, I use both profiles only by myself. Maybe it is worth making and option to allow it. 

That is it.
Thanks to everyone involved with this project. Hope my feedback helps.

**Comment by thestinger** [comment]
There have been existing issues filed about these upstream issues.

We don't plan to change how the mobile data toggle works at the moment.
