### ISSUE TITLE
GOS A14 task switching disfunctional after updates

### ISSUE THREAD

**Issue by commandline-be** [GrapheneOS/os-issue-tracker#2690]
After a few updates over the recent week or so the issue where the task switching hangs got a lot worse. Until some work around is used (opening volume settings, opening settings) to arrive back at the start screen there is no way to switch apps. There also has to be a strange side-ways slide involved to pull up the task windows.

In my experience this improved to an almost non-issue for unknown reasons. It is clearly this is an overlay issue as I've also had "ghost states" where the pin-code entry dialog was transparently visible and the underlying apps were accessible regardless.

At this point, I honestly would not know if this device is compromised or not. I hold on to the fact the task switching issue was there after install on this newly purchased device (7a) which had zero prior install but the factory OS.

**Comment by thestinger** [comment]
There are already issues filed about gesture and recent app regressions in Android 14. This has nothing to do with a compromise.
