### ISSUE TITLE
[Feature Request] Torch shortcut

### ISSUE THREAD

**Issue by lucidtanooki** [GrapheneOS/os-issue-tracker#2691]
Hi. Thanks for this great OS! 

Now on to my subject, I know you already rejected the idea in #636 but I'd like to add some thought on that and kindly ask you to reconsider your decision. Unfortunately the discussion has been closed on the other issue, therefore I cannot comment without opening a new one.

Let's take a look at the smartphone as one of the greatest tools these days. If we take a few of its features like calling people, browsing the web and taking photos there is a fourth great feature: the torch. Artificial light is one of humankind's greatest achievements and having such a useful feature at your disposal as part of the phone, is simply fantastic.

Therefore I think having a rather real-world tool for real-world situations (pressing a button for light) is in my opinion a good idea. I know there are the fast settings - there a a few problems with that:

+ if I need the torch I usually need it quickly - long press comes in handy here
+ if in the dark using the screen shuts your iris causing a longer time until your eyes adjust
+ I often want to use the torch to light something without taking my eyes from it - which is not possible when having to use the screen (keyword: losing context)
+ when wearing gloves of any type the button can still be pressed, touchscreen again is difficult - especially when having the second hand occupied (or not having a second one)

I guess this won't change your opinion on the subject - but on the other hand, why not? 

Please consider it. As long as button long press is not used anyways - why not for that? And if you want to use it for something different later - you could still give users the choice.

Best regards,
Lucidtanooki

PS: Keep up the great work!

**Comment by akc3n** [comment]
Hi @lucidtanooki,

The short answer is basically that unless the AOSP does it, then it most likely is not going to happen, and it's not the project's focus to add features like keybindings.

Appreciate the thorough, detailed examples you provided, as well as the time and effort you put into explaining the benefits.

Thank you kindly.

**Comment by thestinger** [comment]
You can make a lockscreen shortcut for this now. We can enable adding multiple lockscreen shortcuts.
