### ISSUE TITLE
Make PixelNfc app optional, provide it in Apps instead of pre-installed

### ISSUE THREAD

**Issue by universorum** [GrapheneOS/os-issue-tracker#2697]
I am studying how to enable FeliCa on non-Japanese Pixel devices. And I noticed that most Pixel devices already meet the FeliCa hardware requirements. The only thing that make non-Japanese Pixel device unable to use FeliCa is the `com.google.android.pixelnfc` app.

The provider `content://com.google.android.pixelnfc.provider.DeviceInfoContentProvider/isJapanSku` must return `1` to enable the FeliCa function.

In this time, PixelNfc is ship from stack and pre-installed. It mean:

1. Unavailable to uninstall this app
It is a system application and thus cannot be uninstalled.

2. Unavailable to install self own app with same provider URL:
Can not install a new application that declares a provider with conflicting URL until uninstall an old one.

3. Unavailable to decompile and patch the apk, adding your SKU to whitelis
Not possible as Android requires app overwrites/updates to have the same signature.

Because all these reasons, user can not enable FeliCa on non-Japanese Pixel devices unless him root his device.

Maybe we can make PixelNfc app is optional and provide it on Apps. So any user who already own the Japanese Pixel device can install stock app to enable the function. Other user can find some way to make the function enabled by himself without root device.

**Comment by thestinger** [comment]
We aren't going to take this approach.
