### ISSUE TITLE
Allow to add apps to Special Access to Hardware Accelerators

### ISSUE THREAD

**Issue by popogomo** [GrapheneOS/os-issue-tracker#2698]
This is a feature request.

The Special Access to Hardware Accelerators option allows specific apps, such as Google Camera, Photos and Recorded, to have direct access to hardware accelerators which dramatically improves the speed of these apps.

However, it doesn't allow to add custom apps to the list, specifically - GCam which is a modified and enhanced version of stock Google Camera and offers extra features, for example, better image resolution (Max vs Full in stock camera), which results in better pictures.  Without access to Hardware Accelerators, the GCam works very slow and it takes ages to process images, just like the stock Google Camera without Hardware Accelerator access. 

Therefore, can you please add a possibility to allow us to add custom apps to have access to hardware accelerators? Thanks.

**Comment by gsture** [comment]
You will probably get the not going to happen or code it yourself comment but for what it's worth I think this would be useful.

**Comment by muhomorr** [comment]
"Special access to hardware accelerators for Google apps" setting doesn't define the list of apps that it applies to.

This list is instead defined in a proprietary system process (`vendor.google.edgetpu_app_service`) that some Google apps interact with to obtain that special access. When "Special access to hardware accelerators for Google apps" setting is disabled, access to that proprietary process is blocked.

**Comment by joopdo** [comment]
Same question raised here: https://discuss.grapheneos.org/d/1815-google-camera-very-slow-portrait-mode-processing/91
