### ISSUE TITLE
Wallpaper get stretched 

### ISSUE THREAD

**Issue by itsdivyanshjain** [GrapheneOS/os-issue-tracker#2705]
Every time I try to set wallpaper on either lock or home screen, it's got stretched ("This kind of thing are not get noticed when we have black wallpaper"). Also, I confirmed it is not wallpaper & it's length issue.

Device: pixel 6a

**Comment by thestinger** [comment]
On the main user or another user? It works the same as on the stock OS.

**Comment by itsdivyanshjain** [comment]
> On the main user or another user? It works the same as on the stock OS.

all user

**Comment by itsdivyanshjain** [comment]
> It seems that this bug has recently been fixed. Wallpaper can now be set properly with no stretch.

yeah validated, issue is fixed now
