### ISSUE TITLE
Does a Bluetooth Security Key actually work?

### ISSUE THREAD

**Issue by jradxl** [GrapheneOS/os-issue-tracker#2706]
Pixel 6a, latest version GrapheneOS Android 14.
Thetis BLE security key USB A with Bluetooth.
Key does Pair with Bluetooth in the conventional manner.

Trying to add using Chrome or the via Android setup, a Google email address with 2FA enbabled and this Thetis key registered, just results in an hanging page,
"Verifying it's you", Complete sign-in using your security key.

Using Brave browser (which would only provide a sign-in to the browser, and not Android), I do get further.
I get the choice dialog where I can select Bluetooth, NFC and USB keys.
If I choose USB then the login works.
If I choose Bluetooth, the next page is a request pair the key, which hangs.

Tried clearing caches, reinstalling various things and rebooting, but I never get any further than above.

It's worse with nornal Android 13 on my Samsung and Xiaomi phones, where I never get a Bluetooth option with the Brave browser, and similar hanging with Chrome etc,

Perhaps Security Key logins are fundamentally broken, and I can only complete logins (such as the initial login to a Factory reset phone) with 2FA turned off.

Anyone any thoughts?

**Comment by jradxl** [comment]
I've got a bit further with the Vanadium browser.
On the google.co.uk home page and choosing sign-in from top right, with an account with 2FA enabled, does give me a Security Key choice of three, Bluetooth, NCF, USB. The later two work although it might take multiple tries.
In the case of the Bluetooth the Paring page opens and the pairing succeeds (it's necessary to do it on that page, even if it's already registered within Bluetooth in the OS). The page then tries to validate, but fails with there is a problem, and repeats that if it is tried again without requesting a re-pairing.

**Comment by SirPanOfTheCake** [comment]
@jradxl Had similar issues with NFC security keys, see #2089 . Just checking you do have sandboxed play services installed on your GOS phone? I would check out #2089 troubleshootin steps I've done.

**Comment by thestinger** [comment]
Did you give the nearby devices permission to Play services?

**Comment by IPlayZed** [comment]
> Did you give the nearby devices permission to Play services?

@thestinger I have nearby devices permissions access to play services (the permissions seems to apply to other use cases), but it always fails for me. I scan the code with the stock camera app, open the link via Google Play services, scan the QR code and at this point the phone seems to try to connect to my laptop, but instantly shows the screen "Something went wrong, Restart the process on your other device to try again". The computer waits a bit, seemingly not registering any input from the phone.

The funny thing is that the browser (ungoogled chromium) seems to register that I scanned the QR code with the phone, and saves my phone into the used devices. It is just that the key registration itself fails for some reason.

I only tried this for my Windows 11 laptop, where I have Windows Hello disabled, as I use a local account. AFAIK, that is independent of this though.

If some more input is needed to solve the issue, please contact me on the issue, I am happy to help, as this would be a huge usability improvement.

**Comment by IPlayZed** [comment]
I also tried on my Linux device, same problem. This functionality is basically broken. The issue should be reopened and looked into what causes this.

**Comment by IPlayZed** [comment]
![Screenshot_20240121-194417.png](https://github.com/GrapheneOS/os-issue-tracker/assets/21132316/a29025fb-efe0-48c5-a7ba-7be60f5731b8)

![Screenshot_20240121-194410.png](https://github.com/GrapheneOS/os-issue-tracker/assets/21132316/44ada014-957d-46dd-b2ab-5ad960d02f39)

![Screenshot_20240121-194421.png](https://github.com/GrapheneOS/os-issue-tracker/assets/21132316/d16339c3-b1df-444c-a528-2db40cbfb9f6)

I also can't seem to add it locally from Vanadium :/

**Comment by thestinger** [comment]
Passkeys are not supported yet.

**Comment by thestinger** [comment]
FIDO2 security keys work, passkeys do not. Passkeys are not supported yet.

**Comment by IPlayZed** [comment]
> FIDO2 security keys work, passkeys do not. Passkeys are not supported yet.

This is rather interesting, because I could create and authenticate one time in Vanadium. After some times (idk if I changed something manually) it stopped working.

Even when using the official Pixel images passkey support is unreliable at the best, sometimes registration works when initiated from the PC browser, sometimes it had to be added through the mobile browser.

Sorry for the verbosity, but just to be clear, how are FIDO2 security keys supposed to be different from Passkeys?

**Comment by L11R** [comment]
@IPlayZed from website standpoint they are mostly the same, sure. But from OS standpoint they are completely different and use various system APIs.
