### ISSUE TITLE
Arch Linux + Web USB Installer + fwupd issue

### ISSUE THREAD

**Issue by codemodify** [GrapheneOS/os-issue-tracker#2708]
1. follow steps up to flashing the image
2. it reboots a few times as described then there is the error in red in the browser about "claim interface", I did not make a screenshot after that
3. got stuck on this every time when I was retrying the flashing operation
4. the dmesg shows the error that `fwupd` is trying to access it as well
5. flashing succeeded only after stopping the `fwupd` service

![Screenshot from 2023-11-22 21-24-15](https://github.com/GrapheneOS/os-issue-tracker/assets/44710208/b2ce23c1-452d-4c1c-82ce-3be68975ab84)

**Comment by thestinger** [comment]
Thanks, we'll add this to the guide.

**Comment by thestinger** [comment]
@codemodify Can you please file this at https://github.com/fwupd/fwupd/issues? It's a fwupd bug. It shouldn't connect to USB devices like this.

**Comment by thestinger** [comment]
I filed an issue with fwupd.
