### ISSUE TITLE
Unable to update Pixel 6a (to Android 14)

### ISSUE THREAD

**Issue by rafaelsgirao** [GrapheneOS/os-issue-tracker#2709]
My Pixel 6a with GrapheneOS at Android 13 (compilation number TQ3A.230901.001.2023100300 ) is unable to install any new OS updates. The Updater app automatically downloads an update, a notification appears letting me know an update will be installed when my phone restarts. 

The problem is, after my phone starts again, no update has taken place, and the Updater app proceeds again downloading the same update. I have also noted my phone reboots at least once or twice during updates (I'm not sure if this is intended or not), and may consume large amounts of battery ( I've seen from 5% to ~35% drops after it boots again).
This endless cycle (because AFAIK there is no option to pause or stop automatic updates, please correct me if I'm wrong ) continues for as many times as I reboot my phone. I have also tried setting the update channel to beta and alpha, but this didn't fix the issue.

Currently I had to disable the Updater App's network permission so it wouldn't try to download an update after each boot.

The only solution I am aware of is to reinstall GrapheneOS, but I would really prefer to only do this if there is absolutely no other way to address this issue.

**Comment by orazioedoardo** [comment]
You can try sideloading the update from recovery: https://grapheneos.org/usage#updates-sideloading

**Comment by thestinger** [comment]
You should try resetting app preferences via Settings before you update in case you changed a setting in a way that breaks booting the new OS version. You should also try sideloading, but it probably won't make a difference. If neither of those things works, you probably need to try reinstalling the OS. It's not clear from this info if this is a hardware, firmware or software issue and it's not really actionable for us.

**Comment by de0u** [comment]
For whatever it might be worth at this late date, I just updated a 6a from TQ3A.230901.001.2023100300 straight to UQ1A.231205.015.2023123100.  The process was 100% as expected, taking 23 minutes from when the download started until the "App restart required" notification.

**Comment by rafaelsgirao** [comment]
> For whatever it might be worth at this late date, I just updated a 6a from TQ3A.230901.001.2023100300 straight to UQ1A.231205.015.2023123100. The process was 100% as expected, taking 23 minutes from when the download started until the "App restart required" notification after the reboot.

Thanks for your feedback. I tried updating yesterday after reading your comment (re-enabled Network permission), and it updated successfully on the first try (just one reboot). I'm now on latest stable again.

> but it probably won't make a difference. If neither of those things works, you probably need to try reinstalling the OS. It's not clear from this info if this is a hardware, firmware or software issue and it's not really actionable for us.

For what it's worth now, I attempted sideloading an update through recovery, but it failed as you predicted. But I did capture a full adb logcat of the device soft-looping after the recovery's failed update - there seems to be a service constantly crashing. I can paste a trimmed version if anyone's interested.

**Comment by thestinger** [comment]
@rafaelsgirao Please open a new issue about that.

**Comment by thestinger** [comment]
@rafaelsgirao If you currently have any crashes, please open a new issue about that. If everything is fine, no need.
