### ISSUE TITLE
Screen locking is not working in the app (Automate)

### ISSUE THREAD

**Issue by nazar-pc** [GrapheneOS/os-issue-tracker#2710]
I'm using https://llamalab.com/automate/ for some automation on my phone, but ever since upgrading from Android 13 to Android 14 screen locking no longer works with it.

Developer confirmed that it works for them on another Android 14-based OS, so might be something related to Graphene OS specifically in this case.

The locking that requires a pin code works, but "Interact Lock Screen (Android 9+)" block in there that locks the screen without requiring pin code (just fingerprint is sufficient) doesn't do anything.

I have granted app all the permissions necessary to the best of my knowledge.

**Comment by thestinger** [comment]
GrapheneOS doesn't change anything relevant to this, so the assumption that it's a GrapheneOS introduced compatibility issue is unlikely to be correct.

**Comment by nazar-pc** [comment]
GrapheneOS appears to be the most likely cause here because it works on another Android 14-based OS just fine. And it did work on GrapheneOS when it was based on Android 13 too.

Can you provide some debugging steps that would help to confirm or deny whether it is GrapheneOS-specific? Honestly it is a bit frustrating to see the issue closed immediately with a simple opinion with no debugging steps or other actionable feedback provided. Even if it is not GrapheneOS-specific, I'd appreciate some pointers on how to find the root cause.

**Comment by thestinger** [comment]
>  it works on another Android 14-based OS just fine

Not confirmed to be true by anyone active here.

**Comment by thestinger** [comment]
> Developer confirmed that it works for them on another Android 14-based OS, so might be something related to Graphene OS specifically in this case.

Which OS, and where did they confirm this? Doesn't make sense that it would be broken specifically on GrapheneOS. We know what we change in GrapheneOS and we know that in this case, it's highly unlikely to be a GrapheneOS issue rather than an app issue.

> I'd appreciate some pointers on how to find the root cause.

It needs to be checked on another GrapheneOS install and on the stock Pixel OS. If it occurs on the stock OS, the app developer almost certainly has an issue to fix. At the moment, there's a lack of a reason to think this is caused by GrapheneOS since we don't change anything relevant to this.

**Comment by thestinger** [comment]
You should also clear the app data or reinstall the app to see if it's simply a bug in the app's configuration system.

**Comment by henrik-lindqvist** [comment]
Automate dev here. The user claims that `GLOBAL_ACTION_BACK` works but not `GLOBAL_ACTION_LOCK_SCREEN`. I can't reproduce the problem on stock Android 14 emulator. I don't have an GrapheneOS device to test on, is there any emulator image available?

**Comment by nazar-pc** [comment]
Re-tested a simpler flow and it works as expected, there is something else in my setup.

Thanks for the help!
