### ISSUE TITLE
Google Photos unable to edit screenshots from pop-up

### ISSUE THREAD

**Issue by 0xunusedusername** [GrapheneOS/os-issue-tracker#2713]
Moved from an older Pixel to the newest models, and I've noticed a regression in functionality. Been using Google Photos as the primary for a long time, but on the 8's when attempting to edit it says "Editing is not supported for this image."

Using sandboxed Play Services and Photos has both the relevant storage scopes as well as Media management permissions. Other apps like Snapseed comparatively seem to work just fine.

**Comment by thestinger** [comment]
On the stock OS, the Markup app is used for this not Google Photos. This is likely working as intended for Pixels. Markup is Pixel specific and it probably detects it's on a Pixel and tries to use that.

**Comment by 0xunusedusername** [comment]
@matchboxbananasynergy @thestinger Gotcha, thanks. For me, it was working as expected on my 7a, so I thought it was a regression with the latest models.

Installed the Markup apk and it is working as expected now (other than not being able to update it through the Store) 👍

**Comment by thestinger** [comment]
Markup isn't currently updated via the Play Store on the stock OS. That's also why it's difficult to obtain.

**Comment by 0xunusedusername** [comment]
Yeah, seems like an odd choice to me. Grabbed it from APKMirror and just added the releases RSS feed to my reader. Good enough for now.

**Comment by 0xunusedusername** [comment]
@thestinger just wanted to personally say thanks for mirroring the APK in Apps. Makes my life easier :)

**Comment by thestinger** [comment]
It was done because we don't want people relying on a third party site to obtain what's likely an old version and then they'll be left without automatic updates. If it was on the Play Store, we wouldn't bother with a mirror.

**Comment by 0xunusedusername** [comment]
> It was done because we don't want people relying on a third party site to obtain what's likely an old version and then they'll be left without automatic updates. If it was on the Play Store, we wouldn't bother with a mirror.

I figured that was the case. Regardless, it's appreciated.
