### ISSUE TITLE
Can't lock booloader after successful install

### ISSUE THREAD

**Issue by techny210** [GrapheneOS/os-issue-tracker#2723]
Pixel 8 pro, husky-stable, from Ubuntu 22.04 or webusb. Can't lock booloader after successful install. 
Tried to reboot again, same  effect. Bootloader screen does not have option to lock itself the menu options are : start. restart, recovery mode, rescue mode, bar code.
Webusb gives: Error: Bootloader was not locked, please try again!

Cable Connection is not an issue (methinks), installed from Ubuntu box through webusb and tried another device (another android phone) to eliminate the suspect issue, no go, the same error.
Is there a log somewhere so I can take a look as to why?
Is there any other way to lock the bootloader?

**Comment by thestinger** [comment]
It's not successfully installed. You shouldn't use it until it is.

**Comment by thestinger** [comment]
It was likely interrupted before finishing.

**Comment by techny210** [comment]
It was installed just fine, I can use it, install apps and all, just can't lock it

**Comment by techny210** [comment]
Is there any other way to lock the bootloader?

**Comment by thestinger** [comment]
You need to stop using it and reinstall the OS. You didn't complete the install successfully. You think you did, but you didn't.

**Comment by thestinger** [comment]
> Is there any other way to lock the bootloader?

The issue is that you don't have GrapheneOS fully installed, not that you can't lock. The firmware tries to be helpful by not letting you lock when the install is clearly not finished. It was interrupted before it finished.

**Comment by techny210** [comment]
That did it, booted both devices started from scratch, now locked and loaded. Thanks
