### ISSUE TITLE
Root not possible anymore?

### ISSUE THREAD

**Issue by heckarman** [GrapheneOS/os-issue-tracker#2725]
With Magisk installed, the device straight goes into boot loop until root is removed, hardened memory is disabled for Magisk. At the top in the notification menu, you get this system_server crash message. Like I had some 10+ error messages of same kind until I unrooted my device.

After disabling hardened memory, rooted the device again, just to get, storage not being detected and network module dying. Clicking on respective setting would result in system crash.

Also, Zygisk now does not work. I'm aware that it is invasive, but killing an entire service?

I'm aware that GOS does not support this, I just wanted to let you and others know.

**Comment by thestinger** [comment]
You're replacing key parts of the core operating system with something very invasive. It's greatly reducing security of the OS and interfering with it functioning as intended. It's fully expected that this would break since Magisk doesn't take into account the hardening done by GrapheneOS. It's only by chance that there wasn't much earlier obvious breakage.

> After disabling hardened memory

What do you mean by this?

**Comment by thestinger** [comment]
The officially supported mechanism for root access via ADB shell in developer builds (userdebug builds) works fine. You can make userdebug builds with ro.adb.secure=1 enabled like user builds. An invasive replacement for a bunch of the core OS and greatly reduces security including exposing root to a bunch of the OS and making it available to apps not working anymore doesn't mean that you can't make builds with root access in the officially supported way.

**Comment by thestinger** [comment]
The officially supported mechanism for root access via ADB shell in developer builds (userdebug builds) works fine. You can make userdebug builds with ro.adb.secure=1 enabled like user builds to have authentication and root access. An invasive replacement for a bunch of the core OS and greatly reduces security including exposing root to a bunch of the OS and making it available to apps not working anymore doesn't mean that you can't make builds with root access in the officially supported way.

**Comment by heckarman** [comment]
> What do you mean by this?

Hardened memory allocator

**Comment by heckarman** [comment]
Do GrapheneOS have a separate channel that has debug builds? If yes, how can one like me get access to?

**Comment by thestinger** [comment]
We don't publish userdebug builds. They're meant for development. It's possible to build them with `ro.adb.secure=1` to have ADB authentication enabled. It's usually not enabled and ADB is always on which is very unsafe.
