### ISSUE TITLE
Color correction can be enabled, but not disabled

### ISSUE THREAD

**Issue by j6b72** [GrapheneOS/os-issue-tracker#2727]
Hi, I've encountered a bug:

How to reproduce:
1. Via the settings (Accessibility -> Color and Movement -> Color Correction -> Enable color correction) or the quick tiles in the notification area, enable color correction
2. Watch the color correction take effect and then disable color correction again

What happens:
Color Correction stays enabled and the only workaround I've found to disable it again is to reboot the device.

What I'd expect instead:
Disabling color correction instantly restores the default appearance of the colors, like the case on the stock Pixel Rom.

GrapheneOS is up-to-date and I'm using a Pixel 6 Pro.

Could you please take a look at this?

Thank you very much.

Regards
j6b72

**Comment by thestinger** [comment]
Please search for the already filed issues. It's an AOSP issue.
