### ISSUE TITLE
Pixel 7a not updating to 2023112600 - Stuck on 2023111500

### ISSUE THREAD

**Issue by LunchBoxC** [GrapheneOS/os-issue-tracker#2728]
Pixel 7a will not update to: 2023112600 on stable, beta or alpha channels.

When tapping to check for updates, icon appears at top briefly and then in the notifications - phone is "up to date"

**Comment by thestinger** [comment]
It's only in the alpha channel, not beta or stable. You can see that it's not in beta or stable from the releases page. You must not have actually checked alpha.

**Comment by LunchBoxC** [comment]
I must have misunderstood this on the Changelog...  "List of tagged releases. Snapshot releases without tags such as early releases of the project and early device support releases are not listed."  Sorry.

**Comment by thestinger** [comment]
Every production release starts in the alpha channel, then goes to beta and then finally stable. Only production releases are listed on that page. Nothing ever starts in stable or beta.

**Comment by LunchBoxC** [comment]
I understand, I just thought before it was listed on the release page that it was in "Stable" at that point is all.  I misunderstood.

**Comment by thestinger** [comment]
This release didn't go to beta because some minor issues were identified and another release is being made later today addressing them and bringing other improvements.

**Comment by LunchBoxC** [comment]
Many thanks.  Sorry for the misunderstanding.   :)
