### ISSUE TITLE
Videos Turning Blocky/Breaking Up & Sometimes Freeze

### ISSUE THREAD

**Issue by seniorm0ment** [GrapheneOS/os-issue-tracker#2732]
This is actually something I've noticed since I had my Pixel 6 Pro, it seemed to happen more often then however.
It still seems present and happens often enough to be annoying. 
I tried searching for this issue and did not see it, could be my phrasing. Apologies if the issue is already open. Like I said, this is something I've noticed for quite some time now.

## Blocky Videos
Videos will randomly turn blocky, hard to explain but looks like it's all broken up into tiny squares, spread in different directions.
Looks _somewhat_ similar to this, not exact: 
![glitch-distortion-background-broken-video-signal-vector-19481908](https://github.com/GrapheneOS/os-issue-tracker/assets/18413674/8cadf233-abcd-46aa-b30d-c41d55225a6c)

## Frozen Videos
Sometimes also videos will just start black and you can hear the sound.
Or sometimes they will start with the first frame but frozen and you can hear the sound. Or also sometimes they will ppay the first few seconds fine then just freeze completely.

## What Apps It Happens On
I notice it happens across a variety of apps. I don't notice it on Newpipe, however I notice it all the time on Instagram, Snapchat, KurobaEx, Facebook, and a few others.

## OS
GrapheneOS, Pixel 8 Pro
Version: [2023111500](https://grapheneos.org/releases#2023111500)

Google Services enabled
All non-libre (Google: Faceobok, Instagram, Snapchat, etc.) apps installed using Aurora Store

**Comment by thestinger** [comment]
@seniorm0ment Does this still happen in [2023120701](https://grapheneos.org/releases#2023120701)?

**Comment by seniorm0ment** [comment]
I can't say I've noticed it, didn't even realize it was fixed actually I completely forgot I was having this issue. So I guess we can say yes, it's fixed. If I notice it I will let you know?

**Comment by thestinger** [comment]
It's hopefully fixed by the massive GPU driver improvements.
