### ISSUE TITLE
Wifi calling not working on Pixel 4a 5G

### ISSUE THREAD

**Issue by eblanshey** [GrapheneOS/os-issue-tracker#2736]
My Pixel 4a 5G's wifi calling feature does not work. I confirmed it worked perfectly on stock android with the same SIM, so I'm certain my phone supports it. I am on the latest GOS version as of this date (Nov 30 2023).

I've seen many discussions about wifi calling, including [this issue for the Pixel 7](https://github.com/GrapheneOS/os-issue-tracker/issues/1648). Although I understand the support window for the Pixel 4a 5G is nearing an end, it'd be great if the same fix could be made to work on this device, as well.

For the record, I've tried with both AT&T and Verizon SIM cards in the USA, and both didn't work. I confirmed it IS working on another Pixel 7 Pro, so this issue must be device-specific.

Thank you!

**Comment by thestinger** [comment]
Wi-Fi calling works fine across the devices including the Pixel 4a (5G). Multiple major US carriers require running privileged carrier bloatware instead of doing things in the standard way. Try T-Mobile instead.

**Comment by eblanshey** [comment]
@thestinger can you provide any insight on why it would work on the Pixel 7 Pro but not the 4a 5G, using the same SIM cards? The OS and settings were set up identically. Do you think the 4a 5G has carrier bloatware that the 7 Pro does not?

**Comment by thestinger** [comment]
Carriers vary in how they handle each device and the carrier bloatware included across them is different. We don't plan on adding any more of it than what's normally included in vendor.
