### ISSUE TITLE
Autofill Service Not Working on Brave in GrapheneOS

### ISSUE THREAD

**Issue by TwilitWave** [GrapheneOS/os-issue-tracker#2737]
Hello!

There are numerous reports of this issue on the Graphene forum:
https://discuss.grapheneos.org/d/7600-proton-pass-in-brave-on-graphene
https://discuss.grapheneos.org/d/6803-brave-password-autofill-from-bitwarden-stopped-working
https://discuss.grapheneos.org/d/6933-different-question-on-an-old-issue-regarding-brave-autofill
https://discuss.grapheneos.org/d/4802-bitwarden-not-working-on-brave

To summarize:
1. Password Managers utilizing Android Autofille Services (such as BitWarden, Protonpass, 1Password, etc...) don't work in Brave when running GrapheneOS.
2. They DO work in Brave when running Stock Android, indicating that this is a Graphene-specific issue.
3. Some reports have indicated this started happening after Vanadium gained support for Android Autofille, but this may have been user error.
4. It is possible to get the AutoFill pop-up on screen utilizing Android Accessibility, but this barely functions:
      a. It doesn't list options for auto-filling in-line or in the pop-up itself.
      b. It only links to the password app and then from within the app you can select your login details.
      c. It can't detect new form submissions, so you can't add any new logins to the password manager without adding all information manually from the app itself.
      d. Running in Accessibility mode is a security hazard given the privileges it requires.

No workarounds have yet been found, at least in my research and experimenting.

**Comment by thestinger** [comment]
Brave onl supports it when using Google Play. This isn't a GrapheneOS issue. Vanadium added native autofill support.

**Comment by thestinger** [comment]
Use sandboxed Google Play if you want it in Brave.

**Comment by TwilitWave** [comment]
At least in my case, Sandboxed Google Play is enabled, but makes no difference.

**Comment by TwilitWave** [comment]
Indeed, it does work in Vanadium.

I could certainly report this to Brave as well, however I do want to reiterate that the AutoFill Service functions fine in Brave on Stock Android.

As such, it seems to be some combination of Brave + GrapheneOS that seems to be causing this issue, not Brave + Android itself.

**Comment by TwilitWave** [comment]
Ahhh, gotcha. I appreciate the additional context!

**Comment by scrampker** [comment]
Still doesn't work after all this time.
