### ISSUE TITLE
failed to create GrContext for vulkan uploads

### ISSUE THREAD

**Issue by nursoda** [GrapheneOS/os-issue-tracker#2738]
type: crash
osVersion: google/bluejay/bluejay:14/UP1A.231105.003/2023112900:user/release-keys
uid: 1000 (u:r:system_server:s0)
cmdline: system_server
processUptime: 542551s

abortMessage: failed to create GrContext for vulkan uploads

signal: 6 (SIGABRT), code -1 (SI_QUEUE)
threadName: GrallocUploadTh

backtrace:
    /apex/com.android.runtime/lib64/bionic/libc.so (abort+164, pc 5b104)
    /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+112, pc 628a20)
    /apex/com.android.art/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_3::__invoke(char const*)+80, pc 17520)
    /system/lib64/liblog.so (__android_log_assert+308, pc 6f14)
    /system/lib64/libhwui.so (std::__1::__packaged_task_func<android::uirenderer::VkUploader::onUploadHardwareBitmap(SkBitmap const&, android::uirenderer::FormatInfo const&, AHardwareBuffer*)::'lambda'(), std::__1::allocator<android::uirenderer::VkUploader::onUploadHardwareBitmap(SkBitmap const&, android::uirenderer::FormatInfo const&, AHardwareBuffer*)::'lambda'()>, void ()>::operator()()+912, pc 29e8d0)
    /system/lib64/libhwui.so (std::__1::__function::__func<decltype(fp()) android::uirenderer::WorkQueue::runSync<android::uirenderer::renderthread::RenderProxy::detachSurfaceTexture(android::uirenderer::DeferredLayerUpdater*)::$_19>(android::uirenderer::renderthread::RenderProxy::detachSurfaceTexture(android::uirenderer::DeferredLayerUpdater*)::$_19&&)::'lambda'(), std::__1::allocator<decltype(fp()) android::uirenderer::WorkQueue::runSync<android::uirenderer::renderthread::RenderProxy::detachSurfaceTexture(android::uirenderer::DeferredLayerUpdater*)::$_19>(android::uirenderer::renderthread::RenderProxy::detachSurfaceTexture(android::uirenderer::DeferredLayerUpdater*)::$_19&&)::'lambda'()>, void ()>::operator()() (.2a0230ca9784b3ed733f337e97c21a2e)+88, pc 2849c8)
    /system/lib64/libhwui.so (android::uirenderer::WorkQueue::process()+580, pc 2755b4)
    /system/lib64/libhwui.so (android::uirenderer::ThreadBase::threadLoop()+72, pc 273dc8)
    /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+416, pc 13440)
    /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204, pc c8cec)
    /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64, pc 5c8b0)
```

**Comment by nursoda** [comment]
Sure. I just installed the update and rebooted. The crash occurred right after rebooting after SIM-PIN and password entry while the apps were optimized. I didn't start any app then.

**Comment by thestinger** [comment]
Has it happened again?

**Comment by nursoda** [comment]
No, at least not yet. I rebooted, that didn't trigger anything. Yet I assume it happened when post-update app optimization started, and that is not triggered in normal use or even upon reboot.

**Comment by thestinger** [comment]
May be resolved in the newer releases if it's not happening again.

**Comment by nursoda** [comment]
> May be resolved in the newer releases if it's not happening again.

It did not happen again in the last three consecutive December updates. Tanks.
