### ISSUE TITLE
require password to delete user or reset

### ISSUE THREAD

**Issue by Pantyhose-X** [GrapheneOS/os-issue-tracker#2747]
* Grapheneos needs to implement "delete the auxiliary user configuration file" and needs to enter the password
* Other users switching from one user to another should be asked for a password. #Known security risk, my admin user has set a PIN password, when I switch from another user to admin, I don't need to enter the password, which should be dangerous.

Why do you need
When I lend my phone to my family or friends, they may try to switch user. delete the auxiliary user configuration file
bug: When you unlock the device, someone borrows or takes your mobile phone, it will not be difficult to delete the user. The reason is that he does not need to enter a password when he deletes

**Comment by thestinger** [comment]
You do need to enter the password when you switch to a user to unlock them.

Is your 2nd point that you want the password of a user to be required to delete the user you're currently on? The intention is that you make another user for someone else to use. Them deleting their own user shouldn't matter. Also, if they're malicious, why wouldn't they just break the phone?

**Comment by Pantyhose-X** [comment]
I installed too many software games, I don't want it to be deleted, then I need to download it again. I don’t want to be deleted without entering the password.

**Comment by thestinger** [comment]
Use a regular user instead of the guest user. Consider installing the games into the Owner user and disabling them there so you can easily add them to other users via Install available apps.

**Comment by Pantyhose-X** [comment]
> Use a regular user instead of the guest user. Consider installing the games into the Owner user and disabling them there so you can easily add them to other users via Install available apps.

This design is terrible, when my phone is unlocked. Suddenly the FBI checks the phone, I can't switch users in time, the FBI just deletes the user, and all the encrypted data I hadn't backed up in time is gone.

**Comment by thestinger** [comment]
If someone wants to wipe your data, they can just wipe the device from recovery. They can also simply break the phone.

**Comment by Pantyhose-X** [comment]
> from recovery

I don't know if it's possible to set a different password for GrapheneOS Recovery, I haven't tried it, as far as I know China phones require a password to open Developer Mode and Recovery.

**Comment by Pantyhose-X** [comment]
> If someone wants to wipe your data, they can just wipe the device from recovery. They can also simply break the phone.

I don't know if it's possible to set a different password for GrapheneOS Recovery, I haven't tried it, as far as I know China phones require a password to open Developer Mode and Recovery.

**Comment by thestinger** [comment]
If someone has your phone, they can simply break it. They could open it up and connect up to the SSD to wipe it. What's the point?

**Comment by Pantyhose-X** [comment]
> SSD to wipe

SSD wipe is not that easy, but removing a user is very simple.

**Comment by thestinger** [comment]
Wiping via recovery is quite simple, and breaking the phone is even simpler.
