### ISSUE TITLE
Kernel Crash

### ISSUE THREAD

**Issue by xyhhx** [GrapheneOS/os-issue-tracker#2748]
Got a kernel crash report just now.

Paste of report:
https://pb.envs.net/?ccc101f6651d28f0#4un1xdswD56pptdtEkK28Y9C47ESpYrTiUW2GoC8CCQc

**Comment by thestinger** [comment]
Unable to view the linked paste. Can you put it here instead?

**Comment by thestinger** [comment]
Thanks, looks like something that will need to be resolved upstream. Based on the crash log, it's very unlikely that we caused it but rather it looks like a driver/firmware bug.
