### ISSUE TITLE
Hash key is not sent a two-factor authentication system

### ISSUE THREAD

**Issue by anto** [GrapheneOS/os-issue-tracker#2753]
**Summary**
User cannot be authenticated by a two-factor authentication system which calls the phone of the user and asks the user to press the hash (#) key, even though the user presses the hash key on the keypad.  

**Step to reproduce**
1. An internet user accesses a company portal via a web browser where two-factor authentication was setup to call the phone of the user and ask the user to confirm
2. After the user successfully signs in with username and password, the user is presented with a pop-up window containing a button to initiate the call to the phone of the user
3. After the user clicks on that button, the authentication system starts calling the phone of the user
4. The user answers the call and hears an instruction to press the hash key
5. The user activates the keypad and presses the hash key
6. The user hears a confirmation that the sign in is successful and the phone call is terminated
7. The user is given the access to the company portal

**Actual result**
The user is not given the access to the company portal as the authentication system does not receive the hash key which is requested for the user to press, even though the user indeed presses the hash key.

See the example recording file on [this link](https://terwelu.com/public/videos/GrapheneOS_Google_Pixel_6a_Cannot_Send_Hash_Key.mp4).

**Expected result**
The user is successfully authenticated and given the access to the company portal.

See the example when the user moves the SIM card to the phone with other Android OS on recording file on [this link](https://terwelu.com/public/videos/Other_Android_Xioami_MI9Lite_Hash_Key_Sent.mp4).

**Device**
Made and Model: Google Pixel 6a
GrapheneOS Build: UP1A.231105.003.2023112900

**Actions to try solving the issue**
1. Enable Dial pad tones on Sound and vibration setting
2. Try other Dialer apps, e.g. Simple Dialer from F-Droid

**Comment by thestinger** [comment]
This appears to be a carrier or configuration issue.

**Comment by thestinger** [comment]
Different settings such as using VoLTE on one phone but not the other. The issue is likely a broken VoLTE implementation or something similar. You can try turning off VoLTE.
