### ISSUE TITLE
Defer system updates until substantial battery power is available?

### ISSUE THREAD

**Issue by de0u** [GrapheneOS/os-issue-tracker#2756]
Here are some user reports indicating that a device running out of power during a system update can result in file-system corruption, sometimes seemingly severe:
- https://discuss.grapheneos.org/d/9324
- https://discuss.grapheneos.org/d/8958
- https://discuss.grapheneos.org/d/8474
- https://discuss.grapheneos.org/d/8214
- https://discuss.grapheneos.org/d/7081
- https://discuss.grapheneos.org/d/4057
- https://discuss.grapheneos.org/d/4039
- https://discuss.grapheneos.org/d/1594

This situation is presumably rare, but it seems to be troublesome for affected users.  Might it be helpful to either require a 50% charge before applying an update, or add a user-settable threshold?

**Comment by thestinger** [comment]
Running out of power during an update is safe. If the update isn't correctly installed, it will be rolled back.

There's already a toggle to disable automatic updates when battery is low. What's wrong with the existing toggle? There's also one to only update which the device is charging.
