### ISSUE TITLE
Inverted Document Printing Issue on Pixel 7/7a (Version 2023112900) with HL-L2340DW Printer

### ISSUE THREAD

**Issue by mar565** [GrapheneOS/os-issue-tracker#2757]
Tested on: Pixel 7 and 7a
Current version: 2023112900
Printer: HL-L2340DW (b/w only)

I do not know with which version this problem was introduced (last 2-4 updates). But printing a document results in it being inverted. I only use the built-in printing function, which worked fine until it broke. The printer has not been updated and printing from a stock Android device and PC works fine. Can anyone replicate this problem?

**Comment by thestinger** [comment]
@mar565 Do you still have an issue with the [2023120701](https://grapheneos.org/releases#2023120701) release?

**Comment by mar565** [comment]
Persistent with 2024011600

**Comment by mar565** [comment]
Problems solved by updating printer firmware. I have had internet access to my printer blocked as in the past updates have only resulted in a bricked printer or blocked alternative inks.
The problem was introduced with Android 14 and only affected Brother printers and relabled ones (like Dell).
