### ISSUE TITLE
How to manage connections using hotspot

### ISSUE THREAD

**Issue by Madhpharma** [GrapheneOS/os-issue-tracker#2769]
I can’t find options to manage devices under hotspot settings, I can’t find which devices connected to my hotspot, only visible how many devices,

**Comment by thestinger** [comment]
It's not supported at the moment and we don't plan to add it ourselves.

**Comment by xundeenergie** [comment]
Please reopen this.
This is an important feature!

**Comment by WaleedMortaja** [comment]
I think this is a duplicate #3816
