### ISSUE TITLE
kernel panic

### ISSUE THREAD

**Issue by sawft99** [GrapheneOS/os-issue-tracker#2791]
Device: Pixel 7

I had just walked away and came back to it. Pastebin because over character limit on GH

https://pastebin.com/4BP2yQW4

**Comment by 5t0rmr1d3r** [comment]
Same Here...
[crashreport.md](https://github.com/GrapheneOS/os-issue-tracker/files/13623103/crashreport.md)

**Comment by sawft99** [comment]
The update after that didn't have a crash.

**Comment by thestinger** [comment]
@5t0rmr1d3r @sawft99 Both of your issues appear to be either a hardware issue or a driver bug. The crash says that PCI wasn't powered on.

```
exynos_pcie_rc_panic_notifier: ---                                       
cpif: s5100_send_panic_noti_ext: Send CMD_KERNEL_PANIC message to CP     
cpif: pcie_send_ap2cp_irq: Reserve doorbell interrupt: PCI not powered on
```

It looks like a component didn't come back awake when requested.

You both have the same kind of crash.

**Comment by thestinger** [comment]
Likely not something we can address. It will hopefully be fixed by a firmware or driver patch in the future. This should only ever happen when the device isn't in active use such as while idle or when you explicitly turn it on. It's a failure resuming from suspend.
