### ISSUE TITLE
Repeated kernel crashes and restarts part 2

### ISSUE THREAD

**Issue by johannes-qvarford** [GrapheneOS/os-issue-tracker#2797]
Follow-up to #2751.

Crashes keep happening daily after the 2023120701 release. Currently on 2023120800.

Latest crash report: https://pastebin.com/KRee5PsG

Thank you for your hard work.

**Comment by Gummihund** [comment]
Same here!

**Comment by thestinger** [comment]
@johannes-qvarford The log says it rebooted from holding power:

```
Reboot Info:
  RST_STAT: 0xc0000 - PIN_RESET | PO_RESET
  GSA_RESET_STATUS: 0x1 - GSA_PINRESET
  Reboot reason: 0xcccc - Long Press Power Key Reboot (MASTER DISCONNECT)
  Reboot mode: 0x0 - Normal Boot

**Comment by thestinger** [comment]
Looks like a hardware issue. Your power button is being held without you doing it. Please obtain other logs and check for Long Press Power Key Reboot as the reboot reason to confirm it isn't something else and that this was a special case.

**Comment by Gummihund** [comment]
It only appears on my Phone when i put it into the pocket! Or turn it quickly upsidedown somehow! If i leave it on the table it stays on! Also while you use it ... Video etc...  its not turning off.

**Comment by thestinger** [comment]
@Gummihund Can't access the file you uploaded. It's probably a different issue than the one @johannes-qvarford filed.

**Comment by Gummihund** [comment]
Ok thank you! I try to get a better report! It also just appears since the latest update!

**Comment by thestinger** [comment]
@Gummihund The file you tried to upload isn't available for us to look at. You could email it to us instead.

**Comment by Gummihund** [comment]
Ok! I think this report didnt catch the issue anyway! I let the phone crash one more time and then i will mail you the report. Takes me a bit of time due to work!
