### ISSUE TITLE
Camera not working / starting

### ISSUE THREAD

**Issue by shishatuner** [GrapheneOS/os-issue-tracker#2798]
When opening any camera app the screen doesn't display a picture only the control buttons are there.
This happens in GrapheneOS Camera, Gcam and OpenCamera.
It seems like the camera is not starting/ no connection to the camera.
No Errors are shown

Pixel 7 Pro
Build: UQ1A.231205.015.2023120800

**Comment by thestinger** [comment]
That sounds like a hardware issue.

**Comment by thestinger** [comment]
Does it happen with both front/rear camera? Did you try rebooting?

**Comment by shishatuner** [comment]
Yes for both cameras.
Reboot didn't help and sometimes switching from photo to video in gcam helps to display the picture. Most of the time its just black.
So this shouldn't be a hardware issue.

**Comment by thestinger** [comment]
That doesn't indicate it isn't a hardware issue.

**Comment by shishatuner** [comment]
It started after the last update today. Before it worked fine.
Where can I find logs to analyze it?
I just want to be sure what kind of issue it is before throwing my phone away or buying new hardware parts.

**Comment by thestinger** [comment]
The latest update didn't change anything relevant to this. There are frequent updates and any issue you experience will always be shortly after one. That doesn't make it related to the update.

**Comment by shishatuner** [comment]
When starting Threema the front camera works instanzly, but when switching to rear I get an error. It says that it has no permissions to access the android camera.
The permissions are set correctly and as I said, sometimes it works after switcbing modes in the camera app.

**Comment by shishatuner** [comment]
It's the same for Signal but there no error is shown.

**Comment by thestinger** [comment]
This is likely a hardware issue.

**Comment by shishatuner** [comment]
But why shoukd it be a hardware issue when it works sometimes and I can take pictures.
Are thereany system logs I can analyze?

**Comment by thestinger** [comment]
Hardware issues are often intermittent, especially when it's just starting to fail.

**Comment by pixincreate** [comment]
If you've enabled ANGLE graphics for Camera app, that might be the culprit here.

**Comment by thestinger** [comment]
Please disable developer options if they're enabled.

**Comment by shishatuner** [comment]
After a fresh OS install it works without any issues.
Thank you for your time.

**Comment by thestinger** [comment]
@shishatuner Likely caused by changing developer options. Probably could have worked around it disabling them.

**Comment by a-jackson** [comment]
I'm getting this same issue after the latest OS update. Build UQ1A.231205.015.2023121200. Camera app is just black for 10-30s seconds then the camera opens and works fine. Happens in all apps that use the camera.

**Comment by thestinger** [comment]
Disable developer options and reset app preferences.

**Comment by a-jackson** [comment]
Thanks that's done it
