### ISSUE TITLE
Device Performance Drops With Lower Battery

### ISSUE THREAD

**Issue by seniorm0ment** [GrapheneOS/os-issue-tracker#2802]
Device performance seems to drop significantly with _lower_ battery percent. Battery saver has not kicked in, when it does it does lower performance but that is understandable. However, I see zero reason why performance seems to drop when it is not enabled.

Also it seems to throttle performance at lower battery _while plugged in charging_

Pixel 8 Pro 
Version: 2023120800

**Comment by thestinger** [comment]
Need concrete evidence showing this.
