### ISSUE TITLE
Pixel8: sendHistogramChannelIoctl spams log

### ISSUE THREAD

**Issue by miles992** [GrapheneOS/os-issue-tracker#2805]
I have a Pixel 8 with the latest GrapheneOS installed, since the last update I see an endless stream of "sendHistogramChannelIoctl" and "getHistogramData" items floating by via logcat.

The message reads:

hwc-display: sendHistogramChannelIoctl:
kernel doesn't support multi channel histogram ioctl
hwc-display: getHistogramData:
histogram channel #0: BAD_HIST_DATA, sendHistogramChannelIoctl (REQUEST) error (-38)

**Comment by thestinger** [comment]
This doesn't look like a bug but rather noisy logging.

**Comment by thestinger** [comment]
Appears to be overly noisy logging added upstream. It's not really a bug other than such verbose logging not being right.

**Comment by thestinger** [comment]
Resolved for upcoming release.

**Comment by thestinger** [comment]
https://grapheneos.org/releases#2023121200
