### ISSUE TITLE
Add icons for Private dns, Internet connectivity checks, Attestation key provisioning

### ISSUE THREAD

**Issue by W1zardK1ng** [GrapheneOS/os-issue-tracker#2807]
Private dns, Internet connectivity checks and Attestation key provisioning  doesnot have any icons and looks odd, to make this settings align with other options under Network and internet section please add icons for these settings.

**Comment by thestinger** [comment]
Private DNS doesn't have an icon in the stock OS so we didn't use an icon for ours. We'll add icons if they do for Private DNS.
