### ISSUE TITLE
Switching resolution on Pixel 8 Pro causes a reboot 

### ISSUE THREAD

**Issue by mrxx0** [GrapheneOS/os-issue-tracker#2818]
Steps to reproduce:

- Settings -> Display -> Screen resolution

- Switch between high or full resolution

    
Actual behavior : System reboot (new resolution applied)
Expected behavior : Change screen resolution

OS release : Pixel 8 Pro on UQ1A.231205.015.2023120800

**Comment by thestinger** [comment]
Is there a crash log?

**Comment by mrxx0** [comment]
> Is there a crash log?

No crash log just a reboot

**Comment by mrxx0** [comment]
[resolution_crash.txt](https://github.com/GrapheneOS/os-issue-tracker/files/13635592/resolution_crash.txt)

**Comment by muhomorr** [comment]
This issue should be resolved in the current release (2023121200).

**Comment by mrxx0** [comment]
> This issue should be resolved in the current release (2023121200).

Indeed it is fixed.
