### ISSUE TITLE
kernel watchdog triggered

### ISSUE THREAD

**Issue by locusus** [GrapheneOS/os-issue-tracker#2829]
Attached a .txt with the dump.
[Untitled document.txt](https://github.com/GrapheneOS/os-issue-tracker/files/13641569/Untitled.document.txt)

**Comment by thestinger** [comment]
What were you doing when it crashed? It's hard to see where this went wrong.

**Comment by locusus** [comment]
The first time I was browsing with Firefox, maybe? The second time was more or less immediately after the system reboot. Both times the reboot occurred without my pushing+holding the power button.

**Comment by thestinger** [comment]
Please update to the latest release and file a new issue if you encounter another kernel crash.
