### ISSUE TITLE
Kernel Crash

### ISSUE THREAD

**Issue by vvvilife** [GrapheneOS/os-issue-tracker#2836]
[crash.txt](https://github.com/GrapheneOS/os-issue-tracker/files/13650472/crash.txt)

Kernel crash. Listening to music via Bluetooth, open text message and go to share a photo. Phone hung for 10-15 seconds then rebooted

**Comment by slashtab** [comment]
[crash.txt](https://github.com/GrapheneOS/os-issue-tracker/files/13653369/crash.txt)

Kernel Crash on Pixel 7 Stable

**Comment by thestinger** [comment]
Please update to the latest release and file a new issue if you encounter another kernel crash.
