### ISSUE TITLE
System Update option not visible

### ISSUE THREAD

**Issue by bobc73** [GrapheneOS/os-issue-tracker#2862]
I do not see a System Update option in Settings - System
![Screenshot_20231214-111536_1](https://github.com/GrapheneOS/os-issue-tracker/assets/70099756/eb641058-f87c-4918-b151-13f99bcce1d1)

**Comment by bobc73** [comment]
![Uploading Screenshot_20231214-112336.png…]()

**Comment by bobc73** [comment]
![Screenshot_20231214-112336](https://github.com/GrapheneOS/os-issue-tracker/assets/70099756/d04f73a2-1df9-4b00-a973-a6ef46e58fa7)

**Comment by thestinger** [comment]
You disabled the System Updater app and forgot you did it.

**Comment by bobc73** [comment]
I did indeed. Thank you!!
