### ISSUE TITLE
Pixel 8: wireguard VPN tiles behave strangely

### ISSUE THREAD

**Issue by momoxxl** [GrapheneOS/os-issue-tracker#2877]
I use wireguard as a VPN solution on my Pixel 8. I have a tile for it in the quick launcher. By quick launcher I mean the tiles that appear when I swipe down at the top of the display. If I now briefly tap on the Wireguard tile, a settings dialog is displayed with the title "Display over other apps". If I click on the tile for a long time, the Wireguard app is displayed and I can select which tunnel I want to use. 

I played around with it a bit today, also changed the system language. In the meantime, the wireguard tile worked correctly or as I knew it before, namely a short click activates the last selected VPN tunnel. After I changed the language setting to my native language German, I have the original, strange behavior again. However, changing the system language back to English no longer changes anything. 

I don't know how I can provide more information, e.g. log files, to better analyze the problem.

**Comment by thestinger** [comment]
Seems like an app bug, not anything that GrapheneOS changes could cause. Might be a compatibility issue it has with Android 14 or Android 14 QPR1.
