### ISSUE TITLE
Google Pixel 8 Pro camera crashes 

### ISSUE THREAD

**Issue by drdrsco** [GrapheneOS/os-issue-tracker#2885]
My front camera works. But when I switch to the rear, this happens 

```
type: crash
osVersion: google/husky/husky:14/UQ1A.231205.015/2023121200:user/release-keys
uid: 1000 (u:r:hal_camera_default:s0�)
cmdline: /apex/com.google.pixel.camera.hal/bin/hw/android.hardware.camera.provider@2.7-service-google
processUptime: 0s

abortMessage: terminating

signal: 6 (SIGABRT), code -1 (SI_QUEUE)
threadName: SessionPool
MTE: not enabled

backtrace:
    /apex/com.android.runtime/lib64/bionic/libc.so (abort+164, pc 63464)
    /apex/com.android.vndk.v34/lib64/libc++.so (abort_message+276, pc 4d144)
    /apex/com.android.vndk.v34/lib64/libc++.so (demangling_terminate_handler() (.__uniq.205383134706309982814331919004001075825)+72, pc 4d298)
    /apex/com.android.vndk.v34/lib64/libc++.so (std::__terminate(void (*)())+8, pc 4df98)
    /apex/com.android.vndk.v34/lib64/libc++.so (std::terminate()+32, pc 4df20)
    /apex/com.android.vndk.v34/lib64/libc++.so (std::__1::thread::~thread()+24, pc ad5b8)
    /apex/com.google.pixel.camera.hal/lib64/liblyric_hwl.so (pc eb3c24)
    /apex/com.google.pixel.camera.hal/lib64/liblyric_hwl.so (pc 417878)
    /apex/com.google.pixel.camera.hal/lib64/liblyric_hwl.so (pc 416614)
    /apex/com.google.pixel.camera.hal/lib64/liblyric_hwl.so (pc 416558)
    /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204, pc cffec)
    /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64, pc 64d30)
```

**Comment by thestinger** [comment]
Have you tried multiple apps? Have you already tried rebooting? How long has the issue been happening?

**Comment by drdrsco** [comment]
Snapchat doesn't work or the camera app. When I reboot it, it works. But I
don't want to keep on rebooting it every time. I got this phone 3 days ago
and it's been an issue. I cannot remember if it was a problem before I
downloaded grapheneos.


On Saturday, December 16, 2023, Daniel Micay ***@***.***>
wrote:
> Have you tried multiple apps? Have you already tried rebooting? How long
has the issue been happening?
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.<
https://ci5.googleusercontent.com/proxy/XUfPHv9scg0cR5-02UZaMxb5PttFgsMIuxwgloIQRI-yeESgBB0m9iPi2AyngUOIIYwE9dvkDAx8FNdMhXzXkX6NN52zlMfDqHtwgUywCI_rw9l1SABqeKyX2_WRwlwnF08Uj7ixTfcX3W047BjzaN990VWoVXDcpZIxtTLHYjjaWqtLy8sjYFi_lc_Hn5WC4uE5dLqBtsB-TgJVGkWtUxVKQScT0kk_8DAouxls15_mKYe16A=s0-d-e1-ft#https://github.com/notifications/beacon/BEXFCGD54ZSB3JBUTGKIIRDYJZBOTA5CNFSM6AAAAABAX6C67GWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTTOZYVCY.gif>Message
ID: ***@***.***>

**Comment by thestinger** [comment]
This sounds like broken hardware. You should probably check whether it happens on the stock OS.

**Comment by drdrsco** [comment]
How will I be able to check that? I don't know if I said this or not. But,
the front camera always works. It only happens to the rear camera.

On Sunday, December 17, 2023, Daniel Micay ***@***.***> wrote:
> This sounds like broken hardware. You should probably check whether it
happens on the stock OS.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.<
https://ci5.googleusercontent.com/proxy/W4RsuaMB1B_LFyXuqkPPUTYqIec0xf1XVhdJlx0-BaXOuGkreGt8iRcF9IOeYuYybaj4dfsz9FlcOBb0-7ataa6XxYjOz7jeTV3QOHTp6c-NY400euRQhDf2eYxK5uQ53bkU1p1_3HAgi6r0b0bAAuqO88M4jy2iXXWp8iTLrqzJJ_NM9IjP8T5UqopCozcfekMECoCH8jpTMJu3_e6-a4YbM7M-eUYPP8ylFHPD6z2U4I75lQ=s0-d-e1-ft#https://github.com/notifications/beacon/BEXFCGGNQBKEBSPHHE3FWGDYJ4LSPA5CNFSM6AAAAABAX6C67GWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTTO2FO32.gif>Message
ID: ***@***.***>

**Comment by drdrsco** [comment]
Sorry. I read that wrong. I'll just delete grapheneos and see if it will
happen toy stock OS right? That's the only way?

On Sunday, December 17, 2023, Dom ***@***.***> wrote:
> How will I be able to check that? I don't know if I said this or not.
But, the front camera always works. It only happens to the rear camera.
>
> On Sunday, December 17, 2023, Daniel Micay ***@***.***>
wrote:
>> This sounds like broken hardware. You should probably check whether it
happens on the stock OS.
>>
>> —
>> Reply to this email directly, view it on GitHub, or unsubscribe.
>> You are receiving this because you authored the thread.<
https://ci5.googleusercontent.com/proxy/W4RsuaMB1B_LFyXuqkPPUTYqIec0xf1XVhdJlx0-BaXOuGkreGt8iRcF9IOeYuYybaj4dfsz9FlcOBb0-7ataa6XxYjOz7jeTV3QOHTp6c-NY400euRQhDf2eYxK5uQ53bkU1p1_3HAgi6r0b0bAAuqO88M4jy2iXXWp8iTLrqzJJ_NM9IjP8T5UqopCozcfekMECoCH8jpTMJu3_e6-a4YbM7M-eUYPP8ylFHPD6z2U4I75lQ=s0-d-e1-ft#https://github.com/notifications/beacon/BEXFCGGNQBKEBSPHHE3FWGDYJ4LSPA5CNFSM6AAAAABAX6C67GWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTTO2FO32.gif>Message
ID: ***@***.***>

**Comment by thestinger** [comment]
Since you just did an install recently, that's probably the best approach. You could also see if it happens on a fresh GrapheneOS install to see if changes you made caused it. Since it's a new device and others don't have the issue, it seems like a hardware issue, so you're likely going to need to return it.

**Comment by drdrsco** [comment]
Okay. I will try all that. I did also factory reset it last night and I
still have the same problem.

On Sunday, December 17, 2023, Daniel Micay ***@***.***> wrote:
> Since you just did an install recently, that's probably the best
approach. You could also see if it happens on a fresh GrapheneOS install to
see if changes you made caused it. Since it's a new device and others don't
have the issue, it seems like a hardware issue, so you're likely going to
need to return it.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.<
https://ci5.googleusercontent.com/proxy/SB2HD80lUUWuBxdSSq-wOA_oR4-b_WQikOq0Yc34QeHvl54NWraZfTs7jhQgyID0DUk57pfnZ6En_4IKmvWRRUc_2nEFVjBXZ-m04Xu6sd0L2wKeRfUY2QtS6XsQd3CuG_JnGV7Za_yg6Vy0yb3TEt1nw4kgTahCj4djUtnF0MP3DvWBJw5PN_987gI4bs3z8dD9cVuLKAnNl8X4C4cXfLrPE65AXQgSmyA9c3LrHUuiTRzKuA=s0-d-e1-ft#https://github.com/notifications/beacon/BEXFCGEHHK7KYIAPHEKCIZTYJ4SYLA5CNFSM6AAAAABAX6C67GWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTTO2GKUS.gif>Message
ID: ***@***.***>

**Comment by drdrsco** [comment]
I just wanted to say I got a new pixel. Everything works!
