### ISSUE TITLE
add option to show/hide rotate screen button when phone tilted

### ISSUE THREAD

**Issue by ghtesting2020** [GrapheneOS/os-issue-tracker#2906]
Enhancement suggestion/request:

Add option to show/hide rotate screen orientation pop up when phone tilted. Nothing drives me crazier from switching ios to GrapheneOS is that little rotate screen popup that appears when I tilt my phone left or right. 95% of the time my screen orientation is landscape from my doing. The 5% is when I accidentally press that little button or have to annoyingly wait for it to disappear. When I watch a video the screen already autorotates landscape to go full screen. That little pop up should only appear and be opt in/out with an option in settings if a user wants it. There's already an auto rotate option for those that actually want this behavior and a tile that can be added to quick menu instead of this little pop up.

Thanks for all the work your team does. Lovin' GrapheneOS.

**Comment by thestinger** [comment]
This is the standard Android UI and we're probably not going to change it. It might have more configuration in the future but you're the first person to ever ask for it and therefore it's far too niche for us to do it.
