### ISSUE TITLE
High power consumption

### ISSUE THREAD

**Issue by Pantyhose-X** [GrapheneOS/os-issue-tracker#2911]
# 100% power, standby until tomorrow morning
![1](https://github.com/GrapheneOS/os-issue-tracker/assets/42504385/4b31ae2c-a869-473d-80fc-c185bdb2a1f4)
![2](https://github.com/GrapheneOS/os-issue-tracker/assets/42504385/e3f8bb7a-da55-4259-b8e3-8cf77368f4ae)

---
---
# tomorrow morning
![3](https://github.com/GrapheneOS/os-issue-tracker/assets/42504385/5a81f7aa-69df-4032-befa-c29f939793c5)
![4](https://github.com/GrapheneOS/os-issue-tracker/assets/42504385/24b4ae76-30c2-4eb9-b439-346da4f7df6f)

---
---
---

|name|100% Battery|for tomorrow|
|--------------|-------------|-------------|
|Lanucher|80%|20%|
|System apps|20%|69%|
| |
|System(IDLE)|54%|53%|
|Mobile network|10%|40%|

Normal use of the cell phone **Lanucher** consumes 80% of the power, standby consumes 20%.
**System apps** cell phone consumes 20% of power in normal use and boosts power consumption by 69% in standby.
**System(IDLE)** 53% for both normal use and standby.
**Mobile network** cell phone consumes 10% of power in normal use and boosts power consumption by 40% in standby.

- [ ] Standby I didn't turn on any **Mobile network** It increased the power consumption by 30%.

I enabled System>Multiple users> **Allow running in background** ，And **Clear all** Background was not stop. It's like a Podcast Player in Images.

- [ ] Might need a **forcibly stop** all user apps feature
* **100% battery, 10 hours of standby time until tomorrow morning, when it's only at 70%.**

**Comment by thestinger** [comment]
Battery stats are rough estimates. The estimated time remaining is a rough estimate and running down the power to near 0% is the only way to figure out how long it will actually last.

**Comment by thestinger** [comment]
Not using a carrier doesn't mean cellular is disabled. Airplane mode disables cellular.

> I enabled System>Multiple users> Allow running in background ，And Clear all Background was not stop. It's like a Podcast Player in Images.

Using multiple profiles will reduce battery life. Owner user is always active.

> Might need a forcibly stop all user apps feature

There's already a standard Restricted battery mode you can use.

**Comment by Pantyhose-X** [comment]
> Not using a carrier doesn't mean cellular is disabled. Airplane mode disables cellular.
> 
> > I enabled System>Multiple users> Allow running in background ，And Clear all Background was not stop. It's like a Podcast Player in Images.
> 
> Using multiple profiles will reduce battery life. Owner user is always active.
> 
> > Might need a forcibly stop all user apps feature
> 
> There's already a standard Restricted battery mode you can use.

Lanucher and System(IDLE)  You're blaming user settings and hardware for the high power consumption.

**Comment by thestinger** [comment]
The battery stats are only very rough estimates.
