### ISSUE TITLE
More Quickstep options

### ISSUE THREAD

**Issue by ThatOneCalculator** [GrapheneOS/os-issue-tracker#2916]
Right now, the Recents UI (provided by Quickswitch) is very barebones (only quick action is screenshot, opaque background, etc). Providing either a way to customize it a bit more (transparent/blurred background, more quick actions like share/clear all) or integrating something like [QuickSwitch](https://github.com/skittles9823/QuickSwitch) so launchers could handle that part would be very appreciated.

**Comment by thestinger** [comment]
We won't be adding these features. It's not within the scope of GrapheneOS, and what you've linked is not properly implemented or secure.

**Comment by ThatOneCalculator** [comment]
Is not even adding the option for a transparent background within GrapheneOS's scope? The solid gray frankly just looks unappealing.

**Comment by ThatOneCalculator** [comment]
Ah. Where can I file an issue upstream?
