### ISSUE TITLE
Pixel 8 Display Not Working Correctly when Horizontal in Apps

### ISSUE THREAD

**Issue by ironman92710** [GrapheneOS/os-issue-tracker#2923]
I am running the latest version of stable on a pixel 8. I had another person confirm this was also happening to them, and I didn't see any posts about it in issues, which I'm surprised by. It's pretty significant. In any app (settings/vanadium/installed apps), when you turn the screen horizontally, the screen is edge to edge on the bottom, but it is rectangular/black bar on the top camera portion. This means when you use an app, the whole display is not centered and is slightly shifted off-screen, so buttons and things get hidden. If you flip the phone upside down, you can get the other side cut off in the app, so something is up. The top of the display is edge-to-edge and functions normally when the phone is vertical.

**Comment by thestinger** [comment]
Please disable developer options if they're enabled.

**Comment by ironman92710** [comment]
> Please disable developer options if they're enabled.

They are disabled.

**Comment by crptkng** [comment]
I have this issue to. Seems to have started after I enabled auto-rotate and it is resolved by closing and reopening the app / website

**Comment by ironman92710** [comment]
> I have this issue to. Seems to have started after I enabled auto-rotate and it is resolved by closing and reopening the app / website

I tried closing and reopening apps already, but it didn't fix it. Then I tried disabling and enabling auto-rotate when you said this. Didn't Fix it.

**Comment by ironman92710** [comment]
It turns out this is intended, even though it's gross-looking and can limit functionality.
