### ISSUE TITLE
memtag-kernel caueses bootloop

### ISSUE THREAD

**Issue by miles992** [GrapheneOS/os-issue-tracker#2928]
I tried to enable MTE for the kernel. This will cause a boot loop which is unrecoverable.

Using this command demonstrates the issue:
```
adb shell setprop arm64.memtag.bootctl memtag-kernel
```

Is there any plan to support MTE for the kernel in the future or any hint why this causes a bootloop at all?

**Comment by thestinger** [comment]
It's not supported yet.

**Comment by thestinger** [comment]
The standard MTE implementation for the kernel is not really for hardening. It may be incompatible with some of our hardening changes. It might simply be broken with the current release of the kernel. We use a much newer GKI revision than the stock OS.
