### ISSUE TITLE
Android Open Source Music Player do not opens Music files if there's another Music app installed

### ISSUE THREAD

**Issue by kslcsdalsadg** [GrapheneOS/os-issue-tracker#2941]
GrapheneOS includes the "Android Open Source Music Player" (com.android.music) that plays music files (mp3, ogg, ...) by default.
But when other Music Player is installed the Android Open Source Music Player isn't presented as an option to play Music files.
In my case I'm using Auxio Music Player and Storage Scopes to only show to Auxio my Music files (/sdcard/Music) but when I need to  open a Music file outside this folder (by example a OGG file) system starts Auxio, even if Auxio can't play the file due to is outside the scope.
Why is system not showing a selector to select what Music player will be used to play a specific file when I select it from Files app?
Can you make it possible?

Steps to reproduce the issue:

Without any music player installed:
1) Open Files App
2) Navigate to a foldeer containing a Music File then clic on it
3) File is played with AOSMP (That's fine!)

With another Music Player installed
1) Open Files App
2) Navigate to a foldeer containing a Music File then clic on it
3) File is played with the user installed Music player (That's not fine!)

Thanks

**Comment by empratyush** [comment]
> In my case I'm using Auxio Music Player and Storage Scopes to only show to Auxio my Music files (/sdcard/Music) but when I need to open a Music file outside this folder (by example a OGG file) system starts Auxio, even if Auxio can't play the file due to is outside the scope.

(I think it doesn't have correct/complete SAF implementation.)
[see #322](https://github.com/OxygenCobalt/Auxio/issues/322)

**Comment by empratyush** [comment]
btw i think you can open "Android Open Source Music Player" when other music play is installed.

long press the music file > click three dot (top right) > open with

**Comment by kslcsdalsadg** [comment]
> btw i think you can open "Android Open Source Music Player" when other music play is installed.
> 
> long press the music file > click three dot (top right) > open with

Default Files app included by GrapheneOS doesn't list Android Open Source Music Player app if other Music app (Auxio or other) is installed. 
You can try it ;)

**Comment by empratyush** [comment]
ah! yes. built in media player is only for previewing files. expected behavior.
