### ISSUE TITLE
No swipe momentum.

### ISSUE THREAD

**Issue by OrginalS** [GrapheneOS/os-issue-tracker#2943]
Pixel 6a
Build number: UQ1A.231205.015.2023121200

After turning on or restarting the phone while plugged into a power source or plugging in the phone while the screen is off, swipes "carry less momentum". The screen will stop scrolling sooner after finger stops touching the glass. Bigger swipes will be required to switch between home screens, pull down/up the notification/quick settings panel or app drawer, It also affects apps, some more than others.

**Comment by thestinger** [comment]
That's strange.

**Comment by thestinger** [comment]
Does it happen when plugged into an A/C charger or only a computer?

**Comment by OrginalS** [comment]
Upon further investigation it happens every time the device is plugged in, but only with this specific travel charger.
![IMG_20231226_022807](https://github.com/GrapheneOS/os-issue-tracker/assets/36825453/d20b662c-09ee-45be-a32a-f08208c7dba6)

Video of what happens, sorry for low bitrate:


https://github.com/GrapheneOS/os-issue-tracker/assets/36825453/e9b2747d-7868-4a95-be1c-61ddfb38dadc

**Comment by thestinger** [comment]
This sounds like it's somehow causing electrical interference with the touchscreen. Hard to see how it could be a software issue.

**Comment by OrginalS** [comment]
Yeah probably not related to grapheneOS, sorry.

**Comment by thestinger** [comment]
No worries. Most of the issue reports are upstream bugs of some kind. Sometimes we can do something about them.
