### ISSUE TITLE
Auto blocking Camera / Mic by default option

### ISSUE THREAD

**Issue by LunchBoxC** [GrapheneOS/os-issue-tracker#2948]
Could we get a feature enhancement that we can toggle on for the Camera and Mic block that automatically blocks these after a period of inactivity.  

When using an app it asks you if you want to unblock the camera and microphone anyway, so why not have an option to block them by default so if the user forgets to turn them off and the option is set it will automatically default to off like we have an option for Bluetooth / WiFi.

Also if we have this for the Mic it should automatically un-mute the microphone when an incoming call comes in upon answering if it's still in the "blocked" condition.

Thanks for considering these ideas.

**Comment by thestinger** [comment]
You can give out one-time access via the existing permissions so we don't plan to add this right now. The global microphone and camera toggles aren't very useful. The location one is perhaps a bit more useful if you give out background access to specific apps but sometimes don't want it. Also, an app using them could keep it from being disabled by using it before it gets disabled. That's essentially a bypass for this. The issue would be allowing an app to keep using it.
