### ISSUE TITLE
Pixel 8 pro kernel crash (when standby)

### ISSUE THREAD

**Issue by shortenage** [GrapheneOS/os-issue-tracker#2949]
Pixel 8 pro kernel crash when standby (screen locked) an no application opened. Sometimes kernel crash when open any apps (ex, Vanadium), or crashed when login (entering auth from locked screen).

This happening from fresh install, no apps installed other than default (the condition is still new flashed)

[kernel-crash.txt](https://github.com/GrapheneOS/os-issue-tracker/files/13775234/kernel-crash.txt)

**Comment by thestinger** [comment]
Hardware/firmware/driver issue, not something we can address.
