### ISSUE TITLE
7a lock screen artifacts

### ISSUE THREAD

**Issue by tguen** [GrapheneOS/os-issue-tracker#2958]
Since the Dec 7 update, my lock screen is black with yellow artifacts all over. If I change the lock screen, it shows whatever I set it to for about 10 minutes, then goes back to this.

![IMG_20210329_030311](https://github.com/GrapheneOS/os-issue-tracker/assets/57420975/792d09a0-7148-412b-8f63-1665696aa62d)

**Comment by thestinger** [comment]
Turn off developer options if it's enabled. Reset app preferences if that doesn't work. Otherwise, this is likely a hardware issue.
