### ISSUE TITLE
Enable Bluetooth HCI Snoop Log stops devices from connecting to devices

### ISSUE THREAD

**Issue by heckarman** [GrapheneOS/os-issue-tracker#2959]
I'm trying to snoop into my device's Bluetooth to see the Bluetooth packets and had to 'enable' Bluetooth HCI snoop log. Now that, I cannot connect any of my devices that I wanted to snoop in unless I disable them rendering the whole option useless.

In Bluetooth menu though, it just keeps on trying to connect by moving up and down uncontrollably.

**Comment by thestinger** [comment]
Doesn't sound like GrapheneOS-specific behavior. Unless it only happens on GrapheneOS and not the stock OS, it's a support request rather than an issue report.

**Comment by heckarman** [comment]
NVM, after rebooting twice - thrice, it started working all of a sudden.
