### ISSUE TITLE
question: exFAT support for Pixel 5

### ISSUE THREAD

**Issue by j-lakeman** [GrapheneOS/os-issue-tracker#2961]
Will exFAT ever be supported for Pixel 5? I read that Pixel 6 supports it.
It would be quite handy IMHO to be able to use an external drive for backups with the commonly supported exFAT format.

**Comment by thestinger** [comment]
No, and the Pixel 5 is end-of-life now and in extended support from GrapheneOS. It doesn't have firmware or most driver updates anymore so it really needs to be replaced.

https://grapheneos.org/faq#supported-devices
