### ISSUE TITLE
feature request: double tap status bar to lock device

### ISSUE THREAD

**Issue by j-lakeman** [GrapheneOS/os-issue-tracker#2962]
Lineage OS and derivates have the handy setting “tap to sleep”, which would be also quite useful to have in Graphene OS IMHO.
It could even be a security feature if the screen is not just turned off, but also locked.
It also has the potential to prevent the lock button from early breakage, which could contribute to more sustainability.

![Screenshot_20231228-143329_Settings](https://github.com/GrapheneOS/os-issue-tracker/assets/101660243/4c5963e3-2240-4fd8-90c7-a35214e24695)

**Comment by thestinger** [comment]
We don't see much use for this compared to pressing power. It might be slightly more convenient when the phone is lying on a surface but otherwise isn't. We don't currently plan to add it.

**Comment by d3vv3** [comment]
It improves durability of the phone by extending the lifespan of the power button number of clicks. I would love this feature, in companion to "Press and hold fingerprint sensor" to unlock the phone from black screen.
