### ISSUE TITLE
"Extra dim" setting does not persist between reboots and profile switches

### ISSUE THREAD

**Issue by sqrtiswap** [GrapheneOS/os-issue-tracker#2967]
Hi,

when doing a reboot or switching between profiles the `Extra dim` setting resets to off (I assume off is the default setting).
I would have expected it to be persistent and tied to a given profile.
The device is the Pixel 6.

Is this behaviour to be expected, i.e. is it upstream behaviour or is this a bug in GrapheneOS?

**Comment by thestinger** [comment]
There are more settings if you view it in the Settings app.

**Comment by thestinger** [comment]
This doesn't look like a bug, it's just how the quick time works compared to the other settings.

**Comment by sqrtiswap** [comment]
Thanks for letting me know!
Also: Sorry for the noise, I had indeed only ever used the toggle in the pull-down menu and not even considered that there might be additional settings in the Settings app. The toggle `Keep on after device restarts` seems to do exactly what I was after.
