### ISSUE TITLE
Pixel 7 Pro Kernel Panic while in pocket

### ISSUE THREAD

**Issue by ORIOLESFan02** [GrapheneOS/os-issue-tracker#2976]
No idea how or why it crashed, but it did. Here are the logs.

https://pastebin.com/dDSF0x1u

**Comment by thestinger** [comment]
Looks like something outside our control (hardware-related, not caused by hardening).

**Comment by ORIOLESFan02** [comment]
> Looks like something outside our control (hardware-related, not caused by hardening).

Interesting. I believe this is the first time I've seen something like this. I appreciate it.
