### ISSUE TITLE
Kernal Crash When Phone in Pocket + Apps Crashing (Pixel 7 Pro)

### ISSUE THREAD

**Issue by ghosty999** [GrapheneOS/os-issue-tracker#2980]
Recently Ive noticed alot more crashing when opening and swapping between some apps. Then today my phone restarted with a Kernal Crash message upon booting. 

The crash log was too long to post so let me know if any other info is required.

type: crash
isPrevious: true
Build: google/cheetah/cheetah:14/UQ1A.231205.015/2023121200:user/release-keys
Hardware: cheetah
Revision: MP1.0
Bootloader: cloudripper-14.0-10825040
Radio: null
Kernel: Linux version 5.10.201-android13-4-g3e30cc4d5f20 (build-user@build-host) (Android (8508608, based on r450784e) clang version 14.0.7 (https://android.googlesource.com/toolchain/llvm-project 4c603efb0cca074e9238af8b4106c30add4418f6), LLD 14.0.7) #1 SMP PREEMPT Sun Dec 10 13:25:47 UTC 2023

**Comment by thestinger** [comment]
Need the crash log itself. You can attach it as a file.

**Comment by ghosty999** [comment]
[Pixel7Pro-CrashReport010124.txt](https://github.com/GrapheneOS/os-issue-tracker/files/13805075/Pixel7Pro-CrashReport010124.txt)

Sorry for the n00biness! Attached.

**Comment by thestinger** [comment]
@ghosty999 The kernel crash looks like a hardware or driver issue, not something caused by GrapheneOS. Can you give more details about your app crashes?

**Comment by ghosty999** [comment]
> @ghosty999 The kernel crash looks like a hardware or driver issue, not something caused by GrapheneOS. Can you give more details about your app crashes?

I will try grab more info next time it happens. Basically when swapping between apps that either use the camera and/or "picture in picture" playback (like Revanced YouTube) sometimes it will stick. Closing the app usually solves the issue, but it means I lose my place in what I was doing. I'll try grab a screen recording next time it occurs. Thanks.

**Comment by ghosty999** [comment]
Another crash today opening camera app:

```
type: crash
osVersion: google/cheetah/cheetah:14/UQ1A.231205.015/2023123100:user/release-keys
uid: 1000 (u:r:hal_camera_default:s0)
cmdline: /apex/com.google.pixel.camera.hal/bin/hw/android.hardware.camera.provider@2.7-service-google
processUptime: 0s

abortMessage: terminating

signal: 6 (SIGABRT), code -1 (SI_QUEUE)
threadName: SessionPool

backtrace:
    /apex/com.android.runtime/lib64/bionic/libc.so (abort+164, pc 62ea4)
    /apex/com.android.vndk.v34/lib64/libc++.so (abort_message+276, pc 4d144)
    /apex/com.android.vndk.v34/lib64/libc++.so (demangling_terminate_handler() (.__uniq.205383134706309982814331919004001075825)+72, pc 4d298)
    /apex/com.android.vndk.v34/lib64/libc++.so (std::__terminate(void (*)())+8, pc 4df98)
    /apex/com.android.vndk.v34/lib64/libc++.so (std::terminate()+32, pc 4df20)
    /apex/com.android.vndk.v34/lib64/libc++.so (std::__1::thread::~thread()+24, pc ad5b8)
    /apex/com.google.pixel.camera.hal/lib64/liblyric_hwl.so (pc d8f074)
    /apex/com.google.pixel.camera.hal/lib64/liblyric_hwl.so (pc 3e6878)
    /apex/com.google.pixel.camera.hal/lib64/liblyric_hwl.so (pc 3e5614)
    /apex/com.google.pixel.camera.hal/lib64/liblyric_hwl.so (pc 3e5558)
    /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204, pc cfa2c)
    /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64, pc 64770)
```

**Comment by thestinger** [comment]
That's not a kernel crash and is entirely unrelated. It's just the software aborting due to some hardware issue or upstream bug. It may have just lost a connection to the hardware.

**Comment by ghosty999** [comment]
> That's not a kernel crash and is entirely unrelated. It's just the software aborting due to some hardware issue or upstream bug. It may have just lost a connection to the hardware.

Ahh okay. Any idea why I'm suddenly having these crash errors? They all started coming at once about 2 weeks ago. I'm not sure if it was just after an update or not, but performance has degraded on my device. Switching between apps and searching in the settings is slower and can crash like above. Thanks and sorry if this is unrelated to a Kernal Crash. Maybe I need to change the topic title?
