### ISSUE TITLE
Feature Request: Now Playing

### ISSUE THREAD

**Issue by bcsti** [GrapheneOS/os-issue-tracker#2984]
Now Playing is a proprietary feature special to Pixel Phones.

It would be a good addition to GOS since it is:
 - small in size
 - runs locally only
 - does not need network/internet permissions
 - sometimes very useful in everyday life 

So far I am using Shazam, but in terms of privacy, it is not a permanent solution and it is not well integrated into the OS. 

It could be installed the same as Markup/Android Auto using the GOS App store.

This request has no high priority and would just be "nice to have" since I can't see any drawbacks when it would be optionally aviable via the App Store.

For your info, there is already a port of Now Playing, maybe the devs could use it as a entry point? https://github.com/KieronQuinn/AmbientMusicMod

**Comment by thestinger** [comment]
This isn't planned.
