### ISSUE TITLE
Apple USB-C to Jack and USB-C headphones not working on UK/CA version but working on US Pixel 6a

### ISSUE THREAD

**Issue by krysor** [GrapheneOS/os-issue-tracker#2985]
I happen to own 2 versions of the Google Pixel 6a:
- UK/CA (G1AZG), UFS from Micron*
- US bought at US Google Store, UFS from SKHynix*

*according to Fastboot

Apple USB-C to 3.5 mm Headphone Jack Adapter is working perfectly in combination with different headphones on the stock rom on both devices.

The same setup only works on GrapheneOS with the US version but not with the UK/CA version. On the latter the device plays audio as if no adapter + headphones were connected. I am unable to verify whether it works with a different unit of the UK/CA version.

The same issue occurs when using the original Google USB C headphones.

The issue has been mentioned [here](https://discuss.grapheneos.org/d/7448-apple-usb-c-to-jack-not-working-on-ukca-version-but-working-on-us)

**Comment by thestinger** [comment]
Doesn't sound like a software issue.
