### ISSUE TITLE
Kernel crash on Pixel 5a

### ISSUE THREAD

**Issue by danbur** [GrapheneOS/os-issue-tracker#2992]
I keep getting kernel crashes at fairly random times during various user interactions (no discernible pattern) on a Pixel 5a. Attched are the logs.

[Crash Log.txt](https://github.com/GrapheneOS/os-issue-tracker/files/13815110/Crash.Log.txt)

**Comment by thestinger** [comment]
Unfortunately there's no usable info for us in the log. it does show that the device has repeatedly locked up and been rebooted by the hardware watchdog, or that the hardware watchdog is buggy and rebooting it unnecessarily.
