### ISSUE TITLE
Pixel 8: Low Wifi range

### ISSUE THREAD

**Issue by heuwerk** [GrapheneOS/os-issue-tracker#3003]
Hello dear GrapheneOS team,
I've been using a Pixel 8 for a few weeks now and installed GrapheneOS on it straight away.

I have now noticed that the Pixel 8 has a significantly lower Wi-Fi range and the connection drops much earlier than with my previous Pixel 5.

Is this a known problem with the device or could it be due to GrapheneOS? I have not tested this with the stock ROM.

Device data:
Model: `Google Pixel 8 256 GB`
OS version: `GrapheneOS (Android 14)`
Build number: `UQ1A.231205.015.2023123100`

Kind regards
heuwerk

**Comment by thestinger** [comment]
No, it's not due to GrapheneOS. It's possible that the Pixel 8 is using a newer standard like 6GHz support that wasn't being used before and is contributing to you having a worse connection.

**Comment by thestinger** [comment]
Get info on the Wi-Fi network on both devices and compare. You can try changing settings on the Pixel 8.

**Comment by heuwerk** [comment]
Thank you @thestinger  for your quick reply.

In a direct side-by-side comparison, there is not much difference in the signal strength, the Pixel 8 shows the status Fair instead of Good a little earlier.

Maybe I got a defective device or I'm holding it wrong :wink:
