### ISSUE TITLE
google sandboxed layer doesnt allow signin when security key enable and account was signed out remotely

### ISSUE THREAD

**Issue by bedair81** [GrapheneOS/os-issue-tracker#3009]
steps to reproduce:
1. adding security keys to a google account
2.  enabling advanced protection mode(which signs out all currently signed in devices), also tested with just remotely signing said device out from another client
3. attempt to sign in on the "manage your google account screen", alternatively tapping the "account action required" notification from play services
4. reach never ending load screen where security key prompt should show up

logging into the google account from vanadium still showed the popup, successfully reproduced a few times, also had a similar issue on a Pixel 7 Pro last year on android 13. 
Currently using a Pixel 8 Pro on build [2023123100]

**Comment by bedair81** [comment]
![Screenshot_20240104-195106~2.png](https://github.com/GrapheneOS/os-issue-tracker/assets/114684096/09aace19-dab9-4e1a-8043-c75f1148b116)

![Screenshot_20240104-201002~2.png](https://github.com/GrapheneOS/os-issue-tracker/assets/114684096/898e1b3e-af92-499e-87c8-45a9995e9e91)

![Screenshot_20240104-195319~2.png](https://github.com/GrapheneOS/os-issue-tracker/assets/114684096/48532635-2d6c-4183-b4c1-097db488fb1e)

**Comment by thestinger** [comment]
There's a lack of evidence that this is a GrapheneOS specific issue.

**Comment by bedair81** [comment]
fair enough, unable to get my hands on a 2nd device for right now but will update this in the future if i can replicate the issue or not, thanks.

**Comment by thestinger** [comment]
We've seen cases of people having these issues on stock OS. There are likely some compatibility layer bugs but it isn't clear if this is one.
