### ISSUE TITLE
Kernel panic when attempting to use Pixel 6a as webcam

### ISSUE THREAD

**Issue by bkrl** [GrapheneOS/os-issue-tracker#3011]
I had a kernel panic when I attempted to use my Pixel 6a as a USB webcam. Camera access was set to blocked. I wasn't able to reproduce this.

[kernel_panic_log.txt](https://github.com/GrapheneOS/os-issue-tracker/files/13838614/kernel_panic_log.txt)

**Comment by thestinger** [comment]
Looks the same as https://github.com/GrapheneOS/os-issue-tracker/issues/2789.
