### ISSUE TITLE
Android Auto wireless not connecting when hotspot is on

### ISSUE THREAD

**Issue by soupslurpr** [GrapheneOS/os-issue-tracker#3024]
When hotspot is on, Android Auto (wireless, haven't tested wired) does not connect. Turning off hotspot allows it to connect, and the hotspot can be turned on without issue afterwards. Pixel 7.

**Comment by gvijayakumar-16** [comment]
Having the same issue, but not able to connect irrespective of hotspot status. 

Wired works seamlessly though.

**Comment by muhomorr** [comment]
Android Auto doesn't connect when hotspot is on on stock OS too.

@gvijayakumar-16 You have an unrelated issue. The log is incomplete, it lacks the majority of Android Auto entries,
