### ISSUE TITLE
Call recording notify option

### ISSUE THREAD

**Issue by Felting** [GrapheneOS/os-issue-tracker#3026]
Would be useful to have an option to notify the other party when the call is being recording like the google dialer, this would be useful if you're in a region where this is required by law.

**Comment by thestinger** [comment]
The only way to properly notify other people on the call that it's being recorded is saying so in the language that's going to be used for the call. It's not realistic for the OS to do this. How would it know which language to use? Beeping is not truly informing the other party that it's being recorded. People are responsible for complying with this law themselves.

**Comment by thestinger** [comment]
The only way to properly notify other people on the call that it's being recorded is saying so in the language that's going to be used for the call. It's not realistic for the OS to do this. How would it know which language to use? Beeping is not truly informing the other party that it's being recorded. People are responsible for complying with these laws themselves.

Since call recording is currently always explicit rather than automatic, a user can't forget they have recording enabled. It is worth considering that someone could forget to have automatic call recording enabled, so making that clear in the UI for each call is important.

**Comment by thestinger** [comment]
It's often the case that people on a call are in different regions. Complying with the region for the user's current carrier is not necessarily enough. They may be calling someone in a region where it's required for them to notify the other person and that may still apply to them despite not currently being in that region. For example, they may be travelling and have a different carrier temporarily but are calling back to where they live and can't simply ignore the law there. Also, which language should be used? Simply assuming that the language matches the carrier isn't good enough. It's not realistic to do this, and I think it's better to leave it up to people to handle it. There are many things that are illegal and the OS doesn't try to stop you misusing it for those things in general, it just avoids breaking the law without you having control over it, meaning it should not record calls without explicitly asking to do it and automated call recording in particular should have a clear disclaimer about this.

**Comment by Felting** [comment]
> It's often the case that people on a call are in different regions. Complying with the region for the user's current carrier is not necessarily enough. They may be calling someone in a region where it's required for them to notify the other person and that may still apply to them despite not currently being in that region. For example, they may be travelling and have a different carrier temporarily but are calling back to where they live and can't simply ignore the law there. Also, which language should be used? Simply assuming that the language matches the carrier isn't good enough. It's not realistic to do this, and I think it's better to leave it up to people to handle it. There are many things that are illegal and the OS doesn't try to stop you misusing it for those things in general, it just avoids breaking the law without you having control over it, meaning it should not record calls without explicitly asking to do it and automated call recording in particular should have a clear disclaimer about this.

An option to play an customisable audio file when call recording is toggled would bypass the need for a database of languages/audio and would be better than the stock solution. This would also make it easier for newer users used to the stock behavior of notifying the other party by default.
