### ISSUE TITLE
No way to connect fossil watch 

### ISSUE THREAD

**Issue by ale4** [GrapheneOS/os-issue-tracker#3031]
```
type: crash
osVersion: google/crosshatch/crosshatch:12/SP1A.210812.016.C2/2023020600:user/release-keys
package: com.google.android.gms:234816038
process: com.google.android.gms.persistent
processUptime: 780546 ms
GmsCompatConfig version: 90

java.lang.SecurityException: Need android.permission.BLUETOOTH_CONNECT permission for android.content.AttributionSource@1bee8c6d: AdapterService getRemoteName
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2436)
	at android.os.Parcel.createException(Parcel.java:2420)
	at android.os.Parcel.readException(Parcel.java:2396)
	at android.os.Parcel.readException(Parcel.java:2338)
	at android.bluetooth.IBluetooth$Stub$Proxy.getRemoteName(IBluetooth.java:3395)
	at android.bluetooth.BluetoothDevice.getName(BluetoothDevice.java:1274)
	at demh.run(:com.google.android.gms@234816038@23.48.16 (190400-590025996):10)

```

**Comment by ale4** [comment]
Hello,
Thank you for the response. Ack all.
The reason I keep an old device is 5G. I'd rather have LTE/4G device
and mechanical watch, than melt my brain with a microwave.
Thank you again.

Alex

**Comment by thestinger** [comment]
5G is optional. You can disable it. You shouldn't use an insecure device without security patches available. You can't fix the Pixel 3 XL with an alternate OS.

**Comment by thestinger** [comment]
You can also just use the standard way of setting 4G as maximum, which disables 5G.

**Comment by ale4** [comment]
Thanks for the advice and ack all.
I will try to find a way to manage. However my provider advised otherwise:
Once it is built in it will be used by towers it connects automatically and
there is no way to alter it.

**Comment by thestinger** [comment]
That's not at all accurate. There are toggles for controlling which radio standards are used. You're currently using a highly insecure device that has been end-of-life since after October 2021...

**Comment by ale4** [comment]
Thank you for your response. Is there a comparison tool/chart between
existing devices compatible w Graphene OS?

**Comment by thestinger** [comment]
See https://grapheneos.org/faq#recommended-devices. 8th generation Pixels have hardware memory tagging and a significant CPU upgrade to ARMv9 cores along with other minor hardware upgrades. They also have 7 years of support from launch rather than 5 like 6th/7th gen and 3 years like earlier devices. 6th to 7th gen was a much smaller upgrade, mostly a GPU upgrade. Older devices shouldn't be purchased, only the Pixel 5a is not end-of-life yet.

**Comment by ale4** [comment]
Thank you very much for all the detailed info. I Appreciate your time and
efforts!
