### ISSUE TITLE
Can't persist per-network MAC randomization

### ISSUE THREAD

**Issue by bitrate16** [GrapheneOS/os-issue-tracker#3033]
Device: Google Pixel 7 Pro
OS: UQ1A.240105.004.2024010400

Issue description:
I have set MAC randomization to "per-network randomized mac" , but MAC address doesn't persist same in same network (same SSID for 3 mesh AP's). I assume that it may be caused by profile switch or reboot or reconnect (haven't deterministic reproduced it yet), but for some reasons, mac address changes.

Detected it because have set strict mac-based device registration in home network and pixel ignores this setting and sometimes changes it's mac address and then receives another IP. 

Verified that it does not happen with any other device

**Comment by thestinger** [comment]
Turn off development options. It sounds like you enabled the misguided upstream non-persistent MAC address toggle there. It's not useful on GrapheneOS where per-connection MAC randomization is the default and less persistent (but still not per-connection) MAC randomization isn't useful.

**Comment by bitrate16** [comment]
> misguided upstream non-persistent MAC address toggle

Switched off and will observe it's behavior
