### ISSUE TITLE
Kernel crash on Pixel 4a (5G)

### ISSUE THREAD

**Issue by Schlumpf** [GrapheneOS/os-issue-tracker#3042]
Since the last update, the kernel crashs randomly. I didn't use my phone, had it in my pocket. This is the second crash since last update.

See attached log
[crash.log](https://github.com/GrapheneOS/os-issue-tracker/files/13870165/crash.log)

**Comment by thestinger** [comment]
This appears to be a hardware problem.

You're on an end-of-life device receiving extended support and should move to a supported device.
