### ISSUE TITLE
Pixel 8 kernel crash

### ISSUE THREAD

**Issue by cjtamayo** [GrapheneOS/os-issue-tracker#3048]
New to graphene and having stability issues. Lots of kernel crashes and UI is buggy.
[Kernal_crash.txt](https://github.com/GrapheneOS/os-issue-tracker/files/13883013/Kernal_crash.txt)

**Comment by thestinger** [comment]
Appears to be a hardware issue.

**Comment by thestinger** [comment]
You should get the device replaced.
