### ISSUE TITLE
Pixel 7 Pro Kerner Crash GPU?

### ISSUE THREAD

**Issue by EverettCMarm** [GrapheneOS/os-issue-tracker#3055]
[kernerlcrash2.txt](https://github.com/GrapheneOS/os-issue-tracker/files/13906664/kernerlcrash2.txt)

Attached full dump.

GPU Errors?

**Comment by thestinger** [comment]
This appears to be a firmware/hardware issue. Did it happen once or repeatedly?

**Comment by thestinger** [comment]
I don't think anything can be done about this. It hard reset the malfunctioning GPU and then it continued happening.

**Comment by EverettCMarm** [comment]
Began noticing these crashes reporting each time I picked up the phone and saw that it had crashed. Happens randomly.

The Google OS was working, the odd thing is that the Google OS, 4-5 Bars cell connectivity, GOS 1-2

**Comment by thestinger** [comment]
Google doesn't report OS crashes to users, GrapheneOS does. That doesn't mean it wasn't happening on the stock OS.

Are you noticing the crashes themselves or only the crash reports?

**Comment by EverettCMarm** [comment]
I've only witnessed one crash. The rest seemed to be overnight. I haven't witnessed any malfunction under the Google OS, cellular radio gets 4-5 bars, file copies work etc. Just very odd that this crashes every now and then

On January 11, 2024 5:57:12 PM UTC, Daniel Micay ***@***.***> wrote:
>It sounds like your hardware is failing and needs to be replaced. None of this is GrapheneOS related.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/GrapheneOS/os-issue-tracker/issues/3055#issuecomment-1887683331
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Sent from a secret bunker, hidden miles below the Antarctic ice sheet.

**Comment by thestinger** [comment]
> I've only witnessed one crash. The rest seemed to be overnight. I haven't witnessed any malfunction under the Google OS

It doesn't report crashes, and you seem to have been using GrapheneOS longer. The user facing crash reporting we added doesn't exist in the stock OS. It doesn't mean it doesn't have most of the same crashes.

> cellular radio gets 4-5 bars

This doesn't seem related to GrapheneOS but rather is a carrier / carrier configuration issue. It's totally unrelated to this issue.

> file copies work

Not clear what you're talking about.

**Comment by EverettCMarm** [comment]
Basically, testing apps I use and making sure everything is working.

 

Android Auto functionality has been wonderful, thank you!

 

I had the phone reboot spontaneously once while I was using it. 

 

I’m a bit lost as to why changing to GOS lost the connectivity that I had under the Google stock OS. 

 

Could what I am seeing be a driver issue? Is there a way to force GOS back down without redoing everything?

 

Best Regards,

 

Ellis George

 

Sent from a secret bunker, hidden miles below the Antarctic ice sheet.
