### ISSUE TITLE
Kernal Crash

### ISSUE THREAD

**Issue by cory-mark37** [GrapheneOS/os-issue-tracker#3058]
[Editor.txt](https://github.com/GrapheneOS/os-issue-tracker/files/13919592/Editor.txt)

I attached a kernal crash above.

**Comment by thestinger** [comment]
Looks like hardware detected lockup. Unclear if it's a software, firmware or hardware issue. The log somehow had all the newlines removed so it's really hard to read. There's likely no useful info though.
