### ISSUE TITLE
Kernel panic while watching Netflix + frequent app crashes

### ISSUE THREAD

**Issue by codethief** [GrapheneOS/os-issue-tracker#3077]
I'm on a Pixel 8 running the most recent GrapheneOS version (build UQ1A.240105.004.2024010400). I had been watching Netflix for a good half hour when suddenly the app froze and then a few seconds later the screen went black and the phone rebooted. Please find the kernel logs below.

Not sure if it's relevant, but GrapheneOS has been surprisingly unstable for me in recent weeks (maybe even ever since I switched from a Pixel 5 to a Pixel 8 about two months ago). Apps tend to crash every now and then (most prominently Firefox, K-9 Mail & Syncthing but not exclusively so), whereas on the Pixel 5 the same apps had been rock-solid and for years I never experienced any crashes, let alone kernel panics. Unfortunately, I'm often on the road when the crashes happen, otherwise I'd provide logcat logs. (Is there a good way to access the logs from the phone itself?) EDIT: Just as I was writing this and googling for answers to my question, the screen went dark, and Firefox crashed again. (The phone did not reboot, though.) I'll hit Submit for now.

[2024-01-14 Kernel panic.md](https://github.com/GrapheneOS/os-issue-tracker/files/13932847/2024-01-14.Kernel.panic.md)

**Comment by thestinger** [comment]
Appears to be a hardware issue. You'll likely need to return the device.
