### ISSUE TITLE
Panther kernel crash under regular use

### ISSUE THREAD

**Issue by john-ghatas** [GrapheneOS/os-issue-tracker#3087]
Contextual info:
- Sandboxed Play services and android auto enabled.

- Crash occurred randomly at home, thus not connected to AA.

- Build number: UQ1A.240105.004.2024011300

https://paste.opensuse.org/pastes/5b79f376590f

**Comment by john-ghatas** [comment]
Possibly connected to #3089

**Comment by thestinger** [comment]
Appears to be a hardware issue.

`[ 6863.198092][T31534] aoc: encountered error on disabling sensor_3v3.`
