### ISSUE TITLE
ScreenFlickers touch not responsive followed by a kernel crash

### ISSUE THREAD

**Issue by geckogambit** [GrapheneOS/os-issue-tracker#3089]
Hi team,
Running latest stable GraphaneOS on Pixel 6 Pro.

I was experiencing a screen "flickering" for a couple of weeks already, tried checking different settings etc to fix it. Most of the time the issue got fixed by itself after reboot.

Today it happen again  but I had no luck with the reboot (trying to manage to hit the reboot button on the touch during the mess) So I hold power button + volume Up, it promt me for a safe mode initially (misclick I guess) afterwards I confirmed a normal reboot and got this issue.

Two days ago I had the flickering happen right after reboot.
Phone is absolutely not usabe during the period of the bug.
Once I've managed to open the camera and without touching the display it was registering "clicks" like crazy (in a ms intervals) changing the focus circle place.

Log from the crash attached as they are too long.
[crash.txt](https://github.com/GrapheneOS/os-issue-tracker/files/13939314/crash.txt)

I can provide a video of the flickering as well as anything else if needed, please contact me.

**Comment by geckogambit** [comment]
I do not use fingerprint functionality, unlocking is happeing via PIN.

**Comment by thestinger** [comment]
The log you've attached is not from a crash but rather holding power button:

>   Reboot reason: 0xccca - Long Press Power Key Reboot

You may have a broken power button.

**Comment by geckogambit** [comment]
What about the screen flickering and ghost touches, after all, I would not hold the power button for longer than intended l, if the touch worked?
P.S. The button is still fine.

**Comment by thestinger** [comment]
That part sounds like a hardware issue.
