### ISSUE TITLE
Kernel Panic "OPEN_SECURE_OBJECT_FAILED"

### ISSUE THREAD

**Issue by StrangePelaton** [GrapheneOS/os-issue-tracker#3090]
Here is a link to the error log. 
https://pastebin.com/m7E1J9Xb

**Comment by thestinger** [comment]
Looks like a hardware issue.

**Comment by thestinger** [comment]
> OPEN_SECURE_OBJECT_FAILED

That's a failure happening after the error while handling the error rather than the error itself.
