### ISSUE TITLE
Numerous crash logs, any pattern?

### ISSUE THREAD

**Issue by StrangePelaton** [GrapheneOS/os-issue-tracker#3091]
```
```
type: crash
osVersion: google/oriole/oriole:14/UQ1A.231205.015/2023123100:user/release-keys
uid: 1000 (u:r:system_server:s0)
cmdline: system_server
processUptime: 38325s

signal: 11 (SIGSEGV), code 1 (SEGV_MAPERR), faultAddr c77d22ef4c70
threadName: InputProcessor

backtrace:
    <unknown> (pc c77d22ef4c70)
    /system/lib64/libbinder_ndk.so (AParcel_writeCharArray+88, pc 12c78)
    /system/lib64/android.hardware.input.common-V1-ndk.so (aidl::android::hardware::input::common::VideoFrame::writeToParcel(AParcel*) const+68, pc 38d4)
    /system/lib64/libbinder_ndk.so (AParcel_writeParcelableArray+76, pc 124ac)
    /system/lib64/android.hardware.input.common-V1-ndk.so (aidl::android::hardware::input::common::MotionEvent::writeToParcel(AParcel*) const+420, pc 25a4)
    /system/lib64/android.hardware.input.processor-V1-ndk.so (aidl::android::hardware::input::processor::BpInputProcessor::classify(aidl::android::hardware::input::common::MotionEvent const&, aidl::android::hardware::input::common::Classification*)+192, pc 4720)
    /system/lib64/libinputflinger.so (android::MotionClassifier::processEvents()+268, pc 8921c)
    /system/lib64/libinputflinger.so (void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (android::MotionClassifier::*)(), android::MotionClassifier*> >(void*)+60, pc 8f4dc)
    /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204, pc cfa2c)
    /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64, pc 64770)
```

```

**Comment by fuckingridiculous** [comment]
/```
type: crash
osVersion: google/oriole/oriole:14/UQ1A.231205.015/2023123100:user/release-keys
uid: 1000 (u:r:system_server:s0)
cmdline: system_server
processUptime: 42219s

signal: 11 (SIGSEGV), code 2 (SEGV_ACCERR), faultAddr caed7509a850
threadName: android.display

backtrace:
    /system/lib64/libcutils.so (atrace_get_enabled_tags+16, pc 119e0)
    /system/lib64/libartpalette-system.so (PaletteTraceEnabled+16, pc 45b0)
    /apex/com.android.art/lib64/libart.so (void art::Monitor::Lock<(art::LockReason)1>(art::Thread*)+4296, pc 576598)
    /apex/com.android.art/lib64/libart.so (art::Monitor::MonitorEnter(art::Thread*, art::ObjPtr<art::mirror::Object>, bool)+560, pc 57b830)
    /apex/com.android.art/lib64/libart.so (artLockObjectFromCode+36, pc 75aaf4)
    /apex/com.android.art/lib64/libart.so (art_quick_lock_object_no_inline+52, pc 210ea4)
    /system/framework/oat/arm64/services.odex (com.android.server.power.PowerManagerService$LocalService.setUserActivityTimeoutOverrideFromWindowManager+104, pc 754468)
    /system/framework/oat/arm64/services.odex (com.android.server.wm.RootWindowContainer$MyHandler.handleMessage+136, pc 90a1a8)
    /system/framework/arm64/boot-framework.oat (android.os.Handler.dispatchMessage+168, pc 55a968)
    /system/framework/arm64/boot-framework.oat (android.os.Looper.loopOnce+1036, pc 55db7c)
    /system/framework/arm64/boot-framework.oat (android.os.Looper.loop+552, pc 55d6e8)
    /system/framework/arm64/boot-framework.oat (android.os.HandlerThread.run+572, pc 55c9ec)
    /system/framework/oat/arm64/services.odex (com.android.server.ServiceThread.run+88, pc 460ae8)
    /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612, pc 2109a4)
    /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+172, pc 253b3c)
    /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1416, pc 69abc8)
    /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204, pc cfa2c)
    /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64, pc 64770)
```

**Comment by fuckingridiculous** [comment]
```
```
type: crash
osVersion: google/oriole/oriole:14/UQ1A.231205.015/2023123100:user/release-keys
uid: 1000 (u:r:system_server:s0)
cmdline: system_server
processUptime: 24414s

signal: 11 (SIGSEGV), code 2 (SEGV_ACCERR), faultAddr c5dfe7b05510
threadName: android.anim

backtrace:
    [anon:libwebview reservation] (pc 1c175510)
    /system/framework/oat/arm64/services.odex (com.android.server.wm.InputConfigAdapter.applyMapping+156, pc 8ee4ec)
    /system/framework/oat/arm64/services.odex (com.android.server.wm.InputMonitor.populateInputWindowHandle+2364, pc 8f2c3c)
    /system/framework/oat/arm64/services.odex (com.android.server.wm.InputMonitor$UpdateInputForAllWindowsConsumer.accept+5912, pc 8efdc8)
    /system/framework/oat/arm64/services.odex (com.android.server.wm.InputMonitor$UpdateInputForAllWindowsConsumer.accept+92, pc 8f03bc)
    /system/framework/oat/arm64/services.odex (com.android.server.wm.WindowContainer$ForAllWindowsConsumerWrapper.apply+120, pc 91a4d8)
    /system/framework/oat/arm64/services.odex (com.android.server.wm.WindowState.forAllWindows+284, pc 96b2fc)
    /system/framework/oat/arm64/services.odex (com.android.server.wm.WindowContainer.forAllWindows+504, pc 9465e8)
    /system/framework/oat/arm64/services.odex (com.android.server.wm.WindowContainer.forAllWindows+504, pc 9465e8)
    /system/framework/oat/arm64/services.odex (com.android.server.wm.WindowContainer.forAllWindows+504, pc 9465e8)
    /system/framework/oat/arm64/services.odex (com.android.server.wm.InputMonitor$UpdateInputForAllWindowsConsumer.updateInputWindows+2480, pc 8f0db0)
    /system/framework/oat/arm64/services.odex (com.android.server.wm.InputMonitor$UpdateInputWindows.run+584, pc 8f18f8)
    /system/framework/arm64/boot-framework.oat (android.os.Handler.dispatchMessage+76, pc 55a90c)
    /system/framework/arm64/boot-framework.oat (android.os.Looper.loopOnce+1036, pc 55db7c)
    /system/framework/arm64/boot-framework.oat (android.os.Looper.loop+552, pc 55d6e8)
    /system/framework/arm64/boot-framework.oat (android.os.HandlerThread.run+572, pc 55c9ec)
    /system/framework/oat/arm64/services.odex (com.android.server.ServiceThread.run+88, pc 460ae8)
    /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612, pc 2109a4)
    /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+172, pc 253b3c)
    /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1416, pc 69abc8)
    /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204, pc cfa2c)
    /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64, pc 64770)
```

```

**Comment by fuckingridiculous** [comment]
```
```
type: crash
osVersion: google/oriole/oriole:14/UQ1A.231205.015/2023123100:user/release-keys
uid: 1000 (u:r:system_server:s0)
cmdline: system_server
processUptime: 260s

signal: 11 (SIGSEGV), code 1 (SEGV_MAPERR), faultAddr dff1e49bf060
threadName: InputProcessor

backtrace:
    <unknown> (pc dff1e44cfd78)
    /system/lib64/libc++.so (operator new(unsigned long)+24, pc 51028)
    /system/lib64/libc++.so (operator new(unsigned long)+24, pc 51028)
    /system/lib64/libbinder_ndk.so (AStatus_fromStatus+40, pc 13ff8)
    /system/lib64/android.hardware.input.processor-V1-ndk.so (aidl::android::hardware::input::processor::BpInputProcessor::classify(aidl::android::hardware::input::common::MotionEvent const&, aidl::android::hardware::input::common::Classification*)+208, pc 4730)
    /system/lib64/libinputflinger.so (android::MotionClassifier::processEvents()+268, pc 8921c)
    /system/lib64/libinputflinger.so (void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (android::MotionClassifier::*)(), android::MotionClassifier*> >(void*)+60, pc 8f4dc)
    /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204, pc cfa2c)
    /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64, pc 64770)
```

```

**Comment by fuckingridiculous** [comment]
```
```
type: crash
osVersion: google/oriole/oriole:14/UQ1A.231205.015/2023123100:user/release-keys
uid: 1000 (u:r:system_server:s0)
cmdline: system_server
processUptime: 12970s

signal: 11 (SIGSEGV), code 2 (SEGV_ACCERR), faultAddr d1fff441ab70
threadName: android.anim

backtrace:
    <anonymous:d1ffea55a000> (pc 9ec0b70)
    /system/framework/oat/arm64/services.odex (com.android.server.wm.WindowContainer.getActivity+468, pc 946b64)
    /system/framework/oat/arm64/services.odex (com.android.server.wm.DisplayContent.processTaskForTouchExcludeRegion+160, pc 9bb500)
    /system/framework/oat/arm64/services.odex (com.android.server.wm.DisplayContent$$ExternalSyntheticLambda39.accept+160, pc 8e21c0)
    /system/framework/oat/arm64/services.odex (com.android.server.wm.Task.forAllTasks+80, pc 9a1510)
    /system/framework/oat/arm64/services.odex (com.android.server.wm.WindowContainer.forAllTasks+412, pc 9460cc)
    /system/framework/oat/arm64/services.odex (com.android.server.wm.WindowContainer.forAllTasks+412, pc 9460cc)
    /system/framework/oat/arm64/services.odex (com.android.server.wm.WindowContainer.forAllTasks+412, pc 9460cc)
    /system/framework/oat/arm64/services.odex (com.android.server.wm.WindowContainer.forAllTasks+412, pc 9460cc)
    /system/framework/oat/arm64/services.odex (com.android.server.wm.WindowContainer.forAllTasks+412, pc 9460cc)
    /system/framework/oat/arm64/services.odex (com.android.server.wm.WindowContainer.forAllTasks+412, pc 9460cc)
    /system/framework/oat/arm64/services.odex (com.android.server.wm.DisplayContent.updateTouchExcludeRegion+572, pc 9bfa7c)
    /system/framework/oat/arm64/services.odex (com.android.server.wm.RootWindowContainer.performSurfacePlacementNoTrace+5824, pc 954790)
    /system/framework/oat/arm64/services.odex (com.android.server.wm.RootWindowContainer.performSurfacePlacement+140, pc 95303c)
    /system/framework/oat/arm64/services.odex (com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop+1164, pc 920a1c)
    /system/framework/oat/arm64/services.odex (com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement+84, pc 9204e4)
    /system/framework/oat/arm64/services.odex (com.android.server.wm.WindowSurfacePlacer$Traverser.run+368, pc 9201b0)
    /system/framework/arm64/boot-framework.oat (android.os.Handler.dispatchMessage+76, pc 55a90c)
    /system/framework/arm64/boot-framework.oat (android.os.Looper.loopOnce+1036, pc 55db7c)
    /system/framework/arm64/boot-framework.oat (android.os.Looper.loop+552, pc 55d6e8)
    /system/framework/arm64/boot-framework.oat (android.os.HandlerThread.run+572, pc 55c9ec)
    /system/framework/oat/arm64/services.odex (com.android.server.ServiceThread.run+88, pc 460ae8)
    /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612, pc 2109a4)
    /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+172, pc 253b3c)
    /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1416, pc 69abc8)
    /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204, pc cfa2c)
    /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64, pc 64770)
```

```

**Comment by fuckingridiculous** [comment]
```
```
type: crash
osVersion: google/oriole/oriole:14/UQ1A.240105.002/2024010400:user/release-keys
uid: 1000 (u:r:system_server:s0)
cmdline: system_server
processUptime: 20108s

signal: 11 (SIGSEGV), code 2 (SEGV_ACCERR), faultAddr ce827344d458
threadName: android.anim

backtrace:
    [anon:libwebview reservation] (pc 1c656458)
    /system/framework/oat/arm64/services.odex (com.android.server.wm.WindowContainer.forAllWindows+444, pc 94444c)
    /system/framework/oat/arm64/services.odex (com.android.server.wm.WindowContainer.forAllWindows+504, pc 944488)
    /system/framework/oat/arm64/services.odex (com.android.server.wm.WindowContainer.forAllWindows+504, pc 944488)
    /system/framework/oat/arm64/services.odex (com.android.server.wm.WindowContainer.forAllWindows+504, pc 944488)
    /system/framework/oat/arm64/services.odex (com.android.server.wm.DisplayContent.updateKeepClearAreas+456, pc 9bcbd8)
    /system/framework/oat/arm64/services.odex (com.android.server.wm.RootWindowContainer.performSurfacePlacementNoTrace+5804, pc 95261c)
    /system/framework/oat/arm64/services.odex (com.android.server.wm.RootWindowContainer.performSurfacePlacement+140, pc 950edc)
    /system/framework/oat/arm64/services.odex (com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop+1164, pc 91e8bc)
    /system/framework/oat/arm64/services.odex (com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement+84, pc 91e384)
    /system/framework/oat/arm64/services.odex (com.android.server.wm.WindowSurfacePlacer$Traverser.run+368, pc 91e050)
    /system/framework/arm64/boot-framework.oat (android.os.Handler.dispatchMessage+76, pc 55ba1c)
    /system/framework/arm64/boot-framework.oat (android.os.Looper.loopOnce+1036, pc 55ec8c)
    /system/framework/arm64/boot-framework.oat (android.os.Looper.loop+552, pc 55e7f8)
    /system/framework/arm64/boot-framework.oat (android.os.HandlerThread.run+572, pc 55dafc)
    /system/framework/oat/arm64/services.odex (com.android.server.ServiceThread.run+88, pc 460498)
    /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612, pc 2109a4)
    /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+172, pc 253b3c)
    /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1416, pc 69abc8)
    /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204, pc cfa2c)
    /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64, pc 64770)
```

```

**Comment by fuckingridiculous** [comment]
```
```
type: crash
osVersion: google/oriole/oriole:14/UQ1A.231205.015/2023123100:user/release-keys
uid: 1000 (u:r:system_server:s0)
cmdline: system_server
processUptime: 18569s

signal: 11 (SIGSEGV), code 2 (SEGV_ACCERR), faultAddr c4dfea46ce3c
threadName: android.anim

backtrace:
    <anonymous:c4dfdae1d000> (pc f64fe3c)
    /system/framework/oat/arm64/services.odex (com.android.server.wm.WindowContainer.getAnimatingContainer+304, pc 946e30)
    /system/framework/oat/arm64/services.odex (com.android.server.wm.WindowContainer.getAnimatingContainer+364, pc 946e6c)
    /system/framework/oat/arm64/services.odex (com.android.server.wm.WindowContainer.getAnimatingContainer+364, pc 946e6c)
    /system/framework/oat/arm64/services.odex (com.android.server.wm.WindowContainer.getAnimatingContainer+364, pc 946e6c)
    /system/framework/oat/arm64/services.odex (com.android.server.wm.WindowContainer.getAnimatingContainer+364, pc 946e6c)
    /system/framework/oat/arm64/services.odex (com.android.server.wm.WindowContainer.isAnimating+36, pc 949364)
    /apex/com.android.art/lib64/libart.so (nterp_helper+4016, pc 20a330)
    /system/framework/services.jar (com.android.server.wm.WindowAnimator.animate+382, pc 11f13a)
    /system/framework/oat/arm64/services.odex (com.android.server.wm.WindowAnimator.lambda$new$1+320, pc 919d10)
    /system/framework/oat/arm64/services.odex (com.android.server.wm.WindowAnimator$$ExternalSyntheticLambda1.doFrame+84, pc 919b64)
    /system/framework/arm64/boot-framework.oat (android.view.Choreographer.doCallbacks+976, pc 6d0cc0)
    /system/framework/arm64/boot-framework.oat (android.view.Choreographer.doFrame+2180, pc 6d1804)
    /system/framework/arm64/boot-framework.oat (android.view.Choreographer$FrameDisplayEventReceiver.run+88, pc 758748)
    /system/framework/arm64/boot-framework.oat (android.os.Handler.dispatchMessage+76, pc 55a90c)
    /system/framework/arm64/boot-framework.oat (android.os.Looper.loopOnce+1036, pc 55db7c)
    /system/framework/arm64/boot-framework.oat (android.os.Looper.loop+552, pc 55d6e8)
    /system/framework/arm64/boot-framework.oat (android.os.HandlerThread.run+572, pc 55c9ec)
    /system/framework/oat/arm64/services.odex (com.android.server.ServiceThread.run+88, pc 460ae8)
    /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612, pc 2109a4)
    /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+172, pc 253b3c)
    /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1416, pc 69abc8)
    /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204, pc cfa2c)
    /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64, pc 64770)
```

```

**Comment by thestinger** [comment]
These logs show that memory corruption is being triggered, but it's not at all clear why. There's something that's happening on your system that's triggering memory corruption.

**Comment by StrangePelaton** [comment]
Thanks. It only happens when the phone is below about 60°F. Not nearly cold enough for battery issues on any of the other pixels I've had. Google refuses to provide any insight and the phone is out of warranty. any thoughts on why a low temperature might cause memory corruption?

**Comment by thestinger** [comment]
I thought it was probably some kind of software issue, but if it's environmental related then it must be a hardware issue, and specifically an SoC issue. It doesn't seem like it would be a memory issue but it could be.

**Comment by StrangePelaton** [comment]
I wonder if reflowing the board would help. If that's even something that would work on a phone I'm not sure. I've done it with graphics cards.

**Comment by David-Prock** [comment]
People water cool chips to get better performance, so does that really make any since

**Comment by StrangePelaton** [comment]
Only makes sense if the problem stems from a cracked solder joint which thermally contracts enough to lose contact below a certain temperature.

**Comment by thestinger** [comment]
Appears to be a hardware issue, nothing else makes sense when it's based on temperature.

**Comment by StrangePelaton** [comment]
Same thought. My only respite will be to figure out the root cause and if it's repairable. I like the phone otherwise
