### ISSUE TITLE
screen flickering

### ISSUE THREAD

**Issue by browngnome** [GrapheneOS/os-issue-tracker#3099]
I just updated my pixel 8 pro to 2024011300 a few hours ago. The phone has become unusable. The screen is flickering constantly. It seems to display whatever the previous screen was instead of what is currently active. Attached is a crash log when I was navigating the settings menu. 
[Error in Settings 1f566fb96326.txt](https://github.com/GrapheneOS/os-issue-tracker/files/13942503/Error.in.Settings.1f566fb96326.txt)
I will try and upload a video when I can get one under 10MB.

**Comment by browngnome** [comment]
I just rebooted my device and everything seems to be fine... I'm closing the issue since it is no longer happening for now.

**Comment by thestinger** [comment]
It sounds like a hardware issue.
