### ISSUE TITLE
Received call audio not routed to BT

### ISSUE THREAD

**Issue by june012006** [GrapheneOS/os-issue-tracker#3122]
Every time I get a call with my BT headset connected, the dialer shows the headset as the selected output, but the call is through handset audio.   The selector will show when the button is pressed, but the selection is irrelevant, it is still handset only, can't even use speakerphone.   Outgoing calls work without issue.
Pixel 8
Build UQ1A.240105.004.2024011600
BT devices Shokz and Toyota Corolla LE(2022) head unit.
T-Mobile
Alternate user profile

**Comment by thestinger** [comment]
This is an Android issue with secondary users. See https://issuetracker.google.com/issues/232112722. We plan to leave it tracked via the upstream issue.
