### ISSUE TITLE
[Feature request] Hide / change own phone number (to random numbers)

### ISSUE THREAD

**Issue by ElsAr4e** [GrapheneOS/os-issue-tracker#3126]
Every phone allows you to hide your caller ID.

But there might be cases when this does not work.

For example if you make an emergency call your phone number will be shown anyway since for example CLIRO (Calling Line Identification Restriction Override) is used (https://community.e.foundation/t/how-to-disable-caller-id/49948/21)

Could you make it possible if you use GrapheneOS - even if the other person you are calling makes use of CLIRO - still won't view any number? (Useful especially if ad companies (illegally) use CLIRO)

Or if that's technically impossible can you implement a feature like a proxy phone number (https://www.tardigrada.io/blog/proxy-phone-numbers-how-they-work/) (opt-in setting (within the dialer / Android System Settings)) so that your real number (1234567) will never be shown but another random number (3456789)?

**Comment by thestinger** [comment]
You can use VOIP.

**Comment by thestinger** [comment]
> Or if that's technically impossible

Your carrier knows your number and can share it, so it's not within the control of the phone.

**Comment by ElsAr4e** [comment]
> You can use VOIP.

Many / Some VOIP providers disable emergency calls.

So you would need a proxy phone number?

**Comment by thestinger** [comment]
If you need to call emergency services, why wouldn't you call them with a regular number? I assume you want them to send help to your location. Not clear what you want or why, but it's sounding sketchy now.

**Comment by ElsAr4e** [comment]
I don't want to hide my number from emergency services but from (ad) companies that might (illegally) have the same technology.

Therefore this option would be great to have if it's technically possible.
