### ISSUE TITLE
Kernel crash P8p

### ISSUE THREAD

**Issue by dill-shower** [GrapheneOS/os-issue-tracker#3134]
It can be fixed? 

[Kernel.crash.f2397cf418d5.txt](https://github.com/GrapheneOS/os-issue-tracker/files/14035536/Kernel.crash.f2397cf418d5.txt)

**Comment by thestinger** [comment]
This crash report is from a Pixel 7a, not a Pixel 8 Pro. It's a known upstream issue.

**Comment by thestinger** [comment]
Also note this may be a hardware or firmware issue.

**Comment by dill-shower** [comment]
> This crash report is from a Pixel 7a, not a Pixel 8 Pro. It's a known upstream issue.

I'm sorry, not this file. Re-uploaded, can you please check?

**Comment by thestinger** [comment]
It's a potentially related known Pixel 8 issue.

**Comment by thestinger** [comment]
Either way, they're both known upstream bugs and we can't do much about them. May be firmware bugs. Both appear to be issues with the CPU waking up from deep sleep.
