### ISSUE TITLE
Initial wifi connection setup failing.

### ISSUE THREAD

**Issue by Cicango** [GrapheneOS/os-issue-tracker#3138]
Hi,

I have a pixel 6 with the version "14 (UQ1A.240105.002.2024011600)"

I tried to comnect to 2 wifi connections and the connection is either not succesful or or the wifi Name can't be stored?

1. Wifi:

Security: Wpa/Wpa 2 Enterprise
Authentication: Protected Eap (PEAP)
PEAP Version: Version 0
Inner Authentication: MSCHAPv2

Username and password have been correctly provided. The phone just reports "authentication problem"

2. Wifi:

Security: Wep

Don't happens every time but too frequently to be annoying

Correct password have been provided.

![IMG_20240126_102439.jpg](https://github.com/GrapheneOS/os-issue-tracker/assets/50528556/89c1b98b-74e9-4b58-b4df-376f2ca52619)

**Comment by thestinger** [comment]
Sounds like an invalid certificate. It likely also happens on the stock OS.
