### ISSUE TITLE
Block sandboxed Playstore from locking itself to open "play.google.com" links

### ISSUE THREAD

**Issue by firefoxlover** [GrapheneOS/os-issue-tracker#3139]
This has to be something set in AOSP.

If you have Aurorastore and sandboxed Play store installed, Play store locks itself to open said link. The toggle is not possible to disable, so links will always open in Playstore and not in Aurorastore.

Latest GrapheneOS on P6a

I have not tried this with Aurorastore set to use that link first, I will see if google play will even force change that.

**Comment by thestinger** [comment]
This is how link associations work in Android with verified links.

**Comment by firefoxlover** [comment]
Okay I checked and it seems if you set Aurorastore to open these links first, Google Play doesnt override it.

It also didnt keep the association when disabling the playstore.

Afaik these link associations will prioritize Apps from Google Play and Google Play itself.

I guess this is a minor issue then.

**Comment by firefoxlover** [comment]
I dont think upstream will ever fix this. 😅 it is a minor issue probably, documenting the possibility to disable Google Play store to revert the block would be appreciated.
