### ISSUE TITLE
Can't enable APTX on Pixel 3a

### ISSUE THREAD

**Issue by amija004** [GrapheneOS/os-issue-tracker#314]
I am using the Audio-Technica ATH-M50xBT headphones, which use bluetooth 5.0 and support APTX, AAC, and SBC.

In bluetooth device settings, HD Audio is listed as using AAC, where it was listed as APTX in the stock OS.

[Image of Device Settings](https://user-images.githubusercontent.com/35469848/93292106-bd46e200-f7b2-11ea-8a3d-20f168cc9ae8.png)

In developer options, setting APTX as the codec does nothing, while switching between SBC and AAC makes a notable difference in audio quality. If APTX is selected, the choice will not be remembered, and the default will be selected upon exit and re-entry to the menu.

[Image of Developer Settings](https://user-images.githubusercontent.com/35469848/93292353-6261ba80-f7b3-11ea-9c70-a9a940927e8b.png)

**Comment by thestinger** [comment]
Developer options are not supported features for anyone but developers to test it. Support for AptX is a low priority wishlist feature as long as nothing is broken by default.

**Comment by thestinger** [comment]
@amija004 Please try this again on the latest release. It might be fixed.

**Comment by amija004** [comment]
@thestinger
[Image of Changes](https://user-images.githubusercontent.com/35469848/94378726-b8125d00-00f9-11eb-88c4-79c44a247f1e.png)

The HD option listed in bluetooth settings is still AAC. The photo above is from developer settings just to show that system now seems to recognize that AptX is not supported by the device or the headset, which I assume means that the codec is not present in the system.

Thank you for following up with this, and even more for all the work that you do. The wealth of documentation and general information that you and the team have put on the website is exceptional.

**Comment by thestinger** [comment]
Can you check if this has been addressed yet?

**Comment by amija004** [comment]
It has not been addressed, I can still only choose between AAC and SBC. 

I attempted to find the location of the issue, but I have no android development experience and am unfamiliar with the file system.

What I did find was that in the bluetooth a2dp directory, 1. A2dpCodecConfigTest.java and 2. A2dpCodecConfig.java mentioned all the possible codecs, including AptX

1. [https://github.com/GrapheneOS/platform_packages_apps_Bluetooth/blob/68cb7647c7912782ed8e22ae27c92dfaf6e26837/tests/unit/src/com/android/bluetooth/a2dp/A2dpCodecConfigTest.java](https://github.com/GrapheneOS/platform_packages_apps_Bluetooth/blob/68cb7647c7912782ed8e22ae27c92dfaf6e26837/tests/unit/src/com/android/bluetooth/a2dp/A2dpCodecConfigTest.java)

2. [https://github.com/GrapheneOS/platform_packages_apps_Bluetooth/blob/68cb7647c7912782ed8e22ae27c92dfaf6e26837/src/com/android/bluetooth/a2dp/A2dpCodecConfig.java](https://github.com/GrapheneOS/platform_packages_apps_Bluetooth/blob/68cb7647c7912782ed8e22ae27c92dfaf6e26837/src/com/android/bluetooth/a2dp/A2dpCodecConfig.java)

but 3. A2dpStateMachineTest.java (lines 60-61, 82-95) and 4. A2dpServiceTest.java(lines 1046 - 1061) only mentioned sbc and aac, which are the only options available to me on my device.

3. [https://github.com/GrapheneOS/platform_packages_apps_Bluetooth/blob/68cb7647c7912782ed8e22ae27c92dfaf6e26837/tests/unit/src/com/android/bluetooth/a2dp/A2dpStateMachineTest.java](https://github.com/GrapheneOS/platform_packages_apps_Bluetooth/blob/68cb7647c7912782ed8e22ae27c92dfaf6e26837/tests/unit/src/com/android/bluetooth/a2dp/A2dpStateMachineTest.java)

4. [https://github.com/GrapheneOS/platform_packages_apps_Bluetooth/blob/68cb7647c7912782ed8e22ae27c92dfaf6e26837/tests/unit/src/com/android/bluetooth/a2dp/A2dpServiceTest.java](https://github.com/GrapheneOS/platform_packages_apps_Bluetooth/blob/68cb7647c7912782ed8e22ae27c92dfaf6e26837/tests/unit/src/com/android/bluetooth/a2dp/A2dpServiceTest.java)

I was unable to find anything more conclusive. Do these seem like potential leads?

**Comment by thestinger** [comment]
> Do these seem like potential leads?

No, not really. The issue is probably resource configuration where overlays used by the stock OS are missing.

**Comment by thestinger** [comment]
We're not going to be implementing this for the Pixel 3a at this point.

**Comment by Saroumane** [comment]
> We're not going to be implementing this for the Pixel 3a at this point.

Hello,
Does it mean the problem does not exist on newer models of Pixel ?
Or it does exist on these models, and it is planned to fix it ?

**Comment by flawedworld** [comment]
It works fine

**Comment by Saroumane** [comment]
Thanks for the quick answer.
May I ask which Pixel do you use, if it is not intrusive ?
