### ISSUE TITLE
Accessibility "disable Animations" stopped working

### ISSUE THREAD

**Issue by firefoxlover** [GrapheneOS/os-issue-tracker#3140]
That setting removes the need for developer options.

Today after a reboot it randomly stopped working. Disabling and enabling didnt do anything, animations still showed up.

Probably upstream?

UQ1A.240105.002.2024011600

P6a

**Comment by thestinger** [comment]
There was no change to this. Additionally, not all animations are covered by it, but most of the SystemUI and launcher ones are.
