### ISSUE TITLE
Add "default USB connection mode" to Security Settings

### ISSUE THREAD

**Issue by firefoxlover** [GrapheneOS/os-issue-tracker#3141]
In the developer options you can change this, but to remove that need it would be good to put that setting to the security section too, and disable all connections by default.

This is not identical with "USB peripherals" and a user reported their Windows PC would show the MTP connected device even when locked. 

https://discuss.grapheneos.org/d/10540-usb-peripherals-setting-unexpected-behavior

**Comment by thestinger** [comment]
This is not correct.

**Comment by firefoxlover** [comment]
What is not correct?

**Comment by MichaelDevon** [comment]
> In the developer options you can change this, but to remove that need it would be good to put that setting to the security section too, and disable all connections by default.
> 
> This is not identical with "USB peripherals" and a user reported their Windows PC would show the MTP connected device even when locked.
> 
> https://discuss.grapheneos.org/d/10540-usb-peripherals-setting-unexpected-behavior
> 
> To compensate the more complicated UX I have a suggestion. You can place a settings widget on the home screen, directing to the "Devices" page. This allows to directly set the USB mode. I think adding this to the launcher homescreen by default would be really good.

If you change USB Default Config in Developer options, and then disable developer options, it will stay on the one you have selected. 
For example if i want my device to always be in File Transfer mode on any PC connection by default, then i can select it and then diable dev mode. The same way you can set nothing as the action to being plugged in, but thats the default behaivour anyways.
