### ISSUE TITLE
Android Auto voice commands fail unless Android Auto app is active

### ISSUE THREAD

**Issue by slugwerks** [GrapheneOS/os-issue-tracker#3165]
I notice that Android Auto can't access the microphone (voice commands fail) unless the Android Auto app is running in the foreground on my phone. Everything else works no matter what, but not voice commands.

Before I connect my phone to the car (via wired or wireless), I get a notification that "android auto is available." If I tap that while it is displayed, voice commands work until the AA process is stopped or the phone is restarted even if the app is not in the foreground or the phone is locked. It can be frustrating because this notification is not shown while the phone is connected (only 'connected to your car' which does not perform the same function). Furthermore, using wireless mode, I only have a short window while it connects to unlock the phone and tap "android auto is available" to enable voice commands. This is not the behavior of AA on the stock OS. 

What happens when tapping the "Android Auto is available" notification? It seems some child process is launched that allows microphone access.

Info:
Pixel 6a, latest stable release, all dependencies and required permissions enabled.

**Comment by felmey** [comment]
This is happening with my phone (Pixel 7 Pro) as well.  It started a week or two ago.  I also noticed the new "Android Auto is available" notification.  I'll try clicking on it next time and see if it works at least temporarily.

**Comment by felmey** [comment]
I checked tonight and am now getting the "Android Auto is connected" notification on my phone, however voice commands fail still.

**Comment by muhomorr** [comment]
This issue is resolved by the [2024112700](https://grapheneos.org/releases#2024112700) release.
