### ISSUE TITLE
grapheneos android auto cabled works well but cannot get wireless to work

### ISSUE THREAD

**Issue by travelyoga** [GrapheneOS/os-issue-tracker#3176]
I love the new release of the OS with android auto support with Waze.  To do this I had to connect by a USB cable. I was not able to get android auto to work across bluetooth. How do I do this.

**Comment by travelyoga** [comment]
yes, I have all the android auto settings permissions set to YES (ON) - to the right
also I have not been able to get the voice microphone option from the car panel to work.

**Comment by travelyoga** [comment]
after a bunch of button pushing. got it to work over bluetooth.

**Comment by jeffarobertson** [comment]
@travelyoga do you recall what buttons you pushed to get this working? I'm having the same problem. Thanks.

**Comment by travelyoga** [comment]
I have been using cable only since over bluetooth, only my music works.
Android auto does not work over bluetooth this week.
