### ISSUE TITLE
Share dialog uses UUIDs (?) and breaks file extensions

### ISSUE THREAD

**Issue by firefoxlover** [GrapheneOS/os-issue-tracker#3212]
Since quite some time I have this issue

reproduce:
- share an image from the work profile to the normal one
- share a pdf from the system file manager

When sharing from the filemanager, the filename changes to `msf:UUID[no file extension]`.

This breaks PDFs, zip archives etc, and also removes the name.
The file itself stays intact, for example renaming such a zip archive back makes it unzippable.

When I share a file from Fossify Filemanager, it just uses `UUID` without the `msf:` before.

Using latest GrapheneOS on a bluejay

**Comment by empratyush** [comment]
How did you create the work profile? Have you tried any alternative apps? 
The share functionality on Fossify File Manager might be broken. I recommend trying the built in "Document UI" app instead.

**Comment by firefoxlover** [comment]
> When sharing from the filemanager

This is the native AOSP documentsUI. I specifically mentioned Fossify as that also has a bug but a different one.

- documentsUI: `msf:UUID`
- Material Files: works normally
- Fossify filemanager: `UUID`

This has nothing to do with Shelter, it is just a scenario where I noticed that.

**Comment by firefoxlover** [comment]
I can still reproduce this. 

I share a .mp3 file from my music player to the share dialog, instead it shows as a series of numbers

![Error-share-dialog](https://github.com/GrapheneOS/os-issue-tracker/assets/78762110/f051c065-747c-4067-8bde-e952ae3f6840)

**Comment by firefoxlover** [comment]
This seems to have been fixed with one of the last updates!
