### ISSUE TITLE
Unable to read Mifare Classic 1K tags

### ISSUE THREAD

**Issue by Holbormon** [GrapheneOS/os-issue-tracker#3253]
Consider the following setup:

Device A: Google Pixel 8 running the latest GrapheneOS stable build (UQ1A.240205.004.2024020500). 
Device B: Oneplus 6T running crDroid (Android 11). 

Both devices have [MifareClassicTool](https://github.com/ikarus23/MifareClassicTool) installed and use the **same key file** to decrypt & read the **same physical NFC tag** (Mifare Classic 1K). 
This results in the tag being read just fine by device B, but device A outputting a "No valid key found" toast.

However, note that device A is still able to decrypt and read some other tags, such as a Mifare Classic 4K (NXP) for instance.

**Comment by flawedworld** [comment]
This needs to be tested on a stock OS Pixel, it's unlikely that this is anything to do with GrapheneOS.

**Comment by Holbormon** [comment]
I pretty much bought the Pixel 8 for GOS, so I probably only ever booted stock once and didn't play at all with it.
Upon closer inspection it seems that people over at [MifareClassicTool](https://github.com/ikarus23/MifareClassicTool/issues/441) also have the issue on the Pixel 8 in general, as you correctly surmised. Apologies for not noticing before posting here, I've been having the issue for so long now that when I last checked nobody had come forward over there. I also thought it would be pretty odd for stock being unable to do something so basic, so jumped the gun with GOS here. Thanks for your time.
