### ISSUE TITLE
App Notification Microphone Attack

### ISSUE THREAD

**Issue by QuantumQuill** [GrapheneOS/os-issue-tracker#3268]
Some german journalists found out, that apps can activate your microphone without your knowledge. ([Source](https://www.youtube.com/watch?v=rX2tK-qSVpk))
Basically the microphone can be activated on android when the app is open in the front and the user allowed the microphone.
But there is an attack where the app creates a notification without activating the screen. In this way it can activate the microphone and spy on you for hours. 
It would be great to counter fight this attack with a rule which actually does not allow microphone access - even the user allowed it - when the request comes in a moment the App is not in front, the phone is locked, or the screen is off.

**Comment by empratyush** [comment]
> But there is an attack where the app creates a notification without activating the screen. In this way it can activate the microphone and spy on you for hours.

I think you are talking about foreground service. A third-party app can not start a foreground unless it is in the foreground with some exemptions you can read more about it [here](https://developer.android.com/develop/background-work/services/foreground-services) and [here](https://developer.android.com/develop/background-work/services/fg-service-types#microphone). 

> It would be great to counter fight this attack with a rule which actually does not allow microphone access - even the user allowed it - when the request comes in a moment the App is not in front, the phone is locked, or the screen is off.

You can already protect yourself from this, (a) by not granting the permission in the first place (b) disabling the microphone globally when not in use (c) or by setting 'battery optimization restriction' to 'restricted' for individual apps.
