### ISSUE TITLE
eSIM not turning on anymore (gets deactivated immediatly when switched on)

### ISSUE THREAD

**Issue by benstockhecke** [GrapheneOS/os-issue-tracker#3355]
My eSIM no longer works with my phone (Pixel 7Pro) and the latest version of GrapheneOS (build 2024031400).

It is recognised by the system (IMEI in SIM Slot2 is recognised), but I can no longer activate the eSIM under:

Settings->Network and Internet->SIMs->SIM->Use SIM. Whenever I click on "Use SIM" and click on "Turn on" when asked "Turn on SIM=", the slider is automatically deactivated again.

I already tried to de- and reactivate DSDS.

Logcat

> type: logcat
> osVersion: google/cheetah/cheetah:14/AP1A.240305.019.A1/2024031400:user/release-keys
> buffers: main,system,crash,events
> level: verbose
> filterRegex: PhoneAccountRegistrar
> 
> --------- beginning of system
> 1710839508.925  1000  1330  2517 I Telecom : PhoneAccountRegistrar: getSimCallManager: SimCallManager for subId 1 queried, returning: null: TSI.gSCM(cas)@AR4
> 1710839572.063  1000  1330  4861 I Telecom : PhoneAccountRegistrar: getSimCallManager: SimCallManager for subId 1 queried, returning: null: TSI.gSCM(cas)@ASo
> 1710839805.567  1000  1330  5207 I Telecom : PhoneAccountRegistrar: getSimCallManager: SimCallManager for subId 1 queried, returning: null: TSI.gSCM(cas)@AUg
> 1710839807.086  1000  1330  2438 I Telecom : PhoneAccountRegistrar: getSimCallManager: SimCallManager for subId 2 queried, returning: null: TSI.gSCM(cas)@AUo
> 1710839807.982  1000  1330  5207 I Telecom : PhoneAccountRegistrar: Modify account: [ComponentInfo{com.android.phone/com.android.services.telephony.TelephonyConnectionService}, E, UserHandle{0}(subAddr: tel: -> tel:*************)]: TSI.rPA(cap)@AUw
> 1710839807.988  1000  1330  5207 I Telecom : PhoneAccountRegistrar: getSimCallManager: SimCallManager for subId -1 queried, returning: null: TSI.rPA(cap)@AUw
> 1710839807.988  1000  1330  5207 I Telecom : PhoneAccountRegistrar: Notifying telephony of voice service override change for 1 SIMs, hasService = false: TSI.rPA(cap)@AUw
> 1710839807.989  1000  1330  5207 I Telecom : PhoneAccountRegistrar: maybeNotifyTelephonyForVoiceServiceState: simTm is null.: TSI.rPA(cap)@AUw
> 1710839808.002  1000  1330  5207 I Telecom : PhoneAccountRegistrar: Modify account: [ComponentInfo{com.android.phone/com.android.services.telephony.TelephonyConnectionService}, E, UserHandle{0}]: TSI.rPA(cap)@AU4
> 1710839808.008  1000  1330  5207 I Telecom : PhoneAccountRegistrar: getSimCallManager: SimCallManager for subId -1 queried, returning: null: TSI.rPA(cap)@AU4
> 1710839808.008  1000  1330  5207 I Telecom : PhoneAccountRegistrar: Notifying telephony of voice service override change for 1 SIMs, hasService = false: TSI.rPA(cap)@AU4
> 1710839808.008  1000  1330  5207 I Telecom : PhoneAccountRegistrar: maybeNotifyTelephonyForVoiceServiceState: simTm is null.: TSI.rPA(cap)@AU4
> 1710839808.318  1000  1330  4788 I Telecom : PhoneAccountRegistrar: New phone account registered: [[ ] PhoneAccount: ComponentInfo{com.android.phone/com.android.services.telephony.TelephonyConnectionService}, 2, UserHandle{0} Capabilities: CallProvider MultiUser PlaceEmerg SimSub  Audio Routes: BESW Schemes: tel voicemail  Extras: Bundle[{android.telecom.extra.SUPPORTS_VIDEO_CALLING_FALLBACK=true, android.telecom.extra.SORT_ORDER=0}] GroupId: ***]: TSI.rPA(cap)@AVA
> 1710839808.339  1000  1330  4788 I Telecom : PhoneAccountRegistrar: getSimCallManager: SimCallManager for subId 2 queried, returning: null: TSI.rPA(cap)@AVA
> 1710839808.339  1000  1330  4788 I Telecom : PhoneAccountRegistrar: Notifying telephony of voice service override change for 1 SIMs, hasService = false: TSI.rPA(cap)@AVA
> 1710839808.593  1000  1330  4761 I Telecom : PhoneAccountRegistrar: Modify account: [ComponentInfo{com.android.phone/com.android.services.telephony.TelephonyConnectionService}, 2, UserHandle{0}]: TSI.rPA(cap)@AV0
> 1710839808.624  1000  1330  4761 I Telecom : PhoneAccountRegistrar: getSimCallManager: SimCallManager for subId 2 queried, returning: null: TSI.rPA(cap)@AV0
> 1710839808.624  1000  1330  4761 I Telecom : PhoneAccountRegistrar: Notifying telephony of voice service override change for 1 SIMs, hasService = false: TSI.rPA(cap)@AV0
> 1710839809.813  1000  1330  1330 I Telecom : PhoneAccountRegistrar: getSimCallManager: SimCallManager for subId 2 queried, returning: null: TSI.gSCMFU(a)@AXE
> 1710839809.827  1000  1330  1330 I Telecom : PhoneAccountRegistrar: getSimCallManager: SimCallManager for subId 2 queried, returning: null: TSI.gSCMFU(a)@AXI
> 1710839809.842  1000  1330  5892 I Telecom : PhoneAccountRegistrar: setUserSelectedOutgoingPhoneAccount: ComponentInfo{com.android.phone/com.android.services.telephony.TelephonyConnectionService}, 2, UserHandle{0}: TSI.sUSOPA@AXM
> 1710839809.843  1000  1330  5892 I Telecom : PhoneAccountRegistrar: setUserSelectedOutgoingPhoneAccount: no change to voice sub: TSI.sUSOPA@AXM
> 1710839814.517  1000  1330  4861 I Telecom : PhoneAccountRegistrar: Modify account: [ComponentInfo{com.android.phone/com.android.services.telephony.TelephonyConnectionService}, 2, UserHandle{0}(addr: tel:************* -> tel:)(subAddr: tel:************* -> tel:)]: TSI.rPA(cap)@AZE
> 1710839814.534  1000  1330  4861 I Telecom : PhoneAccountRegistrar: getSimCallManager: SimCallManager for subId 2 queried, returning: null: TSI.rPA(cap)@AZE
> 1710839814.535  1000  1330  4861 I Telecom : PhoneAccountRegistrar: Notifying telephony of voice service override change for 1 SIMs, hasService = false: TSI.rPA(cap)@AZE
> 1710839815.497  1000  1330  5893 I Telecom : PhoneAccountRegistrar: Modify account: [ComponentInfo{com.android.phone/com.android.services.telephony.TelephonyConnectionService}, 2, UserHandle{0}]: TSI.rPA(cap)@AZQ
> 1710839815.507  1000  1330  5893 I Telecom : PhoneAccountRegistrar: getSimCallManager: SimCallManager for subId 2 queried, returning: null: TSI.rPA(cap)@AZQ
> 1710839815.507  1000  1330  5893 I Telecom : PhoneAccountRegistrar: Notifying telephony of voice service override change for 1 SIMs, hasService = false: TSI.rPA(cap)@AZQ
> 1710839815.850  1000  1330  1330 I Telecom : PhoneAccountRegistrar: getSimCallManager: SimCallManager for subId 2 queried, returning: null: TSI.gSCMFU(a)@AZk
> 1710839815.884  1000  1330  1330 I Telecom : PhoneAccountRegistrar: getSimCallManager: SimCallManager for subId 2 queried, returning: null: TSI.gSCMFU(a)@AZo
> 1710839817.642  1000  1330  5445 I Telecom : PhoneAccountRegistrar: Modify account: [ComponentInfo{com.android.phone/com.android.services.telephony.TelephonyConnectionService}, 2, UserHandle{0}]: TSI.rPA(cap)@AaA
> 1710839817.647  1000  1330  5445 I Telecom : PhoneAccountRegistrar: getSimCallManager: SimCallManager for subId 2 queried, returning: null: TSI.rPA(cap)@AaA
> 1710839817.647  1000  1330  5445 I Telecom : PhoneAccountRegistrar: Notifying telephony of voice service override change for 1 SIMs, hasService = false: TSI.rPA(cap)@AaA
> 1710839817.676  1000  1330  5445 I Telecom : PhoneAccountRegistrar: Modify account: [ComponentInfo{com.android.phone/com.android.services.telephony.TelephonyConnectionService}, 2, UserHandle{0}]: TSI.rPA(cap)@AaI
> 1710839817.689  1000  1330  5445 I Telecom : PhoneAccountRegistrar: getSimCallManager: SimCallManager for subId 2 queried, returning: null: TSI.rPA(cap)@AaI
> 1710839817.689  1000  1330  5445 I Telecom : PhoneAccountRegistrar: Notifying telephony of voice service override change for 1 SIMs, hasService = false: TSI.rPA(cap)@AaI
> 1710839817.878  1000  1330  4861 I Telecom : PhoneAccountRegistrar: Modify account: [ComponentInfo{com.android.phone/com.android.services.telephony.TelephonyConnectionService}, 2, UserHandle{0}]: TSI.rPA(cap)@AaY
> 1710839817.886  1000  1330  4861 I Telecom : PhoneAccountRegistrar: getSimCallManager: SimCallManager for subId 2 queried, returning: null: TSI.rPA(cap)@AaY
> 1710839817.886  1000  1330  4861 I Telecom : PhoneAccountRegistrar: Notifying telephony of voice service override change for 1 SIMs, hasService = false: TSI.rPA(cap)@AaY
> 1710839818.020  1000  1330  4861 I Telecom : PhoneAccountRegistrar: Modify account: [ComponentInfo{com.android.phone/com.android.services.telephony.TelephonyConnectionService}, 2, UserHandle{0}]: TSI.rPA(cap)@AbA
> 1710839818.040  1000  1330  4861 I Telecom : PhoneAccountRegistrar: getSimCallManager: SimCallManager for subId 2 queried, returning: null: TSI.rPA(cap)@AbA
> 1710839818.040  1000  1330  4861 I Telecom : PhoneAccountRegistrar: Notifying telephony of voice service override change for 1 SIMs, hasService = false: TSI.rPA(cap)@AbA
> 1710839822.431  1000  1330  5891 I Telecom : PhoneAccountRegistrar: Modify account: [ComponentInfo{com.android.phone/com.android.services.telephony.TelephonyConnectionService}, 2, UserHandle{0}]: TSI.rPA(cap)@Ab0
> 1710839822.441  1000  1330  5891 I Telecom : PhoneAccountRegistrar: getSimCallManager: SimCallManager for subId 2 queried, returning: null: TSI.rPA(cap)@Ab0
> 1710839822.441  1000  1330  5891 I Telecom : PhoneAccountRegistrar: Notifying telephony of voice service override change for 1 SIMs, hasService = false: TSI.rPA(cap)@Ab0
> 1710839832.710  1000  1330  5892 I Telecom : PhoneAccountRegistrar: Modify account: [ComponentInfo{org.thoughtcrime.securesms/org.thoughtcrime.securesms.service.webrtc.AndroidCallConnectionService}, ***, UserHandle{0}]: TSI.rPA(ots)@AdE
> 1710839845.703  1000  1330  5209 I Telecom : PhoneAccountRegistrar: getSimCallManager: SimCallManager for subId 1 queried, returning: null: TSI.gSCM(cas)@AdI
> 1710839853.128  1000  1330  2572 I Telecom : PhoneAccountRegistrar: Modify account: [ComponentInfo{org.thoughtcrime.securesms/org.thoughtcrime.securesms.service.webrtc.AndroidCallConnectionService}, ***, UserHandle{0}]: TSI.rPA(ots)@AeA
> --------- beginning of main
> 1710840400.069 10094  6591  6591 D LogcatActivity: command: logcat --buffer=main,system,crash,events -d --dividers --format=epoch,printable,uid,descriptive --regex=PhoneAccountRegistrar *:V

**Comment by benstockhecke** [comment]
> Have you enabled the "eSIM support" toggle in Settings > Network & Internet?

Yes

**Comment by benstockhecke** [comment]
Could it be, that the changes in Build 2024011600 (https://grapheneos.org/releases#2024012600) could have caused the same issues like in this ticket? - https://github.com/GrapheneOS/os-issue-tracker/issues/2097 so this could be an upstream problem. I am also using german Telekom as a provider.

**Comment by benstockhecke** [comment]
After I reset Grapheneos to factory settings, the eSIM was recognised again.

**Comment by WinstonHartnett** [comment]
Maybe related: #3191.

**Comment by benstockhecke** [comment]
Update: Installed Stock Android. And after reboot i am facing the same issue. Likely it has to do with my carrier and or google doing things.

**Comment by benstockhecke** [comment]
> You likely just needed to reset cellular settings.

This has done the trick. Thanks!

**Comment by JulianOestreich90** [comment]
i still face the same problem. Tried resetting network settings over the reset menu but that didn't do the job. Or is something else meant by 'cellular setting'?
