### ISSUE TITLE
Feature Request: Bluetooth Low Energy/LC3 Support

### ISSUE THREAD

**Issue by TempUser13** [GrapheneOS/os-issue-tracker#3397]

**Comment by TempUser13** [comment]
User error for BLE not showing up for my earphones

**Comment by JSchimmelpfennig** [comment]
I have the Sony WF-1000XM5 since 2 days. I'm running the latest GrapheneOS version and latest Firmware on the TWS and Bluetooth LE works! It shows it in the Android settings and as well in the Sony Headphones app. Thanks for the great work :)

**Comment by JSchimmelpfennig** [comment]
I just wanted to give this information here so that he OP and other people who might read it know that this works with GrapheneOS. :-)

15/07/2024 14:24:54 Daniel Micay ***@***.***>:
