### ISSUE TITLE
Contact profile images with inverted colors in Dialer

### ISSUE THREAD

**Issue by Pietro395** [GrapheneOS/os-issue-tracker#3410]
Pixel 6a with GrapheneOS build 20240403

If I open the dialer app and search for the first initials of a contact with a photo set it appears with the colors reversed and incorrect.

Closing the app and trying again can recreate the problem.

![Screenshot_20240405-083441_1.png](https://github.com/GrapheneOS/os-issue-tracker/assets/50447537/6f30bcbb-e7cc-42da-b7c1-d1705a1b8e00)

**Comment by Pietro395** [comment]
> I have also been having this issue intermittently, first noticed it about two weeks ago. I thought it might be caused by me importing all my contacts from an iPhone, but I don't know what your situation is.

I use EteSync and I thought that was the problem, but by uploading a new photo to a contact the problem is there

**Comment by Pietro395** [comment]
@thestinger 
I know this is a low prioprity issue, but what do you think?

**Comment by beryl03** [comment]
Pixel 6 on build 2024071200 : failed
Pixel 4 on build 2024070401 : passed (same app version, different minSDK)

**Comment by empratyush** [comment]
unable to reproduce this on latest stable release.

**Comment by hxtmdev** [comment]
> 2024110700

and Pixel 7

**Comment by beryl03** [comment]
Bug not observed on Pixel 6:
Contacts version 1.7.34
OS build 2024110700

**Comment by AtmosphericIgnition** [comment]
I've also run into this issue in the latest version of the messaging app. Other apps (like Fossify) do not seem affected by this.
