### ISSUE TITLE
"File transfer" over USB does not work anymore without "USB debugging"

### ISSUE THREAD

**Issue by Saroumane** [GrapheneOS/os-issue-tracker#3429]
GrapheneOS 2024040900 on Pixel 6a (did the update today)
Host : up-to-date Archlinux

Last time I used "File transfer" over USB was in september, it worked normally.
Today, I can't browse the Pixel 6a from the Linux host (I get an "MTP error") unless I enable "USB debugging" on the Pixel phone.

I got the idea of enabling "USB debugging" thanks to an user that reported the same problem in the forum : https://discuss.grapheneos.org/d/3648-unable-to-transfer-files-to-pc-unless-usb-debugging-is-enabled

**Comment by Saroumane** [comment]
Thanks, it worked.

What I did precisely, if anyone needs it : 
Settings / System / Developer Options  => re-disable "USB debugging" (it prevented my NFC Payment app from working working, anyway)
On the same page : disable "Developer Options"
Re-plug the phone with USB, verify "USB file transfer" is turned on.

**Comment by kos-muc** [comment]
Thanks, I had completely forgotten about that. 

The USB-Debugging is indispensible for MyPhoneExplorer (MPE) with USB. - I cannot get the permissions to work for SMS and Files (e.g. photos). - MPE needs to be always "in front" and that cannot be enabled.

**Comment by kos-muc** [comment]
PS:
I've managed to activate Developer Mode and USB Debuggin. - MPE still will not grant the required permissions.
I don't understand why I can't even provide an "always on top" access to this app even as a Developer. :(
