### ISSUE TITLE
(probably upstream) sharing messages with ChromeOS Phone Hub is crashing.

### ISSUE THREAD

**Issue by noseshimself** [GrapheneOS/os-issue-tracker#3482]
If I try connecting the ChromeOS Phone Hub with the phone Android is asking me what I would like to share with the computer. Upon selecting "Messages" the application is crashing.

I guess the first line of the report says it all:

```
type: crash
osVersion: google/raven/raven:14/AP1A.240405.002/2024042100:user/release-keys
package: com.google.android.gms:241319038
process: com.google.android.gms.ui
processUptime: 36452 + 202 ms
installer: com.android.vending
GmsCompatConfig version: 108

java.lang.SecurityException: Application must hold android.permission.REQUEST_COMPANION_PROFILE_COMPUTER to associate with a device with android.app.role.COMPANION_DEVICE_COMPUTER profile.
```

Could someone have mercy and forward it upstream or point me to something explaining to me whom to notify and how if it is indeed an upstream problem?

(This is not the only com.google.* that is crashing on not owning required permissions and I'm wondering a bit about how sloppy checking is in plain Android that this is working on an unmodified Pixel...)

**Comment by empratyush** [comment]
unsupported use case. gms need 'android.permission.REQUEST_COMPANION_PROFILE_COMPUTER' permission to provide that feature.
