### ISSUE TITLE
Improve Felica support by bypassing whitelisting of devices for Osaifu-Keitai as described in the link below

### ISSUE THREAD

**Issue by AkechiShiro** [GrapheneOS/os-issue-tracker#3501]
https://github.com/kormax/osaifu-keitai-google-pixel

> 
> No known working ROOT-less methods.
> Following list is provided for reference and to give a possible starting point for people who might want to dig further:
> 
>   1. Manipulate com.google.android.pixelnfc:
>     (Failure) System apps are well-protected against manipulation.
>         Uninstall this app:
>         (Failure) It is a system application and thus cannot be uninstalled.
>         Install your own app with same provider URL:
>         (Failure) You cannot install a new application that declares a provider with conflicting URL until you uninstall an old one.
>     2.  Decompile and patch the apk, adding your SKU to whitelist:
>         (Failure) Not possible as Android requires app overwrites/updates to have the same signature.
>     3. Manipulate com.felicanetworks.mfm.main:
>     (Theory) This might be possible to do without root, but I did not attempt to finish it to the end as it proved to be too complex lacking any experience with Android development.
>     Thing is, com.felicanetworks.mfm.main communicates with, com.felicanetworks.mfc (Mobile FeliCa client), com.felicanetworks.mfs (Mobile FeliCa settings), com.google.android.gms.pay.sidecar (Google Play services for payments) which all do mutual signature verification, thus requiring you to patch ALL of those apps for them to work, replacing signatures and fixing API access due to signature changes.
> 
> As rootless solutions have led us to a dead end, we're gonna join the dark side.

**Comment by AkechiShiro** [comment]
Method 1 is probably the easiest I guess

**Comment by flawedworld** [comment]
We don't want to be sued by Sony. Feel free to do it on your own builds.

**Comment by AkechiShiro** [comment]
Ah damn them, we'll see if I can setup a building CI/CD for this then. Thanks for mentioning this I thought Felica NFC was okay to use anywhere in the World, as Japanese people's phone are provided with NFC Felica already working out of the box.

**Comment by flawedworld** [comment]
It will work on all Pixels but as far as we are aware, Google has only paid to licence the feature on Japanese Pixels.

**Comment by AkechiShiro** [comment]
Then maybe every transportation system needs to use NFC Felica so it becomes more mainstream, but this isn't a great solution tho...

**Comment by AkechiShiro** [comment]
Yes but is installing GrapheneOS a good idea compared to using the Pixel stock ROM ? From Google's point of view GrapheneOS could lead to warranty void, so it's probably not a good idea too.

**Comment by AkechiShiro** [comment]
Yes I'm aware the warranty isn't voided by changing the ROM of any pixels phone (but for others manufacturer it is "voided" despite European laws saying that it shouldn't be voided in that case).

I was just making a point, if I have GrapheneOS on my device, it's not to be limited by licensing issues or whatever. Google should've made it a known fact on the description of the phone that Felica would never work with it because they didn't pay the licensing fees.

This information was never told to me or written in black and white text during my purchase as such I'm not happy.

**Comment by AkechiShiro** [comment]
I understand thanks for the very helpful insights @thestinger @flawedworld
