### ISSUE TITLE
Pixel 6a , build 2024050300 rebooting multiple times a day

### ISSUE THREAD

**Issue by hivefi** [GrapheneOS/os-issue-tracker#3503]
My Pixel 6a , build 2024050300 is rebooting itself multiple times a day. 
I believe it started happening after updating to the current built.

**Comment by hivefi** [comment]
Thank you for your feedback. 
No crash report received. "Notify about system process crashes" is activated in security settings. 
It makes sense that it's not likely related to the update. I have removed some apps I have recently installed.

**Comment by hivefi** [comment]
It's not happend since. Yes, it showed the verified boot screen each time.

**Comment by mxsrm** [comment]
I have been having this problem multiple times a day with a Pixel 6a with latest August version and newest september version. It goes back to the Google Bootloader and starts from the ground up. Any ideas?
