### ISSUE TITLE
Minor feature request. Call Forwarding menu

### ISSUE THREAD

**Issue by drnewcomb** [GrapheneOS/os-issue-tracker#3535]
Would the team consider adding a Call Forwarding menu to the dialer (Or elsewhere), and if so, including a DELAY option to the Not Answered delay? Thanks!

**Comment by empratyush** [comment]
Phone app -> 3 dot on top right ->  settings -> calling accounts -> select your sim card -> Call  forwarding.

> and if so, including a DELAY option to the Not Answered delay?

no.
