### ISSUE TITLE
No Wifi-calling audio on Pixel 8a

### ISSUE THREAD

**Issue by Maxduck** [GrapheneOS/os-issue-tracker#3556]
Wifi-calling working on stock. Telstra (Main/biggest Australian telco)

On GOS, wifi-calling, no ringing sound. When connects no audio for receiver or caller.

After a call using mobile network, then connecting to wifi, using wifi-calling can hear ringing but once connects no audio for receiver or caller.

Multiple wifi networks tried and failed.

Selecting either "call over mobile network" or call over Wi-Fi" makes no difference. Both fail.

thanks

**Comment by SveinAu** [comment]
Same on pixel 7a

**Comment by Maxduck** [comment]
> Same on pixel 7a

Ugh. So, never resolved?

This might be a deal breaker for me. Dang.

**Comment by Maxduck** [comment]
I tried another carrier. Works fine on regular call. Same lack of audio on wifi-calling.

Texts work on wifi-calling (both sending and receiving)

**Comment by Maxduck** [comment]
Seems to be resolved with GrapheneOS version 2024061200 (alpha)
