### ISSUE TITLE
Unencrypted file names leaks to DE through log files

### ISSUE THREAD

**Issue by ryrona2** [GrapheneOS/os-issue-tracker#3583]
The log files stored in "/data/misc/logd" contain very precise usage information, including precise timestamps, what action is carried out in what app using what logged in user profile, and full file paths to files opened in apps, including files stored in CE (Credential Encrypted storage class).

Example 1 (playing video file using VLC app installed through F-Droid):

05-29 17:48:38.353907 1010147 32467 32653 D VLC     : [b400d60569350490/7f8d] libvlc input: `file:///storage/emulated/10/Movies/cute_kittens.mp4' successfully opened

Example 2 (playing same video file using built-in Gallery app):

05-29 17:49:18.731828 1010128 28156 28374 D MediaProvider: Open with FUSE. FilePath: /storage/emulated/10/Movies/cute_kittens.mp4. Uid: 1010128. Media Capabilities Uid: 0. ShouldRedact: false. ShouldTranscode: false

According to Google AOSP documentation, the path "/data/misc" is stored in DE (Device Encrypted storage class). This defeats the purpose with file name encryption in CE, since file names leak unencrypted to DE anyway, so an attacker who can break the security of DE can see the full file names for files stored in each user profile, without knowing the user credentials for that user profile.

https://source.android.com/docs/security/features/encryption/file-based

I think you can easily imagine how bad this can be, if the file names are incriminating in some sense.

The issue appears to affect the latest official release of GrapheneOS too (2024052100), not just userdebug builds, as these log entries can be found in Settings -> System -> View logs on the latest official release too. I suppose the log files are stored in the same place in the file system on official releases.

Solutions considered: The log files could be moved to the owner profile CE, but that does still leak file names from other user profiles to the owner profile. It is way better, but still breaks the isolation user profiles are supposed to give. The log files can be disabled in production builds, but that may make debugging of issues users experience harder. The logger daemon may be modified to try to detect file paths and mask them before writing that log entry to the log file, but there is likely other sensitive information and app data leaked too, since the logs are so verbose.

Migration: Even if this issue is fixed in a new update, file paths have already leaked to DE for existing users, and only a factory reset would recover from this is a cryptographically secure way. So I guess this would be worthy to mention in release notes.

Case of point: User credential for the block based encryption layer would prevent this whole class of data leaks.

**Comment by flawedworld** [comment]
@ryrona2 Report this as a security bug to Google.

**Comment by muhomorr** [comment]
logd logs aren't persisted to storage on production builds.

Persistence of these logs is enabled on debuggable builds by the `logd.logpersistd=logcatd` system property override.

logd and logpersist SELinux domains aren't even allowed to write anything to /data/misc/logd on production builds:
https://github.com/GrapheneOS/platform_system_sepolicy/blob/2a69fff9c2bd85156a24ec03c46b2bf79662ff3e/private/logd.te#L8
https://github.com/GrapheneOS/platform_system_sepolicy/blob/2a69fff9c2bd85156a24ec03c46b2bf79662ff3e/private/logpersist.te#L23

See https://github.com/GrapheneOS/platform_system_logging/blob/14/logcat/logcatd.rc and https://github.com/GrapheneOS/platform_system_logging/blob/14/logd/README.property for more info.

**Comment by ryrona2** [comment]
@muhomorr Thank you for your analysis! Indeed, if the logs are not even persisted, and there even are selinux policies that forbid such persisting, then there is no issue.

I double checked the log viewer in the settings app right now, and can confirm that it only shows logs from the current boot cycle. I also opened a adb shell to the device, and if I try to cd into or stat /data/misc/logd I get "No such file or directory", but if I try to cd into or stat "/data/misc/bootstat" or any other directory that should be there, I get "Permission denied", which to me suggests it is plausible that the "/data/misc/logd" directory does not even exist on production builds.

As such I agree with your analysis and will not look into this further. Again, thank you!

It is a bit unfortunate it is so hard to analyze actual production builds. This is least privilege taken a bit too far in my opinion. If only I could have listed the files in directories without getting "Permission denied" it would have been easier, and I would have felt more confident there are in fact no persisted logs.
