### ISSUE TITLE
Failure when building aapt2 for adevtool

### ISSUE THREAD

**Issue by nicedream06** [GrapheneOS/os-issue-tracker#3681]
I'm trying to use adevtool to generate a vendor tree for Pixel 8 (shiba).
Using the guide at https://github.com/GrapheneOS/adevtool/blob/14/docs/usage.md

I have the GrapheneOS source tree downloaded.

I successfully run `yarn install --cwd vendor/adevtool
`

The next step says to run `source script/envsetup.sh
`, but that file was merged into build/envsetup.sh in this commit https://github.com/GrapheneOS/script/commit/8a949a84126389684be255543b4ec4d47262cb26
So the docs seem to be a bit outdated.

No issue, I source the build/envsetup.sh file instead. No issue there.

Then when I run `m aapt2`, I get the following error:

> FAILED: out/soong/build.aosp_shiba.ninja
cd "$(dirname "out/host/linux-x86/bin/soong_build")" && BUILDER="$PWD/$(basename "out/host/linux-x86/bin/soong_build")" && cd / && env -i  "$BUILDER"     --top "$TOP"     --soong_out "out/soong"     --out "out"     --soong_variables out/soong/soong.aosp_shiba.variables -o out/soong/build.aosp_shiba.ninja --globListDir aosp_shiba --globFile out/soong/globs-aosp_shiba.ninja -l out/.module_paths/Android.bp.list --available_env out/soong/soong.environment.available --used_env out/soong/soong.environment.used.aosp_shiba.build Android.bp
error: external/vixl/Android.bp:109:1: unrecognized module type "art_cc_defaults"
error: external/vixl/Android.bp:122:1: unrecognized module type "art_cc_defaults"
error: external/vixl/Android.bp:179:1: unrecognized module type "art_cc_library"
error: external/vixl/Android.bp:203:1: unrecognized module type "art_cc_library"
fatal errors encountered
14:40:42 soong bootstrap failed with: exit status 1

Any guidance on what to do next? Thanks.

**Comment by flawedworld** [comment]
Follow https://grapheneos.org/build, if you still get issues, resync your tree
