### ISSUE TITLE
screenshot service has caching issues when switching back and forth between profiles while taking screenshots

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/os-issue-tracker#370]
Take screenshots in a profile, switch to another, take screenshots there, switch back, take more screenshots, etc.

Sometimes, screenshots are sent to the profile that was previously taking them since the service is still actively tied to that one.

**Comment by count-null** [comment]
could be related to #330

**Comment by thestinger** [comment]
It's not related. Gallery app issues are caused by it being a sample app that's not maintained. Not the fault of the OS.

**Comment by thestinger** [comment]
I reported this upstream and they closed it as a duplicate, so they were already aware of the problem. Hopefully, a fix will be released soon.

**Comment by mrxx0** [comment]
Not fixed on 2020.12.08.08 on Pixel 4a.

**Comment by thestinger** [comment]
Can someone do some testing to see if this is still reproducible as of the June 2021 update (Quarterly Platform Release 3)?

**Comment by snprmnky** [comment]
Tested on RQ3A.210605.005.2021.06.09.13, and the issue does not occur thus far.
