### ISSUE TITLE
Overview / Recent Apps button stops working

### ISSUE THREAD

**Issue by johnykes** [GrapheneOS/os-issue-tracker#3880]
It's been 9+ months since I got my GrapheneOS on pixel 7a.

Since the first days I have this bug that I think it's the only thing that annoys me: the Overview button (from the nav buttons) stops working randomly, a lot of times! It recovers only after a restart. I restart my phone few times / week just for that.

PS: I have all the updates.

**Comment by johnykes** [comment]
> With the default launcher?

Microsoft Launcher. Could this be the cause? 🤔 Never thought about it.

**Comment by Zwackelmann84** [comment]
Same here. I am using Nova Launcher.

**Comment by johnykes** [comment]
I don't encounter this problem anymore since ~2 weeks ago or something :)
Not sure what have changed, but thank you!
