### ISSUE TITLE
add immediate call rejection for unsolicited phone calls

### ISSUE THREAD

**Issue by renlord** [GrapheneOS/os-issue-tracker#391]
the current android phone app does not have a feature to reject unsolicited phone call at a time when there's proliferation of unwanted scam/spam callers.

complaining to state authorities (i.e. the ACMA in Australia) is hopeless, the only way to maintain one's sanity is to outright reject the unsolicited phone calls and redirect genuine callers to voicemail instead.

**Comment by 2br-2b** [comment]
If you open Phone, then in the top right click the three dots and choose settings, then blocked numbers, you can choose to block calls from unidentified callers.

I believe there is also an option that blocks calls and texts, but I don't remember where that is found.

Is this what you were looking for?

**Comment by renlord** [comment]
No, I want to be able to outright reject calls automatically, unless it matches phone numbers found in my contact list.

**Comment by thestinger** [comment]
Doesn't blocking calls from unidentified numbers do that?

**Comment by thestinger** [comment]
Nevermind, it doesn't do that.

**Comment by 2br-2b** [comment]
What does this toggle not do, then, that you want it to do? It seems to me that the switch already provides the functionality you want.

Does blocking unidentified callers then not block callers who aren't in your contacts?

**Comment by renlord** [comment]
> What does this toggle not do, then, that you want it to do? It seems to me that the switch already provides the functionality you want.
> 
> Does blocking unidentified callers then not block callers who aren't in your contacts?

Have you even tried the toggle?
I have the toggle on, it only blocks unknown caller IDs, it doesn't block callers who aren't in my contact list.

A scam caller can still just phish a random phone number and get through.

**Comment by 2br-2b** [comment]
I understand now. I'm sure I had seen an option for that, but now I can't find it.

I also can't find any FOSS apps providing this functionality. Yet Another Call Blocker can block some spam numbers, but doesn't seem to be able to block all unknown numbers.

**Comment by 2br-2b** [comment]
It's been a while, but I think I found an app which does what you ask. Does [NoPhoneSpam](https://f-droid.org/en/packages/at.bitfire.nophonespam/) do what you ask?

**Comment by wellthissucks** [comment]
This used to be a feature in stock android. You could block all calls except those in your contacts. Can't remember when it disappeared.

**Comment by thestinger** [comment]
You'll need to clarify what you mean by "stock Android". Do you mean the stock Pixel OS? There's no generic "stock Android" OS.

**Comment by thestinger** [comment]
@2br-2b Silence is a dead, unmaintained project without security updates. It shouldn't be used.

**Comment by thestinger** [comment]
@2br-2b Nevermind you meant a different app than I thought you did.

**Comment by wellthissucks** [comment]
Not sure how long ago it was removed. It may not have been on a Pixel that I last saw it. May have been a Sony, but it certainly didn't have any carrier stuff on it. Not locked to any network, or carrier apps.

**Comment by onkq** [comment]
App called Simple Dialer on fdroid has the option to block all calls that isn't in your contacts.

**Comment by empratyush** [comment]
okay, tho that is provided by [BlockedNumberProvider](https://developer.android.com/reference/android/provider/BlockedNumberContract)
