### ISSUE TITLE
Receive "Sandboxed Google Play is running" notification while nom GP is installed

### ISSUE THREAD

**Issue by I-I-IT** [GrapheneOS/os-issue-tracker#3958]
When I Installed the Gemini app, it told me I also needed to install the Google app. So I did. After installing the Google app, I received a notification from GMS Compact that "Sandboxed Google Play is running".

I never installed Google Play, Google Services or MicroG. I use Aurora Store to get non-FOSS apps.

**Did the Google app installed Google services by itself ?**
The Gemini app and the Google app need a bridge to communicate.

 Or, is it an **error from the GMS compact** program?

If needed, I can share a video recording or screenshots.

**Device info :**
Pixel 9
Android 14
Beta channel, up to Sep. MSR
Build n. 2024090400
Gms compat version code 1008
Gms compat config v. 135

**Comment by muhomorr** [comment]
Google app is part of sandboxed Google Play. The sandboxed Google Play compatibility layer is used to make Google app work on GrapheneOS.
