### ISSUE TITLE
expose more of the UserManager functionality in the Settings app

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/os-issue-tracker#397]
We used to do this, but it hasn't been restored yet.

https://developer.android.com/reference/android/os/UserManager

This was the previous issue on the legacy issue tracker: https://github.com/AndroidHardeningArchive/legacy_bugtracker/issues/844.

**Comment by thestinger** [comment]
The user management menu in the Settings app already exposes a few of these options, but a lot more of them would be useful.

**Comment by flawedworld** [comment]
Android 12 didn't seem to add anything useful to expose.
