### ISSUE TITLE
Please add ability to swap back button position when using 2 or 3 button navigation

### ISSUE THREAD

**Issue by vanhoopstallion** [GrapheneOS/os-issue-tracker#398]
As a user of 2 button navigation it would be beneficial to have the back button on the right side. Please can a settings option be added to toggle between swap back / regents buttons from default to alternate.

**Comment by thestinger** [comment]
I don't see much benefit in offering this kind of choice. It's also definitely out-of-scope for GrapheneOS. It's not a privacy or security enhancement, and it's not functionality that we'd need to offer for parity with the stock OS. Those are the basic guidelines we follow for determining whether something should be done by GrapheneOS. Even if there's an existing way to configure this at build time, we don't have the resources to develop and maintain a Settings app control over it. There are already a bunch of things like that we need to develop and maintain for privacy and security features. Can't afford to do this *instead* of a privacy / security toggle in the Settings app, such as more attack surface reduction options.

Our goal is providing the same functionality as the stock OS with substantially improved privacy and security. It detracts from the focus of the project to expend resources developing and maintaining assorted frills and configuration unrelated to privacy and security. The stock OS doesn't offer 2 and 3 button navigation anymore on recent devices.

**Comment by elfein727** [comment]
This is a stock OS feature in 2022. Would appreciate seeing it added.

**Comment by thestinger** [comment]
The stock Pixel OS doesn't even have 2 button navigation. Button navigation is not used by default and is largely deprecated. We're not adding downstream features to it. Use gesture navigation.

**Comment by elfein727** [comment]
Lineage has it.

**Comment by thestinger** [comment]
That's irrelevant. Gesture navigation is the default system navigation method on GrapheneOS and the stock OS. Button navigation is largely deprecated aside from an accessibility feature. Use gesture navigation. Read our usage guide on it.

https://grapheneos.org/usage#gesture-navigation

The issue already has an explanation for why it's closed. Why are you wasting developer time?

**Comment by thestinger** [comment]
This is available as a standard Android feature now.
