### ISSUE TITLE
Attestation fails to generate key pair after factory reset and restore from backup

### ISSUE THREAD

**Issue by NarwhalPrince** [GrapheneOS/os-issue-tracker#4068]
After doing a factory reset through recovery, I restored the device using a seedvault backup. After doing this, I am unable to complete local or remote attestation. The pairings have been cleared and the device has been rebooted. Fails with:

java.security.ProviderException: Failed to generate key pair.

Included Auditor's verbose log
[Auditor log cec7810070dd.txt](https://github.com/GrapheneOS/Auditor/files/14284632/Auditor.log.cec7810070dd.txt)

First time submitting an issue, please go easy on me.

**Comment by zacha81** [comment]
The suggested solution for systems that have already been restored does not work. You cannot clear RemoteProvisioner data as this option is greyed out in the settings.

**Comment by tmakarios** [comment]
> Run `pm clear com.android.rkpdapp` in `adb shell`.

This didn't work for me.  Running the command in `adb shell` reported success, but when I tried auditing the device, it still failed to generate a key pair. 

Same story even when I cleared Auditor's storage, force stopped it, and ran the shell command again.

**Comment by zacha81** [comment]
for me it did help.

**Comment by tmakarios** [comment]
> @tmakarios Make sure you're clearing it for Owner and not another user. You could pass `--user 0` to it but that should already be what it does by default. I don't know why it wouldn't work for you.

The `--user 0` thing didn't make a difference.  I think the backup that was restored in the first place was originally from a LineageOS phone.  Might that be the problem in my case? 

More information:  I have only one GrapheneOS phone, so I was attempting to audit it from a DivestOS phone.  When I try swapping roles, I don't get the key generation error; instead, after scanning the auditee's QR code, the GrapheneOS phone says

> **Error encountered verifying attestation:**
> invalid verified boot key fingerprint: _lots of hexadecimal_

**Comment by snrkl** [comment]
I have a secondary pixel returning in the next few weeks.

@thestinger I'll be able to test a net new backup/restore then and I'll advise how it goes..

**Comment by tmakarios** [comment]
> That's not officially supported and can cause a huge amount of problems.

OK, that's useful to know.  So far I haven't noticed any problems other than this one with Auditor.

**Comment by tmakarios** [comment]
> DivestOS isn't included in Auditor at the moment. We've asked if they want to be included in it but they haven't done it yet.

Good to know there's potential for inclusion of DivestOS in future.
