### ISSUE TITLE
Can't enter the password after the system reboots.

### ISSUE THREAD

**Issue by aadunin** [GrapheneOS/os-issue-tracker#4103]
Pixel 6 pro, GOS Alpha channel, OEM unlocking disabled.
The ‘FUTO Keyboard’ application is installed in the operating system
In the system settings, ‘FUTO Keyboard’ has been selected as the default input, and other keyboards are disabled. 
After rebooting the device, a system message appears on the password input screen:
The ‘FUTO Keyboard’ application has crashed again.
In fact I can't do anything.
I can't enter the password because there is no input method and the system doesn't prompt me to select the stock keyboard.

**Comment by akc3n** [comment]
Perhaps uninstalling the app after rebooting into 'Safe mode' will resolve your situation.
https://support.google.com/pixelphone/answer/2852139

The app itself is the problem and not anything to do with GrapheneOS by the way.

**Comment by aadunin** [comment]
Юрий, благодарю за ответ!
