### ISSUE TITLE
Screen randomly stays 'on' despite inactivity timeout

### ISSUE THREAD

**Issue by Saroumane** [GrapheneOS/os-issue-tracker#4248]
Build 2024102400 on Pixel 6a

I'm a bit embarrassed to report this because I can't reproduce it 'at will'.

Sometimes, my phone is on the home screen (no apps on foreground), and the screen stays on, unlocked, until I manually lock the phone (or reboot)
My screen timeout is set on 30 seconds.

Last time I saw that (in Owner profile), I used the 'task manager' to kill all app 1 by 1 (and wait 30 sec after each one) to try to find the 'culprit'.

The 30sec screen timeout was working again after I killed the calendar app Etar (v1.0.47 installed from Obtainium with an F-droid source)

Problem : I relaunched Etar after that and could not reproduce the problem.

Edit : I also saw that on a secondary profile where Etar is not installed.

**Comment by Saroumane** [comment]
I did not modify brightness.
I have indeed a widget of Etar on Owner profile, but no widgets on secondary profile, where I also have the problem sometimes.

**Comment by Saroumane** [comment]
It just happened again, on a secondary profile. I killed 2 running apps, nothing changes.
I kill last running app : screen timeout is restored.
That app was Vanadium.

**Comment by empratyush** [comment]
I don't think it is worth tracking this issue, it is not an os issue. An app can keep wake lock and this by design.
