### ISSUE TITLE
Phone Went Black & Semi-Unresponsive

### ISSUE THREAD

**Issue by seniorm0ment** [GrapheneOS/os-issue-tracker#4257]
Just had a major issue with my phone

It's a Pixel 8 Pro and I was in the middle of typing to someone and my entire phone just went black. 
I kept holding the power button and I just felt a small vibration after a second. Did it again a few times it kept doing it but nothing changed on the screen.

Then I suddenly saw the swipe bar (but horizontally on the long side of the phone) but it wouldn't do anything. It's like the phone was stuck in landscape, but also still 95% black screen.

Then suddenly my lockscreen wallpaper showed up, but it was sideways and the upper half of the phone was still black. 
I accidentally did an emergency dial and dialed 911 (I assume from one of the power button quick tiles). I could not see a thing or any buttons I just told them it was an accident and they hung it up. I did not see a dialer screen, I did not see a hangup button, I did not see any quick tiles come up when I held the power button. Just a half black upper screen and my lockscreen wallpaper.

I had to hold the top volume button and power button for a while and it rebooted the entire phone and it seems fine now..
I did have a similar issue about a week ago but it just stayed black. Reboot resolved that time too.

Build: 2024102400

**Comment by empratyush** [comment]
It seems like your phone may have encountered a system or service crash that exhausted its resources. Unfortunately, without logs can't really look into it.

will really appreciate, If you can reopen the issue with proper logs.

**Comment by seniorm0ment** [comment]
What is the proper way to grab and send logs without publicly leaking personal information (which I assume is in the logs)

**Comment by empratyush** [comment]
You can grab it in multiple ways.. 
from a desktop `adb logcat` or
Settings -> Developer options -> [Bug report](https://developer.android.com/studio/debug/bug-report) or 
Settings -> System -> View logs -> share..

you can share it any devs 

[muhomorr](https://github.com/GrapheneOS/os-issue-tracker/issues/4203#issuecomment-2452981910)
Daniel Micay daniel.micay@grapheneos.org 
Pratyush pratyush@grapheneos.org
