### ISSUE TITLE
Microphone not muted on stock phone app

### ISSUE THREAD

**Issue by yoyodddd** [GrapheneOS/os-issue-tracker#4262]
Disabled the microphone through the notification center, made other apps like discord not detect my microphone, but the stock phone app ignores the "Unblock microphone" message and lets my voice be recorded through the microphone.
I called a pizza place to order food, and I forgot to unblock my microphone, but they still talked with me though the phone. Is this a bug on the recent release? Or a security issue that I should be concerned? Also after having this issue, the microphone enabling option wasn't toggled, just makes my microphone work in the stock phone app while it's not as on other apps as it's supposed to be. Maybe the stock phone app has a privilege?
![Screenshot_20241031-174043](https://github.com/user-attachments/assets/8cc578de-64ef-4e4e-8437-a8e03eb16436)

**Comment by yoyodddd** [comment]
> I remember months ago that it did work as expected, but I did not have need to reproduce it in a long time. So I don't know when it changed.

did you have the same issue?

**Comment by yoyodddd** [comment]
> > I remember months ago that it did work as expected, but I did not have need to reproduce it in a long time. So I don't know when it changed.
> 
> did you have the same issue?
> 
> 

if so, do you mind explaining more detail?

**Comment by yoyodddd** [comment]
> unable to reproduce this. can you please provide a demo video with logs?

@empratyush what build are you on? this got fixed at the 20241031 build

**Comment by yoyodddd** [comment]
> unable to reproduce this. can you please provide a demo video with logs?

it was a vaild bug at the previous build.

**Comment by empratyush** [comment]
@yoyodddd 
> what build are you on?

current main branch.

>  this got fixed at the 20241031 build.

okay, cool.

**Comment by yoyodddd** [comment]
> We didn't make any changes related to this in [2024103100](https://grapheneos.org/releases#2024103100). It's likely you had some kind of UI issue. Microphone access may not have actually been disabled for you. Are you using multiple users?

@thestinger no. but after reading your comment, i remember there were two windows displaying the same microphone message. it's weird since the microphone was disabled on the notification center quick command buttons.
every other app did not detect my microphone(discord, for example) but the phone app ignored that.
should i be concerned? maybe might be a security issue? idk
