### ISSUE TITLE
Bluetooth volume control bug

### ISSUE THREAD

**Issue by user-51** [GrapheneOS/os-issue-tracker#431]
I am running GrapheneOS on a Pixel 3a. There is an issue with two of my Bluetooth devices - a Plantronics E50 headset and a Logitech Bluetooth audio receiver. When the smartphone loses connection to one of these devices while music is playing (e.g. the headsets battery has expired) the volume control stops working properly: When the bluetooth device has been reconnected only 5 of the 25 volume steps work properly, and the maximum volume is reached after 3 or 4 steps.
This error only occurs with the Plantronics headset and the Logitech adapter, but not with my Bluetooth speaker, the phones internal speaker or any analog headphone. For these devices the volume control works properly even when the error has been triggered. 
Proper volume control for the Plantronics headset and the Logitech adapter is restored by rebooting the phone, but not by unpairing and re-pairing the affected bluetooth device.

**Comment by bukhalo** [comment]
Have you tried enabling the option "Disable absolute volume" is developer settings? I have similar problems with AirPods on stock firmware.
