### ISSUE TITLE
blurred font in call settings phone app in dark mode

### ISSUE THREAD

**Issue by snoo0py** [GrapheneOS/os-issue-tracker#432]
On navigating to Settings -> Calls/Accessibiltiy/Blocked Numbers/Quick responses in dark mode in the phone app the font is blurred and very hard to read:
![Screenshot_20210129-032239](https://user-images.githubusercontent.com/65139253/106224971-7f3bdf00-61e4-11eb-9264-57d5dd2dc81a.png)

Settings -> Sounds and vibration looks fine:
![Screenshot_20210129-033704](https://user-images.githubusercontent.com/65139253/106224970-7ea34880-61e4-11eb-931b-b3877099cf09.png)

This is Setting -> Calls again, but with smallest font setting at settings-app -> Display -> font size

![Screenshot_20210129-034121](https://user-images.githubusercontent.com/65139253/106224968-7e0ab200-61e4-11eb-8e36-4feb589816ac.png)

Device: Pixel4a
Phone app version: 23.0
Build number: RQ1A.210105.002.2021.01.23.03

If you need more information, I'm happy to help.

**Comment by thestinger** [comment]
Resolved in Android 12 GrapheneOS.
