### ISSUE TITLE
Pixel 8a failing to install update

### ISSUE THREAD

**Issue by newb23** [GrapheneOS/os-issue-tracker#4326]
Trying to update to release 2024110700.

Update downloads, installs, verifies, then... nothing. No prompt for reboot, nothing is prompted after reboot, and attempts to manually search for an update starts the process over. 

Unmodified GrapheneOS, update 2024110400, tried toggling between Alpha, Beta, and Stable channels to no effect.

Logs attached! 

[System log _ seamless 10c947171662.txt](https://github.com/user-attachments/files/17730114/System.log._.seamless.10c947171662.txt)
[System log _ seamless 25c903c52717.txt](https://github.com/user-attachments/files/17730115/System.log._.seamless.25c903c52717.txt)
[System Updater log 7b42810839ab.txt](https://github.com/user-attachments/files/17730116/System.Updater.log.7b42810839ab.txt)

**Comment by muhomorr** [comment]
There's not enough info in filtered system logs. Need to see the full system log right after a new update attempt.

Send it to one of the following places:
Matrix: @muhomorr:grapheneos.org
Discord: muhomorr_ (with underscore at the end)
Email: [muhomorr@grapheneos.org](mailto:muhomorr@grapheneos.org)

**Comment by muhomorr** [comment]
Updater log shows that update fails with error code 20 (kDownloadStateInitializationError), but there are several places that produce this error. Full system log should allow to narrow it down.

**Comment by newb23** [comment]
> There's not enough info in filtered system logs. Need to see the full system log right after a new update attempt.
> 
> Send it to one of the following places: Matrix: @muhomorr:grapheneos.org Discord: muhomorr_ (with underscore at the end) Email: [muhomorr@grapheneos.org](mailto:muhomorr@grapheneos.org)

Sent!

**Comment by muhomorr** [comment]
@newb23 Did you try to update the OS before capturing the log? I don't see any traces of OS update attempt there. Need you to try to update the OS again, wait until it fails, then immediately capture the full system log.

**Comment by newb23** [comment]
> @newb23 Did you try to update the OS before capturing the log? I don't see any traces of OS update attempt there. Need you to try to update the OS again, wait until it fails, then immediately capture the full system log.

Re-sent after a fresh reboot and re-attempt!

**Comment by newb23** [comment]
Huh, extrapolated from that log: 

`11-13 10:40:18.947  root  1087  1087 E update_engine: [ERROR:filesystem_verifier_action.cc(510)] Old 'system' partition verification failed.
11-13 10:40:18.949  root  1087  1087 E update_engine: [ERROR:filesystem_verifier_action.cc(512)] This is a server-side error due to mismatched delta update image!
11-13 10:40:18.953  root  1087  1087 E update_engine: [ERROR:filesystem_verifier_action.cc(514)] The delta I've been given contains a system delta update that must be applied over a system with a specific checksum, but the system we're starting with doesn't have that checksum! This means that the delta I've been given doesn't match my existing system. The system partition I have has hash: MstdAcHtftiPJqqPCPsb0E+QZ9foV5q13CR2ZCJjevM= but the update expected me to have DHNMs48tiYvAQT85GZCdY6H70cpILup7VkoPJCkqkAA= .`

**Comment by muhomorr** [comment]
@newb23 Does your device show the "Your device is corrupt" red triangle screen during boot?

**Comment by muhomorr** [comment]
`DHNMs48tiYvAQT85GZCdY6H70cpILup7VkoPJCkqkAA=` system partition hash is correct for 2024110400 release that you're running.

**Comment by newb23** [comment]
> @newb23 Does your device show the "Your device is corrupt" red triangle screen during boot?

Negative, yellow triangle: your device is loading a different operating system. (Paraphrase, no screencap)

**Comment by muhomorr** [comment]
"Yellow triangle" screen should contain the verified boot key has at the bottom ("ID: ...). Check whether it shows
`096b8bd6d44527a24ac1564b308839f67e78202185cbff9cfdcb10e63250bc5e`

**Comment by muhomorr** [comment]
Also try updating the OS one more time, then capture the log again and check whether current system partition hash is still 
`MstdAcHtftiPJqqPCPsb0E+QZ9foV5q13CR2ZCJjevM=`.

**Comment by muhomorr** [comment]
@newb23 When did you install GrapheneOS?

**Comment by Pommede** [comment]
Hi
i've got the same issue with a pixel 7A...see https://discuss.grapheneos.org/d/17033-unable-to-complete-os-install/
thks

**Comment by newb23** [comment]
> Also try updating the OS one more time, then capture the log again and check whether current system partition hash is still `MstdAcHtftiPJqqPCPsb0E+QZ9foV5q13CR2ZCJjevM=`.

Sorry in the delay, work trip. 

Running the update attempt again manually today, and can verify the hash stayed the same. 

`I have has hash: MstdAcHtftiPJqqPCPsb0E+QZ9foV5q13CR2ZCJjevM= but the update expected me to have DHNMs48tiYvAQT85GZCdY6H70cpILup7VkoPJCkqkAA=`

I updated to the pixel 8a offering as soon as it hit the beta channel. Ditto for when 15 dropped.

**Comment by newb23** [comment]
Attempted to update again this morning. New logic on resuming update appears to allow the phone to start at the validation phase, but still ultimately fails installation. 

Log attached filtered for "hash", happy to capture full log or any other regex as requested/provided.
[System log _ hash 9c4d6d2b5010.txt](https://github.com/user-attachments/files/17833711/System.log._.hash.9c4d6d2b5010.txt)

**Comment by newb23** [comment]
> Please try sideloading the latest release:
> 
> https://grapheneos.org/usage#updates-sideloading

Side-load of 2024111800 was successful. 
ADB'd the update over, restart, optimization (x2) reboot, (still yellow triangle - not red) and hot to trot.
Wholly unknown as to what the root cause was, but looking forward to seeing if the next update will take!

**Comment by Pommede** [comment]
apparently, not the same problem :-(
because sideloading doesn't work for me either...
i should live without update...

**Comment by newb23** [comment]
> > Please try sideloading the latest release:
> > https://grapheneos.org/usage#updates-sideloading
> 
> Side-load of 2024111800 was successful. ADB'd the update over, restart, optimization (x2) reboot, (still yellow triangle - not red) and hot to trot. Wholly unknown as to what the root cause was, but looking forward to seeing if the next update will take!

Latest update, 2024112700 was successfully, automatically, installed.

**Comment by Pommede** [comment]
should i open a new issue ???

**Comment by Pommede** [comment]
perhaps but the phone is ok to use, and the update is ok with pixelos and divestos..why a bug with only graphene?
and too expensive to change anything just doing an update with graphene ;-)

**Comment by Pommede** [comment]
i can try to find another android device..but no changes at all of grapheneos,
tried with the cli and the wenbnst...but from 2 differents pc,linux/windows..
probably broken hardware but the ONLY issue is the update of grapheneos...strange...

**Comment by Pommede** [comment]
today the update was ok for the first time :-)
didn't have time to try with another android.
something changes?
