### ISSUE TITLE
Phone calls not showing up on head unit with Android auto

### ISSUE THREAD

**Issue by vertigo65536** [GrapheneOS/os-issue-tracker#4333]
Phone calls are not showing up on the head unit, regardless of how they're made. Both outgoing and incoming calls are affected.
I have Android auto installed on an alternate user. Android auto has all permissions enabled, including everything in the Sandboxed Google Play, and all notification access.
The sound from the calls come through, but the controls do not appear. I cannot answer calls or anything else via the head unit. 
Graphene is fully up to date, and installed on a Pixel 7 Pro.
The head unit is a Pioneer SPH-DA230DAB

**Comment by muhomorr** [comment]
Resolved by https://github.com/GrapheneOS/platform_packages_services_Telecomm/pull/11
