### ISSUE TITLE
Bricking phone by disabling keyboards

### ISSUE THREAD

**Issue by freerig** [GrapheneOS/os-issue-tracker#4348]
If you disable every keyboard except a fancy keyboard like aaaaaaaa or kboard, you will be unable to unlock the device if you're using password. I didn't do it and DON'T do it, but I managed to enable only Gboard (without internet btw) in the lock screen, so I believe it will work with others keyboards.
Not every keyboard can type a password, so I think you shouldn't let the user disable AOSP keyboard, or at least when entering passwords.
Stock Android don't have this issue because we can't disable USB keyboard on lock screen i believe, but in grapheneos, we can.

**Comment by rusty-snake** [comment]
- It's not bricked, you can still factory reset.
- You can reboot into safe mode AFAIK to get back AOSP Keyboard.

**Comment by freerig** [comment]
Ok, didn't know. Thx

**Comment by freerig** [comment]
I meant disabling it in the on screen keyboard page (where you can choose which keyoard are shown), not in the app infos. But that's not a problem thanks to safe mode

**Comment by freerig** [comment]
This seems to be a nice solution.

But well... Actually, what if we put some special characters in the password (like language-specific symbols), that the AOSP keyboard doesn't have...
![image](https://github.com/user-attachments/assets/75ac43f3-4066-4dc6-9315-320f8817a212)
I tried to set my passwork with some random fancy font using kboard app. I didn't go through the whole process (I'm not crazy), but GrapheneOS seems to allow random stuff in passwords (at least during the first steps of the process). So then, when going to safe mode, if AOSP keyboard doens't provides 𝖙𝖍𝖎𝖘 𝖘𝖞𝖒𝖇𝖔𝖑𝖘, we can't unlock the phone for the rest of our life.

Maybe there's a protection against that (again, I'm not crazy, I didn't tried), but if not...
