### ISSUE TITLE
Android Auto audio stopped working after an update

### ISSUE THREAD

**Issue by jooray** [GrapheneOS/os-issue-tracker#4505]
In 2024120900 Android Auto audio (bluetooth) stopped working. It says I should try to restart the device when I look at the device in Bluetooth settings.

When I control the volume, it acts as if Bluetooth is not connected, but the sound does not come out of the internal speaker either. 

Allow rerouting of audio is enabled in sandboxed google play / android auto settings. 

Before this update, it was working, although disconnecting from Android auto often (see https://github.com/GrapheneOS/os-issue-tracker/issues/4224 )

**Comment by muhomorr** [comment]
Does Android Auto have the Microphone permission?

See https://grapheneos.social/@GrapheneOS/113629803646184979 for context.

That issue should be resolved in the current beta release (2024121200).

**Comment by jooray** [comment]
Oh, it did not have Microphone permission. I will try, but since it is a known bug, I am closing this. In case it is not working, I will reopen.
