### ISSUE TITLE
Pixel 4a (5G) MMS problem

### ISSUE THREAD

**Issue by zvl12** [GrapheneOS/os-issue-tracker#454]
MMS appearing as square colored box in secondary profile, cannot download unless going back to main user profile and downloading it from there

**Comment by anupritaisno1** [comment]
Please send a screenshot if possible

**Comment by zvl12** [comment]
see here screenshot, this is situation in secondary profile, if i go to main profile, the mms will show correctly

<img width="559" alt="Screen Shot 2021-02-19 at 0 52 31" src="https://user-images.githubusercontent.com/79111846/108432404-f812e180-724c-11eb-8f52-38062573def3.png">

**Comment by thestinger** [comment]
Please test on the latest June release.

**Comment by snprmnky** [comment]
On latest. No issues. Video and image MMS appear normal.
