### ISSUE TITLE
Reverse wireless charging support

### ISSUE THREAD

**Issue by VSfz3kkDwtjm4LAD2R24** [GrapheneOS/os-issue-tracker#455]
Hi, I recently installed RQ1A.210205.004.2021.02.12.09 on my Pixel 5. I found out the reverse charging feature is not present. I wonder if this would ever be possible to implement into GrapheneOS.

Thanks.

**Comment by thestinger** [comment]
It works fine here. You need to enable it in the menu from the USB notification.

**Comment by VSfz3kkDwtjm4LAD2R24** [comment]
I'm sorry, but could you please further explain it? Did you mean the usb notification that allows you to change between file transfer, ptp, etc.? As far as I'm concerned, I do not see reverse charging option there. Just to make sure, I'm referring to the reverse wireless charging feature exclusive to Pixel 5 at the moment. I apologize if I didn't say it clear.

**Comment by thestinger** [comment]
You didn't say anything about wireless charging.

**Comment by VSfz3kkDwtjm4LAD2R24** [comment]
I'm sorry.

**Comment by thestinger** [comment]
Don't need to be sorry, I just didn't understand what you were talking about because of that.

**Comment by VSfz3kkDwtjm4LAD2R24** [comment]
I'll try to be more specific next time!

**Comment by flawedworld** [comment]
If someone is willing to implement this, then a potential route would be implementing this LineageOS HAL https://github.com/LineageOS/android_device_google_redfin/commit/4119828ed3148451dff1027f80efe5d2fa960429 among other changes to the OS.

**Comment by yaroze** [comment]
Sorry for digging this out of its grave, but I can't seem to find this feature on the Pixel 6 (non-pro).
Any perspective wether this will be implemented?
Thanks for the great work by the way!

**Comment by flawedworld** [comment]
Issue title should be renamed to reflect this. It's not implemented on any device currently.

**Comment by thatnerdjosh** [comment]
@flawedworld - is implementation of this in progress? I am not experienced in Android OS development, but I would be interested in having this feature, so I could try to implement it if it's not already in progress.

**Comment by empratyush** [comment]
Implemented in [#212](https://github.com/GrapheneOS/platform_frameworks_base/pull/212)
