### ISSUE TITLE
investigate if TOUCHSCREEN_SEC_TS_GLOVEMODE is needed/supported on redfin and if it is, how to expose the relevant toggle in settings else disabling it 

### ISSUE THREAD

**Issue by anupritaisno1** [GrapheneOS/os-issue-tracker#456]

**Comment by flawedworld** [comment]
The stock functionality of this "Increase touch sensitivity: Improves touch when using screen protectors" uses the touch_sensitivity_enabled boolean in secure settings.

Identified by `redfin:/ $ settings list secure | grep touch` and seeing the boolean change based on the toggle in stock.

**Comment by anupritaisno1** [comment]
@flawedworld this isn't really relevant to the issue. the toggle may even be unrelated

can you check if this option is enabled on stock by checking /proc/config.gz?

use this command:

```
zcat /proc/config.gz
```

**Comment by flawedworld** [comment]
@anupritaisno1 you are correct, my bad. It is not present. Full contents are here: https://gist.github.com/flawedworld/bf1c94f0daaa14e678e646b7c88e7951

**Comment by thestinger** [comment]
That doesn't mean anything because it's built as a module for them.

**Comment by thestinger** [comment]
That doesn't mean much because it's built separately as a module for them as far as I know.

**Comment by thestinger** [comment]
The touchscreen driver isn't listed there at all.

**Comment by lazerl0rd** [comment]
> @flawedworld this isn't really relevant to the issue. the toggle may even be unrelated
> 
> can you check if this option is enabled on stock by checking /proc/config.gz?
> 
> use this command:
> 
> ```
> zcat /proc/config.gz
> ```

The toggle is unrelated. `CONFIG_TOUCHSCREEN_SEC_TS_GLOVEMODE` isn't even mentioned in the source, and the toggle controls a property which init watches for and sends a command to the `cmd` sys node to enable "glove mode".

**Comment by thestinger** [comment]
So, this should be closed?

**Comment by lazerl0rd** [comment]
> So, this should be closed?

Not yet, as it hints at having the toggle added which I'll be working on at some point this week.

**Comment by thestinger** [comment]
I think a separate issue for a toggle is the best approach if it's unrelated to the kernel configuration option.
