### ISSUE TITLE
Hard crash when unplugging a physical keyboard or disconnecting a bluetooth keyboard for the first time

### ISSUE THREAD

**Issue by transcommunism** [GrapheneOS/os-issue-tracker#458]
Plugged in my keyboard to test something out using the type C to type A adapter that came in the box of my phone. Keyboard worked, and while loading a webpage in Fennec F-Droid, I unplugged the adapter with the keyboard attached. Phone froze, and then brought me back to the initial boot screen that warns me I'm running a non-stock operating system. Could not reproduce the bug once the reboot finished.

**Comment by flawedworld** [comment]
Confirmed on Pixel 5 running RQ1A.210205.004.2021.02.19.15

**Comment by thestinger** [comment]
@transcommunism On which phone model?

**Comment by thestinger** [comment]
It's probably an upstream bug detected by a mitigation.

**Comment by transcommunism** [comment]
> @transcommunism On which phone model?

Pixel 4a

**Comment by thestinger** [comment]
Probably a kernel bug (rather than elsewhere) uncovered by a mitigation. Best way to debug it is getting pstore logs for the previous boot logs on a userdebug build.

**Comment by thestinger** [comment]
https://issuetracker.google.com/u/0/issues/184526464

**Comment by thestinger** [comment]
Can also happen with a Bluetooth keyboard. Seems more tied to keyboard than USB.

**Comment by flawedworld** [comment]
This also applies to mice

**Comment by thestinger** [comment]
This is resolved.
