### ISSUE TITLE
No keyboard when switching to secondary profile

### ISSUE THREAD

**Issue by brennekeh** [GrapheneOS/os-issue-tracker#467]
When switching from owner to password protected secondary profile the keyboard does not show.
Screen touches do not cause the keyboard to show.
Opening and then immediately exiting the global action menu by long pressing the power button causes the keyboard to show at next screen touch.
This problem occurs always on both 2XL and 4a.
This workaround is successful always on both phones.
I have tried installing other keyboards as suggested by strcat, no change. 
GrapheneOS keyboard is the only keyboard available when signing in to both owner and secondary profiles, even if another keyboard is installed.
I have also ensured all permissions for GrapheneOS keyboard are allowed.
No permissions for system apps have been denied.

**Comment by thestinger** [comment]
> GrapheneOS keyboard is the only keyboard available when signing in to both owner and secondary profiles, even if another keyboard is installed.

The keyboard needs direct boot support to be able to do this. Most keyboards won't have it so they can't run before the profile is decrypted.

**Comment by flawedworld** [comment]
This does not seem to be an issue anymore.

**Comment by flawedworld** [comment]
This is still an issue

**Comment by Zanthed** [comment]
Please report if this is still an issue after QPR3.

**Comment by thestinger** [comment]
Let us know if this is still an issue on Android 13.

**Comment by brennekeh** [comment]
I am still seeing this every day with one of my secondary profiles on 13 with 4a. 

Thank you. 

Aug 31, 2022, 02:46 by ***@***.***:

**Comment by thestinger** [comment]
Should be resolved in Android 14 QPR1.
