### ISSUE TITLE
After rebooting, if you quickly switch users, the secondary user's system navigation setting is 2-button regardless of what it was before the update, and does not match what is in the settings menu

### ISSUE THREAD

**Issue by mrhebisan** [GrapheneOS/os-issue-tracker#470]
On Pixel 3a : Reproduced 2 times

* Create at least one secondary user.
* In the Owner's profile, set the gesture style to "3 button"
* In the secondary user's profile, set the gesture style to "Gesture"
* Recieve an OTA update and return to the Owner profile.
* While in the Owner profile, restart the phone so that the update is installed
* VERY QUICKLY as soon as owner boots up, unlock the screen and immediately switch to the secondary user.

Observe : The secondary user's gesture setup is now the default 2 button style.
Observe : Enter Settings -> System -> Gestures -> System Navigation
Observe : The toggle is actually still on "Gesture navitagion" even though the phone is using 2 button.

Tap on any of the other two items to switch to that navigation style.
Tap on Gesture navigation

Observe : You now have gesture navigation back.

**Comment by marcojanotta** [comment]
Pixel 4a, after every OTA update.

Workaround: Switch back to the primary user and back to the secondary user. The system navigation should again match what was set.

**Comment by thestinger** [comment]
This is likely fixed by the June update (Android 11 Quarterly Maintenance Release 3).

**Comment by flawedworld** [comment]
This does not seem to be any issue anymore.
