### ISSUE TITLE
AOSP keyboard spell checker mistakenly underlines words in red when using multiple languages

### ISSUE THREAD

**Issue by deep-ocean-fish** [GrapheneOS/os-issue-tracker#518]
Thank you for the great effort you put into the project! I love GrapheneOS so far!

There is a problem with the spell checking feature. I have set English and German as the GrapheneOS Keyboard languages and my phone language to English and added German as a second system language. Moreover I have set the spell checker Languages to "Use system languages". 

When I type text in English the spell checker won't underline anything but as soon as I switch the keyboard to German it starts underlining words typed in German in red and still spell checks in English. The issue is not present if German is set as the system language and English as the second language. Then when setting the keyboard to German it works fine but when switching the keyboard to English it starts underlining English words in red now. 

It appears as if the system language determines the spelling language. I also have tried setting the system language to English and the spell checker Language (in the settings) to German. This works fine but the "Use system languages" (plural) option (to switch spell checker languages by just pressing the globe on the keyboard)  doesn't seem to work.

**Comment by thestinger** [comment]
This is all based on the keyboard which you can replace with another, and which we will likely replace with another eventually.

**Comment by thestinger** [comment]
See #579. Please file feature requests with FlorisBoard.
