### ISSUE TITLE
Issues with screen sensitivity and slide bar disabling

### ISSUE THREAD

**Issue by EvanFont** [GrapheneOS/os-issue-tracker#519]
Hi, I love my GrapheneOs on my Pixel 4 but the screen recently developed issues with its sensitivity and the App Slide bar has almost completely stopped working. I tried switching the type of slide bar in the options but to no avail. Since if you reset the phone you are then able to open an App (but are then unable to switch between the Apps). This recently developed. It has shown glitchiness. Considering when I went to computer place in town to get it fixed the phone suddenly showed no sign of being out of sorts. It then got worse once I got back. I'm not sure what to do.

**Comment by EvanFont** [comment]
Yes the navigation bar is now only working only when it wants too

**Comment by EvanFont** [comment]
I meant reset as in simply turning it on and off. I have not downloaded anything that would be considered sketchy. The most recent one was simply Ameritrade. And it has not been given permission for anything. All I know is that it just started happening to my phone this morning and it has continued all day.

**Comment by thestinger** [comment]
This sounds like a hardware issue with the touchscreen and I don't really think we can do anything about it.
