### ISSUE TITLE
Alarm sometimes does not go off

### ISSUE THREAD

**Issue by Daveed9** [GrapheneOS/os-issue-tracker#522]
I have a Pixel 2 on build number `RQ2A.210305.006.2021.03.20.15`, although this issue has persisted over multiple updates.

Sometimes the Clock app fails to sound an alarm. When the alarm does not go off, there is no missed alarm notification. With an alarm that repeats daily, it sometimes goes off and sometimes does not. I have cleared the storage of the Clock app. Do Not Disturb is configured to allow the Clock app to interrupt, has Alarms on for Alarms & other interruptions, and my specific scheduled DND says "Alarm can override end time".

**Comment by thestinger** [comment]
> Do Not Disturb is configured to allow the Clock app to interrupt, has Alarms on for Alarms & other interruptions, and my specific scheduled DND says "Alarm can override end time".

DND may still be the problem.

**Comment by thestinger** [comment]
Battery saver mode could also be a problem.

**Comment by thestinger** [comment]
> I have a Pixel 2

Pixel 2 isn't officially supported anymore. We provide extended support releases as a stopgap to help people move to newer generation devices. I doubt that this issue could be tied to hardware, but keep in mind that Pixel 2 support is considered unofficial. It's not the main official branch of GrapheneOS and lacks full security updates since October 2020.

**Comment by Daveed9** [comment]
> > Do Not Disturb is configured to allow the Clock app to interrupt, has Alarms on for Alarms & other interruptions, and my specific scheduled DND says "Alarm can override end time".
> 
> DND may still be the problem.

I believe if this were the case the alarm would fail 100% of the time since I have DND on a schedule.

> Battery saver mode could also be a problem.

My phone has been charging with battery saver off the vast majority of the time that the alarm has failed.



> > I have a Pixel 2
> 
> Pixel 2 isn't officially supported anymore. We provide extended support releases as a stopgap to help people move to newer generation devices. I doubt that this issue could be tied to hardware, but keep in mind that Pixel 2 support is considered unofficial. It's not the main official branch of GrapheneOS and lacks full security updates since proper support ended after October 2020.

I am aware, but I would also presume it is not a hardware issue causing this issue.

**Comment by thestinger** [comment]
Haven't heard of others having the issue though. That's the thing.

**Comment by Daveed9** [comment]
> Haven't heard of others having the issue though. That's the thing.

"I need to stop using my phone as an alarm clock. Overslept a few too many this month because my alarm didn't go off ;)" - @theinstallationwizard:matrix.org, December 17, 2020
[the message](https://matrix.to/#/!omAJrepvwSfkXJrqbK:matrix.org/$1608222978201714oYFHY:matrix.org?via=matrix.org&via=privacytools.io&via=tchncs.de)

"Did the most recent update break the alarm clock again? Mine did not go off this morning. No missed alarm notificaiton as well. Just nothing." - MadCamel on Freenode, December 10, 2020
[the message](https://matrix.to/#/!omAJrepvwSfkXJrqbK:matrix.org/$16076157601141942XVsxt:matrix.org?via=matrix.org&via=privacytools.io&via=tchncs.de)

It seems that there was another bug with the alarm in November of 2020 that got fixed. Searching for "alarm" on the matrix channel I can find those two since the update.

**Comment by thestinger** [comment]
There were also prior issues fixed which may require clearing the app data of the clock app and it cannot be known if those people are simply experiencing the notification channel issues which were resolved. All of these were upstream AOSP issues largely resolved through applying upstream fixes.

**Comment by thestinger** [comment]
@Daveed9 It sounds like you are using the Do Not Disturb mode. It's quite possible that the AOSP Clock app does not integrate well with the feature. If that's the problem, then it should be confirmed and then this can be filed as a new clearer issue about the problem rather than the symptoms of the problem without knowing the cause. It's likely that the AOSP Clock app needs proper DND support developed. I've seen upstream changes and downstream patches in other projects related to this.

**Comment by thestinger** [comment]
@Daveed9 Can you confirm if this is happening only when using DND? If so, I want to file a new more specific issue specifically about it being a DND issue for the Clock app.

**Comment by Daveed9** [comment]
> @Daveed9 Can you confirm if this is happening only when using DND? If so, I want to file a new more specific issue specifically about it being a DND issue for the Clock app.

I can not confirm this (yet). How would you recommend I test this? I do use a scheduled DND mode and the issue only occurs part of the time despite the alarm and DND being on constants schedules.

**Comment by thestinger** [comment]
Please test on the latest June release.

**Comment by snprmnky** [comment]
On RQ3A.210605.005.2021.06.09.13:
If DND is on, the alarm works IF the alarm is allowed to interrupt DND (as expected). If DND is off, the alarm works as expected as well.

**Comment by Daveed9** [comment]
> Please test on the latest June release.

Thank you for fixing this.

> On RQ3A.210605.005.2021.06.09.13:
> If DND is on, the alarm works IF the alarm is allowed to interrupt DND (as expected). If DND is off, the alarm works as expected as well.

Alarms are now working as described here.

**Comment by RootInit** [comment]
> @RootInit Clear data for the Clock app and try without battery saver if it's on. If you're using multiple users, that might be related.

I only have one account on my device and its set to unrestricted. Battery saver was not on and the phone was actually plugged in all night.  Cleared data but its very intermittent so not going to trust it for month or so (if ever).
