### ISSUE TITLE
Bluetooth auto turn off doesn't work properly with modern power management

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/os-issue-tracker#528]
This feature will be removed if this isn't addressed in April.

**Comment by thestinger** [comment]
Multiple people have been unable to reproduce this issue.

**Comment by Exilion666** [comment]
I'm running unmodified GrapheneOS on pixel4 and 4XL on both problem presists.
Going to test timing, but generally steps to reproduce are following:
1.trun BT on
2.set delay feature
3.connect headphones
4.turn screen off
5.wait for few minutes/hours (going to test aprox. how long) without turning phone screen on
6.turn headphones off
7.wait delay time
In my case i listen to audiobooks and after some time putting earphones in charge case, so they disconnect, at morning i take phone and see that BT is on

**Comment by Exilion666** [comment]
Yesterday reinstalled grapheneOS on pixel4, bug appeared again, but i have not cached exactly when, all i can tell now that it takes more than 1hr, so i need some more time to test it...

**Comment by Exilion666** [comment]
As i registered i have problem on both pixel 4 and 4xl if bt device is connected aprox 1,5-2 hours or more, after disconnect bluetooth doesn't turn automatically off after delay. Ready to do more tests and provide logs if anybody can give me instructions. Maybe somebody else can test it out, if the problem is only on my devices, then i will just do a clean install later on other PC

**Comment by flawedworld** [comment]
Thanks for the information @Exilion666 - will be acting on this. I will let you know here if I need further assistance from you.

**Comment by flawedworld** [comment]
@Exilion666 During your attempts to reproduce this, what was the timeout value set to?

**Comment by Exilion666** [comment]
15 and 30 seconds

**Comment by Uldiniad** [comment]
might be caused by https://review.calyxos.org/c/CalyxOS/platform_frameworks_base/+/2330/1#message-85a7e538f53bf58d071c0757b3f746021129ed7e

**Comment by flawedworld** [comment]
> might be caused by https://review.calyxos.org/c/CalyxOS/platform_frameworks_base/+/2330/1#message-85a7e538f53bf58d071c0757b3f746021129ed7e

This same activity is seen in my logcat

**Comment by thestinger** [comment]
It does need to be protected. Is the component sending it not properly privileged?

**Comment by flawedworld** [comment]
@thestinger From my understanding, based on the uid and the log message given, it is not privileged which is causing it to be denied. For additional context:

https://github.com/GrapheneOS/platform_frameworks_base/blob/0c0c3352036432e2caea4b1e8957d102906d68d1/core/java/android/os/Process.java#L246

https://github.com/GrapheneOS/platform_frameworks_base/blob/55c724ac36420ee48f8ec5191fb2d37160cb32b5/services/core/java/com/android/server/am/ActivityManagerService.java#L16027

https://github.com/GrapheneOS/platform_frameworks_base/blob/55c724ac36420ee48f8ec5191fb2d37160cb32b5/services/core/java/com/android/server/am/ActivityManagerService.java#L16045

**Comment by Uldiniad** [comment]
So, the idea of the bluetooth timeout came from the bluetooth discoverable timeout:

https://cs.android.com/android/platform/superproject/+/master:frameworks/base/packages/SettingsLib/src/com/android/settingslib/bluetooth/BluetoothDiscoverableTimeoutReceiver.java

https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/res/AndroidManifest.xml;l=137?q=android.bluetooth.intent.DISCOVERABLE_TIMEOUT

What is strangest in my opinion is that SettingsLib (where the timeout receivers exist) is included in the Settings and SystemUI packages and both share uid with system. That makes me think it should always have the right UID but somehow it is getting the UID of the Settings app

**Comment by thestinger** [comment]
The discoverable timeout is marked as protected upstream.

**Comment by thestinger** [comment]
```
        Intent intent = new Intent(INTENT_TIMEOUT);
        intent.setClassName("com.android.settings", "com.android.settingslib.bluetooth.BluetoothTimeoutReceiver");
```

Is this the problem? The discoverable timeout does this:

```
        Intent intent = new Intent(INTENT_DISCOVERABLE_TIMEOUT);
        intent.setClass(context, BluetoothDiscoverableTimeoutReceiver.class);
```

**Comment by Uldiniad** [comment]
> ```
>         Intent intent = new Intent(INTENT_TIMEOUT);
>         intent.setClassName("com.android.settings", "com.android.settingslib.bluetooth.BluetoothTimeoutReceiver");
> ```
> 
> Is this the problem? The discoverable timeout does this:
> 
> ```
>         Intent intent = new Intent(INTENT_DISCOVERABLE_TIMEOUT);
>         intent.setClass(context, BluetoothDiscoverableTimeoutReceiver.class);
> ```

I tried the way you suggested and I get the same result :/
