### ISSUE TITLE
Request: Please add an option to automatically restart the phone as scheduled

### ISSUE THREAD

**Issue by mawi675lr81** [GrapheneOS/os-issue-tracker#530]
Since restarting the phone is a system level task, please add it as an option so the user can schedule a restart at a set time everyday.

Do no know if there would be any security implications but it'd be great if that option can also be made available for tasker to trigger a reboot.

**Comment by thestinger** [comment]
> Do no know if there would be any security implications but it'd be great if that option can also be made available for tasker to trigger a reboot.

That's not going to be added. A device manager or device policy manager can already reboot.

**Comment by thestinger** [comment]
We cannot add APIs for third party apps anyway. It's no use. They aren't built to run specifically on GrapheneOS.

**Comment by Nebulawn** [comment]
I have made a temporary solution for this @mawi675lr81 its on my repo @ https://github.com/Nebulawn/GrapheneOS_Projects/blob/main/Timer.py

**Comment by thestinger** [comment]
GrapheneOS doesn't have app-accessible root access even in a development build.

The feature is meant to be something that's triggered when the screen is locked and cancelled when the screen is unlocked (via any profile).

**Comment by Nebulawn** [comment]
I will get right on it and make it non root!
kinda had a heart attack when I saw you responded

**Comment by thestinger** [comment]
There's someone working on integrating it into the lockscreen code using an alarm timer.

**Comment by Nebulawn** [comment]
so what should I focus on, anything in particular?

**Comment by thestinger** [comment]
There's an implementation of a feature like this now for the next release. It will auto-reboot after N hours of not unlocking any user profile.
