### ISSUE TITLE
SystemUI stops responding for a long period of time

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/os-issue-tracker#531]
This issue is intended to track generic issues tied to the SystemUI component not responding for a long period of time. It's likely that this is an upstream bug uncovered by hardened_malloc or a similar hardening features. Some users are reporting this problem but most people are not encountering it and I'm not able to reproduce it myself.

Please do not post in this thread without providing a bug report zip in an email to contact@grapheneos.org unless you're a developer working on the issue or come up with a reliable way of reproducing the problem. It's not helpful to post that you're experiencing the issue without providing that information and clutters the thread.

**Comment by thestinger** [comment]
Our current suspicious is that there's an upstream bug in the [ANR (App Not Responding)](https://developer.android.com/topic/performance/vitals/anr) handling. GrapheneOS hardening features sometimes uncover bugs in apps and may increase the frequency of them triggering ANR. If there's an upstream problem with this, it would be encountered more often on GrapheneOS. It's also possible that there are issues triggered during the process of creating the debugging data from encountering the issue. So, it's likely that this is a combination of various upstream issues that are uncovered or aggravated by GrapheneOS hardening features.

**Comment by renlord** [comment]
This does not seem to be an issue anymore.
The OOM killer is alot more aggressive now with killing other user applications while keeping SystemUI fluid and running.

**Comment by modernNeo** [comment]
@renlord Is this really still not an issue? What is happening on my end is when firefox app experiencing an issue, it caused the whole OS to crash. While Firefox itself should not be crashing, should an App crash be capable of causing the whole OS to crash?

**Comment by renlord** [comment]
> @renlord Is this really still not an issue? What is happening on my end is when firefox app experiencing an issue, it caused the whole OS to crash. While Firefox itself should not be crashing, should an App crash be capable of causing the whole OS to crash?

What do you mean by crash?

If applications are being terminated, it is OOMkiller doing its job.

**Comment by modernNeo** [comment]
>What do you mean by crash?

I mean, when this happens on my pixel 4, it can range from the UI just stops responding for a few minutes to the entire OS crashing and I have to boot my phone up again. I was in email communication with @thestinger and shared my logs with them and they indicated to me that the problem was some sort of firefox bug.


> If applications are being terminated, it is OOMkiller doing its job.

It's not always the app being terminiated, the issue is the OS itself crashes as a result of the bug.
