### ISSUE TITLE
Request: Emergency Password to Factory Reset Device

### ISSUE THREAD

**Issue by geeklord858** [GrapheneOS/os-issue-tracker#533]
I understand that Graphene is extremely resistant to brute force attempts and that it isn't practical to create a hidden volume/OS with a decoy password.
However my question is if there can be an added feature where an emergency password is input at the lock screen which factory resets the device (thus wiping the encryption keys)?

This would be in the event that you are 'legally compelled' to provide your password to the authorities (not simple border control agents) and you have no other option.
This is assuming the device is confiscated and the authorities will enter the password themselves and/or you are not expecting them to return your phone in the future.

You would still technically be providing them the correct password to unlock the device, albeit a fresh install with zero user data.

**Comment by Pauler221** [comment]
That sounds really good. I’d also like to see that.

**Comment by thestinger** [comment]
This is filed as https://github.com/GrapheneOS/os_issue_tracker/issues/29 already.
