### ISSUE TITLE
RFE: provide (or use) an implementation of (and/or alternative to) (some of) the client parts of Play Services

### ISSUE THREAD

**Issue by DemiMarie** [GrapheneOS/os-issue-tracker#549]
This might just be a bad idea, and I am by no means expecting to be implemented even if it is not.  That said, in light of https://github.com/GrapheneOS/Vanadium/issues/61 it appears that there are some parts of Google Play Services that do not rely on any network connection,, and which provide useful, security-enhancing features such as FIDO integration.  GrapheneOS could offer support for that subset.

(To be clear: “I have no time to do this” is a valid response ― this is mostly a question about the concept)

**Comment by thestinger** [comment]
Most of the relevant parts of Play services are simply providers for AOSP APIs and can be implemented without involving it such as the backup service, text-to-speech, voice-to-text, geocoding, network-based location providers, etc. We plan on providing alternatives to all of those which doesn't involve implementing Play services APIs.

The way Play services implements FIDO2 is not what we would want if we're going to be making our own implementation. It's just not the approach we would take. We'll make something that works for Vanadium and we could make it possible for other apps to use it but in practice they wouldn't.

Apps using Play services will be checking that it matches their signature and we really don't want to make something that has to pretend to be Play services, etc. through OS support for tricking apps. I don't think it's a sustainable approach and we don't want to be maintaining something like that. There's https://github.com/GrapheneOS/os-issue-tracker/issues/204 filed about making a stub implementation of APIs but that wouldn't include implementing stuff like that. If we're going to do FIDO2, and we probably are, it's going to be a better implementation without issues like https://bugs.chromium.org/p/chromium/issues/detail?id=997538.

**Comment by DemiMarie** [comment]
> The way Play services implements FIDO2 is not what we would want if we're going to be making our own implementation. It's just not the approach we would take. We'll make something that works for Vanadium and we could make it possible for other apps to use it but in practice they wouldn't.

That part is unfortunate, but I really do understand why you don’t want to implement it the way Google Play Services does.  Hopefully this can be made part of AOSP instead.

**Comment by thestinger** [comment]
Ideally, Google would release it as part of AOSP. They did it in Play services to add it to legacy devices. They could do this kind of stuff via APEX components now. It's unfortunate and feels nasty of them to have it there, but they didn't put it there to gate it behind needing Google services but rather to give users without OS updates U2F/FIDO2 quite some time ago.

**Comment by DemiMarie** [comment]
In that case, hopefully they will accept a contribution of it to AOSP, and maybe even deprecate the Play Services version.
