### ISSUE TITLE
Adjust vibration sensitivity

### ISSUE THREAD

**Issue by whiskey01** [GrapheneOS/os-issue-tracker#553]
The vibration strength feels too strong as you can hear it even from 10 meters away. Would it be possible to add a setting to adjust the vibration sensitivity? At the moment you can only turn it off and on in the accessibility settings, at least on the Pixel 3a.

**Comment by thestinger** [comment]
It can be adjusted on the higher end devices, so at most it's lack of support for the feature on that device. Unless it's supported by the stock OS, the hardware probably just lacks proper support for this.
