### ISSUE TITLE
OS crash using otg cameras.

### ISSUE THREAD

**Issue by ananteris** [GrapheneOS/os-issue-tracker#554]
Attempting to use an otg camera (Cainda USB digital microscope(X10)) and any otg camera app on the play store causes a complete crash of the phone (coral). Always reproduces and with every app I have tried.

**Comment by thestinger** [comment]
Can you try this again? We fixed a bug being uncovered in init by hardened_malloc for device events.

**Comment by thestinger** [comment]
This should be resolved now.
