### ISSUE TITLE
Navigation bar missing

### ISSUE THREAD

**Issue by ChickenThief** [GrapheneOS/os-issue-tracker#555]
I just got the new beta update and the navigation bar is missing, there's no back arrow, or home button. There's a horizontal line on the bottom of the screen, but clicking it doesn't do anything. I can swipe up to go to the home screen, and I can swipe up and to the right to open the tab selection page. Thanks for the work you guys do.

**Comment by thestinger** [comment]
Please read the release notes:

https://grapheneos.org/releases#2021.05.16.04
