### ISSUE TITLE
enhancement: Implement a feature making you aware of an IMSI catcher/fake base transceiver stations being used against you.

### ISSUE THREAD

**Issue by Pauler221** [GrapheneOS/os-issue-tracker#561]
Are you planning to include features into GraheneOS like SnoopSnitch, Comsec and others alike provide? It'd be really convenient and useful be able to gather such information without having to root your device and therefore compromise security.

Probably a good amount of the audience GrapheneOS targets might be subjected to such an attack. I'd like to know your thoughts on this and if you're planning to add such a feature in the foreseeable future.

**Comment by thestinger** [comment]
We don't implement security theatre features. It doesn't protect users and would have a ton of false positives. It's covered well in the FAQ and usage guide already.

**Comment by thestinger** [comment]
Please read https://grapheneos.org/faq#cellular-tracking and https://grapheneos.org/usage#lte-only-mode.

**Comment by thestinger** [comment]
No malicious base station is is required to track users via the cellular network and/or intercept insecure carrier-based texts and calls. We're not going to provide a feature with a ton of false negatives and false positives offering no real security and substantially increasing attack surface via the modem debug mode. It's not what we do, sorry. Our documentation covers this well. Our goal is not providing people with frills giving them a false sense of security. GrapheneOS doesn't care about marketing and branding the OS as a product. It means we don't have a reason to do stuff like this just because people have the false impression that it's a good idea and therefore want to have it.

**Comment by Pauler221** [comment]
Sorry, should've checked out the FAQ more carefully. I know that GrapheneOS doesn't care about marketing I also wasn't implying that even though it might have sounded that way. Now my "false" impression has been more or less corrected by the FAQ even though accusing it of being totally false isn't right either since such a feature as you agreed does in fact inform you about IMSI catchers though it might give many false positives or negaitves.

**Comment by thestinger** [comment]
It gives a false sense of security even if it actually worked meaningfully because carrier-based calls/texts can still be monitored by carriers, law enforcement, employees with access to networks, companies with access to networks, etc. The cellular network does not provide secure transport.

**Comment by thestinger** [comment]
No IMSI catcher stuff needed to intercept carrier-based calls and texts.

**Comment by Pauler221** [comment]
Thank you for your time! I understand it now.

**Comment by indiDing** [comment]
Just one more question: Assuming that everything is as described above, why are IMSI catchers still being used?

**Comment by indiDing** [comment]
> Surveillance of everyone in a particular area without obtaining authorization for it particularly if they use carrier based calls/texts. IMSI catcher detectors do not really work well though.

OK, your explanation makes sense to me.

**Comment by indiDing** [comment]
> Also, what is it meant to accomplish? So, it tells you that your device was tricked into joining a network that's probably monitored just like the carrier-based one you usually use that's monitored. What then? You should avoid carrier-based calls either way.

That´s the thing!
