### ISSUE TITLE
keyboard doesn't automatically use the dark theme when the system theme is set to dark mode

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [GrapheneOS/os-issue-tracker#565]
- Dark theme inconsistency with keyboard. Should become dark too.

**Comment by thestinger** [comment]
It does support a dark theme but it has to be manually enabled. We're not going to be actively developing AOSP keyboard. We'll replace it with a better keyboard when an alternative has Direct Boot support and has been appropriately secured/hardened.

**Comment by hp8wvvvgnj6asjm7** [comment]
found

**Comment by thestinger** [comment]
See #579.
