### ISSUE TITLE
Screen recorder unable to capture device audio

### ISSUE THREAD

**Issue by myWorld010** [GrapheneOS/os-issue-tracker#566]
Screen recorder won't capture device audio even thought the toggle for that is enabled. Im on my pixel 4a with the the latest GrapheneOS version.

**Comment by thestinger** [comment]
Please try again on the latest June release.

**Comment by snprmnky** [comment]
On RQ3A.210605.005.2021.06.09.13: screen recording audio be it from microphone or device audio works as expected.

**Comment by Babber** [comment]
I am experiencing this apparently old issue on my Pixel 9 Pro with the latest GrapheneOS 2025011500. Mic sound gets recorded, but nothing if I select 'Device audio'. Just the same if it is recording one app only or the entire screen.
