### ISSUE TITLE
Can't Clear "Contacts" Storage

### ISSUE THREAD

**Issue by Jimmy-Py** [GrapheneOS/os-issue-tracker#567]
I have a mass duplication of my contacts, I would like to delete them and start fresh. I have attempted to delete all my contacts via: settings > apps & notifications > contacts > storage & cache: and clicking both "clear cache" and "clear storage." However, the contacts still appear in the app, even after restarting the phone. Any ideas?

**Comment by thestinger** [comment]
Contacts are stored in the profile data rather than that specific frontend to them. You need to delete them through the Contacts app or another app with contacts access granted to it.

**Comment by thestinger** [comment]
Try clearing the data for the Contacts Storage OS component instead of the user-facing frontend.

**Comment by Jimmy-Py** [comment]
Thank you. Searching for "Contact Storage" in the search by of "Settings" did the trick.
