### ISSUE TITLE
Remove pattern as an unlock method choice in UI

### ISSUE THREAD

**Issue by Wonderfall** [GrapheneOS/os-issue-tracker#570]
Humans are way too predictable when they choose their own pattern locks (especially), thus drastically reducing the entropy and reducing the security of their device. A secure element can't really compensate for a very poorly chosen pattern. Most common patterns can be guessed in a few attempts following a simple logic. Of course a PIN or a password can be poorly chosen too, but patterns are directly prone to "human" suggestion.

According to [this study](https://www.lancaster.ac.uk/staff/wangz3/publications/ndss_17.pdf), a significant amount of Android users are using patterns to protect their devices instead of a PIN. It also experimentally shows that this unlock method is inherently very vulnerable to shoulder surfing. Plenty of other studies have shown this in general.

The option to choose pattern as an unlock method should just be removed from the UI to discourage users from using it, as they should use PIN or password instead (they could ideally be provided with randomly generated ones and pick the one they want).

**Comment by Wonderfall** [comment]
Trying out a simple attempt at https://github.com/Wonderfall/platform_packages_apps_Settings/commit/ed5d3ce2884f0cb9820651072651257ab8ddadc6
Will run some more tests and then I'll open a PR if I'm sure it doesn't break anything.

I'll open a new issue later regarding the random generation of PIN/passwords.

**Comment by thestinger** [comment]
Probably also needs removal from SetupWizard. That could happen before doing this too.

**Comment by thestinger** [comment]
Probably also needs removal from SetupWizard. That could happen before removing it in the Settings app too.

**Comment by Wonderfall** [comment]
To me, SetupWizard seems to use the `com.android.settings.SETUP_LOCK_SCREEN` intent ([here](https://github.com/GrapheneOS/platform_packages_apps_SetupWizard/blob/69ef34821714e264642ccec2e9f9f6adb6951d71/src/org/lineageos/setupwizard/ScreenLockActivity.java#L70) and [there](https://github.com/GrapheneOS/platform_packages_apps_SetupWizard/blob/3dc738694545f2fb0fa04ef5c973352d86500bb6/src/org/lineageos/setupwizard/SetupWizardApp.java#L42)) which [brings us](https://github.com/GrapheneOS/platform_packages_apps_Settings/blob/9421b8fce2575b2c31adb2b77956cc55cb926f3d/AndroidManifest.xml#L1727) to [this code](https://github.com/GrapheneOS/platform_packages_apps_Settings/blob/9421b8fce2575b2c31adb2b77956cc55cb926f3d/src/com/android/settings/password/SetupChooseLockGeneric.java#L166) in Settings. The pattern lock should have the `HIDE_DISABLED` flag since it's [not considered as visible](https://github.com/GrapheneOS/platform_packages_apps_Settings/blob/9421b8fce2575b2c31adb2b77956cc55cb926f3d/src/com/android/settings/password/ChooseLockGeneric.java#L672-L674) thanks to the previous commit. Hope I didn't miss anything.

Need some more testing though.

**Comment by Zanthed** [comment]
We're a production security and privacy focused OS. Read the paper posted that shows the major insecurities about pattern locks. We're not a random custom OS you find off of XDA. There is no regression.

We're not adding it back.

**Comment by Wonderfall** [comment]
> So the overall effect is a regression - there is now no unlock screen security in place at all, because using a PIN is indeed that much more cumbersome.

As you guessed it, the swipe to unlock isn't meant for security. It wasn't hidden (it can be done easily) because it's a sensible choice for not having a secure primary unlock method, which is quite clear. I agree this isn't a common use case but making this setting hidden could have implications, meanwhile pattern is easily replaced by something better.

The pattern option, on the other hand, is indeed quite misleading because it aims to be a "secure" primary unlock method, but fails terribly at doing so. And I personally don't see how a 4-6 digits PIN (backed by Titan M) is that much cumbersome, and as long as they're randomly generated, they're that much stronger over 99% patterns.

Respectfully, I still don't see the change as a regression. In my experience seeing people reacting to the change, they are now using a far more efficient unlock method.

> Giving a warning / confirmation on selecting pattern unlock method, but still allowing it, would have been much nicer.

It would involve more code to maintain for something we would recommend users not to use anyway. In the long term it would be nice to have an [informative UI](https://github.com/GrapheneOS/os-issue-tracker/issues/599) to help users to choose a secure unlock method.

Bear in mind I'm not a project member so I'm not speaking on behalf of the project, but this is my opinion since I suggested the change. I didn't want this change to bother people, but to help them in the long run.

**Comment by thestinger** [comment]
That just tells you if you're using a lock method at all (not swipe or none).

**Comment by Wonderfall** [comment]
@heyheyhello It's been almost a year since the change was made and we haven't noticed too many users complaining about it, to be honest. Sure, some wondered why this option disappeared, as they had been using pattern for a long time. Generally, they were understanding enough and at the end of the day, most of them opted for a much more secure screen lock method. The secure element allows users to choose relatively simple PIN codes without sacrificing convenience at the cost of security.

Let me reiterate in other words: the pattern lock method would not have been replaced if there wasn't an alternative at least as secure and as convenient.

GrapheneOS is a project that aims at improving security and privacy **for everyone**, and therefore also cares about convenience and freedom (I often like to reuse the concept of compliance from pharmacology to explain that). But at the same time, you can't get unconditional freedom and still claim you want security. You coud make the same argument of "protecting people from themselves is a slippery slope" and ask for root or anything else in the name of freedom, which ironically happens to be a slippery slope. Compromises can be found, reasonable and balanced.
