### ISSUE TITLE
Unable to connect to internet after various time of innactivity

### ISSUE THREAD

**Issue by amirmamaghani** [GrapheneOS/os-issue-tracker#571]
Hardware: Pixel 4XL
Issue: Unable to connect to the internet (wifi, cellular) after upgrade 2021.06.08.06.

After my phone is inactive, after some time it suddenly stops network communication and I have to put my phone into flight mode and back to connect.

**Comment by thestinger** [comment]
Sounds like the result of a device manager app or something else you have configured, not an OS issue.

**Comment by thestinger** [comment]
You should get support in the Matrix room. I don't think this is an OS issue, especially without further information indicating it.

**Comment by amirmamaghani** [comment]
After further investigation I found out that it was caused by ProtonVPN app. after updating the app, everything works fine.
