### ISSUE TITLE
fix for google camera >=7.6

### ISSUE THREAD

**Issue by zxyz** [GrapheneOS/os-issue-tracker#572]
Hello,
on my Pixel 3a recent gcam versions are not starting anymore.  According to Lukas, the dev of gcam-service-provider, this can be easily fixed: https://github.com/lukaspieper/Gcam-Services-Provider/issues/22#issuecomment-814239882

Getting recent gcam versions running would be awesome, the responsiveness of OpenCamera on my pixel 3a is really bad.

Thanks!

**Comment by IT-Exilion** [comment]
Google has changed something in latest Gcams, using for now older one

**Comment by innir** [comment]
I doubt, it will be implemented but I'd really love it ... that's how CalyxOS handles it: https://gitlab.com/CalyxOS/device_google_sunfish/-/blob/android11-qpr1/the_experiences.xml

**Comment by thestinger** [comment]
@innir Projects behaving maliciously towards GrapheneOS and the developers including engaging in bullying/harassment are off-topic for our issue tracker and chat rooms.

**Comment by flawedworld** [comment]
To note, such a configuration would should be device specific, each Pixel device exposes different "Google" features on the stock OS.

**Comment by innir** [comment]
I created a pull request for Pixel 4a (as it's the one I can test with) to add the set of PIXEL_*_EXPERIENCE features Google uses to identify their Pixel devices - and maybe other apps also use them to identify Pixel devices.

As Google describes these features as "This is meant to be the canonical feature identifying YEAR and newer Pixel devices." I think it's legit to include them in GrapheneOS as well.

**Comment by Zanthed** [comment]
GCam has been tested by someone on GrapheneOS with the latest June 20th beta and reports GCam working fine now with GCam-Services-Provider:
https://github.com/lukaspieper/Gcam-Services-Provider/issues/22#issuecomment-868195290

**Comment by thestinger** [comment]
If there's a missing library or something like that people can make a new pull request for it. Keep in mind we cannot explicitly support running Google Camera as it can depend more and more on Play services, etc.
