### ISSUE TITLE
Local network discovery / Spotify Connect / Localhost?

### ISSUE THREAD

**Issue by IT-Exilion** [GrapheneOS/os-issue-tracker#573]
Not an issue of GrapheneOS, but more like a question.
Since i using GrapheneOS (not sure mabye it was in LOS as well) in Spotify app i can not find my wireless speakers (Yamaha, tried friends Sonos as well), thought i misconfigured my nework on router, but today found an old samsung phone with stock OS and it has no problems to find my local devices, tried on pixel 4 to instal stock rom, there it works as well. 
Maybe somebody can make some diggin if it has something to do with proprietary Google/Spotify services or maybe it is related to Graphene net hardening?

Upd 1. Tried it on CalyxOS with microG, there is same problem so it probably not related to google services 
Upd 2. Found a thread on AdAway that some people have similar problems becouse of host list, can somebody write how is hosts list configured on GrapheneOS or AOSP?
https://github.com/AdAway/AdAway/issues/1009#issuecomment-388294432

Thanks!

**Comment by thestinger** [comment]
It's the same as the stock OS on AOSP and GrapheneOS. In general, AOSP is the same as the stock OS except for the additional bundled apps/components, overlays, etc.

```
127.0.0.1       localhost
::1             ip6-localhost
```

**Comment by thestinger** [comment]
Does not appear to be a GrapheneOS issue. Likely an app bug. Not something we can address. You need to report app bugs to app developers. We don't do any relevant hardening that would impact this kind of thing. The Network toggle and proper MAC randomization, DHCP anonymity and IP address anonymity for Wi-Fi are the only related features and they wouldn't impact this.

**Comment by thestinger** [comment]
Unless you have evidence of this being a GrapheneOS issue, it has to be assumed that it's an app issue which may be tied to them using Play services. microG is a very incomplete and broken implementation of Play services. It's not a good way to test if it's because an app uses Play services.

**Comment by IT-Exilion** [comment]
You right, found out it has nothing to do with GrapheneOS, but Spotify itself, it doesn't scan and map UPNP devices properly, most of problems with this app are not solved by Spotify, so i found a workaround, maybe it will help somebody.

On F-Droid there are several open source UPNP scanner/casting apps like ControlDLNA or Yaacc that can properly find UPNP devices and then they are appearing in Spotify app (as local devices as expected)

**Comment by mateMathieu** [comment]
Installing Control DLNA worked perfectly @IT-Exilion 
Great and simple solution to fix the local discovery of devices in Spotify client on Graphene OS.

**Comment by thestinger** [comment]
GrapheneOS has the new connectivity module now via Android 13.

**Comment by thestinger** [comment]
GrapheneOS has the new connectivity module now via Android 13 which makes this stuff easier for apps so I don't know why they wouldn't properly support it now.

**Comment by mateMathieu** [comment]
After some test, it happens that it works only if you use ControlDLNA before.
So that is a poor fix.
