### ISSUE TITLE
GrapheneOs/Location and Network crash

### ISSUE THREAD

**Issue by DrDro94** [GrapheneOS/os-issue-tracker#574]
Hi,
I have a pixel 5 and I flash Graphene Os. When I try to use the geo-location my cells network crash and every app can't track satellites or track my position. Every authorisation are enable.
I use a VPN (surfshark) but I don't  @overwrite my position.
I upload a screen video of the problem. If you need any other information I'm here.
Thank you 

https://www.mediafire.com/file/v86w3pv3ykiimju/screen-20210612-181249.mp4/file

**Comment by thestinger** [comment]
There isn't a good reason to think that this is a GrapheneOS issue. It's likely either an app bug or you have something broken installed like microG interfering with it. You should get support on the Matrix room first. This isn't a good place to figure out what's wrong. It looks like you're using a version of OsmAnd from the Play Store.
