### ISSUE TITLE
Wiping clipboard after a specific period of time

### ISSUE THREAD

**Issue by whiteeagle3** [GrapheneOS/os-issue-tracker#578]
clipboard timeout alongside the already existing restriction that only the keyboard and the focused app can access the clipboard.

say: I copy my password to insert it in the browser. Later, I opened a third app to do something else, which will have access to the clipboard, so this option might limit the trust in the focused apps the user opened later after copying to and pasting something from the clipboard.

**Comment by thestinger** [comment]
This doesn't belong in the core OS but rather as a keyboard feature. We're not going to be developing these kinds of features for AOSP keyboard since we intend to move away from it. You should propose it for FlorisBoard.

**Comment by thestinger** [comment]
> I copy my password to insert it in the browser.

A password manager should be using the autofill API, not the clipboard.

**Comment by thestinger** [comment]
See https://github.com/GrapheneOS/os-issue-tracker/issues/579. Please file feature requests with FlorisBoard.
