### ISSUE TITLE
replace AOSP keyboard with FlorisBoard when it has Direct Boot support and more baseline features

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/os-issue-tracker#579]
Please file feature requests for FlorisBoard upstream, not here.

**Comment by MarkusZoppelt** [comment]
More features could mean a larger attack surface. Sure, it may be minor, but the AOSP keyboard has a much longer track record of being secure/tested/practical, etc.

Personally, I would prefer the option to keep the AOSP keyboard. It runs on every Android device and is therefore battle-tested. If users want more features from a keyboard, they have the option to install an alternative.

**Comment by thestinger** [comment]
@MarkusZoppelt You're mixing up AOSP keyboard with Google's Gboard app used on most Android devices shipping with Play services and the Play Store. AOSP keyboard isn't a variant of Gboard and isn't being actively developed. It only gets bare minimum maintenance and security updates and is a sample app that's meant to be replaced as part of any serious variant of Android. AOSP keyboard is slowly rotting away. Language support isn't being expanded/improved/maintained, the spell checking lists are frozen in time and increasingly obsolete, it hasn't gotten any of the newer generation emoji support for years and is increasingly outdated when it comes to the feature set. It's missing features that are now common such as Incognito support (we disable learning by default to work around this), swiping on space bar to move the cursor, glide typing and other features now considered part of the basis. Sticking with outdated code that's not being maintained is definitely not good for security, especially since it has a bunch of code unnecessary written in C++ rather than Kotlin/Java.

**Comment by thestinger** [comment]
We don't want to have all this C++ code exposed as attack surface to apps from the keyboard. Nearly all the relevant added features such as glide typing don't expose attack surface in any meaningful way. Attack surface would be reduced by getting rid of C++ code and instead having almost entirely Kotlin/Java code that's memory and type safe.

**Comment by MarkusZoppelt** [comment]
> [..] AOSP keyboard isn't being actively developed. It only gets bare minimum maintenance and security updates and is a sample app that's meant to be replaced as part of any serious variant of Android. AOSP keyboard is slowly rotting away. Language support isn't being expanded/improved/maintained, the spell checking lists are frozen in time and increasingly obsolete, it hasn't gotten any of the newer generation emoji support for years and is increasingly outdated when it comes to the feature set. [..]

I wasn't aware of the state of the AOSP keyboard then.

Thanks for clarifying, I do support the use of memory safe languages.

**Comment by Forbo** [comment]
It appears the Florisboard now has direct boot support. Are there any other specific features that were blocking the replacement of the AOSP keyboard?

**Comment by thestinger** [comment]
We want it to be a near direct upgrade in every way from AOSP keyboard before shipping it so people aren't unhappy when we remove AOSP keyboard.

**Comment by thestinger** [comment]
The reason we implemented Direct Boot support for it is because I doubt they would have done it otherwise and it wouldn't have ever been a viable replacement for the built-in keyboard app, only as a user installed supplementary one.

**Comment by Zanthed** [comment]
This is no longer happening due to Florisboard using a LGPLv3 spellcheck library and we have intended for Florisboard to replace AOSP spellcheck as well. We cannot just take out the library because 80% of the reason we want to switch is to fix all the bugs with AOSP spellcheck.

Unless there's an actionable and doable solution to the library licencing issue, there are no more plans to integrate Florisboard, we will not spend further resources on it, and it is a real shame we found this out later after we contributed things like Direct Boot ourselves.

**Comment by heuwerk** [comment]
@Zanthed May I ask, what the Issues are with the LGPL License for spell checking?

I would really like to see the AOSP keyboard beeing replaced with Floris Board by default, but at least I could install it manually.

**Comment by flawedworld** [comment]
GrapheneOS cannot include strong copyleft licenced code.

**Comment by thestinger** [comment]
GPLv3 and LGPLv3 code won't be included in GrapheneOS.

GPL2-only code is fine. GPL2 or later code may become GPLv3 and we don't want to include it.

**Comment by thestinger** [comment]
Library they're using is LGPLv3 so unless there's an alternative to that it won't be included in GrapheneOS. A major part of the reason we were planning to include FlorisBoard was the licensing but that ruins it. We contributed Direct Boot support to FlorisBoard because we wanted to include it, but now we realize we can't, at least without that changing.

**Comment by patrickgold** [comment]
Project lead developer/maintainer of FlorisBoard here.

A user of mine has just now brought the library license issue to my attention. My stance to LGPL/GPL-licensed libraries is normally also to make a circle around them, but for Nuspell it seems like I made an exception. Mainly because there wasn't any alternative which cross-compiled to Android in any way, and I think I considered this LPGL/Apache 2.0 inclusion a year ago to be a license gray area.

I am currently at the very beginning of the 0.4 milestone, where I am (re-)implementing word suggestions and inline autocorrect. My initial plans were not to touch the current spell checker at first and continue using Nuspell, however it that's the only blocking reason for your project to not include FlorisBoard, then I am more than open to completely get rid of Nuspell and integrate spell check into the same system as autocorrect. With this change in mind please just let me know your intentions so I can adapt the 0.4 milestone a bit.

**Comment by thestinger** [comment]
Also, while we don't plan to make a locked down device ourselves, we do see why vendors would want to have an immutable root of trust from hardware instead of having a secure element able to store a public key like Pixels with a notice on boot when that's being used instead of the immutable root of trust. It's a lot easier to implement the immutable root of trust securely. This isn't really a major part of the overall attack surface for verified boot but it's logical for a company which doesn't care about using different firmware / different OS to not implement it and we want them to be able to use GrapheneOS and easily work with us without having to worry about ending up with code that would be a legal issue for them.

**Comment by patrickgold** [comment]
> This is probably the only issue blocking us from using it beyond doing an audit of all the exposed interfaces and making sure everything is fine.

Tbh I think doing an audit to check all dependencies licenses would be the best way to ensure full license compliance. If we find some other area besides Nuspell which also has this problem this may be more effort at first to replace that lib, but if the project then is fully license compliant this is absolutely worth the effort. (Especially as I am just a human and not a license expert, so I may have missed something too).

> we want them to be able to use GrapheneOS and easily work with us without having to worry about ending up with code that would be a legal issue for them.

Fully understand the reasoning!

> There might be a few features missing from FlorisBoard that our users expect but what we can do is ship it alongside the default AOSP Keyboard as a bundled option and figure out what people think is missing

There are definitely some key features missing (summary of most requested features by my users):
- Word suggestions+inline autocorrect: high priority and by far most requested, thus I am now beginning with the development of it (0.4 milestone). This is a massive area so I will sit a while at this implementation.
- Emoji suggestions/search: also highly requested, although I just don't had the time to fully integrate this yet (some preps have been done in this area though)
- Local voice input (or at least better integration of already installed voice IMEs/services)
- Smartbar (top row) customization of the quick action order
- A way for the community to share themes, keyboards, etc. via a community repo

But yeah at the beginning I think the best way is to ship both AOSP keyboard and FlorisBoard and then also see what your user's needs are.

**Comment by dkwo** [comment]
Could this issue be potentially reopened, to track 0.4 release? If I understand correctly, they got rid of Nuspell in v0.4.0-alpha01 (release notes: Remove Nuspell spell check implementation for now). I suspect having this available, as an alternative to AOSP keyboard, even if it's in early beta, could be attractive to some.
