### ISSUE TITLE
design and implement a real boot animation instead of the logo mask

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/os-issue-tracker#58]

**Comment by oumno** [comment]
![GrapheneOS_Boot](https://user-images.githubusercontent.com/53978854/63713456-37ff3100-c82f-11e9-9321-30d803469f11.gif)

**Comment by renlord** [comment]
@oumno can you submit a PR for this? it looks good.

**Comment by oumno** [comment]
> @oumno can you submit a PR for this? it looks good.

https://github.com/GrapheneOS/os_issue_tracker/pull/174

**Comment by thestinger** [comment]
This is not really necessary and we don't need to have an issue open about it.
