### ISSUE TITLE
Option to not allow user switch from lock screen

### ISSUE THREAD

**Issue by pionsel435560** [GrapheneOS/os-issue-tracker#581]
I would like access to other users not accessible from lock screen to prevent others from seeing that I have profiles while also letting me still switch profiles when logged in.

**Comment by thestinger** [comment]
I don't think we want to implement this. It would still be possible to determine it other ways.

**Comment by thestinger** [comment]
For now, I'm closing this, since I don't think this can be turned into a feature meeting our standards.
