### ISSUE TITLE
ability to disable vpn for some apps

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [GrapheneOS/os-issue-tracker#583]
There is a big issue with NewPipe that hasn't been fixed for months. VPN users can't use their app anymore. So what was their proposed solution? disable VPN. I can't disable VPN system wide only because one app doesn't like it.

https://github.com/TeamNewPipe/NewPipe/issues/5977

Now using AFWall back in the days this was possible. Graphene has none of these features for firewall control. Reasons: " oh you don't use a VPN like that, and you don't use orbot at the same time ".. some people do. Why do you want to dictate how people use their phone? 

I would like to see finer grained firewall controls with port settings and so on. I don't think this OS is used by noobs who don't know about this stuff and they don't want to be dictated. I know the answer is going to be some excuse about how you're not supposed to do things a certain way and how much of a security hazard whatever feature is.

I know this is more of an issue with newpipe, but it came to my mind again how much I miss having AFWall.

**Comment by thestinger** [comment]
VPN apps already have the option to support bypassing the VPN on a case-by-case basis for apps. If the VPN app you're using doesn't expose this OS feature, ask them to do it.

**Comment by thestinger** [comment]
> Why do you want to dictate how people use their phone?

We don't, and the example you use (Orbot) already supports the OS feature of bypassing it on a case-by-case basis.

I don't know what else you want to be added. The feature you want is already part of AOSP.

**Comment by thestinger** [comment]
> I would like to see finer grained firewall controls with port settings and so on. I don't think this OS is used by noobs who don't know about this stuff and they don't want to be dictated. I know the answer is going to be some excuse about how you're not supposed to do things a certain way and how much of a security hazard whatever feature is.

The feature you want is already implemented in a proper way rather than via hacks which do not work properly. Use the existing feature.

Your negative attitude and attacks on the project will result in being banned from the issue tracker if it continues elsewhere. This is the only warning you'll get.
