### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Githuborian** [GrapheneOS/os-issue-tracker#584]
Phone used: Google Pixel 3a.
Latest updates.
Language: Dutch/Netherlands

Bugs:
- No notifications (for a long time now), just sometimes, when screen is off, meaning notifications from messages (sms), only show up when screen is activated and logged in. Settings are all good.
- When camera is active and filming and then turning just slightly filming goes off randomly. (seems unstable)
- When camera is on sometimes it takes a couple of pictures which is weird.
- Unable to send MMS messages.
- Missed calls tab is gone.
- Notes app keeps closing the note and goes back to the main screen of all notes when it is closed or in the background. never remains active on the note selected, makes it hard to do grocery shopping.

And i am missing a timer, stopwatch, compass and all.

Cheers.

**Comment by thestinger** [comment]
Please use the Matrix rooms for support rather than the issue tracker.

**Comment by thestinger** [comment]
It's not appropriate to report multiple issues in one report or to report things that are neither features requests or bugs. Issues that are already filed in the tracker shouldn't be filed again. It sounds like most of what you need is having your questions answered and help with resolving carrier issues not caused by the OS. You should use the Matrix rooms for that, not the issue tracker.

**Comment by Githuborian** [comment]
It has nothing to do with the carrier because they are send and received but not shown (notified) so it is OS causing this.

Link?

**Comment by thestinger** [comment]
https://grapheneos.org/contact#community

**Comment by thestinger** [comment]
@Githuborian If you mean SMS notifications in a *secondary profile*, there are known AOSP limitations for that case also impacting the stock OS. It works fine in the primary profile.

**Comment by Githuborian** [comment]
What do you mean with primary and secondary profile?

**Comment by thestinger** [comment]
The main user account vs. secondary user accounts.

**Comment by Githuborian** [comment]
Ah, i only have one user account.

But yeah, SMS  notifications do not show up on main (only) profile. just sometimes but most of the time they don' t and as soon as i touch my screen right away a notification is shown. Have it only with grapheneOS.

**Comment by Githuborian** [comment]
After switching to Beta releases and updating i am still experiencing these issues.

**Comment by Githuborian** [comment]
Why does it say that this is closed?

**Comment by thestinger** [comment]
They're support questions not issues in the OS.

**Comment by thestinger** [comment]
To file an issue in the tracker, you need to confirm that it's not caused by something else like your carrier. Each issue needs to be filed separately with proper details and clear instructions on what triggers it. Please use the Matrix room for support.

**Comment by Githuborian** [comment]
Changed the sim card, different carrier, same problem.
Matrix room?

**Comment by Githuborian** [comment]
> They're support questions not issues in the OS.

These are bugs on the OS and not questions.

**Comment by thestinger** [comment]
These aren't bugs.

**Comment by thestinger** [comment]
You're reporting carrier issues and misunderstandings. You seem to think GrapheneOS is a modification of the stock OS and it isn't. I don't know why you're reporting stuff like not having a compass app. If you want an app you can install it. It seems you haven't looked in the Clock app.

Please use the Matrix rooms for support.

https://grapheneos.org/contact#community
