### ISSUE TITLE
Add Feature to Disable Visible PIN Touch Points

### ISSUE THREAD

**Issue by ghost** [GrapheneOS/os-issue-tracker#588]
It is not possible to disable the visibility of which numbers the user is tapping when entering a PIN code. I have had a PIN code compromised due to this. It should be possible to disable the PIN touch visibility.

**Comment by flawedworld** [comment]
We will just wait for Android 14 to implement this.

**Comment by flawedworld** [comment]
@downeymj  We do, if it's in Android 13 QPR3 when it actually comes out, and if it's in a usable state then, then users will get it then.
