### ISSUE TITLE
Investigate enabling ASHA support

### ISSUE THREAD

**Issue by flawedworld** [GrapheneOS/os-issue-tracker#589]
https://source.android.com/devices/bluetooth/asha

ASHA is a Google standard for hearing aids over bluetooth. Investigate enabling this functionality to help improve accessibility for deaf and hard of hearing individuals.

Currently this appears to be disabled by default in AOSP here:
https://github.com/GrapheneOS/platform_frameworks_base/blob/079066126074716767d7454c1c73910cc3e5d5ed/core/res/res/values/config.xml#L133

**Comment by flawedworld** [comment]
cc @Veganizer

**Comment by Veganizer** [comment]
Thank you! This is an absolutely must-have for people with a handicap of hearing. It is needed to phone with someone or to hear music etc.

**Comment by flawedworld** [comment]
https://support.google.com/pixelphone/answer/9393002 this feature should be enabled for all OS builds.

**Comment by thestinger** [comment]
It's not enabled by default in the global configuration since it depends on hardware support.

It's already enabled in AOSP for each of the supported devices in the device repositories. I think it's already supported.

**Comment by thestinger** [comment]
Can file an issue report if it's not working properly. I don't know if any of this depends on Play services. It seems like it's simply an AOSP feature.
