### ISSUE TITLE
PreBuilt APK

### ISSUE THREAD

**Issue by whois89** [GrapheneOS/os-issue-tracker#592]
Performing the following step after build the code then generating release,  I have signed the apk with release key

java -jar /home/grasignapk.jar platform.x509.pem platform.pk8 unsigned.apk signed.apk

1. I have create a directory in external with name "MyTestApk".
2. Create Another Directory "external\MyTestApk\prebuilt" and put MyTestApk.apk there
3. Create Android.mk file, which I have attached.
[Android.txt](https://github.com/GrapheneOS/os-issue-tracker/files/6808525/Android.txt).
4. Then Add entry to "build/target/product/handheld_product.mk" with Directory Name
5. Then Modify the "build/make/core/app_prebuilt_internal.mk" file to print out the name of all including prebuilt apks, its showing the name of my apks as well, but unable to find the apk file from release or out directory
6. ![apks](https://user-images.githubusercontent.com/69184375/125446274-5396df7a-8bb6-49ab-a245-d3d2a1a1ac13.JPG)

**Comment by thestinger** [comment]
The issue tracker isn't used for support. Please use the chat rooms: https://grapheneos.org/contact#community.

**Comment by ZeeshanSultan** [comment]
Facing the same issue, the community wasn't able to respond to this query and also i believe there should be some documentation for having prebuilt packages during build.

Willing to pay support for this as well.

**Comment by thestinger** [comment]
The existing prebuilt packages are usable as documentation.
