### ISSUE TITLE
USE THIS FOLDER button missing in Files app

### ISSUE THREAD

**Issue by shompoe** [GrapheneOS/os-issue-tracker#593]
When an app (any app) launches the Files app to select a location for saving files to, there should be (and on Stock Android 11 OS there is) immediately a button at the bottom "USE THIS FOLDER" to pick the current default folder. On GrapheneOS that button is initially missing, and displays only after you navigate away from the default folder. So if you want to select the default folder you would have to come out of it and go back in first.

**Comment by thestinger** [comment]
By default folder which directory are you referring to? Are you sure this is actually any different?

**Comment by shompoe** [comment]
By default folder I mean whatever folder the Files app starts in when it loads up.

I have Pixel 4a and so does my wife. Mine is GrapheneOS and hers is stock Android. Her phone does not exhibit this problem.

--- 
Mark Desrousseaux



17 Jul 2021, 00:21 by ***@***.***:

**Comment by S3NTYN3L** [comment]
I also have this issue on my 4a.

**Comment by shompoe** [comment]
This issue seems to be resolved with the update to AOSP 12
