### ISSUE TITLE
[Pixel 4a] 4G only mode not recovering from loss of signal

### ISSUE THREAD

**Issue by Karafare** [GrapheneOS/os-issue-tracker#594]
I noticed after activating the 4G only mode that the phone is not recovering after a loss of signal, e.g. due to it being in a basement for a while. The phone just looses the connection (as expected for a basement or similar) but never manages to reconnect to the mobile network afterwards, even if it is in an area where it usually has perfect coverage.
Switching to the normal 4G mode enables the phone to instantly reconnect to the network. 

The issue does not appear in the normal 4G mode and the 4G only mode works flawlessly unless the phone looses the signal.

Conditions:
- Phone: Pixel 4a
- Operator: Vodafone DE (SIM card and contract from 2020 so I do not expect any issues there. VF has shut off it's 3G infrastructure in Germany at the beginning of the month; I couldn't test this feature before then however as I didn't have GrapheneOS installed by then)
- GrapheneOS: RQ3A.210705.001.2021.07.07.19 (issue was also present in the previous release)

**Comment by thestinger** [comment]
This sounds like a carrier side issue and I don't think it's anything we can address ourselves.

**Comment by thestinger** [comment]
Even if they supposedly shut off 3G, it sounds like they still have infrastructure using it that's required in some cases.

**Comment by Karafare** [comment]
Apparently they plan to reuse some 3G equipment for 4G services on the same frequencies, but this was just sidenote anyways (to underline the fact that 4G is the norm with the carrier now). I wouldn't expect this to impact 4G only mode as that doesn't use 3G services.
It might be the case that the initial connection with the cell tower is done using 2G, which would however somewhat defeat the security architecture (if one can call it that) of 4G.
