### ISSUE TITLE
Network and sensors permissions should be disabled by default

### ISSUE THREAD

**Issue by mariomadproductions** [GrapheneOS/os-issue-tracker#596]
For some reason, the network and sensors permissions seem to be enabled by default on all/most apps. Shouldn't they be disabled by default?

**Comment by thestinger** [comment]
It has to be that way since GrapheneOS adds the permissions.

**Comment by mariomadproductions** [comment]
Not sure what you mean.

**Comment by thestinger** [comment]
GrapheneOS adds the Network and Sensors permissions. Apps don't check if they have them at runtime and don't know how to request them. That's why they're enabled by default.

**Comment by thestinger** [comment]
https://github.com/GrapheneOS/os-issue-tracker/issues/563, https://github.com/GrapheneOS/os-issue-tracker/issues/560 and https://github.com/GrapheneOS/os-issue-tracker/issues/597 are the planned improvements. Treating them as normal runtime permissions that are disabled by default is not available as a serious option to consider. It would ruin the usability of the OS and would severely break compatibility so that we would fail most of the CTS/CDD and wouldn't have those unit / integration tests available anymore. A lot of the point behind GrapheneOS is Android app compatibility.

**Comment by mariomadproductions** [comment]
Yeah I guess it makes sense to have it on by default for usability. However, if you install an app, but don't launch it yet, then disable its network permission, can the app use the moment between installing the app and disabling the network permission to connect to the network (for example)?

Although couldn't pseudo-permission request system work by feeding the app dummy data by default (no internet, no gyro movement, that sort of thing), and then detecting when it tries to read it (to bring up the prompt). But I guess that would be complicated to implement.

**Comment by thestinger** [comment]
> Although couldn't pseudo-permission request system work by feeding the app dummy data by default (no internet, no gyro movement, that sort of thing), and then detecting when it tries to read it (to bring up the prompt). But I guess that would be complicated to implement.

This can't actually work reliably and the Sensors permission already gives empty data rather than an exception. Making the INTERNET permission friendlier to apps with it denied is #560 above.

**Comment by thestinger** [comment]
> Yeah I guess it makes sense to have it on by default for usability. However, if you install an app, but don't launch it yet, then disable its network permission, can the app use the moment between installing the app and disabling the network permission to connect to the network (for example)?

No, they can't, but see #562 above which needs to be changed for Network but not for Sensors.

**Comment by thestinger** [comment]
You can see that little progress is made on most features without a contributor taking an interest and working on it. Asking for more features doesn't have much purpose anyway. Only working on them does. Those 3 things need to be done before anything else in this area can even be considered.
