### ISSUE TITLE
Sandboxed Play Store hangs after app is installed

### ISSUE THREAD

**Issue by slashmach1** [GrapheneOS/os-issue-tracker#601]
First off the Sandboxed play implementation is a huge QOL improvement, spectacular!  I am able to add my Google account and install apps but for whatever reason it seems to hang after the app is installed preventing Play Store from installing multiple apps in succession until my device is rebooted or I manually force close Google Play Store.  

My Device is a Pixel 4a.  Running latest Beta Build with Sandbox Implementation RQ3A.210705.001.2021.07.16.19

**Comment by thestinger** [comment]
This is explained at https://grapheneos.org/usage#sandboxed-play-services. You should just install apps with something else. Play Store uses unattended app install permissions to install / update apps, which it doesn't have. We started on shims to coerce it into using the dialog for requesting a user to install apps, but that's not done. It's not necessarily something we're going to provide.

**Comment by slashmach1** [comment]
Understood, I thought it applied to updates for already installed apps.  Not new application installs.  I misread it.

**Comment by thestinger** [comment]
It's somewhat broken in both cases. It can be forced to work for both with force stop. It's more annoying for updates.
