### ISSUE TITLE
Sandboxed Play Store hangs at "Verifying data..." - No account input possible

### ISSUE THREAD

**Issue by 1989gironimo** [GrapheneOS/os-issue-tracker#602]
What is the current situation:
-> Running the experimental version RQ3A.210705.001.2021.07.16.19 on a Pixel 3a XL and followed this install guide: https://grapheneos.org/usage#sandboxed-play-services to install all three apps in the appropriate order and used SAI from F-Droid to install the Split APKs
-> I've confirmed, that all three apps have been installed successfully
-> I've already tried to reboot the smartphone, removed the app data of all three apps after my first try and tried again but both steps didn't solve this issue 
-> I've tried to give all requested (in Settings -> Apps) permissions one by one and tried again, but this didn't make a difference.

Description to reproduce:
- Install version above and the mentioned apps
- Start Play Store
- Click "Sign in" button shown on first screen
- See "Verifying data..." (translation from german, which says "Daten werden überprüft..." and a spinning circle, but no login field

As a sidenote (maybe this is important to know what happens here):
I've tried three apps after installing the Play Services. "Tier" or "Share Now" which are dependent on Play Services don't work but have different issues. The first hangs at trying to login (but no error message than before that Play Services are missing) and the second complains about missing Play Services (which are definitely installed, as I described before and verified before creating this issue.
My banking app "ING" (german version, they have different versions for each country) works now, it doesn't show a black screen anymore while trying to login, so the Play Services aren't recognized by every app.

I'll happily provide more input/data at request :)

**Comment by thestinger** [comment]
It's probably the missing shim fixed byhttps://github.com/GrapheneOS/platform_frameworks_base/commit/88897258ea0861e0b717fa8af36506c18521f64a. There's already a new release in the process of being internally tested for release to the Beta channel. You can temporarily remove the SIM to bypass the issue to sign in.

**Comment by 1989gironimo** [comment]
Thanks! After enabling all permissions and removing the SIM card it does indeed work!
