### ISSUE TITLE
Sandbox Play Services Contacts and Calendar Sync

### ISSUE THREAD

**Issue by slashmach1** [GrapheneOS/os-issue-tracker#603]
I found that adding a Google account and installing Google calendar and Contacts does not configure sync however if you install calendar and then re add the google account by adding a second Google account, calendar sync works within the sandbox implementation.  

Contacts requires a Google sync adapter APK which can be installed as a user app and granted contact permissions to permit Contacts sync using the same method.  Thought this could prove useful to anyone who is still very dependant on Google.

My Device is a Pixel 4a. Running latest Beta Build with Sandbox Implementation RQ3A.210705.001.2021.07.16.19

**Comment by thestinger** [comment]
Sounds like this is basically working as intended? Some things are going to start working significantly better with the upcoming release and with future releases in the next few weeks adding more shims so that more Play services APIs work properly.

**Comment by slashmach1** [comment]
It very much already works with a little finesse.  Definitely not an obvious path for those interested in Calendar/Contacts sync so I thought I would share.

**Comment by nunyabidnes** [comment]
@slashmach1 Can you provide details on the Google sync adapter APK and where to get it?

**Comment by slashmach1** [comment]
It's an additional APK that can either be exported from a stock Android image as it's generic or found on APKPure or any other APK mirror site but that's at your own discretion. 
 
https://www.apkmirror.com/apk/google-inc/google-calendar-sync/

**Comment by slashmach1** [comment]
@nunyabidnes I know there used to be one for contacts as well but that may not be necessary anymore with changes Google has made

**Comment by nunyabidnes** [comment]
I ended up installing DAVx and connecting it to my google account, and now my contacts are there.
