### ISSUE TITLE
Sandboxed Play Services don't provide a functional Maps API

### ISSUE THREAD

**Issue by 1989gironimo** [GrapheneOS/os-issue-tracker#604]
My situation and what I've done:
-> Running the beta buildversion RQ3A.210705.001.2021.07.19.18 on a Pixel 3a XL

-> Tried two different apps, Tier and Share Now, both of them are shared mobility providers.
Both apps rely on a functional maps API to see, where available vehicles are.

-> Installing Google Maps doesn't lead to a working maps API-dependent apps.

-> Rebooting and clearing app data of affected apps and/or Play Services doesn't change anything as well

Issue:
Tier doesn't load past the "Let's go" button right before logging in, Share Now lets you login but it complains in the main menu (where you normally see a map of available vehicles) that Play Services have to be installed to use this app.

My suspicion (because of my former use of microG in the past, which has a similar issue) is that the maps API is not available to these apps, despite installing the Play Services in the correct order and correct way, like described in the documentation on grapheneos.org.

I'll happily provide more info at request!

**Comment by thestinger** [comment]
The modern Maps API is a dynamite module:

https://grapheneos.org/usage#sandboxed-play-services

It will be available once we provide shims for dynamite modules to work in an unprivileged way rather than depending on custom SELinux MAC/MLS policy.

**Comment by 1989gironimo** [comment]
Thanks for the explanation, didn't know what falls under the term dynamite module, had to research them a little first. 

For interested folks it seems that other, for some at least, important parts of the Play Services like SafetyNet, AdMob and OCR functions are part of these modules as well.
