### ISSUE TITLE
?

### ISSUE THREAD

**Issue by Githuborian** [GrapheneOS/os-issue-tracker#605]
Confusion..

What defines as a bug?
What defines as a issue?
Where do i report a issue that is not a bug?
If the OS and not the carrier does a certain thing then why isn't it a bug but a issue?
Why do admins delete topics?
What where my troubles in that topic, i do not remember as i keep forgetting stuff..?

Not to shit on your scene here but for me right now the rumors seem true regarding the dev.
I'm coming here for assistance and do not understand a thing what was said or why and you delete the topic.
WTF?

If the OS is not functioning as it should then it is a bug on the OS.
Humbleness...

**Comment by thestinger** [comment]
You aren't reporting bugs in the OS. You're reporting issues with your carrier / lack of configuration changes for it along with your misunderstandings about GrapheneOS. You were told to use the Matrix rooms for support. The issue tracker is not a place to ask questions and get support. You were told that and yet you're still filing more issues.

> Why do admins delete topics?

Off-topic and rule-violating issues will be removed. This one is blatantly breaking the rules after it was explained.

> Not to shit on your scene here but for me right now the rumors seem true regarding the dev.

Well, now you're making it clear that you're a member of a malicious community raiding / trolling ours.

> If the OS is not functioning as it should then it is a bug on the OS.

That's not what it is happening. You have a strange idea of how the OS should function including bundling additional apps or splitting functionality out of the Clock app.

**Comment by thestinger** [comment]
This is going to be interpreted as a malicious raid if it continues and will result in a ban from the community. You've been told the rules and are deliberately breaking them now, and you're making attacks on the project/developers in a malicious way.
