### ISSUE TITLE
Quick tile security

### ISSUE THREAD

**Issue by neurer** [GrapheneOS/os-issue-tracker#609]
Triggering certain quick tiles requires an unlocked device. While I understand the reasoning behind the enhanced security, I've found myself constantly entering the pin to use quick tile functionality. May I kindly ask to evaluate the security implications of entering a pin vs. enabling Bluetooth/Wifi? Something like defaulting to enhanced quick tile security while also providing the option to revert to the default AOSP behavior may be a more balanced approach.

**Comment by thestinger** [comment]
Bluetooth / Wi-Fi substantially increase attack surface.

**Comment by thestinger** [comment]
There could be a toggle for this but it doesn't seem to bother many people and that makes it harder to maintain.

**Comment by neurer** [comment]
Thank you for your quick reply! Yes, a toggle would mitigate the issue. I suppose it's not an issue at all when using fingerprint unlocking. Which (is pure speculation on my part) may be why it hasn't come up yet.

**Comment by SB13X** [comment]
Speaking of toggles, would it be possible to add a Quick Setting Tile to toggle between cellular modes?

Tapping it changes between 3G-4G recommended/preferred?

I have to use 3G for the hotspot at certain locations lacking suitable 4G speed/coverage and keeping going into the settings can be tiresome. I'm managing as is and would appreciate it being low-priority.

**Comment by thestinger** [comment]
I don't really think we want to do that. 4G does still have coverage issues compared to 3G but that should be rapidly fading away especially with a lot of 3G networks approaching the point where they're going to be shut down / converted to 4G in the near future.

**Comment by thestinger** [comment]
Configuration for this is too complex and there are no plans for changes. I think the niche for using these toggles while locked is too small. We can't implement configuration for incredibly niche things. It's far too much to maintain and takes away from doing important things.
