### ISSUE TITLE
Recurrent Update Client Notification 

### ISSUE THREAD

**Issue by IIIJIII** [GrapheneOS/os-issue-tracker#610]
Since downloading the latest stable update to GrapheneOS I have been getting a silent notification every few hours from the Seamless Update Client saying
"Fully updated
Latest Stable channel release already installed."
There's nothing I'm doing to trigger this (that I know of)

**Comment by IIIJIII** [comment]
This is on a Pixel 5 on 2021.07.26.20 release

**Comment by TrashPandaCodingGarbage** [comment]
Same here on my Pixel 4a 5G

**Comment by thestinger** [comment]
This is included in the release notes:

https://grapheneos.org/releases#2021.07.26.20

You can turn it off if you don't want it. There's a dedicated release channel for the fully updated notifications.

**Comment by thestinger** [comment]
Many users don't understand that the update client is checking every 4 hours automatically and get concerned that they're out-of-date. We added this to make it much more accessible and transparent. It's a fully collapsed + hidden notification at the bottom which is probably also what you want to do with foreground services of apps you trust by configuring them to be collapsed.

**Comment by IIIJIII** [comment]
I see the reasoning, thank you

**Comment by Saroumane** [comment]
So we just have to turn off the one highlighted below, right ?

![signal-2021-08-01-153057](https://user-images.githubusercontent.com/22261137/127772780-7bbd7a97-a936-40aa-90e9-5692e60ae913.png)

**Comment by thestinger** [comment]
If you don't want this silent + collapsed notification, yes. It's going to be quite useful starting in the next release with a timestamp on it showing when it last checked. In theory we could move it to the settings UI but that would involve more work. I'd suggest just not expecting to check and clear out silent notifications. Notice it's not part of the actual Notifications section of the UI, has no status icon, isn't displayed on lockscreen, etc. It's minimum importance status information.
