### ISSUE TITLE
no longer is able to check for latest update

### ISSUE THREAD

**Issue by modernNeo** [GrapheneOS/os-issue-tracker#616]
2 issues:

1. since the latest update, I keep getting this notification
![signal-2021-08-06-073353](https://user-images.githubusercontent.com/14242088/128526813-907c61d8-2c40-43cc-ac89-14a866c88987.png)

2. I can unravel that notification so that I can read what is past the "The u....."

my build number is RQ3A.210805.001.A1.2021.08.03.03

**Comment by thestinger** [comment]
How long has that been happening? We're currently migrating to self-hosted DNS servers for grapheneos.org as we previously did for our other domains. We waited for the old grapheneo.org DS record (DNSSEC) from the .org DNS servers to expire before switching. There should be no problems unless your DNS provider has a broken, non-standards compliant implementation. It will resolve itself soon if that's the problem when it expires from their broken server.

**Comment by modernNeo** [comment]
Thanks for the response. I disabled ExpressVPN and it started working. so I guess I will let them know about that.

But, any response to 
> I can't unravel that notification so that I can read what is past the "The u....."

?

**Comment by thestinger** [comment]
We're aware that the full error messages currently aren't displayed due to how the notifications are configured. It's something we plan on improving in the future.

**Comment by modernNeo** [comment]
is there an github issue that tracks that configuration issue so I can follow that issue to be aware of the progress of the resolution?

**Comment by thestinger** [comment]
There wasn't one but I filed https://github.com/GrapheneOS/platform_packages_apps_Updater/issues/40 about it.

**Comment by thestinger** [comment]
Can you try connecting to the VPN again? It should really be working fine without hitting any errors from DNS.

**Comment by modernNeo** [comment]
> There wasn't one but I filed [GrapheneOS/platform_packages_apps_Updater#40](https://github.com/GrapheneOS/platform_packages_apps_Updater/issues/40) about it.

Cool. thanks

> Can you try connecting to the VPN again? It should really be working fine without hitting any errors from DNS.

yea, it did seem to work again on the same server after a reboot. guess the cache got cleared? idk.
