### ISSUE TITLE
Can't receive sms from individuals on grapheneos

### ISSUE THREAD

**Issue by Nick2690** [GrapheneOS/os-issue-tracker#617]
I recently rootedy pixel 4a with grapheneos and now cannot receive text messages. I can send sms and MMS and can receive from institutions (two factor with codes) but that is it.

**Comment by thestinger** [comment]
Did you forget to disable iMessage for the phone number?

Also, make sure you've properly locked the bootloader and have verified boot enabled. Note that installing GrapheneOS doesn't involve rooting the device.

**Comment by thestinger** [comment]
This is probably caused by iMessage still being enabled. Either that, or it's a carrier configuration issue or other carrier issue.

A strong indication that it's something like iMessage is you're still receiving some SMS.

**Comment by thestinger** [comment]
You're better off starting with the Matrix room to ask for support with issues like this: https://grapheneos.org/contact#community. If people there can't help you and you think it's a bug then it makes sense to file it here. There are a lot more people active there to help people.

**Comment by Nick2690** [comment]
How do I change the imessage settings?

**Comment by thestinger** [comment]
It's an Apple thing rather than related to us. iPhones won't send you SMS if you still have iMessage enabled for the number. There are guides on disabling iMessage since a lot of people run into this when leaving iOS. It's kinda set up this way on purpose to deter people from leaving.

**Comment by thestinger** [comment]
It's something you need to disable in your Apple account or something like that if this is the issue, which it sounds like it is.

**Comment by Nick2690** [comment]
OK, that was my thought. I don't have any apple and the phone I am testing with to send me sms is a normal pixel 4a.

**Comment by thestinger** [comment]
Well, that's quite strange, and seems like it must be a carrier issue if you can receive texts from elsewhere. Perhaps the phone isn't fully activated on their network yet. You should try waiting a bit and perhaps rebooting. You could try inserting the SIM card again. It's best to wait at least ~15 minutes between trying those things since it can take time for phones to activate.

**Comment by Nick2690** [comment]
OK I will contact the carrier. I tried reboot and some reinstall to no avail. I have been using this same phone on the current carrier for months now too with the stock os.

**Comment by thestinger** [comment]
Which carrier?

**Comment by Nick2690** [comment]
Spectrum mobile

**Comment by thestinger** [comment]
It's possible that you need to disable RCS in the carrier somehow.
