### ISSUE TITLE
Group Texts Broken

### ISSUE THREAD

**Issue by Jimmy-Py** [GrapheneOS/os-issue-tracker#619]
Group texts in the stock texting app is broken. Groups texts can be received, but when I respond to them, all members of the text receive my text individually, and not as part of the original conversation. 

This is with the current OS update from 8-5-21, and I noticed in previous ones also.

**Comment by thestinger** [comment]
In the main user profile or a secondary user?

**Comment by Jimmy-Py** [comment]
In the main user profile.

**Comment by flawedworld** [comment]
Confirmed on Pixel 5 running RQ3A.210805.001.A1.2021081822. Perhaps this could be sorted by cherry-picking commits to the Messaging app from master?

**Comment by thestinger** [comment]
We're not going to be working on the Messaging app. You can use a different SMS app.
