### ISSUE TITLE
eBay app invalid request when loging in and nothing shows on main screen expect for reload

### ISSUE THREAD

**Issue by bjones7296** [GrapheneOS/os-issue-tracker#620]
So even with the new play services compatibility layer. I am unable to get the eBay app to work. on the main screen it shows nothing and just has a reload screen which does nothing. When I try to login I get invalid request.

**Comment by thestinger** [comment]
Make sure you've followed the instructions at https://grapheneos.org/usage#sandboxed-play-services precisely. It's best to report this in #testing:grapheneos.org and provide logs. We're interested in expanding app compatibility but it's not a bug for an app to have a dependency on Play services not satisfied by the compatibility layer. It can be improved with more shims to offer more functionality, but not everything is going to work with it sandboxed that way.
