### ISSUE TITLE
Calling Accounts not persisting

### ISSUE THREAD

**Issue by mygiterino** [GrapheneOS/os-issue-tracker#622]
New SIP Calling Accounts do not persist across device reboots. "Ask every time" does not seem to be holding long-term.

**Comment by thestinger** [comment]
Seems like the issue or at least a similar one as https://github.com/GrapheneOS/os-issue-tracker/issues/445.

**Comment by mygiterino** [comment]
Thanks for pointing that out, it's the same issue!
