### ISSUE TITLE
Nexttracks background location update not working

### ISSUE THREAD

**Issue by fieryflamon** [GrapheneOS/os-issue-tracker#623]
I use nexttracks for location tracking to home assistant, but it often doesn't update the location correctly in the background. 

I am not sure if its the app or graphene, but others have reported it being related to the os:

https://codeberg.org/nexttracks/android/issues/9

**Comment by thestinger** [comment]
It's unfortunate that the CalyxOS community is spreading misinformation about GrapheneOS there, as usual. I'll need to make an account and respond to it.

**Comment by thestinger** [comment]
GrapheneOS provides GNSS + A-GPS via the base OS like AOSP and doesn't leak your real-time location to proprietary services like the stock OS or CalyxOS. GNSS + A-GPS takes time to get a location lock and certain features like geocoding aren't currently provided. We don't want to take privacy-violating shortcuts to implement these features. The user attacking us with misinformation there and claiming that this is unrelated to microG is quite wrong.

**Comment by fieryflamon** [comment]
I figured out a workaround that mitigates my problem. In case anyone needs it:

https://joshmccarty.com/track-homeaway-status-household-using-smart-phones-home-assistant/

https://www.home-assistant.io/integrations/ping/

**Comment by thestinger** [comment]
This is an upstream app issue also present with AOSP. It depends on having the Play services backend for the OS location APIs or another network location service which will not be integrated into GrapheneOS.
