### ISSUE TITLE
Fingerprint Recording Not working

### ISSUE THREAD

**Issue by dtecnique7** [GrapheneOS/os-issue-tracker#624]
Hello,

I accidentally switched to a Pin password and deleted the recorded fingerprint/biometric. I then tried to add it and it just simply prompts me for the pin twice, then it takes me back to the main settings > security menu. 

Please note that the fingerprint unlock option was previously working. Thank you in advance.

https://user-images.githubusercontent.com/89043124/129623589-014fc736-0423-4f7a-990f-bfca7d8bfcb6.mp4

I have a new pixel 4a.

**Comment by thestinger** [comment]
Not really clear what has happened here. Is this the owner profile or a secondary one? Can you try removing the lock method and adding it back?

**Comment by dtecnique7** [comment]
> Not really clear what has happened here. Is this the owner profile or a secondary one? Can you try removing the lock method and adding it back?

Thank you for the immediate response. Yes, this is the owner profile and no other profiles are present. I removed the lock method and added it back and the same thing happened. :(

**Comment by dtecnique7** [comment]
To follow up on this. I created a secondary account and it prompted me to set up a finger print. I set up the fingerprint, then deleted it and was able to set up a new one. I switched back to the main admin account to see if I could do the same; however, it kept looping me after entering my password twice.

Should I back up my data and reset the phone?

**Comment by thestinger** [comment]
I'm not really sure what's happening here or how it possibly could have ended up in this state.

**Comment by thestinger** [comment]
> I accidentally switched to a Pin password and deleted the recorded fingerprint/biometric.

That shouldn't cause any problems.

**Comment by thestinger** [comment]
You could factory reset if as an attempt at solving it. If the problem persists after a factory reset, then it must be a hardware issue. Before doing that, you could try obtaining logs with either `adb logcat` or the bug report capture feature in developer options which makes a zip that it shares to an app able to handle the files like Element (Matrix) or an email client. You could either send us that or open it up and strip it down to the bare minimum of the logs and perhaps the tombstone for the relevant crash. It puts a lot of related logs in there which you may care about. Apps aren't supposed to log sensitive data there but often do.

**Comment by dtecnique7** [comment]
> You could factory reset if as an attempt at solving it. If the problem persists after a factory reset, then it must be a hardware issue. Before doing that, you could try obtaining logs with either `adb logcat` or the bug report capture feature in developer options which makes a zip that it shares to an app able to handle the files like Element (Matrix) or an email client. You could either send us that or open it up and strip it down to the bare minimum of the logs and perhaps the tombstone for the relevant crash. It puts a lot of related logs in there which you may care about. Apps aren't supposed to log sensitive data there but often do.

Thank you! I thought I saved the logs, but it didn't work. I then factory reset the phone and voila! I was able to use the fingerprint again. My data backup didn't save either so I have to start from scratch, but it's ok. The only important data I had there were the pictures, which those are backed to several HDs. Everything else, I can re-download. 

Despite this little hiccup, I am impressed with the OS and the privacy it offers. Thank you for your hard work.

**Comment by thestinger** [comment]
I don't know what went wrong here and don't think we'll be able to do anything about it since we can't replicate it. It's probably an upstream bug that will end up being fixed in AOSP.
