### ISSUE TITLE
Trimming videos is clunky

### ISSUE THREAD

**Issue by Jacksper13** [GrapheneOS/os-issue-tracker#625]
Using the standard video trimming feature (open video y gallery, hit three dots on the top right corner, select Trim) is a nightmare, at least for videos recorded with OpenCamera, haven't tested others.

When sliding the trimming bars outside the "currently playing at" dot area, this dot doesn't move along, or ignore the trim, for that matter. The video starts doing a weird 300ms loop of repetition until you move the trimming blue selector to an area where the "currently playing at" ends up inside the valid trimmed part. You then have to move the "currently playing at" dot to the section of the video that will end up in the final video, then move the blue selectors.

Pixel 4, with latest stable release as of Aug 17th 2021. Happened in at least the previous three or four releases too.

**Comment by thestinger** [comment]
This will be addressed by https://github.com/GrapheneOS/os-issue-tracker/issues/48. We're not going to be improving the legacy AOSP Gallery app. It's not a good starting point.
