### ISSUE TITLE
Add EXIF data remover/scrambler

### ISSUE THREAD

**Issue by yodaforces** [GrapheneOS/os-issue-tracker#626]
Add a inbuilt EXIF data remover/scrambler, probably with a toggle button to reduce mistakes from happening - because they do. I know this could be done with third party apps already.

**Comment by thestinger** [comment]
This will be implemented as part of the camera app but not provided separately. It's implemented for the next Camera app release for images (but there isn't yet a toggle for stripping video metadata). There are already apps for that so it's a request for bundling apps which we don't plan to do.

**Comment by mkljczk** [comment]
Well, that would be a great feature for the file/media picker
