### ISSUE TITLE
Bug in TCP/IP Stack affecting NetGuard?

### ISSUE THREAD

**Issue by GHT215** [GrapheneOS/os-issue-tracker#627]
Hi everybody!
Thank you for that nice OS!
For days I'm struggling with the problem, that internet is very slow on cellular network. I'm using NetGuard Pro on unrooted GrapheneOS and deactivated Private DNS.
The bandwith is okay on cellular network, but it takes seconds until a website starts to load or apps getting data from a service.
I wrote on xda-devs about my problem and the dev of NetGuard said the problem could might be a bug in the TCP/IP-Stack of GrapheneOS. 
https://forum.xda-developers.com/t/app-6-0-netguard-no-root-firewall.3233012/post-85497919
I also asked in a german forum: https://forum.kuketz-blog.de/viewtopic.php?f=10&t=8624
How can I support to find a solution for the problem? It seems I'm not the only one having problems with this constellation.
Thanks in advance!
Kind regards

**Comment by thestinger** [comment]
There's no indication of any bug in GrapheneOS and seeing as the developer is maliciously spreading misinformation about the project we won't be helping with fixing problems with their app.

**Comment by thestinger** [comment]
GrapheneOS doesn't remove or restrict APIs in a way which would cause app compatibility issues and there are no compatibility issues caused with NetGuard. Checking the toggle for blocking VPN leaks by default is only a difference in default settings, not something GrapheneOS exclusive and users always get to choose this when adding a VPN.

**Comment by thestinger** [comment]
GrapheneOS doesn't remove or restrict APIs in a way which would cause app compatibility issues and there are no compatibility issues created with NetGuard. Checking the toggle for blocking VPN leaks by default is only a difference in default settings, not something GrapheneOS exclusive and users always get to choose this when adding a VPN.
