### ISSUE TITLE
System Settings App repeated appears to use the Camera without reason. 

### ISSUE THREAD

**Issue by oszyix** [GrapheneOS/os-issue-tracker#629]
The System Settings App repeated appears to use the Camera without reason on the latest update.
A warning notification is being triggered as a tiny camera symbol notification, which upon touching generates a message that the System Settings App is using the camera, and leading the users into the SystemsSettingsApp Info-Menu !

However !:!
It's no longer possible to remove permissions granted to the  SystemsSettingsApp. 
These permissions appear to be hard coded.

If an attacker remote-controls the SystemsSettingsApp the game is played.

**Comment by thestinger** [comment]
The current indicator implementation isn't perfect for system applications. Android 12 introduces it as a standard stable feature and it will work better.

Your complaints about not being able to revoke a permission and that proposed attack don't make any sense. It's a highly privileged core OS component... You're confusing OS components with actual apps. Every actual app is fully sandboxed. Settings isn't one.
