### ISSUE TITLE
Auto-Restart Feature: Device Continues to Auto-Reboot While Fully At Rest

### ISSUE THREAD

**Issue by F0SSIL** [GrapheneOS/os-issue-tracker#630]
The device endlessly auto-restarts even in a fully rested state.

**Comment by thestinger** [comment]
This was a design choice for the feature rather than storing state which could be lost due to a soft reboot from a crash. The only way to avoid it would be using state that can't be reset without a reboot being forced like system properties.

**Comment by thestinger** [comment]
Implemented for the next release along with it being much more robust/secure than the previous implementation.
