### ISSUE TITLE
Add option to hide app in App Drawer in GrapheneOS Launcher

### ISSUE THREAD

**Issue by eennoo** [GrapheneOS/os-issue-tracker#634]
It would be nice if the user could hide apps in the app drawer. Hidden apps should still be searchable in the search field in the app drawer.

Long-pressing on an app in the app drawer and be able to hide it would be a pattern that's quite common in other launchers.
But this feature would require a way to see and manage the hidden apps in order to make an app shown in the app drawer again. Maybe this would require an actual settings view for the GrapheneOS Launcher, which doesn't exist today. 
If not, then a simpler solution could be that when a hidden app is shown in the app drawer search results, long-pressing on it there could include an option to show it again in the app drawer.

**Comment by thestinger** [comment]
> Maybe this would require an actual settings view for the GrapheneOS Launcher, which doesn't exist today.

You can long press on the home screen and there's a Home settings configuration menu. At least one of those options impacts the app drawer too (notification dots).

> It would be nice if the user could hide apps in the app drawer. Hidden apps should still be searchable in the search field in the app drawer.
>
> Long-pressing on an app in the app drawer and be able to hide it would be a pattern that's quite common in other launchers.
>
> If not, then a simpler solution could be that when a hidden app is shown in the app drawer search results, long-pressing on it there could include an option to show it again in the app drawer.

What's the use case for this?

**Comment by oumno** [comment]
> You can long press on the home screen and there's a Home settings configuration menu. At least one of those options impacts the app drawer too (notification dots).

Ah. I had missed that. Thanks.

> What's the use case for this?

To declutter the app drawer. 
It could be apps that you have on the home screen, you don't want to show up again in the app drawer. 
There are some apps that you don't frequently open that you don't want to show up in the app drawer. 
Such as contact/calendar syncing apps (etesync to make a concrete exampel), keyboards etc - basically apps you may set up once and not often access.

**Comment by thestinger** [comment]
I don't really want to do this. You're meant to set up everything you use on the home screens and only using the app drawer as a list of all programs.

**Comment by JayXT** [comment]
I think that each decent Android launcher should have possibility to hide apps or at least respect a setting that allows app to be hidden from the list.

**Comment by Pantyhose-X** [comment]
Hidden apps: Search should not show
Lend your phone to a friend or your kid at home, and you install some NSFW software

**Comment by Pantyhose-X** [comment]
> Settings > Apps and find the apps there

If he is a system -level, It can be hidden

GrapheneOS, except for security. Other features to improve the user experience are basically off the table !

**Comment by derei** [comment]
Use case for ability to hide apps in drawer: some apps (Camera, for example) are required by system to work properly, and forcibly disabling or uninstalling them will cause random crashes (I should know, because I did it).

However, many users may want to use alternative apps. In my case, I prefer the Pixel GCam, because of its features. But now I'm stuck with two Camera apps in drawer.
Whilst this doesn't impact use, it's rather annoying.

There is of course, the question how time consuming and difficult would be to implement such feature. Whilst there are more ardent features to implement in GOS, if this one is rather trivial, perhaps it could be just be done and removed from the list.

**Comment by derei** [comment]
> You're meant to put the applications you use on the home screens.

Oh, so GOS is aimed to be the kind of software where "you do what we tell you to do, not what you want!!!"?

I mean, yeah... it sort of makes sense what you say, until you realise that (almost)all apps installed on the phone are meant to be used by the user.
I'd rather say you're meant to put the apps you want on home screen. No? Perhaps is too liberal this way? We can't have this kind of disorder? 😄

Some people may like a cleaner home screen, only with some apps (perhaps most used), and the rest in the drawer. And here comes the annoyance: having redundant icons in the drawer, just makes it longer, returns more search results, and overall it diminishes the user experience.
