### ISSUE TITLE
Switch the torch on and off by long pressing the power button.

### ISSUE THREAD

**Issue by rickcrash** [GrapheneOS/os-issue-tracker#636]
The torch is mostly used in the dark. In this situation, it is extremely useful and quick to be able to operate the torch by simply pressing a button and not having to use a PIN/fingerprint/menu.

**Comment by actionpapst** [comment]
Could you, despite being against an option like that, give us as users a choice? It's the most annoying missing feature for me with graphene so far and I'm very happy with absolutely everything else.

**Comment by jcz1** [comment]
After switching from LineageOS now, this is the feature I miss the most. Being able to turn on the flashlight even blindly is very useful and I have used it on many previous ROMs/phones.

**Comment by thestinger** [comment]
This feature won't be added to GrapheneOS. If we add a long press binding, it won't be for this.
