### ISSUE TITLE
Control Blocking of Connections Without V.P.N.

### ISSUE THREAD

**Issue by Penguin-Guru** [GrapheneOS/os-issue-tracker#638]
I need some apps to access my local network, but I would also like to block WAN connections not using my V.P.N. Is this an appropriate feature request for Graphene? More fine grained controls might be useful, like per address range/subnet, but this is my particular use case. Allowing this on specific SSID might also be useful for some apps, but I don't have a use for that personally.
As is, I have to toggle the V.P.N. setting and restart my V.P.N. every time I start and stop using one of these apps that needs LAN access. I don't think there's a better way but please correct me if I'm wrong.

**Comment by thestinger** [comment]
A VPN service app can support the ability to allow certain apps to bypass the VPN. It's one of the standard features of the OS VPN service. They can also support changing it based on the active network, etc. I think this is just an app feature and something that's already possible to provide.

**Comment by Penguin-Guru** [comment]
I believe the setting to "Block connections without VPN" takes precedence over app settings. The app I use has a setting that should allow LAN traffic to bypass the VPN, but this setting does not work unless I disable the "Block connections without VPN" setting. If you are sure that the app should be able to bypass the system setting then I will contact them to see if it is a bug on their end but it makes sense to me that this system setting should override the app setting.

**Comment by thestinger** [comment]
It should work fine even with that setting if they're implementing it properly. They may not be implementing it properly.

**Comment by thestinger** [comment]
The block connections without VPN setting blocks traffic that's not going through the VPN, which in this case is a VPN app. It should work fine for the VPN app to send traffic through to the local network as long as that traffic is going through it.

**Comment by ZMcK** [comment]
> It should work fine even with that setting if they're implementing it properly. They may not be implementing it properly.

That might be the case, but I've now seen at least 4 different VPN apps that appear to have the same issue.  Really depends on how the setting was implemented; the VPN might not have the final say in the matter. Haven't checked the source code yet.  Doesn't appear to be a Graphene specific issue. An OS level whitelist would alleviate this issue, tho that's probably not the optimal solution.

**Comment by thestinger** [comment]
It's an app feature and has to be properly implemented by the apps providing it.

**Comment by ZMcK** [comment]
Could be, tho from @Penguin-Guru linked issue, it looks like PIA has an Allow LAN feature. So does ProtonVPN, which I'm using. Neither are working with this setting. Can't I say about the other apps having this issue. I'm planning to check the source code when I get a free minute to see if anything can be done about it.

**Comment by thestinger** [comment]
Their implementation is broken on AOSP and the stock OS on Pixels too and I don't think it's due to an AOSP issue.

**Comment by ZMcK** [comment]
Took a minute to look at the source and I agree; it's a VPN implementation issue, not AOSP or GrapheneOS. As the block is UID and package based, it implies the VPNs are allowing the LAN and whitelisted apps/connections to retain ownership of the connections without removing Protect() or adding them to the exceptions list. 
Anyway, I'll move my complaints to the respective apps, as the apps should really be the ones to handle this and an os level whitelist would just make managing connections more of a nightmare than they already are.

**Comment by thestinger** [comment]
They're probably using something to allow the traffic to not be routed through them rather than routing it through themselves and then sending it and from the local network from there. AOSP could offer a much better API but that's not really up to us and at the very least allowing access to the local network can be done with block all connections enabled as long as the VPN app passes that traffic through itself.

**Comment by real-or-random** [comment]
@ZMcK 
> Anyway, I'll move my complaints to the respective apps, as the apps should really be the ones to handle this and an os level whitelist would just make managing connections more of a nightmare than they already are.

Did anyone implement this? Do you have some links to other issue trackers where you reported this?
