### ISSUE TITLE
Add android auto stub

### ISSUE THREAD

**Issue by lazzurs** [GrapheneOS/os-issue-tracker#640]
It would be useful to have the option to run Android Auto given the Google Play Services sandbox works so well.

It appears the build would need the below stub to get this working?

https://github.com/dylangerdaly/android-auto-stub

Sadly I don't know enough about the Android/GrapheneOS build system to test this but is this possible and if so can someone provider some pointers on how I might test this before submitting a PR?

**Comment by thestinger** [comment]
This goes against the approach of not giving any special privileges or access to Play services. The only way Android Auto could work is if shims were made to make it function without privileged access, which is unlikely. It's beyond what the sandboxed Play services compatibility layer is going to be realistically able to provide. It expects too much invasive access into the OS to provide a different UI as a frontend.

**Comment by lazzurs** [comment]
Thanks for the response, that was quicker and more detailed than I expected :)
