### ISSUE TITLE
Edit the way Messaging app handle punycode/IDN links/URL

### ISSUE THREAD

**Issue by yodaforces** [GrapheneOS/os-issue-tracker#641]
I've just checked how the Messasing app do handle punycode URL:s. For example https://www.googlę.com (notice the 'ę' here) vs https://www.google.com . In Messaging is the "https://www.googlę.com" clickable which is not the case for Molly/Signal.

One way to fix this "issue" would be to automatically
convert punycode URL:s to clickable links as text links.
Then https://www.googlę.com would show up as: https://www.xn--googl-n0a.com/

Or the simple way: Don't make the punycode URL clickable as already the case in Molly/Signal.

Maybe with a toggle button to let the user decide if the link should be clickable or not.

A quick search gave me this: https://github.com/signalapp/Signal-iOS/issues/4194#issuecomment-608301593

So yes, you're more likely to be phished via SMS ;)

**Comment by thestinger** [comment]
Improvements to the Messaging app aren't planned.

**Comment by thestinger** [comment]
The Messaging app may be replaced with something else but we are not going to actively develop it. Feature requests for it will be closed.
