### ISSUE TITLE
QR code scanner

### ISSUE THREAD

**Issue by cedws** [GrapheneOS/os-issue-tracker#642]
Not sure if this is out of scope or not.

The Google Camera app on the stock OS is capable of scanning QR codes as far as I'm aware. The camera app that ships with GrapheneOS is not and this makes sense given the website does say that it's a barebones app from AOSP [here](https://grapheneos.org/usage#camera). If there's a tracking issue for the development of the replacement camera app mentioned then I think this would be a good point to add there.

Being unable to scan QR codes could hinder a user's initial setup of the OS.

**Comment by thestinger** [comment]
The new Camera app has a QR scanning mode and https://github.com/GrapheneOS/os-issue-tracker/issues/713 has been filed about including it in GrapheneOS.

https://github.com/GrapheneOS/Camera

There are alpha builds available at https://github.com/GrapheneOS/platform_external_Camera.
