### ISSUE TITLE
Prebuild fork of Talkback accessibility service: out of date

### ISSUE THREAD

**Issue by PatrykMis** [GrapheneOS/os-issue-tracker#647]
Noticed that Talkback was built from master branch (with GrapheneOS's modifications) on April this year. Current source (commit google/talkback@9db811a) is performing better, builds successfully and contains latest features such as Braille keyboard (Braille screen input method).
Play services (GCM) libraries are not included so patching is not nessesary. Optionally, the folder `utils/src/main/java/com/google/android/accessibility/utils/ocr/` can be excluded from build as OCR is not (yet) implemented and used in Talkback's code (if it will be, it would probably depend on Google services though).
Also, the experimental support for Polish Braille can be included (google/talkback/pull/17) which works quite well.
Blind and visually impaired people will appreciate and benefit from this update as currently it is impossible to update Talkback in seperat user profile, and custom keyboard cannot be used/chosen in work profile too.

**Comment by thestinger** [comment]
The problem with the new release is they removed Switch Access which we probably want to keep, although we could just accept that they dropped it and have adding it back as a future feature via a separate app.

**Comment by PatrykMis** [comment]
From my experience the user base of Switch Access is very low (currently I know noone using it).
As soon as Compatibility Layer is working, the [Android Accessibility Suite](https://play.google.com/store/apps/details?id=com.google.android.marvin.talkback) could be installed from Play Store if needed (it contains Switch Access of course).
From my point of view, the priority of maintaining built-in Switch Access is very low in compareson with updating old (2-years-old, in fact) code of Talkback (Talkback's open-sourced code is always about a year older than latest build surved via Play Store).

**Comment by PatrykMis** [comment]
Eventually, I will appreciate someone who provide me with instructions:

1. How to update Talkback in user profile other than Owner, because in Owner profile I can update system Talkback with my debug-signed build while in other profiles I cannot. I tried different ways (standard, `pm install --user <user_id>` via ADB etc.);

2. Or, preferably, how to set custom keyboard from latest Talkback or [Soft Braille Keyboard](https://github.com/danieldalton10/Soft-Braille-Keyboard) in work profile? It seams that choosing other than default keyboard in work profile is impossible.

**Comment by PatrykMis** [comment]
Closing due to the following change in 2021091407 release:

> • TalkBack (screen reader): update base version to 370044210 and port our changes (Switch Access service has been dropped upstream)

Thanks.
