### ISSUE TITLE
Widgets wiped out from secondary profile home screen when using power button 'end session' shortcut

### ISSUE THREAD

**Issue by pkhomyakov-rms** [GrapheneOS/os-issue-tracker#652]
I have observed this on Pixel 5a running the latest releases but the issue is most likely generic.

HW: Pixel 5a
Build: 2021090819

Steps to reproduce:

1. Create secondary profile, accept defaults for setup wizard. No additional apps installed.
2. Set security method. I used PIN for simplicity, no biometric.
2. Switch to new secondary profile and add a widget to home screen, I used Vanadium search.
3. Lock phone, wake phone, tap 'end session' shown on screen above time. Repeat login to secondary profile. Search widget present. Confirmed multiple times.
4. While profile is active push power button until power function menu is shown. Tap 'end session'. Login back to secondary profile. The home screen is clean, widget is no longer present.
5. Repeat step 4 a few times if nothing happened.

Additional notes:

- Phone has 7 profiles, not clear if this is a contributing factor.
- I have tried multiple different widgets, both system and 3rd party. The problem is definitely reproducible with a single system widget but the issue shows more consistently with 3rd party.
- The problem is more likely to show up if PIN is set. I could not reliably replicate the issue with no lock on profile set.
- The problem does not seem to happen if 'power off' action is chosen instead. Although it is hard to test due to time required for phone reboot.
- The problem does not seem to happen if profile is shut down due to restriction on how many profiles can run concurrently, i.e. when other profiles are activated.

**Comment by thestinger** [comment]
See https://github.com/GrapheneOS/os-issue-tracker/issues/453.

**Comment by pkhomyakov-rms** [comment]
It only happens for me when I use power button triggered 'end session'. Did I misinterpret the significance of that and it is just timing and can happen with any ending of profile scenario?

**Comment by thestinger** [comment]
There are upstream bugs tied to switching between profiles which are primarily triggered when using end session. It's the same issue as the other one. The user there may have meant using end session when they said switch too.
