### ISSUE TITLE
harden disabling network adb at boot

### ISSUE THREAD

**Issue by flawedworld** [GrapheneOS/os-issue-tracker#653]

**Comment by thestinger** [comment]
I think the main thing we need to do is at least make sure this can't be enabled persistently, so that an attacker who compromises the device or gains temporary adb access cannot set up persistently having adb exposed via network.

**Comment by thestinger** [comment]
Already seems to reset at boot.

**Comment by muhomorr** [comment]
Addressed by https://github.com/GrapheneOS/platform_system_core/pull/13
