### ISSUE TITLE
Restrict screenshot and screen-record access to lock screen numpad/ keyboard

### ISSUE THREAD

**Issue by just-wasted** [GrapheneOS/os-issue-tracker#654]
The lockscreen &/ or numpad/ keyboard should be excluded from the posibility to take sceenshots or taking a screenrecording.
Because of the visual feedback while entering a pin or a passphrase they can be captured.

edit: tested on pixel 4a

**Comment by Niko4u5** [comment]
#588 solves this Problem too

**Comment by r3g-5z** [comment]
Maybe be able to backport it if it's in AOSP master.

**Comment by r3g-5z** [comment]
Based on https://github.com/GrapheneOS/os-issue-tracker/issues/588#issuecomment-1500323465, we're going to wait until this is released in Android 14 or possibly Android 13 QPR3 as upstream is already working on this feature.
