### ISSUE TITLE
Override-force-dark-mode doesn't persist across reboots

### ISSUE THREAD

**Issue by TheEarlOfEmsworth** [GrapheneOS/os-issue-tracker#656]
Setting override-force-dark-mode in developer options doesn't persist when the device is rebooted.
RQ3A.20210905.001
Pixel 3XL

**Comment by thestinger** [comment]
I don't really think this is meant to persist. It's there for testing rather than being intended for use by end users.

**Comment by TheEarlOfEmsworth** [comment]
I use this as an accessibility feature. I can't bounce between bright and dark because of a visual impairment. But if this is the same behaviour in AOSP then I guess it's not a GrapheneOS problem.

**Comment by thestinger** [comment]
It's really not meant to be used that way. Apps need to be upgraded to support the dark mode for it to work properly.

**Comment by TheEarlOfEmsworth** [comment]
fair enough. If it's just for debugging I wouldn't expect it to be changed. I'll still use it though :D - Some usability is better than none
