### ISSUE TITLE
feature request: Add option to disable fingerprint sensor when screen is off

### ISSUE THREAD

**Issue by chris42** [GrapheneOS/os-issue-tracker#663]
Would like to see an option, to disable the fingerprint sensor when the screen is off, so you need to first activate the screen and then use the fingerprint reader to unlock.
Placing and sensitivity on my Pixel 5 fingerprint sensor leads to a lot of pocket dialling and unlocks.

I know of the feature to lock the phone so you need to enter the pin to unlock it again, however a simple option to deactivate the sensor when the screen is off would be more elegant and easier to use.

**Comment by thestinger** [comment]
This isn't something we want to add.
