### ISSUE TITLE
Alarm does not sound after device restart

### ISSUE THREAD

**Issue by sst-76** [GrapheneOS/os-issue-tracker#669]
Currently on build RQ3A.210905.001.2021092612 on a Pixel 3, but observed on many prior builds.

If I set the alarm, plug in my phone, and go to sleep, if the phone restarts overnight, the alarm does not sound. I am using the stock clock application. The alarm volume is set to maximum and "gradually increase volume" is set to 10 seconds. The tone is Argon, it is not set to vibrate, the label has custom text "wakey wakey" and the alarm is set to REPEAT, with every day of the week selected.

I think that covers the system setup to replicate the problem. I saw that an earlier, similar, issue had been closed as corrected, but I don't think that's quite accurate. I know that the phone is restarting because using the fingerprint scanner prompts a "PIN is required after device restart."

I haven't missed work for it yet, but I've had a few close calls. My wristwatch is serving as a backup but I would really appreciate it if this issue was elevated.

**Comment by Zanthed** [comment]
Are you using the auto restart feature? Alarms won't work when data is at rest and in BFU state.

**Comment by sst-76** [comment]
No, I am not.

**Comment by thestinger** [comment]
Can you try clearing the clock app data?

**Comment by sst-76** [comment]
> Can you try clearing the clock app data?

That appears to have fixed the issue.
