### ISSUE TITLE
Spoof device fingerprint and build ID props on Pixel devices to match stock OS for sandboxed play services

### ISSUE THREAD

**Issue by flawedworld** [GrapheneOS/os-issue-tracker#670]
This should be done via automated prop extraction in APV and should ONLY be set for the latter 3 apps.

Primary rationale for this is to improve accuracy of the Google Play Store.

**Comment by thestinger** [comment]
We do use the same product name, brand and build ID already. The only thing that doesn't match is the incremental. I don't really think we should need anything else.

**Comment by thestinger** [comment]
Our releases just look like much newer releases of the stock OS since our incremental (build number) is much higher due to using the date as a readable 10 digit number.
