### ISSUE TITLE
Qr Code Activation

### ISSUE THREAD

**Issue by arturosabbatini** [GrapheneOS/os-issue-tracker#672]
I was searching if graphene os has the qr code activation that will been shown after touching 7 times in screen after phone is factory reset. In graphene os this thing doesn't work as I see or is any other method and I don't know it.

**Comment by thestinger** [comment]
No, it's not something that's supported. Device management support is something that will need to be fleshed out.

**Comment by thestinger** [comment]
You're better off asking these questions in the #grapheneos:grapheneos.org Matrix room.

https://grapheneos.org/contact#community
