### ISSUE TITLE
DEBUG_NOTIFIERS uncovered a potentially serious problem on 4th and 5th generation Pixels (notifiers called outside of the _stext to _etext range still passing type-based CFI checks) with the updated Android 12 LLVM kernel toolchain and had to be disabled temporarily

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/os-issue-tracker#681]

**Comment by thestinger** [comment]
Not going to have time to fix this as part of the Android 12 port so removing the milestone.

**Comment by flawedworld** [comment]
DEBUG_NOTIFIERS appears to not break boot on the Pixel 6 however this needs more investigation

**Comment by thestinger** [comment]
No longer plan on enabling this feature due to CFI.

**Comment by thestinger** [comment]
No longer plan on enabling this feature due to CFI and PXN/PAN.
