### ISSUE TITLE
Bad audio quality / regression on Pixel 3A

### ISSUE THREAD

**Issue by falisca** [GrapheneOS/os-issue-tracker#686]
Device: Pixel 3A (sargo)
OS version: RQ3A.211001.001.2021100606 
After the update to 2021100606 the audio is notably lower quality, can be heared specifically on higher frequencies.
Affects all audio coming from the phone speakers.

**Comment by thestinger** [comment]
It might get better after we fully move to Android 12 in a couple weeks.
