### ISSUE TITLE
TalkBack crashes when opening TB settings

### ISSUE THREAD

**Issue by falisca** [GrapheneOS/os-issue-tracker#687]
Opening "reading preferences" (Verbosity settings), in main TalkBack settings app, causes the crash / restart of the TalkBack service.
I noticed this bheavior from the first time TalkBack was included in Graphene OS.
Note that before TalkBack was included in the OS, on the device a previous version of TalkBack was present (manually installed from PlayStore ) and that version was not affected by this bug.
Edit: I added the log showing the crash but apparently without usefull messages.
[TalkBack-Crash.log](https://github.com/GrapheneOS/os-issue-tracker/files/7359537/TalkBack-Crash.log)

**Comment by flawedworld** [comment]
This does not seem to be an issue anymore
