### ISSUE TITLE
Android 12 device config for permission history

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/os-issue-tracker#692]
For https://github.com/GrapheneOS/platform_packages_modules_Permission/commit/7f72319f45da80f967778ceaa795aad4b8db2aab

**Comment by kdrag0n** [comment]
This can be closed now that https://github.com/GrapheneOS/platform_frameworks_base/pull/98 has been merged.

**Comment by thestinger** [comment]
Thanks.
