### ISSUE TITLE
remove AOSP Camera app once the new Camera app is shipped and working well for people

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/os-issue-tracker#714]
This is the next step after #713.

**Comment by DevJackSmith** [comment]
i'm not sure we are talking about the same apps then. When i tried to use Camera included with GOS it has almost no features. Open Camera by comparison was feature rich and much more modern. I seriously doubt it we are talking about the same apps. I'll try to find and include link.

**Comment by thestinger** [comment]
Doing this in one go instead of as separate steps.

**Comment by DevJackSmith** [comment]
@thestinger just wanted to say thank you, you were right. your camera app is much better. apologies for confusing it with aosp camera.
