### ISSUE TITLE
upstream intent filter verification uncaught exceptions caused by trying to send too much data to/from work manager

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/os-issue-tracker#732]

**Comment by thestinger** [comment]
This has been temporarily worked around by disabling the user-facing crash notices. It's not a particularly important feature but it would be good to resolve this so that site associations can be automatically enabled again for apps triggering this problem.

**Comment by firefoxlover** [comment]
> This has been temporarily worked around by disabling the user-facing crash notices. It's not a particularly important feature but it would be good to resolve this so that site associations can be automatically enabled again for apps triggering this problem.

Is there an adb command that you can use to do that?

**Comment by thestinger** [comment]
Not needed, we already worked around it.

**Comment by bitmage** [comment]
I'm curious to know more.  I have LineageOS 12 with MicroG and I am seeing this message.  What could be shared to help the LineageOS developers, and to help users who do not have a fix currently?

**Comment by thestinger** [comment]
This issue tracker is only intended for GrapheneOS.

**Comment by trytomakeyouprivate** [comment]
> This issue tracker is only intended for GrapheneOS.

But where can you find a file with exact that implementation? I would like GrapheneOS but I will not buy a new phone, and especially not one from Google.

**Comment by thestinger** [comment]
Okay, not relevant to our issue tracker.

**Comment by r3g-5z** [comment]
Should be resolved in next GrapheneOS release.

**Comment by r3g-5z** [comment]
Upstream fix doesn't seem to work
