### ISSUE TITLE
Newer versions (21.33.14 and above) of gms break push notifications in secondary user profile

### ISSUE THREAD

**Issue by justinhsa** [GrapheneOS/os-issue-tracker#734]
Device: Pixel 5
OS version: SP1A.210812.015.2021102000

This issue seems unrelated to the OS version, and to me has existed since gms 21.33.14 came out (around 9/23). After updating to this version, Signal and other apps using FCM could not receive push notifications anymore. Completely removing and reinstalling gsf, gms and vending apps did not help, but installing older version of gms (21.30.16) did.  I think google changed something between these two versions of gms. 
In owner profile FCM works fine with all versions of gms. The issue only exists in secondary profile. Versions of gsf and vending apps seem irrelevant. 

Tested not working: 
gms 	21.33.14 (150400-395723304) , 21.39.16 (190400-402663742)

Tested working: 
gms		21.30.16 (150400-391784508) , 21.30.16 (190400-391784508)    (and all previous versions since I hadn't had any problems till 21.33.14)

**Comment by thestinger** [comment]
Android 12 variant of GSF / GMS / Play Store is worth trying.
