### ISSUE TITLE
Camera / microphone / location - timeout

### ISSUE THREAD

**Issue by zioomus** [GrapheneOS/os-issue-tracker#736]
Can you create a time limit for camera, microphone and location?

After a set time of non-use, it will turn off.
Same as in bluetooth

**Comment by thestinger** [comment]
They're only usable by apps that have been granted the appropriate permissions. You can already choose to only grant access for the current session. You can't grant background camera/microphone access at all. Background location access exists but has to be requested separately and normally you would only grant it in the foreground.

**Comment by Zanthed** [comment]
@zioomus 
Bluetooth timeout feature already exists if that's what you're referring to.
Settings -> Connected devices -> Bluetooth timeout

**Comment by thestinger** [comment]
I don't think it makes sense to implement this since it's based on apps using it instead of the user.

**Comment by thestinger** [comment]
This would have to be proposed in a much more specific and clearer way, with an explanation of why it makes sense and the threat model for it.
