### ISSUE TITLE
screenshot service misses events and triggers ANR for SystemUI

### ISSUE THREAD

**Issue by Pauler221** [GrapheneOS/os-issue-tracker#738]
I have a pixel 4a running Android 12 on the beta channel.

Im getting every 40 mins or so a "System UI isn't responding" popup. But nothing seems to be crashing. After pressing on "wait" everything works fine. 

I'm actively texting for 2h now. Didn't have the issue before while just looking occasionally on my phone.

**Comment by Ammako** [comment]
I just got this again, on 2021110122. Can I get any useful info from my logcat?

**Comment by rrrrttttttttt** [comment]
Hello, I'm very new to this. I have just installed the latest stable version on my pixel 4a and I randomly get the "system ui isn't responding" message. Either option wait or close app doesn't seem to affect any functionality. I have an interactive bug report if it helps? Thanks

**Comment by Zanthed** [comment]
https://github.com/GrapheneOS/platform_frameworks_base/commit/562fbd176fdc658f6e8541a285e168e034831250

**Comment by thestinger** [comment]
Resolved in Android 13.
