### ISSUE TITLE
Opening the app switcher while in Gesture Navigation Settings freezes app switcher UI

### ISSUE THREAD

**Issue by jorgeluiscarrillo** [GrapheneOS/os-issue-tracker#749]
Definitely upstream. Happens on stock as well.
1. Settings > System > Gestures > System navigation > Gesture navigation settings (gear icon)
2. Open the app switcher
3. Try to swipe back and forth

**Comment by amojics** [comment]
> Please check if this happens for you on the latest release.

Checked. Issue still present.

Sargo, Build: SP1A.211105.002.2021111414

**Comment by Zanthed** [comment]
Does not appear to be an issue anymore based on my testing.

**Comment by jann-0** [comment]
This still seems to be an issue on my device. A 4a on SQ1A.220205.002.2022022818

**Comment by jorgeluiscarrillo** [comment]
It still occurs in the latest GrapheneOS release, but I just tested in an emulator with 12L and it seems to be fixed there.

**Comment by thestinger** [comment]
It's an upstream AOSP issue we don't want to track here.

**Comment by jann-0** [comment]
That makes sense.
