### ISSUE TITLE
Option to remove navigation bar and/or the white pill

### ISSUE THREAD

**Issue by sorat0mo** [GrapheneOS/os-issue-tracker#753]
I know this is *intended behaviour* on Google's side. Is there any chance the dev team will consider adding support for this feature in Graphene OS? The main reasoning behind this feature request is because the navigation bar is obstructing view when a keyboard is up.

Reference:
[Related Issue on Google Issue tracker](https://issuetracker.google.com/issues/190795679?pli=1#comment24)

**Comment by flawedworld** [comment]
It's unlikely that we will implement such functionality.
