### ISSUE TITLE
playback controls are missing in quick settings audio payer

### ISSUE THREAD

**Issue by pkhomyakov-rms** [GrapheneOS/os-issue-tracker#754]
Pixel 5a, 2021102300 build. 

Player is shown as expected in quick settings panel but playback control PLAY, FORWARD, REWIND buttons are not drawn. A touch to the specific area where corresponding button would be does produce correct action, i.e play/pause etc. There are no symbols for the buttons though.

Verified with several audio apps.

**Comment by amojics** [comment]
Checked with NewPipe and VLC.
Unable to reproduce issue.

Sargo, Build: SP1A.211105.002.2021112123

**Comment by pkhomyakov-rms** [comment]
Pixel 5a, SP1A.211105.003.2021112123, Secondary profile, NewPipe

![buttons-missing](https://user-images.githubusercontent.com/46538814/142965165-f5e93e48-af78-47b1-8743-b97b7b2571b1.jpg)

**Comment by flawedworld** [comment]
Does not seem to be any issue anymore.

**Comment by pkhomyakov-rms** [comment]
Updated to the latest build SQ1A.220105.002.2022013120 and the issue is still present on Pixel 5a. Almost as if proper resolution'ed resources for these buttons are missing in the source.

@flawedworld which model and app are you not seeing it happening?

**Comment by flawedworld** [comment]
On 2022013120 on the Pixel 6 on NewPipe it seems fine.

**Comment by flawedworld** [comment]
What app are you seeing this on?

**Comment by pkhomyakov-rms** [comment]
Can't confirm NewPipe for a moment. I use f-droid version and 0.21.16 update for broken youtube has not made it yet to f-droid. The other two apps I mentioned in the original message (Eleven, Hoopla) are not showing buttons. Will report on NewPine as soon as it updates on f-droid.

**Comment by thestinger** [comment]
Use their latest official releases instead of whatever F-Droid happens to have packaged which is often not up-to-date. Lots of unmaintained or poorly maintained apps have issues with Android 12 including with media notifications. It's unrelated to GrapheneOS. Make sure they're actively maintained apps and that you're using the most recent release. If they're abandoned then there might be forks of them that are actively developed. This media notification thing has no relation to GrapheneOS but rather apps doing certain invalid things got broken by Android 12.

**Comment by pkhomyakov-rms** [comment]
For the record... I don't doubt the problem has nothing to do with Graphene. It is most likely and artifact of whatever google decided to allow out to AOSP tree.

NewPipe 0.21.16 fresh-installed from their official repo. No buttons.

**Comment by thestinger** [comment]
AOSP is the same code used by the stock OS. Many apps have compatibility issues with Android 12 primarily due to doing things incorrectly in the past in a way that relied on behavior that wasn't well defined and simply happened to work before.

**Comment by pkhomyakov-rms** [comment]
There are plenty of Pixel exclusive features that are not in AOSP. It is not the same. In any case....

Running NewPipe 0.21.16 on Pixel 5a on latest SQ1A.220105.002.2022013120. The issue is still present. Buttons react to touch as expected but nothing is drawn, same as Nov 22, 2021 screenshot showed.

**Comment by thestinger** [comment]
The stock OS for Pixels is built from the AOSP source tree with added repositories. They use resource overlays and replacement of packages. They don't alter the AOSP source code directly. They use Google variants of certain apps like Settings but this isn't really relevant to that.

**Comment by thestinger** [comment]
If this issue occurs with the stock OS, you need to report it to NewPipe rather than us.

**Comment by thestinger** [comment]
If this issue occurs with AOSP and/or the stock OS, you need to report it to NewPipe rather than us.

**Comment by pkhomyakov-rms** [comment]
Noted. It would be great if someone from the official team could try to confirm this on Pixel 5a. I do understand though if that's not in the cards due to higher priority tasks and limited resources.

**Comment by division4** [comment]
Just as a reference, I have a similar issue with a Pixel 4a on GrapheneOS Build SQ1.220105.002.2022013120, see https://github.com/enricocid/Music-Player-GO/issues/365.
