### ISSUE TITLE
Updater does not work over VPN when "Always-on VPN" and "Block connections without VPN" are enabled

### ISSUE THREAD

**Issue by guser303** [GrapheneOS/os-issue-tracker#755]
VPN: Wireguard
GrapheneOS: latest stable (based on Android 12) but the previous version is also affected.
Wireguard set-up: Include only certain apps but System Updater does not show on the list. Android System, Download Manager and several system apps that use the network are also included. 
Always-on VPN: enabled
Block connections without VPN: enabled

Expected behavior: System Updater should check for new versions either automatically or manually.
Current behavior: System updater does not connect to the update server. 

If Block connections without VPN is disabled everything works as expected.

**Comment by guser303** [comment]
Are you sure this is upstream ? For some reason Updater cannot be found (and whitelisted) in the Wireguard VPN app even if it has Network permission. Might this be related to Direct Boot ?

**Comment by flawedworld** [comment]
This is an issue with the WireGuard app, not GrapheneOS.
