### ISSUE TITLE
[Upstream/Enhancement] Provide a callback when install dialog of Package Installer is dismissed instead of cancelled

### ISSUE THREAD

**Issue by quh4gko8** [GrapheneOS/os-issue-tracker#759]
The current `PackageInstaller` API has callbacks for most cases except for dismissed install dialog. It would be nice to add a callback for this, like [`STATUS_FAILURE_ABORTED`](https://developer.android.com/reference/android/content/pm/PackageInstaller#STATUS_FAILURE_ABORTED), as it implies the installation is being aborted.

This can (potentially) help improve the shims for installing apps in Play store.

**Comment by thestinger** [comment]
I think this is now implemented properly.
