### ISSUE TITLE
GrapheneOS theme

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/os-issue-tracker#76]

**Comment by Kokokokoka** [comment]
It would be good if one could use an AMOLED-friendly (black) theme

**Comment by thestinger** [comment]
Android Q brings dark theme support. There's already a System UI dark theme present. I'm really only talking about the highlight colors, etc.

**Comment by oldosfan** [comment]
What about a different accent color? Grey would look nice, and it does reflect the "graphene" in **Graphene**OS

**Comment by ineshi2** [comment]
Some users recently reporting missing option to change accent color or asking about how to change it:

https://www.reddit.com/r/GrapheneOS/comments/e7z8bz/unable_to_change_accent_color/
https://www.reddit.com/r/GrapheneOS/comments/epxghm/how_to_change_accent_colors/

**Comment by thestinger** [comment]
Developer options aren't something regular users are meant to use and those settings shouldn't be taken for granted as something that's going to stay around.

**Comment by w3bb** [comment]
I'm not sure about AOSP but this is a non-developer option on the Pixel 3 stock ROM. I believe LineageOS is the same. I'd really like to change the accent colour and exposing this option would be a godsend. The notification menu sticks out like a sore thumb with my otherwise monochromatic theming.

**Comment by thestinger** [comment]
Send a pull request if it's simply a build configuration option. If it's more than that, it won't be added.

**Comment by thestinger** [comment]
The project is focused on privacy/security and robustness. It's currently falling apart due to lack of resources and support. Color themes are just not something that matters. If someone sends a pull request setting some resources in Settings or frameworks/base, I can merge that, but beyond that, I don't want more issues filed about it and I won't be spending time on it. I also don't want contributors that could be working on other things to spend time on it.

**Comment by nutts0** [comment]
@w3bb 
> but this is a non-developer option on the Pixel 3 stock ROM.

Don't see it in stock. Where do you have this option?

**Comment by thestinger** [comment]
Further tweaks can be made to improve this more.

**Comment by thestinger** [comment]
A few very basic changes have been implemented and further issues can be opened about more specific changes.
