### ISSUE TITLE
Pixel 4 Flame display flickers in many apps 

### ISSUE THREAD

**Issue by muzirian** [GrapheneOS/os-issue-tracker#765]
Device Pixel 4 Flame
Android 12 build SP1A.210812.015.2021102613 
Issue Display flickers slightly in many apps.

How to reproduce 
1. Display flickers slightly in many apps, flickering/issue is very visible dark theme in apps like inbuilt gallery or f-droid, aurora store or, when we touch something and display refreshes to show selection highlight.
2. Also visible when small screen changes appears on screen, like updating repo on aurora store, without touching.

Temporary work around- Turning off **smooth display** in settings gets rid of the problem for now.

Attaching video recording of the issue
Can see flickering from 4-7 and 8-10secs

https://user-images.githubusercontent.com/71079779/139538199-075f4af2-8966-43c4-a729-edabc8ed6a22.mp4

**Comment by thestinger** [comment]
Seems like a hardware issue rather than something we can address.

**Comment by muzirian** [comment]
Found similar problem reported for pixel 4 xl https://t.me/GrapheneOS/150909

**Comment by muzirian** [comment]
Could this be problem with android pushing refresh rate too low, when smooth display is turned on?

**Comment by bingoxo** [comment]
> Seems like a hardware issue rather than something we can address.

it never happened before the android 12 update though

**Comment by muzirian** [comment]
I have only used graphene based on android 11, very small time, so really remember if I had issue on 11, editing report.

**Comment by bingoxo** [comment]
turning off smooth display means capping refresh rate at 60 hz instead of using the full 90 hz on the device , so not an ideal solution

**Comment by mobhani** [comment]
I am also having this issue. 

Flicker occurs on dark areas of the screen, mostly visible on grey backgrounds. If I'm viewing an image the darker portions flicker.

This is definitely a software issue as capping the refresh rate to 60Hz solves the issue.

**Comment by mobhani** [comment]
I enabled "Display framerate" in developer settings and I notice that the screen only flickers when the refresh rate switches between 60Hz and 90Hz.

**Comment by thestinger** [comment]
> This is definitely a software issue as capping the refresh rate to 60Hz solves the issue.

Does not make it a software issue...

**Comment by thestinger** [comment]
This is a hardware issue and isn't in the scope of the issue tracker.
