### ISSUE TITLE
Native Camera app / OpenCamera always show black screen

### ISSUE THREAD

**Issue by skaldesh** [GrapheneOS/os-issue-tracker#767]
Hi, I have a Pixel 3a and recently updated to Android 12. After that, several minor patches have been installed as well. Unfortunately, I am not sure which update exactly caused the issue.

My problem is that my camera apps only show a black screen. All the UI controls etc. work and I can "use" the app normally, but the camera image itself is always black. It does not matter whether I use front or rear camera. It affects both the integrated native camera app and the OpenCamera app. 

In OpenCamera, switching between API 2 and legacy also does not affect the bug.

When capturing a photo, the image is also saved to my gallery, but the image is just black as well.

My build number: SP1A.210812.015.2021102613
Not sure, which additional info might be required, let me know :) Somebody can maybe help me to narrow the issue down, I am not too experienced in using the debugging tools, sorry.

**Comment by thestinger** [comment]
It's not a bug. You disabled camera apps for apps with the camera permission with the new global toggle.

**Comment by thestinger** [comment]
It's not a bug. You disabled camera access for apps with the camera permission with the new global toggle. The new global camera and microphone toggles work the same way as the location toggle. If you turn it off, nothing can use it. I think you must have misinterpreted how those work.

**Comment by skaldesh** [comment]
Yes, I JUST noticed that xDD Sorry for the inconvenience. Thanks for the help :heart:

**Comment by skaldesh** [comment]
you can close it :)

**Comment by thestinger** [comment]
No problem, you're not the first one to be confused by that.

**Comment by Ammako** [comment]
On my end, there is a very obvious popup telling you to enable camera access. Is that not working on certain devices?

**Comment by skaldesh** [comment]
On my Pixel 3a, I did not get this popup!
