### ISSUE TITLE
Phone app is sometimes black, unresponsive

### ISSUE THREAD

**Issue by yaomtc** [GrapheneOS/os-issue-tracker#768]
Sometimes the Phone app shows up as a black screen when a call is incoming.

I have noticed this on my Pixel 4a, as has Mike on his Pixel 3:

> <@mikekinley:matrix.org> So, I have noticed on my Pixel 3, using Android 12, that after remaining powered on for some time (exact time I do not yet know, timing it now for when it next does this) the phone (app? Receiver? Listener? Notifier UI overlay? Whatever it is that handles this ) stops displaying or responding to incoming phone calls. The phone will ring and vibrate when a new call is coming in, but there is no visual or button element to answer the call. A system restart fixes the issue for a while.

**Comment by yaomtc** [comment]
Still having this issue. Has anyone *not* seen this issue?

I have found relevant upstream issues:

[Proximity dialer issue](https://issuetracker.google.com/issues/137383985) (closed)

[Issue answering calls](https://issuetracker.google.com/issues/210236801) (unsure of relevance, probably will be closed soon)

[Inactive screen on incoming call](https://issuetracker.google.com/issues/64598338) (2017, closed)

I couldn't find any open issue there that seemed particularly relevant. Should I open a new one?

**Comment by thestinger** [comment]
Do you have a screen protector?

**Comment by yaomtc** [comment]
I do not

**Comment by thestinger** [comment]
Unable to replicate and there's a high chance it's a hardware issue. You could try revoking the Sensors permission from the relevant components including Phone and potentially other components to stop them using the proximity sensor.

**Comment by yaomtc** [comment]
Found the issue. Installed Sensors Multitool and found my proximity sensor is not functioning, even after a reboot. It always reads 0.0 cm. Maybe when I had my screen replaced last year the proximity sensor got messed up? Who knows.

**Comment by thestinger** [comment]
It's possible that it was damaged or it's possible that it's somehow being blocked. It could have gotten something on it or the screen could be a type of glass not allowing it to pass through properly.

You may be able to disable the Sensors permission for the Phone app and maybe certain other Phone-related components to stop this happening. You should try doing that.

**Comment by yaomtc** [comment]
I have, thank you. I just had my roommate call my phone and the phone interface for the incoming call came up for the first time in a while. I'll much rather have to manually turn off the screen than to not have a screen for the call at all.
