### ISSUE TITLE
Question/Improvement: deny Vanadium in secondary profile

### ISSUE THREAD

**Issue by h2dden** [GrapheneOS/os-issue-tracker#769]
I am looking to configure a secondary profile for a child: my son.
I love the option to disallow installing app in scondary profiles, so I can choose the apps running in the secondary profile.
I would also like to disable Vanadium, to deny web browsing to potentially unsafe web sites.
Would it be possible to achieve something like that?
I am thinking about disabling Vanadium in the owner profile, with the secondary profile following suit: basically denying re-enabling Vanadium in the secondary profile when the app is diabled in the owner profile

**Comment by thestinger** [comment]
You can disable Vanadium within the profile but they could enable it again. If you want to disable it in a way they can't enable it again, you need a device manager. The best approach is probably giving a device manager ownership of that user profile.

**Comment by thestinger** [comment]
Don't have a suggested device manager. You should ask in our offtopic Matrix room at a peak time when a lot of people are around (USA / Europe are awake).

**Comment by h2dden** [comment]
appreciated
