### ISSUE TITLE
High quality audio playback impossible (since Android 12)

### ISSUE THREAD

**Issue by NewRedsquare** [GrapheneOS/os-issue-tracker#770]
Since upgrade from A11 to A12, audiophile experience is messy. (now using SP1A.211105.004.2021110122 , Google Pixel 5)

At the moment, i found the issue while using my USB DACs (don't have bluetooth device to try for now)

I tried many music players (UAPP, PowerAmp, Hiby Music) but i can't get 24bits playback, it's locked to 16bits. Even if i "force" 24bits playback, it doesn't do anything. In the logs, it shows that "audio_hw_primary" is selecting the 16bits playback even if it is showing 24bits and 32bits profiles.

also, on some of the apps I can enable a "USB exclusive mode" for direct output to the DAC, which prompts a message to allow the app to "access" my USB DAC. After allowing it, it seems like the "authorization" i gave is ignored and the app can't do direct output to my usb DAC. 

Back to Android 11, i could achieve direct output without hassle. Now with A12, impossible.
I also tested with the same apps and same music files on a stock OS Pixel 4a with Android 12, audio playback is locked at the same frequency and same bitrate. But on the stock OS, the "USB bypass/exclusive mode" is working and isn't ignored (confirmed by music player)

**Comment by thestinger** [comment]
Please confirm if this is still an issue.

**Comment by Xarlith** [comment]
Not sure wheather it's the same bug but USB direct output does not work on Pixel 6.

It works only with the Android driver. As soon as the app tries to take a full control of the USB device the audio playback stops.

According to various sources and the UAPP developers the issue occurs also on stock A12 Pixel 6 roms. They claim it's "a kernel bug that only google can fix".

**Comment by flawedworld** [comment]
https://issuetracker.google.com/issues/210687963
https://issuetracker.google.com/issues/206461274

**Comment by flawedworld** [comment]
It seems like this may be a kernel issue introduced into all devices. It's unlikely that we will fix this ourselves.

**Comment by thestinger** [comment]
If there's any part of this that's specific to GrapheneOS and still occurs on the latest releases but not on the latest stock OS releases, please file a separate issue for it.

**Comment by flawedworld** [comment]
Google will fix this in June

**Comment by flawedworld** [comment]
June update will be released next week by Google.

**Comment by thestinger** [comment]
It's confirmed that the June update fixes this.

**Comment by sandriyishen** [comment]
Pixel 5 still in issue, not fixed. Tried with June update installed, helm bolt and creative sxfi amp with deezer, no go. Helm Bolt switches to red (hi-res) for a fraction of a second and goes back to blue (normal res) immediately.

**Comment by flawedworld** [comment]
@sandriyishen and this was on 2022060701 to confirm?

**Comment by sandriyishen** [comment]
@flawedworld 220605 update build. Just tried with Amazon Music and it works, so may be isolated to particular apps.

**Comment by Xarlith** [comment]
I tried with Neutron HiByMusic and UAPP. All worked perfectly fine.
Pixel 6, 22060701.
