### ISSUE TITLE
Feature request: elegant way of exchanging data between profiles

### ISSUE THREAD

**Issue by h2dden** [GrapheneOS/os-issue-tracker#771]
Currently, if I want to exchange data: text or files, between profiles I am sending a SMS (for text) or MMS (for files) making sure that any secondary profile has SMS enabled.
But this approach has many drawbacks: obvious drawbacks
Is there an elegant way of exchanging data between profiles while keeping the data on the device?

**Comment by thestinger** [comment]
You can transfer data over localhost.

**Comment by thestinger** [comment]
You could also at least use a secure way to do it if you're not going to do it locally.

**Comment by h2dden** [comment]
I do not know how to do it over localhost
You mean with a computer over usb?

**Comment by thestinger** [comment]
No.

**Comment by Zanthed** [comment]
No. On GrapheneOS, profiles can currently communicate between each other over localhost networking. Meaning networking only on the device itself via loopback.

There are apps that can open a simple HTTP server to transfer files. That might work.

**Comment by thestinger** [comment]
This should be done with an app.

**Comment by h2dden** [comment]
@Zanthed can you recommend an app?

**Comment by Zanthed** [comment]
No I cannot. I don't know any. Just look some up.

If you have Matrix, you can send images and others to yourself.
