### ISSUE TITLE
camera gesture "open with" not working after 2021110507

### ISSUE THREAD

**Issue by pkhomyakov-rms** [GrapheneOS/os-issue-tracker#774]
Pixel 5a, Build 2021110507 

It appears that either "replace AOSP Camera app with next-generation GrapheneOS Camera app" or "set GrapheneOS Camera app as the hard-wired handler for camera gesture" disabled ability to choose default camera. 

I had another 3rd party camera selected as "alway open" in one of the profiles, but after 2021110507 update camera power button shortcut always opens bundled OS camera app. There is no app choice dialog anymore in other profiles where multiple camera apps are enabled and "always open with" was not perviously selected.

For the record I have not had the issue camera gesture fix is expected to address. Had no problems with lock, camera app would always open fine with shortcut without prompting to unlock.

Writing this down in case the behavior is as expected (hard-wired kind of implies it is), it would be great to have ability to select camera app restored.

**Comment by thestinger** [comment]
It's intentional but we could undo it.

**Comment by thestinger** [comment]
We'll be reverting the workaround for a new Beta release in the near future. There's a real issue with the gesture on the lockscreen but it only happens when people install multiple camera apps. We'll leave it as it is for the time being.

**Comment by pkhomyakov-rms** [comment]
Tough call. I'd like to have the choice back. To me it outweighs any potential lock/unlock issues and the use is not limited to locked phone scenario, shortcut is expected to works from any place/app/screen when phone is unlocked as well.

I don't know how bad lock screen problems were for other folks though.

**Comment by thestinger** [comment]
The other issue is https://github.com/GrapheneOS/os-issue-tracker/issues/774 and was introduced in AOSP 12. It wasn't previously an issue. I'm not entirely sure what I want to do. The decision was basically made based on the assumption that most people would be happy with the new camera app and wouldn't mind it being the one launched with the gesture. However, the bug only occurs when people have multiple camera apps, and if people have everything they need from the OS one they could just remove the other(s).

**Comment by thestinger** [comment]
I think we'll revert the workaround in the upcoming release that's coming with some further improvements to the new Camera app based on feedback. If people don't need / want another camera app anymore they can always just remove the others and avoid that issue.

**Comment by pkhomyakov-rms** [comment]
Got it. Appreciate the awesome work you and the crew are doing!
