### ISSUE TITLE
Phone hangs, gets worse until unusable

### ISSUE THREAD

**Issue by Random-user23** [GrapheneOS/os-issue-tracker#775]
I just updated my phone, a google pixel 3xl to the most recent stable release of graphene. I'm facing an issue with the phone hanging.  When this initially occurs the phone might hang for a second, the next hang will be worse, eventually the phone freezes and must be restarted. The time that this takes to occur varies greatly, it seems to be dependent on use; if the phone sits idle or is used for very light tasks this issue may not even occur, other apps seems to cause it quickly. The apps that seem to cause issues are all the social media sort of apps i have on my phone, web browsing and a rather intensive gis/mapping app. This issue is brand new, it began occurring almost immediately after update and I've never faced it before.

**Comment by JanOstrowka** [comment]
I have been experiencing similar, occasional freezes.

---

Specification:
os: 2021110617
phone: Pixel 5

**Comment by thestinger** [comment]
Likely a hardware issue. It can't be reproduced. The Pixel 3 / 3 XL are legacy devices receiving extended support releases as a stopgap only.
