### ISSUE TITLE
Call "Timed Out" at Precisely 30 Minutes 0 seconds

### ISSUE THREAD

**Issue by ourichermath** [GrapheneOS/os-issue-tracker#776]
Today, at the exact 30 minute point of an absolutely normal call, my Pixel 3 XL just terminated the call.  Looking at the call screen, it said something like "No Response, Timed Out."  I tried redialing the number three times and all it would do is instantly hang up again (it didn't even dial -- I hit the number and it immediately went "be-bunk" and hung up).  I had to reboot the phone to dial the number again.  Looking at the "details" for that number, it shows the exact 30 minutes 0 seconds original call, three 0 seconds calls, and then the final 8 minute some odd seconds call.

Pixel 3 XL, GrapheneOS SP1A.210812.015.2021110122 (I assume it's fully up-to-date), T-Mobile

Unfortunately, I can't seem to find instructions for submitting logs (though I don't know how useful they'd be following the reboot).

**Comment by thestinger** [comment]
I don't think we'll be able to anything about this. It's likely a carrier-specific issue. Pixel 3 and 3 XL are also in extended support and not much is going to be done with them going forward.

**Comment by thestinger** [comment]
Please confirm if this is still an issue.

**Comment by ourichermath** [comment]
It hasn't repeated itself, and no one else has reported it, so I guess it was just a one time thing.

**Comment by thestinger** [comment]
Could be a carrier issue.
