### ISSUE TITLE
remove redundant libraries from 4th generation pixel devices 

### ISSUE THREAD

**Issue by randomhydrosol** [GrapheneOS/os-issue-tracker#777]
there are a few libraries in our vendor that stock does not have. these should be eventually removed. one example is we are building both 32 and 64-bit versions of the library but stock only has the 64-bit version 

this is extremely low priority as these do not cause any issues at all and cleaning them up wouldn't change anything other than the size of vendor.img

**Comment by thestinger** [comment]
Don't think we need an issue filed about this and it doesn't really matter.
