### ISSUE TITLE
GPS problems

### ISSUE THREAD

**Issue by ChickenThief** [GrapheneOS/os-issue-tracker#778]
I think this bug has been an issue for a few updates, I first noticed it on the stable os update that updated the GUI, but I don't have access to consistent wifi so I don't update very often. The GPS hasn't given me live data for a while now, it seems to be hours or days behind what my actual location is. 

I think it's related, but the update disabled my ability to use Tinder on Vanadium. Every time I open the site it loads the site until about the time the location services icon shows up on the notification bar on my screen. At that point it crashes Vanadium and I have to restart. Because Tinder is the open site in Vanadium, it crashes the app a second time. Trying to use location data does not crash Vanadium when I go to a site like Google maps, but it just loads forever rather than actually reading my location or letting me use the site. Deleting cookies, restarting my phone, and the usual fixes did not work. 

Firefox can use both Tinder, and Google maps, but the location data isn't live. So when I travel, both services think I am at my house. 

For the Human on the other side of the screen: Sorry I didn't report in a timely manner, I've been super busy and I had something of a workaround. I finally had time to report and I want to support the project. Thank you for the work you do, I appreciate it a lot.

**Comment by thestinger** [comment]
We already have https://github.com/GrapheneOS/os-issue-tracker/issues/635 filed.

**Comment by thestinger** [comment]
Please try using location *without* sandboxed Play services. We're aware that the sandboxed Play services compatibility layer doesn't have full support for Play services. Remove it and try Google Maps, Organic Maps, GPSTest and SatStat *without* sandboxed Play services. It should also work fine in Vanadium. Vanadium may have issues in secondary users, which is a known issue with Chromium.

We've been busy with many other things so extending the sandboxed Play services compatibility layer to better support certain things like this hasn't been a priority. We also aren't getting nearly any help despite expecting that people would be interested in contributing in these areas. Migrating to Android 12 greatly slowed down progress on this and we still have more to do based on that. It's not any recent regression but rather sandboxed Play services fully supports the Maps APIs but doesn't yet reliably provide a location via the geolocation APIs.

Please read the thread at https://twitter.com/GrapheneOS/status/1454427808835510275. It's more informative than stuff on the issue tracker about this.
