### ISSUE TITLE
Messaging app incorrectly flags valid text as containing spelling errors

### ISSUE THREAD

**Issue by ezeeman** [GrapheneOS/os-issue-tracker#779]
The Messaging app incorrectly flags every word ending a sentence followed by a dot and a single space as a spelling error. It did not do this in prior releases. Tapping each flagged word brings up a correction list containing the word without the terminating dot.

![Screenshot_20211107-092500_resize](https://user-images.githubusercontent.com/24552926/140656147-0f8f8dfa-e4c0-48b4-99d0-5f7c18d2c417.jpg)

OS version is 2021102300 SP1A.210812.015.2021102300 on a Pixel 4a.

**Comment by ezeeman** [comment]
I don't have a lot of apps installed. I tested protonmail and keypassxc but they don't seem to check spelling when I enter random characters. Please recommend a simple app that will give you the information you're looking for, and I'll install it and test.

My apologies for having submitted this issue in the wrong project.

**Comment by pkhomyakov-rms** [comment]
@thestinger looks like a dup of https://github.com/GrapheneOS/os-issue-tracker/issues/758

**Comment by thestinger** [comment]
Submitting it in the wrong project doesn't matter much.

**Comment by ezeeman** [comment]
Agreed, it's a dupe of https://github.com/GrapheneOS/os-issue-tracker/issues/758  and I should have commented on that one. Perhaps of interest, to help determine which commit it first appeared in, note that this only appeared a few days ago for me, while 758 was reported 12 days ago.
