### ISSUE TITLE
Capitalise First Letter not functioning since upgrading to Android 12

### ISSUE THREAD

**Issue by snrkl** [GrapheneOS/os-issue-tracker#781]
Build Number: SP1A.211105.004.2021110617
Hardware: Pixel 5

**What Happens:**
When typing a new sentence, the first letter of the entered text does not capitalise.

**What I Expect to Happen:**
The auto-correct function should capitalise the first character of the sentence.
 
**Steps to Reproduce:**
In Signal, email or any text entry dialogue, start typing:

"the quick. brown fox. jumps over"

![Screenshot_20211108-233044](https://user-images.githubusercontent.com/2288035/140750706-f5a26021-eafa-45f1-8661-edb2a8639c9f.png)

The text will remain unchanged, rather than auto capitalising to:
"The quick. Brown fox. Jumps over"

**Comment by flawedworld** [comment]
No longer a bug
