### ISSUE TITLE
Unhandled java.io.FileNotFound error when setting contact card photo from storage

### ISSUE THREAD

**Issue by rpdelaney** [GrapheneOS/os-issue-tracker#784]
When setting a contact photo by choosing an existing image from storage, I get a toast with:

```
java.io.FileNotFound error: No content provider: <path to image>
```

I tried converting the png image to jpg and there was no change. The image is not saved to the contact.

If I take the photo rather than choosing it from storage, the new photo is added correctly.

**Comment by flawedworld** [comment]
This no longer seems to be an issue.

**Comment by rpdelaney** [comment]
Unfortunately I'm still having problems:

https://user-images.githubusercontent.com/1139517/152237919-8c9368df-528a-40ab-9348-09cfe97673f3.mp4

**Comment by flawedworld** [comment]
This seems to be an issue with the file manager / contacts app you are using. They don't appear to be the apps shipped with the OS.
