### ISSUE TITLE
Voice search not available

### ISSUE THREAD

**Issue by JanOstrowka** [GrapheneOS/os-issue-tracker#788]
![image](https://user-images.githubusercontent.com/3185243/141120597-2d7a7dc6-345b-4cfa-9371-e03b86cc5b10.png)

Is there any purpose to the microphone icon, inside the search bar? When trying to use it (microphone enabled), I am getting an error visible above - "Voice search not available".

If it does not serve any purpose, it might be better to remove the icon, at least for now, since it does decrease the overall UX.

---

**Specification:**
os: 2021110617
phone: Pixel 5
app version: 23.0

**Comment by thestinger** [comment]
You need an app providing it. We're not going to remove the icon.

**Comment by JanOstrowka** [comment]
What is the name of the app required to make it work?

**Comment by thestinger** [comment]
As far as I know, it will work with any voice to text provider including Google's one. I don't use it myself and can't give any real advice.

**Comment by JanOstrowka** [comment]
Thanks for confirming I am not the target group of this feature 🙃

**Comment by thestinger** [comment]
There are likely some alternatives to Google's one but I haven't looked into it since I have no use for this myself. People may have better info in our Matrix room.
