### ISSUE TITLE
Bottom Sheet Share Menu - stuck on three fixed contacts

### ISSUE THREAD

**Issue by JanOstrowka** [GrapheneOS/os-issue-tracker#789]
![image](https://user-images.githubusercontent.com/3185243/141202596-325df062-8cbf-40a4-8e59-de4394979412.png)

When sharing something, the bottom sheet menu no longer gives relevant/recent contact as a recommendation. Instead, it is stuck on three contacts with whom I rarely/never speak, from a single app (in my case Signal).

The following feature has been very useful in previous Android 11 version, giving most recent contacts, across apps, as a recommendation.

---

**Specification:**
os: 2021110617
phone: Pixel 5

**Comment by flawedworld** [comment]
This doesn't appear to be an issue anymore, please comment if otherwise.
