### ISSUE TITLE
Material You - lack of "Wallpaper colors"

### ISSUE THREAD

**Issue by JanOstrowka** [GrapheneOS/os-issue-tracker#790]
![image](https://user-images.githubusercontent.com/3185243/141203590-ab7313d5-7b88-4641-8a7d-a6956f97763d.png)
(1) - current menu in Graphene OS, (2,3,4) - current menu in native Android 12

Is there any chance, that there might be one of the Android 12 flagship features, color customization, getting introduced? It would be nice to have the option to customize colors, on top of superior privacy and security features.

---

**Specification:**
os: 2021110617
phone: Pixel 5

**Comment by Zanthed** [comment]
A lot of Android customisation features are not actually upstreamed in AOSP yet and are simply apart of the OS that the vendor added in.

Android 12.1 will include a lot of similar features like these.

**Comment by JanOstrowka** [comment]
Too bad ☹️
Let's hope that supplementary features will be introduced shortly.

**Comment by Zanthed** [comment]
Some minor features will be added from ProtonAOSP by kdrag0n.

**Comment by flawedworld** [comment]
These features are not in AOSP 12. They will be a part of AOSP 12.1.
