### ISSUE TITLE
signify: invalid comment in blueline-factory-2021110617.zip; must start with 'untrusted comment: '

### ISSUE THREAD

**Issue by SvenMeyer** [GrapheneOS/os-issue-tracker#792]
I just downloaded `blueline-factory-2021110617.zip`

When doing `signify`, I got this message. Anything to worry about ?

```
$ signify -Cqp factory.pub -x blueline-factory-2021110617.zip && echo verified
signify: invalid comment in blueline-factory-2021110617.zip; must start with 'untrusted comment: '
```

**Comment by thestinger** [comment]
You're passing the zip to signify instead of the signature. Look at the install guide section for that again.

**Comment by SvenMeyer** [comment]
thanks - stupid mistake :-(
