### ISSUE TITLE
Gallery app: Clicking on settings results in black screen

### ISSUE THREAD

**Issue by camoz** [GrapheneOS/os-issue-tracker#794]
Hi,

I have GrapheneOS SP1A.211105.004.2021110617 installed on a Pixel 5.

When I open the default gallery app and click on the upper-right dot-menu, and then click on settings, I get a black screen.

**Comment by thestinger** [comment]
That's expected since there are simply no settings in the menu.

**Comment by thestinger** [comment]
We're planning on replacing this obsolete AOSP sample app with our own gallery as we did with the AOSP Camera app but it's going to be quite a while before that's ready.
