### ISSUE TITLE
Backup settings: Need to swipe back two times to get to the previous menu

### ISSUE THREAD

**Issue by camoz** [GrapheneOS/os-issue-tracker#797]
In `Settings -> System -> Backup`, to get to the previous menu I need to swipe back two times.

After the first swipe-back a new set of codes is chosen. Not sure if this is intentional, it seems like a bug to me (since for the feature "choose new random set of codes", a simple distinct button seems more intuitive).

I have GrapheneOS SP1A.211105.004.2021110617 installed on a Pixel 5.

**Comment by amojics** [comment]
Checked, unable to reproduce issue on Sargo, Build: SP1A.211105.002.2021111414

**Comment by thestinger** [comment]
It happens before it's set up. It might not happen after it's set up.

**Comment by r3g-5z** [comment]
This happens only before it's setup and is a Seedvault specific issue, happens in both SetupWizard and Settings. Seedvault is going to be replaced in the future and this is a super niche bug.

**Comment by thestinger** [comment]
We may also update it again before dropping it. This may or may not be fixed upstream already.
