### ISSUE TITLE
Rename advanced network setting "Use fully randomized MAC (default)"

### ISSUE THREAD

**Issue by camoz** [GrapheneOS/os-issue-tracker#798]
In the advanced options for a wi-fi network, the setting `Privacy` has 3 options available: "Use fully randomized MAC (default)", "Use per-network randomized MAC" and "Use device MAC".

IMO "Use fully randomized MAC (default)" is not a very descriptive name of the setting. It sounds like the MAC is "more" randomized than with other options. More intuitive would IMO be:

1) Use per-connection randomized MAC
2) Use per-network randomized MAC
3) Use device MAC

or

1) Randomize MAC per connection
2) Randomize MAC per network
3) Don't randomize MAC (use device MAC)

If you don't like the alternatives above (I'm not a native english speaker), please consider other alternatives before closing this issue. "Fully randomized" is really not very descriptive here. It's a bit fuzzy, and actually even suggests a wrong meaning here, as pointed out above.

Thanks!

**Comment by thestinger** [comment]
This is implemented.
