### ISSUE TITLE
Possible way to fingerprint devices using their available storage space

### ISSUE THREAD

**Issue by bigswag420** [GrapheneOS/os-issue-tracker#800]
Apps seem to be able to access the amount of available storage despite not granting them any storage permissions (Apple Music shows the available amount of storage within Settings > Download Options > Device Storage. It's only user-facing permission is Network), this could be used to fingerprint devices and correlate user profiles on a device.

For example, you have two profiles with the same app installed, and you decide to free up ~200 MB of storage, that app can see ~200 MB of storage was freed up. After you log on to the other profile, the app on the other profile can also see ~200 MB of storage was freed up. if the available amount of storage was the same across different profiles and differentiated the same amount across two profiles, the app could correlate those two profile over time.

**Comment by thestinger** [comment]
This can also be detected by just using the storage space. It also applies to web sites in web browsers. Without a proposal on how to address this, it's not a feature request. There needs to be a proposal on what could be done about to have it open an issue. It's not actionable right now.

**Comment by turquoispandabear10** [comment]
Some spitballed ideas:

One idea could be to allow an option to allocate a set amount of storage to a profile (if it could be modified after the fact that would be even better,  perhaps with a popup when the storage space getting full icon appears to increase it's size, or an easy setting in the owner profile to increase/decrease the storage sizes with a lock to prevent data being wiped if the space its made too small).  Then the 20 gigs allocated to a profile could be reported as the total space on the device.  This would be great for stopping tracking across profiles, though it would still present a problem tracking the same profile by websites based on the weird profile space sizing (Could be helped by increments of 5 gigs or something). Another component that could be added to mitigate this partially would be to always report the total storage space as a few gigs above what the current storage space is in that profile.  Or the device could lie about the storage space used, until it reaches the red/near full and becomes a problem, with the storage warning for the user earlier than the apps will find out, perhaps with some headroom.  This third thing is a little more hacky, so maybe a deeper off by default setting, but is a random storage value for different apps in the neighborhood of the true value randomly chosen from set increments but not the exact value, and that could change frequently.  A fourth option would be to just not report it if it's not a problem, and then just have a pop up if something is going to exceed the storage limit (and a fifth could be per app storage allocation).
