### ISSUE TITLE
[Upstream?] Accessibility -> Audio adjustments: Marker for neutral position not positioned on the middle

### ISSUE THREAD

**Issue by camoz** [GrapheneOS/os-issue-tracker#801]
In the settings menu `Accessibility -> Audio adjustments`, the L/R balance slider has a small vertical bar as a marker for the neutral position, which is not positioned exactly in the middle of the slider. The slider knob will snap to the middle position, which is (at least visually) exactly in the middle of the slider.

This may be an upstream issue.

**Comment by flawedworld** [comment]
Also affects the stock OS, closing as it's nothing something we are going to fix ourselves.
