### ISSUE TITLE
Keyboard settings: Rename option "personalised suggestions"

### ISSUE THREAD

**Issue by camoz** [GrapheneOS/os-issue-tracker#802]
This is not a real bug, more of an improvement, or actually a small nitpick. But I think it's important for option names to be as concise as possible, so here we go.

In `GrapheneOS Keyboard Settings -> Text correction`, one can configure a personal dictionary of words which will then be used for text correction. Thus, *personalized suggestions* are used by default.

However further down there is also an option toggle `Personalised suggestions`. When this is disabled, *personalized suggestions* are still used, via the custom dictionary that one can define manually. What this option actually does, is *automatically learn suggestions* from my communications and typing. To be more descriptive, this setting should be renamed to `Automatic personalisation`, or `Learn suggestions automatically`. I think `Automatic personalisation` is the most concise.

**Comment by thestinger** [comment]
No plans to change this since we plan on moving to a different keyboard.
