### ISSUE TITLE
Lockscreen: Add option for disabling or reducing the delay of the highlighting of button presses

### ISSUE THREAD

**Issue by camoz** [GrapheneOS/os-issue-tracker#803]
The key pad of the lock screen (where you enter your PIN to unlock the phone) highlights buttons when pressed. This highlight is a delayed animation; the buttons show an "afterglow" even if the finger is lifted from the touch screen.

When a 6-digit PIN is entered quickly, this results in all pressed buttons "glowing" at the same time (more or less bright, depending on when they were pressed). This makes shoulder-surfing a PIN code much more easy, as this "glowing pattern" is much easier to remember at a glance than a sequence of button presses.

An option to restrict the button highlight to the time the button is actually pressed (i.e. the finger has contact with the touch screen), or to disable the button highlight altogether would be nice.

This is (almost) only an issue with non-scrambled PIN key pads. Almost because with a scrambled PIN key pad, the "afterglow" of button presses could enable an attacker to shoulder-surf the PIN by taking a single photo of the scrambled PIN key pad with the respective buttons glowing. That would not be possible without the button "afterglow".

Tested on GrapheneOS SP1A.211105.004.2021110617 installed on a Pixel 5.

**Comment by thestinger** [comment]
Seems to be the same as https://github.com/GrapheneOS/os-issue-tracker/issues/588.
