### ISSUE TITLE
System ui crashed pixel 4

### ISSUE THREAD

**Issue by obyx386** [GrapheneOS/os-issue-tracker#805]
I keep getting messages saying the system ui crashed ever since the 12 update. Also sometimes when trying to unlock the screen the unlock slider just bops up and down a quick lock/unlock followed by a long swipe up fixes that normally. #
[bugreport-flame-SP1A.211105.004-2021-11-19-08-23-04-dumpstate_log-12449.txt](https://github.com/GrapheneOS/os-issue-tracker/files/7570569/bugreport-flame-SP1A.211105.004-2021-11-19-08-23-04-dumpstate_log-12449.txt)
`
[Uploading bugreport-flame-SP1A.211105.004-2021-11-19-08-23-04.zip…]()
`

**Comment by flawedworld** [comment]
See: https://github.com/GrapheneOS/os-issue-tracker/issues/738
