### ISSUE TITLE
Add a 'sensors off' toggle

### ISSUE THREAD

**Issue by svdm-artix** [GrapheneOS/os-issue-tracker#806]
There's an option available through the developer settings that adds an option to disable all sensors (Quick settings development tiles).

I think it'd be beneficial to be able to enable this toggle without having to enable the developer options.

**Comment by thestinger** [comment]
It doesn't make sense anymore due to the proper Camera and Microphone toggles. It would need to be redesigned to fit into the new system properly. This toggle never worked in a reasonable way.

**Comment by rhclayto** [comment]
> It doesn't make sense anymore due to the proper Camera and Microphone toggles. It would need to be redesigned to fit into the new system properly. This toggle never worked in a reasonable way.

Doesn't the toggle also turn off all sensors, such as gyros/accelerometer, etc., not just camera & microphone? https://source.android.com/devices/sensors/sensors-off

Given that there are at least theoretical leaks from those other sensors which don't have toggles, it would be nice to have this. I raised an issue (on the wrong repo, sorry) about making this available across all user profiles (currently it's only available in the main profile).

**Comment by thestinger** [comment]
This is a developer feature not intended for production use and is not designed in a sensible way for inclusion in the user interface. You aren't supposed to be using developer options in production.

**Comment by thestinger** [comment]
It does not make any sense to have a toggle overlapping with the Camera / Microphone toggles which perform their task in a superior, more compatible way. This sensors off toggle is strictly for developers to test their apps. A toggle for other sensors to go along with the Camera/Microphone toggles wouldn't be at all the same. There won't be any replacement or changes for this developer option. You're misunderstanding the purpose.

**Comment by thestinger** [comment]
It would be entirely possible / sensible to extend what the Location / Camera / Microphone toggles provide to Sensors but that's not what is being asked of us.

**Comment by rhclayto** [comment]
From Google's documentation, they suggest that in addition to being intended for developer use, it is also intended for end users: 'This feature helps developers test their app’s functionality in situations where those sensors become unavailable, and also gives users a way to control the sensors in their device.' from https://source.android.com/devices/sensors/sensors-off

However, I am opening a new issue to make a request for a 'sensors off' toggle independent of the reference implementation described at the linked page that is a more sensible, superior, more compatible way in the opinion of the GrapheneOS team.
