### ISSUE TITLE
Some apps are losing push notifications after time / update of google play services

### ISSUE THREAD

**Issue by chris42** [GrapheneOS/os-issue-tracker#807]
Hi there,
after seeing some others in the chat having issues with play service stopping to work for some apps, I decided to put an issue here.

Following happens on my device (Pixel 5, single owner profile with play services installed)
- Initial setup/install of play services as directed on the website
- Purge and reinstall of all apps that needs play services (Whatsapp, Molly, Gcam, Gboard, Next Spaceflight, banking apps)
- All worked as expected, notifications are on time
- After time / or after updating (I can't tell yet) Molly, Next Spaceflight and banking apps having troubles on notifications (e.g., missing them by hours, just notifying when opening or not notifying at all). However Whatsapp seems to work fine, but can't tell if it uses a fallback.
- "Other" play service things seem to work, like for camera or gboard. It just seems trouble with the notifications. Maybe the registration suffers in an update?

I do not know how to debug this, but willing to help here. Probably would need some guidance on how / what to log around this to make it useful for you?

**Comment by aymswick** [comment]
I'm also having this issue with Signal, which based on the GrapheneOS documentation/guide is an app which handles push notifications correctly (a foreground service which appears in the notification shade for polling). Initially I thought that I mistakenly installed/updated GMS, so I reinstalled from the graphene file server, which temporarily fixed push notifications. It appears the issue comes back after some time. I second @chris42 offer to help provide logs/debug info.

**Comment by thestinger** [comment]
> I'm also having this issue with Signal, which based on the GrapheneOS documentation/guide is an app which handles push notifications correctly (a foreground service which appears in the notification shade for polling). 

That's how it works when you don't have Play services so your post doesn't make sense.

**Comment by moodguru-arch** [comment]
I've noticed this issue also. P5 with play services correctly installed as per official guides. All works well for a period of time and then notifications appear to lag. A reinstall of Signal appears to temporarily fix the issue but then it returns. As a temporary fix, I'm using Molly FOSS (to bypass the Google play services requirements). Other notifications via Google play services appear ok but in honesty, other than protonmail, I don't require play services so it's hard to say for certain. Happy to provide any logs but I'm not sure where to start.

**Comment by aymswick** [comment]
> > I'm also having this issue with Signal, which based on the GrapheneOS documentation/guide is an app which handles push notifications correctly (a foreground service which appears in the notification shade for polling).
> 
> That's how it works when you don't have Play services so your post doesn't make sense.

Ah my apologies then, I am experiencing this issue with Signal + GrapheneOS Play Services. I mistakenly interpreted the info on GrapheneOS docs as "signal uses play services and the polling feature as a fallback simultaneously".

**Comment by thestinger** [comment]
You're still misunderstanding how it works. They have two different push implementations. They use FCM when available and otherwise push via their own server. They don't ever use polling. Please read https://grapheneos.org/faq#notifications.

**Comment by chris42** [comment]
Btw: since end of November I haven't updated play services. Molly with FCM implementation now seems to be out of sync again. Weirdly it seems to start with just delayed messages of a few minutes. I would have expected that FCM either is connected / receives on time or nothing.

**Comment by caveman1973** [comment]
I have Signal and Telegram installed in the Personal profile. Telegram stopped working. Signal continues to work normally.

In the Work profile I have ProtonMail and it works normally. Same for WhatsApp.

My guess it's the app's problem (in my case, Telegram) who's not using a fallback after an update.

**Comment by thestinger** [comment]
There are no known issues with this beyond users having a broken configuration. Please get supporti n our Matrix room.

**Comment by chris42** [comment]
I am a bit puzzled about this answer. I asked before, if there is any analysis I can do to help solve this issue... but now this is closed because a "broken configuration" is the issue?
How should it be configured and why is it working for a period of time, but getting worse after updates? (Yes I followed the install guide in the FAQ and it initially works).
So what should I now ask for in the chat or do to solve this?

**Comment by thestinger** [comment]
It's not getting better or worse. It has worked fine for a while without any reproducible/known issues with it. Not every FCM push is done as a high priority push waking the device immediately. FCM isn't always reliable on every network or in every region. It's also entirely possible you have an issue like installing apps before Google Play, or removing/reinstalling it, or one of the AOSP user/work profile issues if you uninstalled it in a different profile. This issue isn't actionable and as far as we can tell it's all fine. You're going to have to get support on Matrix where people can help debug the issue.

**Comment by thestinger** [comment]
If you remove Play, you have to reinstall all the apps depending on it for them to work reliably. In particular, avoid removing GSF unless you're going to reinstall everything else using it. Applies to GMS too, but to a lesser extent. Due to AOSP user/work profile bugs, removing an app in another profile can cause breakage in other profiles where it's installed because the OS can end up removing more than it should. It's beyond the scope of this issue and we can't track all the user/work profile issues on our tracker. It's being worked on upstream.

**Comment by chris42** [comment]
I understand all the issues regarding wrong installs of Play and installing apps afterwards. That's why I completely reset everything and than running into this issue.
Is there any way this can be properly analyzed? Like logging when FCM is active and receiving messages of if apps are properly registered?
It would be quite a waste to talk in the chat about it and just redo the install of Play - wait then for it to happen again - to then being told to redo the install of Play again.

**Comment by thestinger** [comment]
You could try to obtain logs but as we're unable to replicate it, you'll need to obtain useful logs with the right context. There may not be anything about it logged. It's a possibility that there's helpful information being logged, but that doesn't mean you'll be able to easily find it, and it doesn't mean we could use it to fix an issue if there is one. We can't leave the issue open because we can't replicate any issue and most users do not appear to have any issues with this.

**Comment by chris42** [comment]
Just for reference for anyone seeing this issue: It seems to be solved with the [2022052500](https://grapheneos.org/releases#2022052500) release. Monitored this in the last time and all messages seemed to be correct.

**Comment by thestinger** [comment]
If you remove GSF, then you need to reinstall most apps depending on it including Play services and the Play Store. That doesn't apply to removing / reinstalling Play Store and Play services. Just don't uninstall GSF within a profile where you use them. GSF is part of the base OS on devices with Google Play and is never not present so it's not handled.
