### ISSUE TITLE
Apps Not Syncing With Dark Theme

### ISSUE THREAD

**Issue by IJohnDoeI** [GrapheneOS/os-issue-tracker#808]
I hope this makes sense but none of my apps which are set to automatic for their display appearance (I.e. Dark/Light) are picking up on the system default at the time. 
If this happened with one or two apps then I would think it would be the apps fault but it is with all apps.

Using version SP1A.211105.004.2021111414.
Pixel 5

**Comment by thestinger** [comment]
This isn't actionable since you're not listing any specific apps or explaining in detail what's happening. The dark vs. light theme works for everyone else and isn't a GrapheneOS specific feature or something we change.

**Comment by thestinger** [comment]
Turn off developer options, reboot the device, explain if you've done anything with ADB, etc. and say which specific apps aren't working as examples after disabling developer options.
