### ISSUE TITLE
Pixel 4a camera preview black after Android12 update

### ISSUE THREAD

**Issue by 3xmblzj5** [GrapheneOS/os-issue-tracker#809]
Both the front and back camera previews show a black screen.
Do I have any options for fixing this, except reinstalling GrapheneOS?

**Comment by flawedworld** [comment]
You likely changed the global camera toggle.

Settings -> Privacy -> Camera access

Make sure the toggle is on.

**Comment by 3xmblzj5** [comment]
As you predicted, enabling Camera Access fixed the issue.
Thanks for the prompt response.
