### ISSUE TITLE
Legacy search activity can be opened from app drawer

### ISSUE THREAD

**Issue by e-zk** [GrapheneOS/os-issue-tracker#810]
In the app drawer if you touch the search bar then press the enter key twice (with or without typing anything) a legacy-styled search activity is launched.  
App info for the activity shows the "Search" application.

From this activity whatever you type in the search bar is opened in Google in whatever the default browser is set to.   
It might be worth noting the URL contains a source parameter: `source=android-launcher-search`.

**Comment by thestinger** [comment]
https://github.com/GrapheneOS/os-issue-tracker/issues/17 is already filed.
