### ISSUE TITLE
PIN scrambling with USB keyboard: correct PIN is not accepted, correct "screen position" works

### ISSUE THREAD

**Issue by alex-resist** [GrapheneOS/os-issue-tracker#811]
SItuation: keyboard plugged in via USB. Screen lock with PIN, PIN scrambling activated. Phone starting. Correct PIN is 3333 (just as an example, of course).

Expected outcome: entering 3333 on the USB keyboard unlocks phone

Observed outcome: entering the number where the 3 appears on screen unlocks phone. E.g., If the 3 appears at the 1 position, 1111 has to be entered, not 3333.

So the mapping of the USB keyboard is faulty when PIN scrambling is activated.

**Comment by Zanthed** [comment]
Should be solved in the next release.
