### ISSUE TITLE
Last update 2021112021 constatly crashes

### ISSUE THREAD

**Issue by akaun24** [GrapheneOS/os-issue-tracker#812]
So I have updated my phone this morning and it constantly crashes as soon as i open it. Sometimes within 5 seconds sometimes 30. If I leave the phone alone and don't unlock it it seems to be ok. The phone goes back to GrapheneOS logo. I tried restarting it nothings seems to help.

**Comment by thestinger** [comment]
You'll need to clarify what you mean by crashes.

**Comment by akaun24** [comment]
So after I unlock the phone, screen goes black and then GrapheneOS boot logo appears and it boots up again, like it was just restarted. So I unlock the phone again, after a few seconds again screen goes black and GrapheneOS boot logo appears, and it boots up again... and so on.

**Comment by akaun24** [comment]
Later on I will see if I can capture a rash report from Android Studio.

**Comment by thestinger** [comment]
Do you have sandboxed Play services installed?

Do you know which release you were on prior to 2021112021?

**Comment by akaun24** [comment]
I was on the one before this one, usually try to update as soon as update ready. Before the update I installed PlayServices just to check it out but then uninstalled.

**Comment by thestinger** [comment]
Did you fully uninstall all 3 apps? Is it possible you still have it partially installed? Trying to narrow down how it could possibly be tied to the 2021112021 update which primarily just added the expanded Play Store compatibility layer and updated some of our apps.

**Comment by akaun24** [comment]
Ok let me do some more digging when I have a minute and I will report back. Thank you.

**Comment by akaun24** [comment]
Sorry for late response. After that morning I haven't had any crashes since. So I am guessing all is good and what ever caused the crashes went away. If something comes back I will let you know. Thank you.

**Comment by SebastianBerlin** [comment]
Probably it's affiliated with this issue: 3 times so far (of a 2-day-old GrapheneOS-setup) the system crashes and reboots AFTER the device was booted and unlocked. It occurs 3-5 seconds after the unlock, than blackscreen and reboot.

**Comment by thestinger** [comment]
Doubt it's related. Could be a hardware issue. There's a new Beta channel release coming out soon.

**Comment by SebastianBerlin** [comment]
Thanks for the reply. I will keep an eye on it, if it happens again.
