### ISSUE TITLE
Quick Access Menu Long Press Regression

### ISSUE THREAD

**Issue by SenorFusion** [GrapheneOS/os-issue-tracker#813]
Problem: Long Pressing on Quick Access tiles does not show you to the corresponding menu anymore.

**Steps to reproduce:**
1. Pull down quick access menu
2. Long Press on BlueTooth Tile

**Expected Results:**
1. Taken to Bluetooth settings page

**Actual Results**
1. Quick Access menu just stays on the screen, the Bluetooth settings menu is not visible.

If you swipe up to close the quick access menu, you actually are on the correct page - The Bluetooth settings - but this is not obvious to the user because the Quick Access Menu did not automatically close after the long press. So it feels like you did not go anywhere.

This also applies to Internet, Hotspot, Location, and others.

This is true whether you pull it down for the small version or pull down again for the larger version of the Quick Access menu

I believe this has been happening since the very first update to 12. I am running the latest Stable Release, Pixel 5.

**Comment by thestinger** [comment]
Not able to reproduce this issue. Need more details on how you're triggering this.

**Comment by SenorFusion** [comment]
@thestinger  - Is there a log or something I can provide you that would be helpful?

Maybe I am using the wrong terms?

I'm talking about the menu that pulls down from the top, available on every screen. Maybe better called Notification Pulldown Menu?

1. I pull it down.
2. Long Press on the Bluetooth tile

Instead of taking me to the Bluetooth settings menu, the Notification menu stays on the screen.

**Comment by Zanthed** [comment]
I can't reproduce this. Long pressing the Bluetooth tile works just fine and I have a Pixel 5.

There's something weird we don't really know about or what to do here.

**Comment by thestinger** [comment]
@SenorFusion Disable developer options and any device managers or accessibility services.

**Comment by SenorFusion** [comment]
@thestinger - Disabling developer options worked.

I disable animations, because I hate them. That was causing this behavior.

Sorry for the false report.

Thanks!
