### ISSUE TITLE
Question - Could Graphene OS be run in virtual environment of VMOS?

### ISSUE THREAD

**Issue by jbrepogmailcom** [GrapheneOS/os-issue-tracker#814]
As per title. There are many ROMs for VMOS. Virtual Graphene OS could then be used to further enhance application security on any phone, not just Pixels.
Thank you.

**Comment by thestinger** [comment]
This isn't within the scope of the project.

**Comment by thestinger** [comment]
It's not capable of meeting the requirements needed for GrapheneOS. Using virtualisation within GrapheneOS makes sense but definitely not that kind of it.
