### ISSUE TITLE
Proot install ubuntu error

### ISSUE THREAD

**Issue by Guyv-dev** [GrapheneOS/os-issue-tracker#818]
I get an error when I try to install ubuntu through proot on termux. 
![Screenshot_20211123-220620](https://user-images.githubusercontent.com/72630667/143096653-1e56ae6a-7721-4458-949a-bfbcb0990ef4.png)

There is any solution for that?

**Comment by thestinger** [comment]
It looks like you disabled native debugging but are trying to use something depending on it.

**Comment by thestinger** [comment]
Please use the Matrix room for support.
