### ISSUE TITLE
[Request] Add support for Fairphone 3 and Fairphone 4

### ISSUE THREAD

**Issue by m1karii** [GrapheneOS/os-issue-tracker#820]
Title.

**Comment by Ammako** [comment]
Note: FP3 has no verified boot, but FP4 does.

**Comment by Zanthed** [comment]
Just because it has verified boot doesn't make it a valid contestor.

GrapheneOS will not in any way add support for insecure or poor security devices like these. They do not come close anywhere to Google Pixel level security and for it to even be _considered_ it needs to support basic security and all do them correctly.

#414 

Please read: https://grapheneos.org/faq#future-devices

**Comment by Zanthed** [comment]
New device support isn't of much interest either way besides Google Pixels because there isn't a device out there that meets Pixel level security.

**Comment by Ammako** [comment]
Just wanted to point out that FP3 would never ever be considered, is all.

**Comment by thestinger** [comment]
FP4 won't have full security updates for nearly long enough, doesn't have a secure element and is going to have other issues beyond that. It doesn't have sense to invest time in a device with less than 4 years of full security updates from launch at this point. They shouldn't have used an old SoC.

**Comment by thestinger** [comment]
FP4 won't have full security updates for nearly long enough, doesn't have a secure element and is going to have other issues beyond that. It doesn't have sense to invest time in a device with less than 4 years of full security updates from launch at this point. They shouldn't have used an old SoC where it's likely that less than 3 years of proper support is possible.

**Comment by jarri-abidi** [comment]
I get that SoCs are usually a problem but FairPhone actually committed to 5 years of software updates after launch. Also if you look at FairPhone 2 just as an example, it got updates for 7 years. 
I think we can expect similar things for FF4.

**Comment by Zanthed** [comment]
No they did not. They are falsely claiming such things and is maliciously misleading their customers and other journalists who don't know how support works. They are also not on Android 12.1 and you need to be using the latest Android version for full AOSP security patches *at the minimum*.

> No, it doesn't come close to meeting the security requirements. No secure element, likely no verified boot / attestation for an alternate OS and a lot of other issues. It's not their priority and without them providing that it's not an interesting device.

> It also uses an SoC from 2020 with 3 years of support so it only has 2 years of proper support remaining which is not good enough. The expectation is 4 years of support going forward. Their claim that they'll provide 5 years of updates is ignoring that they won't be able to provide full security support for 4/6 of those years they claim they'll support it.

> Please don't ask us to support devices not meeting the requirements.

We're not going to support insecure devices or devices sold by people maliciously misleading their customers into thinking they have full security patches, full support, etc.

**Comment by Zanthed** [comment]
https://grapheneos.org/faq#future-devices

**Comment by Evilhotdog** [comment]
> No they did not. They are falsely claiming such things and is maliciously misleading their customers and other journalists who don't know how support works. They are on Android 11 which is missing the latest security and privacy improvements.
> 
> > No, it doesn't come close to meeting the security requirements. No secure element, likely no verified boot / attestation for an alternate OS and a lot of other issues. It's not their priority and without them providing that it's not an interesting device.
> 
> > It also uses an SoC from 2020 with 3 years of support so it only has 2 years of proper support remaining which is not good enough. The expectation is 4 years of support going forward. Their claim that they'll provide 5 years of updates is ignoring that they won't be able to provide full security support for 4/6 of those years they claim they'll support it.
> 
> > Please don't ask us to support devices not meeting the requirements.
> 
> We're not going to support insecure devices or devices sold by people maliciously misleading their customers into thinking they have full security patches, full support, etc.

What makes you think they're lying about software support?

**Comment by akc3n** [comment]
@Evilhotdog 
> What makes you think they're lying about software support?

[This thread on Twitter explains everything.](https://twitter.com/DanielMicay/status/1444028533186117633) | [nitter](https://nitter.eu/DanielMicay/status/1444028533186117633)
