### ISSUE TITLE
add support for Play Store to install apps with obb data with restricted SAF storage permissions

### ISSUE THREAD

**Issue by flawedworld** [GrapheneOS/os-issue-tracker#821]
example app: https://play.google.com/store/apps/details?id=com.microsoft.office.officehubrow

**Comment by thestinger** [comment]
OBB is working when granted the permission, and since it's a legacy feature I don't think we want to focus on it. Apps are meant to be moving to Play Asset Delivery / Play Feature Delivery and this should get phased out over time.
