### ISSUE TITLE
Add a new permission to allow network sockets by IP address

### ISSUE THREAD

**Issue by msoxzw** [GrapheneOS/os-issue-tracker#822]
In order to circumvent DNS filtering for blocking ads, trackers and malware, some apps use built-in DNS, DNS over HTTPS, etc. to resolve domain names that should be blocked.

To fight against this behavior, I want to only allow network sockets by domain name, and add a new permission to also allow network sockets by IP address, and thus, apps without this permission granted have to resolve domain names via system DNS.

**Comment by thestinger** [comment]
This isn't how networking works and can't be implemented this way.

**Comment by thestinger** [comment]
There are no sockets based on domain name.

**Comment by msoxzw** [comment]
It seems that I need to elaborate my idea.

Without this permission:

Roughly, [`Socket(String host, int port)`](https://developer.android.com/reference/java/net/Socket#Socket(java.lang.String,%20int)) can be directly called by apps,
but [`Socket(InetAddress address, int port)`](https://developer.android.com/reference/java/net/Socket#Socket(java.net.InetAddress,%20int)) is disallowed to be called by apps

More specifically, [`getByAddress(byte[] addr)`](https://developer.android.com/reference/java/net/InetAddress#getByAddress(byte%5B%5D)) and [`getByAddress(String host, byte[] addr)`](https://developer.android.com/reference/java/net/InetAddress#getByAddress(java.lang.String,%20byte%5B%5D)) can not be called by apps,
but [`getAllByName(String host)`](https://developer.android.com/reference/java/net/InetAddress#getAllByName(java.lang.String)) and [`getByName(String host)`](https://developer.android.com/reference/java/net/InetAddress#getByName(java.lang.String)) are allowed to be called by app with additional inspection of hostname, since hostname could be an IP address, which is revealed by [OpenJDK source code](https://github.com/openjdk/jdk/blob/e9b36a83160d3c1fa79841692e9fadf336bf7954/src/java.base/share/classes/java/net/InetAddress.java#L1452).

**Comment by thestinger** [comment]
Client-side checks are not an appropriate way to enforce privacy or security features. It would be inherently broken and bypassed via using another API or library. It isn't correct and would be considered a security vulnerability if a feature could be bypassed that way. You have the wrong idea about how the permission model and networking function.
