### ISSUE TITLE
Clock app: Modify timer

### ISSUE THREAD

**Issue by Kembolowski** [GrapheneOS/os-issue-tracker#823]
### Problem statement
You can create many timers in the clock app and give them custom names. They are stored for later reuse.
It is possible to change the name afterwards by tapping on the displayed text.
But it is impossible to change the timer value (a tap on the displayed value starts/pauses the timer).
### Feature request
It would be nice to facilitate to change the timer value (e.g. by a long tap opening the time editor).

**Comment by Kembolowski** [comment]
Obviously there is an inconvenient workaround:
You can delete an existing timer and create a new one with identical name and the desired new value.

**Comment by thestinger** [comment]
We don't plan to add this. It should be added upstream.
