### ISSUE TITLE
Settings: Missing German translations

### ISSUE THREAD

**Issue by Kembolowski** [GrapheneOS/os-issue-tracker#824]
The settings app lacks German translations for many menu items such as
- `System -> System update`
- `Security -> Auto reboot`
- `Security -> USB accessories`
- `Security -> Enable native code debugging`

**Comment by thestinger** [comment]
Our additions / changes haven't been translated to other languages yet. At some point we'll need to implement a proper process for translations and build translation teams we can trust to do a good job.

**Comment by thestinger** [comment]
German would be one of the priorities since there are a lot of German users but we're not at that point yet.
