### ISSUE TITLE
incorrect reserved space for navigation appears when there's no SIM

### ISSUE THREAD

**Issue by xibeifenghenhaohe** [GrapheneOS/os-issue-tracker#825]
Device: Pixel 4a

OS Version: Latest beta as of 26/11/21 (has been an issue since a little after GOS A12 release)

Description: A black bar on the bottom of the screen (I presume this is referred to as display cutout) appears when a SIM card is not installed, and temporary workarounds only work as long as the device has not been rebooted. 

Steps to reproduce:
1. Uninstall/remove SIM card
2. Reboot

Temporary Workarounds (will be undone if reboot occurs): 
1. Switching to a user profiles
2. Switching to 3 button navigation & back to gesture navigation (credit to @omori:tchncs.de)

**Comment by Zanthed** [comment]
Please test if this is still an issue on the newest beta release.

**Comment by alex-resist** [comment]
Appears to be fixed (4a, latest beta, no SIM).

**Comment by thestinger** [comment]
Still reproducible for me.

**Comment by thestinger** [comment]
I have 1 of each device with nearly all not having a SIM so I can easily reproduce this.

**Comment by alex-resist** [comment]
Correct, it appeared to be fixed on 4a for a while but returned. It's also still present on other devices (4a 5G, 6). Apologies.

**Comment by xibeifenghenhaohe** [comment]
Minor Additions:

As of 11/03/22, the latest GOS beta strangely fixes the issue for the launcher (i.e. upon first glance), however it is evident the problem is still present when opening other apps. 

Better and easier temporary workaround (will have to do again after reboot - like the others in OP): rotate the screen horizontally then back up vertically.

**Comment by Zanthed** [comment]
Please report if this is still an issue after QPR3.

**Comment by thestinger** [comment]
This still happens.

**Comment by xibeifenghenhaohe** [comment]
No longer happens for me on 6a A13 pre-alpha. Close if anyone else can attest.

**Comment by thestinger** [comment]
Can reopen if it reoccurs on 13.

**Comment by alexanderfoerstel** [comment]
Gone for me as well, on 4a 5G and 6a. Hopefully for good.
