### ISSUE TITLE
Not receiving messages when using multiples accounts

### ISSUE THREAD

**Issue by n0sign4l-official** [GrapheneOS/os-issue-tracker#826]
Hi I am having issues in receiving messages in GrapheneOS. I have 3 accounts the owner, the guest and the one that i really use. I have enabled the box that enables that account to use SMS and calls, in fact he can send SMS and he can start calls and receive calls without any problem. The problem is that he cannot receive sms using that account. Messages are received only when I and the session of that account and i see those messages in the owner account. Is it possible to receive the sms also on the other account? 
(I am using Signal for sms in my account) 

Device: Pixel 3a
OS version: latest on stable channel

**Comment by thestinger** [comment]
Signal doesn't work for SMS on secondary users on Android in general. It's not specific to GrapheneOS.
