### ISSUE TITLE
Separate between Ring and notification volume

### ISSUE THREAD

**Issue by maupet** [GrapheneOS/os-issue-tracker#827]
It seems to be only one single slider to adjust ring and notification volume, i.e. it will affect both at the same time.
I would like to set different volumes for phone ring vs notifications.

Ideally, I would also be able to select between a few customizable sound profiles (e.g. normal volume settings, vibrate only, do not disturb).

Is that possible?

**Comment by thestinger** [comment]
We're not planning on changing how this works, especially since it changes between releases.

**Comment by thestinger** [comment]
You can easily toggle between the modes with the button at the top of the volume slider overlay. Press a volume button and tap the icon at the top. Isn't that what you're asking for already?

**Comment by maupet** [comment]
> You can easily toggle between the modes with the button at the top of the volume slider overlay. Press a volume button and tap the icon at the top. Isn't that what you're asking for already?

This would work regarding selecting the sound profile.

But still I haven't found a way to apply different volumes to phone ring vs notifications at the same time.

**Comment by thestinger** [comment]
You can't at least without using a different dialer, but I don't think it's something we want to implement.

**Comment by maupet** [comment]
So the only way I have to mute notifications (but not phone ring), would be to customize the Do Not Disturb mode and leave it enabled at all times, correct?

If that's the only option, I find that to be quite annoying, from an UX standpoint (I find it much more convenient how it is handled on Samsung phones for example, where you simply have separate volume sliders for ring and notifications).

**Comment by Zanthed** [comment]
It's a very low priority thing, if any at all, to solve. If someone wants to work on this themselves and send a patch to make this feature exist that badly, they are very welcome to do so.

**Comment by maupet** [comment]
Understood. I will accept this limitation and try to adjust myself to it. Thank you!

**Comment by Zanthed** [comment]
Do keep in mind that not all OEMs are the same and some features simply do not exist in AOSP and are extra features the vendor has implemented themselves. This could be one of those.

**Comment by VividLemon** [comment]
This is one of those things that kind of disgust me about ASOP. Ideally ASOP would have much more configurable per app settings, and configurable app-defined per category sounds. I'd say all major oem platforms have done this to some extent, and it really seems like a no-brainer for asop. Like, I don't see why I'm forced to get audible `teams` `likes and reactions` notifications just because I want to get phone calls
