### ISSUE TITLE
OS installer should check if board is a mass production variant

### ISSUE THREAD

**Issue by flawedworld** [GrapheneOS/os-issue-tracker#831]
Google Pixel devices declare their board variants in fastboot and board variants can be obtained via device props. An example is given below.

```
[ro.boot.hardware.revision]: [MP1.0]
[ro.boot.revision]: [MP1.0]
[ro.revision]: [MP1.0]
```

Rarely, users buy devices which are EVT, PVT, DVT or other pre-production/development variants from auction sites or flea markets  which are not for production usage and have hardware/firmware/software/security issues by their very nature. We should ensure that we warn users who may be running non MP hardware and implement such checks at installation time.

**Comment by thestinger** [comment]
I think it's enough that the OS shows it.

**Comment by thestinger** [comment]
They will find out once they install GrapheneOS.
