### ISSUE TITLE
Pixel 6: mobile network does not work

### ISSUE THREAD

**Issue by h2dden** [GrapheneOS/os-issue-tracker#832]
I am running GrapheneOS on Pixel 6 GB7N6
Mobile network (phone, sms, data) does not work, although in owner profile under Network and Internet/SIMs I can see the correct network name.
I have tried 2 different providers (sims): same result.
Phone calls do not work, sms are not sent
When checking data connection type, 3G is shown but not working

How can I provide logs for debugging?

**Comment by philippmuench** [comment]
I have the same experience.

**Comment by thestinger** [comment]
We don't have a modern APN database added to it yet so you need to manually configure your network.

**Comment by thestinger** [comment]
That's fully expected for this early stage.

**Comment by philippmuench** [comment]
> We don't have a modern APN database added to it yet so you need to manually configure your network.

Thats fine, thanks for the reply. Is there any guide how to do this?

**Comment by h2dden** [comment]
concur
