### ISSUE TITLE
Pixel 6: add back the double-tap to check phone

### ISSUE THREAD

**Issue by h2dden** [GrapheneOS/os-issue-tracker#833]
Under Settings/System/Gestures, Pixel 3 has an nice option Double tap to check phone
Would be nice to have this option in Pixel 6

**Comment by flawedworld** [comment]
This should be solved now in the 2021120117 release, please let us know if the issues persists after updating.

**Comment by h2dden** [comment]
works fine now

**Comment by lbdroid** [comment]
I see "tap to check phone", but not double-tap. Pixel 6 Pro running 2021122018.

**Comment by flawedworld** [comment]
> I see "tap to check phone", but not double-tap. Pixel 6 Pro running 2021122018.

double tap to wake works fine

**Comment by flawedworld** [comment]
the toggle is under Settings -> Display -> Lock screen -> Tap to check phone

**Comment by thestinger** [comment]
It's single tap on the Pixel 6 rather than double tap and that's just how it's supposed to be. You tap once and it turns on.

**Comment by h2dden** [comment]
is the issue at hand the semantics? Double or single tap, the issue has been resolved and the matter closed...

**Comment by lbdroid** [comment]
> It's single tap on the Pixel 6 rather than double tap and that's just how it's supposed to be. You tap once and it turns on.

That's too bad. Single tap is terrible and just trips all the time without intending it. Is it possible to implement double-tap to wake for it? Or is it a hardware limitation?

**Comment by thestinger** [comment]
I don't know if it's possible but it would definitely be non-trivial. It doesn't really trigger that much by accident since I think it has features like using the proximity sensor to check if it's in a pocket, etc. There's also lift to wake and lift to wake tends to have a lot more false positives.

**Comment by lbdroid** [comment]
It does a lot of unintended tripping for me, unfortunately. And for that matter, the proximity sensor on this device is terrible, can't hold the phone on my shoulder without the screen waking up and hitting buttons with the side of my face, but that would be definitely an upstream problem and probably not fixable without a hardware redesign.
