### ISSUE TITLE
Random occasional reboots

### ISSUE THREAD

**Issue by Pauler221** [GrapheneOS/os-issue-tracker#834]
Device: Pixel 4a running the lastest version of GrapheneOS.

Title says it all. I encounter random reboots. Auto reboot feature is switched off also rebooting after update installation is off as well. Also when the auto reboot feature is on let's say set to 8 hours sometimes the phone reboots randomly as well. I had it unlocked 5 minutes ago and it rebooted.

This issue persists since a longer time already. Like roughly 6-7 months.

**Comment by thestinger** [comment]
Not able to reproduce this and without specifics on your configuration, apps, etc. along with logs or other information we can't do anything about it.

**Comment by thestinger** [comment]
Could be a hardware issue so we can't keep it open without a specific cause in the OS.
