### ISSUE TITLE
Custom APN's not possible with US Carriers due to CarrierConfig and OS issues

### ISSUE THREAD

**Issue by flawedworld** [GrapheneOS/os-issue-tracker#835]
Our workaround their CarrierConfig restrictions seems to no longer work.

**Comment by telegraphene** [comment]
Issue of being unable to make or edit APNs on Graphene isn't specific to Verizon.

Using Mint, APNs come pre-configured from T-Mobile on Graphene. Graphene lets you make a new APN, or edit an existing APN, however any changes do not persist.

Amm interested in making a new APN on Graphene for IPv4 only, as all Mint pre-configured APNs have IPv6 enabled.

It is possible to use IPv4 only config for Mint, done so on another device that is not Graphene.

Propose altering this issue to be non-Verizon specific.

**Comment by sawft99** [comment]
I am not well versed in these things but based on a conversation I had with someone else it sounds related. I am on a Pixel 5a with Verizon. I can send and receive calls and I can send texts. But I don't seem to receive them. Is that what others are experiencing or are there different symptoms?

**Comment by SapientHetero** [comment]
> I am on a Pixel 5a with Verizon. I can send and receive calls and I can send texts.

Can you make and receive WiFi calls?

**Comment by cheeseyfish** [comment]
Pixel 6 Mint Mobile. Same issue.

**Comment by flawedworld** [comment]
@telegraphene @cheeseyfish Please try the 2022011009 release, it may fix your issues.

**Comment by flawedworld** [comment]
This appears to be resolved.

**Comment by sawft99** [comment]
I created #908. I can send and receive calls. I can send texts that are received. However, I am not getting any texts.
