### ISSUE TITLE
Pixel 6 Fingerprint Screen Lock Setup Crash

### ISSUE THREAD

**Issue by MaxHillebrand** [GrapheneOS/os-issue-tracker#836]
Testing `SD1A.210817.037.2021120117` on the Pixel 6.

When setting up a fingerprint screen lock, on the `Touch & hold the fingerprint sensor` screen, as soon as I hold my finger inside the sensor circle, the setup-process aborts and the screen locks. I can reliably reproduce.

**Comment by thestinger** [comment]
The under display fingerprint reader is going to require additional code. It's one of the 3 current limitations with the experimental Pixel 3 support. There's a list of them here: https://twitter.com/GrapheneOS/status/1466344485634420746.

**Comment by thestinger** [comment]
The under display fingerprint reader is going to require additional code. It's one of the 3 current limitations with the experimental Pixel 6 support. There's a list of the limitations here: https://twitter.com/GrapheneOS/status/1466344485634420746.

**Comment by thestinger** [comment]
There's an implementation of this made by one of the GrapheneOS developers (kdrag0n) as part of their own project (ProtonAOSP). It will likely be included and shipped as part of GrapheneOS in about a week. It probably already works properly but they aren't ready to make it public yet so it can't be included in our public releases. We've tested it locally and it works.

**Comment by MaxHillebrand** [comment]
Tested on SD1A.210817.037.2021120708, works properly now.

Thanks!
