### ISSUE TITLE
Widgets sporadically disappear in secondary profile

### ISSUE THREAD

**Issue by h2dden** [GrapheneOS/os-issue-tracker#837]
Running latest GrapheneOS on Pixel 6.
I am running several secondary profiles which I end when not needed. When I reactivate a secondary profile, from time to time, the clock widget disappears.
I have re added the widget several time, but then it disappears again, quite sporadically: no specific pattern

**Comment by thestinger** [comment]
https://github.com/GrapheneOS/os-issue-tracker/issues/453
