### ISSUE TITLE
eBay app barcode scanner not working

### ISSUE THREAD

**Issue by dasbootbee** [GrapheneOS/os-issue-tracker#838]
Sandboxed play services are installed from the GrapheneOS repository.  eBay app installed from Play Store.

When attempting to sell an item and scan a barcode nothing happens -- no barcode is detected.  When trying to to search for an item to buy using the barcode scanner functionality the following message appears: "The barcode detector has not completed downloading.  Please try again later."

I'm wondering if this functionality is coming from Play Services and support for it has not been added to GrapheneOS yet.

**Comment by thestinger** [comment]
They're likely using a Play services library that's not yet supported. Play services has a library for scanning barcodes and also OCR, etc.

**Comment by thestinger** [comment]
They may be using a Play services library that's not yet supported. Play services has a library for scanning barcodes and also OCR, etc. It's also possible that they use Play Store feature delivery to dynamically download the library and we don't have support for that yet.

**Comment by maximbaz** [comment]
I think I have a similar example from a government ID app, that cannot scan the ID card and writes a ton of these logs:

```
W SoloThreadMana: type=1400 audit(0.0:340157): avc: denied { search } for name="camera" dev="dm-16" ino=205 scontext=u:r:hal_camera_default:s0 tcontext=u:object_r:camera_vendor_data_file:s0 tclass=dir permissive=0
W DynamiteModule: Local module descriptor class for com.google.android.gms.vision.ocr not found.
I DynamiteModule: Considering local module com.google.android.gms.vision.ocr:0 and remote module com.google.android.gms.vision.ocr:0
```

I suspect it's the same root cause, or would you like me to create a separate tracking issue?

**Comment by Zanthed** [comment]
It's the same thing as said above; a Play Services OCR library using dynamite modules.

It might be looked into as it is related to dynamite modules and support could be added.
