### ISSUE TITLE
Graphene Web installer release download timeout

### ISSUE THREAD

**Issue by Bummsen** [GrapheneOS/os-issue-tracker#839]
I am trying to follow the web installer guide to boot GrapheneOS on a Lenovo m10 FHD PLUS LTE. 
When im trying to download the latest release of the image i get Error: Timeout of 10000 ms exceeded.
Shall i try to download the image elseware or keep trying at the web installer? 

![image](https://user-images.githubusercontent.com/95544909/144721282-a02fadb6-0b1b-46cd-a2a5-119b11ff4de8.png)

**Comment by louipc** [comment]
On Sat 04 Dec 2021 10:56 -0800, Bummsen wrote:
> I am trying to follow the web installer guide to boot GrapheneOS on a Lenovo m10 FHD PLUS LTE.

If I'm understanding correctly, that is not a supported device.
Please see https://grapheneos.org/faq#supported-devices

**Comment by Zanthed** [comment]
1. That's not a supported device.
2. If you're exceeding the timeout, that's a bad cable or faulty connection of somekind. In normal circumstances, you will never exceed the timeout and no one has ever had to exceed 10 seconds.

**Comment by thestinger** [comment]
Please use the Matrix room for support questions.

**Comment by Alexsrt8** [comment]
I’m having the same problem

**Comment by Alexsrt8** [comment]
![image](https://user-images.githubusercontent.com/102328195/160010294-ae8b2029-9408-41b2-872e-30f889f52500.jpg)
I have a pixel 6

**Comment by Zanthed** [comment]
Please ask for support in our Matrix room.

https://grapheneos.org/contact

**Comment by thestinger** [comment]
@Alexsrt8 You have an unreliable USB connection. You need to fix that in order to install. Use the USB-C to USB-C shipping with the device. Use another Android phone to run the web installer if you don't have another computer with reliable USB-C. Don't use a USB-A to USB-C cable from another product, most are non-standards-compliant.
