### ISSUE TITLE
Consistent Icons For: Clock, Contacts, Gallery, Messaging, Calculator, Phone Apps

### ISSUE THREAD

**Issue by kenktk** [GrapheneOS/os-issue-tracker#840]
Given that these applications are in someway modified by the GrapheneOS team, I believe that the application icons shall mimic other stock GrapheneOS applications. 

Provided below is a few potential icon alternatives for the specified applications above. The source for the icons is the same source as the other application icons. Material Icons > Sharp. This feature request does not ask that every application listed below be changed, but rather a call for consideration to which applications should/should not be changed. 

### Clock
![clockapp_icon](https://user-images.githubusercontent.com/82561022/144768934-f5f524cb-7613-481a-9711-47c34985f6c5.jpg)
### Clock Alternate
![clockapp_alt_icon](https://user-images.githubusercontent.com/82561022/144768951-c0adcd2e-99ec-42cb-a46f-4ec8a3519639.jpg)
### Contacts
![contacts_icon](https://user-images.githubusercontent.com/82561022/144768961-62c64744-8b12-474a-aa6e-0e48d57bab45.jpg)
### Gallery
![photos_icon](https://user-images.githubusercontent.com/82561022/144768997-1a85510c-4268-4bff-b424-349619325db9.jpg)
### Gallery Alternate
![photos_alt_icon](https://user-images.githubusercontent.com/82561022/144769004-7cbc5ea0-1f62-4812-95ef-1df1d9a3b954.jpg)
### Messaging
![sms_icon](https://user-images.githubusercontent.com/82561022/144769014-05964bbd-6003-47c1-9ed2-0eadcb965a2b.jpg)
### Messaging Alternate
![sms_alt_icon](https://user-images.githubusercontent.com/82561022/144769022-03b325c3-447b-435c-9b0b-e9a20fe56431.jpg)
### Messaging Alternate 2
![sms_alt2_icon](https://user-images.githubusercontent.com/82561022/144769028-af088d50-cb87-4018-8d96-e9caf57fe47f.jpg)
### Calculator
![calculate_icon](https://user-images.githubusercontent.com/82561022/144769041-31a2c3c6-a0cf-41cf-a75b-4927c16213ed.jpg)
### Phone
![phoneapp_icon](https://user-images.githubusercontent.com/82561022/144769064-4d2652e0-93f6-40f9-b936-f67ede405f5a.jpg)

**Comment by flawedworld** [comment]
Thank you for the suggestion! I have incorporated some Material icons for our apps, subject to peer review, they may find their way into a release at some point.
