### ISSUE TITLE
Bluetooth volume control not working as intended

### ISSUE THREAD

**Issue by Inthemorningsir** [GrapheneOS/os-issue-tracker#841]
Bluetooth devices connected to the phone are way too quiet.
Interestingly the volume on calls is as high as expected.
So it looks like a software problem since it's happening on several bluetooth devices and calls clearly demonstrate that the volume output can be higher.

Several solutions are offered online (disabling absolute volume, A2DP offload, ...), as it seems to be a regular occurrence for android users, none of which work however.

It might be a EU volume limit issue, but I can't seem to find an option to change region settings or any other controls or information about that whatsoever.

I'm sure there's an incredibly easy fix, please help me find it.

Thanks!

**Comment by thestinger** [comment]
Please ask for support in our Matrix room. We're unable to provide it on the issue tracker.

https://grapheneos.org/contact#community
