### ISSUE TITLE
System Should Be Pitch Black to Conserve Battery Life

### ISSUE THREAD

**Issue by caveman1973** [GrapheneOS/os-issue-tracker#842]
GrapheneOS is not taking advantage of the OLED screen present in Pixel phones. There are places it should be pitch black instead of dark grey.

- System Settings
- Apps list

Other areas that are not important:
- Vanadium
- Messaging (dark mode missing)

**Comment by thestinger** [comment]
Reducing screen power usage by 1% in places that are hardly ever open won't save any significant amount of power.

**Comment by thestinger** [comment]
https://www.xda-developers.com/amoled-black-vs-gray-dark-mode/

**Comment by caveman1973** [comment]
Had no idea the savings were so negligent. According to the article, the savings is 0.3% compared to dark grey.

**Comment by D3vTs4113** [comment]
> Had no idea the savings were so negligent. According to the article, the savings is 0.3% compared to dark grey.

For my it's not only the reason for saving battery it's also because I hate the gray from the standard dark mode I wanted to know if we have the possiblity to switch to a true dark mode with black color on al UI

**Comment by D3vTs4113** [comment]
> It is a true dark mode. Dark mode doesn't mean every single background is `#000000`.

Yes I know but on LineageOS, all UI have a black background and I prefere this, I know it's very stupid request but I wanted to know if it's possible to add this on the next update or just tell us which file edit and just change gray color and add #000000

**Comment by tamis-laan** [comment]
Hey I just moved from Lineage OS to Graphene OS and I must say Graphene OS is just amazing! I think it ticks all the boxes and more compared to Lineage OS. The only thing that is lacking in my humble opinion is the pure black dark mode that Lineage OS support. I know it doesn't significantly improve the battery life. But it makes the phone look 100x better given for example the 8a pixel with its bezels. They just blend in very nicely. The same pure black theme on Lineage OS extends to the calculator dial-er contacts etc. 

Now of course functionality is the most important aspect and I will keep using the GOS regardless, but I think adding pure black dark mode would make a great addition to GOS. I know it doesn't look import to some, but what the eye sees is import to many people.
