### ISSUE TITLE
Provide (Shelter-like) fake camera as second system camera

### ISSUE THREAD

**Issue by codethief** [GrapheneOS/os-issue-tracker#843]
Since Android 11, apps cannot provide an alternative camera anymore. Instead, camera apps need to be pre-installed as system applications. Unfortunately, this also means things like [Shelter's fake camera no longer work](https://github.com/PeterCxy/Shelter/issues/162). This is a real shame – for years I was using the fake camera to select photos via the Documents UI even from within apps that refused to cooperate with the Documents UI and instead demanded full storage access. 

Now I'm not willing to grant them such access for two reasons:
- Even though they live in my work profile, other apps (in the work profile) might have written sensitive information to storage and I want to keep the attack surface as small as possible.
- Granting access to the work profile's storage doesn't exactly help if all my photos are in my personal profile, anyway. The nice thing about the fake camera was that it allowed me to switch between work and personal profile and select files from either.

It would therefore be great if such a fake camera could be incorporated into GrapheneOS as the only solution right now seems to be to not use those apps at all.

**Comment by flexagoon** [comment]
Is this still needed with the GrapheneOS storage scopes feature?

**Comment by codethief** [comment]
@flexagoon I've found Scoped Storage to be rather cumbersome to work with but you're right, strictly speaking it now provides an alternative.

**Comment by thestinger** [comment]
Closing in favor of https://github.com/GrapheneOS/os-issue-tracker/issues/2135.
