### ISSUE TITLE
Settings app shows default Wi-Fi MAC randomization after reboot even though the setting persists properly

### ISSUE THREAD

**Issue by alex-resist** [GrapheneOS/os-issue-tracker#847]
Steps to reproduce: connect to a WiFi. Switch to "per-network randomized MAC" for this WiFi. Reboot phone. Reconnect WiFi.

Expected outcome: "per-network randomized MAC" setting persists

Observed outcome: setting is reverted to the default "per-connection randomized MAC".

Reported on sunfish, confirmed on raven. Latest available stable GOS release.

**Comment by thestinger** [comment]
The setting doesn't appear to be reverted or lost as you can see from the randomized MAC field in the connection details below.

**Comment by alex-resist** [comment]
Duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/830
