### ISSUE TITLE
expose setting for enabling wiping after failed attempts without device manager

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/os-issue-tracker#85]

**Comment by jengo9332** [comment]
@thestinger, @renlord, you guys see any issues with this commit?

https://github.com/Test-AOSP/platform_packages_apps_Settings/commit/87f4ccf71299bcd80b7b055d8974763f98c77fab

**Comment by thestinger** [comment]
We're currently working on the migration to Android 11 and new features can't be developed or reviewed until it's finished, sorry.

**Comment by jengo9332** [comment]
Alright, np. I'll add the base commit here for future reference:
https://github.com/Test-AOSP/platform_frameworks_base/commit/4c2c2dbd3329a7627378a16e341269b92911f562

**Comment by jengo9332** [comment]
@thestinger Just checking in to see if this is the way the project wants to implement this feature.

**Comment by thestinger** [comment]
Does not appear to be a good idea without proper hardware support since it's too easy to bypass. See https://grapheneos.org/faq#encryption about the existing hardware support quickly throttling attempts to 1 per day.
