### ISSUE TITLE
Feature request: Option to increase touch sensitivity

### ISSUE THREAD

**Issue by dephekt** [GrapheneOS/os-issue-tracker#852]
On stock Pixels (at least on my 5a) there's an option to "Increase touch sensitivity" which is particularly useful when using tempered glass screen protectors. Without it, I regularly have issues where key taps are not registered. After switching to stock for a week with this setting enabled, I didn't have to fundamentally change how I type at all, everything just worked as if I didn't have a screen protector.

I brought this up in Matrix and saw someone else mention it today and one moderator seemed to think this would be relatively trivial to add, so I figured I would create an issue here so the request can actually be tracked and discussed and either approved or shot down.

After doing some searching, it seems at least tangentially related to #456. I couldn't find any follow-up issue to that one, so apologies in advance if I'm duplicating an issue here.

**Comment by flawedworld** [comment]
@dephekt Added to Pixel 6 and 6 Pro

**Comment by flawedworld** [comment]
Pixel 4a, 4, 4 XL, 4a 5G, 5, 5a, 6 and 6 Pro have this implemented now.
