### ISSUE TITLE
Play Store compatibility layer: Allow Google Play Protect to be turned off

### ISSUE THREAD

**Issue by jorgeluiscarrillo** [GrapheneOS/os-issue-tracker#855]
Seems like we are missing shims to allow this setting to be turned off. It is unclear whether the feature actually works or not.

**Comment by thestinger** [comment]
Please confirm if this is still an issue. I can't disable it for my account due to Advanced Protection.

**Comment by jorgeluiscarrillo** [comment]
When sandboxed Google Play is first installed, there is a notification that Google Play Protect is turned on. However, it seems like it turns itself off eventually. I don't recall if this behavior is different from when this issue was first filed.

However, now when I try to turn it on, it won't turn on. The Play Protect buttons and toggles just briefly switch to the on state before going back off. Note that I am not signed in to an account, but it shouldn't matter from what I remember from the stock OS.

When trying to turn it on, there aren't really any useful logs either:
```
02-19 11:35:42.492 17312 17358 I Finsky  : [25] VerifyInstalledPackagesTask.o(2): Verifying installed packages
02-19 11:35:42.543 17312 18985 I Finsky  : [222] vzg.a(4): Cleaning the verify apps datastore
02-19 11:35:42.550 17312 18985 I Finsky  : [222] vzg.a(51): Finished cleaning the verify apps datastore
02-19 11:35:42.559 17312 17312 I Finsky  : [2] vyy.accept(6): Done verifying installed packages
```

**Comment by yu-re-ka** [comment]
> Please confirm if this is still an issue. I can't disable it for my account due to Advanced Protection.

I can confirm this is still an issue. I tap the toggle "Scan apps with Play Protect" in "Play Protect settings". I confirm the dialog with "Turn off". But the toggle is still active.

**Comment by BluePixel4k** [comment]
This bug still exist, I can confirm this behavior.

**Comment by Ilithy** [comment]
>It's completely a visual thing

Do you really think so? the fact that Google can (without our consent) scan our applications and send a report containing this information seems very problematic to me on an OS that is supposed to protect the privacy of these users, doesn't it?

Don't see it as aggression, just worried questioning
Thanks.

**Comment by thestinger** [comment]
@Ilithy That has nothing at all to do with a toggle within the app.

**Comment by thestinger** [comment]
@Ilithy Every app can detect the other apps in the same profile. That's how the application model works. It has nothing to do with Play services or this toggle. The Play Protect toggle is within the app and has nothing to do with what it can access. Disabling it won't mean it stops collecting a list of apps within the same profile. Since it's a regular sandboxed app it can't see the overall apps installed on the phone. It's off topic and shouldn't be discussed here.
