### ISSUE TITLE
Low priority: Android easter egg not working properly

### ISSUE THREAD

**Issue by Pauler221** [GrapheneOS/os-issue-tracker#856]
Pressing on "Toy" under cat controls says "cat attracted" but no cat is actually popping up (No notification). Also filling water and bowl doesn't attract any cats like it used to. 
Furthermore the following message pops up frequently: "Android S easter egg has stopped working".

**Comment by thestinger** [comment]
We're not going to be fixing this. It could be disabled if it's not working anymore.
