### ISSUE TITLE
Network tile can be pressed while phone is locked and related settings can be changed from lockscreen

### ISSUE THREAD

**Issue by Pauler221** [GrapheneOS/os-issue-tracker#857]
It's possible to change the network state from the lockscreen like switching WiFi on and off and also switching mobile data on and off. Isn't this a quite sensitive setting in contrast to other ones?

This possibility persists while other not so sensitive settings cannot be changed from the lockscreen like Bluetooth and Airplane mode. 

Is this intended behavior?

**Comment by thestinger** [comment]
It's intended behavior as part of the first Android 12 quarterly release. GrapheneOS has restricted it as part of our next update.
