### ISSUE TITLE
SIP in AOSP dialer disabled since Android 12

### ISSUE THREAD

**Issue by alex8065** [GrapheneOS/os-issue-tracker#858]
Would it be possible to reenable this feature? 

https://developer.android.com/reference/kotlin/android/net/sip/SipManager is deprecated but still in tree as  far as I can tell.

**Comment by Zanthed** [comment]
Android 12 deprecates SIP entirely from their Dialer app, both the AOSP Dialer and Google Dialer apps.

It will not come back. Use a different app for SIP.

**Comment by jekkos** [comment]
Hi, I have created a PR to re-enable this functionality, I hope maintainers here can consider to merge it. [The functionality is only disabled in one repo](https://android-review.googlesource.com/q/topic:%22sip-removal%22), so enabling it back should be straightforward

**Comment by thestinger** [comment]
The repository you made a change to isn't used anymore.

**Comment by jekkos** [comment]
Indeed but it might only be a matter to add it back to the manifest? I see now the official AOSP one is in use. Adding this change means the project needs to fork it back again?

**Comment by thestinger** [comment]
You're modifying the Android 12 code and Android 13 is the only actively developed branch of GrapheneOS. We don't want to add back legacy code that's no longer maintained and you're also assuming that the code hasn't rotted away. It's likely going to get completely removed in the near future if it hasn't been already. The proper approach is using a SIP client that's actively developed.
