### ISSUE TITLE
Screen goes black and unresponsive when using Jitsi

### ISSUE THREAD

**Issue by mobiusgoesabove** [GrapheneOS/os-issue-tracker#859]
This issue has been reproduced several times on multiple Pixel 4XL devices. When using the Jitsi Meet client (downloaded from f-droid, version 21.4.1 build 8662254), when I go to "Start Screen Sharing", after a couple minutes of sharing my screen during a meeting, my screen will all of a sudden go black and unresponsive. Power/volume buttons do not wake the screen up. It typically takes about 3-5 minutes for the screen to recover, however, during the same call, if screen sharing is used again, the screen will eventually become unresponsive again.

GrapheneOS: Build number SQ1A.211205.008.2021220717

**Comment by Zanthed** [comment]
Please report back if this is still an issue on the latest release of GrapheneOS which is now on 12L (12.1).
