### ISSUE TITLE
Pixel 6 GPS not working

### ISSUE THREAD

**Issue by MrHomer2** [GrapheneOS/os-issue-tracker#861]
os version: SD1A.210817.037.202112117
I can enable GPS and disable it, Use Bluetooth and WLAN. However, no app gets any Location data. Yes I have tried any permuation (approx, precise, one time, when the app is running).
If you can tell me what soft of tests I should run to rule out that the issue is with the phone then I can do that.

Thank you very much for your efforts.

**Comment by thestinger** [comment]
GPS is known to work fine on the Pixel 6 and Pixel 6 Pro. Make sure you're testing outside and be aware it will take a very long time to get an initial location lock if you don't have A-GPS via a cellular connection. Use GPSTest/SatStat to monitor it.

**Comment by MrHomer2** [comment]
Thank you for the app recommendations.
It works fine seems to have been solved by either restarting or patience (took about 5 min)

Thank you and sorry for wasting your time.
