### ISSUE TITLE
[feature] Disable 5g (privacy), but keep older 2g, 3g and LTE

### ISSUE THREAD

**Issue by jonathancross** [GrapheneOS/os-issue-tracker#862]
[5g allow for extremely precise location triangulation](https://www.fastcompany.com/90314058/5g-means-youll-have-to-say-goodbye-to-your-location-privacy) of user devices.  Some see this as a privacy concern.
We currently have an [LTE-only mode](https://grapheneos.org/usage#lte-only-mode), but it would be great if this was extended to provide more granular control.  Specifically -- allowing 2g and 3g (useful for situations with weak signals / far from cell towers), but still allowing 5g to be completely disabled.

**Comment by thestinger** [comment]
That's already what the standard 4G mode provides.

**Comment by Zanthed** [comment]
2G and 3G infrastructure is going away very soon and should not be relied on.

**Comment by jonathancross** [comment]
> That's already what the standard 4G mode provides.

Not really: _but keep older 2g, 3g..._

> 2G and 3G infrastructure is going away very soon

Out in the countryside where I travel, 3g is still very common, LTE being an _exception_.

**Comment by thestinger** [comment]
> Not really: but keep older 2g, 3g...

Again, that's what the standard 4G mode provides. You simply want the standard 4G mode rather than the 4G only mode added by GrapheneOS. Have you looked at the preferred network mode configuration? 4G and 4G only are separate modes. 4G only is what's added by GrapheneOS. You're asking for something that's fully supported even in AOSP and the stock Pixel OS.

**Comment by thestinger** [comment]
GrapheneOS supports the preferred network mode configuration across all carriers rather than having it disabled on certain carriers. Other than that, the feature you want is a standard AOSP one present in the stock Pixel OS.

**Comment by jonathancross** [comment]
Are you saying that "Preferred = 4G" is the same as "Absolutely never use 5G"?
The latter is what I'm looking for.

**Comment by thestinger** [comment]
That's what it means, 4G or below.

**Comment by lbdroid** [comment]
The codes in that list map to network selection preferences. You can see better details of the available mappings by running the dialer code *#*#4636#*#*, selecting "phone information", and looking in the "set preferred network type" field.

LTE --> GSM/WCDMA/LTE (PRL)
LTE only --> LTE only
