### ISSUE TITLE
Screenshot preview shows low resolution screenshot during editing

### ISSUE THREAD

**Issue by shibattor** [GrapheneOS/os-issue-tracker#864]
**StR**
1. take screenshot (hold power button + volume down for a few seconds)
2. click on the right (pencil) button shown next to the new screenshot at the bottom left corner

Actual result:
![2021-12-13-205646](https://user-images.githubusercontent.com/87258997/145880068-473c8210-ea04-4a5b-98f8-1624f57d232e.png)

The screenshot itself is fine.

**Comment by thestinger** [comment]
This is an AOSP Gallery app limitation that we consider part of https://github.com/GrapheneOS/os-issue-tracker/issues/48.

**Comment by thestinger** [comment]
Note that you can already install and select a different app as your photo editing app.
