### ISSUE TITLE
Home screen and multitasking glitched, can't open drawer

### ISSUE THREAD

**Issue by novocaiin** [GrapheneOS/os-issue-tracker#866]
Happens often enough to be annoying and renders the phone unusable, so I've finally decided to report this after 3 fresh installs.

Every once in a while, the navbar gets all messed up, I can't swipe up from anywhere (or I can but it's all glitchy), left-drag to open task view, swipe up from home screen to open the app drawer.
All the icons *usually* disappear from home screen too.

Basically, the only way to open apps is through Settings.

A reboot fixes it for a while until it starts happening again.
Switching profiles doesn't fix it, although the other profile works fine.

https://user-images.githubusercontent.com/95007229/145887294-d1539d7c-6241-4054-98bc-68cba2316398.mp4

https://user-images.githubusercontent.com/95007229/145887346-34b35162-d41d-4568-b8d0-99b455f68d2d.mp4

I have not been able to pinpoint what causes this.
As I said, I've reinstalled GOS multiple times, and this keeps returning.

I'm using a Pixel 5 on the stable update channel.

The first time this happened I was asked on the Matrix channel to report this if it happens again, so here I am!
I have a couple logcats of this from different times, varying in size (70 lines all the way to 70k).
Let me know if I should post them.

**Comment by novocaiin** [comment]
Just following up to make sure this wasn't caught in the spam filter, since it hasn't received any labels, and I remember it getting marked as "Spammy" at some point.

**Comment by thestinger** [comment]
There's no spam filter.

**Comment by thestinger** [comment]
There's no spam filter. GitHub might shadow ban accounts but that's unusual and it wouldn't be specific to us.

**Comment by h2dden** [comment]
happens to me too on Pixelv6, but my fix is to end the secondary profile session and then to bring it up again.
annoying though

**Comment by novocaiin** [comment]
> happens to me too on Pixelv6, but my fix is to end the secondary profile session and then to bring it up again. annoying though

What if it happens in the owner (which it does for me more often than in secondaries)?

**Comment by h2dden** [comment]
I have notice it in the owner profile too, even with the latest, production release
For me the solution is either reboot, or ignore it forca while and work in a secondary profile.
I have noticed that even when the owner profile is frozen, secondary profile can work just fine
Eventually, a reboot is needed

**Comment by thestinger** [comment]
Not reproducible. Please let us know if this is still an issue on 12.1.

**Comment by novocaiin** [comment]
@thestinger still an issue on the latest release.
I think in order to reproduce you need to not open a profile (user or owner) for a bit (1hr+), then switch to it.

**Comment by h2dden** [comment]
this is a video showing the owner profile "frozen"
the video is stored for 12 on riseup.
if you need to re upload, let me know
https://share.riseup.net/#fK0qO9uzIaq0b50UNULl4g

**Comment by h2dden** [comment]
check this one out
in the "frozen" state in the owner profile, somehow the drawer pops up, but then when I tap Vanadium, Clock pops up
https://share.riseup.net/#RrxmJCTNvPAUo6ynKcBKEQ

**Comment by flawedworld** [comment]
If you are encountering this issue, are you using a 3rd party launcher?

**Comment by h2dden** [comment]
no. no 3rd party launcher

**Comment by h2dden** [comment]
especially in the owner profile: there is no app or customization

**Comment by novocaiin** [comment]
No 3rd party launcher.
Play Store in user, no Play Store in owner.

**Comment by flawedworld** [comment]
Please capture logs via ADB logcat when reproducing this issue and provide them to me on matrix on @flawedworld:matrix.org or email them to contact@grapheneos.org if that's not possible, thanks.

**Comment by h2dden** [comment]
@flawedworld not my intention to hijack the discussion here, but to whom do you refer?

**Comment by flawedworld** [comment]
All of you. Anyone who is affected by this.

**Comment by Zanthed** [comment]
Please report if this is still an issue after QPR3.

**Comment by git-human-github** [comment]
I came to re-open this issue. I had this bugged "app drawer" for a few automatic updates now, it's never gone away. I have the same symptoms as the original issuer. I can access settings, or the notification drop-down. But I still can't swipe up or down to access the "app drawer". Sometimes the apps on the bottom home-row will stay, but it's inconsistent, and will disappear if you mess with it while the app drawer is bugged. Switching profiles doesn't fix the problem, and restart will only workaround the problem temporarily.
