### ISSUE TITLE
monolithic kernel builds for 6th generation Pixel devices

### ISSUE THREAD

**Issue by flawedworld** [GrapheneOS/os-issue-tracker#870]

**Comment by xandfury** [comment]
Has anyone achieved this so far?

**Comment by flawedworld** [comment]
I'm aware that it has been done possible, but, our key concern is maintainability, in my personal view, we likely won't be doing monolithic kernels for GKI devices, unless we have a clear means to having them with a very low maintenance overhead.

**Comment by thestinger** [comment]
Not currently planned.
