### ISSUE TITLE
[Pixel 6] High battery drain due to mobile network and Wi-Fi

### ISSUE THREAD

**Issue by Anth0rx** [GrapheneOS/os-issue-tracker#872]
I noticed a big amount of battery drain attributed to mobile data and Wi-Fi (see screenshot). Is this normal to other Pixel 6 (Pro) users?

I am currently on the beta channel (build number SQ1D.211205.017.2021121421)

<img src="https://user-images.githubusercontent.com/10292489/146633251-d28f823a-1d2f-4d91-86dd-2e305985cc7c.png" width="50%"/>

**Comment by thestinger** [comment]
There isn't a sign of a bug here. You can ask in the GrapheneOS Matrix rooms.

**Comment by thestinger** [comment]
Mobile network will use much more power if you have a bad signal. You can lower it from 5G to 4G if you have a bad 5G signal to save power. It would probably save power regardless.

**Comment by Anth0rx** [comment]
Unfortunately, this did not solve my issue. I've turned off mobile data auto-connect for now. It seems to work out better. I will observe this over the next charging cycles and will report the results here.
