### ISSUE TITLE
Seedvault no permission to contacts and calendar and messages

### ISSUE THREAD

**Issue by Rudd-O** [GrapheneOS/os-issue-tracker#876]
Seedvault cannot backup messages, or contacts (they stay in "waiting to backup" state).

I looked into its permissions, and it turns out all permissions it has, is "files and folders".  It probably needs the appropriate permissions to do the backups mentioned above.

**Comment by flawedworld** [comment]
Contacts backup works fine and is done by seedvaults contacts backup companion app https://github.com/GrapheneOS/platform_external_seedvault/tree/12/contactsbackup

SMS backup works fine and is done by directly backing up com.android.providers.telephony
