### ISSUE TITLE
Fingerprint Bug with Multiple Users

### ISSUE THREAD

**Issue by jgardner7289** [GrapheneOS/os-issue-tracker#877]
I am using GrapheneOS on a Pixel4a, build SQ1A.211205.008.2021121602. I use fingerprint unlocking for my main account. Today I was experimenting with multiple accounts, and performed the following steps: put the primary account in lockdown mode, switch accounts, unlock the second account, then end that account's session. 

Sometimes nothing will happen, but intermittently these steps result in all fingerprints in the main account being unenrolled. If I go to "fingerprint" under security settings, my phone runs the initial fingerprint setup screen. The first time I encountered this bug I was able to start the enrollment process, but I was not able to enroll all 5 fingerprints. After enrolling one or two, all subsequent attempts resulted in an "Enrollment was not completed" message. The only solution was restarting the device. Even then I was able to add one, maybe two or occasionally three fingerprints before seeing the same error message and having to restart my phone again to continue.

I have now reproduced this bug following the same steps multiple times. After the first time, I was no longer even able to start the fingerprint enrollment process without restarting: "I agree" is grayed out and unclickable in the initial fingerprint setup screen. My phone is persistently staying in a state where if I want to enroll multiple fingerprints, I must restart when I encounter the "Enrollment was not  completed" message.

Update: I have also encountered this bug now simply from switching users, not ending the session

**Comment by h4xor666** [comment]
I experienced this as well, actually. Figured it was something wrong with my hardware.

**Comment by thestinger** [comment]
Let us know if this is still an issue in Android 13. I think it's still a problem but haven't confirmed myself.

**Comment by r3g-5z** [comment]
No response from anyone if it's still an issue. Assuming this is fixed in Android 13/Android 13 QPR1.
