### ISSUE TITLE
Long-press volume control stops working when screen is off

### ISSUE THREAD

**Issue by novocaiin** [GrapheneOS/os-issue-tracker#878]
After locking the phone, I am unable to adjust background audio volume by multiple steps with a long press.

**Comment by akc3n** [comment]
This was previously discussed briefly in our [offtopic](https://matrix.to/#/!tgbPIxPlvGiwpsGJuu:matrix.org/$5TWRkBgPBMydKf79lliJWXeolP_EiZ9bywVtcoGZLVw?via=grapheneos.org&via=matrix.org&via=tchncs.de) matrix room. As mentioned, it's the same effect for other users as well when the screen is off and device is locked. Volume adjustability is incremental rather then continuous.

**Comment by thestinger** [comment]
Works the same way as AOSP. I don't see a reason to have an issue open about it.

**Comment by novocaiin** [comment]
> Works the same way as AOSP

Really?
So this is a general Android bug?
Must be fairly new because I've used Android in the not-so-distant past and would've definitely noticed something like this.

**Comment by thestinger** [comment]
I confirmed that it works the same way.

**Comment by thestinger** [comment]
We can't take on fixing every UX issue with the base OS. We have to start closing all these out of scope upstream issues. We aren't going to work on them.

**Comment by novocaiin** [comment]
> I confirmed that it works the same way.

What device did you confirm on?
And was it AOSP or Google's flavor?
I wonder if it's device specific.

Definitely not the case on an old Motorola I have running Nougat, and I don't think it was the case on a Nexus 5X back when I was using one (until it bootlooped).
But I don't have any other Android 12 devices, and re-flashing stock just to check isn't really an option :\
