### ISSUE TITLE
support the option of receiving the censored locked mode notifications from other profiles that are active in the background

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/os-issue-tracker#88]

**Comment by thestinger** [comment]
Requires https://github.com/GrapheneOS/os_issue_tracker/issues/87 to be useful.

**Comment by expobar** [comment]
How about VPN, is it part of it? There have been multiple occasions where I'd want all profiles to connect to the same VPN network without manually toggling the OpenVPN app, otherwise I'd consider the current implementation a "leak".

**Comment by thestinger** [comment]
That's already supported and isn't tied to this.

**Comment by inthewaves** [comment]
Would it be better if the setting is per-user (i.e. whether a user would want to allow their notifications to be censored and forwarded to the foreground user), or if the setting is global?

**Comment by alt3r-3go** [comment]
This one would indeed be great to have. As User Profiles can and are being used to isolate app groups (including Google services-dependent ones), having notifications from them all in one place is important for usability of that isolation.

**Comment by add1989** [comment]
Agree exactly with @alt3r-3go, very excited to see that the issue has now been assigned 😁 I love GrapheneOS! Keep up the amazing work you are doing guys 👍

**Comment by Zanthed** [comment]
Done
