### ISSUE TITLE
All fingerprints have been suddenly deleted.

### ISSUE THREAD

**Issue by Pauler221** [GrapheneOS/os-issue-tracker#880]
Suddenly I couldn't log into my phone using the fingerprint sensor. I rebooted and nothing had changed so I thought the sensor is faulty. After checking in settings under security I realised that all fingerprints were gone but the sensor was still intact since I could add new fingerprints.

Is removing all fingerprints after a certain event happens a security feature of GrapheneOS?

Maybe its worth mentioning that it happened after I have charged my phone with a not OEM charger (its the first time that happened). It has never happened before that. Could this have caused the problem?

**Comment by thestinger** [comment]
https://github.com/GrapheneOS/os-issue-tracker/issues/877

**Comment by thestinger** [comment]
It's a long-time AOSP issue. Nothing to do with GrapheneOS specifically.
