### ISSUE TITLE
Play compatibility: nearby permission for Exposure Notifications

### ISSUE THREAD

**Issue by daradib** [GrapheneOS/os-issue-tracker#882]
For COVID Exposure Notifications to work, Google Play services must be manually granted the Nearby devices permission. By default the permission is not requested, and Play falsely indicates that Exposure Notifications are enabled.

To reproduce:

I installed the 3 Play services apps in the main profile as described in the Usage guide. Then installed the regional app, [COVID Alert NY](https://coronavirus.health.ny.gov/covid-alert-ny/). Both the regional app and Play correctly prompt to turn on Bluetooth, but Play does not request or check for the Nearby permission. A test with [UUID 0xFD6F Scanner](https://f-droid.org/packages/com.emacberry.uuid0xfd6fscan/) from another device confirms that the beacon is sent when the permission is granted to Play and not when it is not.

Ideally Play would be more informative about the state of exposure notifications, e.g., number of keys seen. I'm also not sure whether the Network permission is required for Play, or just for the regional app to download keys.

Thoughts:

 - Can the permission be denied to Play in stock, and if so, does Play react properly?
 - If not, should Nearby be allowed by default as it is for many apps (including the regional app) along with the Network and Sensors permission?
 - Otherwise, mention this as a limitation in the Usage guide?

**Comment by julianfairfax** [comment]
I granted the nearby devices permission to google play services and my app (swisscovid), still shows an error.

**Comment by daradib** [comment]
To clarify, in my case neither Play nor the app shows any error. Exposure Notifications appears to be enabled but isn't actually functional without the permission.

@julianfairfax Assuming you already tried granting internet and nearby devices permissions to both apps, have you tried the [LibreCHovid](https://github.com/c4dt/dp3t-app-android-ch) fork which replaces the Play client library?

**Comment by julianfairfax** [comment]
I did give both of those permissions to both apps. And the LibreCHovid app only works with microG.

**Comment by daradib** [comment]
> Can the permission be denied to Play in stock, and if so, does Play react properly?

If the Nearby devices permission is manually denied in stock, the same behavior occurs in stock. Exposure Notifications can be enabled, but fails silently. I contacted Google Play Support. Will share any updates.

**Comment by julianfairfax** [comment]
I've also opened an issue in case it's a problem with my app rather than this implementation: https://github.com/SwissCovid/swisscovid-app-android/issues/412

**Comment by thestinger** [comment]
If the same behavior occurs in the stock OS then this should simply be documented in the usage guide and they should really have it request the permission.
