### ISSUE TITLE
Google Contacts on Pixel 3XL not syncing, but all other services like Calendar do 

### ISSUE THREAD

**Issue by claib** [GrapheneOS/os-issue-tracker#883]
Hi there
i'm wondering why google contacts, after being installed, asking me for a google account : when entering, it says this account is alreday linked.
Weird, that all other services like G-Drive, G-Mail, G-Calendar work super smooth !

any advice ?

best regards and thx !

**Comment by flawedworld** [comment]
Google Contacts is likely depending on functionality that is not provided by our shims. Would need investigation if this would mean just add more shims or it is depending on another app.

**Comment by julianfairfax** [comment]
It is depending on another app

**Comment by mturilin** [comment]
I experience this as well:
1. My Google contacts are not synced
2. There's no "Contacts" setting in Google account preferences (see the screenshot)
![photo_2022-09-08 09 59 09](https://user-images.githubusercontent.com/843131/189156523-752aa96c-4fc4-4e00-9cf5-8d04ae0dd16e.jpeg)

**Comment by paulverbeke** [comment]
I have exactly the same thing:
- Google Contacts app ask me to connect my account but when I do it says that it is already configured
- so my contacts are not synced
- There's no "Contacts" setting in Google account preferences

Happens on my Pixel 3a XL but not on my Pixel 6 Pro

**Comment by thestinger** [comment]
You need to grant the required Contacts permission for Play services. May also need to enable Storage Scopes.

**Comment by paulverbeke** [comment]
Doesn't look like I received a push from your sandboxed Play Services asking to grant permission. Maybe I missed it.

**Comment by thestinger** [comment]
Play services doesn't know how to request all the stuff it needs itself and requests some stuff it doesn't actually need in some cases. Our compatibility layer deals with some of both but it's not really the actual purpose of the compatibility layer and isn't the focus of it.
