### ISSUE TITLE
Google Play Location Services for GPS-based games do not work

### ISSUE THREAD

**Issue by heuwerk** [GrapheneOS/os-issue-tracker#886]
Hello,
this is my first Issue report so I hope it is helpful.

# Specification
Device: Google Pixel 5
OS Version: Graphene OS 12
Build-No.: SQ1A.211205.008.2021122018
- Google Services Framework Version 12
- Google Play Services Version 21.45.15
- GPSTest Version 3.9.16 from Google Play Store
- Pikmin Bloom Version 36.1 from Google Play Store

## Problem description
I have the following problem: When I install the Google Play service in a second user profile, I have access to the GPS (tested with GPSTest) and my location is also found, however, games from Niantic Inc. that I have tried (Pokemon Go / Pikmin Bloom) still show the error "GPS is being searched" ("GPS wird gesucht" in german).

## Screenshots
![Screenshot_20211228-121452](https://user-images.githubusercontent.com/75751604/147562341-5bdac3e6-7c43-4ea1-9abe-9d304f133078.png)
![Screenshot_20211228-121601](https://user-images.githubusercontent.com/75751604/147562390-97a69425-1a4a-4102-9ac2-b30c0d0a17da.png)

**Comment by flawedworld** [comment]
See: https://github.com/GrapheneOS/os-issue-tracker/issues/635

**Comment by thestinger** [comment]
You haven't made it clear if you actually granted the necessary permissions. Required information is not provided in the initial report. It has to be known whether you configured it correctly or this is a support issue for the Matrix chat room.

**Comment by heuwerk** [comment]
I have set the location permission for Google Play services and Pikmin Bloom to "Always allow" and "Use exact location". GPS is turned on.
![Screenshot_20211229-072839](https://user-images.githubusercontent.com/75751604/147633649-31113803-ace4-4c9a-9e5c-5d01cfe4136b.png)
.
