### ISSUE TITLE
Endless chain crashing and infinite loading when adding a Google account through Gmail app

### ISSUE THREAD

**Issue by Zanthed** [GrapheneOS/os-issue-tracker#888]
Not sure if having more than 1 Google account matters because in this setup I have multiple, but when adding a new Google Gmail account through the Gmail app and signing into Google, it never gets past the final screen similar to when you initialise Play Store for the first time. Infinite loading circle.

The account still works if you swipe up and close the app, works in Gmail, Play Store, etc and shows up in Settings -> Passwords & accounts; but it does endlessly chain crash during that "initialisation" process.

I have obtained logs where I signed in and sat on the infinite loading screen for a couple minutes which shows Zygote repeatedly killing `com.google.android.gms` processes (signal 9): https://gist.github.com/Zanthed/56b1510305d91af4799bec4364d84fb2
Example: see pid `25014` in those logs.

Can reproduce this reliably on both my Pixel 5 and 6 Pro with the same setup: Adding an account to Gmail and having more than 1 Gmail/Google account signed in.

**Comment by flawedworld** [comment]
cc @muhomorr

**Comment by Zanthed** [comment]
This has been solved in 2022011009.
