### ISSUE TITLE
NFC is not covered by the sensor permission

### ISSUE THREAD

**Issue by ojoeth** [GrapheneOS/os-issue-tracker#889]
* Expected behaviour:
apps which have been denied sensor permission should not have access to NFC

* Actual behaviour:
app can read NFC tags with no permissions granted

* Steps to reproduce:
 1. Download an app which can interact with NFC tags (eg: National Rail Smartcard Manager)
 2. Deny this app sensor permission
 3. Scan an NFC tag with the app

**Comment by flawedworld** [comment]
NFC/FeliCa is controlled by the system-wide toggle, it is not part of the sensors permission.

**Comment by thestinger** [comment]
NFC is not considered a sensor but rather a radio.
