### ISSUE TITLE
Deliveroo snd Uber Rider / Driver Application Logon Issues

### ISSUE THREAD

**Issue by xxxsskxxx** [GrapheneOS/os-issue-tracker#891]
Installed Google services OK and logged into my Google account.

Deliveroo rider and Uber Driver apps launch OK but can't go online to work. Error 'you need accurate location to login' appears.

Required services and apps have location access.

Scrrenshot
https://ibb.co/sFVrWqN

Logs taken from graphene

https://ppp.woelkli.com/s/PwL75Q9jBGjBBWD
PW: RiderGraphene22

Uber doesn't allow me to go online to begin work.  No error message received, the application doesn't pick up my location correctly

**Comment by thestinger** [comment]
I think this falls under https://github.com/GrapheneOS/os-issue-tracker/issues/635. This will hopefully be improved more soon.
