### ISSUE TITLE
Pixel 6 - Cannot change the setting on the Galley app

### ISSUE THREAD

**Issue by abis866i** [GrapheneOS/os-issue-tracker#893]
I tried to play with the settings of the Gallery app on a Pixel 6. Although the app works as expected, when I access the setting it gives me a only black screen. I thought this is with the experimental status of GrapheneOS on the Pixel 6 phone.

**Comment by Zanthed** [comment]
It's not related to Pixel 6. Happens on all devices.

The stock Gallery app is a stock sample test AOSP app. It's not being actively maintained and isn't highly functional or bug-free. You should consider finding a different gallery app for yourself if you need more than basic functionality.

**Comment by thestinger** [comment]
https://github.com/GrapheneOS/os-issue-tracker/issues/48
