### ISSUE TITLE
Ultra-Wideband (UWB) not working

### ISSUE THREAD

**Issue by Zanthed** [GrapheneOS/os-issue-tracker#895]
(Generic issue title to figure out UWB not working as a whole)

**Comment by Zanthed** [comment]
The `Ultra-Wideband (UWB)` toggle in Settings -> Connection preferences doesn't work, unable to toggle on, and forcibly turns itself off.

Logs show some Qorvo apps failing to access files, interfaces, sockets, etc.

https://gist.github.com/Zanthed/6e0bb9c4e0641b9a97d218ad07995c27

**Comment by thestinger** [comment]
I'm not sure which setting you're referring to.

**Comment by thestinger** [comment]
What's the full path to the settings? There's no Settings -> Connection preferences.

**Comment by Zanthed** [comment]
@thestinger UWB is only on Pixel 6 Pro, sorry should clarify that.

**Comment by Zanthed** [comment]
As of 2022010500, the UWB toggle now works. The country code is now detected (for me: `qorvo.Uwb: applyCountryRestriction: country code = us`) which is what determines whether UWB is allowed or not due to country regulations.

There are still SELinux denials on Qorvo stuff setting interface states, sockets, `net_raw`, etc.

New logs: https://gist.github.com/Zanthed/8447e98cbf7a789198e2b93e02dc2417

Will need to figure out how to test UWB functionality in general as on the surfae the toggle is controllable, but the logs indicate that UWB likely does not work.

**Comment by thestinger** [comment]
That's weird that it works now.
