### ISSUE TITLE
Sms notification pops up in secondary profile once in a while when there is no SMS

### ISSUE THREAD

**Issue by novocaiin** [GrapheneOS/os-issue-tracker#897]
This happens almost every time I switch to the secondary profile:

https://user-images.githubusercontent.com/95007229/148276778-9bdcec62-e147-4e4c-b2fe-b1f71e22942d.mp4

**Comment by tsaoi** [comment]
Yep, should probably link this to #510

**Comment by empratyush** [comment]
@novocaiin 
hey i am unable to reproduce this issue, can you please explaining how to reproduce this?

**Comment by novocaiin** [comment]
I haven't used profiles in a while.
Maybe need to have an unread message in the owner.
Make sure phone calls and SMS is turned on for the profile.
I've just create a profile and will comment here when I encounter this again.

**Comment by conradteichmann** [comment]
I had this problem and found a solution:

When I use Signal as my default SMS app in my main profile, I have this exact problem. Apart from the "New message" notification, I am unable to receive any SMS in a secondary profile.

After I set the SMS that ships with the OS as the default SMS app in the main profile, I can receive SMS in the secondary profile again.
