### ISSUE TITLE
VLC doesn't render srt subtitles on Pixel 4a 5g

### ISSUE THREAD

**Issue by borg4242** [GrapheneOS/os-issue-tracker#905]
I can repro with the following steps:
* Fresh GrapheneOS install on my Pixel 4a 5g (previously was on latest stock)
* Install F-Droid
* Install VLC
* Open a video with subtitles over SMB (or one that I copied onto the device earlier)
* VLC correctly detects the existence of the subtitles: if I open the subtitle control on the bottom left, it shows the subtitle tracks and one is auto-selected
* However, the subtitle doesn't render on the screen

I tried the following, none of them helped:
* Upgrading GrapheneOS when the new update arrived
* Enabling all permissions for the VLC app
* Trying all hardware acceleration settings in VLC
* Fiddling around with other VLC settings
* Enabling/disabling subtitles in Android Settings
* Capturing a debug log and looking for oddities / searching the web for odd looking strings in the debug log
* Trying different video formats
* Trying embedded and external subtitles
* Loading over SMB and loading locally
* Downgrading VLC to older versions
* Switching subtitles on/off while video was playing
* Trying a video with multiple subtitles and switching between different ones
* Rotating the screen
* Using VLC's PIP mode (tried both standard and custom)
* Trying different VLC themes
* Setting a different locale in VLC
* Using VLC in TV mode

Interestingly, Just Player and NewPipe both render subtitles. Also, VLC works fine on other platforms (PC, stock Android, and LineageOS).

Context: my media files are on an SMB share. The only open source app that loads files over SMB and has a fair UX is VLC, so unfortunately if I can't make VLC work I don't have a reasonable workaround for my use case, so this is a show stopper for me. I hope there will be a way to make this work because I really like the security related choices in GrapheneOS.

Config:
* Pixel 4a 5G
* Build number SQ1A.220105.002.2022010500 and the one before that
* Stable channel

**Comment by flawedworld** [comment]
Unable to reproduce. Please confirm if this is still an issue.

**Comment by borg4242** [comment]
Tested - fixed in latest stable VLC. Apparently it was a font related VLC bug on some Android 12 devices.
