### ISSUE TITLE
T-Mobile does not detect Pixel 4a w/ GrapheneOS as VoLTE-compatible

### ISSUE THREAD

**Issue by EntropySmoke** [GrapheneOS/os-issue-tracker#906]
My T-Mobile account shows my Pixel 4a (with latest GrapheneOS) as an unconfirmed Android device that is not capable of VoLTE. It is likely that T-Mobile simply does not detect the phone correctly because of non-standard OS, but **how can I check whether I am getting VoLTE with GrapheneOS on T-Mobile network?**

I forced mobile data to LTE-Only mode, but AFAIK that only affects data, not voice. **Is it possible to lock voice to LTE-Only mode?**

**Comment by flawedworld** [comment]
LTE-Only mode enforces it for data and voice, they go over the same network, and you'll be forced into using VoLTE.

**Comment by flawedworld** [comment]
Should also be worthy to note that LTE-Only does not mandate that a carrier will support VoLTE with your device.
