### ISSUE TITLE
Service Location not available for most applications

### ISSUE THREAD

**Issue by gerry501** [GrapheneOS/os-issue-tracker#907]
Dear support team,
My setup: Pixel 4a, Build-Nr. SQ1A.220105.002.2022011009
My problem: I have several applications (mainly train apps) which do not start properly, because they look for having location privileges "Allow all the time" before coming up. They want me to change these settings, but I can't!!! They do not start if they have "Allow only while using the app" privileges, even the Google play Services in the Sandbox has this permission. I suppose they do not use the Google Play Services...

![image](https://user-images.githubusercontent.com/22668278/149147064-2c5e245d-965f-43e7-ba56-2363f5a79f71.png)

![image](https://user-images.githubusercontent.com/22668278/149147131-05e87153-f638-40fb-9379-0a57d9551991.png)

Is it possible to grant these permissions to these Apps directly in GrapheneOS?

**Comment by gerry501** [comment]
On another Android or iOS device the SBB-App starts and works properly - if it has the appropriate permission. These are all well known Apps! Millions of customers are using them.

**Comment by gerry501** [comment]
Ok, I will try to get in touch with these App providers. But I suppose that their Apps work properly on Android 12 and iOS...

**Comment by thestinger** [comment]
iOS isn't relevant...

**Comment by gerry501** [comment]
Recently I talked to one developer of the train app, and he told me that their app is working perfectly on Android 12. A colleague of mine has confirmed this statement...

So this is what he told me:
"To correctly function, our app needs access to your GPS data. Be aware: With the newest updates of Android, there are many mechanism (e.g battery saving mode) that stops our app from getting location data. For that reason, it is impossible for us to start the app and therefore close them. We need access to the location services. So set it to "Allow all the time” to make sure our app can track your location and detect the right journey while you are using another app. This is sometimes called fetching data in the background. Our app will not work if the location preferences are set to “Allowed only while in use" or even “Denied”..."

BTW: I turn off the tracking by turning off the location services at all on my phone, as I'm aware that an app may only track me in exceptional cases...

Hence, there seems to be a difference between GrapheneOS and a standard Android 12+...

**Comment by thestinger** [comment]
That's not the case and they aren't doing this properly.

**Comment by gerry501** [comment]
Ok, tell me what they are doing wrong. 
Aren't they using the google play services and check whether they are entitled themselves before starting up?

**Comment by thestinger** [comment]
They aren't requesting background access as claimed.

**Comment by thestinger** [comment]
It's not how it works on Android 12. Have already gone through all this already and continuing this is unnecessary.

**Comment by Zanthed** [comment]
@gerry501 The app developer needs to refer to Android app dev documentation on always on background location permissions for Android 12. This isn't a bug with GrapheneOS and there's nothing GrapheneOS can do to fix this.

https://developer.android.com/training/location/permissions

**Comment by gerry501** [comment]
But it still works on Android 12... Ok! I got this and I pass it to the developer. Thanks for for the answers!

**Comment by thestinger** [comment]
You haven't tested on Android 12.

**Comment by thestinger** [comment]
GrapheneOS doesn't change anything about this. They are not requesting background location access.

**Comment by gerry501** [comment]
No, I haven't test it by my own! Because I have just a GrapheneOS device. I trusted in the statements of the developers and my colleague... But now I know how to argue. Thanks once again!

**Comment by gerry501** [comment]
Hi Daniel,
Sorry, that I come back to you. But in meantime it was possible for me to talk directly to a developer of the train-app which is not working on GrapheneOS (Pixel 4a). He is aware of the changes between Android 11 and 12! Their App is requesting background location access on Android 12 and runs perfectly. They have approximately 500'000 customers which use Android 12. He tested it once again on a Pixel 4a and 6 - with no problems. He asked me then, if I have a special OS running on my device... Which I had to confirm... He then said that they are not making any tests on devices which are not running the original Google Android... So it's up to me!
Gerhard

> On 20 Jan 2022, at 19:29, Daniel Micay ***@***.***> wrote:
> 
> requesting background location access

Bern University of Applied Sciences
Engineering and Information Technology
Postfach
CH - 2501 Biel/Bienne
Switzerland

Phone: +41 31 848 32 28
E-Mail: ***@***.***

**Comment by Zanthed** [comment]
A special OS is not going to make any difference because we do not change how these location permissions work. GrapheneOS is running the latest publicly available Android 12 version.

If an app isn't able to request always on location, that's the app developer's issue. Not a GrapheneOS issue.

**Comment by thestinger** [comment]
The problem is with the app, not GrapheneOS, as has been explained. If they aren't going to support their app properly then this issue is closed and no further discussion needs to happen. They are not doing what they claim.
