### ISSUE TITLE
Not receiving texts on Verizon

### ISSUE THREAD

**Issue by sawft99** [GrapheneOS/os-issue-tracker#908]
This appears to be resolved.

_Originally posted by @flawedworld in https://github.com/GrapheneOS/os-issue-tracker/issues/835#issuecomment-1009940086_

Related to other Verizon issue I believe. I can now make and receive calls. I can also send text messages and the other person receives them. However, on my end I am not receiving texts.

**Comment by flawedworld** [comment]
Please state your device model, build and carrierconfig version.

Build: Settings -> About phone -> Build number
CarrierConfig: Settings -> Network and Internet -> SIMs -> Operator settings version

**Comment by flawedworld** [comment]
Please also confirm if you have moved from an iPhone device recently, that you have disabled iMessages for your number.

**Comment by sawft99** [comment]
> Please also confirm if you have moved from an iPhone device recently, that you have disabled iMessages for your number.

I have not moved from an Iphone. I will get the other info you asked for a little later. Thank you.

**Comment by flawedworld** [comment]
@sawft99 Please call Verizon support and ask to turn off Advanced Messaging (RCS), It is possible this is the cause of your issue.

**Comment by sawft99** [comment]
I have a Pixel not a Samsung.

-------- Original Message --------

**Comment by sawft99** [comment]
> Please state your device model, build and carrierconfig version.
> 
> Build: Settings -> About phone -> Build number CarrierConfig: Settings -> Network and Internet -> SIMs -> Operator settings version

Build: SQ1A.220105.002.2022011009

I have a "carrier settings version" but not operator. It shows as: verizon_us32000000115.38

**Comment by flawedworld** [comment]
Please request a new SIM card. I'll reopen if that doesn't fix it.

**Comment by flawedworld** [comment]
You should also try deregistering your number from Google Messaging https://messages.google.com/disable-chat

**Comment by sawft99** [comment]
> Please request a new SIM card. I'll reopen if that doesn't fix it.

Should it be a Verizon specific sim or just anybody?

**Comment by flawedworld** [comment]
I don't understand the question. Call Verizon and ask them to send a new SIM card to replace your old one.

**Comment by sawft99** [comment]
> I don't understand the question. Call Verizon and ask them to send a new SIM card to replace your old one.

OK got it. I meant if I used a SIM card from another carrier or maker. Tracfone, AT&T, etc. But you specified so no worries.

**Comment by sawft99** [comment]
> Please request a new SIM card. I'll reopen if that doesn't fix it.

Same problem. Put a different carriers SIM in and no issues.

**Comment by sawft99** [comment]
Resolved in #958
