### ISSUE TITLE
Seamless Update Client - Background Data Use

### ISSUE THREAD

**Issue by alternativesurfer** [GrapheneOS/os-issue-tracker#91]
Hi!

There doesn't seem to be a way to constrain this to only use WIFI, and it blasted through my data plan downloading the July security patches (I assume it was this service as it had logged close to 700MB over cellular in the past 30 days, the only thing closer was my web browsing at 120MB).

**Comment by thestinger** [comment]
It does have a setting for constraining the network:

https://grapheneos.org/usage#updates-settings

It's worth noting that until Android Q, every VPN is considered to be a metered network though. Android Q makes it so that they can surface whether the underlying network is metered.

**Comment by thestinger** [comment]
The feature could be improved a bit, which is filed as https://github.com/GrapheneOS/platform_packages_apps_Updater/issues/1. It doesn't currently keep checking to make sure the network hasn't changed to a metered one, so it's technically possible for it to switch after the job starts.

**Comment by thestinger** [comment]
Also worth noting that the updates *could* mostly be 10-30MiB but the project lacks the resources to generate and test delta updates between versions right now. It used to be done in the past, but it took too much time, and it's a lot more to test unless it's just *assumed* that they work which is a bad idea.
