### ISSUE TITLE
dvfs errors, Pixel 6 Pro

### ISSUE THREAD

**Issue by lbdroid** [GrapheneOS/os-issue-tracker#910]
I am getting a lot of this in the logspew;

```01-13 09:19:00.525  1006  1006 D AOC     : A3:ERR: dvfs.cc, 227: 858 MIPS requested on core 1, which exceeds available compute power!```

**Comment by thestinger** [comment]
That seems expected.

**Comment by lbdroid** [comment]
How is it expected? It suggests a configuration problem -- should not be making unsupportable requests.

**Comment by thestinger** [comment]
Please stop using our issue tracker as a way to ask questions and then debate the answers.
