### ISSUE TITLE
Play Services data wipe or reinstall breaks push notifications

### ISSUE THREAD

**Issue by gordonel** [GrapheneOS/os-issue-tracker#918]
If for any reasons GSF and Play Services app data is erased or they're reinstalled, push notifications will no longer work on all GSF-dependent apps that use Play Services for push notifications (Signal, Telegram, Keybase, you name it) with the only remedy being a total reinstall of those apps.

To repro:
- Set up and test push notifications with any app using Play Services for receiving push notifications
- Erase data on or reinstall Play Services and/or GSF
- Attempt to trigger a push notification

I'm logging this as an issue because on Google ROMs these steps don't result in notifications being borked for all apps. Granted, you can't reinstall GSF and Play Services there, but I hope you get the point

**Comment by gordonel** [comment]
Possible clue: a banking app that I had to set up anew thinks I set up a completely new device

**Comment by thestinger** [comment]
In that case there's probably nothing we can do. It would be useful to test whether the same thing occurs on the stock OS if you remove Play services from the profile with adb and then add it back. If that breaks the same way, then we have the same behavior of the stock OS which is the compatibility layer doing the best that it can do.

**Comment by gordonel** [comment]
> In that case there's probably nothing we can do. It would be useful to test whether the same thing occurs on the stock OS if you remove Play services from the profile with adb and then add it back. If that breaks the same way, then we have the same behavior of the stock OS which is the compatibility layer doing the best that it can do.

No way to do that on the stock OS. Play Services are disableable, but not removable

**Comment by thestinger** [comment]
You can use adb to uninstall them from the profile rather than only disabling them.

**Comment by thestinger** [comment]
I think this will also occur with the stock OS so this issue will be closed unless someone demonstrates that there's something different about the behavior for us. I don't think there's much we can do about it unless you want us to prevent people from wiping the data which I don't want to do. It's still useful to be able to wipe it despite needing to also wipe other apps using it for something that needs to be reset.
