### ISSUE TITLE
Play Services uninstall on one of the profiles breaks Play Services and Google Apps for the other

### ISSUE THREAD

**Issue by gordonel** [GrapheneOS/os-issue-tracker#919]
Setup:
- Insular or Shelter-managed work profile
- Google Play Services installed on one of the profiles

To reproduce:
- Install YouTube from Google Play and open it, making sure it works
- Clone Google Play Services (GSF + Play Services) to the other profile, doesn't matter whether mainland or island is your starting point
- Uninstall Google Play Services from the other profile
- Open YouTube

You'll be stuck on a splash screen with YouTube having a number of Fatal Exception errors, all caused by

```bash
java.lang.SecurityException: Permission Denial: opening provider com.google.android.gsf.gservices.GservicesProvider from ProcessRecord{42666de0 4320:com.google.whatever/u0a10036} (pid=4320, uid=10036) requires com.google.android.providers.gsf.permission.READ_GSERVICES or com.google.android.providers.gsf.permission.WRITE_GSERVICES
```

Tested this with YouTube, Google Play Store and Gmail. YouTube and Google Play Store get stuck on the splash screen, Gmail crashes outright. The only way to fix this is a complete reinstall of Play Services and affected apps, which breaks all push notifications for all apps using Play Services for push notifications and can be a pain in the ass to fix (#918)

**Comment by codethief** [comment]
Could this be related to the following (slightly different) issue I described here? -> https://github.com/signalapp/Signal-Android/issues/9279#issuecomment-991404603

**Comment by thestinger** [comment]
This is how work profiles function. It's not specific to GrapheneOS and we don't have plans to dramatically change how work profiles function. It wouldn't occur if you used a separate user profile.
