### ISSUE TITLE
[feature request] Add Bedtime Mode or Digital Wellbeing suite compatibility

### ISSUE THREAD

**Issue by gordonel** [GrapheneOS/os-issue-tracker#920]
IMHO, one of the best features of the stock ROM is Bedtime Mode that allows you to set DND based on alarm schedule or sleep hours with optional on/off triggers plugging into a charger.

Coincidentally, is there any way to make it work by just installing the Digital Wellbeing app?

**Comment by flawedworld** [comment]
This is not something we are going to add. AOSP has support for do not disturb scheduling and has integration with ending schedules based on next alarm. We are not going to add support for the Digital Wellbeing app as it requires deep system integration
