### ISSUE TITLE
Do not give apps Wi-Fi control special access by default

### ISSUE THREAD

**Issue by flawedworld** [GrapheneOS/os-issue-tracker#922]

**Comment by r3g-5z** [comment]
This would only make sense if we first make special permissions like this more user-facing (https://github.com/GrapheneOS/os-issue-tracker/issues/1312) so if there are legitimate apps that depend on this (`CHANGE_WIFI_STATE`), users won't be confused on why it may not work or where they can turn on Wi-Fi control since it's hidden way in special permissions.

**Comment by r3g-5z** [comment]
A quick glance at our existing infrastructure for that, possibly.

**Comment by r3g-5z** [comment]
I'm actually not entirely sure what apps actually use this. I went through and disabled the permission from a bunch of apps and turned off Wi-Fi to see what they'd do. I didn't observe any difference than if I had the permission enabled and with Wi-Fi enabled. 

It's possible disabling this by default is safe but I really would need to see a legitimate usage of this permission and have a way to compare behaviour. There's `ACCESS_WIFI_STATE` but I don't think it's apart of Wi-Fi control.

**Comment by thestinger** [comment]
I think it may just be added by default because apps used to be able to toggle Wi-Fi by default. Unsure why it's so widespread. Needs to be investigated properly. We don't currently know enough details to decide what to do.

**Comment by muhomorr** [comment]
"Wi-Fi control" special access permission maps to `OP_CHANGE_WIFI_STATE` app-op, which is separate from the `CHANGE_WIFI_STATE` permission.
`CHANGE_WIFI_STATE` permission has `normal` protection level, ie it's auto-granted and cannot be denied by the user.
Many of Wi-FI APIs (WiFiP2p, WiFiRtt, WiFiAware etc),  check only `CHANGE_WIFI_STATE` and not `OP_CHANGE_WIFI_STATE`.

**Comment by thestinger** [comment]
Closing unless someone finds that there is a clear reason to change how this works. No point having an issue open where we don't know why we want to do it.

**Comment by Cynoval0** [comment]
I think there's more to investigate. I'm not sure whether or not a malicious app with this special permission may compromise the user privacy.
Shouldn't be by default on, at least not in apps like Instagram or apps that I never set the network toggle on(example barcode scanner)
![Screenshot_20240426-220820](https://github.com/GrapheneOS/os-issue-tracker/assets/168236512/03fd0dfc-a4fb-4b79-a5a3-648193f4878e)

Years ago I remember Instagram suggesting me multiple profiles of 
random people who just were in the bus with me a few hours later.

**Comment by ClingLang** [comment]
> Explain why.

https://developer.android.com/develop/connectivity/wifi/wifi-suggest

Changing approval status for app
> A user declining the network suggestion notification removes the CHANGE_WIFI_STATE permission from the app. The user can grant this approval later by going into the Wi-Fi control menu (Settings > Apps & notifications > Special App access > Wi-Fi Control > App name).

@muhomorr the android developer says nothing about OP_CHANGE_WIFI_STATE, it states only the problematic permission.
> "Wi-Fi control" special access permission maps to OP_CHANGE_WIFI_STATE app-op, which is separate from the CHANGE_WIFI_STATE permission. CHANGE_WIFI_STATE permission has normal protection level, ie it's auto-granted and cannot be denied by the user. Many of Wi-FI APIs (WiFiP2p, WiFiRtt, WiFiAware etc), check only CHANGE_WIFI_STATE and not OP_CHANGE_WIFI_STATE.

@thestinger an app with this permission potentially can log information about nearby Wi-Fi network, establish WiFi connections, make an hotspot on its own. That's what it's said even in the settings.
I don't think there's more to explain...
![Screenshot_20240427-005053](https://github.com/GrapheneOS/os-issue-tracker/assets/168240566/3fde4edf-0aa5-4e01-af9a-700ae9973293)

**Comment by buawf** [comment]
> No, they cannot.


 Is it same for Non-GOS devices ? as I've an Honor 8X with Android 10 (EMUi), probably the last Android update from Honor.

**Comment by buawf** [comment]
> This is a request, not ability to do it without approval.


 Why is it even requesting ?
