### ISSUE TITLE
Play compatibility: Exposure notifications trigger ApiException

### ISSUE THREAD

**Issue by hmenke** [GrapheneOS/os-issue-tracker#923]
I'm trying to use Exposure Notifications with the tracing app provided by the German government (https://play.google.com/store/apps/details?id=de.rki.coronawarnapp). Access to Nearby Devices is granted for both the app and for Google Play Services (as per https://github.com/GrapheneOS/os-issue-tracker/issues/882). Nevertheless, upon launching the app the exception below appears in logcat and the app tells me the "Exposures have not yet been checked". (after exposure data has been downloaded)

```
01-16 10:46:11.432 17311 17383 W System.err: com.google.android.gms.common.api.ApiException: 10: Unable to validate key file signature: no public key found for package de.rki.coronawarnapp
01-16 10:46:11.432 17311 17383 W System.err: 	at com.google.android.gms.common.api.internal.TaskUtil.trySetResultOrApiException(com.google.android.gms:play-services-base@@17.6.0:3)
01-16 10:46:11.432 17311 17383 W System.err: 	at com.google.android.gms.internal.nearby.zzan.onResult(com.google.android.gms:play-services-nearby@@18.0.3:1)
01-16 10:46:11.432 17311 17383 W System.err: 	at com.google.android.gms.common.api.internal.IStatusCallback$Stub.zaa(com.google.android.gms:play-services-base@@17.6.0:2)
01-16 10:46:11.432 17311 17383 W System.err: 	at com.google.android.gms.internal.base.zab.onTransact(com.google.android.gms:play-services-base@@17.6.0:3)
01-16 10:46:11.432 17311 17383 W System.err: 	at android.os.Binder.execTransactInternal(Binder.java:1195)
01-16 10:46:11.432 17311 17383 W System.err: 	at android.os.Binder.execTransact(Binder.java:1154)
```

Google Play Services: version 21.48.15 (190400-414534850)
GrapheneOS: SQ1A.220105.002.2022011009 (Pixel 4a)

**Comment by jorgeluiscarrillo** [comment]
For now, you can use this https://f-droid.org/en/packages/de.corona.tracing/

**Comment by hmenke** [comment]
Thanks for the suggestion. Unfortunately, the F-Droid version does not work because fixes for Android 12 are missing.
https://codeberg.org/corona-contact-tracing-germany/cwa-android/src/branch/main/CHANGELOG.md
Luckily upstream provides an own F-Droid repository with the latest releases: https://bubu1.eu/cctg/

**Comment by flawedworld** [comment]
Does not seem to be an issue anymore.

**Comment by Zanthed** [comment]
This should be better improved with https://github.com/GrapheneOS/platform_frameworks_base/pull/146

**Comment by thilakm-git** [comment]
> This should be better improved with [GrapheneOS/platform_frameworks_base#146](https://github.com/GrapheneOS/platform_frameworks_base/pull/146)

You're right. It's also actually working now!
