### ISSUE TITLE
The network access permission doesn't block some connections it should be blocking

### ISSUE THREAD

**Issue by rowboatz** [GrapheneOS/os-issue-tracker#924]
Setup:

- regular Pixel 6 with up-to-date stable GOS (build SQ1D.220105.007.2022011423)
- private DNS set to NextDNS to generate logs

Steps to reproduce:

- install Google Maps
- disable its internet access via the network permission
- reboot the device
- unlock the device
- connect the device to the internet
- monitor DNS logs

Issue: DNS logs immediately report more than a hundred connections to Google domains that only occur when Maps is installed (I double checked this).

Things to note:

1. Interestingly, Maps apparently cannot access the internet while it is in the foreground (i.e. I can't search for places/adresses, the map doesn't load, etc), which is expected. It seems that only (maybe some?) background connections bypass the restriction. This seems very weird.

2. This issue might not be limited to Maps. I just haven't been able to reproduce it with another app. I tried with Signal and FairEmail, for example, and the network access permission worked as expected according to NextDNS logs and the apps' behavior.

3. I first noticed it happening in my main profile with Maps from Aurora Store but to control the variables as much as I could, I uninstalled Maps from my main profile, created a new profile from scratch, downloaded the Maps apk from apkmirror through Vanadium, disconnected the device from the internet, installed the Maps apk, denied network access to every app I could (Maps too obviously - no other 3rd party app installed), THEN reconnected the device to the internet. NextDNS again instantly logged more than a hundred connections to the same Google domains right away even though I had disabled every app's internet access via the network permission.

4. I only noticed this happening upon connecting to the internet for the first time after a reboot, but I haven’t waited any further to see if this issue persists without rebooting the phone (i.e. if Maps continues to bypass the network permission in the background occasionally).

Am I missing something here? Could it be that I'm doing something wrong? I was under the impression that the network access permission had priority over everything else and couldn't be bypassed unless under very special circumstances. Do I have a warped idea of the way the network permission is supposed to work? Or is it not working properly as of right now?

This is my first time reporting something on Github so I apologize in advance if I’m not doing it right.

**Comment by thestinger** [comment]
The way you're trying to monitor for leaks is incorrect. Android performs site association verification for domains that the app wants to handle as app links. The OS itself fetches the assetlinks.json file for each domain via an HTTPS GET request. It's not the app making a connection. You're going to need to confirm that you're not confusing this with connections made by the apps.

https://developer.android.com/training/app-links/verify-site-associations

**Comment by thestinger** [comment]
You can disable the Intent Filter Verification Service app and then perform your tests again.

**Comment by thestinger** [comment]
For example, Signal defines a site association with signal.group. The Intent Filter Verification Service will fetch https://signal.group/.well-known/assetlinks.json. It also defines associations with a couple other domains. Google Maps defines a bunch of associations. You'll need to confirm that what you're reporting is not simply that the OS verifies site associations for apps for security reasons to avoid enabling any site associations that are not declared by the site unless the user manually enables the link handling in Settings.

**Comment by rowboatz** [comment]
Thank you very much for explaining all that. I tested it again and you're right, with the Intent Filter Verification Service app's network access disabled, none of what I was seeing shows up in the log - so I was indeed confusing this with connections made by the apps. Besides, the links that showed up did very much look like they could be used for site associations, now that you've mentioned it. It's a relief to know that the permission works fine.

**Comment by thestinger** [comment]
You can disable Intent Filter Verification Service as an app so it just doesn't run instead of breaking it by disabling Network for it.

**Comment by thestinger** [comment]
Note that it only ever fetches https://example.com/.well-known/assetlinks.json where example.com is a domain that the site claims to be associated with in order to check for proof from the domain. It allows the OS to enable app link associations by default when the site association has been verified. That's what makes apps like YouTube able to handle YouTube links automatically by default, but for NewPipe you need to go into the app settings and enable the app link associations instead of them being default enabled and needing to be disabled.

It's a security feature to only have verified app links enabled by default.

**Comment by thestinger** [comment]
You can look at the app link associations inside the Settings page for the app. You can see the result of the check it performs from whether they get enabled by default.
