### ISSUE TITLE
No icon in top status bar if ring and notes volume is turned off

### ISSUE THREAD

**Issue by robovoice1** [GrapheneOS/os-issue-tracker#925]
When i turn off ring and notification volume, icon is missing in the top right phone status bar.
Please see picture!
Picture taken from another phone to show what i mean.

![Screenshot_20220117-131648_1_1](https://user-images.githubusercontent.com/92784377/149768772-676fa80b-745b-4ae9-bbcc-aabd408d4109.png)

Pixel 4a latest beta channel release

**Comment by thestinger** [comment]
This is how Android 12 is intended to work. It shows when you open the notification tray.
