### ISSUE TITLE
[req] Option for including phone top status bar within screenshots

### ISSUE THREAD

**Issue by robovoice1** [GrapheneOS/os-issue-tracker#926]
The actual process is:
Screenshots are taken without the top status bar of the phone. Please see picture.
![Screenshot_20220117-115024](https://user-images.githubusercontent.com/92784377/149771937-2a5ff5b8-2a73-4ffc-8dbf-0adca857eb5b.png)

An option to select if the phone status bar is included or not in screenshots would be nice.
(depending on the later use case of the taken screenshots)

pixel 4a latest beta channel release.

**Comment by thestinger** [comment]
That's only the case if you take screenshots from recent apps instead of with the power + volume down key binding.

**Comment by robovoice1** [comment]
Well, grapheneos newbie alert from my side.
Thanks for the info and fast response! 😃
