### ISSUE TITLE
[req] More options for screen recordings

### ISSUE THREAD

**Issue by robovoice1** [GrapheneOS/os-issue-tracker#927]
Screenrecordings are too big (file size) to upload to some websites.

Including more options to reduce the file size of the recordings and additional options is needed.
For exampel:
Resolution, FPS, Bitrate, Orientation and 
selecting a target app for recording.

Picture is from the actual beta release
![Screenshot_20220117-135830](https://user-images.githubusercontent.com/92784377/149778259-30826d21-9d52-4b52-a1de-e19582a76eb5.png)

Pixel 4a latest beta channel release

As a workaround i am using ScreenCam app.

**Comment by thestinger** [comment]
This isn't something we plan to implement in GrapheneOS.
