### ISSUE TITLE
Screen rotation glitch Newpipe

### ISSUE THREAD

**Issue by 83317** [GrapheneOS/os-issue-tracker#930]
![Screenshot_20220117-154716](https://user-images.githubusercontent.com/93091272/149835345-cb6a6116-7dfa-4891-b064-b05cab3d70a7.png)
![Screenshot_20220117-154737](https://user-images.githubusercontent.com/93091272/149835351-c47af1a9-9f82-44a8-b321-85920e47d91a.png)

The scale of the video is inconsistent, sometimes I get a black box when I try to go full screen

**Comment by thestinger** [comment]
There isn't an indication of this being a GrapheneOS issue rather than a NewPipe issue. It's not something we can address.
