### ISSUE TITLE
Add the option to block the internet connection depending on the network (VPN, Wifi, Mobile etc)

### ISSUE THREAD

**Issue by mapsmak353478** [GrapheneOS/os-issue-tracker#931]
Hello

Thank you for GrapheneOS, it is a very important tool and I thank all the people who are involved in this project. I regularly donate via Monero to this vital project and will continue to do so.

I would like to request the implementation of a very important option.
Currently, we can block the internet connection of an application by authorizing it to connect to the network or not.

But this is not sufficient and not secure enough.
For example, if I have an anonymous Twitter account, I can install an open-source application for Twitter, but to keep my anonymity I have to connect systematically via VPN.

The slightest mistake or the application that launches in the background and connects to the network ... my IP will be de-anonymized immediately.

I can activate the permanent VPN connection, but it's very uncomfortable, you have to activate the VPN permanently to avoid de-anonymization, and even that is not safe (the VPN can disconnet and the kill swtich is not guaranted to work)

When it would be enough to add the option to block the internet connection (at the network level) of an application depending on the network (VPN, Wifi, Mobile etc) just like on CalyxOS

Please consider this

![network](https://user-images.githubusercontent.com/72702025/149865516-b4556a27-6380-4e06-9381-27839af8f6b5.png)

**Comment by thestinger** [comment]
@mapsmak353478 The implementation on CalyxOS is leaky and doesn't work. CalyxOS is a scam project which is engaged in malicious behavior towards GrapheneOS. Promoting it in our community will result in a ban. This is not the correct way to implement this. Due to how you've gone about requesting it, you won't be getting a detailed answer.
