### ISSUE TITLE
[req] Include VPN chaining for better anonymity

### ISSUE THREAD

**Issue by robovoice1** [GrapheneOS/os-issue-tracker#932]
Many apps use their own VPN like:
Netguard
Tor browser
Blokada
TC (Tracker Control)
just to name a few
If you try one of the above apps the firewall (Netguard) is cut off.
I am not interested in rooting a hardened android os to use AFall and an additional VPN app.

Using multiple VPNs without rooting could be "the" feature to switch to GrapheneOs for others. :-)

Thanks for this great os!

**Comment by thestinger** [comment]
It's already entirely possible for VPN apps to support this. You're requesting it in the wrong place.

**Comment by atb00ker** [comment]
I personally think expecting multiple apps, some open-source and some proprietary, to support VPN chaining is practically ensuring it will never happen.
Is it possible to reconsider to built it at OS level, like linux?

**Comment by thestinger** [comment]
> Is it possible to reconsider to built it at OS level, like linux?

GrapheneOS is Linux and has support for it already. You're wrong.

**Comment by thestinger** [comment]
There are already apps supporting this.

**Comment by atb00ker** [comment]
> GrapheneOS is Linux

Sorry, my bad, I was not technically accurate.
I meant that in desktop GNU/Linux distributions like Debian, I can install multiple VPN application, and chain them, as far as I know, the network manager takes care of abstracting the chaining part and very simple VPN apps also work without any effort from my end.

> has support for it already

If there is support for it already, I am sorry to bring it up, I wouldn't bother you further.
From user perspective of someone who does not know much about how android works;
when I try to connect a second VPN, the first one is kicked off.
My understanding from your response is that, it's not the OS/network manager's fault that the first VPN got kicked off, but rather the second app was using some anti-pattern where it actively disconnected the active VPN to open it's connection.
If my understanding is correct, I wonder why all the VPN apps I install use this anti-pattern, but I suppose that discussion would be out-of-scope for this issue.

Thanks for responding to this though, I will try to point to this comment to developers/companies behind the VPN apps I am using, who, if required, I hope will bring a more detailed PoV to this issue.

Cheers.

**Comment by thestinger** [comment]
> I meant that in desktop GNU/Linux distributions like Debian, I can install multiple VPN application, and chain them, as far as I know, the network manager takes care of abstracting the chaining part and very simple VPN apps also work without any effort from my end.

Those distributions don't have a similar feature with a proper kill switch and they handle things much differently where it's left up to the VPN software to set up routing and prevent leaks. If it dies, it leaks. Alternatively, you can do it yourself, which is mainly how WireGuard is used.

> My understanding from your response is that, it's not the OS/network manager's fault that the first VPN got kicked off, but rather the second app was using some anti-pattern where it actively disconnected the active VPN to open it's connection.

The OS does not support doing the nested for them so the apps need to support it. Apps can support it. A single app can support chained VPNs. Apps can also cooperate together. Some apps support forwarding to a SOCKS proxy. One example is NetGuard.

**Comment by atb00ker** [comment]
>  Those distributions don't have a similar feature with a proper kill switch and they handle things much differently where it's left up to the VPN software to set up routing and prevent leaks. If it dies, it leaks. Alternatively, you can do it yourself, which is mainly how WireGuard is used.

I see. In debian, you say "it's left up to the VPN software to set up routing"; I am assuming to mean, here, graphene is setting up routing for the apps.

> Some apps support forwarding to a SOCKS proxy and one example is NetGuard.

I am aware of it, it's my saving grace. I am using a complicated system described here: https://itsignacioportal.github.io/netguard-pdnsf-any-vpn-combo/ to chain two VPNs.
The author of that blog uses the word "slots"; the work profile has it's own "VPN slot"; through which we hack our way into using two VPNs.
I might need to talk with some android developer to use the correct terminology before discussing further, but basically, I want more "VPN slots" without opening the work profile (and preferably more than 2 "slots"), and I know expecting all developers from different companies to "cooperate" isn't going to take me anywhere.

Cheers, for now! 👍🏻

**Comment by atb00ker** [comment]
Hey @An-anonymous-coder and any future Googlers,
some useful information:
1. I tried chatting with CalyOS folks as well on this issue and it's not a priority for them either, sadly.
2. I found an app called [Rethink DNS] that can connect to my wireguard VPN and block internet access at apps level at the same time; it's not a perfect solution because tailscale can still not be connected at same time but I've learned to live with it.

If someone finds a better solution to connect wireguard, tailscale and VPN based firewall without rooting the phone, please share it.


[Rethink DNS]: https://rethinkdns.com/
