### ISSUE TITLE
Screen recorder unable to capture audio

### ISSUE THREAD

**Issue by b0ywearngtights** [GrapheneOS/os-issue-tracker#933]
I'm using a Pixel 4a on build SQ1A.220105.002.2022011423 and the screen recorder can not capture audio whether from device audio or mic audio (also mentioned here #566).  
Could this be due to a wrong configuration on my part?  

https://user-images.githubusercontent.com/94209903/150101459-a85b7d2c-8c18-414d-8b9c-835e47645907.mp4  

![Screenshot_20220119-095616](https://user-images.githubusercontent.com/94209903/150101898-678b7455-aecd-40e9-88ce-c9ea259fccd9.png)

**Comment by thestinger** [comment]
The issue could be that you revoked audio access from a component requiring it. Did you revoke audio recording access from system apps? You should check that.

There's always the option to reset app settings via the OS option for that which will reset all app permissions, notifications, etc. across all apps.

**Comment by Zanthed** [comment]
Unable to reproduce this on my Pixel 6 Pro. Capturing device audio works perfectly fine.

You have a weird setup you're not specifying here.

**Comment by thestinger** [comment]
This appears to work the same way as the stock OS. Not all device audio appears to get recorded but that appears to be how this is set up to work. It depends on how apps are playing audio. I don't think we want to change how this works from how it works on the stock. Unless there's something we're breaking, it's working as expected.
