### ISSUE TITLE
No VoLTE for Vodafone Germany

### ISSUE THREAD

**Issue by allan-gounden** [GrapheneOS/os-issue-tracker#934]
There is no switch for activating VoLTE (voice over LTE) on my Pixel 6. My carrier is Vodafone Germany.

I do not want to use GSM :)

Could you add VoLTE support for my carrier?

Thanks in advance.

Sincerly,
Allan Gounden

**Comment by thestinger** [comment]
We're not maintaining carrier configurations ourselves. The carrier configurations are based on what the carrier submits to AOSP and Google for Pixels. Unless VoLTE is available in the stock OS but not GrapheneOS, there isn't something for us to do. It's the responsibility of the carrier to submit an appropriate configuration. It wouldn't be reasonable for us to maintain thousands of carrier configurations manually.

**Comment by allan-gounden** [comment]
I contacted Vodafone Germany and asked them to update the carrier config. https://source.android.com/devices/tech/config/carrierid#adding_carrier_id_information_to_the_database
https://docs.google.com/forms/d/1KjwTaExKRjkE9tbR9yavBrGzwvuz1dNku2Ae_7GrdUQ/viewform?edit_requested=true
They said they will check it out and give feedback in approximately 2 weeks.

Thank you for your response.

Sincerly,
Allan Gounden
