### ISSUE TITLE
[feature request] NTFS and exFAt support

### ISSUE THREAD

**Issue by allan-gounden** [GrapheneOS/os-issue-tracker#935]
Could you add NTFS and exFAT support please?

Thanks in advance.

Sincerly,
Allan Gounden

**Comment by thestinger** [comment]
NTFS is definitely not being added. exFAT will be available once it's available in AOSP. It won't be implemented downstream in GrapheneOS.

**Comment by allan-gounden** [comment]
Thank you for your response.

Sincerly,
Allan Gounden
