### ISSUE TITLE
Disable Qualcomm DIAG driver in kernels

### ISSUE THREAD

**Issue by flawedworld** [GrapheneOS/os-issue-tracker#936]

**Comment by SkewedZeppelin** [comment]
fwiw I used to have this disabled in all DivestOS kernels but had to remove it a year or so back because it turned out to break compile on most newer sdm kernel trees and also broke cellular on some old legacy devices.

**Comment by flawedworld** [comment]
Hmm, ok this will likely need investigation before we can consider this something suitable for production usage.

**Comment by flawedworld** [comment]
DIAG service and libraries must be removed in tandem with this

**Comment by SkewedZeppelin** [comment]
You cannot remove them all or else the ril won't start.
https://github.com/Divested-Mobile/DivestOS-Build/blob/master/Scripts/Common/Deblob.sh#L111

**Comment by flawedworld** [comment]
It seems far too integrated to reasonably maintain and test this and I don't feel like this is a feasible approach.
