### ISSUE TITLE
Provide minimum display brightness level setting in Adaptive brightness mode 

### ISSUE THREAD

**Issue by SapientHetero** [GrapheneOS/os-issue-tracker#939]
At night my Pixel 5a display is so dim (19%) in adaptive brightness mode that it strains my aging eyes. Every night I have to manually adjust the brightness higher for comfort. But otherwise adaptive brightness mode works well for me.

A user-selected minimal brightness setting that prevents adaptive brightness mode from reducing brightness below the comfort level of each user on their specific device would be a handy future enhancement.

**Comment by thestinger** [comment]
This could be implemented but we have no plans to change how adaptive brightness works and it would have to happen in AOSP rather than GrapheneOS. It's outside the scope of what we are likely to work on.

**Comment by thestinger** [comment]
We'd be willing to change how adaptive brightness is tuned to more closely match the stock OS but then a proposal will have to explain how to do that and point to where it needs to be done. We're very unlikely to add any invasive changes related to things like this. Our goal isn't adding a bunch of features to Android, especially niche options which would only be used by a tiny portion of our users. If the proposal was privacy/security related it would still be unlikely to be implemented unless it could be enabled by default or was a significant improvement. Niche features aren't worth maintaining and just end up being lost when things change between major releases.
