### ISSUE TITLE
Autocorrect - does not capitalise first character of a new sentence

### ISSUE THREAD

**Issue by snrkl** [GrapheneOS/os-issue-tracker#941]
**Build Number**: SQ1A.220105.002.2022011423
**Hardware**: Pixel 5
**Keyboard Configuration**: Stock GrapheneOS Keyboard English (US)
**Locale**: Language English (Australia)

*GrapheneOS Keyboard Settings:*
- Auto-Correction: ON
- Show correction suggestions: ON
- Personalised Suggestions: ON
- Suggest Contact names: ON
- Next-word suggestions: ON

*Spell checker*
- Use spellchecker: ON
- Languages: Use System Languages
- Default spell checker: GrapheneOS Spell Checker

*Add on Dictionaries:*
- English (US)
- Englist
- Deutsch
- Espanol
- Francais
- Italiano
- PycckNN

**What Happens:**
When typing a new sentence, the first letter of the entered text does not capitalise.
eg: 
> "the quick. brown fox. jumps over"

**What I Expect to Happen:**
The auto-correct function should capitalise the first character of the sentence.
eg:
> "The quick. Brown fox. Jumps over"

**Steps to Reproduce:**
In Signal, email or any text entry dialogue, start typing:

> "the quick. brown fox. jumps over"

The text will remain unchanged, rather than auto capitalising to:

> "The quick. Brown fox. Jumps over"

![Screenshot_20220126-221358](https://user-images.githubusercontent.com/2288035/151162132-4477ce5a-36b5-4787-9eee-c611dccb9414.png)
![Screenshot_20220126-221447](https://user-images.githubusercontent.com/2288035/151162740-b7f08585-210d-4114-b1b2-a9ce9f39b0a2.png)
![Screenshot_20220126-221458](https://user-images.githubusercontent.com/2288035/151162743-af9247dc-20d7-4b59-85e8-66f5bc29008e.png)
![Screenshot_20220126-221510](https://user-images.githubusercontent.com/2288035/151162745-f968b998-dfe6-49f9-ab30-b3aff1cfdd05.png)
![Screenshot_20220126-221520](https://user-images.githubusercontent.com/2288035/151162748-7275549a-aa52-4628-845b-3321a2e72079.png)
![Screenshot_20220126-222040](https://user-images.githubusercontent.com/2288035/151162751-a6316ccb-ddfb-4607-a5ee-f234eaee0fc1.png)
![Screenshot_20220126-222339](https://user-images.githubusercontent.com/2288035/151162753-42bdc5be-0c39-4e43-b1d4-e8b8b8b1c444.png)
![Screenshot_20220126-223636](https://user-images.githubusercontent.com/2288035/151164285-6d968f6c-ef42-40b2-acbe-bbd778ed47c3.png)
![Screenshot_20220126-223643](https://user-images.githubusercontent.com/2288035/151164295-25251288-a887-4992-b524-dc7207cfa6fa.png)

**Comment by snrkl** [comment]
tagging @thestinger and @flawedworld: I have re-raised this issue as requested by @thestinger  as it is still impacting my pixel5 system on SQ1A.220105.002.2022011423, which is the current stable release per https://grapheneos.org/releases#stable-channel as at 2022-01-26 22:28hrs [GMT+10]

**Comment by snrkl** [comment]
@thestinger if there is any additional information of interest please let me know what you would like to see, and I will retrieve and update the issue request as soon as possible.

**Comment by flawedworld** [comment]
@snrkl Test it in the "Messaging" app please

**Comment by snrkl** [comment]
@flawedworld re-tested in the Messaging app as requested.. Please see the attached screen recording of the default behaviour.

https://user-images.githubusercontent.com/2288035/151377627-4169b416-1173-48ce-916f-784dc5d56df5.mp4

**Comment by snrkl** [comment]
Tested and reproduced the bug in SQ1A.220105.002.2022013120

**Comment by snrkl** [comment]
Tested and reproduced the bug in SQ1A.220205.002.2022021415

**Comment by snrkl** [comment]
Tester and reproduced the bug in SQ1A.220205.002.2022021721

**Comment by snrkl** [comment]
Tested and reproduced in SQ1A.220205.002.2022030501

**Comment by snrkl** [comment]
Tested and reproduced in SP2A.220305.012.2022030801

**Comment by snrkl** [comment]
Tested and reproduced in SP2A.220305.012.2022032715 on pixel5

**Comment by snrkl** [comment]
Tested and appears to be fixed in SP2A.220305.012.2022033013 on Pixel5

**Comment by flawedworld** [comment]
@snrkl Are you sure?

**Comment by snrkl** [comment]
@flawedworld yep...

https://user-images.githubusercontent.com/2288035/161406481-869370f6-aa64-4572-bf12-f0d800bc4f21.mp4

**Comment by snrkl** [comment]
I noticed after the latest update, that it was working OoB for new profiles created (I have been playing with the new GrapheneOS App Store installation of GSF etc..)

I revisited my main profile and toggled the "Auto-capitalisation" preference from off to on (this setting wasn't doing anything previously) and it worked.

Not sure if it was the latest update, or a recent update with toggling the "Auto-capitalisation" off and on again, but it worked.

**Comment by Zanthed** [comment]
We haven't made any changes to LatinIME (AOSP Keyboard) besides adding two new languages.

Are you sure the language is _not_ set to English US? We have a potential fix for spell check for languages _other_ than English US.

**Comment by snrkl** [comment]
@Zanthed interesting  (I assume LatinIME is for latin character sets, not actually for es-la languages) here are the screens: 
![Screenshot_20220403-105629](https://user-images.githubusercontent.com/2288035/161406731-cc4eeda5-f49e-4830-bced-c05b9df4acd0.png)
![Screenshot_20220403-105640](https://user-images.githubusercontent.com/2288035/161406735-fd81da39-5518-4e87-984d-0e127df4b03e.png)
![Screenshot_20220403-105654](https://user-images.githubusercontent.com/2288035/161406737-c329501d-f130-42f3-a178-a96037919581.png)
![Screenshot_20220403-105706](https://user-images.githubusercontent.com/2288035/161406741-f6af91ee-1445-43e2-b69a-e71142be8f68.png)
![Screenshot_20220403-105721](https://user-images.githubusercontent.com/2288035/161406744-a785d936-bc07-4b63-9dea-14b21c0cafdc.png)


Of note, I don't recall the Spell Check being English US previously...

**Comment by flawedworld** [comment]
This should be fixed now.
