### ISSUE TITLE
Graphene OS Certificates in non Root profiles

### ISSUE THREAD

**Issue by SeemsLogical** [GrapheneOS/os-issue-tracker#942]
I'm using Multiple Profiles on Graphene OS on a Pixel 6 Pro.  The Root user is basically stock with no extra applications installed.  I then have a a few user profiles for various applications.

In my "work" user I need to load another CA Certificate.

In the ROOT User I can seen Settings->Security->Encryption Credentials->Install a Certificate and load any certificate I need.

However in my other User profiles

Settings->Security->[Encryption Credentials] is not an option and I do not see a way to load our company's CA Certificate.

Any ideas how to add another CA Certificate to a non-root user profile?

**Comment by Zanthed** [comment]
This is normal behaviour and not a bug. The owner profile is responsible for stuff like network configuration and such. Not other profiles.

**Comment by thestinger** [comment]
We don't plan to change how this works.

**Comment by SeemsLogical** [comment]
If I may politely disagree on the status of it being a bug.   Before submitting this issue, I tried loading the company CA in the owner profile but that CA is not trusted in the other user profiles.  So while I can load a CA Certificate, I cannot use anything but the native CA Certificate in user profiles.  That's a significant limitation and why I say bug.  This could be resolved by either 1) (less secure) allowing the owner profile CA Certificates to be accepted by all user profiles or 2) and perhaps considered more secure, allow user profiles to load CA Certificates for their profile specific use.

**Comment by Zanthed** [comment]
You need to confirm if this same behaviour happens on stock OS. If you can't add/use your company CA in other profiles, then we're not going to change how it works because it's intended. You can file this upstream to AOSP, otherwise this is exactly how it's meant to work and will not be changed.

**Comment by Zanthed** [comment]
This isn't a bug if this is how it works on stock OS.

**Comment by thestinger** [comment]
It's definitely not a bug. It was initially a support question and now it's a feature request. Importing a CA roots is a legacy feature that's being largely phased out over time. We're not going to extend support for it to secondary users. If Android adds support for it then we won't remove it but we don't consider this a desirable feature in the first place. Nothing should be expecting you to import root certificates. Why do you want it in the first place? It increasingly doesn't work because apps default to ignoring non-system roots. Browsers currently opt into trusting non-system roots but we may remove that for Vanadium and people could use another browser if they want it.

**Comment by Zanthed** [comment]
You need to figure out with your company why you need to import a root certificate and the use-cases for it that require you to import one. Otherwise, get yourself an actual work phone.

**Comment by SeemsLogical** [comment]
@Zanthed We have our own Certificate Authority for our own internal network and applications.  We are a bunch of network and security admins and see no reason to buy publicly recognizable CA Signed certificates for our non-public internal applications, but I see now this is not an issue specific to GrapheneOS.   Oops! Forgiveness everyone.   Thanks for all your hard work on this project and rapid responses. It's much appreciated.
