### ISSUE TITLE
Matrix Community

### ISSUE THREAD

**Issue by Yehuda1927** [GrapheneOS/os-issue-tracker#948]
Sorry for the silly question, but I am new to the whole GrapheneOS community and will be flashing my first Pixel 6 Pro later this week. When I asked a question, I was told to post in the the Matrix Community. Sorry, but what is that and how do I navigate to it? Thanks in advance.

**Comment by flawedworld** [comment]
See: https://grapheneos.org/contact#community

**Comment by Yehuda1927** [comment]
Thank you.

------- Original Message -------
