### ISSUE TITLE
Support fs-verity on Play Store and GrapheneOS App repository apps

### ISSUE THREAD

**Issue by flawedworld** [GrapheneOS/os-issue-tracker#949]

**Comment by flawedworld** [comment]
For Play Store, we should just need to extract certificates from the stock OS. For the GrapheneOS store we need to ship our own certificate and provide apks with fs-verity metadata.

**Comment by r3g-5z** [comment]
This is done for Apps app.

**Comment by thestinger** [comment]
Play Store fs-verity key is potentially already included in the OS if it's the same key they use for the CTS. Not entirely clear to be. APK signing v4 appears to be a separate thing.

**Comment by r3g-5z** [comment]
Play Store fs-verity certs are removed in https://github.com/GrapheneOS/adevtool/blob/13/config/common/file-removal.yml#L303-L304

**Comment by thestinger** [comment]
It seems to be included via AOSP anyway.

**Comment by thestinger** [comment]
fsverity-release.x509.der

**Comment by thestinger** [comment]
I'm not sure if that's even used at all by the Play Store. It may only be used by CTS...

**Comment by developernadeem** [comment]
I have build a custom GrapheneOS and I have add a presigned apk into it. How can I update apk while fs-varity is enforced?

**Comment by thestinger** [comment]
Add an fs-verity public key for your app to the OS in build/make as we did and sign your app.

**Comment by developernadeem** [comment]
Can you please elobrate a bit more? How to generate and these new keys and what schema ( v2, v3 or v4) should I use for signing? fsverity-release.x509.der seems already there under  build/make/target/product/security.

**Comment by thestinger** [comment]
Look at our apps.grapheneos.org repository. You need to add a new key, not replace the existing ones.

**Comment by developernadeem** [comment]
So if i sign the app with platform keys, I don't need this step? As I see platform keys are already over there.

**Comment by thestinger** [comment]
No. You need to do what I said.

**Comment by developernadeem** [comment]
Can you please define the steps for creating key and signing process? I’m kind of stuck. I shell be very thankful to you.

**Comment by thestinger** [comment]
It's in the apps.grapheneos.org repository.

**Comment by developernadeem** [comment]
Unfortunately I couldn’t find any guidance in the repository 😓

**Comment by developernadeem** [comment]
I found it thank, can you please guide through signing apk as well?
My undersatanding is to use 
apksigner sign 
  --key key.pem --cert cert.pem
  [signer_options] app-name.apk

**Comment by developernadeem** [comment]
Can you please guide? Im new to OS development? 
signig it with apksigner doesnt work

**Comment by thestinger** [comment]
Use the guide there. This is a separate thing from signing the APK.

**Comment by developernadeem** [comment]
I have followed the instructions and trying update app with ```.fsv_sig``` certs same as Apps repository but I'm not able to update the app. I have ```.der``` and ```.pem``` files under ```build/make/target/product/security```.

**Comment by thestinger** [comment]
> I have .der and .pem files under build/make/target/product/security.

You should never do this. That's not how it's done.

**Comment by thestinger** [comment]
Only the public key goes in the source tree. Look at our commit adding ours. You should never put your private keys into the source tree. Follow our OS build instructions and the app repository instructions. Signing apps is a separate thing from signing them with fs-verity keys and you need to do both correctly. This isn't a substitute for regular signing. Not able to provide further support here.

**Comment by developernadeem** [comment]
I understand it well now, I have followed the steps here https://github.com/GrapheneOS/platform_build/commit/33bf99094ed86ebdf177c9fc3309d5896a16896e , I have also generated the ```.fsv_sig``` using ```import-apks.py``` and ```generate.py``` . But I'm not able to isntall update by any mean. 
My Updater code looks like this 

```
val params = updateResponse.makeSessionParams(applicationContext)
                val pkgInstaller = applicationContext.packageManager.packageInstaller
                val id = pkgInstaller.createSession(params)
                pkgInstaller.openSession(id).use { session ->
                    FileInputStream(file).use { inputStream ->
                        session.openWrite("${updateResponse.packageName}.apk", 0, file.length())
                            .use { outputStream ->
                                inputStream.copyTo2(outputStream)
                            }
                    }
                    if (updateResponse.hasFsVeritySignatures) {
                        //download and write metadata for the package
                        FileInputStream(fsvFile).use { inputStream ->
                            session.openWrite("${updateResponse.packageName}.fsv_sig", 0, fsvFile.length())
                                .use { outputStream ->
                                    inputStream.copyTo2(outputStream)
                                }
                        }
                    }
                    session.commit(
                        createIntentSender(
                            applicationContext,
                            id,
                            updateResponse.packageName
                        )
                    )
                }
                
```

**Comment by thestinger** [comment]
Is the regular APK signature correct? If you're building and signing the app outside the OS it needs to be done as PRESIGNED or by using the same signing key for signing that specific APK for the OS signing.

**Comment by developernadeem** [comment]
Im using PRESIGNED keys and yes apk signing is correct.

**Comment by developernadeem** [comment]
I couldn’t find any resources on the internet so you are my last hope🧑🏻‍💻.

**Comment by developernadeem** [comment]
fs-verity: java.io.IOException: Failed to enable fs-verity on .. Required key not available. So Im ammusing the keys is not being added to keyring.
