### ISSUE TITLE
(Re-)Add support for arbitrary Unicode characters in filenames (= ext4 filenames)

### ISSUE THREAD

**Issue by codethief** [GrapheneOS/os-issue-tracker#952]
This is probably an upstream issue.

I used to be able to synchronize all my files from my Linux laptop (ext4 file system) to my Android (v9) phone using [Syncthing](https://syncthing.net). Now that I've switched to a phone with GrapheneOS / Android 12, however, syncing certain files to the phone's internal storage suddenly fails. More specifically, it's precisely those files whose name includes any of the Windows NTFS / FAT forbidden characters `":<>?|\*`. On top of that, it seems that filenames are no longer case-sensitive. (See [this post](https://forum.syncthing.net/t/clean-sync-to-new-device-does-not-work-and-stops-at-99/17698/12) on the Syncthing forums for all the details.) This seems to be a general issue (i.e. unrelated to Syncthing) because other apps, like text editors, which previously (on Android 9) handled characters like `:` and `?` in filenames just fine now also exhibit issues.

I therefore suspect that there there must have been a silent breaking change in the underlying Android APIs upstream, probably [this one](https://android.googlesource.com/platform/packages/providers/MediaProvider/+/6b7baf4b9722dd75bfb5d64acadf48223226cde6) in Android 11. To be honest, I find it mindboggling that they introduced such a breaking change without proper announcement. It's 2022, I haven't used Windows in more than a decade and I suddenly cannot sync ebooks to my phone anymore when their title includes a colon or a question mark?!

What would be the proper channel to address this? Should I direct my request to the Android devs or would you be open to offer advanced users an option in the developer settings to enable the full range of characters in filenames again? Given that Android internally uses ext4, I suppose such a change should only(?) involve disabling the check in the APIs (mentioned in the commit linked above) when writing to internal storage.

**Comment by flawedworld** [comment]
Upstream would need to sort this out.

**Comment by codethief** [comment]
@flawedworld Thanks for the quick response. I'll try that then. If that fails, would you be open to accepting a patch that lets advanced users enable the full range of characters in the developer settings?

**Comment by flawedworld** [comment]
This seems like it was intentionally done by upstream. If such a patch was made, dev time would need be invested into ensuring that rationale for upstream's change would not be reintroduced.
