### ISSUE TITLE
[Possible regression] Google Maps started requiring Google Location Accuracy for navigation after 2022013010 update

### ISSUE THREAD

**Issue by gordonel** [GrapheneOS/os-issue-tracker#953]
Device: Pixel 6 Pro
After installing 2022013010 update, Google Maps started requiring to turn on Google Location Accuracy to use navigation on a profile with Sandboxed Play Services. This wasn't the case on the previous build. Not really sure what to make of it
![screenshot](https://user-images.githubusercontent.com/45173186/152037538-d72f52a3-118f-4baf-a202-6b7c86de7ad7.jpg)

**Comment by flawedworld** [comment]
Nothing to do with it
