### ISSUE TITLE
Force Enable VOLTE Provisioning

### ISSUE THREAD

**Issue by bloomiz** [GrapheneOS/os-issue-tracker#954]
Users that use some carriers that aren't officially supported by Google can use VOLTE by force enabling VOLTE Provisioning.
(Since Android S Beta 4, VOLTE Provisioning is disabled by default for unsupported carriers.)
Some other OS/ROMs enabled it by default without modifying carrierconfig for debugging options.
This feature could make some Carriers use GrapheneOS without any system-level modification.
For some users that are using totally VOLTE unsupported carriers, this could be totally broken/useless feature. But for others who need this feature, They could use official GrapheneOS without security harmful actions(Unlock, Root, System modification).

Thanks for watching my issue and sorry for my bad english.

**Comment by thestinger** [comment]
We can't force enable it by default. It would be broken across many carriers and would cause a major issue. There could be a toggle to force it but we already have compatibility as broad as the stock OS and carriers should be interested in getting that working already.

**Comment by bloomiz** [comment]
Thank you for the reply @thestinger 

So, Is there any plans to add the force toggle to the next releases?
If not, How Can I use GrapheneOS with VOLTE?

I think enabling debugging preferences on build level could be a security concern.

**Comment by Zanthed** [comment]
VoLTE already works just fine with GrapheneOS. 
If it's not working your carrier doesn't support it or they have a problem with it.

This force VoLTE provisioning thing is a pure hack, something that should only be used as a temporary bandaid, and is something you should really just figure out with your carrier.

**Comment by flawedworld** [comment]
Closing in favour of something like https://github.com/GrapheneOS/os-issue-tracker/issues/956 which would make more sense.
