### ISSUE TITLE
Feature request: Integrate a configuration tool for a second/work profile

### ISSUE THREAD

**Issue by noseshimself** [GrapheneOS/os-issue-tracker#955]
I'm currently using Shelter to restrict certain (Google Play requiring) apps I need to be running unless I want to carry a second phone around.

Shelter has several disadvantages (including having to stand on your head reciting ancient Greek lyrics to set up/restrict the Google play services in that partition -- especially the tracking functions like sending location data to Google).

Would it be possible to integrate management of the second partition into Graphene and its tools (and maybe even have more than one?) with "tools" including anything that is contained in the setting up which is needed in the work profile to get Google stuff under control?

[remove this if I missed the obvious]

**Comment by flawedworld** [comment]
We won't be adding support for work profiles. We will likely add support for nested profiles and cross profile notifications in future. We will be adding support to SetupWizard in future to setup sandboxed Google Play Services and support in our App repo app once it is production ready.
