### ISSUE TITLE
Unable to receive SMS texts with RedPocket (Verizon MVNO)

### ISSUE THREAD

**Issue by LearningAsIGo71** [GrapheneOS/os-issue-tracker#958]
I saw this problem mentioned back in November with other Verizon MVNOs and the issue was closed. 

I'm using RedPocket (Verizon MVNO) and cannot receive any SMS texts. Sending texts works fine, but I cannot receive any texts. 

I'm using a Google Pixel 5a 5g with latest release of GrapheneOS. 

Steps taken to attempt fix: 

- Reset Wifi/Mobile/Bluetooth

- Turn off Roaming

- Had RedPocket reset my account and then manually inputted recommended APN settings. 

I do **not** experience the issue on my wife's Pixel 5 GrapheneOS phone which uses RedPocket with AT&T.

**Comment by flawedworld** [comment]
Please follow these instructions here: https://github.com/GrapheneOS/grapheneos.org/pull/331/files

**Comment by sawft99** [comment]
Sounds similar to my #908. Still had issues after all of that. Might try to reset SIM settings on my phone one last time. Curious to know if any of this ends up working for you.

**Comment by LearningAsIGo71** [comment]
Thanks for the reply. I attempted to follow the steps... unfortunately https://messages.google.com/disable-chats appears to be a dead link.

**Comment by LearningAsIGo71** [comment]
Disregard the above. The removing the "s" from chats in the link above provides a working link (note: the link needs to be corrected at https://github.com/GrapheneOS/grapheneos.org/pull/331/files ).

Nevertheless, the old phone is running Android 9 and when I go to Message settings it says "Chat feature unavailable for this device" so there is nothing to turn off. 

I'll look into deregistering my phone number from my carrier's RCS service. If that doesn't work I guess I'll request a new SIM.

**Comment by LearningAsIGo71** [comment]
RedPocket tech support acted as if they didn't know anything about deregistering the RCS service. They also said they will **not** send me a new RedPocket CDMA SIM because since I am able to receive SMS texts on my old phone using the SIM it proves their is nothing wrong with the SIM. 

Their only solution was to either:
1. Factory reset the phone (I didn't tell them I'm trying to get SMS to work on a fresh install of GrapheneOS) or 
2. Switch over to GSM by using a GSM SIM that they can issue me. 

Any other suggestions to try to resolve this issue on my Pixel 5a using RedPocket Verizon CDMA before I make the undesired switch to GSM? (I say undesired because I already have 3 phones in my household on AT&T GSM, and would like one on Verizon as an alternative in the event of a down AT&T network).

**Comment by flawedworld** [comment]
@LearningAsIGo71 Have you tried the SIM in the Pixel 5 device?

**Comment by LearningAsIGo71** [comment]
Okay, this is getting super bizarre. I stuck the SIM in the Pixel 5 running the latest GrapheneOS build and I could not get it to make or receive calls. When attempting to call the phone a message said it was not in service. 

But here's where it gets really bizarre: when attempting to make a call out to **any** number the call would get routed to some phone dating service! "Welcome to America's hottest talk line. Guys, hot ladies are waiting to talk to you. Press 1 now..."!! What is this craziness? 

I put the SIM back in the Pixel 5a and attempted to make a call and it patched into the same dating service! I then attempted make a call to the 5a and the incoming call went through. So after receiving the call, I then tried again to make an outgoing call and returned to working as normal... no more dating service nonsense. 

I put the SIM back in the Pixel 5 and got the same problem with calls getting routed to the dating service. 

Then I decided to try the SIM in an old Pixel 3XL running CalyxOS with Android 11 and everything works as it should. Incoming and outgoing calls as well as SMS texts all work fine.

**Comment by thestinger** [comment]
I'm having trouble taking this at face value now.

**Comment by thestinger** [comment]
https://www.miamiherald.com/news/nation-world/national/article174813321.html

**Comment by LearningAsIGo71** [comment]
So is it possible my SIM is compromised? 

I don't know why the SIM works in my old LG phone running factory Google Android 9, almost works with the GrapheneOS Pixel 5a (the exception being not able to **receive** SMS texts... and also discovered not able to **send** attachments via SMS), doesn't work at all on the GrapheneOS Pixel 5, but works as normal on an old Pixel 3XL running Calyx. 

With that said, I do **not** want anything to do with standard Google Android or with Calyx for that matter (Calyx is not updated regularly, has no sandboxed Play services, and is buggy [e.g. never get Signal notifications until I open up Signal, Florisboard swipe function randomly stops, etc]). 

I want to use GrapheneOS on all my devices, but not having the ability to use the RedPocket Verizon CDMA is not ideal. Not only do I want another cell carrier as a backup, but also for dead-zones. Sometimes when traveling in the USA Verizon works in certain areas AT&T does not, and vice versa. 

But if push comes to shove, I'll switch all my phones to RedPocket AT&T GSM so I can use GrapheneOS.

**Comment by LearningAsIGo71** [comment]
Just tried the SIM in an old stock Verizon Samsung S7 running Android 8 and calls and SMS texts work fine.

**Comment by flawedworld** [comment]
I think asking for a GSM SIM may be the easiest choice at the moment, and if you want to trial CDMA in future again, ask for a new CDMA SIM once you have used the GSM SIM for a bit.

**Comment by flawedworld** [comment]
I speculate that if you lie to support and say you have damaged the SIM so they send you a new CDMA SIM, you may have some luck. But no promises.

**Comment by sawft99** [comment]
I found [this](https://support.google.com/pixelphone/thread/123988298/pixel-5a-5g-won-t-connect-to-verizon-sim-card?hl=en), [this](https://www.reddit.com/r/GooglePixel/comments/pbmue8/pixel_5a_verizon_sim_data_working_but_not_calls/), and [this](https://www.reddit.com/r/GooglePixel/comments/pc6jx6/5a_on_verizon/).

Going to talk to Verizon and see if confirming RCS is off on their end and that the "CDM-less" feature is active.

**Comment by flawedworld** [comment]
@LearningAsIGo71 please try the above suggestions

**Comment by sawft99** [comment]
IT WORKED! Did it over chat with Verizon. They enabled the CDMA-less feature and I gave them the IMEI of my new phone (the 5a). Also gave them the CCID of the new SIM I got. It sounds like you were trying to stick your SIM in a new phone like I was so i told them I was trying to activate that new device. Took my SIM our of my current phone, turned it off, put it in my 5a, powered up, Verizon did their thing, rebooted 5a one more time. Calls and texts in both directions.

Bonus: I have a long time account with multiple people on it. They said our plan was "set to 4g" which seems to just mean you can only use up to 4g technology. They enabled/switched/upgraded it to a 5g plan at no additional cost.

**Comment by flawedworld** [comment]
Nice.

**Comment by LearningAsIGo71** [comment]
After much back and forth I finally found a competent RedPocket tech support agent who was able to get my phone working by enabling CDMAless on the Pixel 5a. It finally is able to send and receive texts on the Verizon network! What a load off my shoulders!

Nevertheless, I am still disturbed by what happened when I put the SIM in my wife's GrapheneOS Pixel 5. Why in the world would it route to a phone dating service? Is it possible the phone is compromised? I bought it used on eBay factory reset and then installed GrapheneOS on it. It works flawless with RedPocket GSMA SIM, so I don't know what's up, but it is troubling.

**Comment by thestinger** [comment]
No, it's not compromised and there's no reason to think that. It's a carrier issue.

**Comment by thestinger** [comment]
It's not 'troubling' at all.

**Comment by LearningAsIGo71** [comment]
So the carrier routing all my calls to an adult phone service is not troubling? I beg to differ. This is completely different than what happened in the FEMA example you referenced above. In that case people were simply dialing the wrong number. In my case all the calls made on the Pixel 5 using the CDMA SIM get routed to the adult service. And why would it only happen on the Pixel 5? Something is seriously amiss.

**Comment by sawft99** [comment]
> So the carrier routing all my calls to an adult phone service is not troubling? I beg to differ. This is completely different than what happened in the FEMA example you referenced above. In that case people were simply dialing the wrong number. In my case all the calls made on the Pixel 5 using the CDMA SIM get routed to the adult service. And why would it only happen on the Pixel 5? Something is seriously amiss.

There's a 99.9% chance you're phone is fine. If you're that concerned format the graphene phone. If it's still a problem then it's a carrier issue.
