### ISSUE TITLE
Would absolutly LOVE the ability to create folders in the app drawer to make it less cluttered while not downloading a 3rd party launcher.

### ISSUE THREAD

**Issue by MoldyTaint** [GrapheneOS/os-issue-tracker#960]
Would absolutly LOVE the ability to create folders in the app drawer tomake it less cluttered while not downloading a 3rd party launcher.

**Comment by thestinger** [comment]
@Zanthed We can move issues but I'm unsure if you have the privilege for it. Do you need a transfer issue option?

**Comment by thestinger** [comment]
@MoldyTaint I strongly recommend setting up the home screens with every single app you have in a sensible arrangement including folders if desired. You can probably fit it all on one screen if you use folders. App drawer isn't intended to be used regularly once you've customized the phone. Every app you normally use should be on the home screen. It's a different approach than an iPhone and I think that's fine. App drawer is the all programs menu.

**Comment by Zanthed** [comment]
@thestinger I'm not in the organisation so I don't have any permissions.
