### ISSUE TITLE
[Pixel 6] Phone screen wakes when moved even when "lift to check phone" is disabled everywhere in settings.

### ISSUE THREAD

**Issue by Misterk267** [GrapheneOS/os-issue-tracker#965]
Phone: Pixel 6
Build: SQ1D.220105.007.2022013120 (latest beta as of 02/07/2022)
Sandboxed google play active

Steps to reproduce: 

1. Disable "lift to check phone" in gesture or lock screen settings
2. Lock the phone, wait 5 seconds
3. Move or bump the phone. The darkened screen that displays time and notifications will activate for a few seconds

Other information:
I also have "tap to check phone," "always show time and info" disabled, and lockscreen set to not display any notifications. I am unsure if this could be a contributing factor.

**Comment by thestinger** [comment]
This is expected because you have fingerprint enabled.
