### ISSUE TITLE
Unable to start a Hotspot

### ISSUE THREAD

**Issue by ihateandroid12** [GrapheneOS/os-issue-tracker#966]
System info:
- Google Pixel 3XL
- Android 12

I am unable to start a hotspot on my device, I already attempted to reset networking settings but it didnt fix my issue. My settings app is constantly freezing and I just get a "WiFi error" upon attempting to start my hotspot. The video shows my issue.

**Comment by ihateandroid12** [comment]
It seems my video didnt append?

Heres the video: https://files.catbox.moe/srxwmu.mp4

**Comment by Zanthed** [comment]
What is your carrier version? Settings -> Network and Internet -> SIMs -> Operator settings version

**Comment by Zanthed** [comment]
This is likely a hardware issue and is not actually related to carrier stuff.
