### ISSUE TITLE
Please revert #840

### ISSUE THREAD

**Issue by BayLee4** [GrapheneOS/os-issue-tracker#969]
Please, please revert #840 as the end result looks like some kind of broken high contrast theme was just installed.

**Comment by flawedworld** [comment]
We aren't changing them.

**Comment by BayLee4** [comment]
@flawedworld So bad, this is just hideous.

**Comment by Zanthed** [comment]
You'll get over it. The icons need to be changed. They were legacy bitmaps with no adaptive support and needed to be changed.

**Comment by BayLee4** [comment]
@Zanthed I would gladly update the old icons to a more suitable format if that can bring them back. Those new icons are just ugly and completely contrast with _any_ other application installed.

**Comment by Zanthed** [comment]
We're not changing them. They needed a consistent and modern style.

**Comment by BayLee4** [comment]
This is neither consistent nor modern.

**Comment by BayLee4** [comment]
At least change the white backgound to the old colors.

**Comment by camoz** [comment]
By the way this also has accessibility implications for people with bad eyesight.

And it's kind of unergonomic and therefore worse UX than before (human beings can distinguish colors and are used to identify objects using that distiction). It's not just about aesthetics.

Also, a bit discussion would be nice instead of immedieately closing the issue.

**Comment by motivemachine** [comment]
> We're not changing them. They needed a consistent and modern style.

I look forward to seeing such a style. This isn't it. It doesn't look good, and it looks even worse amid all the other non-OS app icons next to them.

**Comment by thestinger** [comment]
We can implement https://github.com/GrapheneOS/os-issue-tracker/issues/970 to switch to the rounded Material icons from the sharp Material icons. We want to have consistent GrapheneOS branding for our apps similar to how other collections of apps have their own color schemes. Android is moving towards allowing users to choose the OS color scheme which will be in AOSP with Android 12.1. Setting an icon color scheme and style is something they're working on. We really needed to move on from the legacy bitmap icons to adaptive icons especially with support for icon color schemes on the horizon. We aren't going to move back to the legacy low resolution AOSP bitmap icons and we don't like their inconsistent and quite badly aged designs. It's not constructive to demand that we revert this. If you have a better idea on what our icons should look like and are willing to put in the work across all the apps with icons including the ones without launcher icons, then work on that is welcome. It should have a consistent style and set of colors across them. It could look more like the Vanadium icon but that's going to have to change soon too when Chromium finally has an adaptive icon.

**Comment by BayLee4** [comment]
@thestinger You're confusing 'consistent set of colors' with 'bichromatic'.

The first one would have been choosing a color scheme (Pastel, Warm, Cold, Nord, Dracula...), and the second one is what we have now: a bad UX and look. As far as I know Pixel phones don't have e-Ink displays, there's really no point in using these black and white colors, as it's also easy to confuse applications based on their looks like @camoz noted.

If the team is open to discussion, which somewhat wasn't apparent in this thread, I would like to suggest using the 'old' background colors of application (Blue, Dark blue, Cyan...) to easily differentiate them. Wether or not creating an 'official' GrapheneOS color scheme to choose colors from it could also discussed. But as the current `#000000` black and `#FFFFFF` white don't qualify as color scheme either, it should come in a later point. On a side note, I'm also favorable for #970, even if it doesn't address the main concern regarding the colors.

**Comment by thestinger** [comment]
The icons are not designed in a way where there are more than 2 colors per icon, and we want a consistent set of colors across icons. As I said it would be fine if they looked more like the Vanadium icon but we don't plan on designing that kind of thing for each of the apps. There aren't many of these apps and the icons are quite distinct between them. The OS already uses these same kinds of icons all over the place in much smaller sizes without having a bunch of colors. I don't buy into your argument. You don't like how it looks and you're trying to justify that. It's not a valid use of the issue tracker regardless. This isn't a place to ask us to revert subjective aesthetic changes. So yeah, we are not open to this here and you'll be banned if you continue.
