### ISSUE TITLE
Consider using Material Rounded icon style rather than Sharp for new app icons

### ISSUE THREAD

**Issue by jorgeluiscarrillo** [GrapheneOS/os-issue-tracker#970]
The new material app icons use the sharp icon style which looks quite aggressive and clashes with the modern rounded UI style of the OS. Additionally, the Camera app uses the rounded icon style so there is some inconsistency.

I am proposing that we change some or all of the new icons to use the Rounded icon style.
It can be argued that we should stick with the sharp style for some apps like PDF Viewer and Gallery since we usually associate a picture or a page as "square". However, I will leave it to the developers to decide if we should stay consistent or to pick and choose.
![material_rounded_icons_comparison](https://user-images.githubusercontent.com/33134232/153084450-dab5e3a2-2927-43eb-b44b-3a1a4906945b.png)

**Comment by thestinger** [comment]
I think it would make sense to switch all of them to rounded. I wouldn't want to switch only some of them.

**Comment by Zanthed** [comment]
Next release and next releases of our apps will now have all rounded icons.
