### ISSUE TITLE
Connect to WiFi Issue when no certificate is needed for Phase 2 Autentication

### ISSUE THREAD

**Issue by LramirezP** [GrapheneOS/os-issue-tracker#971]
When you try to connect a network by TTLS with MSCHAPV2 authentication it always requires specifying the CA certificates (either "User system certificates" or "Install certificates"). There should be another option stating "No CA certificate is required" as if there is no way of setting the certificate you cannot connect to the network. Meaning, that if you do not choose an option for the certificate, the connection button never gets enabled

Here I attach an image of the part of the configuration I am talking about and a screenshot of how the connection setting is done in PopOS. I have also seen the option on regular Android but I don't have one at the moment.

![signal-2022-02-09-113938_001](https://user-images.githubusercontent.com/95030001/153182499-8383e5c4-ffde-4e62-b76f-48ba25a5924f.png)
.

![image](https://user-images.githubusercontent.com/95030001/153182613-d28a855e-f45f-4dfd-91a4-ae2257a978d8.png)

**Comment by Zanthed** [comment]
Don't think this is something we can implement ourselves and would have to be solved upstream.

**Comment by flawedworld** [comment]
Consult with the helpdesk of your organization. This is how Android 12 works.

**Comment by Zanthed** [comment]
https://www.xda-developers.com/android-11-break-enterprise-wifi-connection/

This is actually intended and not something we can do.
