### ISSUE TITLE
"No SIM card - Emergency Calls Only" after latest update

### ISSUE THREAD

**Issue by Luch3ro** [GrapheneOS/os-issue-tracker#975]
Updated to build SP1A.210812.016.C1.2022020800 on Pixel 3 XL and began receiving "No SIM card" error. Unable to make calls or send/receive SMS. I realize 3 XL is on extended release support, am planning to upgrade phone soon, but phone right now is able to browse via WiFi and nothing else.

**Comment by flawedworld** [comment]
It's either a hardware failure or Google broke your carrier.

**Comment by Luch3ro** [comment]
Thus happened once within the last year, but was able to go into the Testing menu via *#*#4636#*#* and change the preferred network to fix. Doing the same now, my preferred network choice does not persist. I have re-seated the SIM card, uninstalled the carrier's app, and booted into safe mode to see if the preferred network change would persist, all unsuccessful. When I go into Settings->Network and Internet, the Calls & SMS and SIMs menus are grayed out.

**Comment by Kem74** [comment]
Did you figure it out eventually or rebuild the phone?

**Comment by Luch3ro** [comment]
I bought a newer Pixel that is supported. I think the old phone went out of
official support.
