### ISSUE TITLE
Battery Optimization app list cuts off

### ISSUE THREAD

**Issue by Nairou** [GrapheneOS/os-issue-tracker#976]
When viewing "All Apps" in the Battery Optimization list, scrolling to the bottom shows the very last item cut off, hiding below the navigation row.

Edit: Pixel 6

![photo_2022-02-10_08-52-57](https://user-images.githubusercontent.com/942190/153421659-617fe659-39fb-4f3b-b00c-27381eb53629.jpg)

**Comment by jorgeluiscarrillo** [comment]
I can't find the UI for this anymore in Settings, not sure if it was removed or what. Consider closing this.

**Comment by thestinger** [comment]
It might be gone due to background restriction toggle being merged into this as a 3rd mode.
