### ISSUE TITLE
contacts doesn't support vCard v4.0.

### ISSUE THREAD

**Issue by zee0** [GrapheneOS/os-issue-tracker#977]
protonmail exports addresss book entries to vCard v4.0. importing to grapheneos contacts results in an error: "couldn't import vCard, the format isn't supported."

vCard v3.0 works fine, and in practice if i do `sed -i '/VERSION:4.0/c\VERSION:3.0' protonContacts.vcf` the import is successful.

**Comment by Zanthed** [comment]
Next release will support basic importing for vCard 4.0.

https://github.com/GrapheneOS/platform_packages_apps_Contacts/commit/641ead721d59c719f6efbbfeb3ed842e269a4a6f

**Comment by helgator** [comment]
vCard v4.0 still does not work as of today - just reporting.

**Comment by flawedworld** [comment]
You can import vCard 4.0 but not all vCard 4.0 data is supported. @helgator

**Comment by percivallo** [comment]
I exportet my contacts from Fairphone-Android and the version tag was "2.1"
After editing in Thunderbird the version tag was gone so I had to reintroduce it in text editor. But 2.1 would not work for import in GrapheneOS contacts.
Had to edit the file again in text editor and replace 2.1 by 3.0 to make it work. 
If the import function could do that automatically it would have saved a lot of time and hassle.
