### ISSUE TITLE
App not working with sandboxed Play Services: Capital One

### ISSUE THREAD

**Issue by Nairou** [GrapheneOS/os-issue-tracker#980]
Tested in a profile with Play Services, and in a profile without. In both cases, app opens to a blank white screen and doesn't respond.

Strangely, the app works fine in LineageOS/DivestOS (without microG).

App Manager shows that the app uses Firebase and Mobile Ads (GMS).

The app also has barcode scanning capability (may be related to #838) however the current issue is not directly with any barcode scanning page.

**Comment by Nairou** [comment]
_(First time using logcat, let me know if you want different results)_

Log results, filtered to "capitalone":
[logcat.txt](https://github.com/GrapheneOS/os-issue-tracker/files/8043269/logcat.txt)

**Comment by h4xor666** [comment]
FWIW Capital One works fine for me, even on a profile without Google Play Services.

**Comment by Nairou** [comment]
> FWIW Capital One works fine for me, even on a profile without Google Play Services.

How did you install it? Can you tell what version you have?

I was certainly surprised when it didn't work for me, since I had it work fine previously on another device without Play Services.

**Comment by h4xor666** [comment]
> > FWIW Capital One works fine for me, even on a profile without Google Play Services.
> 
> How did you install it? Can you tell what version you have?
> 
> I was certainly surprised when it didn't work for me, since I had it work fine previously on another device without Play Services.

Whatever the most recent version is, I installed from Aurora store. Where did you install from?

**Comment by Nairou** [comment]
> Whatever the most recent version is, I installed from Aurora store. Where did you install from?

I'm about to try with Aurora Store. I had installed it from the Play Store, in a secondary profile with Play Services. I also tried copying the apk to my main profile without Play Services, and had the same issue there.

**Comment by h4xor666** [comment]
> > Whatever the most recent version is, I installed from Aurora store. Where did you install from?
> 
> I'm about to try with Aurora Store. I had installed it from the Play Store, in a secondary profile with Play Services. I also tried copying the apk to my main profile without Play Services, and had the same issue there.

Roger that. Let us know what you find out!

**Comment by Nairou** [comment]
Okay, Aurora Store worked. Capital One is running fine without Play Services.

1. Installed via Play Services (second profile)
2. Opened app, launched fine
3. Backed up APK file, copied to owner profile (no Play Services)
4. Installed APK using SAI
5. Opened app, blank screen
6. Uninstalled app, re-installed via Aurora Store
7. Install succeeded, which means the APK was identical
8. Open app, it runs normally

No idea what step is at fault, I've done this process for many other apps. I guess there's no real issue here! :facepalm:

**Comment by pushkin-** [comment]
FWIW, I'm also seeing Capital One crash on startup. Tried installing with Google Play Store and with Aurora Store.
