### ISSUE TITLE
GrapheneOS reconnects to wifi if you do "nmap -sV" scan

### ISSUE THREAD

**Issue by EthOverFlow** [GrapheneOS/os-issue-tracker#987]
If I scan my Pixel 6 with Graphene OS from my Arch Linux Distro with "nmap -sV x.x.x.x" two or three times, than my Pixel 6 disconnects from the wifi and reconnects again. I wrote a script which scans all IPs in my network with "-sV" all the time an was able to kick my Pixel 6 most of the time out of the wifi network. 

Maybe somebody can explain that to me.

Regards, Alex

**Comment by thestinger** [comment]
Sounds like an issue with your Wi-Fi network. No indication of any issue with the OS.

**Comment by EthOverFlow** [comment]
No its with no other device and I tried it with another router. Its 100% GrapheneOS!
