### ISSUE TITLE
Sandboxed Google Play Services not correctly providing HomeAssistant with location

### ISSUE THREAD

**Issue by Nalydmerc** [GrapheneOS/os-issue-tracker#990]
Disclaimer: I'm trying to figure out if this is an issue with the HomeAssistant app, or the Google Play Services Sandbox layer, so let me know if I have this wrong, or if this report is misplaced. I'm a firmware developer by trade, but not an app or android developer, so bear with me as I try my best to figure out what's going on here. It's unfortunate that HomeAssistant requires Google Play Services for its location features, but it is what it is.

Device: Pixel 5
Google Play Services Sandbox installed.
No separate profiles, right now everything is installed on the Owner profile.

I'm using the HomeAssistant App (the full, google play store version that requires Google Play Services) with my own server and am trying to get location tracking to work. The location updates are not working and in the HomeAssistant app logs I see the following:

```
02-16 17:26:20.963  4187  4837 W GooglePlayServicesUtil: io.homeassistant.companion.android requires the Google Play Store, but it is missing.
02-16 17:26:20.963  4187  4837 W GoogleApiManager: The service for com.google.android.gms.internal.location.zzaz is not available: ConnectionResult{statusCode=SERVICE_INVALID, resolution=null, message=null}
```

I have tried this with and without the "Reroute location requests to the OS APIs" option enabled.
I've made sure HomeAssistant has any and all location permissions it needs. When it tries to get my location, I can see the green location notification dot and it says that HomeAssistant is using my location.
When the reroute option was disabled, I made sure Google Play Services had the appropriate location permissions.

**Comment by thestinger** [comment]
Did you install the app before getting Play services and the Play Store? Reinstall the app if that's the case. Do you have the Play Store installed and working? GSF + GMS is not always enough for apps.

**Comment by thestinger** [comment]
Please try again with the latest release (currently in Beta) after making sure you have Play services and the Play Store working correctly along with making sure you installed the app afterwards.

**Comment by Nalydmerc** [comment]
I did have Google Play Services and Google Service Framework installed before installing HomeAssistant. I do not have the Google Play Store installed (I downloaded the app via the aurora store), it that required for some location services? Other apps that use location services/notifications (Google Maps, Discord) work correctly, however some throw errors with varying severity (Lyft, Doordash).

I updated to the latest beta and can confirm the issue is still present.

I got location tracking in HomeAssistant working with NextTracks (+1 for open source solutions and integrations) so this is not a huge issue. However if it is helpful to development in any way I can provide logs or whatever information is needed to assist in debugging. Don't want to waste your time if it's not needed though, just depends on what you want.

**Comment by thestinger** [comment]
You should install the Play Store. It provides Play Asset Delivery, Play Feature Delivery and other features used by apps. It isn't a prerequisite for Google Play services geolocation to work but it may be required by this app to work properly.

**Comment by thestinger** [comment]
Those services it provides to other apps should mostly work without logging into an account. You can use a throwaway account similar to how Aurora Store uses a throwaway automatically if you want.

**Comment by kantlivelong** [comment]
@Nalydmerc did you ever get this working?

**Comment by Nalydmerc** [comment]
@kantlivelong Not with HomeAssistant, but I did get location reporting working with [NextTracks](https://fossdroid.com/a/nexttracks.html). It works on GrapheneOS, wasn't too much extra configuration, and it works just fine with HomeAssistant.

**Comment by thestinger** [comment]
The issue appeared to have been caused by not having the Play Store. It's not an optional component of Google Play. Google Play services depends on Google Play Store whether or not you use the Play Store to install apps.
