### ISSUE TITLE
Not able to access compatibility layer settings when installed in work profile

### ISSUE THREAD

**Issue by guga14** [GrapheneOS/os-issue-tracker#992]
I have the Google play compatibility layer installed in the work profile and when I click to open the settings in Settings > Apps it redirects me to the website as if it wasn't installed, making me unable to access the settings at all.

**Comment by thestinger** [comment]
Those are the settings for outside the work profile.

**Comment by guga14** [comment]
Well I know that, but I can't find a way to access the work profile
settings. In some places, inside de normal profile settings, there is a tab
for the work profile, but in this case, as soon as I click, it redirects to
the website automatically, without giving me the option to change to the
work profile tab

Daniel Micay ***@***.***> escreveu no dia quinta, 17/02/2022
à(s) 21:39:
