### ISSUE TITLE
change the clock app icon

### ISSUE THREAD

**Issue by gosreport** [GrapheneOS/os-issue-tracker#995]
current icon

![alarm.jpg](https://user-images.githubusercontent.com/99921949/154591550-e858fbc6-2c59-447b-923a-c1e60e90d87e.jpg)

suggested icon

![clock.jpg](https://user-images.githubusercontent.com/99921949/154591576-777770d6-2994-4eb0-9798-aad927463cf8.jpg)

reason:

the current icon displays an alarm, this suggests that the clock app is mainly used as an alarm app

the suggested icon above does a better job representing the clock app and the icon is more generic

**Comment by thestinger** [comment]
This has already been implemented in the new release (https://grapheneos.org/releases#2022021721).
