### ISSUE TITLE
gallery app improvements

### ISSUE THREAD

**Issue by gosreport** [GrapheneOS/os-issue-tracker#996]
- the top left icon is the previous gallery app icon
suggestion: replace this with the current icon

- the settings button does nothing
suggestion: remove the button

- the app is outdated

![Screenshot_20220217-161708.png](https://user-images.githubusercontent.com/99921949/154593538-6ef446a6-e18e-4700-889c-443b8fde99f1.png)

![Screenshot_20220217-161718.png](https://user-images.githubusercontent.com/99921949/154593544-0c156828-8d53-4cfa-8b31-a93ba09e55c5.png)

**Comment by thestinger** [comment]
https://github.com/GrapheneOS/os-issue-tracker/issues/48

**Comment by Zanthed** [comment]
Going to close this in favour of https://github.com/GrapheneOS/os-issue-tracker/issues/48

We're aware AOSP Gallery is extremely outdated and horrible UI/UX, however it's not something we can just remove due to it providing core functionality, CTS tests, etc.
