### ISSUE TITLE
remove top gradient from homescreen

### ISSUE THREAD

**Issue by CaqCat** [GrapheneOS/os-issue-tracker#997]
![gradient.png](https://user-images.githubusercontent.com/99921949/154758107-483017dc-c049-40a2-b16d-cc246cade81b.png)

(screenshot was edited to make the gradient more visible)

remove the gradient or add a setting to enable or disable it

in my opinion the gradient mimics screen burn in and has no place being there

**Comment by smdyv** [comment]
Resolved since release [2022091400](https://grapheneos.org/releases#2022091400)

https://github.com/GrapheneOS/platform_packages_apps_Launcher3/pull/8
