### ISSUE TITLE
system navigation bar bug

### ISSUE THREAD

**Issue by gosreport** [GrapheneOS/os-issue-tracker#998]
this bug occurs every time the phone is rebooted with gesture navigation enabled.

after the phone reboots, the navigation bar takes up the space used when the 2-button or 3-button navigation are enabled.

this bug is fixed when switching from the 2-button or 3-button navigation to the gesture navigation.

this bug occurs on the pixel 4a.

![before.jpeg](https://user-images.githubusercontent.com/99921949/154765274-2f7a8fa8-73fd-47a9-bdeb-fabef96df2ac.jpeg)

![after.jpeg](https://user-images.githubusercontent.com/99921949/154765283-fcfc549f-bbd6-4d52-99aa-c34077f02ec4.jpeg)

**Comment by thestinger** [comment]
Filed as https://github.com/GrapheneOS/os-issue-tracker/issues/825 already.
